import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import { reconstructConversation, reconstructConversationMessage, reconstructConversationParticipant, type Conversation, type ConversationId, type ConversationMessage, type ConversationMessageId, type ConversationParticipant, type ConversationParticipantId } from "../domain/conversation.js";

type ConversationRow={id:string;company_id:number;channel:Conversation["channel"];state:Conversation["state"];created_at:string;updated_at:string;closed_at:string|null};
type ParticipantRow={id:string;conversation_id:string;participant_type:ConversationParticipant["type"];reference:string|null;created_at:string};
type MessageRow={id:string;conversation_id:string;sender_participant_id:string;direction:ConversationMessage["direction"];content:string;idempotency_key:string|null;assistant_execution_record_id:string|null;created_at:string};
const conversation=(row:ConversationRow):Conversation=>reconstructConversation({id:row.id as ConversationId,companyId:row.company_id,channel:row.channel,state:row.state,createdAt:row.created_at,updatedAt:row.updated_at,closedAt:row.closed_at});
const participant=(row:ParticipantRow):ConversationParticipant=>reconstructConversationParticipant({id:row.id as ConversationParticipantId,conversationId:row.conversation_id as ConversationId,type:row.participant_type,reference:row.reference,createdAt:row.created_at});
const message=(row:MessageRow):ConversationMessage=>reconstructConversationMessage({id:row.id as ConversationMessageId,conversationId:row.conversation_id as ConversationId,senderParticipantId:row.sender_participant_id as ConversationParticipantId,direction:row.direction,content:row.content,idempotencyKey:row.idempotency_key,executionRecordId:row.assistant_execution_record_id,createdAt:row.created_at});

/** Async core persistence only; the synchronous conversation runtime remains the active composition. */
export class AsyncConversationCorePersistence {
  public constructor(private readonly database:SqlDatabase) {}
  public async findConversation(context:WorkspaceContext,companyId:number,id:ConversationId):Promise<Conversation|null>{const rows=await this.database.query<ConversationRow>("SELECT c.* FROM conversations c JOIN companies co ON co.id=c.company_id WHERE co.workspace_id=? AND c.company_id=? AND c.id=?",[context.workspaceId,companyId,id]);return rows[0]?conversation(rows[0]):null;}
  public async createConversation(context:WorkspaceContext,value:Conversation):Promise<Conversation|null>{const result=await this.database.execute("INSERT INTO conversations(id,company_id,channel,state,created_at,updated_at,closed_at) SELECT ?,co.id,?,?,?,?,? FROM companies co WHERE co.workspace_id=? AND co.id=?",[value.id,value.channel,value.state,value.createdAt,value.updatedAt,value.closedAt,context.workspaceId,value.companyId]);return Number(result.rowsAffected)===1?this.findConversation(context,value.companyId,value.id):null;}
  public async createParticipant(context:WorkspaceContext,companyId:number,value:ConversationParticipant):Promise<ConversationParticipant|null>{const result=await this.database.execute("INSERT INTO conversation_participants(id,conversation_id,participant_type,reference,created_at) SELECT ?,c.id,?,?,? FROM conversations c JOIN companies co ON co.id=c.company_id WHERE co.workspace_id=? AND c.company_id=? AND c.id=?",[value.id,value.type,value.reference,value.createdAt,context.workspaceId,companyId,value.conversationId]);if(Number(result.rowsAffected)!==1)return null;const rows=await this.database.query<ParticipantRow>("SELECT p.* FROM conversation_participants p JOIN conversations c ON c.id=p.conversation_id WHERE c.company_id=? AND p.id=?",[companyId,value.id]);return rows[0]?participant(rows[0]):null;}
  public async createMessage(context:WorkspaceContext,companyId:number,value:ConversationMessage):Promise<ConversationMessage|null>{const result=await this.database.execute("INSERT INTO conversation_messages(id,conversation_id,sender_participant_id,direction,content,idempotency_key,assistant_execution_record_id,created_at) SELECT ?,c.id,p.id,?,?,?,?,? FROM conversations c JOIN conversation_participants p ON p.id=? AND p.conversation_id=c.id JOIN companies co ON co.id=c.company_id WHERE co.workspace_id=? AND c.company_id=? AND c.id=?",[value.id,value.direction,value.content,value.idempotencyKey,value.executionRecordId,value.createdAt,value.senderParticipantId,context.workspaceId,companyId,value.conversationId]);if(Number(result.rowsAffected)!==1)return null;const rows=await this.database.query<MessageRow>("SELECT m.* FROM conversation_messages m JOIN conversations c ON c.id=m.conversation_id WHERE c.company_id=? AND m.id=?",[companyId,value.id]);return rows[0]?message(rows[0]):null;}
  public async listMessages(context:WorkspaceContext,companyId:number,conversationId:ConversationId):Promise<readonly ConversationMessage[]>{return (await this.database.query<MessageRow>("SELECT m.* FROM conversation_messages m JOIN conversations c ON c.id=m.conversation_id JOIN companies co ON co.id=c.company_id WHERE co.workspace_id=? AND c.company_id=? AND c.id=? ORDER BY m.created_at,m.id",[context.workspaceId,companyId,conversationId])).map(message);}
}
