import { randomUUID } from "node:crypto";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { ProactiveActionRepositoryPort } from "../application/ports.js";
import { proactiveActionBounded, proactiveActionId, proactiveActionOperationId, proactiveActionPositive, proactiveActionTimestamp, type ProactiveAction, type ProactiveActionPolicy } from "../domain/proactiveAction.js";

export class ProactiveActionOperatorValidationError extends Error {}
export class ProactiveActionOperatorNotFoundError extends Error {}
export class ProactiveActionOperatorConflictError extends Error { public constructor(readonly code: string) { super(code); } }

export type ProactivePolicyProjection = { readonly enabled: boolean; readonly version: number };
export type ProactiveActionProjection = { readonly id: string; readonly conversationId: string; readonly intentKind: "follow_up"; readonly runAt: string; readonly state: string; readonly attemptCount: number; readonly safeReasonCode: string | null; readonly version: number; readonly createdAt: string; readonly updatedAt: string; readonly completedAt: string | null; readonly cancelledAt: string | null; };

export class ProactiveActionOperatorService {
  public constructor(private readonly actions: ProactiveActionRepositoryPort, private readonly clock: { now(): string }) {}
  public policy(context: WorkspaceContext, companyIdValue: unknown): ProactivePolicyProjection { const companyId = companyIdValueParse(companyIdValue); const policy = this.actions.findPolicy(context, companyId); if (!policy) throw new ProactiveActionOperatorNotFoundError(); return policyProjection(policy); }
  public updatePolicy(context: WorkspaceContext, actorId: string, companyIdValue: unknown, input: unknown): ProactivePolicyProjection { const companyId = companyIdValueParse(companyIdValue), command = policyCommand(input), result = this.actions.applyPolicy(context, companyId, { actorId, ...command, occurredAt: this.clock.now() }); if (result.kind === "applied" || result.kind === "replayed_applied") return policyProjection(result.policy); if (result.kind === "not_found") throw new ProactiveActionOperatorNotFoundError(); throw new ProactiveActionOperatorConflictError("proactive_action_conflict"); }
  public create(context: WorkspaceContext, actorId: string, companyIdValue: unknown, conversationIdValue: unknown, input: unknown): ProactiveActionProjection { const companyId = companyIdValueParse(companyIdValue), conversationId = bounded(conversationIdValue, "Conversation ID"), command = createCommand(input), scope = this.actions.resolveCreationScope(context, companyId, conversationId); if (!scope) throw new ProactiveActionOperatorNotFoundError(); const result = this.actions.createAction(context, companyId, { id: `pac_${randomUUID().replaceAll("-", "")}`, actorId, operationId: command.operationId, conversationId, whatsAppConnectionId: scope.whatsAppConnectionId, assistantProfileId: scope.assistantProfileId, assistantParticipantId: scope.assistantParticipantId, runAt: command.runAt, expectedAuthorityGeneration: scope.authorityGeneration, occurredAt: this.clock.now() }); if (result.kind === "created" || result.kind === "replayed") return actionProjection(result.action); if (result.kind === "not_found") throw new ProactiveActionOperatorNotFoundError(); if (result.kind === "policy_disabled") throw new ProactiveActionOperatorConflictError("proactive_actions_disabled"); if (result.kind === "service_window_closed") throw new ProactiveActionOperatorConflictError("whatsapp_service_window_closed"); throw new ProactiveActionOperatorConflictError("proactive_action_conflict"); }
  public list(context: WorkspaceContext, companyIdValue: unknown): readonly ProactiveActionProjection[] { const companyId = companyIdValueParse(companyIdValue); if (!this.actions.findPolicy(context, companyId)) throw new ProactiveActionOperatorNotFoundError(); return this.actions.listActions(context, companyId, 100).map(actionProjection); }
  public detail(context: WorkspaceContext, companyIdValue: unknown, actionIdValue: unknown): ProactiveActionProjection { const companyId = companyIdValueParse(companyIdValue), action = this.actions.findAction(context, companyId, actionId(actionIdValue)); if (!action) throw new ProactiveActionOperatorNotFoundError(); return actionProjection(action); }
  public cancel(context: WorkspaceContext, actorId: string, companyIdValue: unknown, actionIdValue: unknown, input: unknown): ProactiveActionProjection { const companyId = companyIdValueParse(companyIdValue), actionIdValueParsed = actionId(actionIdValue), command = cancelCommand(input), result = this.actions.requestCancel(context, companyId, actionIdValueParsed, { actorId, ...command, occurredAt: this.clock.now() }); if (result.kind === "cancelled" || result.kind === "replayed") return actionProjection(result.action); if (result.kind === "not_found") throw new ProactiveActionOperatorNotFoundError(); throw new ProactiveActionOperatorConflictError(result.kind === "send_started" || result.kind === "replayed_send_started" ? "send_started" : "proactive_action_conflict"); }
}
function companyIdValueParse(value: unknown): number { const parsed = typeof value === "string" && /^\d+$/.test(value) ? Number(value) : NaN; if (!Number.isSafeInteger(parsed) || parsed < 1) throw new ProactiveActionOperatorNotFoundError(); return parsed; }
function bounded(value: unknown, label: string): string { try { return proactiveActionBounded(value as string, label, 200); } catch { throw new ProactiveActionOperatorValidationError(); } }
function actionId(value: unknown): string { try { return proactiveActionId(value as string); } catch { throw new ProactiveActionOperatorNotFoundError(); } }
function exact(value: unknown, keys: readonly string[]): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as Record<string, unknown>).length !== keys.length || keys.some((key) => !(key in value))) throw new ProactiveActionOperatorValidationError(); return value as Record<string, unknown>; }
function policyCommand(input: unknown): { operationId: string; expectedVersion: number; enabled: boolean } { const value = exact(input, ["operationId", "expectedVersion", "enabled"]); try { if (typeof value.operationId !== "string" || typeof value.expectedVersion !== "number" || !Number.isSafeInteger(value.expectedVersion) || typeof value.enabled !== "boolean") throw new Error(); return { operationId: proactiveActionOperationId(value.operationId), expectedVersion: proactiveActionPositive(value.expectedVersion, "Expected version"), enabled: value.enabled }; } catch { throw new ProactiveActionOperatorValidationError(); } }
function createCommand(input: unknown): { operationId: string; runAt: string } { const value = exact(input, ["operationId", "runAt", "intentKind"]); try { if (typeof value.operationId !== "string" || typeof value.runAt !== "string" || value.intentKind !== "follow_up") throw new Error(); return { operationId: proactiveActionOperationId(value.operationId), runAt: proactiveActionTimestamp(value.runAt, "runAt") }; } catch { throw new ProactiveActionOperatorValidationError(); } }
function cancelCommand(input: unknown): { operationId: string; expectedVersion: number } { const value = exact(input, ["operationId", "expectedVersion"]); try { if (typeof value.operationId !== "string" || typeof value.expectedVersion !== "number" || !Number.isSafeInteger(value.expectedVersion)) throw new Error(); return { operationId: proactiveActionOperationId(value.operationId), expectedVersion: proactiveActionPositive(value.expectedVersion, "Expected version") }; } catch { throw new ProactiveActionOperatorValidationError(); } }
function policyProjection(value: ProactiveActionPolicy): ProactivePolicyProjection { return Object.freeze({ enabled: value.enabled, version: value.version }); }
function actionProjection(value: ProactiveAction): ProactiveActionProjection { return Object.freeze({ id: value.id, conversationId: value.conversationId, intentKind: value.intentKind, runAt: value.runAt, state: value.state, attemptCount: value.attemptCount, safeReasonCode: safeReason(value.safeReasonCode), version: value.version, createdAt: value.createdAt, updatedAt: value.updatedAt, completedAt: value.completedAt, cancelledAt: value.cancelledAt }); }
function safeReason(value: string | null): string | null { return value === null ? null : new Set(["whatsapp_service_window_closed", "assistant_assignment_changed", "authority_lost", "conversation_closed", "proactive_policy_disabled", "whatsapp_connection_unavailable", "whatsapp_binding_invalid", "proactive_retry_exhausted", "provider_permanent_failure", "uncertain"]).has(value) ? value : "proactive_action_unavailable"; }
