import { createHash } from "node:crypto";

export interface KnowledgeDocumentV2 { readonly id:string; readonly workspaceId:number; readonly companyId:number; readonly sourceId:string; readonly sourceRevisionId:string; readonly contentDigest:string; readonly normalizedText:string; readonly createdAt:string; }
export interface KnowledgeChunkV2 { readonly id:string; readonly documentId:string; readonly workspaceId:number; readonly companyId:number; readonly ordinal:number; readonly text:string; readonly normalizedText:string; readonly byteLength:number; readonly characterStart:number; readonly characterEnd:number; readonly sourceRevisionId:string; readonly contentDigest:string; }
export interface KnowledgeIndexV2 { readonly id:string; readonly workspaceId:number; readonly companyId:number; readonly sourceRevisionId:string; readonly documentId:string; readonly kind:"lexical"; readonly status:"building"|"ready"|"failed"; readonly chunkCount:number; readonly createdAt:string; readonly completedAt:string|null; }
export interface RetrievalContext { readonly text:string; readonly citations:readonly { readonly sourceRevisionId:string; readonly chunkId:string; readonly characterStart:number; readonly characterEnd:number; }[]; }
export const KNOWLEDGE_V2_CHUNK_BYTES=800; export const KNOWLEDGE_V2_CHUNK_OVERLAP_BYTES=120;
export function chunkUtf8Deterministically(text:string,maximumBytes=KNOWLEDGE_V2_CHUNK_BYTES,overlapBytes=KNOWLEDGE_V2_CHUNK_OVERLAP_BYTES):readonly {readonly text:string;readonly characterStart:number;readonly characterEnd:number}[]{if(!Number.isSafeInteger(maximumBytes)||maximumBytes<1||!Number.isSafeInteger(overlapBytes)||overlapBytes<0||overlapBytes>=maximumBytes)throw new Error("Knowledge V2 chunk limits are invalid.");const chars=Array.from(text),out:Array<{text:string;characterStart:number;characterEnd:number}>=[];let start=0;while(start<chars.length){let end=start,bytes=0;while(end<chars.length){const next=Buffer.byteLength(chars[end]!,"utf8");if(bytes+next>maximumBytes&&end>start)break;if(next>maximumBytes)throw new Error("A Unicode code point exceeds the Knowledge V2 chunk limit.");bytes+=next;end++;}out.push({text:chars.slice(start,end).join(""),characterStart:start,characterEnd:end});if(end===chars.length)break;let retained=0,nextStart=end;while(nextStart>start){const size=Buffer.byteLength(chars[nextStart-1]!,"utf8");if(retained+size>overlapBytes)break;retained+=size;nextStart--;}start=nextStart===end?end:nextStart;}return Object.freeze(out.map(chunk=>Object.freeze({...chunk})));}
export function knowledgeV2Id(prefix:"kdoc"|"kchk"|"kidx",value:string):string{return `${prefix}_${createHash("sha256").update(value).digest("hex").slice(0,32)}`;}
export function lexicalTerms(value:string):readonly string[]{if(typeof value!=="string")return Object.freeze([]);return Object.freeze(Array.from(new Set(value.normalize("NFKC").toLocaleLowerCase("en-US").match(/[\p{L}\p{N}]+/gu)??[])).filter(term=>term.length>1));}
