import { stripeBillingProviderCapabilities, type BillingCommercialOfferValidation, type BillingProvider, type BillingProviderResult, type BillingSubscriptionReadResult } from "../application/billingProvider.js";
import { providerEvidenceState, type ProviderEvidenceState } from "../domain/billing.js";

export interface StripeBillingProviderConfiguration { readonly secretKey:string; readonly apiBaseUrl:string; readonly timeoutMs:number; readonly allowedRedirectOrigins:readonly string[]; readonly providerHostedRedirects?:boolean; readonly apiVersion?:string; }
export type StripeFetch=(input:string,init:RequestInit)=>Promise<Response>;
export class StripeBillingConfigurationError extends Error {}
export function stripeBillingProviderFromEnvironment(environment:NodeJS.ProcessEnv=process.env,fetcher:StripeFetch=fetch):StripeBillingProvider { const secret=environment.STRIPE_SECRET_KEY?.trim(); if(!secret)throw new StripeBillingConfigurationError("STRIPE_SECRET_KEY is required when Stripe is configured."); const base=environment.STRIPE_API_BASE_URL?.trim()||"https://api.stripe.com", timeout=Number(environment.STRIPE_TIMEOUT_MS??"10000"), origins=(environment.STRIPE_ALLOWED_REDIRECT_ORIGINS??"").split(",").map(value=>value.trim()).filter(Boolean); if(!Number.isSafeInteger(timeout)||timeout<1||timeout>60_000)throw new StripeBillingConfigurationError("STRIPE_TIMEOUT_MS is invalid."); if(!origins.length)throw new StripeBillingConfigurationError("STRIPE_ALLOWED_REDIRECT_ORIGINS is required when Stripe is configured."); try { return new StripeBillingProvider({secretKey:secret,apiBaseUrl:base,timeoutMs:timeout,allowedRedirectOrigins:[...new Set(origins.map(origin=>{const url=new URL(origin);if(url.origin!==origin||url.protocol!=="https:")throw new Error();return url.origin;}))],providerHostedRedirects:true,...(environment.STRIPE_API_VERSION?.trim()?{apiVersion:environment.STRIPE_API_VERSION.trim()}:{} )},fetcher); } catch { throw new StripeBillingConfigurationError("Stripe Billing configuration is invalid."); } }
export class StripeBillingProvider implements BillingProvider {
  public readonly capabilities=stripeBillingProviderCapabilities;
  public constructor(private readonly config:StripeBillingProviderConfiguration,private readonly fetcher:StripeFetch=fetch) { try { const base=new URL(config.apiBaseUrl);if(!config.secretKey||base.protocol!=="https:"||!Number.isSafeInteger(config.timeoutMs)||config.timeoutMs<1)throw new Error(); } catch { throw new Error("Stripe Billing configuration is invalid."); } }
  public createCheckoutSession(input:{readonly idempotencyKey:string;readonly catalogReference:string;readonly successTarget:string;readonly cancelTarget:string;readonly correlationToken?:string|undefined}):Promise<BillingProviderResult> { if(!this.redirect(input.successTarget)||!this.redirect(input.cancelTarget))return Promise.resolve({kind:"failed",code:"invalid_request"}); return this.post("/v1/checkout/sessions",{mode:"subscription","line_items[0][price]":input.catalogReference,"line_items[0][quantity]":"1",success_url:input.successTarget,cancel_url:input.cancelTarget,...(input.correlationToken?{client_reference_id:input.correlationToken}:{})},input.idempotencyKey,true); }
  public createPortalSession(input:{readonly billingAccountReference:string;readonly returnTarget:string}):Promise<BillingProviderResult> { if(!input.billingAccountReference||!this.redirect(input.returnTarget))return Promise.resolve({kind:"failed",code:"invalid_request"}); return this.post("/v1/billing_portal/sessions",{customer:input.billingAccountReference,return_url:input.returnTarget},null,true); }
  public cancelAtPeriodEnd(input:{readonly idempotencyKey:string;readonly subscriptionReference:string}):Promise<BillingProviderResult> { return input.subscriptionReference?this.post(`/v1/subscriptions/${encodeURIComponent(input.subscriptionReference)}`,{cancel_at_period_end:"true"},input.idempotencyKey,false):Promise.resolve({kind:"failed",code:"invalid_request"}); }
  public reactivateSubscription(input:{readonly idempotencyKey:string;readonly subscriptionReference:string}):Promise<BillingProviderResult> { return input.subscriptionReference?this.post(`/v1/subscriptions/${encodeURIComponent(input.subscriptionReference)}`,{cancel_at_period_end:"false"},input.idempotencyKey,false):Promise.resolve({kind:"failed",code:"invalid_request"}); }
  public async readSubscription(input:{readonly subscriptionReference:string}):Promise<BillingSubscriptionReadResult> { if(!this.id(input.subscriptionReference))return {kind:"failed",code:"invalid_request"}; const body=await this.get(`/v1/subscriptions/${encodeURIComponent(input.subscriptionReference)}`); if(body==="not_found")return {kind:"not_found"}; if(!body)return {kind:"uncertain"}; const id=this.string(body.id); if(id!==input.subscriptionReference)return {kind:"uncertain"}; const status=this.stripeState(body.status); if(!status)return {kind:"uncertain"}; const start=this.timestamp(body.current_period_start),end=this.timestamp(body.current_period_end),trialEnd=this.timestamp(body.trial_end); if(start===undefined||end===undefined||trialEnd===undefined)return {kind:"uncertain"}; const items=body.items;const lines:unknown[]=items&&typeof items==="object"&&Array.isArray((items as Record<string,unknown>).data)?(items as Record<string,unknown>).data as unknown[]:[];const price=lines.length===1&&lines[0]&&typeof lines[0]==="object"?(lines[0] as Record<string,unknown>).price:null;const providerCommercialReference=price&&typeof price==="object"?this.string((price as Record<string,unknown>).id):null; return {kind:"success",evidence:Object.freeze({providerSubscriptionId:id,providerCommercialReference,providerEvidenceState:status,currentPeriodStart:start,currentPeriodEnd:end,trialEndsAt:trialEnd,cancelAtPeriodEnd:body.cancel_at_period_end===true})}; }
  public recoverOperation(input:{readonly kind:import("../domain/billingOperations.js").BillingOperationKind;readonly idempotencyKey:string;readonly catalogReference?:string;readonly successTarget?:string;readonly cancelTarget?:string;readonly correlationToken?:string;readonly subscriptionReference?:string}):Promise<BillingProviderResult> { if(input.kind==="checkout_session_create"&&input.catalogReference&&input.successTarget&&input.cancelTarget)return this.createCheckoutSession({idempotencyKey:input.idempotencyKey,catalogReference:input.catalogReference,successTarget:input.successTarget,cancelTarget:input.cancelTarget,correlationToken:input.correlationToken});if(input.kind==="subscription_cancel_at_period_end"&&input.subscriptionReference)return this.cancelAtPeriodEnd({idempotencyKey:input.idempotencyKey,subscriptionReference:input.subscriptionReference});if(input.kind==="subscription_reactivate"&&input.subscriptionReference)return this.reactivateSubscription({idempotencyKey:input.idempotencyKey,subscriptionReference:input.subscriptionReference});return Promise.resolve({kind:"failed",code:"invalid_request"}); }
  public async validateCommercialOffer(input:{readonly catalogReference:string;readonly currency:string;readonly amountMinor:number;readonly interval:"month"|"year"}):Promise<BillingCommercialOfferValidation>{if(!this.id(input.catalogReference)||input.currency!=="USD"||!Number.isSafeInteger(input.amountMinor)||input.amountMinor<1)return{kind:"invalid"};const body=await this.get(`/v1/prices/${encodeURIComponent(input.catalogReference)}`);if(body==="not_found")return{kind:"invalid"};if(!body)return{kind:"unavailable"};const recurring=body.recurring;return body.active===true&&body.currency==="usd"&&body.unit_amount===input.amountMinor&&recurring&&typeof recurring==="object"&&(recurring as Record<string,unknown>).interval===input.interval?{kind:"ready"}:{kind:"invalid"};}
  private redirect(value:string):boolean { try { const url=new URL(value); return url.protocol==="https:"&&this.config.allowedRedirectOrigins.includes(url.origin); } catch{return false;} }
  private providerRedirect(value:string):boolean { try { const url=new URL(value); return url.protocol==="https:"&&(this.config.providerHostedRedirects?(url.hostname==="checkout.stripe.com"||url.hostname==="billing.stripe.com"):this.config.allowedRedirectOrigins.includes(url.origin)); } catch{return false;} }
  private id(value:unknown):value is string{return typeof value==="string"&&value.length>0&&value.length<=200;}
  private string(value:unknown):string|null{return this.id(value)?value:null;}
  private timestamp(value:unknown):string|null|undefined { if(value===null)return null;if(typeof value!=="number"||!Number.isSafeInteger(value)||value<0)return undefined;return new Date(value*1000).toISOString(); }
  private stripeState(value:unknown):ProviderEvidenceState|null { if(typeof value!=="string")return null; const state=value==="paused"?"paused":value; try{return providerEvidenceState(state);}catch{return "unknown";} }
  private async get(path:string):Promise<Record<string,unknown>|"not_found"|null> { const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.config.timeoutMs);try{const headers=new Headers({Authorization:`Bearer ${this.config.secretKey}`});if(this.config.apiVersion)headers.set("Stripe-Version",this.config.apiVersion);const response=await this.fetcher(`${this.config.apiBaseUrl}${path}`,{method:"GET",headers,signal:controller.signal});if(response.status===404)return "not_found";if(!response.ok)return null;const body:unknown=await response.json();return body&&typeof body==="object"?body as Record<string,unknown>:null;}catch{return null;}finally{clearTimeout(timer);} }
  private async post(path:string,values:Record<string,string>,idempotencyKey:string|null,redirect:boolean):Promise<BillingProviderResult> { const controller=new AbortController(), timer=setTimeout(()=>controller.abort(),this.config.timeoutMs); try { const headers=new Headers({Authorization:`Bearer ${this.config.secretKey}`,"Content-Type":"application/x-www-form-urlencoded"}); if(this.config.apiVersion)headers.set("Stripe-Version",this.config.apiVersion); if(idempotencyKey)headers.set("Idempotency-Key",idempotencyKey); const response=await this.fetcher(`${this.config.apiBaseUrl}${path}`,{method:"POST",headers,body:new URLSearchParams(values).toString(),signal:controller.signal}); if(!response.ok)return response.status>=400&&response.status<500?{kind:"failed",code:"invalid_request"}:{kind:"uncertain"}; let body:unknown;try{body=await response.json();}catch{return{kind:"uncertain"};} if(!body||typeof body!=="object")return{kind:"uncertain"}; const record=body as Record<string,unknown>, id=typeof record.id==="string"&&record.id.length>0&&record.id.length<=200?record.id:null, url=typeof record.url==="string"?record.url:undefined; if(!id||(redirect&&(!url||!this.providerRedirect(url))))return{kind:"uncertain"}; return {kind:"success",providerObjectId:id,...(redirect&&url?{redirectUrl:url}:{})}; } catch { return {kind:"uncertain"}; } finally { clearTimeout(timer); } }
}
