import { useEffect, useRef, useState } from "react";
import { ApiError, atlasApi } from "../api/atlasApi";
import { publicWebChatApi } from "../api/publicWebChatApi";
import { Badge, Button, Surface } from "../design-system/primitives";
import type { ActivationAction, ActivationProjection, ActivationStage, ActivationStageId } from "../types/api";

interface Props { readonly csrf:string; readonly workspaceId:string; readonly companyId:number; readonly projection:ActivationProjection; readonly onNavigate:(path:string)=>void; readonly onRefresh:()=>void; }

const stageCopy:Record<ActivationStageId,string>={company:"Empresa",knowledge:"Conocimiento",assistant:"Asistente",web_chat:"Web Chat",verification:"Verificación",pilot_ready:"Piloto listo",human_ops:"Operaciones humanas"};
const actionCopy:Record<ActivationAction,string>={complete_company:"Completar empresa",publish_knowledge:"Publicar conocimiento",configure_assistant:"Configurar asistente",activate_web_chat:"Activar Web Chat",start_verification:"Iniciar verificación",resolve_pilot_readiness:"Actualizar estado del piloto",review_human_operations:"Abrir conversaciones"};
const reasonCopy:Record<NonNullable<ActivationStage["reasonCode"]>,string>={company_missing:"No encontramos esta empresa.",company_suspended:"La empresa está suspendida.",company_archived:"La empresa está archivada.",default_assistant_not_executable:"El asistente predeterminado todavía no está listo para atender.",published_knowledge_missing:"Todavía falta publicar conocimiento.",web_chat_not_connected:"Todavía no hay un Web Chat conectado.",web_chat_inactive:"Web Chat está conectado pero inactivo.",verification_required:"Probá una conversación para confirmar que el asistente responde.",verification_pending:"La conversación de verificación está en curso.",verification_failed:"La comprobación anterior no se completó. Intentá nuevamente.",pilot_not_ready:"Atlas volverá a comprobar la preparación del piloto."};

export function safeActivationPath(path:string|null,companyId:number):string|null { if(path===null)return null;const base=`/companies/${companyId}`,known=new Set([base,`${base}/knowledge`,`${base}/assistant`,`${base}/channels/web-chat`,`/conversations`]);return known.has(path)?path:null; }

function statusCopy(stage:ActivationStage):string { if(stage.state==="complete")return "Listo";if(stage.state==="blocked")return "Bloqueado";if(stage.state==="unavailable")return "No disponible";return "Pendiente"; }
function ownerCopy(stage:ActivationStage):string|null { if(stage.owner==="platform")return "Atlas necesita completar una configuración.";if(stage.owner==="external_provider")return "Se requiere una acción del proveedor.";return null; }

export function ActivationJourney({csrf,workspaceId,companyId,projection,onNavigate,onRefresh}:Props):React.JSX.Element {
  const [submitting,setSubmitting]=useState(false),[notice,setNotice]=useState<string|null>(null),[verificationUrl,setVerificationUrl]=useState<string|null>(null),scopeRef=useRef("");
  const scope=`${workspaceId}:${companyId}`;
  scopeRef.current=scope;
  const actionStage=projection.stages.find(stage=>stage.action===projection.nextAction)??null;
  const actionPath=actionStage?safeActivationPath(actionStage.actionPath,companyId):null;
  useEffect(()=>{const refresh=():void=>onRefresh();window.addEventListener("focus",refresh);return()=>window.removeEventListener("focus",refresh);},[onRefresh,scope]);
  const perform=async(verificationWindow:Window|null=null):Promise<void>=>{if(submitting||!actionStage)return;setNotice(null);setVerificationUrl(null);if(actionPath){onNavigate(actionPath);return;}if(projection.nextAction==="resolve_pilot_readiness"){onRefresh();setNotice("Actualizamos el estado con la información más reciente.");return;}if(projection.nextAction!=="start_verification")return;const actionScope=scope;setSubmitting(true);try{const attempt=await atlasApi.startActivationVerification(csrf,workspaceId,companyId),connections=await atlasApi.listWebChatConnections(workspaceId,companyId),connection=connections.find(value=>value.status==="active");if(!connection)throw new Error("Web Chat is unavailable.");await publicWebChatApi.startActivationVerification(connection.publicId,attempt.token);if(scopeRef.current!==actionScope)return;const url=`/chat/${connection.publicId}`;setVerificationUrl(url);if(verificationWindow){verificationWindow.opener=null;verificationWindow.location.replace(url);}setNotice(verificationWindow?"La conversación de verificación está abierta. Enviá un mensaje y volvé a esta página para confirmar el resultado.":"Abrí la conversación de verificación para continuar.");onRefresh();}catch(error:unknown){verificationWindow?.close();if(scopeRef.current===actionScope)setNotice(error instanceof ApiError?error.message:"No pudimos iniciar la verificación. Intentá nuevamente.");}finally{if(scopeRef.current===actionScope)setSubmitting(false);}};
  const begin=():void=>{const verificationWindow=projection.nextAction==="start_verification"?window.open("","_blank"):null;void perform(verificationWindow);};
  return <section className="pilot-readiness" aria-busy={submitting} aria-labelledby="activation-journey-title"><header className="work-anchor"><p className="work-anchor__context">Recorrido de activación</p><h1 id="activation-journey-title" tabIndex={-1}>Activá tu asistente</h1><p>Atlas confirma cada paso con el estado actual de la empresa.</p>{actionStage&&<Button className="next-action" onClick={begin} disabled={submitting}>{submitting?"Iniciando...":actionCopy[projection.nextAction]}</Button>}{notice&&<p role="status">{notice}</p>}{verificationUrl&&<a href={verificationUrl} target="_blank" rel="noreferrer">Abrir conversación de verificación</a>}</header><Surface className="readiness-evidence"><ol>{projection.stages.map(stage=>{const owner=ownerCopy(stage),tone=stage.state==="complete"?"success":stage.state==="blocked"?"danger":stage.state==="unavailable"?"warning":"info";return <li key={stage.id}><div><strong>{stageCopy[stage.id]}</strong><Badge tone={tone}>{statusCopy(stage)}</Badge>{stage.reasonCode&&<p>{reasonCopy[stage.reasonCode]}</p>}{owner&&<p className="work-anchor__quiet">{owner}</p>}</div></li>;})}</ol><p className="work-anchor__quiet">Última verificación: <time dateTime={projection.evaluatedAt}>{projection.evaluatedAt}</time></p></Surface></section>;
}
