// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import { ApiError, atlasApi } from "../api/atlasApi";
import { I18nProvider } from "../i18n/I18nContext";
import { AssistantStatusPanel } from "./AssistantStatusPanel";

const readiness = { assistantIdentifier: "default" as const, workspaceId: 1, companyId: 2, status: "ready" as const, blockers: [], knowledgeVersionId: "knowledge", assistantProfileId: "profile", evaluatedAt: "2026-01-01T00:00:00.000Z", policyVersion: "assistant-readiness-v1", configurationDigest: "a".repeat(64) };
const operational = { assistant: { status: "ready" as const, evaluatedAt: readiness.evaluatedAt, blockers: [] }, whatsApp: [{ connectionId: "connection", status: "active" as const, validationState: "valid" as const, healthState: "healthy" as const }], voice: { status: "unavailable" as const } };
const renderPanel = (props: Partial<React.ComponentProps<typeof AssistantStatusPanel>> = {}) => render(<I18nProvider><AssistantStatusPanel csrf="csrf" workspaceId="workspace" companyId={2} profileId="profile" canManage {...props}/></I18nProvider>);
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

test("shows confirmed readiness, safe blockers, voice neutrality, and deterministic links", async () => { vi.spyOn(atlasApi, "getAssistantReadiness").mockResolvedValue({ ...readiness, status: "blocked", blockers: ["published_knowledge_missing", "whatsapp_credentials_missing"] }); vi.spyOn(atlasApi, "getCompanyOperationalStatus").mockResolvedValue(operational); const navigate = vi.fn(); renderPanel({ onNavigate: navigate }); await screen.findByText("Needs attention"); expect(screen.getByText("The company's knowledge still needs to be published.")).toBeTruthy(); expect(screen.getByText("Voice service is currently unavailable. This does not prevent the assistant from serving customers through available channels.")).toBeTruthy(); fireEvent.click(screen.getByRole("link", { name: "Publish knowledge" })); expect(navigate).toHaveBeenCalledWith("/companies/2/knowledge"); });
test("allows only managers to refresh and canonically refetches after confirmation", async () => { const getReadiness = vi.spyOn(atlasApi, "getAssistantReadiness").mockResolvedValue(readiness); const getOperational = vi.spyOn(atlasApi, "getCompanyOperationalStatus").mockResolvedValue(operational); vi.spyOn(atlasApi, "refreshAssistantReadiness").mockResolvedValue(readiness); renderPanel(); await screen.findByText("Ready"); fireEvent.click(screen.getByRole("button", { name: "Check again" })); await waitFor(() => expect(getReadiness).toHaveBeenCalledTimes(2)); expect(getOperational).toHaveBeenCalledTimes(2); });
test("preserves confirmed status for refresh failures and gives safe retry guidance", async () => { vi.spyOn(atlasApi, "getAssistantReadiness").mockResolvedValue(readiness); vi.spyOn(atlasApi, "getCompanyOperationalStatus").mockResolvedValue(operational); vi.spyOn(atlasApi, "refreshAssistantReadiness").mockRejectedValue(new ApiError(429, "private", null, 30)); renderPanel(); await screen.findByText("Ready"); fireEvent.click(screen.getByRole("button", { name: "Check again" })); await screen.findByText("Checking is temporarily limited. Try again in 30 seconds."); expect(screen.getByText("Confirmed details")).toBeTruthy(); });
test("maps inaccessible and unavailable initial reads without exposing server details", async () => { vi.spyOn(atlasApi, "getAssistantReadiness").mockRejectedValue(new ApiError(404, "private")); renderPanel(); await screen.findByText("This status is no longer available."); cleanup(); vi.restoreAllMocks(); vi.spyOn(atlasApi, "getAssistantReadiness").mockRejectedValue(new ApiError(503, "private")); renderPanel(); await screen.findByText("We could not confirm the assistant status right now."); });
test("does not let a stale scoped response overwrite the new profile", async () => { let resolveFirst!: (value: typeof readiness) => void; const first = new Promise<typeof readiness>(resolve => { resolveFirst = resolve; }); vi.spyOn(atlasApi, "getAssistantReadiness").mockReturnValueOnce(first).mockResolvedValue({ ...readiness, assistantProfileId: "next" }); vi.spyOn(atlasApi, "getCompanyOperationalStatus").mockResolvedValue(operational); const view = renderPanel({ profileId: "old" }); view.rerender(<I18nProvider><AssistantStatusPanel csrf="csrf" workspaceId="workspace" companyId={2} profileId="next" canManage/></I18nProvider>); resolveFirst(readiness); await screen.findByText("Ready"); expect(screen.queryByText("This status applies to the company's default assistant.")).toBeNull(); });
