// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { AssistantCapabilitiesPanel } from "./AssistantCapabilitiesPanel";
import { I18nProvider } from "../i18n/I18nContext";

const json=(body:unknown,status=200):Response=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const item=(overrides:Partial<{id:string;assigned:boolean;availability:"available"|"unavailable"|"degraded";consequence:"read_only"|"consequential";safeReason:string|null;safeNextAction:string|null;toolCount:number}>={})=>({id:"live_data.read",assigned:false,availability:"available" as const,consequence:"read_only" as const,safeReason:null,safeNextAction:null,toolCount:1,...overrides});
const catalog=(...capabilities:ReturnType<typeof item>[])=>({capabilities});
const renderPanel=(props:Partial<React.ComponentProps<typeof AssistantCapabilitiesPanel>>={})=>render(<I18nProvider><AssistantCapabilitiesPanel csrf="csrf" workspaceId="workspace" companyId={1} profileId="assistant" canManage {...props}/></I18nProvider>);
const toggle=(id:string)=>document.getElementById(`capability-${id}`) as HTMLInputElement;

afterEach(()=>{cleanup();vi.restoreAllMocks();});

it("saves a changed read-only capability and refetches the authoritative catalog",async()=>{const updated=catalog(item({assigned:true}));const fetchMock=vi.fn().mockResolvedValueOnce(json(catalog(item()))).mockResolvedValueOnce(json({capabilities:["live_data.read"]})).mockResolvedValueOnce(json(updated));vi.stubGlobal("fetch",fetchMock);const view=renderPanel();await screen.findByRole("heading",{name:"What this assistant can do"});expect(view.container.querySelector("section.assistant-capabilities")).not.toBeNull();expect(view.container.querySelector(".assistant-capabilities__list li.assistant-capability-row")).not.toBeNull();fireEvent.click(toggle("live_data.read"));fireEvent.click(screen.getByRole("button",{name:"Save changes"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));expect(fetchMock.mock.calls[1]?.[0]).toBe("/api/workspaces/workspace/companies/1/assistant-profiles/assistant/capabilities");expect(JSON.parse(String((fetchMock.mock.calls[1]?.[1] as RequestInit).body))).toEqual({capabilities:["live_data.read"]});expect(toggle("live_data.read").checked).toBe(true);expect((screen.getByRole("button",{name:"Save changes"}) as HTMLButtonElement).disabled).toBe(true);});

it("requires confirmation before enabling a consequential capability",async()=>{const booking=item({id:"scheduling.create_booking",consequence:"consequential"});const fetchMock=vi.fn().mockResolvedValueOnce(json(catalog(booking))).mockResolvedValueOnce(json({capabilities:[booking.id]})).mockResolvedValueOnce(json(catalog({...booking,assigned:true})));vi.stubGlobal("fetch",fetchMock);renderPanel();await screen.findByText("Create bookings");fireEvent.click(toggle(booking.id));fireEvent.click(screen.getByRole("button",{name:"Save changes"}));expect(screen.getByRole("alertdialog",{name:"Confirm capabilities"})).toBeTruthy();expect(fetchMock).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole("button",{name:"Confirm and save"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));});
it("renders distinct availability badges for available, degraded, and unavailable capabilities",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json(catalog(item({availability:"available"}),item({id:"scheduling.get_booking",availability:"degraded"}),item({id:"scheduling.create_booking",availability:"unavailable"})))));const view=renderPanel();await screen.findByText("Current data");expect(view.container.querySelector(".assistant-capability-row__availability--available")).not.toBeNull();expect(view.container.querySelector(".assistant-capability-row__availability--degraded")).not.toBeNull();expect(view.container.querySelector(".assistant-capability-row__availability--unavailable")).not.toBeNull();});

it("refetches the current catalog after a conflict",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(json(catalog(item()))).mockResolvedValueOnce(json({error:"changed"},409)).mockResolvedValueOnce(json(catalog(item({assigned:true}))));vi.stubGlobal("fetch",fetchMock);renderPanel();await screen.findByText("Current data");fireEvent.click(toggle("live_data.read"));fireEvent.click(screen.getByRole("button",{name:"Save changes"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));expect(toggle("live_data.read").checked).toBe(true);});

it("renders unknown capabilities safely and keeps read-only users from changing them",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json(catalog(item({id:"future.capability",assigned:true,availability:"degraded",safeReason:"Configuration incomplete",safeNextAction:"Contact an administrator"})))));renderPanel({canManage:false});await screen.findByText("Available capability");expect(screen.getByText("This capability is managed safely.")).toBeTruthy();expect(screen.getByText("Configuration incomplete")).toBeTruthy();expect(toggle("future.capability").disabled).toBe(true);expect(screen.queryByRole("button",{name:"Save changes"})).toBeNull();expect(screen.getByRole("status").textContent).toContain("do not have permission");expect(screen.queryByText("future.capability")).toBeNull();});

it.each([[404,"Capabilities are unavailable for this assistant."],[429,"We couldn't load capabilities. Try again."],[503,"We couldn't load capabilities. Try again."]])("maps a %i capability API failure to the safe UI state",async(status,message)=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json({error:"private"},status)));renderPanel();expect((await screen.findByRole("alert")).textContent).toBe(message);});

it("aborts the obsolete catalog request when the assistant context changes",async()=>{let firstSignal:AbortSignal|undefined;const first=new Promise<Response>(()=>{});const fetchMock=vi.fn().mockImplementationOnce((_url:string,options:RequestInit)=>{firstSignal=options.signal as AbortSignal;return first;}).mockResolvedValueOnce(json(catalog(item({id:"scheduling.get_booking"}))));vi.stubGlobal("fetch",fetchMock);const view=renderPanel();view.rerender(<I18nProvider><AssistantCapabilitiesPanel csrf="csrf" workspaceId="workspace" companyId={1} profileId="next-assistant" canManage/></I18nProvider>);await screen.findByText("View bookings");expect(firstSignal?.aborted).toBe(true);});
