// @vitest-environment jsdom
import { afterEach, expect, test, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { I18nProvider } from "../i18n/I18nContext";
import { AssistantTestPanel } from "./AssistantTestPanel";

const profile={id:"assistant-1",name:"Atlas",description:null,businessRole:null,objective:null,audience:null,tone:"professional" as const,assistantLanguage:"en" as const,welcomeMessage:null,fallbackMessage:"Fallback",status:"ready" as const,createdAt:"2026-01-01",updatedAt:"2026-01-01",archivedAt:null};
const response=(body:unknown,status=200,headers:Record<string,string>={"content-type":"application/json"})=>new Response(JSON.stringify(body),{status,headers});
function renderPanel(capabilities:("assistant:preview"|"chat:use")[]=["assistant:preview","chat:use"]){return render(<I18nProvider><AssistantTestPanel csrf="csrf" workspaceId="workspace" companyId={1} profile={profile} capabilities={capabilities}/></I18nProvider>);}
function submit(message="Question"){fireEvent.change(screen.getByRole("textbox"),{target:{value:message}});fireEvent.click(screen.getByRole("button",{name:"Send test"}));}
afterEach(()=>{cleanup();vi.restoreAllMocks();window.localStorage.clear();});

test("uses only the selected real endpoint for each customer mode",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({status:"answered",answer:"Preview"})).mockResolvedValueOnce(response({status:"safe_fallback",answer:"Active"}));renderPanel();submit();await screen.findByText("Preview");expect(String(fetchMock.mock.calls[0]?.[0])).toContain("/assistant-profiles/assistant-1/preview");expect(String(fetchMock.mock.calls[0]?.[0])).not.toContain("/assistant/executions");fireEvent.click(screen.getByRole("tab",{name:"With active functions"}));submit("Another");await screen.findByText("Active");expect(String(fetchMock.mock.calls[1]?.[0])).toContain("/assistant/executions");expect(String(fetchMock.mock.calls[1]?.[0])).not.toContain("/preview");expect(JSON.parse(String((fetchMock.mock.calls[1]?.[1] as RequestInit).body))).toEqual({assistantProfileId:"assistant-1",message:"Another"});expect(screen.getByText("The assistant responded safely.")).toBeTruthy();});

test("enforces customer validation, permissions, pending protection, safe errors, and previous answers",async()=>{const pending=new Promise<Response>(()=>{}),fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({status:"answered",answer:"Confirmed"})).mockReturnValueOnce(pending);renderPanel();const send=screen.getByRole("button",{name:"Send test"});expect(send).toHaveProperty("disabled",true);fireEvent.change(screen.getByRole("textbox"),{target:{value:" ".repeat(5)}});expect(send).toHaveProperty("disabled",true);submit();await screen.findByText("Confirmed");submit("Next");expect(screen.getByRole("button",{name:"Sending…"})).toHaveProperty("disabled",true);fireEvent.click(screen.getByRole("button",{name:"Sending…"}));expect(fetchMock).toHaveBeenCalledTimes(2);});

test("maps safe HTTP errors and does not render raw diagnostics",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(response({error:{code:"secret_trace",message:"internal provider secret"}},429,{"content-type":"application/json","retry-after":"30"}));renderPanel();submit();const alert=await screen.findByRole("alert");expect(alert.textContent).toContain("temporarily rate limited");expect(alert.textContent).not.toContain("secret");});

test("shows truthful permission combinations and aborts stale profile requests",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>new Promise<Response>(()=>{}));const view=renderPanel(["assistant:preview"]);expect(screen.getByRole("tab",{name:"With active functions"})).toHaveProperty("disabled",true);submit();const signal=(fetchMock.mock.calls[0]?.[1] as RequestInit).signal as AbortSignal;view.rerender(<I18nProvider><AssistantTestPanel csrf="csrf" workspaceId="workspace" companyId={1} profile={{...profile,id:"assistant-2"}} capabilities={["assistant:preview"]}/></I18nProvider>);await waitFor(()=>expect(signal.aborted).toBe(true));cleanup();renderPanel([]);expect(screen.getByText("You do not have permission to test this assistant.")).toBeTruthy();});

test("aborts active work and clears customer data when permission changes",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>new Promise<Response>(()=>{}));const view=renderPanel(["chat:use"]);fireEvent.change(screen.getByRole("textbox"),{target:{value:"Question"}});fireEvent.click(screen.getByRole("button",{name:"Send test"}));const signal=(fetchMock.mock.calls[0]?.[1] as RequestInit).signal as AbortSignal;view.rerender(<I18nProvider><AssistantTestPanel csrf="csrf" workspaceId="workspace" companyId={1} profile={profile} capabilities={[]}/></I18nProvider>);await waitFor(()=>expect(signal.aborted).toBe(true));expect(screen.getByText("You do not have permission to test this assistant.")).toBeTruthy();});

test("aborts active work when the panel unmounts",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>new Promise<Response>(()=>{}));const view=renderPanel();submit();const signal=(fetchMock.mock.calls[0]?.[1] as RequestInit).signal as AbortSignal;view.unmount();await waitFor(()=>expect(signal.aborted).toBe(true));});

test("preserves the selected mode, message, and answer when CSRF rotates",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({status:"answered",answer:"Confirmed"})).mockResolvedValueOnce(response({status:"answered",answer:"Renewed"}));const view=renderPanel();fireEvent.click(screen.getByRole("tab",{name:"With active functions"}));submit("Keep this message");await screen.findByText("Confirmed");view.rerender(<I18nProvider><AssistantTestPanel csrf="rotated-csrf" workspaceId="workspace" companyId={1} profile={profile} capabilities={["assistant:preview","chat:use"]}/></I18nProvider>);expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("Keep this message");expect(screen.getByText("Confirmed")).toBeTruthy();expect(screen.getByRole("tab",{name:"With active functions"}).getAttribute("aria-selected")).toBe("true");submit("Uses renewed CSRF");await screen.findByText("Renewed");expect((fetchMock.mock.calls[1]?.[1] as RequestInit).headers).toMatchObject({"x-csrf-token":"rotated-csrf"});});
