import { useEffect, useRef, useState } from "react";
import { atlasApi } from "../api/atlasApi";
import { Callout } from "../design-system/product";
import { useI18n } from "../i18n/I18nContext";
import { markReadyDisabled, missingReadyFields, visibleTransitions, type FormMode, type ReadyAdvisoryField } from "../state/authenticatedPortalState";
import { previewAllowed } from "../state/assistantPreviewState";
import type { AssistantProfile, AssistantProfileStatus, CreateAssistantProfileInput, DefaultAssistantAssignment, Permission, UpdateAssistantProfileInput } from "../types/api";
import { AssistantPreviewPanel } from "./AssistantPreviewPanel";
import { AssistantProfileForm } from "./AssistantProfileForm";
import { AssistantStatusBadge } from "./AssistantStatusBadge";
import { ContextBackLink } from "./ContextBackLink";
import { OperationalAssistantExecutionPanel } from "./OperationalAssistantExecutionPanel";

interface Props { csrf:string; workspaceId:string|null; workspaceRole:string|null; capabilities:Permission[]; companyId:number|null; companyName:string|null; companySelected:boolean; profiles:AssistantProfile[]; selectedProfile:AssistantProfile|null; transientArchivedProfile:AssistantProfile|null; loading:boolean; error:boolean; formMode:FormMode; submitting:boolean; transitionTarget:AssistantProfileStatus|null; onSelectProfile:(profileId:string)=>void; onOpenCreate:()=>void; onOpenEdit:()=>void; onCloseForm:()=>void; onSubmitForm:(input:CreateAssistantProfileInput|UpdateAssistantProfileInput)=>void; onTransition:(profile:AssistantProfile,target:AssistantProfileStatus)=>void; onRetry:()=>void; }

const fieldKeys:Record<ReadyAdvisoryField,Parameters<ReturnType<typeof useI18n>["t"]>[0]>={name:"profiles.field.name",businessRole:"profiles.field.businessRole",objective:"profiles.field.objective",tone:"profiles.field.tone",assistantLanguage:"profiles.field.language",welcomeMessage:"profiles.field.welcomeMessage",fallbackMessage:"profiles.field.fallbackMessage"};

export function AssistantProfilesPanel(props:Props):React.JSX.Element {
  const {t,formatDate}=useI18n(); const [confirmArchive,setConfirmArchive]=useState<AssistantProfile|null>(null); const [defaultAssistant,setDefaultAssistant]=useState<DefaultAssistantAssignment|null>(null);
  const [detailVisible,setDetailVisible]=useState(false);
  const createTriggerRef=useRef<HTMLButtonElement>(null); const restoreCreateFocus=useRef(false);
  useEffect(()=>{if(!props.workspaceId||!props.companyId)return;void atlasApi.getDefaultAssistant(props.workspaceId,props.companyId).then(setDefaultAssistant).catch(()=>setDefaultAssistant(null));},[props.workspaceId,props.companyId,props.profiles]);
  useEffect(()=>{if(props.formMode==="closed"&&restoreCreateFocus.current){restoreCreateFocus.current=false;createTriggerRef.current?.focus();}},[props.formMode]);
  const selected=props.selectedProfile; const missing=selected?missingReadyFields(selected):[];
  const transition=(profile:AssistantProfile,target:AssistantProfileStatus):void=>{if(target==="archived"){setConfirmArchive(profile);return;}props.onTransition(profile,target);};
  const transitionLabel=(target:AssistantProfileStatus):string=>target==="ready"?t("profiles.action.ready"):target==="disabled"?t("profiles.action.disable"):target==="archived"?t("profiles.action.archive"):selected?.status==="archived"?t("profiles.action.restore"):t("profiles.action.draft");
  const closeWorkspace=():void=>{restoreCreateFocus.current=props.formMode==="create";setDetailVisible(false);props.onCloseForm();};
  const profileStatus=(status:AssistantProfileStatus):string=>status==="ready"?t("profiles.readiness.ready"):status==="draft"?t("profiles.readiness.draft"):t("profiles.readiness.attention");
  const focused=props.formMode!=="closed"||detailVisible;
  const back=<ContextBackLink href={`/companies/${props.companyId}/assistant`} label={t("profiles.back")} onNavigate={(event)=>{event.preventDefault();closeWorkspace();}}/>;

  if(!props.companySelected)return <section className="authenticated-section assistant-profiles"><h2>{t("profiles.title")}</h2><p className="state-copy">{t("profiles.companyRequired")}</p></section>;
  return <section className={`authenticated-section assistant-profiles${focused?" assistant-profiles--focused":""}`} aria-busy={props.loading}>
    {!focused&&props.profiles.length>0&&<div className="section-heading"><div><h2>{t("profiles.title")}</h2><p>{t("profiles.description")}</p></div><button ref={createTriggerRef} className="button button--primary" type="button" onClick={props.onOpenCreate}>{t("profiles.create")}</button></div>}
    {props.loading&&<p role="status">{t("profiles.loading")}</p>}
    {props.error&&<div className="inline-message inline-message--error" role="alert"><p>{t("profiles.loadError")}</p><button className="button button--secondary" type="button" onClick={props.onRetry}>{t("common.retry")}</button></div>}
    {props.formMode==="create"&&<div className="assistant-profile-workspace">{back}<header className="assistant-profile-workspace__heading"><p className="atlas-eyebrow">{t("profiles.form.eyebrow")}</p><h2>{t("profiles.createTitle")}</h2><p>{t("profiles.form.createDescription")}</p></header><AssistantProfileForm mode="create" submitting={props.submitting} onSubmit={props.onSubmitForm} onCancel={closeWorkspace}/></div>}
    {props.transientArchivedProfile&&<div className="archived-recovery" role="status"><div><strong>{t("profiles.archivedTitle")}</strong><p>{t("profiles.archivedDescription",{profileName:props.transientArchivedProfile.name})}</p></div><button className="button button--secondary" disabled={props.transitionTarget!==null} onClick={()=>props.onTransition(props.transientArchivedProfile!,"draft")}>{t("profiles.action.restore")}</button></div>}
    {!props.loading&&!props.error&&props.profiles.length===0&&props.formMode!=="create"&&!props.transientArchivedProfile&&<section className="assistant-configuration-empty" aria-labelledby="assistant-configuration-title"><p className="atlas-eyebrow">{t("profiles.form.eyebrow")}</p><h2 id="assistant-configuration-title">{t("profiles.emptyTitle")}</h2><p>{t("profiles.emptyDescription")}</p><ul><li>{t("profiles.form.purpose")}</li><li>{t("profiles.form.communication")}</li><li>{t("profiles.form.messages")}</li></ul><button ref={createTriggerRef} className="button button--primary" type="button" onClick={props.onOpenCreate}>{t("profiles.createFirst")}</button></section>}
    <div className="assistant-profile-layout">
      {!focused&&props.profiles.length>0&&<div className="assistant-profile-list" aria-label={t("profiles.listLabel")}>{props.profiles.map(profile=><article key={profile.id} className="assistant-profile-item"><div className="assistant-profile-item__identity"><h3>{profile.name}</h3>{profile.businessRole&&<p>{profile.businessRole}</p>}</div><dl className="assistant-profile-facts"><div><dt>{t("profiles.fact.language")}</dt><dd>{profile.assistantLanguage.toUpperCase()}</dd></div><div><dt>{t("profiles.fact.tone")}</dt><dd>{t(`profiles.tone.${profile.tone}`)}</dd></div><div><dt>{t("profiles.fact.readiness")}</dt><dd>{profileStatus(profile.status)}</dd></div></dl><button type="button" className="button button--secondary" onClick={()=>{setDetailVisible(true);props.onSelectProfile(profile.id);}}>{profile.status === "draft" ? t("profiles.review") : t("profiles.viewConfiguration")}</button></article>)}</div>}
    {selected&&detailVisible&&props.formMode!=="create"&&<div className="assistant-profile-workspace">{back}<div className="assistant-profile-detail">
        {selected.status==="draft"&&<header className="assistant-profile-review"><p className="atlas-eyebrow">{t("profiles.reviewEyebrow")}</p><h2>{t("profiles.reviewTitle")}</h2><p>{t("profiles.reviewDescription")}</p></header>}
        <div className="assistant-profile-identity workspace-title-row"><div><h3>{selected.name}</h3><p>{t("profiles.updatedAt",{date:formatDate(selected.updatedAt)})}</p>{defaultAssistant?.assistantProfileId===selected.id&&<p role="status">Default Assistant</p>}</div><AssistantStatusBadge status={selected.status}/></div>
        {props.formMode==="edit"?<AssistantProfileForm mode="edit" profile={selected} submitting={props.submitting} onSubmit={props.onSubmitForm} onCancel={closeWorkspace}/>:<>
          <dl className="assistant-profile-summary"><div className="assistant-profile-summary-item assistant-profile-summary-item--compact"><dt>{t("profiles.field.language")}</dt><dd>{selected.assistantLanguage.toUpperCase()}</dd></div><div className="assistant-profile-summary-item assistant-profile-summary-item--compact"><dt>{t("profiles.field.tone")}</dt><dd>{t(`profiles.tone.${selected.tone}`)}</dd></div><div className="assistant-profile-summary-item assistant-profile-summary-item--full"><dt>{t("profiles.field.businessRole")}</dt><dd>{selected.businessRole??t("profiles.notConfigured")}</dd></div><div className="assistant-profile-summary-item assistant-profile-summary-item--full"><dt>{t("profiles.field.objective")}</dt><dd>{selected.objective??t("profiles.notConfigured")}</dd></div><div className="assistant-profile-summary-item assistant-profile-summary-item--full"><dt>{t("profiles.field.audience")}</dt><dd>{selected.audience??t("profiles.notConfigured")}</dd></div><div className="assistant-profile-summary-item assistant-profile-summary-item--full"><dt>{t("profiles.field.welcomeMessage")}</dt><dd>{selected.welcomeMessage??t("profiles.notConfigured")}</dd></div><div className="assistant-profile-summary-item assistant-profile-summary-item--full"><dt>{t("profiles.field.fallbackMessage")}</dt><dd>{selected.fallbackMessage}</dd></div></dl>
          {missing.length>0&&<Callout tone="warning" title={t("profiles.readyWarning")}><ul>{missing.map(field=><li key={field}>{t(fieldKeys[field])}</li>)}</ul></Callout>}
          <div className="assistant-profile-actions">{visibleTransitions(selected.status).includes("ready")&&<div className="assistant-profile-actions__primary"><button className="button button--primary" type="button" disabled={markReadyDisabled(selected,props.transitionTarget!==null)} onClick={()=>transition(selected,"ready")}>{props.transitionTarget==="ready"?t("profiles.transitioning"):transitionLabel("ready")}</button></div>}<div className="assistant-profile-actions__secondary action-row"><button className="button button--secondary" type="button" disabled={selected.status==="archived"||props.submitting} onClick={props.onOpenEdit}>{t("common.edit")}</button>{props.workspaceId&&props.companyId&&selected.status!=="archived"&&<button className="button button--secondary" type="button" onClick={()=>void atlasApi.setDefaultAssistant(props.csrf,props.workspaceId!,props.companyId!,selected.id,defaultAssistant?.version).then(setDefaultAssistant)}>{t("profiles.action.setDefault")}</button>}{visibleTransitions(selected.status).filter(target=>target!=="ready"&&target!=="archived").map(target=><button key={target} className="button button--secondary" type="button" disabled={props.transitionTarget!==null} onClick={()=>transition(selected,target)}>{props.transitionTarget===target?t("profiles.transitioning"):transitionLabel(target)}</button>)}</div>{visibleTransitions(selected.status).includes("archived")&&<div className="assistant-profile-actions__danger"><button className="button button--danger-quiet" type="button" disabled={props.transitionTarget!==null} onClick={()=>transition(selected,"archived")}>{props.transitionTarget==="archived"?t("profiles.transitioning"):transitionLabel("archived")}</button></div>}</div>
          {props.workspaceId&&props.companyId&&props.companyName&&<AssistantPreviewPanel csrf={props.csrf} workspaceId={props.workspaceId} companyId={props.companyId} companyName={props.companyName} profile={selected} allowed={previewAllowed(props.workspaceRole)}/>}
          {props.workspaceId&&props.companyId&&props.companyName&&<OperationalAssistantExecutionPanel csrf={props.csrf} workspaceId={props.workspaceId} companyId={props.companyId} companyName={props.companyName} profile={selected} capabilities={props.capabilities}/>}</>}
      </div></div>}
    </div>
    {confirmArchive&&<div className="confirm-panel" role="group" aria-labelledby="archive-profile-title"><h3 id="archive-profile-title">{t("profiles.archiveConfirmTitle")}</h3><p>{t("profiles.archiveConfirm",{profileName:confirmArchive.name})}</p><div className="action-row"><button className="button button--danger" disabled={props.transitionTarget!==null} onClick={()=>{props.onTransition(confirmArchive,"archived");setConfirmArchive(null);}}>{t("common.confirm")}</button><button className="button button--secondary" disabled={props.transitionTarget!==null} onClick={()=>setConfirmArchive(null)}>{t("common.cancel")}</button></div></div>}
  </section>;
}
