// @vitest-environment jsdom
import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { I18nProvider } from "../i18n/I18nContext";
import { AssistantToolsPanel } from "./AssistantToolsPanel";

const json=(body:unknown,status=200):Response=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const tool=(overrides:Record<string,unknown>={})=>({id:"live_data.read",enabled:true,availability:"available",capabilityId:"live_data.read",safeReason:null,safeNextAction:null,...overrides});
const renderPanel=(props:Partial<React.ComponentProps<typeof AssistantToolsPanel>>={})=>render(<I18nProvider><AssistantToolsPanel workspaceId="workspace" companyId={1} profileId="assistant" {...props}/></I18nProvider>);
afterEach(()=>{cleanup();vi.restoreAllMocks();});

 it("renders customer-safe tool states and a capabilities link",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json({tools:[tool(),tool({id:"scheduling.get_booking",enabled:false}),tool({id:"scheduling.create_booking",availability:"unavailable",safeReason:"Configuration incomplete",safeNextAction:"Review company setup"}),tool({id:"scheduling.cancel_booking",availability:"degraded",safeReason:"Some availability remains",safeNextAction:"Try again later"}),tool({id:"future.tool"})]})));const view=renderPanel();const heading=await screen.findByRole("heading",{name:"Assistant tools"});expect(heading.closest("section")?.className).toContain("assistant-tools");expect(view.container.querySelector("ul.assistant-tools__list")).not.toBeNull();expect(view.container.querySelector("li.assistant-tool-row")).not.toBeNull();expect(view.container.querySelectorAll(".assistant-tool-row .ds-badge").length).toBeGreaterThan(1);expect(screen.getByText("Current data")).toBeTruthy();expect(screen.getAllByText("Not enabled").length).toBeGreaterThan(0);expect(screen.getByText("Enable the corresponding capability to use this tool.")).toBeTruthy();expect(screen.getByText("Configuration incomplete")).toBeTruthy();expect(screen.getByText(/Partially available/)).toBeTruthy();expect(screen.getByText("Available tool")).toBeTruthy();expect(screen.queryByText("future.tool")).toBeNull();expect(screen.getAllByRole("link",{name:"View capabilities"})[0]?.getAttribute("href")).toBe("/companies/1/assistant/assistant/capabilities");});
 it("shows loading, empty, and safe error states",async()=>{let resolve!: (value:Response)=>void;vi.stubGlobal("fetch",vi.fn().mockReturnValue(new Promise<Response>(done=>{resolve=done;})));renderPanel();expect(screen.getAllByRole("status")[0]?.textContent).toContain("Loading tools...");resolve(json({tools:[]}));expect(await screen.findByText("There are no tools to show.")).toBeTruthy();cleanup();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json({error:"private"},503)));renderPanel();expect((await screen.findByRole("alert")).textContent).toContain("We couldn't load tools. Try again.");});
it("aborts obsolete tool catalog requests",async()=>{let first:AbortSignal|undefined;let calls=0;vi.stubGlobal("fetch",vi.fn().mockImplementation((_url:string,options:RequestInit)=>{calls+=1;if(calls===1){first=options.signal as AbortSignal;return new Promise<Response>(()=>{});}return Promise.resolve(json({tools:[]}));}));const view=renderPanel();view.rerender(<I18nProvider><AssistantToolsPanel workspaceId="workspace" companyId={1} profileId="next"/></I18nProvider>);expect(first?.aborted).toBe(true);await screen.findByText("There are no tools to show.");});
