import { useEffect, useState } from "react";
import { atlasApi } from "../api/atlasApi";
import { useI18n } from "../i18n/I18nContext";
import { useAuthentication } from "../state/AuthenticationContext";
import { AuthenticatedCompanyPortal } from "./AuthenticatedCompanyPortal";
import { useRouter } from "../routing/RouterProvider";

type View = "login" | "request" | "check" | "enroll" | "invitation" | "password";
export function AuthenticationPortal(): React.JSX.Element {
  const { locale } = useI18n(); const { navigate, pathname, search } = useRouter(); const { state: auth, bootstrap, login, logout, invalidate } = useAuthentication(); const es = locale === "es"; const invitationLink = pathname.includes("accept-invitation"); const hasProof = new URLSearchParams(search).has("proof"); const [view, setView] = useState<View>(hasProof && !invitationLink ? "enroll" : "login"); const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [confirmation, setConfirmation] = useState(""), [error, setError] = useState(""); const proof = (): string => new URLSearchParams(search).get("proof") ?? ""; const message = (): string => es ? "No pudimos completar la operación." : "We couldn't complete the operation."; const submit = async (action: () => Promise<void>): Promise<void> => { setError(""); try { await action(); } catch { setError(message()); } }; useEffect(() => { if (auth.status === "authenticated" && invitationLink) setView("invitation"); }, [auth.status, invitationLink]);
  if (auth.status === "booting") return <main className="auth-card"><p role="status">{es ? "Restaurando sesión…" : "Restoring session…"}</p></main>;
  if (auth.status === "retryable-error") return <main className="auth-card"><p role="alert">{auth.error}</p><button onClick={() => void bootstrap()}>{es ? "Reintentar" : "Retry"}</button></main>;
  if (auth.status === "authenticated") { if (view === "password") return <AuthForm title={es ? "Cambiar contraseña" : "Replace password"} error={error} onSubmit={(event) => { event.preventDefault(); void submit(async () => { await atlasApi.replacePassword(auth.csrfToken, String(new FormData(event.currentTarget).get("current") ?? ""), password, confirmation); invalidate(); setView("login"); }); }}><Password name="current" label={es ? "Contraseña actual" : "Current password"}/><Password value={password} onChange={setPassword} label={es ? "Nueva contraseña" : "New password"}/><Password value={confirmation} onChange={setConfirmation} label={es ? "Confirmación" : "Confirmation"}/><button>{es ? "Cambiar contraseña" : "Replace password"}</button></AuthForm>; if (invitationLink && view === "invitation") return <main className="auth-card"><h1>{es ? "Invitación al espacio" : "Workspace invitation"}</h1><button onClick={() => void submit(async () => { await atlasApi.acceptInvitation(auth.csrfToken, proof()); navigate("/", { replace: true }); setView("login"); })}>{es ? "Aceptar" : "Accept"}</button><button onClick={() => void submit(async () => { await atlasApi.rejectInvitation(auth.csrfToken, proof()); navigate("/", { replace: true }); setView("login"); })}>{es ? "Rechazar" : "Reject"}</button>{error && <p role="alert">{error}</p>}</main>; return <AuthenticatedCompanyPortal csrf={auth.csrfToken} email={auth.identity.email} onPassword={() => setView("password")} onLogout={() => void submit(logout)}/>; }
  if (view === "check") return <main className="auth-card"><h1>{es ? "Revisá tu correo" : "Check your email"}</h1><p>{es ? "Si la identidad es elegible, enviamos un enlace." : "If the identity is eligible, we sent a link."}</p><button onClick={() => setView("login")}>{es ? "Volver" : "Back"}</button></main>;
  if (view === "enroll") return <AuthForm title={es ? "Crear contraseña" : "Create password"} error={error} onSubmit={(event) => { event.preventDefault(); void submit(async () => { await atlasApi.completeCredentialEnrollment(proof(), password, confirmation); navigate("/", { replace: true }); setView("login"); }); }}><Password value={password} onChange={setPassword} label={es ? "Contraseña" : "Password"}/><Password value={confirmation} onChange={setConfirmation} label={es ? "Confirmación" : "Confirmation"}/><button>{es ? "Crear contraseña" : "Create password"}</button></AuthForm>;
  if (view === "request") return <AuthForm title={es ? "Inscribir una contraseña" : "Enroll a password"} error={error} onSubmit={(event) => { event.preventDefault(); void submit(async () => { await atlasApi.requestCredentialEnrollment(email); setView("check"); }); }}><label>{es ? "Correo electrónico" : "Email"}<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)}/></label><button>{es ? "Enviar enlace" : "Send link"}</button></AuthForm>;
  return <AuthForm title={es ? "Iniciar sesión" : "Log in"} error={error || auth.error || ""} onSubmit={(event) => { event.preventDefault(); void submit(async () => { await login(email, password); }); }}><label>{es ? "Correo electrónico" : "Email"}<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)}/></label><Password value={password} onChange={setPassword} label={es ? "Contraseña" : "Password"}/><button>{es ? "Ingresar" : "Log in"}</button><button type="button" onClick={() => setView("request")}>{es ? "Crear contraseña" : "Enroll password"}</button></AuthForm>;
}
function AuthForm({ title, error, onSubmit, children }: { title: string; error: string; onSubmit: React.FormEventHandler<HTMLFormElement>; children: React.ReactNode }): React.JSX.Element { return <main className="auth-card"><form onSubmit={onSubmit}><h1>{title}</h1>{error && <p role="alert">{error}</p>}{children}</form></main>; }
function Password({ label, name = "password", value, onChange }: { label: string; name?: string; value?: string; onChange?: (value: string) => void }): React.JSX.Element { return <label>{label}<input name={name} type="password" required value={value} onChange={onChange ? (event) => onChange(event.target.value) : undefined}/></label>; }
