import { useState } from "react";
import { atlasApi } from "../api/atlasApi";
import { useI18n } from "../i18n/I18nContext";

type View="login"|"request"|"check"|"enroll"|"authenticated"|"password";
export function AuthenticationPortal():React.JSX.Element{
  const {locale}=useI18n();const es=locale==="es";const [view,setView]=useState<View>(new URLSearchParams(location.search).has("proof")?"enroll":"login");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirmation,setConfirmation]=useState("");const [csrf,setCsrf]=useState("");const [identity,setIdentity]=useState<{email:string}|null>(null);const [error,setError]=useState("");
  const submit=async(action:()=>Promise<void>):Promise<void>=>{setError("");try{await action();}catch{setError(es?"No pudimos completar la operación.":"We couldn't complete the operation.");}};
  if(view==="authenticated"&&identity)return <main className="auth-card"><h1>{es?"Identidad autenticada":"Authenticated identity"}</h1><p>{identity.email}</p><p>{es?"Todavía no tenés acceso a un espacio de trabajo.":"You don't have Workspace access yet."}</p><button onClick={()=>setView("password")}>{es?"Cambiar contraseña":"Replace password"}</button><button onClick={()=>void submit(async()=>{await atlasApi.logout(csrf);setCsrf("");setIdentity(null);setView("login");})}>{es?"Cerrar sesión":"Log out"}</button></main>;
  if(view==="password")return <AuthForm title={es?"Cambiar contraseña":"Replace password"} error={error} onSubmit={e=>{e.preventDefault();void submit(async()=>{await atlasApi.replacePassword(csrf,(new FormData(e.currentTarget).get("current")??"").toString(),password,confirmation);setView("login");});}}><Password name="current" label={es?"Contraseña actual":"Current password"}/><Password value={password} onChange={setPassword} label={es?"Nueva contraseña":"New password"}/><Password value={confirmation} onChange={setConfirmation} label={es?"Confirmación":"Confirmation"}/><button>{es?"Cambiar contraseña":"Replace password"}</button></AuthForm>;
  if(view==="check")return <main className="auth-card"><h1>{es?"Revisá tu correo":"Check your email"}</h1><p>{es?"Si la identidad es elegible, enviamos un enlace de inscripción.":"If the identity is eligible, we sent an enrollment link."}</p><button onClick={()=>setView("login")}>{es?"Volver":"Back"}</button></main>;
  if(view==="enroll")return <AuthForm title={es?"Crear contraseña":"Create password"} error={error} onSubmit={e=>{e.preventDefault();void submit(async()=>{await atlasApi.completeCredentialEnrollment(new URLSearchParams(location.search).get("proof")??"",password,confirmation);history.replaceState({},"","/");setView("login");});}}><Password value={password} onChange={setPassword} label={es?"Contraseña":"Password"}/><Password value={confirmation} onChange={setConfirmation} label={es?"Confirmación":"Confirmation"}/><button>{es?"Crear contraseña":"Create password"}</button></AuthForm>;
  if(view==="request")return <AuthForm title={es?"Inscribir una contraseña":"Enroll a password"} error={error} onSubmit={e=>{e.preventDefault();void submit(async()=>{await atlasApi.requestCredentialEnrollment(email);setView("check");});}}><label>{es?"Correo electrónico":"Email"}<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button>{es?"Enviar enlace":"Send link"}</button></AuthForm>;
  return <AuthForm title={es?"Iniciar sesión":"Log in"} error={error} onSubmit={e=>{e.preventDefault();void submit(async()=>{const result=await atlasApi.login(email,password);setCsrf(result.csrfToken);const me=await atlasApi.currentIdentity();setIdentity(me);setView("authenticated");});}}><label>{es?"Correo electrónico":"Email"}<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><Password value={password} onChange={setPassword} label={es?"Contraseña":"Password"}/><button>{es?"Ingresar":"Log in"}</button><button type="button" onClick={()=>setView("request")}>{es?"Crear contraseña":"Enroll password"}</button></AuthForm>;
}
function AuthForm({title,error,onSubmit,children}:{title:string;error:string;onSubmit:React.FormEventHandler<HTMLFormElement>;children:React.ReactNode}):React.JSX.Element{return <main className="auth-card"><form onSubmit={onSubmit}><h1>{title}</h1>{error&&<p role="alert">{error}</p>}{children}</form></main>;}
function Password({label,name="password",value,onChange}:{label:string;name?:string;value?:string;onChange?:(v:string)=>void}):React.JSX.Element{return <label>{label}<input name={name} type="password" autoComplete={name==="current"?"current-password":"new-password"} required value={value} onChange={onChange?e=>onChange(e.target.value):undefined}/></label>;}
