import { useEffect, useRef, useState } from "react";
import { ApiError, atlasApi } from "../api/atlasApi";
import { useI18n } from "../i18n/I18nContext";
import type { CustomerBillingManagementActions, CustomerBillingOffer, CustomerBillingPayerIdentities, CustomerBillingSummary, WorkspaceSummary } from "../types/api";
import { ContextBackLink } from "./ContextBackLink";
import { Alert, Button, ConfirmDialog, EmptyState, LoadingState, Select } from "../design-system/primitives";

interface Props { csrf:string; workspace:WorkspaceSummary|null; search:string; pathname:string; onNavigateDashboard?:()=>void; }
type Data={summary:CustomerBillingSummary;offers:CustomerBillingOffer[];actions:CustomerBillingManagementActions;payers:CustomerBillingPayerIdentities};
type Notice={message:string;tone:"success"|"warning"|"danger"|"info"};
function aborted(error:unknown):boolean{return error instanceof DOMException&&error.name==="AbortError";}
function money(amountMinor:number,currency:string,locale:string):string{return new Intl.NumberFormat(locale,{style:"currency",currency}).format(amountMinor/100);}
function limit(value:number|null):string{return value===null?"-":String(value);}
function idempotencyKey():string{return crypto.randomUUID();}

export function BillingPage({csrf,workspace,search,pathname,onNavigateDashboard}:Props):React.JSX.Element{
  const {t,locale,formatDate}=useI18n(),[data,setData]=useState<Data|null>(null),[error,setError]=useState(false),[loading,setLoading]=useState(false),[pending,setPending]=useState<string|null>(null),[notice,setNotice]=useState<Notice|null>(null),[confirmCancel,setConfirmCancel]=useState(false),request=useRef(0),abort=useRef<AbortController|null>(null),operationLock=useRef(false),canManage=workspace?.capabilities.includes("workspace:manage")===true;
  const load=async(retry=false):Promise<void>=>{abort.current?.abort();if(!workspace){setData(null);setLoading(false);return;}const controller=new AbortController(),id=++request.current;abort.current=controller;setLoading(true);setError(false);try{const [summary,offers,actions,payers]=await Promise.all([atlasApi.getBillingSummary(workspace.id,controller.signal),atlasApi.getBillingOffers(workspace.id,controller.signal),atlasApi.getBillingManagementActions(workspace.id,controller.signal),canManage?atlasApi.getBillingPayerIdentities(workspace.id,controller.signal):Promise.resolve({options:[],selectedEmail:null})]);if(id===request.current&&!controller.signal.aborted)setData({summary,offers,actions,payers});}catch(cause){if(!aborted(cause)&&id===request.current)setError(true);}finally{if(id===request.current&&!controller.signal.aborted)setLoading(false);}if(retry&&id===request.current&&!controller.signal.aborted)window.setTimeout(()=>{if(id===request.current)void load(false);},1_500);};
  useEffect(()=>{operationLock.current=false;void load();return()=>abort.current?.abort();},[workspace?.id,canManage]);
  useEffect(()=>{const params=new URLSearchParams(search),returned=params.get("checkout")??(pathname.endsWith("/checkout/success")?"success":pathname.endsWith("/checkout/cancel")?"cancel":pathname.endsWith("/portal/return")?"portal":null);if((returned==="success"||returned==="cancel"||returned==="portal")&&workspace){setNotice({message:returned==="cancel"?t("billing.cancelled"):returned==="portal"?t("billing.updated"):t("billing.returned"),tone:returned==="cancel"?"warning":"info"});void load(returned==="success"||returned==="portal");}},[search,pathname,workspace?.id]);
  const perform=async(kind:"checkout"|"portal"|"cancel"|"reactivate",offerId?:string):Promise<void>=>{if(!workspace||operationLock.current)return;operationLock.current=true;const controller=new AbortController();setPending(kind);setNotice(null);let reconciliationPending=false;try{const result=kind==="checkout"?await atlasApi.checkoutBillingOffer(csrf,workspace.id,offerId!,idempotencyKey(),controller.signal):kind==="portal"?await atlasApi.openBillingPortal(csrf,workspace.id,controller.signal):kind==="cancel"?await atlasApi.cancelBillingSubscription(csrf,workspace.id,idempotencyKey(),controller.signal):await atlasApi.reactivateBillingSubscription(csrf,workspace.id,idempotencyKey(),controller.signal);if(result.redirectUrl){window.location.assign(result.redirectUrl);return;}reconciliationPending=result.status==="in_progress"||result.status==="uncertain";setNotice(reconciliationPending?{message:t("billing.confirmationPending"),tone:"info"}:result.status==="succeeded"?{message:t("billing.updated"),tone:"success"}:{message:t("billing.actionUnavailable"),tone:"warning"});if(result.status==="succeeded"||reconciliationPending)void load(reconciliationPending);}catch(cause){setNotice(cause instanceof ApiError&&cause.status===409?{message:t("billing.actionUnavailable"),tone:"warning"}:{message:t("billing.error"),tone:"danger"});}finally{if(!reconciliationPending){operationLock.current=false;setPending(null);}}};
  const setPayer=async(identityId:string|null):Promise<void>=>{if(!workspace||!data||pending)return;const selected=data.payers.options.find(option=>option.email===data.payers.selectedEmail);if(identityId===null&&!selected)return;setPending("payer");setNotice(null);try{const result=identityId===null?await atlasApi.clearBillingPayerIdentity(csrf,workspace.id,selected!.identityId):await atlasApi.setBillingPayerIdentity(csrf,workspace.id,identityId);setNotice(result.status==="succeeded"?{message:t("billing.updated"),tone:"success"}:{message:t("billing.actionUnavailable"),tone:"warning"});void load(result.status!=="succeeded");}catch(cause){setNotice(cause instanceof ApiError&&cause.status===409?{message:t("billing.actionUnavailable"),tone:"warning"}:{message:t("billing.error"),tone:"danger"});}finally{setPending(null);}};
  if(!workspace)return <section className="billing-page"><EmptyState title={t("billing.title")} description={t("billing.workspaceRequired")}/></section>;
  if(loading&&!data)return <section className="billing-page"><LoadingState title={t("billing.loading")}/></section>;
  if(error&&!data)return <section className="billing-page"><Alert tone="danger">{t("billing.error")}<Button variant="secondary" onClick={()=>void load()}>{t("common.retry")}</Button></Alert></section>;
  if(!data)return <section className="billing-page"><h1>{t("billing.title")}</h1></section>;
  const actions=data.actions.actions,checkoutAllowed=canManage&&data.summary.capabilities.canStartNewCheckout&&data.summary.subscription.state!=="reconciliation_required",actionsDisabled=!canManage||pending!==null||data.summary.subscription.state==="reconciliation_required",selectedPayer=data.payers.options.find(option=>option.email===data.payers.selectedEmail)??null;
  return <section className="billing-page">{onNavigateDashboard&&<ContextBackLink href="/dashboard" label={t("billing.backToDashboard")} onNavigate={event=>{event.preventDefault();onNavigateDashboard();}}/>}<header className="work-anchor"><p className="atlas-eyebrow">{t("billing.eyebrow")}</p><h1>{t("billing.title")}</h1><p>{t("billing.lead")}</p></header>{notice&&<Alert tone={notice.tone}>{notice.message}</Alert>}{data.summary.subscription.state==="reconciliation_required"&&<Alert tone="info">{t("billing.confirmationPending")}</Alert>}{error&&<Alert tone="danger">{t("billing.error")}</Alert>}
     <section className="billing-summary" aria-labelledby="billing-current"><div><p className="atlas-eyebrow">{t("billing.currentPlan")}</p><h2 id="billing-current">{data.summary.subscription.plan?.name??t("billing.noPlan")}</h2><p>{t(`billing.state.${data.summary.subscription.state}`)}</p>{data.summary.subscription.plan&&<strong>{money(data.summary.subscription.plan.amountMinor,data.summary.subscription.plan.currency,locale)} / {t(`billing.interval.${data.summary.subscription.plan.interval}`)}</strong>}</div><div className="billing-actions">{actions.includes("portal")&&<Button variant="secondary" disabled={actionsDisabled} onClick={()=>void perform("portal")}>{t("billing.portal")}</Button>}{actions.includes("cancel")&&<Button variant="danger" disabled={actionsDisabled} onClick={()=>setConfirmCancel(true)}>{t("billing.cancel")}</Button>}{actions.includes("reactivate")&&<Button disabled={actionsDisabled} onClick={()=>void perform("reactivate")}>{t("billing.reactivate")}</Button>}{!canManage&&<p role="status">{t("billing.readOnly")}</p>}</div></section>
    {canManage&&<section className="billing-payer" aria-labelledby="billing-payer"><h2 id="billing-payer">{t("billing.payer.title")}</h2><p>{selectedPayer?selectedPayer.email:t("billing.payer.selectBeforeArs")}</p>{data.payers.options.length>0?<><label htmlFor="billing-payer-select">{t("billing.payer.verifiedEmail")}</label><Select id="billing-payer-select" value={selectedPayer?.identityId??""} disabled={pending!==null} onChange={event=>{if(event.target.value)void setPayer(event.target.value);}}><option value="">{t("billing.payer.selectEmail")}</option>{data.payers.options.map(option=><option key={option.identityId} value={option.identityId}>{option.email}</option>)}</Select>{selectedPayer&&<Button variant="secondary" disabled={pending!==null} onClick={()=>void setPayer(null)}>{t("billing.payer.clear")}</Button>}</>:<p>{t("billing.payer.unavailable")}</p>}</section>}
    <section className="billing-entitlement"><h2>{t("billing.entitlement")}</h2>{data.summary.entitlement?<><p>{data.summary.entitlement.mutationEligible?t("billing.entitled"):t("billing.notEntitled")}</p><dl><div><dt>{t("billing.companies")}</dt><dd>{limit(data.summary.entitlement.maxCompanies)}</dd></div><div><dt>{t("billing.assistants")}</dt><dd>{limit(data.summary.entitlement.maxAssistantProfiles)}</dd></div><div><dt>{t("billing.channels")}</dt><dd>{limit(data.summary.entitlement.maxActiveChannels)}</dd></div></dl><small>{t("billing.effective",{date:formatDate(data.summary.entitlement.effectiveAt)})}</small></>:<p>{t("billing.noEntitlement")}</p>}</section>
    <section><header className="section-heading"><div><p className="atlas-eyebrow">{t("billing.plans")}</p><h2>{t("billing.choosePlan")}</h2><p>{t("billing.noFx")}</p></div></header><div className="billing-offer-groups">{(["USD","ARS"] as const).map(currency=>{const offers=data.offers.filter(offer=>offer.currency===currency);return offers.length?<section key={currency} aria-label={currency}><h3>{currency}</h3><div className="billing-offers">{offers.map(offer=><article className="billing-offer" key={offer.offerId}><div><h4>{offer.name}</h4><p>{offer.description}</p><strong>{money(offer.amountMinor,offer.currency,locale)} / {t(`billing.interval.${offer.interval}`)}</strong>{offer.inclusions.length>0&&<ul>{offer.inclusions.map(item=><li key={item.code}>{item.title}</li>)}</ul>}</div><Button disabled={!checkoutAllowed||!offer.checkoutAvailable||pending!==null||(offer.provider==="mercadopago"&&!selectedPayer)} onClick={()=>void perform("checkout",offer.offerId)}>{t("billing.select")}</Button></article>)}</div></section>:null;})}</div></section>
    <ConfirmDialog cancelLabel={t("common.cancel")} confirmLabel={t("billing.cancel")} description={t("billing.cancelConfirmation")} open={confirmCancel} title={t("billing.cancel")} onCancel={()=>setConfirmCancel(false)} onConfirm={()=>{setConfirmCancel(false);void perform("cancel");}}/>
  </section>;
}
