// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import { ApiError, atlasApi } from "../api/atlasApi";
import { I18nProvider } from "../i18n/I18nContext";
import type { CustomerBillingOffer, CustomerBillingSummary, WorkspaceSummary } from "../types/api";
import { BillingPage } from "./BillingPage";

const capabilities={canOpenBillingPortal:true,canCancel:true,canReactivate:false,canStartNewCheckout:true,canSwitchProvider:false} as const;
const summary={rolloutMode:"managed" as const,subscription:{state:"active" as const,plan:{key:"starter",name:"Starter",interval:"month" as const,currency:"USD",amountMinor:1200}},entitlement:null,capabilities};
const offer={offerId:"offer",provider:"stripe" as const,key:"starter",version:1,name:"Starter",description:"For small teams",inclusions:[],interval:"month" as const,currency:"USD",amountMinor:1200,checkoutAvailable:true};
const workspace=(id:string,manage=false):WorkspaceSummary=>({id,name:id,role:"owner",capabilities:manage?["workspace:manage"]:[]});
const renderBilling=(props:Partial<React.ComponentProps<typeof BillingPage>>={})=>render(<I18nProvider><BillingPage csrf="csrf" workspace={workspace("one",true)} search="" pathname="/billing" {...props}/></I18nProvider>);
const mockLoad=(value:CustomerBillingSummary=summary,offers:CustomerBillingOffer[]=[offer],actions:("portal"|"cancel"|"reactivate")[]=[]):void=>{vi.spyOn(atlasApi,"getBillingSummary").mockResolvedValue(value);vi.spyOn(atlasApi,"getBillingOffers").mockResolvedValue(offers);vi.spyOn(atlasApi,"getBillingManagementActions").mockResolvedValue({actions,capabilities:value.capabilities});vi.spyOn(atlasApi,"getBillingPayerIdentities").mockResolvedValue({options:[],selectedEmail:null});};
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();});

test("disables customer billing controls without workspace management and separates currencies",async()=>{vi.spyOn(atlasApi,"getBillingSummary").mockResolvedValue(summary);vi.spyOn(atlasApi,"getBillingOffers").mockResolvedValue([offer,{...offer,offerId:"ars",provider:"mercadopago",currency:"ARS",amountMinor:2500}]);vi.spyOn(atlasApi,"getBillingManagementActions").mockResolvedValue({actions:["portal","cancel"],capabilities});render(<I18nProvider><BillingPage csrf="csrf" workspace={workspace("one")} search="" pathname="/billing"/></I18nProvider>);await screen.findByRole("heading",{name:"Starter",level:2});expect((screen.getByRole("button",{name:"Manage billing"}) as HTMLButtonElement).disabled).toBe(true);expect(screen.getAllByRole("button",{name:"Choose plan"}).every(button=>(button as HTMLButtonElement).disabled)).toBe(true);expect(screen.getByText("USD")).toBeTruthy();expect(screen.getByText("ARS")).toBeTruthy();});

test("renders the billing route current history price and USD and ARS offers without FX or provider claims",async()=>{mockLoad(summary,[offer,{...offer,offerId:"ars-offer",provider:"mercadopago",currency:"ARS",amountMinor:2500}]);renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});expect(screen.getAllByText(/\$12\.00/)).toHaveLength(2);expect(screen.getByText("USD")).toBeTruthy();expect(screen.getByText("ARS")).toBeTruthy();expect(screen.getByText("Prices are shown by currency. Atlas does not convert currencies.")).toBeTruthy();expect(document.body.textContent).not.toMatch(/stripe|mercadopago|price_[a-z]|secret/i);});

test("suppresses checkout for an active subscription when canonical capabilities disallow it",async()=>{mockLoad({...summary,capabilities:{...capabilities,canStartNewCheckout:false}},[offer],["portal"]);renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});expect((screen.getByRole("button",{name:"Choose plan"}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole("button",{name:"Manage billing"}) as HTMLButtonElement).disabled).toBe(false);});

test("lets a manager dispatch Stripe offers as opaque IDs and blocks Mercado Pago until a payer is selected",async()=>{mockLoad(summary,[offer,{...offer,offerId:"mp-offer",provider:"mercadopago",currency:"ARS",amountMinor:2500}]);const checkout=vi.spyOn(atlasApi,"checkoutBillingOffer").mockResolvedValue({status:"unavailable"});renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});const buttons=screen.getAllByRole("button",{name:"Choose plan"});fireEvent.click(buttons[0]!);await waitFor(()=>expect(checkout).toHaveBeenCalledTimes(1));expect((buttons[1] as HTMLButtonElement).disabled).toBe(true);expect(checkout.mock.calls.map(call=>call[2])).toEqual(["offer"]);expect(checkout.mock.calls.flat().join(" ")).not.toMatch(/stripe|mercadopago|price|secret/i);});

test("requires a verified payer selection for Mercado Pago and sends only its opaque identity ID",async()=>{mockLoad(summary,[offer,{...offer,offerId:"mp-offer",provider:"mercadopago",currency:"ARS",amountMinor:2500}]);vi.mocked(atlasApi.getBillingPayerIdentities).mockResolvedValue({options:[{identityId:"identity_opaque",email:"payer@example.test"}],selectedEmail:null});const set=vi.spyOn(atlasApi,"setBillingPayerIdentity").mockResolvedValue({status:"succeeded"});renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});expect((screen.getAllByRole("button",{name:"Choose plan"})[1] as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText("Verified email"),{target:{value:"identity_opaque"}});await waitFor(()=>expect(set).toHaveBeenCalledWith("csrf","one","identity_opaque"));expect(document.body.textContent).toContain("payer@example.test");expect(document.body.textContent).not.toContain("identity_opaque");});

test("offers Mercado Pago checkout only with a selected verified payer and no Stripe-only actions",async()=>{const mercadoPagoOffer={...offer,offerId:"mp-offer",provider:"mercadopago" as const,currency:"ARS",amountMinor:2500};mockLoad(summary,[mercadoPagoOffer],[]);vi.mocked(atlasApi.getBillingPayerIdentities).mockResolvedValue({options:[{identityId:"identity_opaque",email:"payer@example.test"}],selectedEmail:"payer@example.test"});renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});expect(screen.getByText("ARS")).toBeTruthy();expect((screen.getByRole("button",{name:"Choose plan"}) as HTMLButtonElement).disabled).toBe(false);expect(screen.queryByRole("button",{name:"Manage billing"})).toBeNull();expect(screen.queryByRole("button",{name:"Cancel at period end"})).toBeNull();expect(screen.queryByRole("button",{name:"Keep subscription"})).toBeNull();});

test("checkout return routes cannot fake success and refetch canonical canceled state",async()=>{mockLoad({...summary,subscription:{...summary.subscription,state:"canceled",plan:null}},[offer]);renderBilling({search:"?checkout=success",pathname:"/billing/checkout/success"});await screen.findByText("Cancelled");expect(screen.getByRole("status").textContent).toContain("returned from checkout");expect(atlasApi.getBillingSummary).toHaveBeenCalledTimes(2);});

test("checkout cancellation refreshes the canonical state without inferring a billing outcome",async()=>{mockLoad({...summary,subscription:{...summary.subscription,state:"canceled",plan:null}},[offer]);renderBilling({search:"?checkout=cancel",pathname:"/billing/checkout/cancel"});await screen.findByText("Cancelled");expect(screen.getByRole("status").textContent).toContain("cancelled");expect(atlasApi.getBillingSummary).toHaveBeenCalledTimes(2);});

test("performs one bounded reconciliation retry rather than polling checkout forever",async()=>{vi.useFakeTimers();mockLoad();renderBilling({pathname:"/billing/checkout/success"});await act(async()=>{await vi.runAllTimersAsync();});expect(atlasApi.getBillingSummary).toHaveBeenCalledTimes(3);await act(async()=>{await vi.advanceTimersByTimeAsync(60_000);});expect(atlasApi.getBillingSummary).toHaveBeenCalledTimes(3);});

test("portal return refreshes canonical billing state without inferring an entitlement",async()=>{mockLoad({...summary,subscription:{...summary.subscription,state:"canceling_at_period_end"}},[offer],["portal"]);renderBilling({pathname:"/billing/portal/return"});await screen.findByText("Cancels at period end");expect(atlasApi.getBillingSummary).toHaveBeenCalledTimes(2);expect(screen.queryByText("Active")).toBeNull();});

test("handles an HTTP 409 checkout conflict safely and leaves canonical billing controls available",async()=>{mockLoad(summary,[offer]);const checkout=vi.spyOn(atlasApi,"checkoutBillingOffer").mockRejectedValue(new ApiError(409,"changed"));renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});fireEvent.click(screen.getByRole("button",{name:"Choose plan"}));await screen.findByText("This action is no longer available. Review the current status.");expect(checkout).toHaveBeenCalledTimes(1);expect((screen.getByRole("button",{name:"Choose plan"}) as HTMLButtonElement).disabled).toBe(false);});

test("confirms cancellation before dispatching the billing action",async()=>{mockLoad(summary,[offer],["cancel"]);const cancel=vi.spyOn(atlasApi,"cancelBillingSubscription").mockResolvedValue({status:"succeeded"});renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});fireEvent.click(screen.getByRole("button",{name:"Cancel at period end"}));expect(cancel).not.toHaveBeenCalled();const dialog=screen.getByRole("alertdialog");fireEvent.click(within(dialog).getByRole("button",{name:"Cancel at period end"}));await waitFor(()=>expect(cancel).toHaveBeenCalledWith("csrf","one",expect.any(String),expect.any(AbortSignal)));});

test("announces failed operations as errors rather than successful updates",async()=>{mockLoad(summary,[offer]);vi.spyOn(atlasApi,"checkoutBillingOffer").mockRejectedValue(new Error("offline"));renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});fireEvent.click(screen.getByRole("button",{name:"Choose plan"}));expect((await screen.findByRole("alert")).textContent).toContain("couldn't load billing");});

test("keeps validation, authorization, rate-limit, and provider failures customer-safe",async()=>{for(const status of [400,401,403,429,503]){mockLoad(summary,[offer]);vi.spyOn(atlasApi,"checkoutBillingOffer").mockRejectedValue(new ApiError(status,"provider_secret"));renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});fireEvent.click(screen.getByRole("button",{name:"Choose plan"}));const alert=await screen.findByRole("alert");expect(alert.textContent).toContain("couldn't load billing");expect(alert.textContent).not.toContain("provider_secret");cleanup();vi.restoreAllMocks();}});

test("holds checkout controls after an uncertain operation instead of creating a replacement",async()=>{mockLoad(summary,[offer]);const checkout=vi.spyOn(atlasApi,"checkoutBillingOffer").mockResolvedValue({status:"uncertain"});renderBilling();await screen.findByRole("heading",{name:"Starter",level:2});const button=screen.getByRole("button",{name:"Choose plan"});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(checkout).toHaveBeenCalledTimes(1));expect((await screen.findByRole("status")).textContent).toContain("confirming the billing status");expect((screen.getByRole("button",{name:"Choose plan"}) as HTMLButtonElement).disabled).toBe(true);});

test("aborts stale workspace reads before applying the next workspace",async()=>{let signal:AbortSignal|undefined;const stalled=new Promise<typeof summary>(()=>{});vi.spyOn(atlasApi,"getBillingSummary").mockImplementationOnce((_id,nextSignal)=>{signal=nextSignal;return stalled;}).mockResolvedValue(summary);vi.spyOn(atlasApi,"getBillingOffers").mockResolvedValue([offer]);vi.spyOn(atlasApi,"getBillingManagementActions").mockResolvedValue({actions:[],capabilities});vi.spyOn(atlasApi,"getBillingPayerIdentities").mockResolvedValue({options:[],selectedEmail:null});const view=render(<I18nProvider><BillingPage csrf="csrf" workspace={workspace("old",true)} search="" pathname="/billing"/></I18nProvider>);view.rerender(<I18nProvider><BillingPage csrf="csrf" workspace={workspace("new",true)} search="" pathname="/billing"/></I18nProvider>);await screen.findByRole("heading",{name:"Starter",level:2});expect(signal?.aborted).toBe(true);});

test("uses the plans eyebrow and exposes a standardized dashboard link in Spanish",async()=>{window.localStorage.setItem("atlas.locale","es");mockLoad();const back=vi.fn();render(<I18nProvider><BillingPage csrf="csrf" workspace={workspace("one",true)} search="" pathname="/billing" onNavigateDashboard={back}/></I18nProvider>);const eyebrow=await screen.findByText("Planes disponibles");expect(eyebrow.textContent?.toUpperCase()).toBe("PLANES DISPONIBLES");expect(document.body.textContent).not.toContain("AVIONES DISPONIBLES");const link=screen.getByRole("link",{name:"Volver al inicio"});expect(link.getAttribute("href")).toBe("/dashboard");fireEvent.click(link);expect(back).toHaveBeenCalledTimes(1);});
