import { useEffect, useRef, useState } from "react";
import { ApiError, atlasApi } from "../api/atlasApi";
import { useI18n } from "../i18n/I18nContext";
import type { CustomerBillingManagementActions, CustomerBillingOffer, CustomerBillingSummary, WorkspaceSummary } from "../types/api";
import { ContextBackLink } from "./ContextBackLink";
import { Alert, Button, EmptyState, LoadingState, Surface } from "../design-system/primitives";

interface Props { csrf:string; workspace:WorkspaceSummary|null; search:string; pathname:string; onNavigateDashboard?:()=>void; }
type Data={summary:CustomerBillingSummary;offers:CustomerBillingOffer[];actions:CustomerBillingManagementActions};
function aborted(error:unknown):boolean{return error instanceof DOMException&&error.name==="AbortError";}
function money(amountMinor:number,currency:string,locale:string):string{return new Intl.NumberFormat(locale,{style:"currency",currency}).format(amountMinor/100);}
function limit(value:number|null):string{return value===null?"-":String(value);}
function idempotencyKey():string{return crypto.randomUUID();}

export function BillingPage({csrf,workspace,search,pathname,onNavigateDashboard}:Props):React.JSX.Element{
  const {t,locale,formatDate}=useI18n(),[data,setData]=useState<Data|null>(null),[error,setError]=useState(false),[loading,setLoading]=useState(false),[pending,setPending]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),request=useRef(0),abort=useRef<AbortController|null>(null);
  const load=async(retry=false):Promise<void>=>{abort.current?.abort();if(!workspace){setData(null);setLoading(false);return;}const controller=new AbortController(),id=++request.current;abort.current=controller;setLoading(true);setError(false);try{const [summary,offers,actions]=await Promise.all([atlasApi.getBillingSummary(workspace.id,controller.signal),atlasApi.getBillingOffers(workspace.id,controller.signal),atlasApi.getBillingManagementActions(workspace.id,controller.signal)]);if(id===request.current&&!controller.signal.aborted)setData({summary,offers,actions});}catch(cause){if(!aborted(cause)&&id===request.current)setError(true);}finally{if(id===request.current&&!controller.signal.aborted)setLoading(false);}
    if(retry&&id===request.current&&!controller.signal.aborted)window.setTimeout(()=>{if(id===request.current)void load(false);},1_500);
  };
  useEffect(()=>{void load();return()=>abort.current?.abort();},[workspace?.id]);
  useEffect(()=>{const params=new URLSearchParams(search),returned=params.get("checkout")??(pathname.endsWith("/checkout/success")?"success":pathname.endsWith("/checkout/cancel")?"cancel":null);if((returned==="success"||returned==="cancel")&&workspace){setNotice(returned==="success"?t("billing.returned"):t("billing.cancelled"));void load(returned==="success");}},[search,pathname,workspace?.id]);
  const perform=async(kind:"checkout"|"portal"|"cancel"|"reactivate",offerId?:string):Promise<void>=>{if(!workspace||pending)return;const controller=new AbortController();setPending(kind);setNotice(null);try{const result=kind==="checkout"?await atlasApi.checkoutBillingOffer(csrf,workspace.id,offerId!,idempotencyKey(),controller.signal):kind==="portal"?await atlasApi.openBillingPortal(csrf,workspace.id,controller.signal):kind==="cancel"?await atlasApi.cancelBillingSubscription(csrf,workspace.id,idempotencyKey(),controller.signal):await atlasApi.reactivateBillingSubscription(csrf,workspace.id,idempotencyKey(),controller.signal);if(result.redirectUrl){window.location.assign(result.redirectUrl);return;}setNotice(result.status==="succeeded"?t("billing.updated"):t("billing.actionUnavailable"));if(result.status==="succeeded"||result.status==="in_progress"||result.status==="uncertain")void load(result.status!=="succeeded");}catch(cause){setNotice(cause instanceof ApiError&&cause.status===409?t("billing.actionUnavailable"):t("billing.error"));}finally{setPending(null);}};
   if(!workspace)return <section className="billing-page"><EmptyState title={t("billing.title")} description={t("billing.workspaceRequired")}/></section>;
   if(loading&&!data)return <section className="billing-page"><LoadingState title={t("billing.loading")}/></section>;
   if(error&&!data)return <section className="billing-page"><Alert tone="danger">{t("billing.error")}<Button variant="secondary" onClick={()=>void load()}>{t("common.retry")}</Button></Alert></section>;
  if(!data)return <section className="billing-page"><h1>{t("billing.title")}</h1></section>;
  const canManage=workspace.capabilities.includes("workspace:manage"),actions=data.actions.actions,checkoutAllowed=canManage&&data.summary.capabilities.canStartNewCheckout;
   return <section className="billing-page">{onNavigateDashboard&&<ContextBackLink href="/dashboard" label="Volver al inicio" onNavigate={event=>{event.preventDefault();onNavigateDashboard();}}/>}<header className="work-anchor"><p className="atlas-eyebrow">{t("billing.eyebrow")}</p><h1>{t("billing.title")}</h1><p>{t("billing.lead")}</p></header>{notice&&<Alert tone="success">{notice}</Alert>}{error&&<Alert tone="danger">{t("billing.error")}</Alert>}
    <section className="billing-summary" aria-labelledby="billing-current"><div><p className="atlas-eyebrow">{t("billing.currentPlan")}</p><h2 id="billing-current">{data.summary.subscription.plan?.name??t("billing.noPlan")}</h2><p>{t(`billing.state.${data.summary.subscription.state}`)}</p>{data.summary.subscription.plan&&<strong>{money(data.summary.subscription.plan.amountMinor,data.summary.subscription.plan.currency,locale)} / {t(`billing.interval.${data.summary.subscription.plan.interval}`)}</strong>}</div><div className="billing-actions">{actions.includes("portal")&&<Button variant="secondary" disabled={!canManage||pending!==null} onClick={()=>void perform("portal")}>{t("billing.portal")}</Button>}{actions.includes("cancel")&&<Button variant="danger" disabled={!canManage||pending!==null} onClick={()=>void perform("cancel")}>{t("billing.cancel")}</Button>}{actions.includes("reactivate")&&<Button disabled={!canManage||pending!==null} onClick={()=>void perform("reactivate")}>{t("billing.reactivate")}</Button>}{!canManage&&<p role="status">{t("billing.readOnly")}</p>}</div></section>
    <section className="billing-entitlement"><h2>{t("billing.entitlement")}</h2>{data.summary.entitlement?<><p>{data.summary.entitlement.mutationEligible?t("billing.entitled"):t("billing.notEntitled")}</p><dl><div><dt>{t("billing.companies")}</dt><dd>{limit(data.summary.entitlement.maxCompanies)}</dd></div><div><dt>{t("billing.assistants")}</dt><dd>{limit(data.summary.entitlement.maxAssistantProfiles)}</dd></div><div><dt>{t("billing.channels")}</dt><dd>{limit(data.summary.entitlement.maxActiveChannels)}</dd></div></dl><small>{t("billing.effective",{date:formatDate(data.summary.entitlement.effectiveAt)})}</small></>:<p>{t("billing.noEntitlement")}</p>}</section>
    <section><header className="section-heading"><div><p className="atlas-eyebrow">{t("billing.plans")}</p><h2>{t("billing.choosePlan")}</h2><p>{t("billing.noFx")}</p></div></header><div className="billing-offer-groups">{(["USD","ARS"] as const).map(currency=>{const offers=data.offers.filter(offer=>offer.currency===currency);return offers.length?<section key={currency} aria-label={currency}><h3>{currency}</h3><div className="billing-offers">{offers.map(offer=><article className="billing-offer" key={offer.offerId}><div><h4>{offer.name}</h4><p>{offer.description}</p><strong>{money(offer.amountMinor,offer.currency,locale)} / {t(`billing.interval.${offer.interval}`)}</strong>{offer.inclusions.length>0&&<ul>{offer.inclusions.map(item=><li key={item.code}>{item.title}</li>)}</ul>}</div><Button disabled={!checkoutAllowed||!offer.checkoutAvailable||pending!==null} onClick={()=>void perform("checkout",offer.offerId)}>{t("billing.select")}</Button></article>)}</div></section>:null;})}</div></section>
  </section>;
}
