// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { I18nProvider } from "../i18n/I18nContext";
import { CompanyKnowledgePanel } from "./CompanyKnowledgePanel";

const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});
const unavailable=()=>json({error:{code:"knowledge_unavailable",message:"missing"}},404);
const revision={id:"ksrv_a",sourceId:"ksrc_a",revisionNumber:1,status:"ready" as const,mediaType:"text/plain",normalizedText:"normalized safe facts",extractedKnowledge:{services:["Service"],hours:"Always",locations:["Remote"],faq:[]},failureCode:null,createdAt:"2026-01-01T00:00:00.000Z",completedAt:"2026-01-01T00:00:01.000Z"};
const source=(kind:"manual_text"|"public_url"|"pdf"="manual_text")=>({id:"ksrc_a",companyId:1,kind,name:"Facts",locator:kind==="public_url"?"https://example.com":null,status:"active" as const,version:1,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null,latestRevision:{...revision,mediaType:kind==="pdf"?"application/pdf":"text/plain"},includedRevisionId:null});
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((ok,fail)=>{resolve=ok;reject=fail;});return{promise,resolve,reject};}

afterEach(()=>{cleanup();vi.restoreAllMocks();});

describe("CompanyKnowledgePanel",()=>{
  it("derives accessible controls from server capabilities and never exposes raw enums",async()=>{
    vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>String(input).endsWith("/knowledge/sources")?json([]):unavailable()));
    render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest","knowledge:publish","knowledge:archive"]}/></I18nProvider>);
    expect(await screen.findByRole("heading",{name:"Company Knowledge"})).toBeTruthy();
    expect(screen.getByRole("button",{name:"Manual Text"})).toBeTruthy();
    expect(screen.getByRole("button",{name:"Public URL"})).toBeTruthy();
    expect(screen.getByRole("button",{name:"PDF"})).toBeTruthy();
    expect((screen.getByRole("button",{name:"Publish selection"})as HTMLButtonElement).disabled).toBe(true);
    expect(screen.queryByText("manual_text")).toBeNull();
  });

  it("keeps Viewer read-only while Operator can ingest but cannot publish or archive",async()=>{
    const fetcher=vi.fn(async(input:string|URL|Request)=>String(input).endsWith("/knowledge/sources")?json([]):unavailable());vi.stubGlobal("fetch",fetcher);
    const view=render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read"]}/></I18nProvider>);
    await screen.findByRole("heading",{name:"Company Knowledge"});expect(screen.queryByRole("button",{name:"Manual Text"})).toBeNull();view.unmount();
    render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);
    await screen.findByRole("button",{name:"Manual Text"});expect(screen.queryByRole("button",{name:"Publish selection"})).toBeNull();
  });

  it.each([{mode:"Manual Text",value:"facts",path:"/manual"},{mode:"Public URL",value:"https://example.com",path:"/url"}])("creates $mode and clears sensitive input",async({mode,value,path})=>{
    const calls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==="POST"){calls.push(url);return json({source:{},revision:{}},201);}return url.endsWith("/knowledge/sources")?json([]):unavailable();}));
    render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);await screen.findByRole("button",{name:mode});fireEvent.click(screen.getByRole("button",{name:mode}));
    fireEvent.change(screen.getByLabelText("Source name"),{target:{value:"Facts"}});fireEvent.change(screen.getByLabelText(mode==="Manual Text"?/Text/:"Public URL"),{target:{value}});fireEvent.click(screen.getByRole("button",{name:"Ingest source"}));
    await waitFor(()=>expect(calls.some(url=>url.endsWith(path))).toBe(true));await waitFor(()=>expect((screen.getByLabelText("Source name")as HTMLInputElement).value).toBe(""));
  });

  it("uses Unicode code-point validation rather than UTF-16 maxLength",async()=>{
    vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>String(input).endsWith("/knowledge/sources")?json([]):unavailable()));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);const area=await screen.findByLabelText(/Text/)as HTMLTextAreaElement;expect(area.maxLength).toBe(-1);
  });

  it("aborts an in-flight mutation when Company context changes",async()=>{
    let signal:AbortSignal|undefined;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==="POST"){signal=init.signal as AbortSignal;return await new Promise<Response>(()=>{});}return url.endsWith("/knowledge/sources")?json([]):unavailable();}));
    const view=render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.change(await screen.findByLabelText("Source name"),{target:{value:"Facts"}});fireEvent.change(screen.getByLabelText(/Text/),{target:{value:"facts"}});fireEvent.click(screen.getByRole("button",{name:"Ingest source"}));await waitFor(()=>expect(signal).toBeTruthy());view.rerender(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={2} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);expect(signal!.aborted).toBe(true);
  });

  it.each([{kind:"manual_text" as const,button:"Manual Text",path:"/revisions/manual"},{kind:"public_url" as const,button:"Public URL",path:"/revisions/url"},{kind:"pdf" as const,button:"PDF",path:"/revisions/pdf?expectedSourceVersion=1"}])("creates a $kind retry/revision",async({kind,path})=>{
    const calls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==="POST"){calls.push(url);return json({source:source(kind),revision},201);}return url.endsWith("/knowledge/sources")?json([source(kind)]):unavailable();}));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.click(await screen.findByRole("button",{name:"Create revision"}));if(kind==="manual_text")fireEvent.change(screen.getByLabelText(/Text/),{target:{value:"next"}});if(kind==="public_url")fireEvent.change(screen.getByLabelText("Public URL"),{target:{value:"https://next.example"}});if(kind==="pdf")fireEvent.change(screen.getByLabelText(/PDF up to/),{target:{files:[new File(["%PDF"],"facts.pdf",{type:"application/pdf"})]}});const submit=screen.getAllByRole("button",{name:"Create revision"})[0]as HTMLButtonElement;await waitFor(()=>expect(submit.disabled).toBe(false));fireEvent.submit(submit.closest("form")!);await waitFor(()=>expect(calls.some(url=>url.endsWith(path))).toBe(true));
  });

  it("creates PDF, clears the selected file, and enforces the 10 MiB boundary",async()=>{const calls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==="POST"){calls.push(url);return json({source:source("pdf"),revision},201);}return url.endsWith("/knowledge/sources")?json([]):unavailable();}));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.click(await screen.findByRole("button",{name:"PDF"}));fireEvent.change(screen.getByLabelText("Source name"),{target:{value:"PDF facts"}});const input=screen.getByLabelText(/PDF up to/)as HTMLInputElement,large=new File([],"large.pdf",{type:"application/pdf"}),ok=new File([],"ok.pdf",{type:"application/pdf"});Object.defineProperty(large,"size",{value:10*1024*1024+1});Object.defineProperty(ok,"size",{value:10*1024*1024});fireEvent.change(input,{target:{files:[large]}});const submit=screen.getByRole("button",{name:"Ingest source"})as HTMLButtonElement;await waitFor(()=>expect(submit.disabled).toBe(false));fireEvent.submit(submit.closest("form")!);expect((await screen.findByRole("alert")).textContent).toContain("exceeds 10 MiB");fireEvent.change(input,{target:{files:[ok]}});await waitFor(()=>expect(submit.disabled).toBe(false));fireEvent.submit(submit.closest("form")!);await waitFor(()=>expect(calls.some(url=>url.includes("/sources/pdf"))).toBe(true));await waitFor(()=>expect((screen.getByLabelText(/PDF up to/)as HTMLInputElement).files?.length??0).toBe(0));});

  it("loads revision detail and renders normalized text as plain content",async()=>{vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>{const url=String(input);if(url.includes("/revisions/ksrv_a"))return json(revision);if(url.endsWith("/knowledge/sources"))return json([source()]);return unavailable();}));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read"]}/></I18nProvider>);fireEvent.click(await screen.findByRole("button",{name:"View revision"}));expect(await screen.findByText("normalized safe facts")).toBeTruthy();expect(screen.getByRole("button",{name:"Close details"})).toBeTruthy();});

  it.each([{workspaceId:"wsp_b",companyId:1},{workspaceId:null,companyId:null}])("aborts mutation on context or logout change",async(next)=>{let signal:AbortSignal|undefined;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{if(init?.method==="POST"){signal=init.signal as AbortSignal;return await new Promise<Response>(()=>{});}return String(input).endsWith("/knowledge/sources")?json([]):unavailable();}));const view=render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.change(await screen.findByLabelText("Source name"),{target:{value:"Facts"}});fireEvent.change(screen.getByLabelText(/Text/),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Ingest source"}));await waitFor(()=>expect(signal).toBeTruthy());view.rerender(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId={next.workspaceId} companyId={next.companyId} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);expect(signal!.aborted).toBe(true);});

  it("aborts mutation on unmount",async()=>{let signal:AbortSignal|undefined;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{if(init?.method==="POST"){signal=init.signal as AbortSignal;return await new Promise<Response>(()=>{});}return String(input).endsWith("/knowledge/sources")?json([]):unavailable();}));const view=render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.change(await screen.findByLabelText("Source name"),{target:{value:"Facts"}});fireEvent.change(screen.getByLabelText(/Text/),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Ingest source"}));await waitFor(()=>expect(signal).toBeTruthy());view.unmount();expect(signal!.aborted).toBe(true);});

  it("resets selection and announces publication conflict before explicit re-review",async()=>{let publications=0;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==="POST"&&url.endsWith("/publication")){publications++;return json({error:{code:"knowledge_publication_changed",message:"changed"}},409);}if(url.endsWith("/knowledge/sources"))return json([source()]);return unavailable();}));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:publish"]}/></I18nProvider>);fireEvent.click(await screen.findByLabelText("Include in next publication"));fireEvent.click(screen.getByRole("button",{name:"Publish selection"}));expect((await screen.findByRole("alert")).textContent).toContain("publication changed");expect((screen.getByLabelText("Include in next publication")as HTMLInputElement).checked).toBe(false);expect(publications).toBe(1);});

  it("renders translated lifecycle labels in English and Spanish without raw enums",async()=>{const fetcher=vi.fn(async(input:string|URL|Request)=>String(input).endsWith("/knowledge/sources")?json([source()]):unavailable());vi.stubGlobal("fetch",fetcher);localStorage.setItem("atlas.locale","en");const view=render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read"]}/></I18nProvider>);expect((await screen.findByRole("listitem")).textContent).toContain("Ready");expect(screen.queryByText("manual_text")).toBeNull();view.unmount();localStorage.setItem("atlas.locale","es");render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read"]}/></I18nProvider>);expect((await screen.findByRole("listitem")).textContent).toContain("Lista");expect(screen.getByRole("listitem").textContent).toContain("Texto manual");localStorage.removeItem("atlas.locale");});

  it.each([{name:"Administrator",capabilities:["knowledge:read","knowledge:ingest","knowledge:publish","knowledge:archive"] as const},{name:"Owner",capabilities:["knowledge:read","knowledge:ingest","knowledge:publish","knowledge:archive"] as const}])("renders $name controls from capabilities",async({capabilities})=>{vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>String(input).endsWith("/knowledge/sources")?json([source()]):unavailable()));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={[...capabilities]}/></I18nProvider>);expect(await screen.findByRole("button",{name:"Publish selection"})).toBeTruthy();expect(screen.getByRole("button",{name:"Archive"})).toBeTruthy();});

  it.each([{outcome:"success" as const,change:"workspace" as const},{outcome:"error" as const,change:"workspace" as const},{outcome:"success" as const,change:"company" as const},{outcome:"error" as const,change:"company" as const}])("ignores stale mutation $outcome after $change change without replay",async({outcome,change})=>{const pending=deferred<Response>();let posts=0;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{if(init?.method==="POST"){posts++;return pending.promise;}return String(input).endsWith("/knowledge/sources")?json([]):unavailable();}));const view=render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.change(await screen.findByLabelText("Source name"),{target:{value:"Secret"}});fireEvent.change(screen.getByLabelText(/Text/),{target:{value:"sensitive facts"}});fireEvent.click(screen.getByRole("button",{name:"Ingest source"}));await waitFor(()=>expect(posts).toBe(1));view.rerender(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId={change==="workspace"?"wsp_b":"wsp_a"} companyId={change==="company"?2:1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);expect((screen.getByLabelText("Source name")as HTMLInputElement).value).toBe("");expect((screen.getByLabelText(/Text/)as HTMLTextAreaElement).value).toBe("");outcome==="success"?pending.resolve(json({source:{},revision:{}},201)):pending.reject(new Error("old failure"));await Promise.resolve();await Promise.resolve();expect(posts).toBe(1);expect(screen.queryByRole("alert")).toBeNull();});

  it("clears selected PDF and sensitive state on logout and never replays the mutation",async()=>{const pending=deferred<Response>();let posts=0;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{if(init?.method==="POST"){posts++;return pending.promise;}return String(input).endsWith("/knowledge/sources")?json([]):unavailable();}));const view=render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.click(await screen.findByRole("button",{name:"PDF"}));fireEvent.change(screen.getByLabelText("Source name"),{target:{value:"Sensitive PDF"}});const fileInput=screen.getByLabelText(/PDF up to/)as HTMLInputElement;fireEvent.change(fileInput,{target:{files:[new File(["%PDF"],"secret.pdf",{type:"application/pdf"})]}});const submit=screen.getByRole("button",{name:"Ingest source"})as HTMLButtonElement;await waitFor(()=>expect(submit.disabled).toBe(false));fireEvent.submit(submit.closest("form")!);await waitFor(()=>expect(posts).toBe(1));view.rerender(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId={null} companyId={null} capabilities={[]}/></I18nProvider>);pending.resolve(json({source:{},revision:{}},201));await Promise.resolve();expect(posts).toBe(1);expect(screen.queryByDisplayValue("Sensitive PDF")).toBeNull();});

  it.each([{label:"exact code-point",value:"a".repeat(80_000),accepted:true},{label:"over code-point",value:"a".repeat(80_001),accepted:false},{label:"exact UTF-8 byte",value:"é".repeat(50*1024),accepted:true},{label:"over UTF-8 byte",value:"é".repeat(50*1024)+"a",accepted:false}])("enforces the $label boundary in the rendered form",async({value,accepted})=>{let posts=0;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{if(init?.method==="POST"){posts++;return json({source:{},revision:{}},201);}return String(input).endsWith("/knowledge/sources")?json([]):unavailable();}));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);fireEvent.change(await screen.findByLabelText("Source name"),{target:{value:"Boundary"}});fireEvent.change(screen.getByLabelText(/Text/),{target:{value}});fireEvent.click(screen.getByRole("button",{name:"Ingest source"}));if(accepted)await waitFor(()=>expect(posts).toBe(1));else{expect(await screen.findByRole("alert")).toBeTruthy();expect(posts).toBe(0);}});

  it("supports native keyboard activation, labelled forms, and exact live-region transitions",async()=>{const sources=deferred<Response>();vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>{const url=String(input);if(url.includes("/revisions/ksrv_a"))return json(revision);if(url.endsWith("/knowledge/sources"))return sources.promise;return unavailable();}));const user=userEvent.setup();render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:ingest"]}/></I18nProvider>);const loading=await screen.findByText("Loading…");expect(loading.getAttribute("role")).toBe("status");sources.resolve(json([source()]));const publication=await screen.findByText("No Knowledge is published yet.");expect(publication.getAttribute("role")).toBe("status");expect(screen.queryByText("Loading…")).toBeNull();const details=screen.getByRole("button",{name:"View revision"});details.focus();await user.keyboard("{Enter}");const detail=await screen.findByText("normalized safe facts");expect(detail.closest("aside")?.getAttribute("aria-live")).toBe("polite");const close=screen.getByRole("button",{name:"Close details"});close.focus();await user.keyboard(" ");await waitFor(()=>expect(screen.queryByText("normalized safe facts")).toBeNull());expect(screen.getByLabelText("Source name")).toBeTruthy();expect(screen.getByLabelText(/Text/)).toBeTruthy();});

  it("transitions the status live region from loading to published",async()=>{const sources=deferred<Response>(),publication=deferred<Response>();vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>String(input).endsWith("/knowledge/sources")?sources.promise:publication.promise));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read"]}/></I18nProvider>);expect((await screen.findByText("Loading…")).getAttribute("role")).toBe("status");sources.resolve(json([source()]));publication.resolve(json({id:"kver_a",companyId:1,versionNumber:1,publicationVersion:1,knowledge:{},snapshotDigest:"digest",publishedByActorId:"usr_a",publishedAt:"2026-01-01T00:00:00.000Z",sourceRevisionIds:["ksrv_a"]}));const published=await screen.findByText("A Knowledge version is published.");expect(published.getAttribute("role")).toBe("status");expect(screen.queryByText("Loading…")).toBeNull();});

  it("transitions from loading to the publication conflict announcement",async()=>{let publicationRequests=0;vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==="POST"&&url.endsWith("/publication"))return json({error:{code:"knowledge_publication_changed",message:"changed"}},409);if(url.endsWith("/knowledge/sources"))return json([source()]);publicationRequests++;return unavailable();}));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read","knowledge:publish"]}/></I18nProvider>);expect((await screen.findByText("Loading…")).getAttribute("role")).toBe("status");await screen.findByText("No Knowledge is published yet.");fireEvent.click(screen.getByLabelText("Include in next publication"));fireEvent.click(screen.getByRole("button",{name:"Publish selection"}));const conflict=await screen.findByText("The publication changed. Review and select the sources again.");expect(conflict.getAttribute("role")).toBe("alert");expect(publicationRequests).toBeGreaterThan(0);});

  it("transitions from loading to the Knowledge error announcement",async()=>{vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>String(input).endsWith("/knowledge/sources")?json({error:{code:"knowledge_temporarily_unavailable",message:"unavailable"}},503):unavailable()));render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_a" companyId={1} capabilities={["knowledge:read"]}/></I18nProvider>);expect((await screen.findByText("Loading…")).getAttribute("role")).toBe("status");const error=await screen.findByText("The Knowledge operation could not be completed.");expect(error.getAttribute("role")).toBe("alert");expect(screen.queryByText("Loading…")).toBeNull();});
});
