import { useEffect, useReducer, useRef, useState } from "react";
import { ApiError, atlasApi } from "../api/atlasApi";
import { useI18n } from "../i18n/I18nContext";
import { initialKnowledgeState, knowledgeReducer, type KnowledgeRequest } from "../state/knowledgeState";
import type { KnowledgeRevision, KnowledgeSource, KnowledgeSourceKind, Permission } from "../types/api";

interface Props { csrf:string; workspaceId:string|null; companyId:number|null; capabilities:Permission[]; }
const PDF_LIMIT=10*1024*1024,MANUAL_CHARACTERS=80_000,MANUAL_BYTES=100*1024;

export function CompanyKnowledgePanel({csrf,workspaceId,companyId,capabilities}:Props):React.JSX.Element{
  const {t}=useI18n(),[state,dispatch]=useReducer(knowledgeReducer,initialKnowledgeState),sequence=useRef(0),loadAbort=useRef<AbortController|null>(null),mutationAbort=useRef<AbortController|null>(null);
  const [mode,setMode]=useState<"manual"|"url"|"pdf">("manual"),[name,setName]=useState(""),[content,setContent]=useState(""),[file,setFile]=useState<File|null>(null),[fileInputKey,setFileInputKey]=useState(0),[revising,setRevising]=useState<KnowledgeSource|null>(null),[detail,setDetail]=useState<KnowledgeRevision|null>(null),[reviewRequired,setReviewRequired]=useState(false),[validation,setValidation]=useState<string|null>(null);
  const canIngest=capabilities.includes("knowledge:ingest"),canPublish=capabilities.includes("knowledge:publish"),canArchive=capabilities.includes("knowledge:archive");
  const request=():KnowledgeRequest=>({requestId:++sequence.current,workspaceId:workspaceId!,companyId:companyId!,generation:state.generation});
  const clearSensitive=()=>{setContent("");setFile(null);setFileInputKey(value=>value+1);setRevising(null);setDetail(null);setValidation(null);};
  const load=async():Promise<void>=>{if(!workspaceId||!companyId)return;loadAbort.current?.abort();const controller=new AbortController();loadAbort.current=controller;const r=request();dispatch({type:"loading",request:r});try{const sources=await atlasApi.listKnowledgeSources(workspaceId,companyId,controller.signal);let publication=null;try{publication=await atlasApi.getKnowledgePublication(workspaceId,companyId,controller.signal);}catch(error){if(!(error instanceof ApiError&&error.code==="knowledge_unavailable"))throw error;}dispatch({type:"loaded",request:r,sources,publication});}catch(error){if(!aborted(error))dispatch({type:"failed",request:r});}};
  useEffect(()=>{loadAbort.current?.abort();mutationAbort.current?.abort();dispatch({type:"contextChanged"});setName("");clearSensitive();setReviewRequired(false);if(workspaceId&&companyId)void load();return()=>{loadAbort.current?.abort();mutationAbort.current?.abort();clearSensitive();};},[workspaceId,companyId]);
  const startMutation=()=>{mutationAbort.current?.abort();const controller=new AbortController();mutationAbort.current=controller;return controller;};
  const valid=():boolean=>{if(mode==="manual"&&(Array.from(content).length>MANUAL_CHARACTERS||new TextEncoder().encode(content).byteLength>MANUAL_BYTES)){setValidation(t("knowledge.manualLimit"));return false;}if(mode==="pdf"&&file&&file.size>PDF_LIMIT){setValidation(t("knowledge.fileTooLarge"));return false;}setValidation(null);return true;};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!workspaceId||!companyId||!valid())return;const controller=startMutation(),r=request();dispatch({type:"submitting",request:r});try{if(revising){if(mode==="manual")await atlasApi.reviseManualKnowledge(csrf,workspaceId,companyId,revising.id,revising.version,content,controller.signal);else if(mode==="url")await atlasApi.reviseUrlKnowledge(csrf,workspaceId,companyId,revising.id,revising.version,content,controller.signal);else if(file)await atlasApi.revisePdfKnowledge(csrf,workspaceId,companyId,revising.id,revising.version,file,controller.signal);}else if(mode==="manual")await atlasApi.createManualKnowledge(csrf,workspaceId,companyId,name,content,controller.signal);else if(mode==="url")await atlasApi.createUrlKnowledge(csrf,workspaceId,companyId,name,content,controller.signal);else if(file)await atlasApi.createPdfKnowledge(csrf,workspaceId,companyId,name,file,controller.signal);if(controller.signal.aborted)return;setName("");clearSensitive();await load();}catch(error){if(!aborted(error))dispatch({type:"failed",request:r});}};
  const publish=async()=>{if(!workspaceId||!companyId)return;const controller=startMutation(),r=request();dispatch({type:"submitting",request:r});try{await atlasApi.publishKnowledge(csrf,workspaceId,companyId,state.selectedRevisionIds,state.publication?.id??null,controller.signal);if(controller.signal.aborted)return;setReviewRequired(false);await load();}catch(error){if(aborted(error))return;if(error instanceof ApiError&&error.code==="knowledge_publication_changed"){dispatch({type:"contextChanged"});setReviewRequired(true);await load();return;}dispatch({type:"failed",request:r});}};
  const archiveSource=async(source:KnowledgeSource)=>{if(!workspaceId||!companyId)return;const controller=startMutation();try{await atlasApi.archiveKnowledgeSource(csrf,workspaceId,companyId,source.id,source.version,controller.signal);if(!controller.signal.aborted)await load();}catch(error){if(!aborted(error))dispatch({type:"failed",request:request()});}};
  const showDetail=async(source:KnowledgeSource)=>{if(!workspaceId||!companyId||!source.latestRevision)return;loadAbort.current?.abort();const controller=new AbortController();loadAbort.current=controller;try{setDetail(await atlasApi.getKnowledgeRevision(workspaceId,companyId,source.id,source.latestRevision.id,controller.signal));}catch(error){if(!aborted(error))setValidation(t("knowledge.error"));}};
  const beginRevision=(source:KnowledgeSource)=>{setRevising(source);setMode(kindMode(source.kind));setName(source.name);setContent(source.locator??"");setFile(null);setValidation(null);};
  if(!workspaceId||!companyId)return <section className="portal-section"><h2>{t("knowledge.title")}</h2><p>{t("knowledge.companyRequired")}</p></section>;
  return <section className="portal-section" aria-labelledby="knowledge-title"><header><h2 id="knowledge-title">{t("knowledge.title")}</h2><p>{t("knowledge.description")}</p></header>{(state.error||validation)&&<p role="alert">{validation??t("knowledge.error")}</p>}{reviewRequired&&<p role="alert">{t("knowledge.reviewRequired")}</p>}{state.loading&&<p role="status">{t("common.loading")}</p>}
  {canIngest&&<form onSubmit={e=>void submit(e)}><div className="button-row">{(["manual","url","pdf"] as const).map(value=><button key={value} type="button" disabled={!!revising&&mode!==value} onClick={()=>setMode(value)}>{t(`knowledge.${value}`)}</button>)}</div><label>{t("knowledge.name")}<input value={name} maxLength={120} required disabled={!!revising} onChange={e=>setName(e.target.value)}/></label>{mode==="manual"&&<label>{t("knowledge.text")}<textarea value={content} required onChange={e=>setContent(e.target.value)}/><small>{t("knowledge.manualLimit")}</small></label>}{mode==="url"&&<label>{t("knowledge.url")}<input type="url" value={content} required onChange={e=>setContent(e.target.value)}/></label>}{mode==="pdf"&&<label>{t("knowledge.pdfHelp")}<input key={fileInputKey} type="file" accept="application/pdf" required onChange={e=>setFile(e.target.files?.[0]??null)}/></label>}<button disabled={state.submitting||mode==="pdf"&&!file}>{revising?t("knowledge.revise"):t("knowledge.ingest")}</button>{revising&&<button type="button" onClick={clearSensitive}>{t("common.cancel")}</button>}</form>}
  <ul aria-label={t("knowledge.sources")}>{state.sources.map(source=><li key={source.id}><strong>{source.name}</strong> — {t(`knowledge.kind.${source.kind}`)} — {t(`knowledge.status.${source.status}`)}{source.latestRevision&&<> — {t(`knowledge.status.${source.latestRevision.status}`)} <button onClick={()=>void showDetail(source)}>{t("knowledge.details")}</button></>}{source.latestRevision?.status==="ready"&&source.status==="active"&&<label><input type="checkbox" checked={state.selectedRevisionIds.includes(source.latestRevision.id)} onChange={e=>dispatch({type:"select",revisionId:source.latestRevision!.id,selected:e.target.checked})}/>{t("knowledge.include")}</label>}{canIngest&&source.status==="active"&&!source.latestRevision?.status.includes("pending")&&<button onClick={()=>beginRevision(source)}>{t("knowledge.revise")}</button>}{canArchive&&source.status==="active"&&<button onClick={()=>void archiveSource(source)}>{t("knowledge.archive")}</button>}</li>)}</ul>
  {detail&&<aside aria-live="polite"><button onClick={()=>setDetail(null)}>{t("knowledge.closeDetails")}</button><pre>{detail.normalizedText??""}</pre></aside>}<p role="status">{state.publication?t("knowledge.published"):t("knowledge.unpublished")}</p>{canPublish&&<button disabled={state.submitting||state.selectedRevisionIds.length===0} onClick={()=>void publish()}>{t("knowledge.publish")}</button>}</section>;
}
function aborted(error:unknown):boolean{return error instanceof DOMException&&error.name==="AbortError";}
function kindMode(kind:KnowledgeSourceKind):"manual"|"url"|"pdf"{return kind==="manual_text"?"manual":kind==="public_url"?"url":"pdf";}
