// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import { I18nProvider } from "../i18n/I18nContext";
import type { KnowledgePublication, KnowledgeSource } from "../types/api";
import { CompanyKnowledgePanel } from "./CompanyKnowledgePanel";
import { presentKnowledgeSource } from "./knowledgePresentation";

const revision={id:"rev_1",sourceId:"src_1",revisionNumber:1,status:"ready" as const,mediaType:"text/plain",normalizedText:"safe facts",extractedKnowledge:null,failureCode:null,createdAt:"2026-01-01T00:00:00.000Z",completedAt:"2026-01-01T00:00:00.000Z"};
const source=(status:"pending"|"ready"|"failed"="ready"):KnowledgeSource=>({id:"src_1",companyId:1,kind:"manual_text",name:"Policies",locator:null,status:"active",version:1,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null,latestRevision:{...revision,status},includedRevisionId:null});
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});
function renderPanel(capabilities=["knowledge:read","knowledge:ingest","knowledge:publish"] as const){return render(<I18nProvider><CompanyKnowledgePanel csrf="csrf" workspaceId="wsp_1" companyId={1} capabilities={[...capabilities]}/></I18nProvider>);}
function mockLibrary(sources:KnowledgeSource[]=[]){vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==="POST")return json({source:sources[0]??source(),revision},201);if(url.endsWith("/knowledge/sources"))return json(sources);return json({error:{code:"knowledge_unavailable",message:"unavailable"}},404);}));}
afterEach(()=>{cleanup();vi.unstubAllGlobals();localStorage.clear();});

test("pure presentation maps authoritative lifecycle combinations",()=>{expect(presentKnowledgeSource(source("pending"),null).state).toBe("processing");expect(presentKnowledgeSource(source("failed"),null).state).toBe("attention");expect(presentKnowledgeSource(source("ready"),null).state).toBe("review");expect(presentKnowledgeSource({...source(),status:"archived"},null).state).toBe("archived");const publication={id:"pub",companyId:1,versionNumber:1,publicationVersion:1,knowledge:{},snapshotDigest:"x",publishedByActorId:"u",publishedAt:"2026-01-01",sourceRevisionIds:["rev_1"]} as KnowledgePublication;expect(presentKnowledgeSource(source(),publication).state).toBe("available");});

test("empty knowledge shows four distinct teaching actions without legacy pseudo-tabs",async()=>{mockLibrary();renderPanel();await screen.findByText("Atlas does not know this company yet");for(const title of ["Learn from my website","Learn from a document","Build common answers","Add internal knowledge"])expect(screen.getByRole("heading",{name:title})).toBeTruthy();expect(screen.queryByText("Manual Text")).toBeNull();expect(screen.queryByText("Public URL")).toBeNull();expect(screen.queryByText("Documents")).toBeNull();});
test("FAQ is truthful and non-interactive because no dedicated contract exists",async()=>{mockLibrary();renderPanel();await screen.findByText("Atlas does not know this company yet");const article=screen.getByRole("heading",{name:"Build common answers"}).closest("article")!;expect(article.textContent).toContain("Coming soon");expect(article.querySelector("button")).toBeNull();});
test.each([["Learn from my website","Public website URL","Teach from this website"],["Learn from a document","Choose PDF","Teach from this document"],["Add internal knowledge","Knowledge for Atlas","Teach this knowledge"]])("opens focused %s flow with deterministic back and restores focus",async(method,field,submit)=>{mockLibrary();renderPanel();const heading=await screen.findByRole("heading",{name:method});fireEvent.click(heading.closest("article")!.querySelector("button")!);expect(screen.getByText(field)).toBeTruthy();expect(screen.getByRole("button",{name:submit})).toBeTruthy();const back=screen.getByRole("link",{name:/Back to teaching methods/});expect(back.getAttribute("href")).toBe("/companies/1/knowledge");fireEvent.click(back);expect(screen.getByRole("heading",{name:"Teach Atlas something new"})).toBeTruthy();const restored=screen.getByRole("heading",{name:method}).closest("article")!.querySelector("button")!;await waitFor(()=>expect(document.activeElement).toBe(restored));});
test("website payload preserves its contract",async()=>{const fetch=vi.fn(async(input:string|URL|Request,init?:RequestInit)=>init?.method==="POST"?json({source:source(),revision},201):String(input).endsWith("/knowledge/sources")?json([]):json({error:{code:"knowledge_unavailable"}},404));vi.stubGlobal("fetch",fetch);renderPanel();fireEvent.click((await screen.findByRole("heading",{name:"Learn from my website"})).closest("article")!.querySelector("button")!);const fields=screen.getAllByRole("textbox");fireEvent.change(fields[0]!,{target:{value:"Main site"}});fireEvent.change(fields[1]!,{target:{value:"https://example.test"}});fireEvent.submit(screen.getByRole("button",{name:"Teach from this website"}).closest("form")!);await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/sources/url"),expect.objectContaining({method:"POST",body:JSON.stringify({name:"Main site",url:"https://example.test"})})));});
test("PDF shows selected filename and preserves the raw PDF request",async()=>{const fetch=vi.fn(async(input:string|URL|Request,init?:RequestInit)=>init?.method==="POST"?json({source:source(),revision},201):String(input).endsWith("/knowledge/sources")?json([]):json({error:{code:"knowledge_unavailable"}},404));vi.stubGlobal("fetch",fetch);renderPanel();fireEvent.click((await screen.findByRole("heading",{name:"Learn from a document"})).closest("article")!.querySelector("button")!);fireEvent.change(screen.getByRole("textbox"),{target:{value:"Guide"}});const input=screen.getByLabelText("Choose PDF");const file=new File(["pdf"],"guide.pdf",{type:"application/pdf"});fireEvent.change(input,{target:{files:[file]}});expect(screen.getByText("guide.pdf")).toBeTruthy();fireEvent.submit(screen.getByRole("button",{name:"Teach from this document"}).closest("form")!);await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/sources/pdf?name=Guide"),expect.objectContaining({method:"POST",body:file,headers:expect.objectContaining({"content-type":"application/pdf"})})));});
test("loading never renders the empty library and failure offers recovery",async()=>{let reject!:(reason:unknown)=>void;vi.stubGlobal("fetch",vi.fn(()=>new Promise<Response>((_,r)=>{reject=r;})));renderPanel();expect((await screen.findByRole("status")).textContent).toContain("checking what it already knows");expect(screen.queryByText("Atlas has not learned company knowledge yet")).toBeNull();reject(new Error("offline"));expect(await screen.findByRole("button",{name:"Try again"})).toBeTruthy();});
test("populated knowledge leads with the library and opens teaching on demand",async()=>{mockLibrary([source("ready")]);renderPanel();expect(await screen.findByRole("heading",{name:"Atlas knowledge"})).toBeTruthy();expect(screen.getByText("Ready to review")).toBeTruthy();expect(screen.queryByRole("heading",{name:"Learn from my website"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Teach Atlas something new"}));expect(screen.getByRole("heading",{name:"Learn from my website"})).toBeTruthy();fireEvent.click(screen.getByRole("link",{name:"Back to Atlas knowledge"}));const restored=screen.getByRole("button",{name:"Teach Atlas something new"});await waitFor(()=>expect(document.activeElement).toBe(restored));expect(screen.queryByText("rev_1")).toBeNull();expect(screen.queryByText("Include in next publication")).toBeNull();});
test("Spanish entry and deterministic back copy are complete",async()=>{localStorage.setItem("atlas.locale","es");mockLibrary();renderPanel();expect(await screen.findByRole("heading",{name:"Enseñale algo nuevo a Atlas"})).toBeTruthy();expect(screen.getByText("¿Qué querés que aprenda hoy?")).toBeTruthy();const method=screen.getByRole("heading",{name:"Agregar conocimiento interno"});fireEvent.click(method.closest("article")!.querySelector("button")!);const back=screen.getByRole("link",{name:/Volver a formas de enseñar/});expect(back.getAttribute("href")).toBe("/companies/1/knowledge");});
