// @vitest-environment jsdom
import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { I18nProvider } from "../i18n/I18nContext";
import { OperationalAssistantExecutionPanel } from "./OperationalAssistantExecutionPanel";
const profile={id:"asp_0123456789abcdef",name:"Profile",description:null,businessRole:"Sales",objective:"Help",audience:null,tone:"professional" as const,assistantLanguage:"en" as const,welcomeMessage:"Welcome",fallbackMessage:"Fallback",status:"ready" as const,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null};
afterEach(()=>{cleanup();vi.restoreAllMocks();window.localStorage.removeItem("atlas.locale");});
it("uses the explicit profile endpoint and capability gate",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({status:"answered",answer:"Answer"}),{status:200,headers:{"content-type":"application/json"}}));const view=render(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="wsp" companyId={1} companyName="Company" profile={profile} capabilities={["chat:use"]}/></I18nProvider>);fireEvent.change(screen.getByRole("textbox"),{target:{value:" Hello "}});fireEvent.click(screen.getByRole("button",{name:"Send to assistant"}));await screen.findByText("Answer");const [url,options]=fetchMock.mock.calls[0] as [string,RequestInit];expect(url).toBe("/api/workspaces/wsp/companies/1/assistant/executions");expect(JSON.parse(String(options.body))).toEqual({assistantProfileId:profile.id,message:"Hello"});view.unmount();render(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="wsp" companyId={1} companyName="Company" profile={profile} capabilities={[]}/></I18nProvider>);expect(screen.queryByRole("button")).toBeNull();});

it("rejects malformed responses and aborts stale execution on a context change",async()=>{let signal:AbortSignal|undefined;const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation((_url,options)=>{signal=options?.signal as AbortSignal;return new Promise<Response>(()=>{});});const view=render(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="wsp" companyId={1} companyName="Company" profile={profile} capabilities={["chat:use"]}/></I18nProvider>);fireEvent.change(screen.getByRole("textbox"),{target:{value:"Question"}});fireEvent.click(screen.getByRole("button",{name:"Send to assistant"}));const changed={...profile,id:"asp_1123456789abcdef"};view.rerender(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="wsp" companyId={1} companyName="Company" profile={changed} capabilities={["chat:use"]}/></I18nProvider>);await waitFor(()=>expect(signal?.aborted).toBe(true));expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("");view.unmount();fetchMock.mockResolvedValue(new Response(JSON.stringify({status:"unexpected",answer:"Answer"}),{status:200,headers:{"content-type":"application/json"}}));render(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="wsp" companyId={1} companyName="Company" profile={profile} capabilities={["chat:use"]}/></I18nProvider>);fireEvent.change(screen.getByRole("textbox"),{target:{value:"Question"}});fireEvent.click(screen.getByRole("button",{name:"Send to assistant"}));await screen.findByRole("alert");});

it("does not render operational controls for non-ready Profiles",()=>{for(const status of ["draft","disabled","archived"] as const){cleanup();render(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="wsp" companyId={1} companyName="Company" profile={{...profile,status}} capabilities={["chat:use"]}/></I18nProvider>);expect(screen.queryByRole("textbox")).toBeNull();}});

it("aborts and clears for Workspace, Company, Profile, and unmount changes",async()=>{const signals:AbortSignal[]=[];vi.spyOn(globalThis,"fetch").mockImplementation((_url,options)=>{signals.push(options?.signal as AbortSignal);return new Promise<Response>(()=>{});});const view=render(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="one" companyId={1} companyName="Company" profile={profile} capabilities={["chat:use"]}/></I18nProvider>);const submit=()=>{fireEvent.change(screen.getByRole("textbox"),{target:{value:"Question"}});fireEvent.click(screen.getByRole("button",{name:"Send to assistant"}));};submit();view.rerender(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="two" companyId={1} companyName="Company" profile={profile} capabilities={["chat:use"]}/></I18nProvider>);await waitFor(()=>expect(signals[0]?.aborted).toBe(true));expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("");submit();view.rerender(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="two" companyId={2} companyName="Company" profile={profile} capabilities={["chat:use"]}/></I18nProvider>);await waitFor(()=>expect(signals[1]?.aborted).toBe(true));submit();view.rerender(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="two" companyId={2} companyName="Company" profile={{...profile,id:"asp_2123456789abcdef"}} capabilities={["chat:use"]}/></I18nProvider>);await waitFor(()=>expect(signals[2]?.aborted).toBe(true));submit();view.unmount();expect(signals[3]?.aborted).toBe(true);});

it("renders localized fallback and rate-limit outcomes accessibly",async()=>{window.localStorage.setItem("atlas.locale","es");const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(new Response(JSON.stringify({status:"safe_fallback",answer:"Fallback"}),{status:200,headers:{"content-type":"application/json"}})).mockResolvedValueOnce(new Response(JSON.stringify({error:{code:"assistant_execution_rate_limited",message:"limited"}}),{status:429,headers:{"content-type":"application/json"}}));render(<I18nProvider><OperationalAssistantExecutionPanel csrf="csrf" workspaceId="wsp" companyId={1} companyName="Company" profile={profile} capabilities={["chat:use"]}/></I18nProvider>);fireEvent.change(screen.getByRole("textbox"),{target:{value:"Pregunta"}});fireEvent.click(screen.getByRole("button",{name:"Enviar al asistente"}));const fallback=await screen.findByText("Respuesta alternativa segura");expect(fallback.parentElement?.getAttribute("aria-live")).toBe("polite");fireEvent.change(screen.getByRole("textbox"),{target:{value:"Otra pregunta"}});fireEvent.click(screen.getByRole("button",{name:"Enviar al asistente"}));const rateLimited=await screen.findByRole("alert");expect(rateLimited.textContent).toBe("La ejecución está limitada temporalmente. Intentá nuevamente.");fetchMock.mockClear();});
