import { useEffect, useReducer, useRef, useState } from "react";
import { ApiError, atlasApi } from "../api/atlasApi";
import { useI18n } from "../i18n/I18nContext";
import { operationalAssistantExecutionAccessibility, operationalAssistantExecutionReducer, operationalMessageLength, operationalMessageValid, initialOperationalAssistantExecutionState } from "../state/operationalAssistantExecutionState";
import type { AssistantProfile, Permission } from "../types/api";

interface Props { csrf: string; workspaceId: string; companyId: number; companyName: string; profile: AssistantProfile; capabilities: Permission[]; }
export function OperationalAssistantExecutionPanel(props: Props): React.JSX.Element | null {
  const { t } = useI18n(); const [message, setMessage] = useState(""); const [state, dispatch] = useReducer(operationalAssistantExecutionReducer, initialOperationalAssistantExecutionState); const request = useRef(0); const controller = useRef<AbortController | null>(null);
  useEffect(() => { request.current += 1; controller.current?.abort(); setMessage(""); dispatch({ type: "contextChanged" }); return () => controller.current?.abort(); }, [props.workspaceId, props.companyId, props.profile.id, props.profile.status]);
  const allowed = props.capabilities.includes("chat:use"), executable = props.profile.status === "ready"; if (!allowed || !executable) return null;
  const length = operationalMessageLength(message), pending = state.status === "pending";
  const submit = async (event: React.FormEvent): Promise<void> => { event.preventDefault(); if (!executable || !operationalMessageValid(message) || pending) return; controller.current?.abort(); const active = new AbortController(); controller.current = active; const requestId = ++request.current; dispatch({ type: "started", requestId }); try { const result = await atlasApi.executeAssistantProfile(props.csrf, props.workspaceId, props.companyId, props.profile.id, message.trim(), active.signal); dispatch({ type: "succeeded", requestId, outcome: result.status, answer: result.answer }); } catch (error: unknown) { if (error instanceof DOMException && error.name === "AbortError") return; const code = error instanceof ApiError ? error.code : null; const key = code === "assistant_profile_not_executable" ? "operationalExecution.profileUnavailable" : code === "company_not_ready" ? "operationalExecution.companyUnavailable" : code === "knowledge_unavailable" ? "operationalExecution.knowledgeUnavailable" : code === "assistant_execution_rate_limited" ? "operationalExecution.rateLimited" : error instanceof ApiError && error.status === 400 ? "operationalExecution.invalid" : "operationalExecution.temporarilyUnavailable"; dispatch({ type: "failed", requestId, key }); } };
  return <section className="assistant-preview" aria-labelledby="operational-execution-title"><div><h4 id="operational-execution-title">{t("operationalExecution.title")}</h4><p>{t("operationalExecution.context", { profileName: props.profile.name, companyName: props.companyName })}</p></div><form className="assistant-preview-form" onSubmit={(event) => void submit(event)}><label className="form-field"><span>{t("operationalExecution.messageLabel")}</span><textarea value={message} disabled={pending} placeholder={t("operationalExecution.placeholder")} onChange={(event) => setMessage(event.target.value)}/><small>{t("operationalExecution.limit", { count: String(length) })}</small></label><button className="button button--primary" type="submit" disabled={pending || !operationalMessageValid(message)}>{pending ? t("operationalExecution.sending") : t("operationalExecution.send")}</button></form>{pending && <p role={operationalAssistantExecutionAccessibility.pendingRole}>{t("operationalExecution.responding")}</p>}{(state.status === "answered" || state.status === "safe_fallback") && <div className={`assistant-preview-result${state.status === "safe_fallback" ? " assistant-preview-result--fallback" : ""}`} aria-live={operationalAssistantExecutionAccessibility.resultLive}><strong>{state.status === "safe_fallback" ? t("operationalExecution.fallback") : t("operationalExecution.answer")}</strong><p>{state.answer}</p></div>}{state.status === "error" && <div className="inline-message inline-message--error" role={operationalAssistantExecutionAccessibility.errorRole}>{t(state.key)}</div>}</section>;
}
