import { useI18n } from "../i18n/I18nContext";
import type { PilotReadiness, PilotReadinessCheck, PilotReadinessClassification, PilotReadinessNextAction } from "../types/api";
import { Badge, Button, Surface } from "../design-system/primitives";

interface Props { readonly companyId:number; readonly readiness:PilotReadiness; readonly onNavigate:(path:string)=>void; readonly showActions?:boolean; }

const classificationCopy:Record<PilotReadinessClassification,{title:string;description:string}>={
  setup_incomplete:{title:"Faltan pasos de configuración",description:"Completá los pasos necesarios para preparar tu piloto."},
  code_ready:{title:"Atlas necesita una configuración",description:"La configuración de Atlas para este canal todavía está pendiente."},
  configuration_ready:{title:"Atlas está configurado",description:"Activá un canal para que tu piloto pueda atender conversaciones."},
  external_provider_blocked:{title:"Hay una acción pendiente del proveedor",description:"Completá la verificación o configuración pendiente con el proveedor."},
  pilot_ready:{title:"Tu piloto está listo",description:"Atlas puede atender conversaciones en al menos un canal operativo."},
};
const checkCopy:Record<PilotReadinessCheck["id"],string>={workspace_context:"Contexto del espacio",company:"Empresa activa",default_assistant:"Asistente predeterminado",published_knowledge:"Conocimiento publicado",commercial_entitlement:"Estado comercial",operational_channel:"Canal operativo",web_chat:"Web Chat",whatsapp:"WhatsApp",scheduling:"Agenda y disponibilidad",proactive:"Seguimientos proactivos"};
const reasonCopy:Record<NonNullable<PilotReadinessCheck["reasonCode"]>,string>={workspace_context_invalid:"No pudimos confirmar el contexto del espacio.",company_missing:"No encontramos esta empresa.",company_suspended:"La empresa está suspendida.",company_archived:"La empresa está archivada.",default_assistant_not_executable:"El asistente predeterminado todavía no está listo para atender.",published_knowledge_missing:"Todavía falta publicar conocimiento para Atlas.",commercial_control_suspended:"La cuenta comercial está suspendida.",commercial_entitlement_missing:"No pudimos confirmar una habilitación comercial vigente.",commercial_entitlement_ineligible:"La habilitación comercial actual no permite operar el piloto.",operational_channel_missing:"Conectá y activá al menos un canal.",web_chat_not_connected:"Todavía no hay un Web Chat conectado.",web_chat_inactive:"Web Chat está conectado pero inactivo.",whatsapp_not_connected:"Todavía no hay una conexión de WhatsApp.",whatsapp_inactive:"WhatsApp está conectado pero inactivo.",whatsapp_platform_configuration_unavailable:"Atlas todavía necesita completar su configuración de WhatsApp.",whatsapp_business_verification_pending:"Meta necesita completar la verificación de la empresa.",whatsapp_validation_failed:"La validación de WhatsApp requiere una revisión en Meta.",whatsapp_health_degraded:"WhatsApp informó un estado operativo que requiere atención.",scheduling_not_configured:"La agenda todavía no está configurada.",proactive_not_configured:"Los seguimientos proactivos todavía no están configurados."};
const actionCheck:Record<PilotReadinessNextAction,PilotReadinessCheck["id"]>={resolve_workspace_context:"workspace_context",review_company:"company",configure_assistant:"default_assistant",publish_knowledge:"published_knowledge",review_billing:"commercial_entitlement",activate_web_chat:"web_chat",connect_whatsapp:"operational_channel",review_whatsapp:"whatsapp"};

export function safePilotReadinessPath(path:string|null,companyId:number):string|null { if(path===null)return null;const base=`/companies/${companyId}`,known=new Set(["/dashboard","/billing","/conversations",base,`${base}/assistant`,`${base}/knowledge`,`${base}/channels`,`${base}/channels/web-chat`,`${base}/channels/whatsapp`]);return known.has(path)?path:null; }

function statusCopy(status:PilotReadinessCheck["status"]):string { if(status==="complete")return "Listo";if(status==="incomplete")return "Pendiente";if(status==="blocked")return "Bloqueado";if(status==="unavailable")return "No disponible";return "No aplica"; }
function ownerCopy(owner:PilotReadinessCheck["owner"]):string|null { if(owner==="customer")return "Completá este paso en Atlas";if(owner==="platform")return "Atlas necesita completar una configuración";if(owner==="external_provider")return "Se requiere una acción del proveedor";return null; }
function actionLabel(id:PilotReadinessCheck["id"]):string { if(id==="default_assistant")return "Configurar asistente";if(id==="published_knowledge")return "Publicar conocimiento";if(id==="commercial_entitlement")return "Ver facturación";if(id==="web_chat")return "Administrar Web Chat";if(id==="whatsapp")return "Administrar WhatsApp";if(id==="operational_channel")return "Ver canales";if(id==="scheduling"||id==="proactive")return "Ver automatizaciones";return "Revisar configuración"; }

export function PilotReadinessPanel({companyId,readiness,onNavigate,showActions=true}:Props):React.JSX.Element {
  const {formatDate}=useI18n(),summary=classificationCopy[readiness.classification],required=readiness.checks.filter(check=>check.required),optional=readiness.checks.filter(check=>!check.required),nextAction=readiness.nextAction,primaryCheck=nextAction===null?null:readiness.checks.find(check=>check.id===actionCheck[nextAction])??null,primaryPath=primaryCheck?safePilotReadinessPath(primaryCheck.actionPath,companyId):null;
  const navigate=(path:string):void=>onNavigate(path);
  return <div className="pilot-readiness" aria-busy={false}>
    <header className="work-anchor"><p className="work-anchor__context">Prepará Atlas para tu piloto</p><h2 tabIndex={-1}>Estado del piloto</h2><Surface className={`readiness-statement pilot-readiness__summary pilot-readiness__summary--${readiness.classification}`} role="status"><strong>{summary.title}</strong><p>{summary.description}</p></Surface>{showActions&&primaryPath&&primaryCheck&&<Button className="next-action" onClick={()=>navigate(primaryPath)}>{actionLabel(primaryCheck.id)}</Button>}<p className="work-anchor__quiet">Última verificación: <time dateTime={readiness.evaluatedAt}>{formatDate(readiness.evaluatedAt)}</time></p></header>
    <ReadinessSection title="Configuración necesaria" checks={required} companyId={companyId} primaryCheckId={primaryCheck?.id ?? null} onNavigate={navigate} showActions={showActions}/>
    {optional.length>0&&<details className="pilot-readiness__optional"><summary>Mejorá tu piloto</summary><p>Estos pasos son opcionales y no impiden que el piloto esté listo.</p><ReadinessSection title="Mejorá tu piloto" checks={optional} companyId={companyId} primaryCheckId={null} onNavigate={navigate} showActions={showActions}/></details>}
  </div>;
}

function ReadinessSection({title,description,checks,companyId,primaryCheckId,onNavigate,showActions}:{readonly title:string;readonly description?:string;readonly checks:readonly PilotReadinessCheck[];readonly companyId:number;readonly primaryCheckId:PilotReadinessCheck["id"]|null;readonly onNavigate:(path:string)=>void;readonly showActions:boolean}):React.JSX.Element{return <section className="readiness-evidence pilot-readiness__checks" aria-label={title}><h2>{title}</h2>{description&&<p>{description}</p>}<ul>{checks.map(check=>{const path=safePilotReadinessPath(check.actionPath,companyId),owner=ownerCopy(check.owner),tone=check.status==="complete"?"success":check.status==="blocked"?"danger":check.status==="unavailable"?"warning":"info";return <li key={check.id} className={`pilot-readiness__check pilot-readiness__check--${check.status}`}><div><strong>{checkCopy[check.id]}</strong><Badge tone={tone}>{statusCopy(check.status)}</Badge>{check.reasonCode&&<p>{reasonCopy[check.reasonCode]}</p>}{owner&&owner!=="Completá este paso en Atlas"&&<p className="work-anchor__quiet">{owner}</p>}</div>{showActions&&path&&check.id!==primaryCheckId&&check.status!=="complete"&&check.status!=="not_applicable"&&<Button size="sm" variant="quiet" onClick={()=>onNavigate(path)}>{actionLabel(check.id)}</Button>}</li>;})}</ul></section>}
