// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import { ApiError, atlasApi } from "../api/atlasApi";
import type { SchedulingConfiguration } from "../types/api";
import { SchedulingAutomationsPanel } from "./SchedulingAutomationsPanel";

const configuration=(companyId=1):SchedulingConfiguration=>({aggregateVersion:7,locations:[{id:"loc_1",name:"Main",address:"Old address",timezone:"UTC",active:true,created_at:"now",updated_at:"now"}],resources:[{id:"res_1",location_id:"loc_1",name:"Room",timezone:"UTC",capacity:1,active:true,created_at:"now",updated_at:"now"}],services:[{id:"svc_1",resource_id:"res_1",name:"Visit",duration_minutes:30,buffer_before_minutes:0,buffer_after_minutes:0,slot_granularity_minutes:15,minimum_lead_minutes:0,maximum_horizon_days:30,active:true,created_at:"now",updated_at:"now"}],weeklyWorkingWindows:[],dateExceptions:[{id:"exc_1",resource_id:"res_1",local_date:"2026-01-02",kind:"closed",start_time:null,end_time:null}],readiness:{state:"minimal",hasLocations:true,hasResources:true,hasServices:true,hasWeeklyAvailability:false}});
const toolCatalog={tools:[]};
function setup(companyId=1,capabilities=["company:manage"] as const){const get=vi.spyOn(atlasApi,"getSchedulingConfiguration").mockImplementation(async(_workspace,id)=>configuration(id));vi.spyOn(atlasApi,"getAssistantToolCatalog").mockResolvedValue(toolCatalog);const mutate=vi.spyOn(atlasApi,"mutateSchedulingConfiguration").mockResolvedValue({aggregateVersion:8,affected:{entityType:"x",entityId:"x",action:"updated"}});const view=render(<SchedulingAutomationsPanel csrf="csrf" workspaceId="w" companyId={companyId} profileId="assistant" capabilities={[...capabilities]} onNavigate={vi.fn()}/>);return{get,mutate,view};}
function submit(name:string):void{fireEvent.submit(screen.getByRole("button",{name}).closest("form")!);}
function command(mutate:ReturnType<typeof vi.spyOn>,operation:string,last=false):Record<string,unknown>{const calls:unknown[][]=mutate.mock.calls;const matching=calls.filter(call=>(call[3] as {operation:string}).operation===operation);const call=last?matching.at(-1):matching[0];expect(call).toBeTruthy();return call![3] as Record<string,unknown>;}
afterEach(()=>{cleanup();vi.restoreAllMocks();});

test("renders all nine scheduling commands with CAS, operation IDs, and safe reloads",async()=>{const {mutate,get}=setup();await screen.findByText("Main");
  submit("Guardar ubicación");await waitFor(()=>expect(mutate).toHaveBeenCalledTimes(1));
  fireEvent.click(screen.getByRole("button",{name:"Editar ubicación"}));fireEvent.change(screen.getByLabelText("Nombre de ubicación"),{target:{value:"Renamed location"}});submit("Guardar ubicación");
  submit("Guardar recurso");await waitFor(()=>expect(mutate).toHaveBeenCalledTimes(3));fireEvent.click(screen.getByRole("button",{name:"Editar recurso"}));fireEvent.change(screen.getByLabelText("Nombre de recurso"),{target:{value:"Renamed resource"}});submit("Guardar recurso");
  fireEvent.change(screen.getByLabelText("Recurso"),{target:{value:"res_1"}});submit("Guardar servicio");await waitFor(()=>expect(mutate).toHaveBeenCalledTimes(5));fireEvent.click(screen.getByRole("button",{name:"Editar servicio"}));fireEvent.change(screen.getByLabelText("Nombre de servicio"),{target:{value:"Renamed service"}});submit("Guardar servicio");
  fireEvent.change(screen.getByLabelText("Recurso para disponibilidad"),{target:{value:"res_1"}});submit("Guardar disponibilidad");
  fireEvent.change(screen.getByLabelText("Recurso para excepción"),{target:{value:"res_1"}});fireEvent.change(screen.getByLabelText("Fecha"),{target:{value:"2026-01-03"}});submit("Agregar excepción");
  fireEvent.click(screen.getByRole("button",{name:"Quitar excepción"}));await waitFor(()=>expect(mutate).toHaveBeenCalledTimes(9));
  for(const operation of ["create_location","update_location","create_resource","update_resource","create_service","update_service","replace_weekly_availability","add_date_exception","remove_date_exception"]){const input=command(mutate,operation);expect(input.expectedVersion).toBe(7);expect(input.operationId).toEqual(expect.any(String));}expect(command(mutate,"update_location").payload).toMatchObject({locationId:"loc_1",name:"Renamed location"});expect(command(mutate,"update_resource").payload).toMatchObject({resourceId:"res_1",name:"Renamed resource"});expect(command(mutate,"update_service").payload).toMatchObject({serviceId:"svc_1",name:"Renamed service"});expect(get.mock.calls.length).toBeGreaterThan(1);
});

test("same payload retry reuses its operation ID, changed payload creates one, and conflict reloads",async()=>{const {mutate,get}=setup();await screen.findByText("Main");mutate.mockRejectedValueOnce(new Error("offline"));submit("Guardar ubicación");await screen.findByText(/Podés reintentar/);const first=command(mutate,"create_location");submit("Guardar ubicación");await waitFor(()=>expect(mutate).toHaveBeenCalledTimes(2));expect(command(mutate,"create_location",true).operationId).toBe(first.operationId);fireEvent.change(screen.getByLabelText("Nombre de ubicación"),{target:{value:"Different"}});submit("Guardar ubicación");await waitFor(()=>expect(mutate).toHaveBeenCalledTimes(3));expect(command(mutate,"create_location",true).operationId).not.toBe(first.operationId);mutate.mockRejectedValueOnce(new ApiError(409,"stale"));fireEvent.change(screen.getByLabelText("Nombre de ubicación"),{target:{value:"Conflict"}});submit("Guardar ubicación");await screen.findByText(/Recargamos los datos/);expect(get.mock.calls.length).toBeGreaterThan(1);});

test("read-only users cannot mutate and scope changes ignore late data while clearing edits",async()=>{let resolveFirst!:(value:SchedulingConfiguration)=>void;const pending=new Promise<SchedulingConfiguration>(resolve=>{resolveFirst=resolve;});const get=vi.spyOn(atlasApi,"getSchedulingConfiguration").mockImplementation((_workspace,id)=>id===1?pending:Promise.resolve({...configuration(2),locations:[{...configuration(2).locations[0]!,name:"Company B"}]}));vi.spyOn(atlasApi,"getAssistantToolCatalog").mockResolvedValue(toolCatalog);const {rerender}=render(<SchedulingAutomationsPanel csrf="csrf" workspaceId="w" companyId={1} profileId="a" capabilities={[]} onNavigate={vi.fn()}/>);rerender(<SchedulingAutomationsPanel csrf="csrf" workspaceId="w" companyId={2} profileId="b" capabilities={["company:manage"]} onNavigate={vi.fn()}/>);expect(await screen.findByText("Company B")).toBeTruthy();resolveFirst({...configuration(1),locations:[{...configuration(1).locations[0]!,name:"Company A"}]});await waitFor(()=>expect(screen.queryByText("Company A")).toBeNull());expect(screen.getByText("Agregar ubicación")).toBeTruthy();expect(screen.queryByRole("button",{name:"Editar ubicación"})).toBeTruthy();expect(get).toHaveBeenCalledTimes(2);});
test("company changes clear every explicit edit identity and its form",async()=>{const {view}=setup(1);await screen.findByText("Main");fireEvent.click(screen.getByRole("button",{name:"Editar ubicación"}));fireEvent.click(screen.getByRole("button",{name:"Editar recurso"}));fireEvent.click(screen.getByRole("button",{name:"Editar servicio"}));view.rerender(<SchedulingAutomationsPanel csrf="csrf" workspaceId="w" companyId={2} profileId="other" capabilities={["company:manage"]} onNavigate={vi.fn()}/>);await screen.findByText("Main");expect(screen.getByText("Agregar ubicación")).toBeTruthy();expect(screen.getByText("Agregar recurso")).toBeTruthy();expect(screen.getByText("Agregar servicio")).toBeTruthy();expect((screen.getByLabelText("Nombre de ubicación") as HTMLInputElement).value).toBe("");expect((screen.getByLabelText("Nombre de recurso") as HTMLInputElement).value).toBe("");expect((screen.getByLabelText("Nombre de servicio") as HTMLInputElement).value).toBe("");});
test("keeps compact secondary tabs and native active controls accessible",async()=>{setup();await screen.findByText("Main");for(const name of ["Agenda","Seguimientos","Ubicaciones","Recursos","Servicios","Disponibilidad","Excepciones"]){fireEvent.click(screen.getByRole("tab",{name}));expect(screen.getByRole("tab",{name}).getAttribute("aria-selected")).toBe("true");}const active=screen.getByRole("checkbox",{name:"Ubicación activa"});expect(active.getAttribute("type")).toBe("checkbox");expect(active.className).toContain("ds-checkbox");});
