import { useEffect, useState } from "react";
import { atlasApi } from "../api/atlasApi";
import { useI18n } from "../i18n/I18nContext";
import type { AssistantProfile, CompanyStatus, Permission, WhatsAppConnection, WhatsAppConnectionOperationalStatus } from "../types/api";
import { ContextBackLink } from "./ContextBackLink";
import { ProductHero } from "../design-system/product";
import { buildWhatsAppOnboardingViewModel, type WhatsAppFailureKind, type WhatsAppStageId } from "./whatsAppOnboardingPresentation";

interface Props { readonly csrf:string; readonly workspaceId:string|null; readonly companyId:number|null; readonly companyStatus?:CompanyStatus|null; readonly profiles:readonly AssistantProfile[]; readonly capabilities:readonly Permission[]; }
type View="overview"|"situation"|"guidance"|"diagnose"|"create"|"detail";
type Situation="new"|"business"|"personal"|"unsure";

export function WhatsAppOnboardingPanel({csrf,workspaceId,companyId,profiles,capabilities}:Props):React.JSX.Element|null {
  const {t,formatDate}=useI18n(); const [connections,setConnections]=useState<readonly WhatsAppConnection[]>([]); const [statuses,setStatuses]=useState<Record<string,WhatsAppConnectionOperationalStatus>>({});
  const [connectionId,setConnectionId]=useState(""); const [view,setView]=useState<View>("overview"); const [situation,setSituation]=useState<Situation|null>(null); const [profileId,setProfileId]=useState(""); const [phoneNumberId,setPhoneNumberId]=useState(""); const [businessAccountId,setBusinessAccountId]=useState(""); const [accessToken,setAccessToken]=useState(""); const [showToken,setShowToken]=useState(false); const [replaceToken,setReplaceToken]=useState(false); const [loading,setLoading]=useState(true); const [pending,setPending]=useState(false); const [error,setError]=useState(false); const [notice,setNotice]=useState<string|null>(null);
  const [detailFromCreate,setDetailFromCreate]=useState(false);
  const [prerequisiteAcknowledged,setPrerequisiteAcknowledged]=useState(false);
  const readable=capabilities.includes("company:read"),manageable=capabilities.includes("company:manage"),readyProfiles=profiles.filter(profile=>profile.status==="ready"); const activeConnection=connections.find(connection=>connection.id===connectionId)??null; const status=activeConnection?statuses[activeConnection.id]??null:null; const model=status?buildWhatsAppOnboardingViewModel(status):null;
  const resetMessages=():void=>{setError(false);setNotice(null);};
  const go=(next:View):void=>{setView(next);window.setTimeout(()=>{const heading=document.getElementById("whatsapp-step-heading");if(heading)heading.focus();else document.querySelector<HTMLElement>(".whatsapp-focused button")?.focus();},0);};
  const load=async():Promise<void>=>{if(!workspaceId||!companyId)return;setLoading(true);resetMessages();try{const listed=await atlasApi.listWhatsAppConnections(workspaceId,companyId);const resolved=await Promise.all(listed.map(connection=>atlasApi.getWhatsAppConnectionStatus(workspaceId,companyId,connection.id)));setConnections(listed);setStatuses(Object.fromEntries(resolved.map(item=>[item.connection.id,item])));}catch{setError(true);}finally{setLoading(false);}};
  useEffect(()=>{let current=true;if(!workspaceId||!companyId||!readable)return()=>{current=false;};setLoading(true);setConnections([]);setStatuses({});setConnectionId("");setView("overview");resetMessages();void atlasApi.listWhatsAppConnections(workspaceId,companyId).then(async listed=>({listed,resolved:await Promise.all(listed.map(connection=>atlasApi.getWhatsAppConnectionStatus(workspaceId,companyId,connection.id)))})).then(({listed,resolved})=>{if(current){setConnections(listed);setStatuses(Object.fromEntries(resolved.map(item=>[item.connection.id,item])));}}).catch(()=>{if(current)setError(true);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[workspaceId,companyId,readable]);
  const openConnection=(id:string):void=>{setConnectionId(id);setDetailFromCreate(false);go("detail");setReplaceToken(false);setAccessToken("");resetMessages();};
  const create=async():Promise<void>=>{if(!workspaceId||!companyId||!profileId||!phoneNumberId.trim()||!businessAccountId.trim()||pending)return;setPending(true);resetMessages();try{const created=await atlasApi.createWhatsAppConnection(csrf,workspaceId,companyId,{assistantProfileId:profileId,phoneNumberId:phoneNumberId.trim(),whatsappBusinessAccountId:businessAccountId.trim()});const createdStatus=await atlasApi.getWhatsAppConnectionStatus(workspaceId,companyId,created.id);setConnections(current=>[...current,created]);setStatuses(current=>({...current,[created.id]:createdStatus}));setConnectionId(created.id);setDetailFromCreate(true);setProfileId("");setPhoneNumberId("");setBusinessAccountId("");go("detail");setNotice(t("waGuide.notice.created"));}catch{setError(true);}finally{setPending(false);}};
  const saveCredential=async():Promise<void>=>{if(!workspaceId||!companyId||!connectionId||!accessToken.trim()||pending)return;setPending(true);resetMessages();try{const updated=await atlasApi.configureWhatsAppCredentials(csrf,workspaceId,companyId,connectionId,accessToken.trim());setStatuses(current=>({...current,[connectionId]:updated}));setAccessToken("");setShowToken(false);setReplaceToken(false);setNotice(t("waGuide.notice.credential"));}catch{setAccessToken("");setError(true);}finally{setPending(false);}};
  const operation=async(action:"validate"|"activate"|"deactivate"):Promise<void>=>{if(!workspaceId||!companyId||!connectionId||pending)return;setPending(true);resetMessages();try{const updated=action==="validate"?await atlasApi.validateWhatsAppConnection(csrf,workspaceId,companyId,connectionId):action==="activate"?await atlasApi.activateWhatsAppConnection(csrf,workspaceId,companyId,connectionId):await atlasApi.deactivateWhatsAppConnection(csrf,workspaceId,companyId,connectionId);setStatuses(current=>({...current,[connectionId]:updated}));setConnections(current=>current.map(item=>item.id===connectionId?updated.connection:item));if(action==="validate"&&updated.validationState!=="valid")setError(true);else setNotice(t(action==="validate"?"waGuide.notice.validated":action==="activate"?"waGuide.notice.activated":"waGuide.notice.deactivated"));}catch{setError(true);}finally{setPending(false);}};
  if(!workspaceId||!companyId)return <section className="authenticated-section"><h2>{t("whatsapp.title")}</h2><p>{t("whatsapp.companyRequired")}</p></section>; if(!readable)return null;
  const back=<ContextBackLink href={`/companies/${companyId}/channels`} label={t("channels.back")}/>;
  if(error&&connections.length===0&&view==="overview"&&!loading)return <section className="authenticated-section whatsapp-guide">{back}<ProductHero eyebrow={t("waGuide.channel")} title={t("waGuide.title")} description={t("waGuide.lead")}/><div className="inline-message inline-message--error" role="alert"><strong>{t("waGuide.error.generic")}</strong><p>{t("waGuide.error.next")}</p><button className="button button--secondary" type="button" onClick={()=>void load()}>{t("common.retry")}</button></div></section>;
  return <section className="authenticated-section whatsapp-guide" aria-busy={loading||pending}>{view==="overview"&&back}<ProductHero eyebrow={t("waGuide.channel")} title={t("waGuide.title")} description={t("waGuide.lead")}/>
    {error&&<div className="inline-message inline-message--error" role="alert"><strong>{t(status?.validationFailureCode?failureKey(model?.failure??"unknown"):"waGuide.error.generic")}</strong><p>{t("waGuide.error.next")}</p><button className="button button--secondary" type="button" onClick={()=>void load()}>{t("common.retry")}</button></div>}{notice&&<p className="inline-message inline-message--success" role="status">{notice}</p>}
    {loading?<p role="status">{t("waGuide.loading")}</p>:
      view==="overview"?<Overview connections={connections} statuses={statuses} profiles={profiles} manageable={manageable} onOpen={openConnection} onStart={()=>go("situation")} t={t} formatDate={formatDate}/>:
      view==="situation"?<SituationChoice selected={situation} onSelect={(next)=>{if(next!==situation)setPrerequisiteAcknowledged(false);setSituation(next);}} onContinue={()=>go(situation==="unsure"?"diagnose":"guidance")} onCancel={()=>go("overview")} t={t}/>:
      view==="diagnose"?<DecisionHelper onResolve={(resolved)=>{setSituation(resolved);setPrerequisiteAcknowledged(false);go("guidance");}} onBack={()=>go("situation")} t={t}/>:
      view==="guidance"&&situation?<ScenarioGuidance situation={situation} acknowledged={prerequisiteAcknowledged} onAcknowledge={setPrerequisiteAcknowledged} onContinue={()=>go("create")} onBack={()=>go("situation")} t={t}/>:
      view==="create"?<CreateWorkspace readyProfiles={readyProfiles} profileId={profileId} phoneNumberId={phoneNumberId} businessAccountId={businessAccountId} pending={pending} onProfile={setProfileId} onPhone={setPhoneNumberId} onBusiness={setBusinessAccountId} onCreate={()=>void create()} onCancel={()=>go("guidance")} t={t}/>:
      status&&activeConnection&&model?<ConnectionWorkspace status={status} profile={profiles.find(item=>item.id===activeConnection.assistantProfileId)??null} model={model} accessToken={accessToken} showToken={showToken} replaceToken={replaceToken} pending={pending} onToken={setAccessToken} onShowToken={()=>setShowToken(value=>!value)} onReplace={()=>setReplaceToken(true)} onSave={()=>void saveCredential()} onValidate={()=>void operation("validate")} onActivate={()=>void operation("activate")} onDeactivate={()=>void operation("deactivate")} onBack={()=>go(detailFromCreate?"create":"overview")} t={t} formatDate={formatDate}/>:<p role="status">{t("waGuide.loadingConnection")}</p>}
  </section>;
}

type T=ReturnType<typeof useI18n>["t"]; type DateFormatter=ReturnType<typeof useI18n>["formatDate"];
function Overview({connections,statuses,profiles,manageable,onOpen,onStart,t,formatDate}:{connections:readonly WhatsAppConnection[];statuses:Record<string,WhatsAppConnectionOperationalStatus>;profiles:readonly AssistantProfile[];manageable:boolean;onOpen:(id:string)=>void;onStart:()=>void;t:T;formatDate:DateFormatter}):React.JSX.Element{return <div className="whatsapp-guide__overview">{connections.length===0?<div className="whatsapp-guide__empty"><h3>{t("waGuide.empty.title")}</h3><p>{t("waGuide.empty.lead")}</p>{manageable&&<button className="button button--primary" type="button" onClick={onStart}>{t("waGuide.start")}</button>}</div>:<><div className="whatsapp-guide__summary-heading"><div><h3>{t("waGuide.connections.title")}</h3><p>{t("waGuide.connections.lead")}</p></div>{manageable&&<button className="button button--secondary" type="button" onClick={onStart}>{t("waGuide.createAnother")}</button>}</div><div className="whatsapp-connection-list">{connections.map(connection=>{const status=statuses[connection.id],model=status?buildWhatsAppOnboardingViewModel(status):null;return <article className="whatsapp-connection-summary" key={connection.id}><div><p className="atlas-eyebrow">{t("waGuide.phoneTechnical")}</p><h4>{connection.phoneNumberId}</h4><p>{profiles.find(profile=>profile.id===connection.assistantProfileId)?.name??t("waGuide.profileUnavailable")}</p></div>{status&&<dl><Fact label={t("waGuide.fact.credential")} value={t(status.credentialsConfigured?"waGuide.saved":"waGuide.missing")}/><Fact label={t("waGuide.fact.validation")} value={t(validationKey(status.validationState))}/><Fact label={t("waGuide.fact.activation")} value={t(status.connection.status==="active"?"waGuide.active":"waGuide.inactive")}/><Fact label={t("waGuide.fact.operation")} value={t(healthKey(status.healthState))}/></dl>}<div><p>{t(actionSummary(model?.currentStage??"connection"))}</p>{model?.lastActivityAt&&<small>{t("waGuide.lastActivity",{date:formatDate(model.lastActivityAt)})}</small>}<button className="button button--primary" type="button" onClick={()=>onOpen(connection.id)}>{t("waGuide.continue")}</button></div></article>;})}</div></>}</div>}
function SituationChoice({selected,onSelect,onContinue,onCancel,t}:{selected:Situation|null;onSelect:(value:Situation)=>void;onContinue:()=>void;onCancel:()=>void;t:T}):React.JSX.Element{const options:readonly Situation[]=["new","business","personal","unsure"];return <div className="whatsapp-focused"><button className="button button--quiet" type="button" onClick={onCancel}>{t("common.back")}</button><header><p className="atlas-eyebrow">{t("waGuide.stage.understand")}</p><h3 id="whatsapp-step-heading" tabIndex={-1}>{t("waGuide.situation.title")}</h3><p>{t("waGuide.situation.lead")}</p></header><div className="whatsapp-situation-list">{options.map(option=><button key={option} type="button" className={`whatsapp-situation${selected===option?" is-selected":""}`} aria-pressed={selected===option} onClick={()=>onSelect(option)}><strong>{t(`waGuide.situation.${option}.title`)}</strong><span>{t(`waGuide.situation.${option}.lead`)}</span></button>)}</div><button className="button button--primary" disabled={!selected} onClick={onContinue}>{t("common.continue")}</button></div>}
function ScenarioGuidance({situation,acknowledged,onAcknowledge,onContinue,onBack,t}:{situation:Situation;acknowledged:boolean;onAcknowledge:(value:boolean)=>void;onContinue:()=>void;onBack:()=>void;t:T}):React.JSX.Element{const checklist=situation==="new"?[t("waGuide.situation.new.lead"),t("waGuide.situation.new.guidance"),t("waGuide.phone.helpTitle")]:situation==="business"?[t("waGuide.situation.business.lead"),t("waGuide.situation.business.guidance"),t("waGuide.meta.work")]:[t("waGuide.situation.personal.lead"),t("waGuide.situation.personal.guidance"),t("waGuide.cloudApi")];return <div className="whatsapp-focused"><button className="button button--quiet" type="button" onClick={onBack}>{t("common.back")}</button><header><p className="atlas-eyebrow">{t("waGuide.stage.understand")}</p><h3 id="whatsapp-step-heading" tabIndex={-1}>{t(`waGuide.situation.${situation}.title`)}</h3><p>{t(`waGuide.situation.${situation}.guidance`)}</p></header><section className="whatsapp-scenario-guidance"><h4>{t("waGuide.metaControlled")}</h4><ul>{checklist.map(item=><li key={item}>{item}</li>)}</ul><Responsibility t={t}/><label className="whatsapp-prerequisite-confirm"><input type="checkbox" checked={acknowledged} onChange={event=>onAcknowledge(event.target.checked)}/><span>{t("waGuide.prerequisite.confirm")}</span></label></section><button className="button button--primary" type="button" disabled={!acknowledged} onClick={onContinue}>{t("common.continue")}</button></div>}
function DecisionHelper({onResolve,onBack,t}:{onResolve:(value:Exclude<Situation,"unsure">)=>void;onBack:()=>void;t:T}):React.JSX.Element{const choices:readonly Exclude<Situation,"unsure">[]=["business","personal","new"];return <div className="whatsapp-focused"><button className="button button--quiet" type="button" onClick={onBack}>{t("common.back")}</button><header><p className="atlas-eyebrow">{t("waGuide.situation.unsure.title")}</p><h3 id="whatsapp-step-heading" tabIndex={-1}>{t("waGuide.situation.title")}</h3><p>{t("waGuide.situation.unsure.guidance")}</p></header><div className="whatsapp-decision-list">{choices.map(choice=><button className="whatsapp-situation" type="button" key={choice} onClick={()=>onResolve(choice)}><strong>{t(`waGuide.situation.${choice}.title`)}</strong><span>{t(`waGuide.situation.${choice}.lead`)}</span></button>)}</div></div>}
function CreateWorkspace({readyProfiles,profileId,phoneNumberId,businessAccountId,pending,onProfile,onPhone,onBusiness,onCreate,onCancel,t}:{readyProfiles:readonly AssistantProfile[];profileId:string;phoneNumberId:string;businessAccountId:string;pending:boolean;onProfile:(v:string)=>void;onPhone:(v:string)=>void;onBusiness:(v:string)=>void;onCreate:()=>void;onCancel:()=>void;t:T}):React.JSX.Element{return <div className="whatsapp-focused"><button className="button button--quiet" type="button" disabled={pending} onClick={onCancel}>{t("common.back")}</button><header><p className="atlas-eyebrow">{t("waGuide.stage.connect")}</p><h3 id="whatsapp-step-heading" tabIndex={-1}>{t("waGuide.create.title")}</h3><p>{t("waGuide.create.lead")}</p></header><Responsibility t={t}/><div className="whatsapp-create-guided"><label className="form-field"><span>{t("whatsapp.profileSelect")}</span><select value={profileId} onChange={e=>onProfile(e.target.value)}><option value="">{t("whatsapp.profilePlaceholder")}</option>{readyProfiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><TechnicalField label={t("waGuide.phone.label")} value={phoneNumberId} onChange={onPhone} helpTitle={t("waGuide.phone.helpTitle")} help={t("waGuide.phone.help")}/><TechnicalField label={t("waGuide.business.label")} value={businessAccountId} onChange={onBusiness} helpTitle={t("waGuide.business.helpTitle")} help={t("waGuide.business.help")}/></div>{readyProfiles.length===0&&<p className="inline-message inline-message--warning">{t("waGuide.noReadyProfile")}</p>}<button className="button button--primary" disabled={pending||!profileId||!phoneNumberId.trim()||!businessAccountId.trim()} onClick={onCreate}>{t("waGuide.create.action")}</button></div>}
function ConnectionWorkspace({status,profile,model,accessToken,showToken,replaceToken,pending,onToken,onShowToken,onReplace,onSave,onValidate,onActivate,onDeactivate,onBack,t,formatDate}:{status:WhatsAppConnectionOperationalStatus;profile:AssistantProfile|null;model:ReturnType<typeof buildWhatsAppOnboardingViewModel>;accessToken:string;showToken:boolean;replaceToken:boolean;pending:boolean;onToken:(v:string)=>void;onShowToken:()=>void;onReplace:()=>void;onSave:()=>void;onValidate:()=>void;onActivate:()=>void;onDeactivate:()=>void;onBack:()=>void;t:T;formatDate:DateFormatter}):React.JSX.Element{return <div className="whatsapp-focused"><button className="button button--quiet" type="button" onClick={onBack}>{t("waGuide.backConnections")}</button><header><p className="atlas-eyebrow">{t("waGuide.phoneTechnical")}</p><h3>{status.connection.phoneNumberId}</h3><p>{profile?.name??t("waGuide.profileUnavailable")}</p></header><ol className="whatsapp-stage-list">{model.stages.map(stage=><li key={stage.id} className={`is-${stage.state}`} aria-current={stage.state==="current"?"step":undefined}><span>{t(stage.state==="complete"?"waGuide.stage.complete":stage.state==="current"?"waGuide.stage.current":"waGuide.stage.future")}</span><strong>{t(stageKey(stage.id))}</strong>{stage.state==="current"&&<CurrentStage stage={stage.id} status={status} modelFailure={model.failure} accessToken={accessToken} showToken={showToken} replaceToken={replaceToken} pending={pending} onToken={onToken} onShowToken={onShowToken} onReplace={onReplace} onSave={onSave} onValidate={onValidate} onActivate={onActivate} t={t}/>}</li>)}</ol><dl className="whatsapp-safe-activity"><Fact label={t("waGuide.fact.webhook")} value={status.lastWebhookActivityAt?formatDate(status.lastWebhookActivityAt):t("waGuide.activity.none")}/><Fact label={t("waGuide.fact.provider")} value={status.lastProviderActivityAt?formatDate(status.lastProviderActivityAt):t("waGuide.activity.none")}/></dl>{status.connection.status==="active"&&<button className="button button--danger-quiet" disabled={pending} onClick={onDeactivate}>{t("whatsapp.deactivate")}</button>}</div>}
function CurrentStage({stage,status,modelFailure,accessToken,showToken,replaceToken,pending,onToken,onShowToken,onReplace,onSave,onValidate,onActivate,t}:{stage:WhatsAppStageId;status:WhatsAppConnectionOperationalStatus;modelFailure:WhatsAppFailureKind|null;accessToken:string;showToken:boolean;replaceToken:boolean;pending:boolean;onToken:(v:string)=>void;onShowToken:()=>void;onReplace:()=>void;onSave:()=>void;onValidate:()=>void;onActivate:()=>void;t:T}):React.JSX.Element{if(stage==="credential")return <div className="whatsapp-current-stage"><p>{t("waGuide.credential.lead")}</p>{status.credentialsConfigured&&!replaceToken?<><p role="status">{t("waGuide.credential.saved")}</p><button className="button button--secondary" onClick={onReplace}>{t("waGuide.credential.replace")}</button></>:<><label className="form-field"><span>{t("waGuide.token.label")}</span><span className="secure-input"><input type={showToken?"text":"password"} autoComplete="new-password" value={accessToken} onChange={e=>onToken(e.target.value)}/><button type="button" onClick={onShowToken}>{t(showToken?"auth.password.hide":"auth.password.show")}</button></span></label><p>{t("waGuide.token.warning")}</p><Disclosure title={t("waGuide.token.helpTitle")} text={t("waGuide.token.help")}/><button className="button button--primary" disabled={pending||!accessToken.trim()} onClick={onSave}>{t("waGuide.credential.save")}</button></>}</div>;if(stage==="validation")return <div className="whatsapp-current-stage"><p>{t("waGuide.validation.lead")}</p>{modelFailure&&<aside className="inline-message inline-message--error"><strong>{t(failureKey(modelFailure))}</strong><p>{t("waGuide.error.next")}</p></aside>}<Disclosure title={t("waGuide.validation.whatTitle")} text={t("waGuide.validation.what")}/><button className="button button--primary" disabled={pending||!status.credentialsConfigured} onClick={onValidate}>{t("waGuide.validation.action")}</button></div>;if(stage==="activation")return <div className="whatsapp-current-stage"><p>{t("waGuide.activation.lead")}</p><p>{t("waGuide.activation.constraint")}</p><button className="button button--primary" disabled={pending||status.validationState!=="valid"} onClick={onActivate}>{t("waGuide.activation.action")}</button></div>;return <div className="whatsapp-current-stage"><h4>{t("waGuide.test.title")}</h4><p>{t("waGuide.test.instructions")}</p><ol><li>{t("waGuide.test.send")}</li><li>{t("waGuide.test.wait")}</li><li>{t("waGuide.test.check")}</li></ol>{!status.lastWebhookActivityAt&&<p>{t("waGuide.test.noWebhook")}</p>}</div>}
function Responsibility({t}:{t:T}):React.JSX.Element{return <div className="whatsapp-responsibility"><section><h4>{t("waGuide.meta.title")}</h4><p>{t("waGuide.meta.work")}</p></section><section><h4>{t("waGuide.atlas.title")}</h4><p>{t("waGuide.atlas.work")}</p></section></div>}
function TechnicalField({label,value,onChange,helpTitle,help}:{label:string;value:string;onChange:(v:string)=>void;helpTitle:string;help:string}):React.JSX.Element{return <div><label className="form-field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} maxLength={256}/></label><Disclosure title={helpTitle} text={help}/></div>}
function Disclosure({title,text}:{title:string;text:string}):React.JSX.Element{const [open,setOpen]=useState(false);return <div className="whatsapp-disclosure"><button type="button" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span>{title}</span><span aria-hidden="true">{open?"−":"+"}</span></button>{open&&<p>{text}</p>}</div>}
function Fact({label,value}:{label:string;value:string}):React.JSX.Element{return <div><dt>{label}</dt><dd>{value}</dd></div>}
const stageKey=(stage:WhatsAppStageId):Parameters<T>[0]=>`waGuide.stage.${stage}`; const validationKey=(state:WhatsAppConnectionOperationalStatus["validationState"]):Parameters<T>[0]=>state==="valid"?"waGuide.validation.valid":state==="invalid"?"waGuide.validation.invalid":"waGuide.validation.pending"; const healthKey=(state:WhatsAppConnectionOperationalStatus["healthState"]):Parameters<T>[0]=>state==="healthy"?"waGuide.health.healthy":state==="degraded"?"waGuide.health.degraded":"waGuide.health.inactive"; const actionSummary=(stage:WhatsAppStageId):Parameters<T>[0]=>`waGuide.next.${stage}`; const failureKey=(failure:WhatsAppFailureKind):Parameters<T>[0]=>`waGuide.failure.${failure}`;
