// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { I18nProvider } from "../i18n/I18nContext";
import type { AssistantProfile, WhatsAppConnectionOperationalStatus } from "../types/api";
import { WhatsAppOnboardingPanel } from "./WhatsAppOnboardingPanel";

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const profile:AssistantProfile={id:"asp_0123456789abcdef0123456789abcdef",name:"Sales Assistant",description:null,businessRole:null,objective:null,audience:null,tone:"friendly",assistantLanguage:"en",welcomeMessage:null,fallbackMessage:"Fallback",status:"ready",createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null};
const operational=(overrides:Partial<WhatsAppConnectionOperationalStatus>={}):WhatsAppConnectionOperationalStatus=>({connection:{id:"wac_0123456789abcdef0123456789abcdef",assistantProfileId:profile.id,phoneNumberId:"123456789012345",whatsappBusinessAccountId:"456789012345678",status:"inactive",createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"},credentialsConfigured:false,validationState:"not_validated",validatedAt:null,validationFailureCode:null,healthState:"inactive",lastProviderActivityAt:null,lastWebhookActivityAt:null,healthFailureCode:null,updatedAt:"2026-01-01T00:00:00.000Z",...overrides});
function renderPanel(){return render(<I18nProvider><WhatsAppOnboardingPanel csrf="csrf" workspaceId="wsp" companyId={1} profiles={[profile]} capabilities={["company:read","company:manage"]}/></I18nProvider>)}
afterEach(()=>{cleanup();vi.restoreAllMocks();window.localStorage.clear();});

describe("guided WhatsApp onboarding",()=>{
  it("shows a focused no-connection entry without the legacy checklist",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json([])));renderPanel();expect(await screen.findByRole("heading",{name:"WhatsApp is not connected yet"})).toBeTruthy();expect(screen.getByRole("button",{name:"Start setup"})).toBeTruthy();expect(screen.queryByText("Company context")).toBeNull();expect(screen.getByRole("link",{name:"Back to places to work"}).getAttribute("href")).toBe("/companies/1/channels");});
  it("does not offer duplicate creation while loading or after a failed load",async()=>{let reject!:(reason:unknown)=>void;const promise=new Promise<Response>((_,value)=>{reject=value});vi.stubGlobal("fetch",vi.fn().mockReturnValue(promise));renderPanel();expect(screen.queryByRole("button",{name:"Start setup"})).toBeNull();reject(new Error("offline"));expect(await screen.findByRole("alert")).toBeTruthy();expect(screen.queryByRole("button",{name:"Start setup"})).toBeNull();});
  it("explains all four situations without claiming personal-account conversion",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json([])));renderPanel();fireEvent.click(await screen.findByRole("button",{name:"Start setup"}));for(const name of ["I have a new number for the business","I already use WhatsApp Business with this number","I currently use personal WhatsApp","I am not sure"])expect(screen.getByRole("button",{name:new RegExp(name)})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/I currently use personal WhatsApp/}));fireEvent.click(screen.getByRole("button",{name:"Continue"}));expect(screen.getAllByText(/Atlas cannot convert this account/).length).toBeGreaterThan(0);});
  it("preserves the exact connection payload and keeps the token out of creation",async()=>{const created=operational().connection;const fetchMock=vi.fn().mockResolvedValueOnce(json([])).mockResolvedValueOnce(json(created)).mockResolvedValueOnce(json(operational()));vi.stubGlobal("fetch",fetchMock);renderPanel();fireEvent.click(await screen.findByRole("button",{name:"Start setup"}));fireEvent.click(screen.getByRole("button",{name:/I have a new number/}));fireEvent.click(screen.getByRole("button",{name:"Continue"}));fireEvent.click(screen.getByRole("checkbox"));fireEvent.click(screen.getByRole("button",{name:"Continue"}));fireEvent.change(screen.getByLabelText("Ready profile"),{target:{value:profile.id}});fireEvent.change(screen.getByLabelText("WhatsApp Phone Number ID"),{target:{value:"123"}});fireEvent.change(screen.getByLabelText("WhatsApp Business Account ID"),{target:{value:"456"}});fireEvent.click(screen.getByRole("button",{name:"Create connection"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));expect(JSON.parse(String(fetchMock.mock.calls[1]?.[1]?.body))).toEqual({assistantProfileId:profile.id,phoneNumberId:"123",whatsappBusinessAccountId:"456"});expect(String(fetchMock.mock.calls[1]?.[1]?.body)).not.toContain("accessToken");});
  it("opens one existing connection directly with its management details",async()=>{const current=operational({credentialsConfigured:true});vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(json([current.connection])).mockResolvedValueOnce(json(current)));renderPanel();expect(await screen.findByRole("heading",{name:"123456789012345"})).toBeTruthy();expect(screen.queryByRole("button",{name:"Continue setup"})).toBeNull();expect(screen.getByText("Validate the connection").closest("li")?.getAttribute("aria-current")).toBe("step");expect(screen.getByText("WhatsApp Business Account ID")).toBeTruthy();expect(screen.getByText("456789012345678")).toBeTruthy();expect(screen.getAllByText("Sales Assistant").length).toBeGreaterThan(0);expect(screen.getByRole("button",{name:"Edit"})).toBeTruthy();expect(screen.getByRole("button",{name:"Replace credential"})).toBeTruthy();expect(document.querySelectorAll('[aria-current="step"]')).toHaveLength(1);});
  it("never renders a stored token and replacement uses the unchanged credential payload",async()=>{const current=operational({credentialsConfigured:true,validationState:"invalid",validatedAt:"2026-01-02T00:00:00.000Z",validationFailureCode:"invalid_credentials",healthState:"degraded",healthFailureCode:"invalid_credentials"});const updated=operational({credentialsConfigured:true});const fetchMock=vi.fn().mockResolvedValueOnce(json([current.connection])).mockResolvedValueOnce(json(current)).mockResolvedValueOnce(json(updated));vi.stubGlobal("fetch",fetchMock);renderPanel();await screen.findByRole("heading",{name:"123456789012345"});expect(screen.queryByLabelText("Access token")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Replace credential"}));fireEvent.change(screen.getByLabelText("Access token"),{target:{value:"secret-token"}});fireEvent.click(screen.getByRole("button",{name:"Save credential"}));await waitFor(()=>expect(screen.queryByDisplayValue("secret-token")).toBeNull());expect(JSON.parse(String(fetchMock.mock.calls[2]?.[1]?.body))).toEqual({accessToken:"secret-token"});expect(String(fetchMock.mock.calls[2]?.[0])).not.toContain("secret-token");});
  it("edits inactive connection configuration through PATCH and refreshes status",async()=>{const current=operational({credentialsConfigured:true});const changed={...current.connection,phoneNumberId:"999"};const refreshed=operational({connection:changed,credentialsConfigured:true});const fetchMock=vi.fn().mockResolvedValueOnce(json([current.connection])).mockResolvedValueOnce(json(current)).mockResolvedValueOnce(json(changed)).mockResolvedValueOnce(json(refreshed));vi.stubGlobal("fetch",fetchMock);renderPanel();await screen.findByRole("heading",{name:"123456789012345"});fireEvent.click(screen.getByRole("button",{name:"Edit"}));fireEvent.change(screen.getByLabelText("WhatsApp Phone Number ID"),{target:{value:"999"}});fireEvent.click(screen.getByRole("button",{name:"Save"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(4));expect(JSON.parse(String(fetchMock.mock.calls[2]?.[1]?.body))).toEqual({assistantProfileId:profile.id,phoneNumberId:"999",whatsappBusinessAccountId:current.connection.whatsappBusinessAccountId});expect(screen.getAllByText("999").length).toBeGreaterThan(0);});
  it("blocks activation until valid and maps provider failures without raw diagnostics",async()=>{const current=operational({credentialsConfigured:true}),invalid=operational({credentialsConfigured:true,validationState:"invalid",validatedAt:"2026-01-02T00:00:00.000Z",validationFailureCode:"insufficient_permissions",healthState:"degraded",healthFailureCode:"insufficient_permissions"});const fetchMock=vi.fn().mockResolvedValueOnce(json([current.connection])).mockResolvedValueOnce(json(current)).mockResolvedValueOnce(json(invalid));vi.stubGlobal("fetch",fetchMock);renderPanel();await screen.findByRole("heading",{name:"123456789012345"});fireEvent.click(screen.getByRole("button",{name:"Validate connection"}));expect((await screen.findByRole("alert")).textContent).toContain("required permissions");expect(document.body.textContent).not.toContain("fbtrace");expect(screen.queryByRole("button",{name:"Activate WhatsApp"})).toBeNull();});
  it("keeps multiple connections independently scannable",async()=>{const first=operational(),second=operational({connection:{...operational().connection,id:"wac_1123456789abcdef0123456789abcdef",phoneNumberId:"999999999999999"}});vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(json([first.connection,second.connection])).mockResolvedValueOnce(json(first)).mockResolvedValueOnce(json(second)));renderPanel();expect(await screen.findByRole("heading",{name:"123456789012345"})).toBeTruthy();expect(screen.getByRole("heading",{name:"999999999999999"})).toBeTruthy();expect(screen.getAllByRole("button",{name:"Continue setup"})).toHaveLength(2);});
  it("provides the approved Spanish entry copy",async()=>{window.localStorage.setItem("atlas.locale","es");vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json([])));renderPanel();expect(await screen.findByRole("heading",{name:"Conectar WhatsApp"})).toBeTruthy();expect(screen.getByText("Prepará el número de tu empresa para que Atlas pueda recibir y responder conversaciones.")).toBeTruthy();expect(screen.getByRole("button",{name:"Comenzar configuración"})).toBeTruthy();});
  it("uses deterministic in-wizard Back actions and restores focus",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json([])));renderPanel();fireEvent.click(await screen.findByRole("button",{name:"Start setup"}));expect(screen.queryByRole("link",{name:"Back to places to work"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:/I have a new number/}));fireEvent.click(screen.getByRole("button",{name:"Continue"}));await waitFor(()=>expect(document.activeElement).toBe(screen.getByRole("heading",{name:"I have a new number for the business"})));fireEvent.click(screen.getByRole("button",{name:"Back"}));expect(screen.getByRole("heading",{name:"How will you connect WhatsApp?"})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Back"}));expect(screen.getByRole("button",{name:"Start setup"})).toBeTruthy();});
  it("routes the unsure choice through a decision helper before scenario guidance",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json([])));renderPanel();fireEvent.click(await screen.findByRole("button",{name:"Start setup"}));fireEvent.click(screen.getByRole("button",{name:/I am not sure/}));fireEvent.click(screen.getByRole("button",{name:"Continue"}));expect(screen.getByRole("button",{name:/I already use WhatsApp Business/})).toBeTruthy();expect(screen.queryByLabelText("Ready profile")).toBeNull();fireEvent.click(screen.getByRole("button",{name:/I currently use personal WhatsApp/}));expect(screen.getAllByText(/Atlas cannot convert this account/).length).toBeGreaterThan(0);});
  it("requires a distinct prerequisite acknowledgement for every resolved scenario",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json([])));renderPanel();fireEvent.click(await screen.findByRole("button",{name:"Start setup"}));for(const choice of [/I have a new number/,/I already use WhatsApp Business/,/I currently use personal WhatsApp/]){fireEvent.click(screen.getByRole("button",{name:choice}));fireEvent.click(screen.getByRole("button",{name:"Continue"}));expect(screen.queryByLabelText("Ready profile")).toBeNull();expect((screen.getByRole("button",{name:"Continue"}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole("checkbox") as HTMLInputElement).checked).toBe(false);fireEvent.click(screen.getByRole("checkbox"));expect((screen.getByRole("button",{name:"Continue"}) as HTMLButtonElement).disabled).toBe(false);fireEvent.click(screen.getByRole("button",{name:"Back"}));}});
  it("returns from the shared form to its prerequisite without clearing non-secret values",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json([])));renderPanel();fireEvent.click(await screen.findByRole("button",{name:"Start setup"}));fireEvent.click(screen.getByRole("button",{name:/I have a new number/}));fireEvent.click(screen.getByRole("button",{name:"Continue"}));fireEvent.click(screen.getByRole("checkbox"));fireEvent.click(screen.getByRole("button",{name:"Continue"}));fireEvent.change(screen.getByLabelText("WhatsApp Phone Number ID"),{target:{value:"123"}});fireEvent.change(screen.getByLabelText("WhatsApp Business Account ID"),{target:{value:"456"}});fireEvent.click(screen.getByRole("button",{name:"Back"}));expect((screen.getByRole("checkbox") as HTMLInputElement).checked).toBe(true);fireEvent.click(screen.getByRole("button",{name:"Continue"}));expect((screen.getByLabelText("WhatsApp Phone Number ID") as HTMLInputElement).value).toBe("123");expect((screen.getByLabelText("WhatsApp Business Account ID") as HTMLInputElement).value).toBe("456");});
});
