import type { MediaService } from "../../media/services/mediaService.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { SpeechSynthesisPort } from "../application/speechSynthesisPort.js";
import type { AsyncVoiceRepositoryPort, VoiceRepositoryPort } from "../application/voicePorts.js";
import type { VoiceSynthesisRequest } from "../domain/voice.js";
import { operationalLogger } from "../../observability/operationalLogger.js";

export type VoiceSynthesisWorkerOutcome={readonly kind:"completed"|"failed"|"retryable"|"suppressed"|"lease_lost";readonly requestId:string;};
export interface VoiceSynthesisWorkerOptions{readonly owner:string;readonly batchSize:number;readonly leaseMilliseconds:number;readonly synthesisTimeoutMilliseconds:number;}

export class VoiceSynthesisWorkerService {
  public constructor(private readonly voices:VoiceRepositoryPort|AsyncVoiceRepositoryPort,private readonly media:Pick<MediaService,"store">,private readonly speech:SpeechSynthesisPort,private readonly clock:{now():string},private readonly options:VoiceSynthesisWorkerOptions){}
  public async runOnce(context:WorkspaceContext,companyId:number):Promise<readonly VoiceSynthesisWorkerOutcome[]>{const now=this.clock.now(),requests=await this.voices.leaseSynthesis(context,companyId,{owner:this.options.owner,now,expiresAt:new Date(Date.parse(now)+this.options.leaseMilliseconds).toISOString(),limit:this.options.batchSize});return Promise.all(requests.map(request=>this.synthesize(context,companyId,request)));}
  private async synthesize(context:WorkspaceContext,companyId:number,request:VoiceSynthesisRequest):Promise<VoiceSynthesisWorkerOutcome>{const authorized=await this.voices.authorizeSynthesis(context,companyId,request.id,this.options.owner,this.clock.now());if(authorized.kind!=="authorized")return{kind:authorized.kind,requestId:request.id};const result=await this.callProvider(authorized.text);const at=this.clock.now();if(result.kind!=="completed")return this.settle(context,companyId,request,result.kind,result.safeFailureCategory,at);try{const asset=await this.media.store(context,companyId,{operation:"ingest",idempotencyKey:`voice-synthesis:${request.id}`,declaredMediaType:result.mimeType,filename:"assistant.ogg",content:bytes(result.audio)}),saved=await this.voices.finalizeSynthesis(context,companyId,request.id,this.options.owner,{kind:"completed",mediaAssetId:asset.id,updatedAt:this.clock.now()});return{kind:saved?.state==="suppressed"?"suppressed":saved===null?"lease_lost":"completed",requestId:request.id};}catch{return this.settle(context,companyId,request,"retryable","media_persistence_failed",this.clock.now());}}
  private async callProvider(text:string):Promise<Awaited<ReturnType<SpeechSynthesisPort["synthesize"]>>>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;try{const timeout=new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>{controller.abort();reject(new Error("synthesis_timeout"));},this.options.synthesisTimeoutMilliseconds);});return await Promise.race([this.speech.synthesize({text,signal:controller.signal}),timeout]);}catch{return{kind:"retryable",safeFailureCategory:controller.signal.aborted?"timeout":"provider_unavailable"};}finally{if(timer)clearTimeout(timer);}}
  private async settle(context:WorkspaceContext,companyId:number,request:VoiceSynthesisRequest,kind:"retryable"|"failed",safeFailureCategory:string,updatedAt:string):Promise<VoiceSynthesisWorkerOutcome>{operationalLogger.warn("voice_synthesis_failed",{subsystem:"voice",operation:"synthesis",outcome:kind,workspaceId:context.workspaceId,companyId,safeErrorCategory:safeFailureCategory});const saved=await this.voices.finalizeSynthesis(context,companyId,request.id,this.options.owner,{kind,safeFailureCategory,updatedAt});return{kind:saved?.state==="suppressed"?"suppressed":saved===null?"lease_lost":kind,requestId:request.id};}
}
async function* bytes(value:Uint8Array):AsyncIterable<Uint8Array>{yield value;}
