import { runtimeWorkerCycleFailed, runtimeWorkerCycleStarted, runtimeWorkerCycleSucceeded, runtimeWorkerHealth, runtimeWorkerStageCleared, runtimeWorkerStageStarted, runtimeWorkerStarted, runtimeWorkerStopped, type WhatsAppRecoveryStage } from "../../config/runtimeReadiness.js";
import { createRunId, normalizeOperationalError, operationalLogger, withRunContext } from "../../observability/operationalLogger.js";

type Timer = { unref(): void };
export interface WhatsAppRecoveryRuntimeDependencies { readonly schedule?: (callback: () => void, milliseconds: number) => Timer; readonly clear?: (timer: Timer) => void; readonly reportError?: () => void; }

/** Serializes durable WhatsApp recovery cycles and fences timer work during shutdown. */
export class WhatsAppRecoveryRuntime {
  private timer: Timer | null = null;
  private running: Promise<void> | null = null;
  private started = false;
  private readonly schedule: (callback: () => void, milliseconds: number) => Timer;
  private readonly clear: (timer: Timer) => void;
  public constructor(private readonly recover: (onStage: (stage: WhatsAppRecoveryStage | null) => void) => Promise<void>, dependencies: WhatsAppRecoveryRuntimeDependencies = {}, private readonly intervalMilliseconds = 5_000) { this.schedule = dependencies.schedule ?? ((callback, milliseconds) => setInterval(callback, milliseconds)); this.clear = dependencies.clear ?? ((timer) => clearInterval(timer as ReturnType<typeof setInterval>)); }
  public start(): void { if (this.started) return; this.started = true; runtimeWorkerStarted("whatsapp_recovery"); operationalLogger.info("whatsapp_recovery_started", { worker: "whatsapp_recovery", outcome: "started" }); this.timer = this.schedule(() => { void this.run(); }, this.intervalMilliseconds); this.timer.unref(); void this.run(); }
  public async stop(): Promise<void> { if (!this.started && !this.running) return; this.started = false; if (this.timer) { this.clear(this.timer); this.timer = null; } await this.running; runtimeWorkerStopped("whatsapp_recovery"); }
  private run(): Promise<void> { if (!this.started || this.running) return this.running ?? Promise.resolve(); runtimeWorkerCycleStarted("whatsapp_recovery"); const runId = createRunId(), startedAt = performance.now(); const cycle = withRunContext(runId, () => this.recover(stage => { if (stage) runtimeWorkerStageStarted("whatsapp_recovery", stage); else runtimeWorkerStageCleared("whatsapp_recovery"); })).then(() => { const failures = runtimeWorkerHealth("whatsapp_recovery")?.consecutiveFailures ?? 0; runtimeWorkerCycleSucceeded("whatsapp_recovery"); if (failures > 0) operationalLogger.info("whatsapp_recovery_recovered", { worker: "whatsapp_recovery", outcome: "recovered", consecutiveFailures: failures, durationMs: Math.round(performance.now() - startedAt), runId }); }).catch((error: unknown) => { const normalized = normalizeOperationalError(error), category = normalized === "database_failure" ? "database_failure" : normalized === "provider_unavailable" || normalized === "provider_timeout" || normalized === "transport_failure" ? "provider_failure" : "internal_failure"; runtimeWorkerCycleFailed("whatsapp_recovery", category); const health = runtimeWorkerHealth("whatsapp_recovery")!; operationalLogger.error("whatsapp_recovery_cycle_failed", { worker: "whatsapp_recovery", stage: health.lastFailedStage ?? "unknown", safeErrorCategory: health.lastErrorCategory!, consecutiveFailures: health.consecutiveFailures, durationMs: Math.round(performance.now() - startedAt), runId }); }).finally(() => { if (this.running === cycle) this.running = null; }); this.running = cycle; return cycle; }
}
