import { runtimeWorkerCycleFailed, runtimeWorkerCycleStarted, runtimeWorkerCycleSucceeded, runtimeWorkerHealth, runtimeWorkerScheduled, runtimeWorkerStageCleared, runtimeWorkerStageStarted, runtimeWorkerSubstageStarted, runtimeWorkerStarted, runtimeWorkerStopped, type WhatsAppRecoveryStage, type WhatsAppResumeSubstage } from "../../config/runtimeReadiness.js";
import { createRunId, normalizeOperationalError, operationalLogger, withRunContext } from "../../observability/operationalLogger.js";

type Timer = { unref(): void };
const idleDelays = [5_000, 10_000, 15_000, 20_000] as const;
export interface WhatsAppRecoveryRuntimeDependencies { readonly schedule?: (callback: () => void, milliseconds: number) => Timer; readonly clear?: (timer: Timer) => void; readonly reportError?: () => void; }

/** Serializes durable WhatsApp recovery cycles and fences timer work during shutdown. */
export class WhatsAppRecoveryRuntime {
  private timer: Timer | null = null;
  private running: Promise<void> | null = null;
  private started = false;
  private emptyStreak = 0;
  private generation = 0;
  private readonly schedule: (callback: () => void, milliseconds: number) => Timer;
  private readonly clear: (timer: Timer) => void;
  public constructor(private readonly recover: (onStage: (stage: WhatsAppRecoveryStage | null) => void, onSubstage: (substage: WhatsAppResumeSubstage) => void) => Promise<number | void>, dependencies: WhatsAppRecoveryRuntimeDependencies = {}) { this.schedule = dependencies.schedule ?? ((callback, milliseconds) => setTimeout(callback, milliseconds)); this.clear = dependencies.clear ?? ((timer) => clearTimeout(timer as ReturnType<typeof setTimeout>)); }
  public start(): void { if (this.started) return; this.generation += 1; this.started = true; runtimeWorkerStarted("whatsapp_recovery"); operationalLogger.info("whatsapp_recovery_started", { worker: "whatsapp_recovery", outcome: "started" }); void this.run(); }
  public async stop(): Promise<void> { if (!this.started && !this.running) return; this.started = false; this.generation += 1; if (this.timer) { this.clear(this.timer); this.timer = null; } await this.running; runtimeWorkerStopped("whatsapp_recovery"); }
  private run(): Promise<void> { if (!this.started || this.running) return this.running ?? Promise.resolve(); runtimeWorkerCycleStarted("whatsapp_recovery"); const runId = createRunId(), startedAt = performance.now(); const cycle = withRunContext(runId, () => this.recover(stage => { if (stage) runtimeWorkerStageStarted("whatsapp_recovery", stage); else runtimeWorkerStageCleared("whatsapp_recovery"); }, substage => runtimeWorkerSubstageStarted("whatsapp_recovery", substage))).then((workCount) => { const failures = runtimeWorkerHealth("whatsapp_recovery")?.consecutiveFailures ?? 0; runtimeWorkerCycleSucceeded("whatsapp_recovery"); if (failures > 0) operationalLogger.info("whatsapp_recovery_recovered", { worker: "whatsapp_recovery", outcome: "recovered", consecutiveFailures: failures, durationMs: Math.round(performance.now() - startedAt), runId }); this.scheduleNext(this.nextDelay(workCount ?? 0)); }).catch((error: unknown) => { const normalized = normalizeOperationalError(error), category = normalized === "database_failure" ? "database_failure" : normalized === "provider_unavailable" || normalized === "provider_timeout" || normalized === "transport_failure" ? "provider_failure" : "internal_failure"; runtimeWorkerCycleFailed("whatsapp_recovery", category); this.emptyStreak = 0; const health = runtimeWorkerHealth("whatsapp_recovery")!; operationalLogger.error("whatsapp_recovery_cycle_failed", { worker: "whatsapp_recovery", stage: health.lastFailedStage ?? "unknown", substage: health.lastFailedSubstage ?? "none", safeErrorCategory: health.lastErrorCategory!, consecutiveFailures: health.consecutiveFailures, durationMs: Math.round(performance.now() - startedAt), runId }); this.scheduleNext(idleDelays[0]); }).finally(() => { if (this.running === cycle) this.running = null; }); this.running = cycle; return cycle; }
  private nextDelay(workCount: number): number { if (workCount > 0) { this.emptyStreak = 0; return idleDelays[0]; } const index = Math.min(this.emptyStreak, idleDelays.length - 1); this.emptyStreak = Math.min(this.emptyStreak + 1, idleDelays.length - 1); return idleDelays[index]!; }
  private scheduleNext(delay: number): void { if (!this.started) return; const generation = this.generation; runtimeWorkerScheduled("whatsapp_recovery", Date.now() + delay); this.timer = this.schedule(() => { if (this.started && this.generation === generation) void this.run(); }, delay); this.timer.unref(); }
}
