import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { CompanyKnowledge } from "../../types/companyKnowledge.js";
import { KnowledgeDomainError, validateExtractedBusinessKnowledge, validateStoredCompanyKnowledgeJson, type CompanyKnowledgeVersion, type ExtractedBusinessKnowledge, type KnowledgeSource, type KnowledgeSourceKind, type KnowledgeSourceRevision } from "../domain/knowledge.js";

type Row=Record<string,string|number|null>;
const sourceSelect="SELECT s.* FROM knowledge_sources s JOIN companies co ON co.id=s.company_id";
const revisionSelect="SELECT r.* FROM knowledge_source_revisions r JOIN knowledge_sources s ON s.id=r.source_id JOIN companies co ON co.id=s.company_id";
function source(row:Row):KnowledgeSource{return{id:String(row.id),companyId:Number(row.company_id),kind:String(row.kind)as KnowledgeSourceKind,origin:String(row.origin)as KnowledgeSource["origin"],name:String(row.name),normalizedName:String(row.normalized_name),locator:row.locator===null?null:String(row.locator),status:String(row.status)as KnowledgeSource["status"],version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at),archivedAt:row.archived_at===null?null:String(row.archived_at)};}
function json(value:string):unknown{try{return JSON.parse(value);}catch{throw new KnowledgeDomainError("knowledge_integrity_failure");}}
function revision(row:Row):KnowledgeSourceRevision{return{id:String(row.id),sourceId:String(row.source_id),revisionNumber:Number(row.revision_number),status:String(row.status)as KnowledgeSourceRevision["status"],mediaType:String(row.media_type),contentDigest:row.content_digest===null?null:String(row.content_digest),normalizedText:row.normalized_text===null?null:String(row.normalized_text),extractedKnowledge:row.extracted_knowledge_json===null?null:validateExtractedBusinessKnowledge(json(String(row.extracted_knowledge_json))),extractorSchemaVersion:"company-business-knowledge-v1",inputBytes:Number(row.input_bytes),normalizedBytes:row.normalized_bytes===null?null:Number(row.normalized_bytes),normalizedCharacters:row.normalized_characters===null?null:Number(row.normalized_characters),pageCount:row.page_count===null?null:Number(row.page_count),failureCode:row.failure_code===null?null:String(row.failure_code),createdAt:String(row.created_at),completedAt:row.completed_at===null?null:String(row.completed_at)};}
function version(row:Row,ids:readonly string[]):CompanyKnowledgeVersion{return{id:String(row.id),companyId:Number(row.company_id),versionNumber:Number(row.version_number),compilerVersion:"company-knowledge-compiler-v1",knowledge:validateStoredCompanyKnowledgeJson(String(row.knowledge_json)),snapshotDigest:String(row.snapshot_digest),publishedByActorId:String(row.published_by_actor_id),publishedAt:String(row.published_at),sourceRevisionIds:ids,publicationVersion:Number(row.publication_version)};}

/** Async persistence boundary for Knowledge administration, source ingestion, and publication. */
export class AsyncCompanyKnowledgeRepository {
  public constructor(private readonly database:SqlDatabase){}
  public async listSources(c:WorkspaceContext,companyId:number):Promise<readonly KnowledgeSource[]>{return(await this.database.query<Row>(`${sourceSelect} WHERE co.workspace_id=? AND co.id=? ORDER BY s.created_at DESC,s.id DESC`,[c.workspaceId,companyId])).map(source);}
  public async findSource(c:WorkspaceContext,companyId:number,id:string):Promise<KnowledgeSource|null>{const rows=await this.database.query<Row>(`${sourceSelect} WHERE co.workspace_id=? AND co.id=? AND s.id=?`,[c.workspaceId,companyId,id]);return rows[0]?source(rows[0]):null;}
  public async findRevision(c:WorkspaceContext,companyId:number,sourceId:string,id:string):Promise<KnowledgeSourceRevision|null>{const rows=await this.database.query<Row>(`${revisionSelect} WHERE co.workspace_id=? AND co.id=? AND s.id=? AND r.id=?`,[c.workspaceId,companyId,sourceId,id]);return rows[0]?revision(rows[0]):null;}
  public async latestRevision(c:WorkspaceContext,companyId:number,sourceId:string):Promise<KnowledgeSourceRevision|null>{const rows=await this.database.query<Row>(`${revisionSelect} WHERE co.workspace_id=? AND co.id=? AND s.id=? ORDER BY r.revision_number DESC LIMIT 1`,[c.workspaceId,companyId,sourceId]);return rows[0]?revision(rows[0]):null;}
  public async findRevisions(c:WorkspaceContext,companyId:number,ids:readonly string[]):Promise<readonly KnowledgeSourceRevision[]>{if(!ids.length)return[];return(await this.database.query<Row>(`${revisionSelect} WHERE co.workspace_id=? AND co.id=? AND r.id IN (${ids.map(()=>"?").join(",")})`,[c.workspaceId,companyId,...ids])).map(revision);}
  public async createSourceAndPending(c:WorkspaceContext,companyId:number,input:{id:string;revisionId:string;kind:KnowledgeSourceKind;name:string;normalizedName:string;locator:string|null;mediaType:string;inputBytes:number;createdAt:string}):Promise<{source:KnowledgeSource;revision:KnowledgeSourceRevision}>{await this.database.transaction(async database=>{if(!(await database.query<{id:number}>("SELECT id FROM companies WHERE workspace_id=? AND id=?",[c.workspaceId,companyId])).length)throw new KnowledgeDomainError("resource_not_found");const count=await database.query<{count:number}>("SELECT COUNT(*) count FROM knowledge_sources WHERE company_id=?",[companyId]);if(Number(count[0]?.count??0)>=50)throw new KnowledgeDomainError("knowledge_limit_exceeded");await database.execute("INSERT INTO knowledge_sources VALUES(?,?,?,'user',?,?,?,'active',1,?,?,NULL)",[input.id,companyId,input.kind,input.name,input.normalizedName,input.locator,input.createdAt,input.createdAt]);await database.execute("INSERT INTO knowledge_source_revisions(id,source_id,revision_number,status,media_type,extractor_schema_version,input_bytes,created_at) VALUES(?,?,1,'pending',?,'company-business-knowledge-v1',?,?)",[input.revisionId,input.id,input.mediaType,input.inputBytes,input.createdAt]);await database.execute("UPDATE companies SET status='processing' WHERE id=? AND NOT EXISTS(SELECT 1 FROM company_knowledge_publications WHERE company_id=?)",[companyId,companyId]);});const createdSource=await this.findSource(c,companyId,input.id),createdRevision=await this.findRevision(c,companyId,input.id,input.revisionId);if(!createdSource||!createdRevision)throw new Error("Knowledge source could not be read after creation.");return{source:createdSource,revision:createdRevision};}
  public async reserveRevision(c:WorkspaceContext,companyId:number,input:{sourceId:string;revisionId:string;locator:string|null;expectedSourceVersion:number;mediaType:string;inputBytes:number;createdAt:string;abandonedBefore:string}):Promise<KnowledgeSourceRevision>{return this.database.transaction(async database=>{const repository=new AsyncCompanyKnowledgeRepository(database),current=await repository.findSource(c,companyId,input.sourceId);if(!current)throw new KnowledgeDomainError("resource_not_found");if(current.status!=="active")throw new KnowledgeDomainError("source_archived");await database.execute("UPDATE knowledge_source_revisions SET status='failed',failure_code='ingestion_interrupted',completed_at=? WHERE source_id=? AND status='pending' AND created_at<=?",[input.createdAt,input.sourceId,input.abandonedBefore]);const pending=await database.query<{id:string}>("SELECT id FROM knowledge_source_revisions WHERE source_id=? AND status='pending'",[input.sourceId]);if(pending.length)throw new KnowledgeDomainError("knowledge_ingestion_in_progress");const next=await database.query<{number:number}>("SELECT COALESCE(MAX(revision_number),0)+1 number FROM knowledge_source_revisions WHERE source_id=?",[input.sourceId]),changed=await database.execute("UPDATE knowledge_sources SET locator=?,version=version+1,updated_at=? WHERE id=? AND company_id=? AND version=?",[input.locator,input.createdAt,input.sourceId,companyId,input.expectedSourceVersion]);if(Number(changed.rowsAffected)!==1)throw new KnowledgeDomainError("knowledge_source_changed");await database.execute("INSERT INTO knowledge_source_revisions(id,source_id,revision_number,status,media_type,extractor_schema_version,input_bytes,created_at) VALUES(?,?,?,'pending',?,'company-business-knowledge-v1',?,?)",[input.revisionId,input.sourceId,Number(next[0]?.number??1),input.mediaType,input.inputBytes,input.createdAt]);const created=await repository.findRevision(c,companyId,input.sourceId,input.revisionId);if(!created)throw new Error("Knowledge revision could not be read after reservation.");return created;});}
  public async completeRevision(c:WorkspaceContext,companyId:number,id:string,input:{contentDigest:string;normalizedText:string;extracted:ExtractedBusinessKnowledge;normalizedBytes:number;normalizedCharacters:number;pageCount:number|null;completedAt:string}):Promise<boolean>{const owned=await this.database.query<{id:string}>("SELECT r.id FROM knowledge_source_revisions r JOIN knowledge_sources s ON s.id=r.source_id JOIN companies co ON co.id=s.company_id WHERE r.id=? AND co.workspace_id=? AND co.id=?",[id,c.workspaceId,companyId]);if(!owned.length)return false;await this.database.execute("UPDATE knowledge_source_revisions SET status='ready',content_digest=?,normalized_text=?,extracted_knowledge_json=?,normalized_bytes=?,normalized_characters=?,page_count=?,completed_at=? WHERE id=? AND status='pending'",[input.contentDigest,input.normalizedText,JSON.stringify(input.extracted),input.normalizedBytes,input.normalizedCharacters,input.pageCount,input.completedAt,id]);return (await this.database.query<{status:string}>("SELECT status FROM knowledge_source_revisions WHERE id=?",[id]))[0]?.status==="ready";}
  public async failRevision(c:WorkspaceContext,companyId:number,id:string,code:string,at:string):Promise<boolean>{const result=await this.database.execute("UPDATE knowledge_source_revisions SET status='failed',failure_code=?,completed_at=? WHERE id=? AND status='pending' AND source_id IN(SELECT s.id FROM knowledge_sources s JOIN companies co ON co.id=s.company_id WHERE co.workspace_id=? AND co.id=?)",[code,at,id,c.workspaceId,companyId]);if(Number(result.rowsAffected)===1)await this.database.execute("UPDATE companies SET status='failed' WHERE id=? AND NOT EXISTS(SELECT 1 FROM company_knowledge_publications WHERE company_id=?) AND NOT EXISTS(SELECT 1 FROM knowledge_source_revisions r JOIN knowledge_sources s ON s.id=r.source_id WHERE s.company_id=? AND r.status='pending')",[companyId,companyId,companyId]);return Number(result.rowsAffected)===1;}
  public async archiveSource(c:WorkspaceContext,companyId:number,id:string,expected:number,at:string):Promise<KnowledgeSource|null>{const result=await this.database.execute("UPDATE knowledge_sources SET status='archived',version=version+1,updated_at=?,archived_at=? WHERE id=? AND company_id IN(SELECT id FROM companies WHERE workspace_id=? AND id=?) AND version=? AND status='active' AND NOT EXISTS(SELECT 1 FROM knowledge_source_revisions WHERE source_id=? AND status='pending')",[at,at,id,c.workspaceId,companyId,expected,id]);return Number(result.rowsAffected)===1?this.findSource(c,companyId,id):null;}
  public async loadPublished(c:WorkspaceContext,companyId:number):Promise<CompanyKnowledge|null>{const rows=await this.database.query<{knowledge_json:string}>("SELECT v.knowledge_json FROM companies co JOIN company_knowledge_publications p ON p.company_id=co.id JOIN company_knowledge_versions v ON v.id=p.knowledge_version_id AND v.company_id=co.id WHERE co.workspace_id=? AND co.id=?",[c.workspaceId,companyId]);return rows[0]?validateStoredCompanyKnowledgeJson(rows[0].knowledge_json):null;}
  public async loadCurrentVersion(c:WorkspaceContext,companyId:number):Promise<CompanyKnowledgeVersion|null>{const rows=await this.database.query<Row>("SELECT v.*,p.publication_version FROM companies co JOIN company_knowledge_publications p ON p.company_id=co.id JOIN company_knowledge_versions v ON v.id=p.knowledge_version_id WHERE co.workspace_id=? AND co.id=?",[c.workspaceId,companyId]);if(!rows[0])return null;const ids=(await this.database.query<{source_revision_id:string}>("SELECT source_revision_id FROM company_knowledge_version_sources WHERE knowledge_version_id=? ORDER BY ordinal",[String(rows[0].id)])).map(row=>row.source_revision_id);return version(rows[0],ids);}
  public async publish(c:WorkspaceContext,companyId:number,input:{expectedVersionId:string|null;versionId:string;snapshotDigest:string;canonicalJson:string;revisionIds:readonly string[];actorId:string;at:string}):Promise<{status:"created"|"idempotent"|"changed";version?:CompanyKnowledgeVersion}>{return this.database.transaction(async database=>{const repository=new AsyncCompanyKnowledgeRepository(database),visible=await database.query<{id:number}>("SELECT id FROM companies WHERE workspace_id=? AND id=?",[c.workspaceId,companyId]);if(!visible.length)throw new KnowledgeDomainError("resource_not_found");validateStoredCompanyKnowledgeJson(input.canonicalJson);const current=await repository.loadCurrentVersion(c,companyId);if(current?.snapshotDigest===input.snapshotDigest)return{status:"idempotent",version:current};if((current?.id??null)!==input.expectedVersionId)return{status:"changed"};const revisions=await repository.findRevisions(c,companyId,input.revisionIds);if(revisions.length!==input.revisionIds.length||revisions.some(item=>item.status!=="ready"))throw new KnowledgeDomainError("source_revision_not_ready");const count=await database.query<{count:number}>("SELECT COALESCE(MAX(version_number),0)+1 count FROM company_knowledge_versions WHERE company_id=?",[companyId]);await database.execute("INSERT INTO company_knowledge_versions VALUES(?,?,?,'company-knowledge-compiler-v1',?,?,?,?)",[input.versionId,companyId,Number(count[0]?.count??1),input.canonicalJson,input.snapshotDigest,input.actorId,input.at]);for(const [ordinal,id] of input.revisionIds.entries())await database.execute("INSERT INTO company_knowledge_version_sources VALUES(?,?,?)",[input.versionId,id,ordinal+1]);await database.execute("INSERT INTO company_knowledge_publications(company_id,knowledge_version_id,publication_version,published_by_actor_id,published_at) VALUES(?,?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET knowledge_version_id=excluded.knowledge_version_id,publication_version=company_knowledge_publications.publication_version+1,published_by_actor_id=excluded.published_by_actor_id,published_at=excluded.published_at",[companyId,input.versionId,1,input.actorId,input.at]);await database.execute("UPDATE companies SET status='ready' WHERE id=?",[companyId]);const created=await repository.loadCurrentVersion(c,companyId);if(!created)throw new Error("Knowledge publication could not be read after creation.");return{status:"created",version:created};});}
}
