import { createHash } from "node:crypto";
import type { ExternalProviderCredentialResolverPort } from "../application/externalProviderCredentials.js";
import type { ExternalCalendarEventProviderPort, ExternalEventResult } from "../../scheduling/application/externalCalendarPorts.js";
import { validateInstant, validateTimezone } from "../../scheduling/domain/scheduling.js";
import { GoogleCalendarTransportError, type GoogleCalendarEventsHttpTransportPort } from "./googleCalendarTransport.js";
import type { GoogleCalendarAccessTokenProviderPort } from "./googleCalendarFreeBusyProvider.js";

type EventRequest = Parameters<ExternalCalendarEventProviderPort["getEvent"]>[0];
export function googleCalendarEventId(operationId: string): string { if (!/^ewo_[a-f0-9]{32}$/.test(operationId)) throw new Error("Google Calendar event ID is invalid."); return `a${createHash("sha256").update(operationId).digest("hex")}`; }
export function validateGoogleCalendarEventId(value: string): string { if (!/^[a-v0-9]{5,1024}$/.test(value)) throw new Error("Google Calendar event ID is invalid."); return value; }

export class GoogleCalendarEventsProvider implements ExternalCalendarEventProviderPort {
  public constructor(private readonly credentials: ExternalProviderCredentialResolverPort, private readonly tokens: GoogleCalendarAccessTokenProviderPort, private readonly transport: GoogleCalendarEventsHttpTransportPort) {}
  public async getEvent(request: EventRequest): Promise<ExternalEventResult> { const ready = await this.ready(request); if (ready.kind !== "ready") return ready; try { const response = await this.transport.getEvent({ accessToken: ready.token, calendarId: request.binding.externalCalendarId, eventId: ready.eventId, signal: request.signal }); return eventResult(response.status, response.body, ready.eventId); } catch (error: unknown) { return failure(error); } }
  public async insertEvent(request: Parameters<ExternalCalendarEventProviderPort["insertEvent"]>[0]): Promise<ExternalEventResult> { const ready = await this.ready(request); if (ready.kind !== "ready") return ready; let body: string; try { body = JSON.stringify(createBody(ready.eventId, request.operationId, request.startAt, request.endAt, request.timeZone, "atlas_create_operation_id")); } catch { return { kind: "validation_error" }; } try { const response = await this.transport.insertEvent({ accessToken: ready.token, calendarId: request.binding.externalCalendarId, body, signal: request.signal }); return eventResult(response.status, response.body, ready.eventId, request.operationId, "atlas_create_operation_id"); } catch (error: unknown) { return failure(error); } }
  public async patchEvent(request: Parameters<ExternalCalendarEventProviderPort["patchEvent"]>[0]): Promise<ExternalEventResult> { const ready = await this.ready(request); if (ready.kind !== "ready" || !etag(request.expectedRemoteVersion)) return { kind: "validation_error" }; let body: string; try { body = JSON.stringify(createBody(undefined, request.operationId, request.startAt, request.endAt, request.timeZone, "atlas_last_operation_id")); } catch { return { kind: "validation_error" }; } try { const response = await this.transport.patchEvent({ accessToken: ready.token, calendarId: request.binding.externalCalendarId, eventId: ready.eventId, ifMatch: request.expectedRemoteVersion, body, signal: request.signal }); return eventResult(response.status, response.body, ready.eventId, request.operationId, "atlas_last_operation_id"); } catch (error: unknown) { return failure(error); } }
  public async deleteEvent(request: Parameters<ExternalCalendarEventProviderPort["deleteEvent"]>[0]): Promise<{ readonly kind: "success" } | { readonly kind: Exclude<ExternalEventResult, { readonly kind: "success" }>["kind"] }> { const ready = await this.ready(request); if (ready.kind !== "ready" || !etag(request.expectedRemoteVersion)) return { kind: "validation_error" }; try { const response = await this.transport.deleteEvent({ accessToken: ready.token, calendarId: request.binding.externalCalendarId, eventId: ready.eventId, ifMatch: request.expectedRemoteVersion, signal: request.signal }); return status(response.status); } catch (error: unknown) { return failure(error); } }
  private async ready(request: EventRequest): Promise<{ readonly kind: "ready"; readonly token: string; readonly eventId: string } | { readonly kind: Exclude<ExternalEventResult, { readonly kind: "success" }>["kind"] }> { let eventId: string; try { if (request.binding.workspaceId !== request.context.workspaceId || request.binding.companyId !== request.companyId || request.binding.integrationConnectionId !== request.connectionId || !request.binding.externalCalendarId.trim()) throw new Error("invalid"); eventId = validateGoogleCalendarEventId(request.externalEventId); } catch { return { kind: "validation_error" }; } const credentials = await this.credentials.resolve(request.context, request.companyId, request.connectionId); if (credentials.kind === "not_found") return { kind: "validation_error" }; if (credentials.kind !== "resolved") return credentials; if (credentials.provider !== "google_calendar" || credentials.integrationKind !== "calendar") return { kind: "validation_error" }; const token = await this.tokens.acquire(credentials.material, request.signal); return token.kind === "success" ? { kind: "ready", token: token.accessToken, eventId } : token; }
}
function createBody(id: string | undefined, operationId: string, startAt: string, endAt: string, timeZone: string, property: "atlas_create_operation_id" | "atlas_last_operation_id"): Record<string, unknown> { if (!/^ewo_[a-f0-9]{32}$/.test(operationId)) throw new Error("invalid"); const start = instant(startAt), end = instant(endAt), zone = validateTimezone(timeZone); if (end <= start) throw new Error("invalid"); return Object.freeze({ ...(id === undefined ? {} : { id }), summary: "Atlas appointment", start: { dateTime: start, timeZone: zone }, end: { dateTime: end, timeZone: zone }, extendedProperties: { private: { [property]: operationId } } }); }
function eventResult(http: number, body: string, expectedId: string, expectedOperationId?: string, property?: "atlas_create_operation_id" | "atlas_last_operation_id"): ExternalEventResult { const result = status(http); if (result.kind !== "success") return result; try { const parsed = event(body, expectedId); if (expectedOperationId && (property === "atlas_create_operation_id" ? parsed.createOperationId : parsed.lastOperationId) !== expectedOperationId) throw new Error("invalid"); return { kind: "success", event: parsed }; } catch { return { kind: "invalid_response" }; } }
function status(http: number): { readonly kind: "success" } | { readonly kind: Exclude<ExternalEventResult, { readonly kind: "success" }>["kind"] } { if (http >= 200 && http < 300) return { kind: "success" }; if (http === 400) return { kind: "validation_error" }; if (http === 401) return { kind: "unauthorized" }; if (http === 403) return { kind: "forbidden" }; if (http === 404) return { kind: "not_found" }; if (http === 409 || http === 412) return { kind: "conflict" }; if (http === 429) return { kind: "rate_limited" }; if (http === 408 || http === 504) return { kind: "timeout" }; return http >= 500 ? { kind: "unavailable" } : { kind: "invalid_response" }; }
function event(body: string, expectedId: string): { readonly externalEventId: string; readonly remoteVersion: string; readonly remoteState: "active" | "cancelled"; readonly startAt: string; readonly endAt: string; readonly timeZone: string; readonly createOperationId: string | null; readonly lastOperationId: string | null; } { const value: unknown = JSON.parse(body); if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid"); const row = value as Record<string, unknown>; if (row.id !== expectedId || typeof row.etag !== "string" || !etag(row.etag) || (row.status !== "confirmed" && row.status !== "cancelled")) throw new Error("invalid"); const start = dateTime(row.start), end = dateTime(row.end); if (end.instant <= start.instant || start.zone !== end.zone) throw new Error("invalid"); const privateValues = privateProperties(row.extendedProperties); return Object.freeze({ externalEventId: expectedId, remoteVersion: row.etag, remoteState: row.status === "cancelled" ? "cancelled" : "active", startAt: start.instant, endAt: end.instant, timeZone: start.zone, createOperationId: privateValues.atlas_create_operation_id ?? null, lastOperationId: privateValues.atlas_last_operation_id ?? null }); }
function dateTime(value: unknown): { readonly instant: string; readonly zone: string } { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid"); const row = value as Record<string, unknown>; if (typeof row.dateTime !== "string" || typeof row.timeZone !== "string") throw new Error("invalid"); return { instant: instant(row.dateTime), zone: validateTimezone(row.timeZone) }; }
function privateProperties(value: unknown): { readonly atlas_create_operation_id?: string; readonly atlas_last_operation_id?: string } { if (value === undefined) return {}; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid"); const privateValues = (value as Record<string, unknown>).private; if (privateValues === undefined) return {}; if (!privateValues || typeof privateValues !== "object" || Array.isArray(privateValues)) throw new Error("invalid"); const row = privateValues as Record<string, unknown>, output: Record<string, string> = {}; for (const key of ["atlas_create_operation_id", "atlas_last_operation_id"] as const) { const value = row[key]; if (value !== undefined) { if (typeof value !== "string" || !/^ewo_[a-f0-9]{32}$/.test(value)) throw new Error("invalid"); output[key] = value; } } return output; }
function instant(value: string): string { if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value)) throw new Error("invalid"); const parsed = new Date(value); if (Number.isNaN(parsed.valueOf())) throw new Error("invalid"); return validateInstant(parsed.toISOString()); }
function etag(value: string): boolean { return typeof value === "string" && value.length > 0 && value.length <= 200; }
function failure(error: unknown): { readonly kind: Exclude<ExternalEventResult, { readonly kind: "success" }>["kind"] } { if (error instanceof GoogleCalendarTransportError) return { kind: "invalid_response" }; return error instanceof DOMException && (error.name === "AbortError" || error.name === "TimeoutError") || (typeof error === "object" && error !== null && (error as { name?: unknown }).name === "AbortError") ? { kind: "timeout" } : { kind: "unavailable" }; }
