import assert from "node:assert/strict";
import test from "node:test";
import { WorkerPdfTextExtractor } from "../knowledge/infrastructure/pdfTextExtractor.js";
import type { PdfWorkerLifecycleEvidence } from "../knowledge/infrastructure/pdfTextExtractor.js";
import { KnowledgeDomainError } from "../knowledge/domain/knowledge.js";

function pdf(pageTexts:readonly (string|null)[],catalogExtra=""):Uint8Array{
  const objects:string[]=[`<< /Type /Catalog /Pages 2 0 R ${catalogExtra} >>`];
  const pageIds=pageTexts.map((_,index)=>3+index*2),fontId=3+pageTexts.length*2;
  objects.push(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${pageTexts.length} >>`);
  pageTexts.forEach((text,index)=>{const pageId=3+index*2,contentId=pageId+1,chunks=text?.match(/.{1,30}/g)??[],body=text===null?"":`BT /F1 12 Tf 20 100 Td ${chunks.map(chunk=>`(${chunk}) Tj 0 -1 Td`).join(" ")} ET`;objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);objects.push(`<< /Length ${Buffer.byteLength(body)} >>\nstream\n${body}\nendstream`);});
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");let value="%PDF-1.4\n",offsets=[0];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(value));value+=`${index+1} 0 obj\n${object}\nendobj\n`;});const xref=Buffer.byteLength(value);value+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(const offset of offsets.slice(1))value+=`${String(offset).padStart(10,"0")} 00000 n \n`;value+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(value);
}
const rejectsPdf=(bytes:Uint8Array)=>assert.rejects(new WorkerPdfTextExtractor().extract(bytes,new AbortController().signal),KnowledgeDomainError);
function structuredPdf(objects:readonly string[],trailerExtra=""):Uint8Array{let value="%PDF-1.4\n";const offsets:number[]=[];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(value));value+=`${index+1} 0 obj\n${object}\nendobj\n`;});const xref=Buffer.byteLength(value);value+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(const offset of offsets)value+=`${String(offset).padStart(10,"0")} 00000 n \n`;value+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R ${trailerExtra} >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(value);}
function encryptedPdf():Uint8Array{return structuredPdf(["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] /Contents 4 0 R >>","<< /Length 18 >>\nstream\nBT (secret) Tj ET\nendstream",`<< /Filter /Standard /V 1 /R 2 /Length 40 /O <${"00".repeat(32)}> /U <${"11".repeat(32)}> /P -4 >>`],`/Encrypt 5 0 R /ID [<${"22".repeat(16)}><${"22".repeat(16)}>]`);}
function attachmentPdf():Uint8Array{return structuredPdf(["<< /Type /Catalog /Pages 2 0 R /Names << /EmbeddedFiles << /Names [(evidence.txt) 5 0 R] >> >> >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] /Contents 4 0 R >>","<< /Length 17 >>\nstream\nBT (facts) Tj ET\nendstream","<< /Type /Filespec /F (evidence.txt) /EF << /F 6 0 R >> >>","<< /Type /EmbeddedFile /Length 8 >>\nstream\nevidence\nendstream"]);}

test("real PDF worker enforces the 100-page boundary",{timeout:15_000},async()=>{assert.equal((await new WorkerPdfTextExtractor().extract(pdf(Array.from({length:100},(_,i)=>`page ${i}`)),new AbortController().signal)).pageCount,100);await rejectsPdf(pdf(Array.from({length:101},(_,i)=>`page ${i}`)));});
test("real PDF worker enforces normalized-text boundary",{timeout:15_000},async()=>{const boundary=Array.from({length:100},()=>"A".repeat(968));assert.equal((await new WorkerPdfTextExtractor().extract(pdf(boundary),new AbortController().signal)).pageCount,100);const over=[...boundary];over[99]="A".repeat(969);await rejectsPdf(pdf(over));});
test("real PDF worker rejects truncation",async()=>{const valid=pdf(["facts"]);await rejectsPdf(valid.subarray(0,valid.length-30));});
test("real PDF worker rejects malformed xref",async()=>{const valid=pdf(["facts"]);await rejectsPdf(Buffer.from(Buffer.from(valid).toString().replace("startxref\n","startxref\n999999\n%")));});
test("real PDF worker rejects a structurally valid password-protected document",async()=>{await rejectsPdf(encryptedPdf());});
test("real PDF worker rejects empty scanned input",async()=>{await rejectsPdf(pdf([null]));});
test("real PDF worker rejects document JavaScript actions",async()=>{await rejectsPdf(pdf(["facts"],"/OpenAction << /S /JavaScript /JS (app.alert('x')) >>"));});
test("PDF envelope rejects a structurally valid embedded attachment",async()=>{await rejectsPdf(attachmentPdf());});
test("PDF envelope rejects external URI actions before starting the production worker",async()=>{let evidence:PdfWorkerLifecycleEvidence|undefined;await assert.rejects(new WorkerPdfTextExtractor({onLifecycle:value=>{evidence=value;}}).extract(pdf(["safe"],"/OpenAction << /S /URI /URI (https://example.com/secret) >>"),new AbortController().signal),KnowledgeDomainError);assert.equal(evidence,undefined);});
test("the production-default worker reports forced cleanup after timeout",async()=>{let evidence:PdfWorkerLifecycleEvidence|undefined;await assert.rejects(new WorkerPdfTextExtractor({timeoutMilliseconds:1,onLifecycle:value=>{evidence=value;}}).extract(pdf(["safe"]),new AbortController().signal),KnowledgeDomainError);assert.deepEqual(evidence,{pagesLoaded:0,pagesCleaned:0,loadingTaskDestroyed:false,portCloseRequested:false,networkAttempts:0,timerRemoved:true,abortHandlerRemoved:true,listenersRemoved:true,workerExitAwaited:true});});
test("the production-default worker reports forced cleanup after abort",async()=>{let evidence:PdfWorkerLifecycleEvidence|undefined;const controller=new AbortController(),pending=new WorkerPdfTextExtractor({onLifecycle:value=>{evidence=value;}}).extract(pdf(["safe"]),controller.signal);controller.abort();await assert.rejects(pending,KnowledgeDomainError);assert.deepEqual(evidence,{pagesLoaded:0,pagesCleaned:0,loadingTaskDestroyed:false,portCloseRequested:false,networkAttempts:0,timerRemoved:true,abortHandlerRemoved:true,listenersRemoved:true,workerExitAwaited:true});});
