import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { BackupOrchestrationService } from "../operations/backupOrchestration.js";
import { BackupVerificationService } from "../operations/backupVerification.js";
import { RestoreOrchestrationService, restoredMediaInventory, type RestoredDatabaseAccess } from "../operations/restoreOrchestration.js";
import type { BackupObject, BackupObjectPage, BackupObjectStorage } from "../operations/s3BackupObjectStorage.js";
import { LocalSqlDatabase } from "../config/sqlDatabase.js";
import { migrationHead, runMigrations } from "../config/migrations.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";

class Objects implements BackupObjectStorage {
  public readonly values=new Map<string,Uint8Array>();
  public async put(key:string,body:AsyncIterable<Uint8Array>,sizeBytes:number):Promise<void>{const chunks:Uint8Array[]=[];for await(const chunk of body)chunks.push(chunk);const value=Buffer.concat(chunks);if(value.byteLength!==sizeBytes)throw new Error("size");this.values.set(key,value);}
  public async get(key:string,maximumBytes:number):Promise<BackupObject>{const value=this.values.get(key);if(!value||value.byteLength>maximumBytes)throw new Error("missing");return {key,body:(async function*(){yield value;})(),sizeBytes:value.byteLength,contentType:null,checksum:null};}
  public async exists(key:string):Promise<boolean>{return this.values.has(key);}
  public async verify(key:string,expectedBytes:number):Promise<void>{if(this.values.get(key)?.byteLength!==expectedBytes)throw new Error("missing");}
  public async list(_prefix:string,_token:string|null,_limit:number):Promise<BackupObjectPage>{return {keys:[],continuationToken:null};}
  public async delete(key:string):Promise<"deleted"|"locked">{this.values.delete(key);return "deleted";}
}
const at="2026-09-20T00:00:00.000Z", media=Buffer.from([1,2,3,4]), digest=createHash("sha256").update(media).digest("hex"), reference="workspaces/1/companies/1/media/mbl_pass5c/object";
function migratedDatabase():DatabaseSync{const database=new DatabaseSync(":memory:");database.exec("PRAGMA foreign_keys=ON");runMigrations(database);return database;}
function seed(database:DatabaseSync):number{const context=createWorkspaceContext(new WorkspaceRepository(database).resolveDefault()),company=new CompanyRepository(database).create(context,{name:"Pass 5C",website:"https://pass5c.test"});database.prepare("INSERT INTO media_blobs(id,workspace_id,company_id,sha256_digest,size_bytes,media_type,storage_reference,state,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run("mbl_pass5c",context.workspaceId,company.id,digest,media.byteLength,"audio/ogg",reference,"active",at);return company.id;}

test("EPIC054 PASS5C creates a SHA-256 verified backup and restores a migrated media fixture at the canonical head",async()=>{const source=migratedDatabase(),target=migratedDatabase(),storage=new Objects(),destination=new Objects();try{const companyId=seed(source),sourceRows=source.prepare("SELECT COUNT(*) count FROM media_blobs").get() as {count:number};const manifest=await new BackupOrchestrationService({inventory:async()=>[{storageReference:reference,digest,sizeBytes:media.byteLength,contentType:"audio/ogg"}],read:async()=>((async function*(){yield media;})())},storage,()=>new Date(at)).create({writesQuiesced:true,sourceDatabase:"source-db",migrationHead:migrationHead.name,sourceBucket:"live",backupBucket:"backup",applicationBuild:"test",retentionDays:1});assert.equal(manifest.migrationHead,migrationHead.name);assert.deepEqual(await new BackupVerificationService(storage,migrationHead.name).verify(manifest.backupId),{backupId:manifest.backupId,objectCount:1,totalBytes:media.byteLength,state:"complete"});const targetSql=new LocalSqlDatabase(target);const restored:RestoredDatabaseAccess={verify:async head=>{assert.equal(head,migrationHead.name);assert.equal((await targetSql.query<{name:string}>("SELECT name FROM schema_migrations ORDER BY id DESC LIMIT 1"))[0]?.name,migrationHead.name);},mediaInventory:()=>restoredMediaInventory(targetSql),credentialCounts:async()=>({credentialRowsChecked:0,credentialRowsCompatible:0,credentialRowsIncompatible:0})};let recovered=false;const result=await new RestoreOrchestrationService(new BackupVerificationService(storage,migrationHead.name),async()=>manifest,{createPointInTimeRestore:async()=>{seed(target);recovered=true;},verifyDatabaseExists:async()=>{}},{create:async()=>restored},storage,destination).restore({backupId:manifest.backupId,targetDatabase:"restored-db",liveBucket:"live",backupBucket:"backup",restoreBucket:"restore"});assert.equal(recovered,true);assert.equal(result.migrationHead,migrationHead.name);assert.deepEqual(await restoredMediaInventory(targetSql),[{storageReference:reference,sizeBytes:media.byteLength,contentType:"audio/ogg",checksum:digest}]);assert.deepEqual(destination.values.get(reference),media);assert.equal((source.prepare("SELECT COUNT(*) count FROM media_blobs").get() as {count:number}).count,sourceRows.count);assert.equal(companyId,1);}finally{source.close();target.close();}});

test("EPIC054 PASS5C rejects same-size corrupted backup bytes by SHA-256",async()=>{const storage=new Objects(),id=`bkp_${"c".repeat(32)}`,key=`backups/${id}/media/entry_00000000`,entry={stableEntryId:"entry_00000000",originalStorageReference:reference,contentType:"audio/ogg",expectedBytes:media.byteLength,checksum:digest,backupObjectKey:key},inventoryChecksum=createHash("sha256").update(`${entry.stableEntryId}:${entry.originalStorageReference}:${entry.expectedBytes}:${entry.checksum}:${entry.backupObjectKey}`).digest("hex"),manifest={formatVersion:1,backupId:id,createdAt:at,applicationBuild:"test",migrationHead:migrationHead.name,database:{provider:"turso",mode:"pitr",sourceDatabase:"source-db",recoveryPoint:at},media:{sourceBucket:"live",backupBucket:"backup",objectCount:1,totalBytes:media.byteLength,inventoryChecksum,entries:[entry]},retention:{retentionDays:1,retentionUntil:"2026-09-21T00:00:00.000Z"},state:"complete"} as const;await storage.put(key,(async function*(){yield Buffer.from([4,3,2,1]);})(),media.byteLength);const serialized=Buffer.from(JSON.stringify(manifest));await storage.put(`backups/${id}/manifest.json`,(async function*(){yield serialized;})(),serialized.byteLength);await assert.rejects(new BackupVerificationService(storage,migrationHead.name).verify(id),/Backup verification failed/);});
