import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { test } from "node:test";
import express from "express";
import { runMigrations } from "../config/migrations.js";
import { PlatformAdministratorRepository } from "../repositories/platformAdministratorRepository.js";
import { PlatformAdministrationRepository } from "../repositories/platformAdministrationRepository.js";
import { PlatformAuthorizationService } from "../platformAdmin/services/platformAuthorizationService.js";
import { PlatformAdministrationService } from "../platformAdmin/services/platformAdministrationService.js";
import { createPlatformAdminControllers } from "../controllers/platformAdminController.js";
import { createPlatformAdminRouter } from "../routes/platformAdmin.js";

function database(claimant: string | null = null): DatabaseSync { const value = new DatabaseSync(":memory:"); value.exec("PRAGMA foreign_keys=ON"); runMigrations(value, 35); if (claimant) { value.prepare("INSERT INTO users(id,status,locale,created_at,updated_at) VALUES(?,'active','en','2026-01-01','2026-01-01')").run(claimant); value.prepare("UPDATE platform_bootstrap SET claimed_by_user_id=?,claimed_at='2026-01-01' WHERE singleton=1").run(claimant); } runMigrations(value); return value; }
function app(value: DatabaseSync, userId: string | null) { const admins = new PlatformAdministratorRepository(value), service = new PlatformAdministrationService(new PlatformAdministrationRepository(value)); const application = express(); application.use("/admin", createPlatformAdminRouter({ cookieName: () => "session", current: () => userId ? { userId } : null } as never, new PlatformAuthorizationService(admins), createPlatformAdminControllers(service))); return application; }
async function get(application: express.Express, path: string): Promise<Response> { const listener = application.listen(0, "127.0.0.1"); await new Promise<void>((resolve) => listener.once("listening", resolve)); try { const address = listener.address(); if (!address || typeof address === "string") throw new Error(); return await fetch(`http://127.0.0.1:${address.port}${path}`, { headers: { cookie: "session=value" } }); } finally { listener.close(); } }

test("EPIC-031 migrates the bootstrap claimant to one active platform administrator without altering tenant data", () => { const value = database("usr_bootstrap"); value.prepare("INSERT INTO workspaces(key,name,created_at) VALUES('demo','INMOBILIARIA DEMO','2026-01-02')").run(); const grant = (value.prepare("SELECT user_id,status,granted_at,granted_by_user_id,revoked_at FROM platform_administrators").all() as Array<Record<string, unknown>>).map((row) => ({ ...row })); assert.deepEqual(grant, [{ user_id: "usr_bootstrap", status: "active", granted_at: "2026-01-01", granted_by_user_id: null, revoked_at: null }]); runMigrations(value); assert.equal((value.prepare("SELECT COUNT(*) count FROM platform_administrators").get() as { count: number }).count, 1); assert.equal((value.prepare("SELECT name FROM workspaces WHERE key='demo'").get() as { name: string }).name, "INMOBILIARIA DEMO"); value.close(); });

test("EPIC-031 admin APIs require a live dedicated platform grant, never a workspace role", async () => { const value = database("usr_admin"); for (const id of ["usr_owner", "usr_administrator", "usr_operator", "usr_viewer", "usr_normal"]) value.prepare("INSERT INTO users(id,status,locale,created_at,updated_at) VALUES(?,'active','en','2026-01-01','2026-01-01')").run(id); const workspaceId = (value.prepare("SELECT id FROM workspaces WHERE key='default'").get() as { id: number }).id; for (const [id, role] of [["usr_owner", "owner"], ["usr_administrator", "administrator"], ["usr_operator", "operator"], ["usr_viewer", "viewer"]] as const) value.prepare("INSERT INTO memberships(id,workspace_id,user_id,role,status,version,created_at,activated_at) VALUES(?,?,?,?,'active',1,'2026-01-01','2026-01-01')").run(`mem_${role}`, workspaceId, id, role); for (const id of ["usr_admin", "usr_owner", "usr_administrator", "usr_operator", "usr_viewer"]) { const response = await get(app(value, id), "/admin/overview"); assert.equal(response.status, id === "usr_admin" ? 200 : 404); } assert.equal((await get(app(value, "usr_normal"), "/admin/workspaces")).status, 404); assert.equal((await get(app(value, null), "/admin/overview")).status, 404); value.prepare("UPDATE platform_administrators SET status='revoked',revoked_at='2026-01-02' WHERE user_id='usr_admin'").run(); assert.equal((await get(app(value, "usr_admin"), "/admin/overview")).status, 404); value.close(); });

test("EPIC-031 workspace projections are paginated, complete, and contain only safe aggregates", () => { const value = database("usr_admin"); value.prepare("INSERT INTO workspaces(key,name,created_at,public_id) VALUES('first','First','2026-01-02','wsp_first'),('second','Second','2026-01-01','wsp_second')").run(); const service = new PlatformAdministrationService(new PlatformAdministrationRepository(value)); const first = service.workspaces(undefined, "1"); assert.equal(first.workspaces.length, 1); assert.ok(first.nextCursor); const second = service.workspaces(first.nextCursor, "1"), third = service.workspaces(second.nextCursor, "1"); assert.equal(second.workspaces.length, 1); assert.equal(third.workspaces.length, 1); const ids = [...first.workspaces, ...second.workspaces, ...third.workspaces].map((workspace) => workspace.id); assert.equal(new Set(ids).size, 3); assert.ok(ids.includes("wsp_first")); assert.ok(ids.includes("wsp_second")); assert.throws(() => service.workspaces(undefined, "101")); assert.deepEqual(Object.keys(first.workspaces[0]!).sort(), ["assistantProfileCount", "companyCount", "createdAt", "id", "latestActivityAt", "memberCount", "name", "webChatConnectionCount", "whatsApp"]); value.close(); });

test("EPIC-031 users are safely paginated and require a live platform grant", async () => { const value=database("usr_admin"); value.prepare("INSERT INTO users(id,status,locale,created_at,updated_at) VALUES('usr_one','active','en','2026-01-02','2026-01-02'),('usr_two','active','en','2026-01-01','2026-01-01')").run(); value.prepare("INSERT INTO authentication_identities(id,user_id,email,normalized_email,email_verified,created_at,updated_at) VALUES('id_one','usr_one','one@example.test','one@example.test',1,'2026-01-02','2026-01-02'),('id_two','usr_two','two@example.test','two@example.test',0,'2026-01-01','2026-01-01')").run(); const workspaceId=(value.prepare("SELECT id FROM workspaces WHERE key='default'").get() as {id:number}).id; value.prepare("INSERT INTO memberships(id,workspace_id,user_id,role,status,version,created_at,activated_at) VALUES('mem_one',?,'usr_one','viewer','active',1,'2026-01-02','2026-01-02')").run(workspaceId); const service=new PlatformAdministrationService(new PlatformAdministrationRepository(value)),first=service.users(undefined,"1"),second=service.users(first.nextCursor,"1"); assert.equal(first.users.length,1); assert.equal(second.users.length,1); assert.notEqual(first.users[0]!.id,second.users[0]!.id); assert.deepEqual(Object.keys(first.users[0]!).sort(),["activeWorkspaceMembershipCount","createdAt","email","emailVerified","hasActiveWorkspaceMembership","id"]); assert.throws(()=>service.users(undefined,"101")); const response=await get(app(value,"usr_admin"),"/admin/users?limit=1"); assert.equal(response.status,200); assert.equal((await get(app(value,"usr_one"),"/admin/users")).status,404); assert.equal((await get(app(value,null),"/admin/users")).status,404); value.prepare("UPDATE platform_administrators SET status='revoked',revoked_at='2026-01-03' WHERE user_id='usr_admin'").run(); assert.equal((await get(app(value,"usr_admin"),"/admin/users")).status,404); value.close(); });
