import assert from "node:assert/strict";
import test from "node:test";
import { BillingReconciliationRuntime } from "../billing/services/billingReconciliationRuntime.js";
import { WhatsAppRecoveryRuntime } from "../whatsapp/services/WhatsAppRecoveryRuntime.js";

const flush=():Promise<void>=>new Promise(resolve=>setImmediate(resolve));

test("EPIC056 billing production scheduler uses one-shot timeouts and fences stale callbacks across restart",async()=>{const scheduled:Array<{callback:()=>void;cleared:boolean;unref():void}>=[],originalSetTimeout=global.setTimeout,originalClearTimeout=global.clearTimeout;let calls=0;global.setTimeout=((callback:()=>void)=>{const timer={callback,cleared:false,unref(){}};scheduled.push(timer);return timer as never;}) as typeof setTimeout;global.clearTimeout=((timer:{cleared:boolean})=>{timer.cleared=true;}) as typeof clearTimeout;try{const runtime=new BillingReconciliationRuntime({async runBatch(){calls+=1;return[];}} as never,{intervalMilliseconds:5_000,batchSize:1});runtime.start();await flush();assert.equal(scheduled.length,1);const stale=scheduled[0]!;await runtime.stop();assert.equal(stale.cleared,true);runtime.start();await flush();stale.callback();await flush();assert.equal(calls,2);await runtime.stop();}finally{global.setTimeout=originalSetTimeout;global.clearTimeout=originalClearTimeout;}});

test("EPIC056 WhatsApp scheduler immediately runs, backs off idle work, and resets after work or errors",async()=>{const scheduled:Array<{callback:()=>void;unref():void}>=[],delays:number[]=[];let calls=0;const runtime=new WhatsAppRecoveryRuntime(async()=>{calls+=1;if(calls===6)return 1;},{schedule:(callback,milliseconds)=>{delays.push(milliseconds);const timer={callback,unref(){}};scheduled.push(timer);return timer;},clear:()=>{}});runtime.start();await flush();for(let index=0;index<5;index+=1){scheduled[index]!.callback();await flush();}assert.deepEqual(delays,[5_000,10_000,15_000,20_000,20_000,5_000]);await runtime.stop();const errors:Array<{callback:()=>void;unref():void}>=[],errorDelays:number[]=[];let errorCalls=0;const failing=new WhatsAppRecoveryRuntime(async()=>{errorCalls+=1;if(errorCalls===5)throw new Error("expected");},{schedule:(callback,milliseconds)=>{errorDelays.push(milliseconds);const timer={callback,unref(){}};errors.push(timer);return timer;},clear:()=>{}});failing.start();await flush();for(let index=0;index<4;index+=1){errors[index]!.callback();await flush();}assert.deepEqual(errorDelays,[5_000,10_000,15_000,20_000,5_000]);await failing.stop();});

test("EPIC056 WhatsApp scheduler prevents overlap and fences stale callbacks after restart",async()=>{const scheduled:Array<{callback:()=>void;cleared:boolean;unref():void}>=[];let calls=0,release:(()=>void)|undefined;const blocked=new Promise<void>(resolve=>{release=resolve;});const runtime=new WhatsAppRecoveryRuntime(async()=>{calls+=1;if(calls===1)await blocked;},{schedule:callback=>{const timer={callback,cleared:false,unref(){}};scheduled.push(timer);return timer;},clear:timer=>{timer.cleared=true;}});runtime.start();scheduled[0]?.callback();assert.equal(calls,1);release?.();await flush();const stale=scheduled[0]!;await runtime.stop();assert.equal(stale.cleared,true);runtime.start();await flush();stale.callback();await flush();assert.equal(calls,2);await runtime.stop();});
