import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { AssistantToolOrchestrator } from "../assistant/services/assistantToolOrchestrator.js";
import { ToolExecutionError, ToolExecutionService } from "../assistant/services/toolExecutionService.js";
import type { ToolExecutionTraceRepositoryPort } from "../assistant/application/toolContracts.js";
import { ToolRegistry } from "../assistant/application/toolRegistry.js";
import { productionAssistantCapabilityCatalog } from "../assistant/domain/assistantCapability.js";
import { createDatabase } from "../config/database.js";
import { LocalSqlDatabase } from "../config/sqlDatabase.js";
import { BookingRepository } from "../repositories/bookingRepository.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { SchedulingRepository } from "../repositories/schedulingRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { schedulingBookingToolDefinitions } from "../scheduling/application/bookingToolDefinitions.js";
import { BookingCommandService } from "../scheduling/services/bookingCommandService.js";
import { BookingQueryService } from "../scheduling/services/bookingQueryService.js";
import { SchedulingService } from "../scheduling/services/schedulingService.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";

class Clock { public value = "2026-08-18T12:00:00.000Z"; public now(): string { return this.value; } }
async function setup() { const database = createDatabase(":memory:"), context = createWorkspaceContext(new WorkspaceRepository(database).resolveDefault()), company = new CompanyRepository(database).create(context, { name: "Bookings", website: "https://bookings.test" }), clock = new Clock(), scheduling = new SchedulingService(new SchedulingRepository(new LocalSqlDatabase(database)), clock), repository = new BookingRepository(new LocalSqlDatabase(database)), commands = new BookingCommandService(repository, clock); const resource = await scheduling.createResource(context, company.id, { name: "Room", timezone: "UTC" }); const service = await scheduling.createService(context, company.id, { resourceId: resource.id, name: "Viewing", durationMinutes: 30 }); await scheduling.addWorkingWindow(context, company.id, { resourceId: resource.id, weekday: 2, startTime: "13:00", endTime: "15:00" }); const slots = await scheduling.listSlots(context, company.id, service.id, { fromLocalDate: "2026-08-18", days: 1 }); return { database, context, company, clock, scheduling, commands, queries: new BookingQueryService(repository), slots }; }
test("EPIC037 preserves historical mutations while scoping idempotency to operation", () => { const database = createDatabase(":memory:"); try { assert.equal((database.prepare("SELECT name FROM schema_migrations WHERE id=46").get() as { name: string }).name, "0046_scheduling_booking_mutations_audit_lineage"); assert.equal((database.prepare("SELECT name FROM schema_migrations WHERE id=47").get() as { name: string }).name, "0047_scheduling_booking_mutation_operation_scope"); assert.ok((database.prepare("PRAGMA table_info(scheduling_bookings)").all() as Array<{ name: string }>).some(column => column.name === "rescheduled_from_booking_id")); assert.match((database.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='scheduling_booking_mutations'").get() as { sql: string }).sql, /UNIQUE\(workspace_id,company_id,operation,idempotency_key\)/); assert.match((database.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='scheduling_booking_mutations'").get() as { sql: string }).sql, /outcome TEXT NOT NULL/); assert.match((database.prepare("SELECT sql FROM sqlite_master WHERE type='trigger' AND name='scheduling_booking_audit_events_no_update'").get() as { sql: string }).sql, /append-only/); } finally { database.close(); } });

test("EPIC037 authoritatively creates, retries, rejects stale and divergent commands, and reschedules atomically", async () => { const value = await setup(); try { const serviceId = (value.database.prepare("SELECT id FROM scheduling_services").get() as { id: string }).id, firstSlot = value.slots[0]!, nextSlot = value.slots[1]!; const first = await value.commands.create(value.context, value.company.id, { serviceId, startAt: firstSlot.startAt, reference: "BK-1", idempotencyKey: "create-1" }); assert.equal((await value.commands.create(value.context, value.company.id, { serviceId, startAt: firstSlot.startAt, reference: "BK-1", idempotencyKey: "create-1" })).id, first.id); await assert.rejects(value.commands.create(value.context, value.company.id, { serviceId, startAt: nextSlot.startAt, reference: "changed", idempotencyKey: "create-1" })); await assert.rejects(value.commands.create(value.context, value.company.id, { serviceId, startAt: firstSlot.startAt, reference: "stale", idempotencyKey: "stale-1" })); const moved = await value.commands.reschedule(value.context, value.company.id, { bookingId: first.id, newStartAt: firstSlot.startAt, reference: "BK-2", idempotencyKey: "move-1" }); assert.equal(moved.rescheduledFromBookingId, first.id); assert.equal((await value.queries.get(value.context, value.company.id, first.id)).state, "cancelled"); assert.equal((await value.commands.cancel(value.context, value.company.id, { bookingId: moved.id, idempotencyKey: "cancel-1" })).state, "cancelled"); assert.equal((value.database.prepare("SELECT COUNT(*) AS count FROM scheduling_booking_audit_events").get() as { count: number }).count, 3); } finally { value.database.close(); } });

test("EPIC037 permits key reuse across operations, rejects divergent same-operation commands, and records already-cancelled replays", async () => { const value = await setup(); try { const serviceId = (value.database.prepare("SELECT id FROM scheduling_services").get() as { id: string }).id, firstSlot = value.slots[0]!, nextSlot = value.slots[1]!; const created = await value.commands.create(value.context, value.company.id, { serviceId, startAt: firstSlot.startAt, reference: "KEY-1", idempotencyKey: "shared" }); await assert.rejects(() => value.commands.create(value.context, value.company.id, { serviceId, startAt: nextSlot.startAt, reference: "KEY-2", idempotencyKey: "shared" })); const cancelled = await value.commands.cancel(value.context, value.company.id, { bookingId: created.id, idempotencyKey: "shared" }); assert.equal(cancelled.state, "cancelled"); const already = await value.commands.cancelWithOutcome(value.context, value.company.id, { bookingId: created.id, idempotencyKey: "cancel-new" }); assert.equal(already.status, "already_cancelled"); assert.equal((await value.commands.cancelWithOutcome(value.context, value.company.id, { bookingId: created.id, idempotencyKey: "cancel-new" })).status, "already_cancelled"); assert.equal((value.database.prepare("SELECT COUNT(*) AS count FROM scheduling_booking_mutations WHERE booking_id=? AND operation='cancel'").get(created.id) as { count: number }).count, 2); assert.equal((value.database.prepare("SELECT COUNT(*) AS count FROM scheduling_booking_audit_events WHERE booking_id=?").get(created.id) as { count: number }).count, 2); } finally { value.database.close(); } });

test("EPIC037 scopes commands by tenant and commits at most one racing slot request", async () => { const value = await setup(); try { const serviceId = (value.database.prepare("SELECT id FROM scheduling_services").get() as { id: string }).id, slot = value.slots[0]!; const attempts = await Promise.allSettled([value.commands.create(value.context, value.company.id, { serviceId, startAt: slot.startAt, reference: "race-a", idempotencyKey: "race-a" }), value.commands.create(value.context, value.company.id, { serviceId, startAt: slot.startAt, reference: "race-b", idempotencyKey: "race-b" })]); assert.equal(attempts.filter(attempt => attempt.status === "fulfilled").length, 1); const created = attempts.find((attempt): attempt is PromiseFulfilledResult<import("../scheduling/domain/scheduling.js").SchedulingBooking> => attempt.status === "fulfilled")!.value; const other = new CompanyRepository(value.database).create(value.context, { name: "Other", website: "https://other.test" }); await assert.rejects(value.commands.reschedule(value.context, other.id, { bookingId: created.id, newStartAt: slot.startAt, reference: "cross", idempotencyKey: "cross-1" })); assert.equal((value.database.prepare("SELECT COUNT(*) AS count FROM scheduling_bookings WHERE company_id=?").get(other.id) as { count: number }).count, 0); } finally { value.database.close(); } });

test("EPIC037 exposes direct, code-owned, confirmed, idempotent tools with safe failures", async () => { const value = await setup(); try { const definitions = schedulingBookingToolDefinitions(value.commands, value.queries); const registry = new ToolRegistry(productionAssistantCapabilityCatalog, definitions), createSchema = registry.get("scheduling.create_booking")!.inputSchema as { readonly required?: readonly string[] }, rescheduleSchema = registry.get("scheduling.reschedule_booking")!.inputSchema as { readonly required?: readonly string[] }; assert.deepEqual(registry.list().map(tool => tool.name), ["scheduling.create_booking", "scheduling.reschedule_booking", "scheduling.cancel_booking", "scheduling.get_booking"]); assert.deepEqual(createSchema.required, ["serviceId", "startAt", "reference"]); assert.deepEqual(rescheduleSchema.required, ["bookingId", "newStartAt", "reference"]); assert.equal(registry.get("scheduling.create_booking")?.confirmationPolicy, "user"); const result = await registry.get("scheduling.get_booking")!.executor({ workspaceId: value.context.workspaceId, companyId: value.company.id, assistantProfileId: "asp_test", assistantExecutionRecordId: "aex_test", conversationId: null, channel: "internal", invocationId: "call", idempotencyKey: null, confirmation: null }, { bookingId: "sbk_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, new AbortController().signal) as { status: string }; assert.equal(result.status, "not_found"); } finally { value.database.close(); } });

test("EPIC037 real booking tools are not executed without capability or after availability changes", async () => { let calls = 0, availabilityReads = 0; const commands = { create: async () => { calls += 1; throw new Error("must not execute"); } } as unknown as BookingCommandService, definitions = schedulingBookingToolDefinitions(commands, {} as BookingQueryService), registry = new ToolRegistry(productionAssistantCapabilityCatalog, definitions), capability = productionAssistantCapabilityCatalog.require("scheduling.create_booking"), model = { createSession: () => ({ start: async () => ({ kind: "tool_calls" as const, toolCalls: [{ id: "call", toolName: "scheduling.create_booking", input: { serviceId: "svc", startAt: "2026-08-18T13:00:00.000Z", reference: "BK" } }] }), continue: async () => ({ kind: "final" as const, text: "done" }) }) }, traces: ToolExecutionTraceRepositoryPort = { createRequested: async trace => ({ ...trace, state: "requested" }), complete: async () => true, fail: async () => true }, context = { workspaceId: 1, companyId: 1, assistantProfileId: "asp_test", assistantExecutionRecordId: "aex_test", conversationId: null, channel: "internal" as const, invocationId: "", idempotencyKey: "key", confirmation: { kind: "user" as const, confirmationId: "confirm" } }; const unavailable = new AssistantToolOrchestrator(model, registry, { listForProfile: async () => [], existsForProfile: async () => true, replaceForProfile: async () => true }, { isAvailable: async () => true }, new ToolExecutionService(traces, new Clock()), new Clock()); await assert.rejects(() => unavailable.run("prompt", context), ToolExecutionError); assert.equal(calls, 0); const changing = new AssistantToolOrchestrator(model, registry, { listForProfile: async () => [capability], existsForProfile: async () => true, replaceForProfile: async () => true }, { isAvailable: async () => ++availabilityReads === 1 }, new ToolExecutionService(traces, new Clock()), new Clock()); await assert.rejects(() => changing.run("prompt", context), ToolExecutionError); assert.ok(availabilityReads >= 2); assert.equal(calls, 0); });

test("EPIC037 commits one of two separate-connection reschedules without partial lineage", async () => { const directory = mkdtempSync(join(tmpdir(), "atlas-booking-")), path = join(directory, "atlas.sqlite"), first = createDatabase(path), second = createDatabase(path); try { const context = createWorkspaceContext(new WorkspaceRepository(first).resolveDefault()), company = new CompanyRepository(first).create(context, { name: "Concurrent", website: "https://concurrent.test" }), clock = new Clock(), scheduling = new SchedulingService(new SchedulingRepository(new LocalSqlDatabase(first)), clock), firstCommands = new BookingCommandService(new BookingRepository(new LocalSqlDatabase(first)), clock), secondCommands = new BookingCommandService(new BookingRepository(new LocalSqlDatabase(second)), clock), resource = await scheduling.createResource(context, company.id, { name: "Room", timezone: "UTC" }), service = await scheduling.createService(context, company.id, { resourceId: resource.id, name: "Viewing", durationMinutes: 30 }), _window = await scheduling.addWorkingWindow(context, company.id, { resourceId: resource.id, weekday: 2, startTime: "13:00", endTime: "15:00" }), slots = await scheduling.listSlots(context, company.id, service.id, { fromLocalDate: "2026-08-18", days: 1 }), source = await firstCommands.create(context, company.id, { serviceId: service.id, startAt: slots[0]!.startAt, reference: "SOURCE", idempotencyKey: "source" }), attempts = await Promise.allSettled([firstCommands.reschedule(context, company.id, { bookingId: source.id, newStartAt: slots[1]!.startAt, reference: "TARGET-A", idempotencyKey: "target-a" }), secondCommands.reschedule(context, company.id, { bookingId: source.id, newStartAt: slots[2]!.startAt, reference: "TARGET-B", idempotencyKey: "target-b" })]); assert.equal(attempts.filter(attempt => attempt.status === "fulfilled").length, 1); const replacement = attempts.find((attempt): attempt is PromiseFulfilledResult<import("../scheduling/domain/scheduling.js").SchedulingBooking> => attempt.status === "fulfilled")!.value; assert.equal((first.prepare("SELECT state FROM scheduling_bookings WHERE id=?").get(source.id) as { state: string }).state, "cancelled"); assert.equal((first.prepare("SELECT COUNT(*) AS count FROM scheduling_bookings WHERE rescheduled_from_booking_id=? AND state='confirmed'").get(source.id) as { count: number }).count, 1); assert.equal(replacement.rescheduledFromBookingId, source.id); assert.equal((first.prepare("SELECT COUNT(*) AS count FROM scheduling_bookings WHERE state='confirmed'").get() as { count: number }).count, 1); } finally { first.close(); second.close(); rmSync(directory, { recursive: true, force: true }); } });
