import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import type { AddressInfo } from "node:net";
import test from "node:test";
import express from "express";
import type { AssistantExecutionPort } from "../assistant/application/assistantExecutionPort.js";
import type { AssistantExecutionRequest, AssistantExecutionResult } from "../assistant/application/assistantExecution.js";
import { assistantProfileId, reconstructAssistantProfile, type AssistantProfile } from "../assistant/domain/assistantProfile.js";
import { assistantExecutionRecordId } from "../assistant/domain/operationalAssistantRuntime.js";
import { InMemoryConversationTurnLock, OperationalConversationTurnService } from "../assistant/services/operationalConversationTurnService.js";
import { OperationalAssistantRuntime } from "../assistant/services/operationalAssistantRuntime.js";
import { createApp } from "../app.js";
import { createDatabase } from "../config/database.js";
import { ConversationService } from "../conversation/services/conversationService.js";
import { AssistantExecutionRecordRepository } from "../repositories/assistantExecutionRecordRepository.js";
import { AssistantProfileRepository } from "../repositories/assistantProfileRepository.js";
import { CompanyKnowledgeRepository } from "../repositories/companyKnowledgeRepository.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { ConversationRepository } from "../repositories/conversationRepository.js";
import { WebChatConnectionRepository } from "../repositories/webChatConnectionRepository.js";
import { WebChatSessionRepository } from "../repositories/webChatSessionRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { createPublicWebChatRouter } from "../routes/publicWebChat.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";
import { PublicWebChatConversationInProgressError, PublicWebChatConversationRuntimeError, PublicWebChatConversationService, PublicWebChatConversationValidationError } from "../webChat/services/publicWebChatConversationService.js";
import { PublicWebChatSessionService } from "../webChat/services/publicWebChatSessionService.js";
import { WebChatConnectionService } from "../webChat/services/webChatConnectionService.js";
import { publishKnowledgeFixture } from "./knowledgeTestFixture.js";

class Clock { private index = 0; public now(): string { return new Date(Date.UTC(2026, 6, 26, 12, 0, this.index++)).toISOString(); } }
class Execution implements AssistantExecutionPort { public calls = 0; public request: AssistantExecutionRequest | null = null; public result: AssistantExecutionResult = { outcome: "answered", answer: "Grounded answer" }; public error: Error | null = null; public wait: Promise<void> | null = null; public async execute(request: AssistantExecutionRequest): Promise<AssistantExecutionResult> { this.calls++; this.request = request; if (this.wait) await this.wait; if (this.error) throw this.error; return this.result; } }
function ready(companyId: number): AssistantProfile { return reconstructAssistantProfile({ id: assistantProfileId("asp_0123456789abcdef0123456789abcdef"), companyId, name: "Web", normalizedName: "web", description: null, businessRole: "Advisor", objective: "Help", audience: null, tone: "friendly", assistantLanguage: "en", welcomeMessage: "Welcome", fallbackMessage: "Approved fallback", status: "ready", createdAt: "2026-07-26T12:00:00.000Z", updatedAt: "2026-07-26T12:00:00.000Z", archivedAt: null }); }
function setup() { const database = createDatabase(":memory:"), clock = new Clock(), workspaces = new WorkspaceRepository(database), context = createWorkspaceContext(workspaces.resolveDefault()), companies = new CompanyRepository(database), company = companies.create(context, { name: "Web", website: "https://web.test", status: "ready" }); publishKnowledgeFixture(database, context, company.id, { company: { name: company.name, website: company.website, phone: "", email: "" }, business: { services: ["Sales"], hours: "Always", locations: [] }, faq: [] }); const profiles = new AssistantProfileRepository(database), profile = ready(company.id); profiles.create(context, company.id, profile); const connections = new WebChatConnectionService(companies, profiles, new WebChatConnectionRepository(database), clock), connection = connections.create(context, company.id, { assistantProfileId: profile.id }), conversationService = new ConversationService(new ConversationRepository(database), clock), sessionService = new PublicWebChatSessionService(connections, conversationService, new WebChatSessionRepository(database), clock), execution = new Execution(), records = new AssistantExecutionRecordRepository(database), turns = new OperationalConversationTurnService(companies, new CompanyKnowledgeRepository(database), profiles, conversationService, new OperationalAssistantRuntime(execution, records, clock), new InMemoryConversationTurnLock(), "test", 2), service = new PublicWebChatConversationService(sessionService, turns, conversationService); return { database, context, company, connection, connections, conversationService, execution, records, sessionService, service }; }

test("EPIC-016.6 resolves IDs from the Session, persists a linked turn, and returns only outbound content", async () => { const value = setup(); try { const started = value.sessionService.start(value.connection.publicId, null), result = await value.service.sendMessage(value.connection.publicId, started.rawToken, "  Hello  "), session = value.sessionService.resolveSession(started.rawToken)!; assert.deepEqual(result, { message: "Grounded answer" }); assert.equal(value.execution.calls, 1); assert.deepEqual(value.execution.request?.history?.map((entry) => entry.content), ["Hello"]); const messages = value.conversationService.listMessages(value.context, value.company.id, session.conversationId); assert.deepEqual(messages.map((message) => [message.direction, message.content]), [["inbound", "Hello"], ["outbound", "Grounded answer"]]); const executionRecord = messages[1]?.executionRecordId; assert.ok(executionRecord); assert.equal(value.records.findById(assistantExecutionRecordId(executionRecord))?.state, "answered"); } finally { value.database.close(); } });
test("EPIC-016.6 validates input, persists fallback, maps runtime errors, and serializes turns", async () => { const value = setup(); try { const started = value.sessionService.start(value.connection.publicId, null); for (const input of ["", " ", 1, "x".repeat(4_001)]) await assert.rejects(() => value.service.sendMessage(value.connection.publicId, started.rawToken, input), PublicWebChatConversationValidationError); value.execution.result = { outcome: "safe_fallback", answer: "ignored" }; assert.deepEqual(await value.service.sendMessage(value.connection.publicId, started.rawToken, "Fallback"), { message: "Approved fallback" }); value.execution.error = new Error("provider failure"); await assert.rejects(() => value.service.sendMessage(value.connection.publicId, started.rawToken, "Failure"), PublicWebChatConversationRuntimeError); value.execution.error = null; let release!: () => void; value.execution.wait = new Promise<void>((resolve) => { release = resolve; }); const first = value.service.sendMessage(value.connection.publicId, started.rawToken, "First"); await new Promise((resolve) => setImmediate(resolve)); await assert.rejects(() => value.service.sendMessage(value.connection.publicId, started.rawToken, "Second"), PublicWebChatConversationInProgressError); release(); await first; } finally { value.database.close(); } });
test("EPIC-016.6 exposes only the same-origin public message DTO", async () => { const value = setup(), empty = express.Router(), app = createApp({ authorizedCompaniesRouter: empty, chatRouter: empty, companiesRouter: empty, identityRouter: empty, knowledgeRouter: empty, publicWebChatRouter: createPublicWebChatRouter(value.sessionService, value.service, false), scrapeRouter: empty, workspacesRouter: empty }), listener = app.listen(0, "127.0.0.1"); await new Promise<void>((resolve) => listener.once("listening", resolve)); const origin = `http://127.0.0.1:${(listener.address() as AddressInfo).port}`; try { const started = value.sessionService.start(value.connection.publicId, null), path = `${origin}/public/web-chat/${value.connection.publicId}/messages`, headers = { cookie: `atlas_web_chat_session=${encodeURIComponent(started.rawToken)}`, origin, "content-type": "application/json" }; const success = await fetch(path, { method: "POST", headers, body: JSON.stringify({ message: "Hello" }) }); assert.equal(success.status, 200); assert.deepEqual(await success.json(), { message: "Grounded answer" }); assert.equal(success.headers.get("access-control-allow-origin"), null); for (const body of [{ content: "Hello" }, { message: "Hello", companyId: 1 }, { message: " " }]) assert.equal((await fetch(path, { method: "POST", headers, body: JSON.stringify(body) })).status, 400); assert.equal((await fetch(path, { method: "POST", headers: { origin, "content-type": "application/json" }, body: JSON.stringify({ message: "Hello" }) })).status, 404); assert.equal((await fetch(path, { method: "POST", headers: { ...headers, origin: "https://invalid.test" }, body: JSON.stringify({ message: "Hello" }) })).status, 404); assert.equal((await fetch(path, { method: "POST", headers: { ...headers, "content-type": "text/plain" }, body: "Hello" })).status, 415); assert.equal((await fetch(path, { method: "POST", headers, body: JSON.stringify({ message: "x".repeat(8_192) }) })).status, 413); } finally { await new Promise<void>((resolve) => listener.close(() => resolve())); value.database.close(); } });
test("EPIC-016.8 returns only chronological public history for the bound active session", async () => { const value = setup(), empty = express.Router(), app = createApp({ authorizedCompaniesRouter: empty, chatRouter: empty, companiesRouter: empty, identityRouter: empty, knowledgeRouter: empty, publicWebChatRouter: createPublicWebChatRouter(value.sessionService, value.service, false), scrapeRouter: empty, workspacesRouter: empty }), listener = app.listen(0, "127.0.0.1"); await new Promise<void>((resolve) => listener.once("listening", resolve)); const origin = `http://127.0.0.1:${(listener.address() as AddressInfo).port}`; try { const started = value.sessionService.start(value.connection.publicId, null), path = `${origin}/public/web-chat/${value.connection.publicId}/messages`, cookie = `atlas_web_chat_session=${encodeURIComponent(started.rawToken)}`; assert.deepEqual(await (await fetch(path, { headers: { cookie } })).json(), { messages: [] }); await value.service.sendMessage(value.connection.publicId, started.rawToken, "Hello"); const history = await fetch(path, { headers: { cookie } }); assert.equal(history.status, 200); const body = await history.json() as { messages: Array<Record<string, unknown>> }; assert.deepEqual(body.messages.map((message) => Object.keys(message).sort()), [["content", "createdAt", "direction"], ["content", "createdAt", "direction"]]); assert.deepEqual(body.messages.map((message) => [message.direction, message.content]), [["inbound", "Hello"], ["outbound", "Grounded answer"]]); assert.equal((await fetch(path)).status, 404); const other = value.connections.create(value.context, value.company.id, { assistantProfileId: value.connection.assistantProfileId }); assert.equal((await fetch(`${origin}/public/web-chat/${other.publicId}/messages`, { headers: { cookie } })).status, 404); value.sessionService.close(value.connection.publicId, started.rawToken); assert.equal((await fetch(path, { headers: { cookie } })).status, 404); } finally { await new Promise<void>((resolve) => listener.close(() => resolve())); value.database.close(); } });
test("EPIC-016.8 rejects expired public history sessions", async () => { const value = setup(), empty = express.Router(), app = createApp({ authorizedCompaniesRouter: empty, chatRouter: empty, companiesRouter: empty, identityRouter: empty, knowledgeRouter: empty, publicWebChatRouter: createPublicWebChatRouter(value.sessionService, value.service, false), scrapeRouter: empty, workspacesRouter: empty }), listener = app.listen(0, "127.0.0.1"); await new Promise<void>((resolve) => listener.once("listening", resolve)); const origin = `http://127.0.0.1:${(listener.address() as AddressInfo).port}`; try { const started = value.sessionService.start(value.connection.publicId, null), path = `${origin}/public/web-chat/${value.connection.publicId}/messages`; value.database.prepare("UPDATE web_chat_sessions SET expires_at=? WHERE token_digest=?").run("2026-07-01T00:00:00.000Z", createHash("sha256").update(started.rawToken).digest("hex")); assert.equal((await fetch(path, { headers: { cookie: `atlas_web_chat_session=${encodeURIComponent(started.rawToken)}` } })).status, 404); } finally { await new Promise<void>((resolve) => listener.close(() => resolve())); value.database.close(); } });
