import assert from "node:assert/strict";
import test from "node:test";
import { MediaDomainError, MediaStorageError } from "../media/domain/media.js";
import { S3MediaStorage } from "../media/infrastructure/s3MediaStorage.js";

const configuration={endpoint:"https://s3.example.test",region:"auto",bucket:"atlas-media",accessKeyId:"key",secretAccessKey:"secret"},id="mbl_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",location={workspaceId:1,companyId:2};
async function* bytes(...chunks:Uint8Array[]):AsyncGenerator<Uint8Array>{yield* chunks;}

test("EPIC056 PASS3 stages known bytes with explicit length and inspected content type",async()=>{let input:Record<string,unknown>|undefined;const storage=new S3MediaStorage(configuration,{send:async(command:{input:Record<string,unknown>})=>{input=command.input;for await(const _chunk of input.Body as AsyncIterable<Uint8Array>){}return{};}});const value=Uint8Array.of(1,2,3),refs=storage.plan(id,location);await storage.stage(refs,bytes(value),location,{sizeBytes:3,digest:"039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81",mediaType:"image/png"});assert.equal(input?.ContentLength,3);assert.equal(input?.ContentType,"image/png");});

test("EPIC056 PASS3 preserves staging and promotion integrity failures",async()=>{const refs=new S3MediaStorage(configuration,{send:async(command:{input:Record<string,unknown>})=>{for await(const _chunk of command.input.Body as AsyncIterable<Uint8Array>){}return{};}}).plan(id,location),stage=new S3MediaStorage(configuration,{send:async(command:{input:Record<string,unknown>})=>{for await(const _chunk of command.input.Body as AsyncIterable<Uint8Array>){}return{};}});await assert.rejects(stage.stage(refs,bytes(Uint8Array.of(1)),location,{sizeBytes:2,digest:"039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81",mediaType:"image/png"}),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_integrity_invalid");const promote=new S3MediaStorage(configuration,{send:async(command:{constructor:{name:string}})=>command.constructor.name==="GetObjectCommand"?{ContentLength:2,Body:bytes(Uint8Array.of(1))}:{}});await assert.rejects(promote.promote(refs.stagingReference,id,"image/png"),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_integrity_invalid");});

test("EPIC056 PASS3 promotes bounded bytes with an explicit create-only length",async()=>{let input:Record<string,unknown>|undefined;const value=Uint8Array.of(1,2,3),storage=new S3MediaStorage(configuration,{send:async(command:{constructor:{name:string};input:Record<string,unknown>})=>{if(command.constructor.name==="GetObjectCommand")return{ContentLength:value.byteLength,Body:bytes(value)};if(command.constructor.name==="PutObjectCommand")input=command.input;return{};}}),refs=storage.plan(id,location);await storage.promote(refs.stagingReference,id,"image/png");assert.equal(input?.IfNoneMatch,"*");assert.equal(input?.ContentType,"image/png");assert.equal(input?.ContentLength,value.byteLength);assert.equal(input?.Body instanceof Uint8Array,true);assert.deepEqual(input?.Body,value);});

test("EPIC056 PASS3 rejects oversized, truncated, and bodyless reads safely",async()=>{const reference="workspaces/1/companies/2/media/mbl_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/object";for(const response of [{ContentLength:3,Body:bytes(Uint8Array.of(1,2))},{ContentLength:1,Body:bytes(Uint8Array.of(1,2))},{ContentLength:1}]){const storage=new S3MediaStorage(configuration,{send:async()=>response});await assert.rejects(storage.read(reference,2),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_integrity_invalid"||error instanceof MediaDomainError&&error.code==="media_storage_failed");}});

test("EPIC056 PASS3 maps timeout failures without provider detail leakage",async()=>{const reference="workspaces/1/companies/2/media/mbl_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/object",storage=new S3MediaStorage(configuration,{send:async()=>{throw new Error("secret endpoint failure");}});await assert.rejects(storage.delete(reference),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_storage_failed"&&!error.message.includes("secret"));});

test("EPIC056 PASS3 classifies provider failures and confirms only delete absence",async()=>{const reference="workspaces/1/companies/2/media/mbl_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/object";for(const [error,category] of [[Object.assign(new Error("raw"),{name:"TimeoutError"}),"timeout"],[Object.assign(new Error("raw"),{$metadata:{httpStatusCode:503}}),"transient_provider"],[Object.assign(new Error("raw"),{code:"ECONNRESET"}),"transport"],[Object.assign(new Error("raw"),{name:"AccessDenied",$metadata:{httpStatusCode:403}}),"authorization"],[Object.assign(new Error("raw"),{name:"PreconditionFailed",$metadata:{httpStatusCode:412}}),"collision"],[Object.assign(new Error("raw"),{name:"NoSuchKey",$metadata:{httpStatusCode:404}}),"not_found"],[new Error("raw"),"permanent"]] as const){const storage=new S3MediaStorage(configuration,{send:async()=>{throw error;}});if(category==="not_found")assert.deepEqual(await storage.delete(reference),{status:"absent"});else await assert.rejects(storage.delete(reference),(value:unknown)=>value instanceof MediaStorageError&&value.category===category&&!value.message.includes("raw"));}});
