import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { createDatabase } from "../config/database.js";
import { ConversationRepository } from "../repositories/conversationRepository.js";
import { OutboundDeliveryRepository } from "../repositories/outboundDeliveryRepository.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";
import { conversationId, conversationMessageId, conversationParticipantId, reconstructConversation, reconstructConversationMessage, reconstructConversationParticipant } from "../conversation/domain/conversation.js";

const at = "2026-08-26T12:00:00.000Z";
function setup(path=":memory:") {
  const db=createDatabase(path), context=createWorkspaceContext(new WorkspaceRepository(db).resolveDefault()), company=new CompanyRepository(db).create(context,{name:"Order",website:"https://order.test"}), conversations=new ConversationRepository(db), deliveries=new OutboundDeliveryRepository(db);
  const make=(suffix:string)=>{const conversation=conversations.createConversation(context,reconstructConversation({id:conversationId(`cnv_${suffix.padStart(32,"0")}`),companyId:company.id,channel:"whatsapp",state:"open",createdAt:at,updatedAt:at,closedAt:null}))!, participant=conversations.createParticipant(context,company.id,reconstructConversationParticipant({id:conversationParticipantId(`cpt_${suffix.padStart(32,"0")}`),conversationId:conversation.id,type:"assistant",reference:"assistant",createdAt:at}))!; return {conversation,participant};};
  const first=make("1"), second=make("2"); let sequence=0;
  const add=(target:typeof first,state:string)=>{sequence+=1;const id=sequence.toString(16).padStart(32,"0"), message=conversations.createMessage(context,company.id,reconstructConversationMessage({id:conversationMessageId(`cmsg_${id}`),conversationId:target.conversation.id,senderParticipantId:target.participant.id,direction:"outbound",content:id,idempotencyKey:null,executionRecordId:null,createdAt:at}))!;db.prepare("INSERT INTO provider_message_records(id,communication_channel,transport_provider,direction,transport_connection_id,conversation_message_id,external_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").run(`pmr_${id}`,"whatsapp","meta_whatsapp_cloud","outbound","connection",message.id,null,at,at);db.prepare("INSERT INTO outbound_deliveries(id,provider_message_record_id,transport_connection_id,state,attempt_count,next_attempt_at,lease_owner,lease_expires_at,safe_error_category,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(`odl_${id}`,`pmr_${id}`,"connection",state,0,at,state==="leased"?"old":null,state==="leased"?"2026-08-26T12:01:00.000Z":null,null,at,at);return `odl_${id}`;};
  return {db,deliveries,first,second,add};
}
test("EPIC043 orders non-terminal outbound deliveries per conversation without blocking another conversation",()=>{for(const state of ["pending","leased","retryable","uncertain"]){const v=setup();try{const a=v.add(v.first,state),b=v.add(v.first,"pending"),other=v.add(v.second,"pending");const leased=v.deliveries.leaseReady("worker",at,"2026-08-26T13:00:00.000Z",10).map(x=>x.id);assert.equal(leased.includes(b as never),false);assert.equal(leased.includes(other as never),true);v.db.prepare("UPDATE outbound_deliveries SET state='permanent_failure',lease_owner=NULL,lease_expires_at=NULL WHERE id=?").run(a);assert.equal(v.deliveries.leaseReady("worker2",at,"2026-08-26T13:00:00.000Z",10).some(x=>x.id===b),true);}finally{v.db.close();}}});
test("EPIC043 terminal deliveries release the next conversation delivery",()=>{for(const state of ["accepted","delivered","read","permanent_failure"]){const v=setup();try{v.add(v.first,state);const b=v.add(v.first,"pending");assert.equal(v.deliveries.leaseReady("worker",at,"2026-08-26T13:00:00.000Z",10).some(x=>x.id===b),true);}finally{v.db.close();}}});
test("EPIC043 restart recovery preserves retryable expired-lease and uncertain ordering",()=>{for(const state of ["retryable","leased","uncertain"]){const directory=mkdtempSync(join(tmpdir(),"atlas-043-order-")),path=join(directory,"atlas.sqlite"),v=setup(path);try{const a=v.add(v.first,state),b=v.add(v.first,"pending");v.db.close();const reopened=new DatabaseSync(path);reopened.exec("PRAGMA foreign_keys=ON");const deliveries=new OutboundDeliveryRepository(reopened);assert.equal(deliveries.leaseReady("restarted",at,"2026-08-26T13:00:00.000Z",10).some(x=>x.id===b),false);reopened.prepare("UPDATE outbound_deliveries SET state='accepted',lease_owner=NULL,lease_expires_at=NULL WHERE id=?").run(a);reopened.close();const finalDb=new DatabaseSync(path);finalDb.exec("PRAGMA foreign_keys=ON");assert.equal(new OutboundDeliveryRepository(finalDb).leaseReady("final",at,"2026-08-26T13:00:00.000Z",10).some(x=>x.id===b),true);finalDb.close();}finally{rmSync(directory,{recursive:true,force:true});}}});
test("EPIC043 two SQLite workers claim only the head while another conversation progresses",()=>{const directory=mkdtempSync(join(tmpdir(),"atlas-043-workers-")),path=join(directory,"atlas.sqlite"),v=setup(path);try{v.add(v.first,"pending");const blocked=v.add(v.first,"pending"),other=v.add(v.second,"pending");const second=new DatabaseSync(path);second.exec("PRAGMA foreign_keys=ON");const firstClaim=v.deliveries.leaseReady("one",at,"2026-08-26T13:00:00.000Z",10),secondClaim=new OutboundDeliveryRepository(second).leaseReady("two",at,"2026-08-26T13:00:00.000Z",10);const all=[...firstClaim,...secondClaim];assert.equal(all.filter(x=>x.id===blocked).length,0);assert.equal(all.filter(x=>x.id===other).length,1);assert.equal(all.length,2);second.close();}finally{v.db.close();rmSync(directory,{recursive:true,force:true});}});
