import assert from "node:assert/strict";
import test from "node:test";
import type { MediaService } from "../media/services/mediaService.js";
import type { VoiceRepositoryPort, VoiceWorkSettlement } from "../whatsapp/application/voicePorts.js";
import type { AudioTranscriptionRequest } from "../whatsapp/domain/voice.js";
import { VoiceTranscriptionWorkerService } from "../whatsapp/services/voiceTranscriptionWorkerService.js";
import { includeVoiceSemanticHistory, resolveVoiceSemanticContent, resolveVoiceSemanticMessage, VoiceSemanticContentUnavailableError } from "../whatsapp/services/voiceSemanticContentResolver.js";

const at = "2026-08-27T12:00:00.000Z", context = { workspaceId: 1, workspaceKey: "test" }, request = { id: "atr_1", workspaceId: 1, companyId: 1, conversationId: "cnv_1", messageId: "msg_1", mediaAssetId: "mas_1", state: "leased", leaseOwner: "worker", leaseExpiresAt: "2026-08-27T12:01:00.000Z", attemptCount: 1, expectedAuthorityGeneration: 1, safeOutcome: null, safeFailureCategory: null, createdAt: at, updatedAt: at, completedAt: null } as AudioTranscriptionRequest;

function wav(): Uint8Array { const bytes = new Uint8Array(44 + 16_000), view = new DataView(bytes.buffer); bytes.set(Buffer.from("RIFF")); view.setUint32(4, 16_036, true); bytes.set(Buffer.from("WAVEfmt "), 8); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, 8_000, true); view.setUint32(28, 16_000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); bytes.set(Buffer.from("data"), 36); view.setUint32(40, 16_000, true); return bytes; }
function worker(repository: Partial<VoiceRepositoryPort>, result: Parameters<ConstructorParameters<typeof VoiceTranscriptionWorkerService>[2]["transcribe"]>[0] extends never ? never : { readonly kind: "completed"; readonly transcript: string; readonly languageTag: string | null } | { readonly kind: "retryable" | "failed"; readonly safeFailureCategory: string }): VoiceTranscriptionWorkerService { return new VoiceTranscriptionWorkerService(repository as VoiceRepositoryPort, { open: async () => wav() } as Pick<MediaService, "open">, { transcribe: async () => result }, { now: () => at }, { owner: "worker", batchSize: 1, leaseMilliseconds: 60_000, transcriptionTimeoutMilliseconds: 50, maximumDurationMilliseconds: 2_000, createTranscriptId: () => "cat_1" }); }

test("EPIC044 PASS3A worker leases, inspects, transcribes, and atomically finalizes", async () => { let finalized: Parameters<VoiceRepositoryPort["finalizeTranscription"]>[4] | undefined; const repository: Partial<VoiceRepositoryPort> = { leaseTranscriptions: (_context, _company, lease) => { assert.equal(lease.owner, "worker"); return [request]; }, finalizeTranscription: (_context, _company, id, owner, value) => { assert.equal(id, request.id); assert.equal(owner, "worker"); finalized = value; return { kind: "opened", request, transcript: {} as never }; } }; assert.deepEqual(await worker(repository, { kind: "completed", transcript: " hola   atlas ", languageTag: "es" }).runOnce(context, 1), [{ kind: "completed", requestId: request.id }]); assert.equal(finalized?.transcript.normalizedTranscript, "hola atlas"); assert.match(finalized?.transcript.inputDigest ?? "", /^[a-f0-9]{64}$/u); });

test("EPIC044 PASS3A worker safely settles retryable and invalid provider results", async () => { const settlements: VoiceWorkSettlement[] = []; const repository: Partial<VoiceRepositoryPort> = { leaseTranscriptions: () => [request], settleTranscription: (_context, _company, _id, _owner, value) => { settlements.push(value); return request; } }; assert.deepEqual(await worker(repository, { kind: "retryable", safeFailureCategory: "provider_busy" }).runOnce(context, 1), [{ kind: "retryable", requestId: request.id }]); assert.deepEqual(await worker(repository, { kind: "completed", transcript: "   ", languageTag: null }).runOnce(context, 1), [{ kind: "failed", requestId: request.id }]); assert.deepEqual(settlements.map(value => [value.state, value.safeFailureCategory]), [["retryable", "provider_busy"], ["failed", "invalid_transcript"]]); });

test("EPIC044 PASS3A worker reports stale finalization ownership", async () => { const repository: Partial<VoiceRepositoryPort> = { leaseTranscriptions: () => [request], finalizeTranscription: () => ({ kind: "lease_lost" }) }; assert.deepEqual(await worker(repository, { kind: "completed", transcript: "hola", languageTag: "es" }).runOnce(context, 1), [{ kind: "lease_lost", requestId: request.id }]); });

test("EPIC044 PASS3A semantic content prefers the persisted transcript", () => { const repository = { findTranscriptByMessage: (_context: typeof context, _companyId: number, messageId: string) => messageId === "msg_1" ? { normalizedTranscript: "voice meaning" } as ReturnType<VoiceRepositoryPort["findTranscriptByMessage"]> : null }; assert.equal(resolveVoiceSemanticContent(repository, context, 1, "msg_1", "original"), "voice meaning"); assert.equal(resolveVoiceSemanticContent(repository, context, 1, "missing", "original"), "original"); });

test("EPIC044 PASS4 semantic projection preserves message identity and gates deferred history", () => { const inbound: import("../conversation/domain/conversation.js").ConversationMessage = { id: "cmsg_10000000000000000000000000000000", conversationId: "cnv_10000000000000000000000000000000", senderParticipantId: "cpt_10000000000000000000000000000000", direction: "inbound", content: "[attachment received]", idempotencyKey: null, executionRecordId: null, createdAt: at } as never, assistant: import("../conversation/domain/conversation.js").ConversationMessage = { id: "cmsg_20000000000000000000000000000000", conversationId: inbound.conversationId, senderParticipantId: inbound.senderParticipantId, direction: "outbound", content: "generated", idempotencyKey: null, executionRecordId: null, createdAt: at } as never; const repository = { findTranscriptByMessage: (_context: typeof context, _companyId: number, messageId: string) => messageId === inbound.id ? { normalizedTranscript: "canonical voice meaning" } as ReturnType<VoiceRepositoryPort["findTranscriptByMessage"]> : null, isVoiceInboundMessage: (_context: typeof context, _companyId: number, messageId: string) => messageId === inbound.id, isAssistantMessageSemanticallyVisible: (_context: typeof context, _companyId: number, messageId: string) => messageId === assistant.id }; const semantic = resolveVoiceSemanticMessage(repository, context, 1, inbound); assert.equal(semantic.id, inbound.id); assert.equal(semantic.content, "canonical voice meaning"); assert.equal(inbound.content, "[attachment received]"); assert.equal(includeVoiceSemanticHistory(repository, context, 1, inbound), true); assert.equal(includeVoiceSemanticHistory(repository, context, 1, assistant), true); assert.equal(includeVoiceSemanticHistory({ ...repository, isAssistantMessageSemanticallyVisible: () => false }, context, 1, assistant), false); });

test("EPIC044 PASS4 fails closed before placeholder crosses the semantic boundary", () => { const message = { id: "cmsg_30000000000000000000000000000000", conversationId: "cnv_10000000000000000000000000000000", senderParticipantId: "cpt_10000000000000000000000000000000", direction: "inbound", content: "[attachment received]", idempotencyKey: null, executionRecordId: null, createdAt: at } as import("../conversation/domain/conversation.js").ConversationMessage; assert.throws(() => resolveVoiceSemanticMessage({ findTranscriptByMessage: () => null, isVoiceInboundMessage: () => true }, context, 1, message), VoiceSemanticContentUnavailableError); });
