import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { createDatabase } from "../config/database.js";
import type { MediaStoragePort, MediaStorageReferences } from "../media/application/ports.js";
import type { MediaAsset, MediaBlob, MediaIngestAttempt } from "../media/domain/media.js";
import { MediaStorageError } from "../media/domain/media.js";
import { MediaRecoveryService } from "../media/services/mediaRecoveryService.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { MediaRepository } from "../repositories/mediaRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";
import { WhatsAppRecoveryRuntime } from "../whatsapp/services/WhatsAppRecoveryRuntime.js";

const at = "2026-09-21T00:00:00.000Z";
const expires = "2026-09-21T01:00:00.000Z";
const afterExpiry = "2026-09-21T02:00:00.000Z";
const png = Uint8Array.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 1]);
const digest = createHash("sha256").update(png).digest("hex");

class Storage implements MediaStoragePort {
  public readonly objects = new Map<string, Uint8Array>();
  public readonly owned: Array<{ reference: string; createdAt: string }> = [];
  public deleteError: MediaStorageError | null = null;
  public plan(id: string): MediaStorageReferences { return { stagingReference: `tmp_${id}`, finalStorageReference: id }; }
  public async stage(references: MediaStorageReferences, content: AsyncIterable<Uint8Array>) { const bytes: number[] = []; for await (const chunk of content) bytes.push(...chunk); const value = Uint8Array.from(bytes); this.objects.set(references.stagingReference, value); return { temporaryReference: references.stagingReference, finalStorageReference: references.finalStorageReference, digest: createHash("sha256").update(value).digest("hex"), sizeBytes: value.byteLength }; }
  public async readTemporary(reference: string): Promise<Uint8Array> { return this.value(reference); }
  public async promote(temporaryReference: string, blobId: string): Promise<string> { this.objects.set(blobId, this.value(temporaryReference)); this.objects.delete(temporaryReference); return blobId; }
  public async delete(reference: string) { if (this.deleteError) throw this.deleteError; this.objects.delete(reference); return { status: "absent" as const }; }
  public async read(reference: string): Promise<Uint8Array> { return this.value(reference); }
  public async listOwned(): Promise<readonly { reference: string; createdAt: string }[]> { return this.owned; }
  private value(reference: string): Uint8Array { const value = this.objects.get(reference); if (!value) throw new MediaStorageError("not_found"); return value; }
}

function fixture() { const db = createDatabase(":memory:"), workspaces = new WorkspaceRepository(db), context = createWorkspaceContext(workspaces.resolveDefault()), companies = new CompanyRepository(db), company = companies.create(context, { name: "Recovery", website: "https://recovery.test" }), repository = new MediaRepository(db), storage = new Storage(); return { db, workspaces, context, companies, company, repository, storage }; }
function reservation(context: ReturnType<typeof createWorkspaceContext>, companyId: number, suffix: string) { const asset: MediaAsset = { id: `mas_${suffix}`, workspaceId: context.workspaceId, companyId, kind: "image", mediaType: "image/png", sizeBytes: null, filename: null, metadata: {}, status: "pending", createdAt: at, archivedAt: null, deletedAt: null }; const attempt: MediaIngestAttempt = { assetId: asset.id, workspaceId: context.workspaceId, companyId, candidateBlobId: `mbl_${suffix}`, stagingStorageReference: `tmp_${suffix}`, finalStorageReference: `mbl_${suffix}`, digest, sizeBytes: png.byteLength, inspectedMediaType: "image/png", state: "reserved", leaseOwner: null, leaseToken: null, leaseExpiresAt: null, attemptCount: 0, failureCategory: null, createdAt: at, updatedAt: at, settledAt: null }; const blob: MediaBlob = { id: attempt.candidateBlobId, workspaceId: context.workspaceId, companyId, digest, sizeBytes: png.byteLength, mediaType: "image/png", storageReference: attempt.finalStorageReference, state: "active", createdAt: at }; return { asset, attempt, blob }; }
function reserve(v: ReturnType<typeof fixture>, suffix: string, context = v.context, companyId = v.company.id) { const value = reservation(context, companyId, suffix); assert.equal(v.repository.reserve(context, companyId, "ingest", suffix, "b".repeat(64), value.asset, value.attempt, at).kind, "reserved"); return value; }
function recovery(v: ReturnType<typeof fixture>, now = at) { return new MediaRecoveryService(v.repository, v.storage, { now: () => now }); }
function ready(v: ReturnType<typeof fixture>, suffix: string) { const value = reserve(v, suffix); v.storage.objects.set(value.blob.storageReference, png); assert.ok(v.repository.markStaged(v.context, v.company.id, value.asset.id, at)); assert.ok(v.repository.markPromoted(v.context, v.company.id, value.asset.id, at)); assert.equal(v.repository.complete(v.context, v.company.id, value.asset.id, value.blob, at)?.status, "ready"); return value; }

test("EPIC056 PASS4 recovers reserved, staged, and retryable durable attempts", async () => { const v = fixture(); try { const reserved = reserve(v, "reserved"), staged = reserve(v, "staged"), retryable = reserve(v, "retryable"); for (const value of [reserved, staged]) v.storage.objects.set(value.attempt.stagingStorageReference, png); v.storage.objects.set(retryable.attempt.finalStorageReference, png); assert.ok(v.repository.markStaged(v.context, v.company.id, staged.asset.id, at)); assert.ok(v.repository.markStaged(v.context, v.company.id, retryable.asset.id, at)); assert.ok(v.repository.markPromoted(v.context, v.company.id, retryable.asset.id, at)); v.repository.fail(v.context, v.company.id, retryable.asset.id, "timeout", true, at); for (let index = 0; index < 3; index += 1) assert.equal(await recovery(v).recover(v.context, v.company.id, { owner: "worker", limit: 1, leaseMilliseconds: 60_000 }), 1); for (const value of [reserved, staged, retryable]) assert.equal(v.repository.findIngestAttempt(v.context, v.company.id, value.asset.id)?.state, "settled", value.asset.id); } finally { v.db.close(); } });

test("EPIC056 PASS4 duplicate workers, stale owners, and expired leases cannot overlap recovery", async () => { const v = fixture(); try { const duplicate = reserve(v, "duplicate"); v.storage.objects.set(duplicate.attempt.stagingStorageReference, png); assert.deepEqual((await Promise.all([recovery(v).recover(v.context, v.company.id, { owner: "first", limit: 1, leaseMilliseconds: 60_000 }), recovery(v).recover(v.context, v.company.id, { owner: "second", limit: 1, leaseMilliseconds: 60_000 })])).sort(), [0, 1]); const stale = reserve(v, "stale"); v.storage.objects.set(stale.attempt.stagingStorageReference, png); assert.equal(v.repository.leaseIncomplete(v.context, v.company.id, "lost", "token", at, expires, 1).length, 1); assert.equal(await recovery(v).recover(v.context, v.company.id, { owner: "replacement", limit: 1, leaseMilliseconds: 60_000 }), 0); assert.equal(v.repository.markRecoveryStaged(v.context, v.company.id, stale.asset.id, "lost", "token", afterExpiry), false); assert.equal(await recovery(v, afterExpiry).recover(v.context, v.company.id, { owner: "replacement", limit: 1, leaseMilliseconds: 60_000 }), 1); } finally { v.db.close(); } });

test("EPIC056 PASS4 fences recovery transitions by owner, token, and expiry", () => { const v = fixture(); try { const value = reserve(v, "fenced"); assert.equal(v.repository.leaseIncomplete(v.context, v.company.id, "owner", "token", at, expires, 1).length, 1); assert.equal(v.repository.markRecoveryStaged(v.context, v.company.id, value.asset.id, "other", "token", at), false); assert.equal(v.repository.markRecoveryStaged(v.context, v.company.id, value.asset.id, "owner", "other", at), false); assert.equal(v.repository.markRecoveryStaged(v.context, v.company.id, value.asset.id, "owner", "token", afterExpiry), false); assert.equal(v.repository.markRecoveryStaged(v.context, v.company.id, value.asset.id, "owner", "token", at), true); assert.equal(v.repository.markRecoveryPromoted(v.context, v.company.id, value.asset.id, "owner", "token", at), true); assert.equal(v.repository.settleRecovery(v.context, v.company.id, value.asset.id, "other", "token", value.blob, at), null); assert.equal(v.repository.failRecovery(v.context, v.company.id, value.asset.id, "owner", "other", "integrity", false, at), false); } finally { v.db.close(); } });

test("EPIC056 PASS4 reclaims once under contention and does not finalize ambiguous deletes", async () => { const v = fixture(); try { const reclaimed = ready(v, "reclaim"); assert.ok(v.repository.delete(v.context, v.company.id, reclaimed.asset.id, at)?.reclaim); await Promise.all([recovery(v).recover(v.context, v.company.id, { owner: "one", limit: 1, leaseMilliseconds: 60_000 }), recovery(v).recover(v.context, v.company.id, { owner: "two", limit: 1, leaseMilliseconds: 60_000 })]); assert.equal((v.db.prepare("SELECT state FROM media_blobs WHERE id=?").get(reclaimed.blob.id) as { state: string }).state, "reclaimed"); const ambiguous = ready(v, "ambiguous"); assert.ok(v.repository.delete(v.context, v.company.id, ambiguous.asset.id, at)?.reclaim); v.storage.deleteError = new MediaStorageError("transport"); await assert.rejects(recovery(v).recover(v.context, v.company.id, { owner: "worker", limit: 1, leaseMilliseconds: 60_000 })); assert.equal((v.db.prepare("SELECT state FROM media_blobs WHERE id=?").get(ambiguous.blob.id) as { state: string }).state, "reclaim_pending"); } finally { v.db.close(); } });

test("EPIC056 PASS4 detects missing and corrupt ready media", async () => { const v = fixture(); try { const missing = ready(v, "missing"), corrupt = ready(v, "corrupt"); v.storage.objects.delete(missing.blob.storageReference); v.storage.objects.set(corrupt.blob.storageReference, Uint8Array.of(1)); assert.equal(await recovery(v).recover(v.context, v.company.id, { owner: "worker", limit: 10, leaseMilliseconds: 60_000 }), 0); assert.equal(v.repository.findAsset(v.context, v.company.id, missing.asset.id)?.status, "failed"); assert.equal(v.repository.findAsset(v.context, v.company.id, corrupt.asset.id)?.status, "failed"); } finally { v.db.close(); } });

test("EPIC056 PASS4 deletes 24-hour orphans but preserves newer and referenced objects", async () => { const v = fixture(), originalNow = Date.now; try { const referenced = ready(v, "referenced"); v.storage.objects.set("old-orphan", png); v.storage.objects.set("new-orphan", png); v.storage.owned.push({ reference: "old-orphan", createdAt: "2026-09-19T00:00:00.000Z" }, { reference: "new-orphan", createdAt: "2026-09-20T23:00:00.001Z" }, { reference: referenced.blob.storageReference, createdAt: "2026-09-19T00:00:00.000Z" }); Date.now = () => Date.parse(at); await recovery(v).recover(v.context, v.company.id, { owner: "worker", limit: 10, leaseMilliseconds: 60_000 }); assert.equal(v.storage.objects.has("old-orphan"), false); assert.equal(v.storage.objects.has("new-orphan"), true); assert.equal(v.storage.objects.has(referenced.blob.storageReference), true); } finally { Date.now = originalNow; v.db.close(); } });

test("EPIC056 PASS4 isolates recovery by workspace and company", async () => { const v = fixture(); try { const otherContext = createWorkspaceContext(v.workspaces.createForSystemUse({ key: "other", name: "Other" })), otherCompany = v.companies.create(otherContext, { name: "Other", website: "https://other.test" }), other = reserve(v, "other", otherContext, otherCompany.id); v.storage.objects.set(other.attempt.stagingStorageReference, png); assert.equal(await recovery(v).recover(v.context, v.company.id, { owner: "worker", limit: 10, leaseMilliseconds: 60_000 }), 0); assert.equal(v.repository.findIngestAttempt(otherContext, otherCompany.id, other.asset.id)?.state, "reserved"); assert.equal(await recovery(v).recoverAvailable("worker"), 1); assert.equal(v.repository.findIngestAttempt(otherContext, otherCompany.id, other.asset.id)?.state, "settled"); } finally { v.db.close(); } });

test("EPIC056 PASS4 runtime cycles are bounded to one active invocation", async () => { let invoke: (() => void) | undefined, calls = 0, release: (() => void) | undefined; const gate = new Promise<void>(resolve => { release = resolve; }); const runtime = new WhatsAppRecoveryRuntime(async () => { calls += 1; await gate; }, { schedule: callback => { invoke = callback; return { unref() {} }; }, clear: () => undefined }); runtime.start(); invoke?.(); invoke?.(); assert.equal(calls, 1); release?.(); await runtime.stop(); assert.equal(calls, 1); });
