import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { createDatabase } from "../config/database.js";
import { runMigrations } from "../config/migrations.js";
import { LocalSqlDatabase } from "../config/sqlDatabase.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { SchedulingConfigurationRepository } from "../repositories/schedulingConfigurationRepository.js";
import { SchedulingRepository } from "../repositories/schedulingRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { SchedulingConfigurationConflictError, SchedulingConfigurationService } from "../scheduling/services/schedulingConfigurationService.js";
import { SchedulingService } from "../scheduling/services/schedulingService.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";

const at = "2026-09-14T00:00:00.000Z";
function setup() { const database = createDatabase(":memory:"), context = createWorkspaceContext(new WorkspaceRepository(database).resolveDefault()), company = new CompanyRepository(database).create(context, { name: "Scheduling Config", website: "https://scheduling-config.test" }), service = new SchedulingConfigurationService(new SchedulingConfigurationRepository(new LocalSqlDatabase(database)), { now: () => at }); return { database, context, company, service }; }
async function command(service: SchedulingConfigurationService, context: ReturnType<typeof createWorkspaceContext>, companyId: number, expectedVersion: number, operation: string, payload: Record<string, unknown>, operationId = `${operation}-${expectedVersion}`) { return service.command(context, companyId, "user", { operationId, expectedVersion, operation, payload }); }

test("EPIC051 migration reaches 0073 and upgrades 0072 without changing scheduling data", async () => {
  const directory = mkdtempSync(join(tmpdir(), "atlas-epic051-")), path = join(directory, "atlas.sqlite"); let database = new DatabaseSync(path);
  try { database.exec("PRAGMA foreign_keys=ON"); runMigrations(database, 72); const context = createWorkspaceContext(new WorkspaceRepository(database).resolveDefault()), company = new CompanyRepository(database).create(context, { name: "Legacy Scheduling", website: "https://legacy-scheduling.test" }), legacy = new SchedulingService(new SchedulingRepository(new LocalSqlDatabase(database)), { now: () => at }), resource = await legacy.createResource(context, company.id, { name: "Legacy Room", timezone: "UTC" }); runMigrations(database); assert.deepEqual({ ...(database.prepare("SELECT id,name FROM schema_migrations ORDER BY id DESC LIMIT 1").get() as Record<string, unknown>) }, { id: 73, name: "0073_scheduling_configuration_controls" }); assert.equal((database.prepare("SELECT name FROM scheduling_resources WHERE id=?").get(resource.id) as { name: string }).name, "Legacy Room"); assert.equal((database.prepare("SELECT version FROM scheduling_configuration_controls WHERE workspace_id=? AND company_id=?").get(context.workspaceId, company.id) as { version: number }).version, 1); } finally { database.close(); rmSync(directory, { recursive: true, force: true }); }
});
test("EPIC051 durable operation and audit rows reject update/delete after a successful command", async () => {
  const { database, context, company, service } = setup(); try { await command(service, context, company.id, 1, "create_location", { name: "Main", timezone: "UTC" }); const operation = database.prepare("SELECT outcome_json FROM scheduling_configuration_operations").get() as { outcome_json: string }, audit = database.prepare("SELECT action FROM scheduling_configuration_audit_events").get() as { action: string }; assert.throws(() => database.prepare("UPDATE scheduling_configuration_operations SET outcome_json='{}'").run(), /append-only/); assert.throws(() => database.prepare("DELETE FROM scheduling_configuration_operations").run(), /append-only/); assert.throws(() => database.prepare("UPDATE scheduling_configuration_audit_events SET action='changed'").run(), /append-only/); assert.throws(() => database.prepare("DELETE FROM scheduling_configuration_audit_events").run(), /append-only/); assert.equal((database.prepare("SELECT outcome_json FROM scheduling_configuration_operations").get() as { outcome_json: string }).outcome_json, operation.outcome_json); assert.equal((database.prepare("SELECT action FROM scheduling_configuration_audit_events").get() as { action: string }).action, audit.action); } finally { database.close(); } });
test("EPIC051 readiness progresses only to availability usable by the booking engine", async () => {
  const { database, context, company, service } = setup(); try { assert.equal(((await service.read(context, company.id)).readiness as { state: string }).state, "not_configured"); const resource = await command(service, context, company.id, 1, "create_resource", { name: "Room", timezone: "UTC" }); assert.equal(((await service.read(context, company.id)).readiness as { state: string }).state, "minimal"); const resourceId = ((resource.affected as { entityId: string }).entityId); await command(service, context, company.id, 2, "create_service", { resourceId, name: "Visit", durationMinutes: 30 }); assert.equal(((await service.read(context, company.id)).readiness as { state: string }).state, "minimal"); await command(service, context, company.id, 3, "replace_weekly_availability", { resourceId, windows: [{ weekday: 1, startTime: "09:00", endTime: "17:00" }] }); const readiness = (await service.read(context, company.id)).readiness as { state: string; hasServices: boolean; hasWeeklyAvailability: boolean }; assert.deepEqual(readiness, { state: "locally_configured", hasLocations: false, hasResources: true, hasServices: true, hasWeeklyAvailability: true }); } finally { database.close(); } });
test("EPIC051 commands replay exactly once, reject conflicts and roll back failures", async () => {
  const { database, context, company, service } = setup(); try { const input = { name: "Main", timezone: "UTC" }, first = await command(service, context, company.id, 1, "create_location", input, "same"); const replay = await command(service, context, company.id, 1, "create_location", input, "same"); assert.deepEqual(replay, first); assert.equal((database.prepare("SELECT COUNT(*) count FROM scheduling_locations").get() as { count: number }).count, 1); assert.equal((database.prepare("SELECT version FROM scheduling_configuration_controls").get() as { version: number }).version, 2); assert.equal((database.prepare("SELECT COUNT(*) count FROM scheduling_configuration_audit_events").get() as { count: number }).count, 1); await assert.rejects(command(service, context, company.id, 2, "create_location", { name: "Other", timezone: "UTC" }, "same"), SchedulingConfigurationConflictError); await assert.rejects(command(service, context, company.id, 1, "create_location", { name: "Stale", timezone: "UTC" }, "stale"), SchedulingConfigurationConflictError); const before = database.prepare("SELECT version FROM scheduling_configuration_controls").get() as { version: number }; await assert.rejects(command(service, context, company.id, 2, "create_resource", { name: "Bad", timezone: "Invalid/Timezone" }, "invalid")); assert.equal((database.prepare("SELECT COUNT(*) count FROM scheduling_resources").get() as { count: number }).count, 0); assert.equal((database.prepare("SELECT COUNT(*) count FROM scheduling_configuration_operations WHERE operation_id='invalid'").get() as { count: number }).count, 0); assert.equal((database.prepare("SELECT version FROM scheduling_configuration_controls").get() as { version: number }).version, before.version); } finally { database.close(); } });
test("EPIC051 updates mutable scheduling entities and rejects cross-company references", async () => {
  const { database, context, company, service } = setup(); try { const location = await command(service, context, company.id, 1, "create_location", { name: "Old", timezone: "UTC" }), locationId = (location.affected as { entityId: string }).entityId; await command(service, context, company.id, 2, "update_location", { locationId, name: "New", address: "1 Atlas Way", timezone: "UTC", active: false }); assert.equal((database.prepare("SELECT name,active FROM scheduling_locations WHERE id=?").get(locationId) as { name: string; active: number }).name, "New"); const resource = await command(service, context, company.id, 3, "create_resource", { name: "Room", timezone: "UTC" }), resourceId = (resource.affected as { entityId: string }).entityId; await command(service, context, company.id, 4, "update_resource", { resourceId, locationId: null, name: "Room Two", timezone: "UTC", capacity: 2, active: true }); assert.equal((database.prepare("SELECT capacity,active FROM scheduling_resources WHERE id=?").get(resourceId) as { capacity: number; active: number }).capacity, 2); const bookingService = await command(service, context, company.id, 5, "create_service", { resourceId, name: "Visit", durationMinutes: 30 }), serviceId = (bookingService.affected as { entityId: string }).entityId; await command(service, context, company.id, 6, "update_service", { serviceId, resourceId, name: "Visit Two", durationMinutes: 45, bufferBeforeMinutes: 5, bufferAfterMinutes: 5, slotGranularityMinutes: 15, minimumLeadMinutes: 30, maximumHorizonDays: 60, active: false }); const updated = database.prepare("SELECT duration_minutes,active FROM scheduling_services WHERE id=?").get(serviceId) as { duration_minutes: number; active: number }; assert.deepEqual({ ...updated }, { duration_minutes: 45, active: 0 }); const other = new CompanyRepository(database).create(context, { name: "Other", website: "https://other-scheduling.test" }), otherResource = await command(service, context, other.id, 1, "create_resource", { name: "Other Room", timezone: "UTC" }); const before = database.prepare("SELECT version FROM scheduling_configuration_controls WHERE company_id=?").get(company.id) as { version: number }; await assert.rejects(command(service, context, company.id, before.version, "create_service", { resourceId: (otherResource.affected as { entityId: string }).entityId, name: "Wrong", durationMinutes: 30 }, "wrong-company")); assert.equal((database.prepare("SELECT COUNT(*) count FROM scheduling_services WHERE company_id=?").get(company.id) as { count: number }).count, 1); } finally { database.close(); } });
