import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { runMigrations } from "../config/migrations.js";
import { BillingOperationService } from "../billing/application/billingOperationService.js";
import { DeterministicFakeBillingProvider, stripeBillingProviderCapabilities } from "../billing/application/billingProvider.js";
import { BillingProviderRegistry } from "../billing/application/billingProviderRegistry.js";
import { BillingOperationRepository } from "../repositories/billingOperationRepository.js";
import { BillingAccountRepository, BillingCatalogRepository, BillingProviderCommercialOfferRepository, BillingSubscriptionRepository } from "../repositories/billingRepository.js";
import { asyncBillingOperations } from "./helpers/asyncBillingTestComposition.js";

const at="2026-09-01T00:00:00.000Z";
function open():DatabaseSync{const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");runMigrations(db);return db;}
function account(db:DatabaseSync){return new BillingAccountRepository(db).findByWorkspace((db.prepare("SELECT id FROM workspaces WHERE key='default'").get()as{id:number}).id)!;}
function plan(db:DatabaseSync,key:string,kind:"stripe"|"mercadopago",amount:number){return new BillingCatalogRepository(db).create({planKey:key,catalogVersion:1,displayName:key,interval:"month",currency:kind==="stripe"?"USD":"ARS",amountMinor:amount,lifecycle:"active",maxCompanies:1,maxAssistantProfiles:1,maxActiveChannels:1,mutationEligible:true,entitlementDefinitionVersion:1,providerKind:kind,providerPriceId:`${kind}_${key}`});}

test("EPIC052 accepts independent Stripe/USD and Mercado Pago/ARS prices for one Atlas plan",()=>{const db=open();try{const catalog=new BillingCatalogRepository(db),entry=catalog.create({planKey:"atlas",catalogVersion:1,displayName:"Atlas",interval:"month",currency:"USD",amountMinor:100,lifecycle:"active",maxCompanies:1,maxAssistantProfiles:1,maxActiveChannels:1,mutationEligible:true,entitlementDefinitionVersion:1,providerKind:"stripe",providerPriceId:"price_usd"}),offers=new BillingProviderCommercialOfferRepository(db),mp=offers.create({catalogEntryId:entry.id,providerKind:"mercadopago",offerVersion:1,currency:"ARS",amountMinor:2500,interval:"month",providerPlanReference:"mp_ars",readinessState:"ready",lifecycle:"sellable",at});assert.deepEqual(catalog.sellableOffers(entry.id).map(value=>[value.providerKind,value.currency,value.amountMinor]),[["mercadopago","ARS",2500],["stripe","USD",100]]);assert.throws(()=>offers.create({catalogEntryId:entry.id,providerKind:"stripe",offerVersion:2,currency:"ARS",amountMinor:1,interval:"month",providerPlanReference:"bad",readinessState:"ready",lifecycle:"sellable",at}));assert.equal(mp.currency,"ARS");}finally{db.close();}});

test("EPIC052 binds checkout replay to the exact provider commercial offer",()=>{const db=open();try{const entry=plan(db,"binding","stripe",100),offers=new BillingProviderCommercialOfferRepository(db),first=offers.findForCatalogProvider(entry.id,"stripe")!,second=offers.create({catalogEntryId:entry.id,providerKind:"stripe",offerVersion:2,currency:"USD",amountMinor:200,interval:"year",providerPlanReference:"price_annual",readinessState:"ready",lifecycle:"sellable",at}),operations=new BillingOperationRepository(db),a=account(db),input={billingAccountId:a.id,kind:"checkout_session_create" as const,providerKind:"stripe" as const,operationId:"bound",fingerprint:"a".repeat(64),catalogEntryId:entry.id,providerCommercialOfferId:first.id,at};assert.equal(operations.createOrReplay(input).kind,"created");assert.equal(operations.createOrReplay(input).kind,"same");assert.equal(operations.createOrReplay({...input,providerCommercialOfferId:second.id}).kind,"conflict");assert.equal(operations.createOrReplay({...input,providerKind:"mercadopago"}).kind,"conflict");assert.equal(operations.checkoutProviderReference(operations.find(a.id,"checkout_session_create","bound")!),"stripe_binding");}finally{db.close();}});

test("EPIC052 legacy unbound recovery retains trusted persisted catalog evidence only",()=>{const db=open();try{const entry=plan(db,"legacy","stripe",100),a=account(db),operations=new BillingOperationRepository(db);operations.createOrReplay({billingAccountId:a.id,kind:"checkout_session_create",providerKind:"stripe",operationId:"legacy-op",fingerprint:"d".repeat(64),catalogEntryId:entry.id,at});db.exec("DROP TRIGGER billing_checkout_enrollments_provider_offer_backfill");db.prepare("INSERT INTO billing_checkout_enrollments(id,billing_account_id,catalog_entry_id,provider_commercial_offer_id,checkout_operation_id,provider_kind,provider_checkout_object_id,provider_subscription_id,provider_customer_id,status,version,created_at,updated_at) VALUES('legacy',?,?,NULL,(SELECT id FROM billing_operations WHERE billing_account_id=? AND operation_id='legacy-op'),'stripe','cs_legacy','sub_legacy',NULL,'ready',1,?,?)").run(a.id,entry.id,a.id,at,at);const row=db.prepare("SELECT provider_commercial_offer_id FROM billing_checkout_enrollments WHERE id='legacy'").get()as{provider_commercial_offer_id:null};assert.equal(row.provider_commercial_offer_id,null);assert.equal(operations.hasOpenCheckoutEnrollment(a.id),true);}finally{db.close();}});

test("EPIC052 cross-provider checkout races return conflict without a second provider mutation",async()=>{const db=open();try{const a=account(db),stripePlan=plan(db,"race-stripe","stripe",100),mpPlan=plan(db,"race-mp","mercadopago",100),stripe=new DeterministicFakeBillingProvider({kind:"success",providerObjectId:"cs_race"}),mp=new DeterministicFakeBillingProvider({kind:"success",providerObjectId:"mp_race"},{...stripeBillingProviderCapabilities,requiresPayerEmailForCheckout:false}),service=asyncBillingOperations(db,new BillingProviderRegistry([{kind:"stripe",provider:stripe},{kind:"mercadopago",provider:mp}]),()=>at);assert.equal((await service.checkout({workspaceId:a.workspaceId,catalogEntryId:stripePlan.id,operationId:"stripe",successTarget:"https://atlas.test/s",cancelTarget:"https://atlas.test/c"})).kind,"succeeded");assert.equal((await service.checkout({workspaceId:a.workspaceId,catalogEntryId:mpPlan.id,operationId:"mp",successTarget:"https://atlas.test/s",cancelTarget:"https://atlas.test/c"})).kind,"conflict");assert.equal(mp.calls.length,0);}finally{db.close();}});
