import assert from "node:assert/strict";
import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import test from "node:test";
import { runFreshAsyncMigrations } from "../config/asyncMigrations.js";
import { DatabaseSync } from "node:sqlite";
import { createDatabase } from "../config/database.js";
import { createLibsqlDatabase as createNativeLibsqlDatabase, SynchronousSqlDatabaseAdapter, type SqlDatabase } from "../config/sqlDatabase.js";
import { runMigrations } from "../config/migrations.js";
import { AsyncCompanyRepository } from "../company/infrastructure/asyncCompanyDomain.js";
import { BinaryMediaInspector } from "../media/infrastructure/mediaInspector.js";
import { AsyncMediaRepository } from "../media/infrastructure/asyncMediaPersistence.js";
import { LocalMediaStorage } from "../media/infrastructure/localMediaStorage.js";
import { MediaIngestInterrupted, MediaService } from "../media/services/mediaService.js";
import { MediaDomainError, type MediaAsset, type MediaIngestAttempt } from "../media/domain/media.js";
import type { MediaAssociationOwnerResolver, MediaRepositoryPort, MediaStoragePort } from "../media/application/ports.js";
import { MediaRepository } from "../repositories/mediaRepository.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";

const png=Uint8Array.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1]);
const nativeLibsqlDatabases=new Map<string,SqlDatabase>(),nativeLibsqlClosers=new Map<string,()=>Promise<void>>(),asyncDirectory=mkdtempSync(join(tmpdir(),"atlas-pass2-async-"));let asyncMigrationsReady=false,asyncCompanySequence=0;
function createLibsqlDatabase(url:string,authToken:string):SqlDatabase{const existing=nativeLibsqlDatabases.get(url);if(existing)return existing;const database=createNativeLibsqlDatabase(url,authToken);nativeLibsqlClosers.set(url,database.close.bind(database));database.close=async()=>{};nativeLibsqlDatabases.set(url,database);return database;}
async function* content():AsyncGenerator<Uint8Array>{yield png;}
class Owners implements MediaAssociationOwnerResolver { public owns():boolean{return true;} }
test.after(async()=>{for(const close of nativeLibsqlClosers.values())await close();});
function fixture(repository?:MediaRepositoryPort,storage?:MediaStoragePort){const directory=mkdtempSync(join(tmpdir(),"atlas-pass2-")),db=createDatabase(":memory:"),context=createWorkspaceContext(new WorkspaceRepository(db).resolveDefault()),company=new CompanyRepository(db).create(context,{name:"Durable media",website:"https://media.test"}),local=new LocalMediaStorage(directory),repo=repository??new MediaRepository(db),service=new MediaService(repo,storage??local,new BinaryMediaInspector(),new Owners(),{now:()=>"2026-09-21T00:00:00.000Z"});return{directory,db,context,company,local,repo,service};}
function input(key:string){return{operation:"ingest" as const,idempotencyKey:key,declaredMediaType:"image/png",filename:"logo.png",content:content()};}

test("EPIC056 PASS2 migrates a clean database and upgrades 0076 media rows to 0078",()=>{const clean=createDatabase(":memory:");try{assert.equal((clean.prepare("SELECT name FROM schema_migrations ORDER BY id DESC LIMIT 1").get() as {name:string}).name,"0078_media_reclaim_leases");}finally{clean.close();}const directory=mkdtempSync(join(tmpdir(),"atlas-pass2-migration-")),path=join(directory,"atlas.sqlite");let db=new DatabaseSync(path);try{db.exec("PRAGMA foreign_keys=ON");runMigrations(db,76);const context=createWorkspaceContext(new WorkspaceRepository(db).resolveDefault()),company=new CompanyRepository(db).create(context,{name:"Existing",website:"https://existing.test"}),at="2026-09-21T00:00:00.000Z";db.prepare("INSERT INTO media_blobs(id,workspace_id,company_id,sha256_digest,size_bytes,media_type,storage_reference,state,created_at) VALUES(?,?,?,?,?,?,?,'active',?)").run("mbl_existing",context.workspaceId,company.id,"a".repeat(64),png.byteLength,"image/png","mbl_existing",at);db.prepare("INSERT INTO media_assets(id,workspace_id,company_id,blob_id,kind,media_type,size_bytes,safe_filename,metadata_json,status,created_at,archived_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,'ready',?,NULL,NULL)").run("mas_existing",context.workspaceId,company.id,"mbl_existing","image","image/png",png.byteLength,"logo.png","{}",at);runMigrations(db);assert.deepEqual((db.prepare("SELECT id,name FROM schema_migrations WHERE id>=76 ORDER BY id").all() as Array<{id:number;name:string}>).map(row=>({id:row.id,name:row.name})),[{id:76,name:"0076_public_web_chat_durable_turn_claims"},{id:77,name:"0077_media_durable_ingest_attempts"},{id:78,name:"0078_media_reclaim_leases"}]);assert.equal((db.prepare("SELECT status FROM media_assets WHERE id='mas_existing'").get() as {status:string}).status,"ready");assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE type='index' AND name='idx_media_ingest_attempts_recovery'").get());assert.throws(()=>db.prepare("INSERT INTO media_ingest_attempts(asset_id,workspace_id,company_id,candidate_blob_id,staging_storage_reference,final_storage_reference,sha256_digest,size_bytes,inspected_media_type,state,attempt_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'unknown',0,?,?)").run("mas_existing",context.workspaceId,company.id,"mbl_x","tmp_x","mbl_x","a".repeat(64),1,"image/png","x","x"));}finally{db.close();rmSync(directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 durably records exact references then settles asset, blob, and attempt atomically",async()=>{const v=fixture();try{const result=await v.service.store(v.context,v.company.id,input("success")),row=v.db.prepare("SELECT * FROM media_ingest_attempts WHERE asset_id=?").get(result.id) as {candidate_blob_id:string;staging_storage_reference:string;final_storage_reference:string;sha256_digest:string;size_bytes:number;inspected_media_type:string;state:string;settled_at:string|null};assert.match(row.candidate_blob_id,/^mbl_/u);assert.match(row.staging_storage_reference,/^tmp_/u);assert.equal(row.final_storage_reference,row.candidate_blob_id);assert.equal(row.sha256_digest.length,64);assert.equal(row.size_bytes,png.byteLength);assert.equal(row.inspected_media_type,"image/png");assert.equal(row.state,"settled");assert.notEqual(row.settled_at,null);assert.equal(result.status,"ready");assert.equal((await v.repo.findIngestAttempt(v.context,v.company.id,result.id))?.state,"settled");const replay=await v.service.store(v.context,v.company.id,input("success"));assert.equal(replay.id,result.id);}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 preserves staged and retryable durable evidence across pre-promotion and post-promotion failures",async()=>{const v=fixture();const failing:MediaStoragePort={plan:(id,location)=>v.local.plan(id,location),stage:(refs,body,location)=>v.local.stage(refs,body,location),readTemporary:(ref,max)=>v.local.readTemporary(ref,max),promote:async()=>{throw new MediaDomainError("media_storage_failed");},delete:ref=>v.local.delete(ref),read:(ref,max)=>v.local.read(ref,max)};const service=new MediaService(v.repo,failing,new BinaryMediaInspector(),new Owners(),{now:()=>"2026-09-21T00:00:00.000Z"});try{await assert.rejects(service.store(v.context,v.company.id,input("before-promote")),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_storage_failed");const staged=v.db.prepare("SELECT state,staging_storage_reference,final_storage_reference,candidate_blob_id,safe_failure_category FROM media_ingest_attempts").get() as {state:string;staging_storage_reference:string;final_storage_reference:string;candidate_blob_id:string;safe_failure_category:string};assert.equal(staged.state,"retryable_failure");assert.equal(staged.safe_failure_category,"media_storage_failed");assert.match(staged.staging_storage_reference,/^tmp_/u);assert.equal(staged.final_storage_reference,staged.candidate_blob_id);await assert.rejects(service.store(v.context,v.company.id,input("before-promote")),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_idempotency_retryable_failure");}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 retains promoted evidence if final SQL settlement rolls back",async()=>{const v=fixture();v.db.exec("CREATE TRIGGER fail_ready_event BEFORE INSERT ON media_asset_events WHEN NEW.event_type='ready' BEGIN SELECT RAISE(ABORT,'test settlement failure'); END;");try{await assert.rejects(v.service.store(v.context,v.company.id,input("settlement")));const row=v.db.prepare("SELECT a.status,i.state,i.final_storage_reference,i.candidate_blob_id FROM media_assets a JOIN media_ingest_attempts i ON i.asset_id=a.id").get() as {status:string;state:string;final_storage_reference:string;candidate_blob_id:string};assert.equal(row.status,"pending");assert.equal(row.state,"retryable_failure");assert.equal(row.final_storage_reference,row.candidate_blob_id);assert.equal((v.db.prepare("SELECT COUNT(*) count FROM media_blobs").get() as {count:number}).count,0);}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 scopes attempts and keeps terminal failures out of successful replays",async()=>{const v=fixture();try{await assert.rejects(v.service.store(v.context,v.company.id,{...input("bad"),declaredMediaType:"image/jpeg"}));assert.equal((v.db.prepare("SELECT COUNT(*) count FROM media_ingest_attempts").get() as {count:number}).count,0);const first=await v.service.store(v.context,v.company.id,input("scoped"));assert.equal(await v.repo.findIngestAttempt({...v.context,workspaceId:v.context.workspaceId+1},v.company.id,first.id),null);await assert.rejects(v.service.store(v.context,v.company.id,{...input("scoped"),filename:"other.png"}),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_idempotency_conflict");}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 reports terminal idempotency attempts distinctly from successful replays",async()=>{const v=fixture(),at="2026-09-21T00:00:00.000Z",asset={id:"mas_terminal",workspaceId:v.context.workspaceId,companyId:v.company.id,kind:"image" as const,mediaType:"image/png",sizeBytes:null,filename:null,metadata:{},status:"pending" as const,createdAt:at,archivedAt:null,deletedAt:null},ingest={assetId:asset.id,workspaceId:v.context.workspaceId,companyId:v.company.id,candidateBlobId:"mbl_terminal",stagingStorageReference:"tmp_terminal",finalStorageReference:"mbl_terminal",digest:"b".repeat(64),sizeBytes:1,inspectedMediaType:"image/png",state:"staged" as const,leaseOwner:null,leaseToken:null,leaseExpiresAt:null,attemptCount:0,failureCategory:null,createdAt:at,updatedAt:at,settledAt:null};try{assert.equal((await v.repo.reserve(v.context,v.company.id,"ingest","terminal","c".repeat(64),asset,ingest,at)).kind,"reserved");await v.repo.fail(v.context,v.company.id,asset.id,"media_type_mismatch",false,at);assert.equal((await v.repo.reserve(v.context,v.company.id,"ingest","terminal","c".repeat(64),asset,ingest,at)).kind,"terminal_failure");}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 crash seams retain reserved, staged, and final ownership evidence without replay identities",async()=>{for(const seam of ["afterReserved","afterStagingWrite","afterPromotion"] as const){const v=fixture(),service=new MediaService(v.repo,v.local,new BinaryMediaInspector(),new Owners(),{now:()=>"2026-09-21T00:00:00.000Z"},{[seam]:()=>{throw new MediaIngestInterrupted();}});try{await assert.rejects(service.store(v.context,v.company.id,input(`crash-${seam}`)),MediaIngestInterrupted);const row=v.db.prepare("SELECT asset_id,state,staging_storage_reference,final_storage_reference,candidate_blob_id FROM media_ingest_attempts").get() as {asset_id:string;state:string;staging_storage_reference:string;final_storage_reference:string;candidate_blob_id:string};assert.equal(row.state,seam==="afterReserved"?"reserved":seam==="afterStagingWrite"?"reserved":"staged");assert.equal(row.final_storage_reference,row.candidate_blob_id);assert.equal(existsSync(join(v.directory,row.staging_storage_reference)),seam==="afterStagingWrite");assert.equal(existsSync(join(v.directory,row.final_storage_reference)),seam==="afterPromotion");const before=v.db.prepare("SELECT COUNT(*) count FROM media_ingest_attempts").get() as {count:number};await assert.rejects(v.service.store(v.context,v.company.id,input(`crash-${seam}`)),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_idempotency_in_progress");assert.equal((v.db.prepare("SELECT COUNT(*) count FROM media_ingest_attempts").get() as {count:number}).count,before.count);}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}}});

test("EPIC056 PASS2 completed replay never replans or stages a second identity",async()=>{const v=fixture();let plans=0,stages=0;const storage:MediaStoragePort={plan:(id,location)=>{plans++;return v.local.plan(id,location);},stage:(refs,body,location)=>{stages++;return v.local.stage(refs,body,location);},readTemporary:(ref,max)=>v.local.readTemporary(ref,max),promote:(ref,id,type)=>v.local.promote(ref,id,type),delete:ref=>v.local.delete(ref),read:(ref,max)=>v.local.read(ref,max)};const service=new MediaService(v.repo,storage,new BinaryMediaInspector(),new Owners(),{now:()=>"2026-09-21T00:00:00.000Z"});try{await service.store(v.context,v.company.id,input("stable"));await service.store(v.context,v.company.id,input("stable"));assert.equal(plans,1);assert.equal(stages,1);}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 classifies upgraded 0076 pending idempotency without an attempt as legacy incomplete",async()=>{const v=fixture(),at="2026-09-21T00:00:00.000Z",fingerprint="d".repeat(64);try{v.db.prepare("INSERT INTO media_assets(id,workspace_id,company_id,blob_id,kind,media_type,size_bytes,safe_filename,metadata_json,status,created_at,archived_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,'pending',?,NULL,NULL)").run("mas_legacy",v.context.workspaceId,v.company.id,null,"image","image/png",null,null,"{}",at);v.db.prepare("INSERT INTO media_idempotency(workspace_id,company_id,operation,idempotency_key,request_fingerprint,asset_id,created_at) VALUES(?,?,?,?,?,?,?)").run(v.context.workspaceId,v.company.id,"ingest","legacy",fingerprint,"mas_legacy",at);assert.equal((await v.repo.resolve(v.context,v.company.id,"ingest","legacy",fingerprint)).kind,"legacy_incomplete");}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

async function asyncFixture(){const directory=asyncDirectory,database=createLibsqlDatabase(pathToFileURL(join(directory,"atlas.sqlite")).href,"local-test-token"),context=createWorkspaceContext({id:1,publicId:"default",key:"default",name:"Default Workspace",timezone:null,defaultLocale:"en",createdAt:"2026-09-21T00:00:00.000Z"});if(!asyncMigrationsReady){await runFreshAsyncMigrations(database);asyncMigrationsReady=true;}const sequence=++asyncCompanySequence;if(sequence===4)await database.executeScript("PRAGMA foreign_keys=OFF;DELETE FROM media_ingest_attempts;DELETE FROM media_idempotency;DELETE FROM media_assets;DELETE FROM media_blobs;PRAGMA foreign_keys=ON;");const company=await new AsyncCompanyRepository(database).create(context,{name:`Async media ${sequence}`,website:`https://async-media-${sequence}.test`});return{directory,database,context,company};}
function reservation(context:ReturnType<typeof createWorkspaceContext>,companyId:number,suffix:string){const at="2026-09-21T00:00:00.000Z",asset:MediaAsset={id:`mas_${suffix}`,workspaceId:context.workspaceId,companyId,kind:"image",mediaType:"image/png",sizeBytes:null,filename:null,metadata:{},status:"pending",createdAt:at,archivedAt:null,deletedAt:null},attempt:MediaIngestAttempt={assetId:asset.id,workspaceId:context.workspaceId,companyId,candidateBlobId:`mbl_${suffix}`,stagingStorageReference:`tmp_${suffix}`,finalStorageReference:`mbl_${suffix}`,digest:"e".repeat(64),sizeBytes:png.byteLength,inspectedMediaType:"image/png",state:"reserved",leaseOwner:null,leaseToken:null,leaseExpiresAt:null,attemptCount:0,failureCategory:null,createdAt:at,updatedAt:at,settledAt:null};return{asset,attempt,at};}
async function closeAsyncFixture(_value:Awaited<ReturnType<typeof asyncFixture>>){}

test("EPIC056 PASS2 reservation uses atomic batches rather than interactive transactions",async()=>{const v=await asyncFixture();try{let outerQueries=0,batches=0;const scoped:SqlDatabase={execute:(sql,args)=>v.database.execute(sql,args),writeBatch:async statements=>{batches+=1;return v.database.writeBatch(statements);},executeScript:script=>v.database.executeScript(script),query:async(sql,args)=>{outerQueries+=1;return v.database.query(sql,args);},transaction:async()=>{throw new Error("interactive transactions are forbidden for reservation");},close:()=>v.database.close()};const repo=new AsyncMediaRepository(scoped),first=reservation(v.context,v.company.id,"handles");assert.equal((await repo.resolve(v.context,v.company.id,"ingest","handles","f".repeat(64))).kind,"new");assert.ok(outerQueries>0);outerQueries=0;assert.equal((await repo.reserve(v.context,v.company.id,"ingest","handles","f".repeat(64),first.asset,first.attempt,first.at)).kind,"reserved");assert.equal(batches,1);assert.equal(outerQueries,1);assert.equal((await repo.resolve(v.context,v.company.id,"ingest","handles","f".repeat(64))).kind,"in_progress");}finally{await closeAsyncFixture(v);}});

test("EPIC056 PASS2 async libSQL concurrent reservations keep one durable identity",async()=>{const v=await asyncFixture(),repo=new AsyncMediaRepository(v.database),sameA=reservation(v.context,v.company.id,"same_a"),sameB=reservation(v.context,v.company.id,"same_b"),fingerprint="a".repeat(64);try{const same=await Promise.all([repo.reserve(v.context,v.company.id,"ingest","same-key",fingerprint,sameA.asset,sameA.attempt,sameA.at),repo.reserve(v.context,v.company.id,"ingest","same-key",fingerprint,sameB.asset,sameB.attempt,sameB.at)]);assert.deepEqual(new Set(same.map(result=>result.kind)),new Set(["reserved","in_progress"]));assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_assets WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:1}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_idempotency WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:1}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_ingest_attempts WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:1}]);const mismatchA=reservation(v.context,v.company.id,"mismatch_a"),mismatchB=reservation(v.context,v.company.id,"mismatch_b"),mismatch=await Promise.all([repo.reserve(v.context,v.company.id,"ingest","mismatch-key","b".repeat(64),mismatchA.asset,mismatchA.attempt,mismatchA.at),repo.reserve(v.context,v.company.id,"ingest","mismatch-key","c".repeat(64),mismatchB.asset,mismatchB.attempt,mismatchB.at)]);assert.deepEqual(new Set(mismatch.map(result=>result.kind)),new Set(["reserved","divergent"]));assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_assets WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:2}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_idempotency WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:2}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_ingest_attempts WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:2}]);}finally{await closeAsyncFixture(v);}});

test("EPIC056 PASS2 async separate libSQL facades reconcile reservation races from committed state",async()=>{const v=await asyncFixture(),other=createLibsqlDatabase(pathToFileURL(join(v.directory,"atlas.sqlite")).href,"local-test-token"),first=new AsyncMediaRepository(v.database),second=new AsyncMediaRepository(other),sameA=reservation(v.context,v.company.id,"facade_same_a"),sameB=reservation(v.context,v.company.id,"facade_same_b");try{const same=await Promise.all([first.reserve(v.context,v.company.id,"ingest","facade-same","a".repeat(64),sameA.asset,sameA.attempt,sameA.at),second.reserve(v.context,v.company.id,"ingest","facade-same","a".repeat(64),sameB.asset,sameB.attempt,sameB.at)]);assert.deepEqual(new Set(same.map(result=>result.kind)),new Set(["reserved","in_progress"]));assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_assets WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:1}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_idempotency WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:1}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_ingest_attempts WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:1}]);const mismatchA=reservation(v.context,v.company.id,"facade_mismatch_a"),mismatchB=reservation(v.context,v.company.id,"facade_mismatch_b"),mismatch=await Promise.all([first.reserve(v.context,v.company.id,"ingest","facade-mismatch","b".repeat(64),mismatchA.asset,mismatchA.attempt,mismatchA.at),second.reserve(v.context,v.company.id,"ingest","facade-mismatch","c".repeat(64),mismatchB.asset,mismatchB.attempt,mismatchB.at)]);assert.deepEqual(new Set(mismatch.map(result=>result.kind)),new Set(["reserved","divergent"]));assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_assets WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:2}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_idempotency WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:2}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_ingest_attempts WHERE workspace_id=? AND company_id=?",[v.context.workspaceId,v.company.id]),[{count:2}]);}finally{await other.close();await closeAsyncFixture(v);}});

test("EPIC056 PASS2 reconciles governed rows and normalizes exhausted contention",async()=>{const v=fixture(),database=new SynchronousSqlDatabaseAdapter(v.db),first=reservation(v.context,v.company.id,"reconcile"),stored=await v.repo.reserve(v.context,v.company.id,"ingest","reconcile","d".repeat(64),first.asset,first.attempt,first.at),blocked:SqlDatabase={execute:(sql,args)=>database.execute(sql,args),writeBatch:async()=>{throw Object.assign(new Error("SQLITE_BUSY: database is locked"),{code:"SQLITE_BUSY"});},executeScript:script=>database.executeScript(script),query:(sql,args)=>database.query(sql,args),transaction:operation=>database.transaction(operation),close:()=>Promise.resolve()},repo=new AsyncMediaRepository(blocked),second=reservation(v.context,v.company.id,"blocked");try{assert.equal(stored.kind,"reserved");assert.equal((await repo.reserve(v.context,v.company.id,"ingest","reconcile","d".repeat(64),second.asset,second.attempt,second.at)).kind,"in_progress");await assert.rejects(repo.reserve(v.context,v.company.id,"ingest","absent","e".repeat(64),second.asset,second.attempt,second.at),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_storage_failed"&&!error.message.includes("SQLITE_BUSY"));}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 retains promoted evidence before final settlement begins",async()=>{const v=fixture(),service=new MediaService(v.repo,v.local,new BinaryMediaInspector(),new Owners(),{now:()=>"2026-09-21T00:00:00.000Z"},{afterPromoted:()=>{throw new MediaIngestInterrupted();}});try{await assert.rejects(service.store(v.context,v.company.id,input("promoted-crash")),MediaIngestInterrupted);const row=v.db.prepare("SELECT a.status,i.state,i.candidate_blob_id,i.staging_storage_reference,i.final_storage_reference FROM media_assets a JOIN media_ingest_attempts i ON i.asset_id=a.id").get() as {status:string;state:string;candidate_blob_id:string;staging_storage_reference:string;final_storage_reference:string};assert.equal(row.status,"pending");assert.equal(row.state,"promoted");assert.equal(row.final_storage_reference,row.candidate_blob_id);assert.ok(existsSync(join(v.directory,row.final_storage_reference)));assert.equal((v.db.prepare("SELECT COUNT(*) count FROM media_blobs").get() as {count:number}).count,0);await assert.rejects(service.store(v.context,v.company.id,input("promoted-crash")),(error:unknown)=>error instanceof MediaDomainError&&error.code==="media_idempotency_in_progress");assert.equal((v.db.prepare("SELECT COUNT(*) count FROM media_ingest_attempts").get() as {count:number}).count,1);}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 rolls back every reservation write when the reserved event fails",async()=>{const v=fixture();v.db.exec("CREATE TRIGGER fail_reserved_event BEFORE INSERT ON media_asset_events WHEN NEW.event_type='reserved' BEGIN SELECT RAISE(ABORT,'forced reservation failure'); END;");try{await assert.rejects(v.service.store(v.context,v.company.id,input("rollback")));for(const table of ["media_assets","media_idempotency","media_ingest_attempts","media_asset_events"]){assert.equal((v.db.prepare(`SELECT COUNT(*) count FROM ${table}`).get() as {count:number}).count,0);}}finally{v.db.close();rmSync(v.directory,{recursive:true,force:true});}});

test("EPIC056 PASS2 repeats two-facade batch races without local coordination",async()=>{const v=await asyncFixture(),other=createLibsqlDatabase(pathToFileURL(join(v.directory,"atlas.sqlite")).href,"local-test-token"),first=new AsyncMediaRepository(v.database),second=new AsyncMediaRepository(other);try{for(let index=0;index<20;index+=1){const sameA=reservation(v.context,v.company.id,`stress_same_a_${index}`),sameB=reservation(v.context,v.company.id,`stress_same_b_${index}`),same=await Promise.all([first.reserve(v.context,v.company.id,"ingest",`stress-same-${index}`,"a".repeat(64),sameA.asset,sameA.attempt,sameA.at),second.reserve(v.context,v.company.id,"ingest",`stress-same-${index}`,"a".repeat(64),sameB.asset,sameB.attempt,sameB.at)]);assert.deepEqual(new Set(same.map(value=>value.kind)),new Set(["reserved","in_progress"]));const differentA=reservation(v.context,v.company.id,`stress_different_a_${index}`),differentB=reservation(v.context,v.company.id,`stress_different_b_${index}`),different=await Promise.all([first.reserve(v.context,v.company.id,"ingest",`stress-different-${index}`,"b".repeat(64),differentA.asset,differentA.attempt,differentA.at),second.reserve(v.context,v.company.id,"ingest",`stress-different-${index}`,"c".repeat(64),differentB.asset,differentB.attempt,differentB.at)]);assert.deepEqual(new Set(different.map(value=>value.kind)),new Set(["reserved","divergent"]));}assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_assets"),[{count:40}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_idempotency"),[{count:40}]);assert.deepEqual(await v.database.query<{count:number}>("SELECT COUNT(*) count FROM media_ingest_attempts"),[{count:40}]);}finally{await closeAsyncFixture(v);}});
