import assert from "node:assert/strict";
import { test } from "node:test";
import { createServer, request as httpRequest, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import { SecurePublicUrlProvider, createSafeLookup, type ConnectionLookup } from "../knowledge/infrastructure/publicUrlProvider.js";
import { KnowledgeDomainError, KNOWLEDGE_LIMITS } from "../knowledge/domain/knowledge.js";

const loopbackLookup:ConnectionLookup=(_hostname,options,callback)=>callback(null,typeof options==="object"&&options&&(options as{all?:boolean}).all?[{address:"127.0.0.1",family:4}]:"127.0.0.1",4);
async function withServer(run:(provider:SecurePublicUrlProvider,base:string,calls:()=>number)=>Promise<void>):Promise<void>{let count=0;const server=createServer((req,res)=>{count++;route(req.url??"/",res);});await new Promise<void>((resolve,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",resolve);});const port=(server.address()as AddressInfo).port,provider=new SecurePublicUrlProvider({connectionLookup:loopbackLookup,allowedPorts:[port],timeoutMilliseconds:250});try{await run(provider,`http://public.test:${port}`,()=>count);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}}
function route(path:string,res:ServerResponse):void{if(path==="/text"){res.writeHead(200,{"content-type":"text/plain"});res.end("Atlas facts");return;}if(path==="/html"){res.writeHead(200,{"content-type":"text/html"});res.end('<a href="/second">second</a>Atlas');return;}if(path==="/redirect"){res.writeHead(302,{location:"/text"});res.end();return;}if(path==="/downgrade"){res.writeHead(302,{location:"http://public.test/text"});res.end();return;}if(path.startsWith("/loop/")){const next=Number(path.split("/").at(-1))+1;res.writeHead(302,{location:`/loop/${next}`});res.end();return;}if(path==="/wrong"){res.writeHead(200,{"content-type":"application/json"});res.end("{}");return;}if(path==="/encoded"){res.writeHead(200,{"content-type":"text/plain","content-encoding":"gzip"});res.end("encoded");return;}if(path==="/large"){res.writeHead(200,{"content-type":"text/plain"});res.end(Buffer.alloc(KNOWLEDGE_LIMITS.urlResponseBytes+1,65));return;}if(path==="/slow"){setTimeout(()=>{res.writeHead(200,{"content-type":"text/plain"});res.end("late");},100);return;}res.writeHead(404);res.end();}

test("actual URL adapter follows validated redirects and fetches exactly one page",async()=>withServer(async(provider,base,calls)=>{const redirected=await provider.acquire(`${base}/redirect`,new AbortController().signal);assert.equal(redirected.text,"Atlas facts");assert.equal(redirected.finalUrl,`${base}/text`);const before=calls(),html=await provider.acquire(`${base}/html`,new AbortController().signal);assert.match(html.text,/second/);assert.equal(calls(),before+1);}));
test("actual URL adapter rejects redirect overflow, media, encoding and streaming overflow",async()=>withServer(async(provider,base)=>{await assert.rejects(provider.acquire(`${base}/loop/0`,new AbortController().signal),(error:unknown)=>error instanceof KnowledgeDomainError&&error.code==="url_redirect_limit");await assert.rejects(provider.acquire(`${base}/wrong`,new AbortController().signal),(error:unknown)=>error instanceof KnowledgeDomainError&&error.code==="url_media_type_unsupported");await assert.rejects(provider.acquire(`${base}/encoded`,new AbortController().signal),(error:unknown)=>error instanceof KnowledgeDomainError&&error.code==="url_content_encoding_unsupported");await assert.rejects(provider.acquire(`${base}/large`,new AbortController().signal),(error:unknown)=>error instanceof KnowledgeDomainError&&error.code==="knowledge_input_too_large");}));
test("actual URL adapter enforces request timeout and caller abort",async()=>withServer(async(_provider,base)=>{const port=Number(new URL(base).port),provider=new SecurePublicUrlProvider({connectionLookup:loopbackLookup,allowedPorts:[port],timeoutMilliseconds:25});await assert.rejects(provider.acquire(`${base}/slow`,new AbortController().signal),KnowledgeDomainError);const controller=new AbortController(),pending=provider.acquire(`${base}/slow`,controller.signal);controller.abort();await assert.rejects(pending); }));
test("safe connection lookup rejects mixed and rebound private DNS results",async()=>{let call=0;const lookup=createSafeLookup((_hostname,_options,callback)=>{call++;callback(null,call===1?[{address:"8.8.8.8",family:4},{address:"127.0.0.1",family:4}]:[{address:"10.0.0.1",family:4}]);});for(let index=0;index<2;index++)await new Promise<void>(resolve=>lookup("public.test",{},error=>{assert.equal(error?.code,"EACCES");resolve();}));});
test("adapter ignores proxy environment because direct HTTP transport owns the connection",async()=>{const previous=process.env.HTTP_PROXY;process.env.HTTP_PROXY="http://127.0.0.1:1";try{await withServer(async(provider,base)=>assert.equal((await provider.acquire(`${base}/text`,new AbortController().signal)).text,"Atlas facts"));}finally{if(previous===undefined)delete process.env.HTTP_PROXY;else process.env.HTTP_PROXY=previous;}});

test("actual provider rejects mixed DNS and rebinding on provider connections",async()=>withServer(async(_provider,base)=>{const port=Number(new URL(base).port),mixed=new SecurePublicUrlProvider({allowedPorts:[port],connectionLookup:createSafeLookup((_host,_options,callback)=>callback(null,[{address:"8.8.8.8",family:4},{address:"127.0.0.1",family:4}]))});await assert.rejects(mixed.acquire(`${base}/text`,new AbortController().signal),KnowledgeDomainError);let calls=0;const rebound=new SecurePublicUrlProvider({allowedPorts:[port],connectionLookup:(host,options,callback)=>{calls++;if(calls===1)return loopbackLookup(host,options,callback);callback(Object.assign(new Error("rebound"),{code:"EACCES"}),"",0);}});await assert.rejects(rebound.acquire(`${base}/redirect`,new AbortController().signal),KnowledgeDomainError);assert.equal(calls,2);}));
test("actual provider exercises and rejects the HTTPS downgrade fixture",async()=>withServer(async(_provider,base)=>{const port=Number(new URL(base).port),provider=new SecurePublicUrlProvider({allowedPorts:[port],connectionLookup:loopbackLookup,requestFactory:(url,options,callback)=>httpRequest(new URL(`http://127.0.0.1:${port}${url.pathname}`),{...options,lookup:undefined},callback)});await assert.rejects(provider.acquire(`https://public.test:${port}/downgrade`,new AbortController().signal),(error:unknown)=>error instanceof KnowledgeDomainError&&error.code==="invalid_public_url");}));
test("actual provider rejects complete literal special-use address classes before transport",async()=>{for(const address of["0.0.0.0","10.0.0.1","100.64.0.1","127.0.0.1","169.254.0.1","172.16.0.1","192.0.0.1","192.0.2.1","192.31.196.1","192.52.193.1","192.88.99.1","192.168.0.1","192.175.48.1","198.18.0.1","198.51.100.1","203.0.113.1","224.0.0.1","240.0.0.1","::","::1","::ffff:127.0.0.1","fc00::1","fe80::1","fec0::1","ff00::1","2001:db8::1","2002::1"]){const host=address.includes(":")?`[${address}]`:address;await assert.rejects(new SecurePublicUrlProvider().acquire(`http://${host}/`,new AbortController().signal),KnowledgeDomainError);}});
