import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { assistantProfileId, reconstructAssistantProfile, type AssistantProfile } from "../assistant/domain/assistantProfile.js";
import { createDatabase } from "../config/database.js";
import { ConversationService } from "../conversation/services/conversationService.js";
import { AssistantProfileRepository } from "../repositories/assistantProfileRepository.js";
import { CompanyRepository } from "../repositories/companyRepository.js";
import { ConversationRepository } from "../repositories/conversationRepository.js";
import { WebChatConnectionRepository } from "../repositories/webChatConnectionRepository.js";
import { WebChatSessionRepository } from "../repositories/webChatSessionRepository.js";
import { WorkspaceRepository } from "../repositories/workspaceRepository.js";
import { createWorkspaceContext } from "../types/workspaceContext.js";
import { WebChatConnectionService } from "../webChat/services/webChatConnectionService.js";
import { PublicWebChatSessionService } from "../webChat/services/publicWebChatSessionService.js";

class Clock { public value = "2026-07-25T12:00:00.000Z"; public now(): string { return this.value; } }
function digest(raw: string): string { return createHash("sha256").update(raw).digest("hex"); }
function ready(companyId: number): AssistantProfile { return reconstructAssistantProfile({ id: assistantProfileId("asp_0123456789abcdef0123456789abcdef"), companyId, name: "Web", normalizedName: "web", description: null, businessRole: "Advisor", objective: "Help", audience: null, tone: "friendly", assistantLanguage: "en", welcomeMessage: "Welcome", fallbackMessage: "Fallback", status: "ready", createdAt: "2026-07-25T12:00:00.000Z", updatedAt: "2026-07-25T12:00:00.000Z", archivedAt: null }); }
async function setup() { const database = createDatabase(":memory:"), clock = new Clock(), workspaces = new WorkspaceRepository(database), context = createWorkspaceContext(workspaces.resolveDefault()), companies = new CompanyRepository(database), company = companies.create(context, { name: "Web", website: "https://web.test" }), profiles = new AssistantProfileRepository(database), profile = ready(company.id); profiles.create(context, company.id, profile); const connections = new WebChatConnectionService(companies, profiles, new WebChatConnectionRepository(database), clock), connection = await connections.create(context, company.id, { assistantProfileId: profile.id }), conversations = new ConversationService(new ConversationRepository(database), clock), sessions = new WebChatSessionRepository(database), service = new PublicWebChatSessionService(connections, conversations, sessions, clock); return { database, clock, context, company, connection, connections, sessions, service }; }

test("EPIC-016.5 creates an opaque anonymous session with a Conversation and neutral Participants", async () => { const { database, connection, service, sessions } = await setup(); try { const started = await service.start(connection.publicId, null), stored = sessions.findByTokenDigest(digest(started.rawToken)); assert.equal(started.state, "active"); assert.match(started.rawToken, /^[A-Za-z0-9_-]{43}$/); assert.ok(stored); assert.notEqual(stored!.tokenDigest, started.rawToken); assert.equal((database.prepare("SELECT COUNT(*) count FROM conversations").get() as { count: number }).count, 1); assert.equal((database.prepare("SELECT COUNT(*) count FROM conversation_participants").get() as { count: number }).count, 2); assert.equal((await service.resolveSession(started.rawToken))?.conversationId, stored!.conversationId); } finally { database.close(); } });
test("EPIC-016.5 resumes only active sessions and lazily expires or blocks inactive Connections", async () => { const { database, clock, context, company, connection, connections, service, sessions } = await setup(); try { const started = await service.start(connection.publicId, null), resumed = await service.start(connection.publicId, started.rawToken); assert.equal(resumed.rawToken, started.rawToken); assert.equal((database.prepare("SELECT COUNT(*) count FROM web_chat_sessions").get() as { count: number }).count, 1); await connections.setStatus(context, company.id, connection.id, { status: "inactive" }); assert.equal(await service.resolveSession(started.rawToken), null); await connections.setStatus(context, company.id, connection.id, { status: "active" }); clock.value = "2026-07-27T12:00:00.000Z"; assert.equal(await service.resolveSession(started.rawToken), null); assert.equal(sessions.findByTokenDigest(digest(started.rawToken))?.state, "expired"); } finally { database.close(); } });
test("EPIC-016.5 closes a matching session idempotently after its Connection becomes inactive", async () => { const { database, context, company, connection, connections, service, sessions } = await setup(); try { const started = await service.start(connection.publicId, null); await connections.setStatus(context, company.id, connection.id, { status: "inactive" }); await service.close(connection.publicId, started.rawToken); await service.close(connection.publicId, started.rawToken); assert.equal(sessions.findForCloseByTokenDigest(digest(started.rawToken), connection.publicId)?.state, "closed"); assert.equal((database.prepare("SELECT COUNT(*) count FROM conversations").get() as { count: number }).count, 1); assert.equal((database.prepare("SELECT COUNT(*) count FROM conversation_participants").get() as { count: number }).count, 2); } finally { database.close(); } });
