import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { runMigrations } from "../config/migrations.js";
import { DeterministicFakeBillingProvider } from "../billing/application/billingProvider.js";
import { BillingProviderRegistry } from "../billing/application/billingProviderRegistry.js";
import { PlatformAdministrationService } from "../platformAdmin/services/platformAdministrationService.js";
import { BillingCatalogAdministrationRepository } from "../repositories/billingCatalogAdministrationRepository.js";
import { CatalogConflictError, CatalogValidationError } from "../repositories/billingCatalogAdministrationRepository.js";
import { PlatformAdministrationRepository } from "../repositories/platformAdministrationRepository.js";

const actor="usr_admin";
function open():DatabaseSync{const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");runMigrations(db);db.prepare("INSERT INTO users(id,status,locale,created_at,updated_at) VALUES(?,'active','en','2026-01-01','2026-01-01')").run(actor);return db;}
function planInput(operationId:string){return{operationId,planKey:"atlas",catalogVersion:1,displayName:"Atlas",description:"",inclusions:["knowledge"],maxCompanies:1,maxAssistantProfiles:1,maxActiveChannels:1,mutationEligible:true,trialDurationDays:null,graceDurationDays:null};}
function offerInput(operationId:string,expectedVersion:number){return{operationId,expectedVersion,providerKind:"stripe" as const,amountMinor:1000,interval:"month" as const,providerPlanReference:"price_atlas",readinessState:"not_configured" as const};}

test("EPIC052 PASS2 records not_configured without contacting an absent provider",async()=>{const db=open();try{const catalog=new BillingCatalogAdministrationRepository(db),service=new PlatformAdministrationService(new PlatformAdministrationRepository(db),undefined,catalog,new BillingProviderRegistry());const plan=service.createBillingPlan(actor,planInput("create"));const offer=service.addBillingOffer(actor,plan.id,offerInput("offer",plan.version));const saved=await service.validateBillingOffer(actor,plan.id,offer.id,{operationId:"validate",expectedVersion:catalog.find(plan.id)!.version,expectedOfferVersion:offer.version});assert.equal(saved.readinessState,"not_configured");assert.equal(catalog.find(plan.id)!.version,3);}finally{db.close();}});

test("EPIC052 PASS2 records provider unavailability safely and promotes published prices through a new draft",async()=>{const db=open();try{const catalog=new BillingCatalogAdministrationRepository(db),unavailable=new DeterministicFakeBillingProvider({kind:"success",providerObjectId:"unused"},undefined,undefined,{kind:"unavailable"}),service=new PlatformAdministrationService(new PlatformAdministrationRepository(db),undefined,catalog,new BillingProviderRegistry([{kind:"stripe",provider:unavailable}]));const plan=service.createBillingPlan(actor,planInput("create"));const offer=service.addBillingOffer(actor,plan.id,offerInput("offer",plan.version));const unavailableOffer=await service.validateBillingOffer(actor,plan.id,offer.id,{operationId:"validate",expectedVersion:catalog.find(plan.id)!.version,expectedOfferVersion:offer.version});assert.equal(unavailableOffer.readinessState,"unavailable");const ready=new DeterministicFakeBillingProvider();const readyService=new PlatformAdministrationService(new PlatformAdministrationRepository(db),undefined,catalog,new BillingProviderRegistry([{kind:"stripe",provider:ready}]));const checked=await readyService.validateBillingOffer(actor,plan.id,offer.id,{operationId:"retry",expectedVersion:catalog.find(plan.id)!.version,expectedOfferVersion:unavailableOffer.version});const published=readyService.publishBillingPlan(actor,plan.id,{operationId:"publish",expectedVersion:catalog.find(plan.id)!.version});assert.equal(checked.readinessState,"ready");assert.equal(published.publicationState,"published");const next=readyService.nextBillingPlanVersion(actor,plan.id,{operationId:"reprice",expectedVersion:published.version});assert.equal(next.publicationState,"draft");assert.equal(next.catalogVersion,2);assert.equal(catalog.offers(next.id).length,0);assert.equal(catalog.find(plan.id)!.publicationState,"published");}finally{db.close();}});

test("EPIC052 PASS2 makes catalog commands idempotent and rejects reused operation identifiers with a different request",()=>{const db=open();try{const catalog=new BillingCatalogAdministrationRepository(db),service=new PlatformAdministrationService(new PlatformAdministrationRepository(db),undefined,catalog);const input=planInput("create");const created=service.createBillingPlan(actor,input);const replay=service.createBillingPlan(actor,input);assert.deepEqual(replay,created);assert.equal(catalog.list().length,1);assert.throws(()=>service.createBillingPlan(actor,{...input,displayName:"Changed"}),CatalogConflictError);assert.equal(catalog.audit(created.id).length,1);assert.equal(catalog.audit(created.id)[0]?.eventType,"plan_draft_created");}finally{db.close();}});

test("EPIC052 PASS2 only permits valid draft terms and rejects stale or malformed offer changes atomically",()=>{const db=open();try{const catalog=new BillingCatalogAdministrationRepository(db),service=new PlatformAdministrationService(new PlatformAdministrationRepository(db),undefined,catalog);const plan=service.createBillingPlan(actor,planInput("create"));assert.throws(()=>service.updateBillingPlanDraft(actor,plan.id,{...planInput("update"),expectedVersion:plan.version,planKey:"changed",catalogVersion:1}),CatalogConflictError);assert.throws(()=>service.addBillingOffer(actor,plan.id,{...offerInput("bad",plan.version),amountMinor:0}),CatalogValidationError);assert.equal(catalog.offers(plan.id).length,0);const offer=service.addBillingOffer(actor,plan.id,offerInput("offer",plan.version));assert.throws(()=>service.updateBillingOfferDraft(actor,plan.id,offer.id,{...offerInput("update",plan.version+1),expectedOfferVersion:offer.version,providerKind:"mercadopago"}),CatalogConflictError);assert.equal(catalog.offers(plan.id)[0]?.providerKind,"stripe");assert.equal(catalog.find(plan.id)?.version,2);}finally{db.close();}});

test("EPIC052 PASS2 persists each provider validation result and gives the provider only public commercial terms",async()=>{const db=open();try{const catalog=new BillingCatalogAdministrationRepository(db);let received:unknown=null;const provider=new DeterministicFakeBillingProvider({kind:"success",providerObjectId:"unused"},undefined,undefined,{kind:"invalid"});provider.validateCommercialOffer=async input=>{received=input;return{kind:"invalid"};};const service=new PlatformAdministrationService(new PlatformAdministrationRepository(db),undefined,catalog,new BillingProviderRegistry([{kind:"stripe",provider}]));const plan=service.createBillingPlan(actor,planInput("create"));const offer=service.addBillingOffer(actor,plan.id,offerInput("offer",plan.version));const validated=await service.validateBillingOffer(actor,plan.id,offer.id,{operationId:"validate",expectedVersion:2,expectedOfferVersion:1});assert.equal(validated.readinessState,"invalid");assert.deepEqual(received,{catalogReference:"price_atlas",currency:"USD",amountMinor:1000,interval:"month"});assert.equal(validated.version,2);assert.equal(catalog.find(plan.id)?.version,3);}finally{db.close();}});

test("EPIC052 PASS2 publishes only ready offers, sells them immutably, and retires the complete catalog version",async()=>{const db=open();try{const catalog=new BillingCatalogAdministrationRepository(db),service=new PlatformAdministrationService(new PlatformAdministrationRepository(db),undefined,catalog,new BillingProviderRegistry([{kind:"stripe",provider:new DeterministicFakeBillingProvider()}]));const plan=service.createBillingPlan(actor,planInput("create"));const offer=service.addBillingOffer(actor,plan.id,offerInput("offer",plan.version));assert.throws(()=>service.publishBillingPlan(actor,plan.id,{operationId:"publish-early",expectedVersion:2}),CatalogConflictError);const ready=await service.validateBillingOffer(actor,plan.id,offer.id,{operationId:"validate",expectedVersion:2,expectedOfferVersion:1});const published=service.publishBillingPlan(actor,plan.id,{operationId:"publish",expectedVersion:3});assert.equal(published.publicationState,"published");assert.equal(catalog.offers(plan.id)[0]?.lifecycle,"sellable");assert.throws(()=>service.updateBillingOfferDraft(actor,plan.id,offer.id,{...offerInput("change",published.version),expectedOfferVersion:ready.version}),CatalogConflictError);const retired=service.retireBillingPlan(actor,plan.id,{operationId:"retire",expectedVersion:published.version});assert.equal(retired.publicationState,"retired");assert.equal(catalog.offers(plan.id)[0]?.lifecycle,"retired");assert.equal(catalog.audit(plan.id).map(value=>value.eventType).sort().join(","),"plan_draft_created,plan_published,plan_retired,provider_offer_created,provider_offer_validated");}finally{db.close();}});
