import assert from "node:assert/strict";
import test from "node:test";
import { createDatabase } from "../config/database.js";
import { PasswordPolicy, BuiltInCommonPasswordBlocklist } from "../identity/domain/authentication.js";
import { reconstructUser } from "../identity/domain/user.js";
import { ScryptPasswordProvider, SecureRandomProvider, Sha256CredentialEnrollmentHashProvider, Sha256SessionIdentifierProvider } from "../identity/infrastructure/securityProviders.js";
import { SystemClock } from "../identity/infrastructure/systemClock.js";
import { AuthenticationFailure, AuthenticationService } from "../identity/services/authenticationService.js";
import { SqliteAuthenticationTransaction } from "../repositories/identityTransaction.js";
import { UserRepository } from "../repositories/userRepository.js";
import type { CredentialEnrollmentDeliveryPort, CredentialEnrollmentDeliveryRequest } from "../identity/application/ports.js";

class Delivery implements CredentialEnrollmentDeliveryPort { public request:CredentialEnrollmentDeliveryRequest|null=null; public async deliver(request:CredentialEnrollmentDeliveryRequest){this.request=request;return "accepted" as const;} }
function setup(){const database=createDatabase(":memory:");const now="2026-07-16T12:00:00.000Z";new UserRepository(database).create(reconstructUser({id:"usr_test",status:"active",locale:"en",authenticationIdentities:[{id:"aid_test",email:"person@example.com",normalizedEmail:"person@example.com",emailVerified:true,createdAt:now,updatedAt:now}],createdAt:now,updatedAt:now}));const delivery=new Delivery();const service=new AuthenticationService(new SqliteAuthenticationTransaction(database),new SecureRandomProvider(),new Sha256CredentialEnrollmentHashProvider(),new ScryptPasswordProvider(),new Sha256SessionIdentifierProvider(),new SystemClock(),delivery,"http://localhost:5173",false);return{database,delivery,service};}

test("password policy counts Unicode code points, permits spaces, and rejects mismatch and common values",()=>{const policy=new PasswordPolicy(new BuiltInCommonPasswordBlocklist());assert.doesNotThrow(()=>policy.validate("frase larga 🔐 segura","frase larga 🔐 segura"));assert.throws(()=>policy.validate("short","short"));assert.throws(()=>policy.validate("frase larga segura","different value"));assert.throws(()=>policy.validate("password123456","password123456"));assert.throws(()=>policy.validate("x".repeat(129),"x".repeat(129)));});

test("scrypt is asynchronous, salted, safely verifies, and session identifiers are opaque",async()=>{const provider=new ScryptPasswordProvider();const first=await provider.protect("frase larga 🔐 segura");const second=await provider.protect("frase larga 🔐 segura");assert.notEqual(first.salt,second.salt);assert.notEqual(first.confirmation,second.confirmation);assert.equal((await provider.verify("frase larga 🔐 segura",first)).matches,true);assert.equal((await provider.verify("wrong password value",first)).matches,false);await provider.dummyVerify("unknown password value");const identifiers=new Sha256SessionIdentifierProvider();const value=identifiers.create();assert.equal(Buffer.from(value.raw,"base64url").byteLength,32);assert.notEqual(value.raw,value.digest);assert.equal(identifiers.parse(value.raw)?.digest,value.digest);});

test("enrollment, login, current identity, rotation, replacement and logout create no Workspace authority",async()=>{const{database,delivery,service}=setup();await service.requestEnrollment("PERSON@example.com");assert.ok(delivery.request);const proof=new URL(delivery.request.enrollmentUrl).searchParams.get("proof")!;await service.completeEnrollment(proof,"frase larga 🔐 segura","frase larga 🔐 segura");await assert.rejects(()=>service.completeEnrollment(proof,"frase larga 🔐 segura","frase larga 🔐 segura"),AuthenticationFailure);assert.equal((database.prepare("SELECT COUNT(*) AS count FROM sessions").get() as {count:number}).count,0);const login=await service.login("person@example.com","frase larga 🔐 segura","loopback");assert.ok(database.prepare("SELECT identifier_digest FROM sessions").get());assert.equal(JSON.stringify(database.prepare("SELECT * FROM sessions").get()).includes(login.rawIdentifier),false);const current=service.current(login.rawIdentifier);assert.equal(current?.email,"person@example.com");assert.equal("workspaceId" in (current??{}),false);const rotated=service.refresh(login.rawIdentifier);assert.equal(service.current(login.rawIdentifier),null);assert.ok(service.current(rotated.rawIdentifier));await service.replacePassword(rotated.rawIdentifier,"frase larga 🔐 segura","otra frase 🔐 muy segura","otra frase 🔐 muy segura");assert.equal(service.current(rotated.rawIdentifier),null);await assert.rejects(()=>service.login("person@example.com","frase larga 🔐 segura","loopback"),AuthenticationFailure);const relogin=await service.login("person@example.com","otra frase 🔐 muy segura","loopback");service.logout(relogin.rawIdentifier);assert.equal(service.current(relogin.rawIdentifier),null);database.close();});

test("migration 5 is additive, indexed, restart safe, and bootstraps no authentication state",()=>{const database=createDatabase(":memory:");assert.equal((database.prepare("SELECT COUNT(*) AS count FROM schema_migrations").get() as {count:number}).count,10);for(const table of ["password_credentials","credential_enrollments","sessions","login_throttles"])assert.equal((database.prepare(`SELECT COUNT(*) AS count FROM ${table}`).get() as {count:number}).count,0);const indexes=(database.prepare("SELECT name FROM sqlite_master WHERE type='index'").all() as Array<{name:string}>).map(x=>x.name);assert.ok(indexes.includes("idx_sessions_digest"));assert.ok(indexes.includes("idx_credential_enrollments_digest"));assert.deepEqual(database.prepare("PRAGMA foreign_key_check").all(),[]);database.close();});
