import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import { assistantProfileId } from "../../assistant/domain/assistantProfile.js";
import type { AsyncWhatsAppConnectionCredentialRepositoryPort, AsyncWhatsAppConnectionOperationalStateRepositoryPort, AsyncWhatsAppConnectionRepositoryPort, AsyncWhatsAppLinkedIntegrationCredentialRepositoryPort } from "../application/ports.js";
import { reconstructWhatsAppConnection, whatsAppConnectionId, type WhatsAppConnection, type WhatsAppConnectionId, type WhatsAppConnectionStatus } from "../domain/whatsappConnection.js";
import { reconstructEncryptedWhatsAppConnectionCredentials, reconstructWhatsAppConnectionOperationalState, type EncryptedWhatsAppConnectionCredentials, type WhatsAppConnectionOperationalState } from "../domain/whatsappConnectionOnboarding.js";

type ConnectionRow={id:string;workspace_id:number;company_id:number;assistant_profile_id:string;phone_number_id:string;whatsapp_business_account_id:string;status:WhatsAppConnectionStatus;created_at:string;updated_at:string};
type CredentialRow={whatsapp_connection_id:string;encrypted_access_token:string;created_at:string;updated_at:string};
type OperationalStateRow={whatsapp_connection_id:string;validation_state:WhatsAppConnectionOperationalState["validationState"];validated_at:string|null;validation_failure_code:WhatsAppConnectionOperationalState["validationFailureCode"];health_state:WhatsAppConnectionOperationalState["healthState"];last_provider_activity_at:string|null;last_webhook_activity_at:string|null;health_failure_code:WhatsAppConnectionOperationalState["healthFailureCode"];updated_at:string};
const connection=(row:ConnectionRow):WhatsAppConnection=>reconstructWhatsAppConnection({id:row.id as WhatsAppConnectionId,workspaceId:row.workspace_id,companyId:row.company_id,assistantProfileId:assistantProfileId(row.assistant_profile_id),phoneNumberId:row.phone_number_id,whatsappBusinessAccountId:row.whatsapp_business_account_id,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at});
const credentials=(row:CredentialRow):EncryptedWhatsAppConnectionCredentials=>reconstructEncryptedWhatsAppConnectionCredentials({whatsAppConnectionId:whatsAppConnectionId(row.whatsapp_connection_id),encryptedAccessToken:row.encrypted_access_token,createdAt:row.created_at,updatedAt:row.updated_at});
const operationalState=(row:OperationalStateRow):WhatsAppConnectionOperationalState=>reconstructWhatsAppConnectionOperationalState({whatsAppConnectionId:whatsAppConnectionId(row.whatsapp_connection_id),validationState:row.validation_state,validatedAt:row.validated_at,validationFailureCode:row.validation_failure_code,healthState:row.health_state,lastProviderActivityAt:row.last_provider_activity_at,lastWebhookActivityAt:row.last_webhook_activity_at,healthFailureCode:row.health_failure_code,updatedAt:row.updated_at});

export class AsyncWhatsAppConnectionPersistence implements AsyncWhatsAppConnectionRepositoryPort, AsyncWhatsAppConnectionCredentialRepositoryPort, AsyncWhatsAppConnectionOperationalStateRepositoryPort, AsyncWhatsAppLinkedIntegrationCredentialRepositoryPort {
  public constructor(private readonly database:SqlDatabase) {}
  public async create(context:WorkspaceContext,value:WhatsAppConnection):Promise<WhatsAppConnection|null>{const result=await this.database.execute("INSERT INTO whatsapp_connections(id,workspace_id,company_id,assistant_profile_id,phone_number_id,whatsapp_business_account_id,status,created_at,updated_at) SELECT ?,c.workspace_id,c.id,p.id,?,?,?,?,? FROM companies c JOIN assistant_profiles p ON p.id=? AND p.company_id=c.id WHERE c.workspace_id=? AND c.id=? AND c.workspace_id=?",[value.id,value.phoneNumberId,value.whatsappBusinessAccountId,value.status,value.createdAt,value.updatedAt,value.assistantProfileId,context.workspaceId,value.companyId,value.workspaceId]);return Number(result.rowsAffected)===1?this.findById(context,value.companyId,value.id):null;}
  public async findById(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId):Promise<WhatsAppConnection|null>{const rows=await this.database.query<ConnectionRow>("SELECT wc.* FROM whatsapp_connections wc JOIN companies c ON c.id=wc.company_id WHERE wc.id=? AND wc.company_id=? AND wc.workspace_id=? AND c.workspace_id=?",[id,companyId,context.workspaceId,context.workspaceId]);return rows[0]?connection(rows[0]):null;}
  public async findByIdForRecovery(id:WhatsAppConnectionId):Promise<WhatsAppConnection|null>{const rows=await this.database.query<ConnectionRow>("SELECT wc.* FROM whatsapp_connections wc JOIN companies c ON c.id=wc.company_id AND c.workspace_id=wc.workspace_id JOIN workspace_commercial_controls cc ON cc.workspace_id=wc.workspace_id AND cc.status='active' WHERE wc.id=?",[id]);return rows[0]?connection(rows[0]):null;}
  public async findByPhoneNumberId(phoneNumberId:string):Promise<WhatsAppConnection|null>{const rows=await this.database.query<ConnectionRow>("SELECT wc.* FROM whatsapp_connections wc JOIN companies c ON c.id=wc.company_id AND c.workspace_id=wc.workspace_id AND c.lifecycle_state!='archived' JOIN assistant_profiles p ON p.id=wc.assistant_profile_id AND p.company_id=c.id AND p.status!='archived' JOIN workspace_commercial_controls cc ON cc.workspace_id=wc.workspace_id AND cc.status='active' WHERE wc.phone_number_id=?",[phoneNumberId]);return rows[0]?connection(rows[0]):null;}
  public async listByCompany(context:WorkspaceContext,companyId:number):Promise<WhatsAppConnection[]>{return (await this.database.query<ConnectionRow>("SELECT wc.* FROM whatsapp_connections wc JOIN companies c ON c.id=wc.company_id WHERE wc.company_id=? AND wc.workspace_id=? AND c.workspace_id=? ORDER BY wc.created_at DESC,wc.id DESC",[companyId,context.workspaceId,context.workspaceId])).map(connection);}
  public async updateStatus(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId,expected:string,status:WhatsAppConnectionStatus,updatedAt:string):Promise<WhatsAppConnection|null>{const result=await this.database.execute("UPDATE whatsapp_connections SET status=?,updated_at=? WHERE id=? AND company_id=? AND workspace_id=? AND updated_at=? AND company_id IN (SELECT id FROM companies WHERE id=? AND workspace_id=?)",[status,updatedAt,id,companyId,context.workspaceId,expected,companyId,context.workspaceId]);return Number(result.rowsAffected)===1?this.findById(context,companyId,id):null;}
  public async updateAssistantProfile(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId,expected:string,profileId:WhatsAppConnection["assistantProfileId"],updatedAt:string):Promise<WhatsAppConnection|null>{const result=await this.database.execute("UPDATE whatsapp_connections SET assistant_profile_id=?,updated_at=? WHERE id=? AND company_id=? AND workspace_id=? AND status='inactive' AND updated_at=? AND EXISTS (SELECT 1 FROM assistant_profiles p WHERE p.id=? AND p.company_id=?) AND company_id IN (SELECT id FROM companies WHERE id=? AND workspace_id=?)",[profileId,updatedAt,id,companyId,context.workspaceId,expected,profileId,companyId,companyId,context.workspaceId]);return Number(result.rowsAffected)===1?this.findById(context,companyId,id):null;}
  public async updateConfiguration(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId,expected:string,profileId:WhatsAppConnection["assistantProfileId"],phoneNumberId:string,whatsappBusinessAccountId:string,updatedAt:string):Promise<WhatsAppConnection|null>{const result=await this.database.execute("UPDATE whatsapp_connections SET assistant_profile_id=?,phone_number_id=?,whatsapp_business_account_id=?,updated_at=? WHERE id=? AND company_id=? AND workspace_id=? AND status='inactive' AND updated_at=? AND EXISTS (SELECT 1 FROM assistant_profiles p WHERE p.id=? AND p.company_id=?) AND company_id IN (SELECT id FROM companies WHERE id=? AND workspace_id=?)",[profileId,phoneNumberId,whatsappBusinessAccountId,updatedAt,id,companyId,context.workspaceId,expected,profileId,companyId,companyId,context.workspaceId]);return Number(result.rowsAffected)===1?this.findById(context,companyId,id):null;}
  public async replaceCredentialsAndDeactivate(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId,expected:string,value:EncryptedWhatsAppConnectionCredentials,state:WhatsAppConnectionOperationalState,updatedAt:string):Promise<WhatsAppConnection|null>{return this.database.transaction(async database=>{const result=await database.execute("UPDATE whatsapp_connections SET status='inactive',updated_at=? WHERE id=? AND company_id=? AND workspace_id=? AND updated_at=? AND company_id IN (SELECT id FROM companies WHERE id=? AND workspace_id=?)",[updatedAt,id,companyId,context.workspaceId,expected,companyId,context.workspaceId]);if(Number(result.rowsAffected)!==1)return null;await database.execute("INSERT INTO whatsapp_connection_credentials(whatsapp_connection_id,encrypted_access_token,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(whatsapp_connection_id) DO UPDATE SET encrypted_access_token=excluded.encrypted_access_token,updated_at=excluded.updated_at",[value.whatsAppConnectionId,value.encryptedAccessToken,value.createdAt,value.updatedAt]);await database.execute("INSERT INTO whatsapp_connection_operational_states(whatsapp_connection_id,validation_state,validated_at,validation_failure_code,health_state,last_provider_activity_at,last_webhook_activity_at,health_failure_code,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(whatsapp_connection_id) DO UPDATE SET validation_state=excluded.validation_state,validated_at=excluded.validated_at,validation_failure_code=excluded.validation_failure_code,health_state=excluded.health_state,last_provider_activity_at=excluded.last_provider_activity_at,last_webhook_activity_at=excluded.last_webhook_activity_at,health_failure_code=excluded.health_failure_code,updated_at=excluded.updated_at",[state.whatsAppConnectionId,state.validationState,state.validatedAt,state.validationFailureCode,state.healthState,state.lastProviderActivityAt,state.lastWebhookActivityAt,state.healthFailureCode,state.updatedAt]);return this.findById(context,companyId,id);});}
  public async findCredentials(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId):Promise<EncryptedWhatsAppConnectionCredentials|null>{const rows=await this.database.query<CredentialRow>("SELECT credentials.* FROM whatsapp_connection_credentials credentials JOIN whatsapp_connections connection ON connection.id=credentials.whatsapp_connection_id JOIN companies company ON company.id=connection.company_id WHERE credentials.whatsapp_connection_id=? AND connection.company_id=? AND connection.workspace_id=? AND company.workspace_id=?",[id,companyId,context.workspaceId,context.workspaceId]);return rows[0]?credentials(rows[0]):null;}
  public async replaceCredentials(context:WorkspaceContext,companyId:number,value:EncryptedWhatsAppConnectionCredentials):Promise<EncryptedWhatsAppConnectionCredentials|null>{const result=await this.database.execute("INSERT INTO whatsapp_connection_credentials(whatsapp_connection_id,encrypted_access_token,created_at,updated_at) SELECT connection.id,?,?,? FROM whatsapp_connections connection JOIN companies company ON company.id=connection.company_id WHERE connection.id=? AND connection.company_id=? AND connection.workspace_id=? AND company.workspace_id=? ON CONFLICT(whatsapp_connection_id) DO UPDATE SET encrypted_access_token=excluded.encrypted_access_token,updated_at=excluded.updated_at",[value.encryptedAccessToken,value.createdAt,value.updatedAt,value.whatsAppConnectionId,companyId,context.workspaceId,context.workspaceId]);return Number(result.rowsAffected)===1?this.findCredentials(context,companyId,value.whatsAppConnectionId):null;}
  public async findOperationalState(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId):Promise<WhatsAppConnectionOperationalState|null>{const rows=await this.database.query<OperationalStateRow>("SELECT state.* FROM whatsapp_connection_operational_states state JOIN whatsapp_connections connection ON connection.id=state.whatsapp_connection_id JOIN companies company ON company.id=connection.company_id WHERE state.whatsapp_connection_id=? AND connection.company_id=? AND connection.workspace_id=? AND company.workspace_id=?",[id,companyId,context.workspaceId,context.workspaceId]);return rows[0]?operationalState(rows[0]):null;}
  public async replaceOperationalState(context:WorkspaceContext,companyId:number,value:WhatsAppConnectionOperationalState):Promise<WhatsAppConnectionOperationalState|null>{const result=await this.database.execute("INSERT INTO whatsapp_connection_operational_states(whatsapp_connection_id,validation_state,validated_at,validation_failure_code,health_state,last_provider_activity_at,last_webhook_activity_at,health_failure_code,updated_at) SELECT connection.id,?,?,?,?,?,?,?,? FROM whatsapp_connections connection JOIN companies company ON company.id=connection.company_id WHERE connection.id=? AND connection.company_id=? AND connection.workspace_id=? AND company.workspace_id=? ON CONFLICT(whatsapp_connection_id) DO UPDATE SET validation_state=excluded.validation_state,validated_at=excluded.validated_at,validation_failure_code=excluded.validation_failure_code,health_state=excluded.health_state,last_provider_activity_at=excluded.last_provider_activity_at,last_webhook_activity_at=excluded.last_webhook_activity_at,health_failure_code=excluded.health_failure_code,updated_at=excluded.updated_at",[value.validationState,value.validatedAt,value.validationFailureCode,value.healthState,value.lastProviderActivityAt,value.lastWebhookActivityAt,value.healthFailureCode,value.updatedAt,value.whatsAppConnectionId,companyId,context.workspaceId,context.workspaceId]);return Number(result.rowsAffected)===1?this.findOperationalState(context,companyId,value.whatsAppConnectionId):null;}
  public async findIntegrationConnectionId(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId):Promise<string|null>{const rows=await this.database.query<{integration_connection_id:string|null}>("SELECT connection.integration_connection_id FROM whatsapp_connections connection JOIN companies company ON company.id=connection.company_id WHERE connection.id=? AND connection.company_id=? AND connection.workspace_id=? AND company.workspace_id=?",[id,companyId,context.workspaceId,context.workspaceId]);return rows[0]?.integration_connection_id??null;}
  public async findWhatsAppConnectionIdByIntegrationConnectionId(context:WorkspaceContext,companyId:number,integrationConnectionId:string):Promise<string|null>{const rows=await this.database.query<{id:string}>("SELECT connection.id FROM whatsapp_connections connection JOIN companies company ON company.id=connection.company_id WHERE connection.integration_connection_id=? AND connection.company_id=? AND connection.workspace_id=? AND company.workspace_id=?",[integrationConnectionId,companyId,context.workspaceId,context.workspaceId]);return rows[0]?.id??null;}
  public async findLinkedIntegrationSecret(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId):Promise<string|null>{return this.integrationSecret(context,companyId,id,"");}
  public async findReadyLinkedIntegrationSecret(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId):Promise<string|null>{return this.integrationSecret(context,companyId,id," AND integration.status='active' AND state.validation_state='valid' AND state.health_state='healthy'");}
  private async integrationSecret(context:WorkspaceContext,companyId:number,id:WhatsAppConnectionId,ready:string):Promise<string|null>{const stateJoin=ready?" JOIN integration_connection_operational_states state ON state.integration_connection_id=integration.id":"";const rows=await this.database.query<{encrypted_secret:string}>(`SELECT secret.encrypted_secret FROM whatsapp_connections connection JOIN companies company ON company.id=connection.company_id JOIN integration_connections integration ON integration.id=connection.integration_connection_id AND integration.workspace_id=connection.workspace_id AND integration.company_id=connection.company_id${stateJoin} JOIN integration_connection_secrets secret ON secret.integration_connection_id=integration.id WHERE connection.id=? AND connection.company_id=? AND connection.workspace_id=? AND company.workspace_id=? AND integration.provider='meta_whatsapp' AND integration.kind='cloud_api'${ready}`,[id,companyId,context.workspaceId,context.workspaceId]);return rows[0]?.encrypted_secret??null;}
}
