import { randomUUID } from "node:crypto";
import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { ChannelExecutionRequestId, MediaGateRecomputeOutcome } from "../../transport/domain/providerDelivery.js";
import type { WhatsAppInboundMedia, WhatsAppInboundMediaFailure, WhatsAppInboundMediaState, WhatsAppInboundMediaTransitionOutcome } from "../domain/whatsappInboundMedia.js";

type Row = { id:string; workspace_id:number; company_id:number; whatsapp_connection_id:string; channel_provider_event_id:string; conversation_message_id:string; provider_media_id:string; provider_kind:WhatsAppInboundMedia["descriptor"]["kind"]; declared_mime:string; safe_filename:string|null; ordinal:number; caption_present:number; state:WhatsAppInboundMediaState; media_asset_id:string|null; failure_code:WhatsAppInboundMediaFailure|null; last_retry_failure_code:WhatsAppInboundMediaFailure|null; last_retry_failure_at:string|null; attempt_count:number; next_attempt_at:string|null; lease_token:string|null; lease_owner:string|null; lease_acquired_at:string|null; lease_expires_at:string|null; created_at:string; updated_at:string; completed_at:string|null; };
type RequestRow = { id:string; media_gate_state:"open"|"blocked_by_media"|"blocked_by_transcript"; event_id:string; event_message_id:string|null; };

const media = (row:Row):WhatsAppInboundMedia => Object.freeze({ id:row.id, workspaceId:Number(row.workspace_id), companyId:Number(row.company_id), connectionId:row.whatsapp_connection_id, eventId:row.channel_provider_event_id, conversationMessageId:row.conversation_message_id, descriptor:Object.freeze({ wamid:"", providerMediaId:row.provider_media_id, kind:row.provider_kind, declaredMime:row.declared_mime, filename:row.safe_filename, caption:null, ordinal:Number(row.ordinal) }), state:row.state, mediaAssetId:row.media_asset_id, failureCode:row.failure_code, lastRetryFailureCode:row.last_retry_failure_code, lastRetryFailureAt:row.last_retry_failure_at, attemptCount:Number(row.attempt_count), nextAttemptAt:row.next_attempt_at, leaseToken:row.lease_token, leaseOwner:row.lease_owner, leaseAcquiredAt:row.lease_acquired_at, leaseExpiresAt:row.lease_expires_at, createdAt:row.created_at, updatedAt:row.updated_at, completedAt:row.completed_at });

/** Async durable recovery ledger. Every claim and settlement retains the synchronous ledger's fences. */
export class AsyncWhatsAppInboundMediaPersistence {
  public constructor(private readonly database:SqlDatabase) {}

  public async claimInboundMediaForRecovery(context:WorkspaceContext, companyId:number, connectionId:string, owner:string, now:string, expiresAt:string):Promise<{ readonly media:WhatsAppInboundMedia; readonly leaseToken:string }|null> { return this.database.transaction(async database => { const row=(await database.query<Row>("SELECT * FROM whatsapp_inbound_media WHERE workspace_id=? AND company_id=? AND whatsapp_connection_id=? AND ((state='pending_download' AND (next_attempt_at IS NULL OR next_attempt_at<=?)) OR (state='ingesting' AND lease_expires_at<=?)) ORDER BY created_at,id LIMIT 1",[context.workspaceId,companyId,connectionId,now,now]))[0]; if(!row)return null; const leaseToken=`wml_${randomUUID().replaceAll("-","")}`, changed=await database.execute("UPDATE whatsapp_inbound_media SET state='ingesting',lease_token=?,lease_owner=?,lease_acquired_at=?,lease_expires_at=?,attempt_count=attempt_count+1,updated_at=? WHERE id=? AND workspace_id=? AND company_id=? AND (state='pending_download' OR (state='ingesting' AND lease_expires_at<=?))",[leaseToken,owner,now,expiresAt,now,row.id,context.workspaceId,companyId,now]); if(Number(changed.rowsAffected)!==1)throw new Error("media_lease_lost"); const claimed=(await database.query<Row>("SELECT * FROM whatsapp_inbound_media WHERE id=?",[row.id]))[0]; if(!claimed)throw new Error("WhatsApp inbound media claim could not be read."); return Object.freeze({media:media(claimed),leaseToken}); }); }

  public async markAssociated(context:WorkspaceContext, companyId:number, connectionId:string, id:string, token:string, assetId:string, at:string):Promise<WhatsAppInboundMediaTransitionOutcome> { return this.database.transaction(async database => { const current=await this.current(database,context,companyId,connectionId,id); if(!current)return {kind:"not_found"}; if(current.state==="associated")return current.media_asset_id===assetId?{kind:"replayed",media:media(current)}:{kind:"conflict",currentState:current.state}; if(current.state!=="ingesting")return {kind:"conflict",currentState:current.state}; if(!activeLease(current,token,at))return {kind:"lease_lost"}; if(!(await database.query<{id:string}>("SELECT id FROM media_assets WHERE id=? AND workspace_id=? AND company_id=? AND status='ready' AND archived_at IS NULL AND deleted_at IS NULL",[assetId,context.workspaceId,companyId]))[0])return {kind:"conflict",currentState:current.state}; await database.execute("UPDATE whatsapp_inbound_media SET state='associated',media_asset_id=?,failure_code=NULL,next_attempt_at=NULL,lease_token=NULL,lease_owner=NULL,lease_acquired_at=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE id=?",[assetId,at,at,id]); return {kind:"applied",media:await this.saved(database,id)}; }); }

  public async markRetryableFailure(context:WorkspaceContext, companyId:number, connectionId:string, id:string, token:string, code:WhatsAppInboundMediaFailure, nextAttemptAt:string, at:string):Promise<WhatsAppInboundMediaTransitionOutcome> { return this.database.transaction(async database => { const current=await this.current(database,context,companyId,connectionId,id); if(!current)return {kind:"not_found"}; if(current.state==="pending_download")return current.lease_token===null&&current.lease_owner===null&&current.lease_acquired_at===null&&current.lease_expires_at===null&&current.last_retry_failure_code===code&&current.next_attempt_at===nextAttemptAt?{kind:"replayed",media:media(current)}:{kind:"conflict",currentState:current.state}; if(current.state!=="ingesting")return {kind:"conflict",currentState:current.state}; if(!activeLease(current,token,at))return {kind:"lease_lost"}; await database.execute("UPDATE whatsapp_inbound_media SET state='pending_download',media_asset_id=NULL,failure_code=NULL,last_retry_failure_code=?,last_retry_failure_at=?,next_attempt_at=?,lease_token=NULL,lease_owner=NULL,lease_acquired_at=NULL,lease_expires_at=NULL,completed_at=NULL,updated_at=? WHERE id=?",[code,at,nextAttemptAt,at,id]); return {kind:"applied",media:await this.saved(database,id)}; }); }

  public async markTerminalFailure(context:WorkspaceContext, companyId:number, connectionId:string, id:string, token:string, code:WhatsAppInboundMediaFailure, at:string):Promise<WhatsAppInboundMediaTransitionOutcome> { return this.database.transaction(async database => { const current=await this.current(database,context,companyId,connectionId,id); if(!current)return {kind:"not_found"}; const state=code==="unsupported_media"?"unsupported":"failed"; if(current.state==="failed"||current.state==="unsupported")return current.state===state&&current.failure_code===code?{kind:"replayed",media:media(current)}:{kind:"conflict",currentState:current.state}; if(current.state!=="ingesting")return {kind:"conflict",currentState:current.state}; if(!activeLease(current,token,at))return {kind:"lease_lost"}; await database.execute("UPDATE whatsapp_inbound_media SET state=?,media_asset_id=NULL,failure_code=?,next_attempt_at=NULL,lease_token=NULL,lease_owner=NULL,lease_acquired_at=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE id=?",[state,code,at,at,id]); return {kind:"applied",media:await this.saved(database,id)}; }); }

  public async recoverableScopes(now:string, limit:number):Promise<readonly {readonly workspaceId:number; readonly companyId:number; readonly connectionId:string}[]> { if(!Number.isSafeInteger(limit)||limit<1)return []; return (await this.database.query<{workspace_id:number;company_id:number;whatsapp_connection_id:string}>("SELECT workspace_id,company_id,whatsapp_connection_id FROM whatsapp_inbound_media WHERE (state='pending_download' AND (next_attempt_at IS NULL OR next_attempt_at<=?)) OR (state='ingesting' AND lease_expires_at<=?) GROUP BY workspace_id,company_id,whatsapp_connection_id ORDER BY MIN(created_at),whatsapp_connection_id LIMIT ?",[now,now,limit])).map(row=>Object.freeze({workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),connectionId:row.whatsapp_connection_id})); }

  public async settledGateCandidates(limit:number):Promise<readonly {readonly workspaceId:number; readonly companyId:number; readonly connectionId:string; readonly eventId:string}[]> { if(!Number.isSafeInteger(limit)||limit<1)return []; return (await this.database.query<{workspace_id:number;company_id:number;whatsapp_connection_id:string;channel_provider_event_id:string}>("SELECT m.workspace_id,m.company_id,m.whatsapp_connection_id,m.channel_provider_event_id FROM whatsapp_inbound_media m JOIN channel_execution_requests r ON r.channel_provider_event_id=m.channel_provider_event_id WHERE r.media_gate_state='blocked_by_media' AND NOT EXISTS(SELECT 1 FROM whatsapp_inbound_media pending WHERE pending.workspace_id=m.workspace_id AND pending.company_id=m.company_id AND pending.whatsapp_connection_id=m.whatsapp_connection_id AND pending.channel_provider_event_id=m.channel_provider_event_id AND pending.state IN ('pending_download','ingesting')) GROUP BY m.workspace_id,m.company_id,m.whatsapp_connection_id,m.channel_provider_event_id ORDER BY MIN(m.created_at),m.channel_provider_event_id LIMIT ?",[limit])).map(row=>Object.freeze({workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),connectionId:row.whatsapp_connection_id,eventId:row.channel_provider_event_id})); }

  public async findExecutionRequestIdForEvent(context:WorkspaceContext,companyId:number,connectionId:string,eventId:string):Promise<ChannelExecutionRequestId|null>{const row=(await this.database.query<{id:string}>("SELECT r.id FROM channel_execution_requests r JOIN channel_provider_events e ON e.id=r.channel_provider_event_id JOIN whatsapp_connections wc ON wc.id=e.transport_connection_id JOIN companies c ON c.id=wc.company_id AND c.workspace_id=wc.workspace_id WHERE e.id=? AND wc.workspace_id=? AND wc.company_id=? AND wc.id=? AND e.communication_channel='whatsapp'",[eventId,context.workspaceId,companyId,connectionId]))[0];return row?row.id as ChannelExecutionRequestId:null;}

  public async recomputeExecutionMediaGate(context:WorkspaceContext,companyId:number,connectionId:string,executionRequestId:ChannelExecutionRequestId,updatedAt:string):Promise<MediaGateRecomputeOutcome>{return this.database.transaction(async database=>{const current=(await database.query<RequestRow>("SELECT r.id,r.media_gate_state,e.id AS event_id,e.conversation_message_id AS event_message_id FROM channel_execution_requests r JOIN channel_provider_events e ON e.id=r.channel_provider_event_id JOIN whatsapp_connections wc ON wc.id=e.transport_connection_id JOIN companies c ON c.id=wc.company_id AND c.workspace_id=wc.workspace_id WHERE r.id=? AND wc.workspace_id=? AND wc.company_id=? AND wc.id=? AND e.communication_channel='whatsapp'",[executionRequestId,context.workspaceId,companyId,connectionId]))[0];if(!current)return{kind:"not_found"};const rows=current.event_message_id===null?[]:await database.query<{state:WhatsAppInboundMediaState}>("SELECT state FROM whatsapp_inbound_media WHERE workspace_id=? AND company_id=? AND whatsapp_connection_id=? AND channel_provider_event_id=? AND conversation_message_id=?",[context.workspaceId,companyId,connectionId,current.event_id,current.event_message_id]);if(current.media_gate_state==="blocked_by_transcript")return{kind:"unchanged",gate:"blocked_by_transcript"};if(rows.length===0)return current.media_gate_state==="blocked_by_media"?{kind:"conflict"}:{kind:"unchanged",gate:"open"};const gate=rows.some(row=>row.state==="pending_download"||row.state==="ingesting")?"blocked_by_media":"open";if(current.media_gate_state===gate)return{kind:"unchanged",gate};await database.execute("UPDATE channel_execution_requests SET media_gate_state=?,updated_at=? WHERE id=? AND media_gate_state=?",[gate,updatedAt,executionRequestId,current.media_gate_state]);return{kind:"updated",gate};});}

  public async suppressBlockedAudioExecution(context:WorkspaceContext,companyId:number,connectionId:string,executionRequestId:ChannelExecutionRequestId,updatedAt:string):Promise<boolean>{const changed=await this.database.execute("UPDATE channel_execution_requests SET state='completed',outcome='suppressed',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND state='pending' AND media_gate_state='blocked_by_media' AND EXISTS(SELECT 1 FROM channel_provider_events e JOIN whatsapp_connections wc ON wc.id=e.transport_connection_id JOIN whatsapp_inbound_media m ON m.channel_provider_event_id=e.id WHERE e.id=channel_execution_requests.channel_provider_event_id AND wc.workspace_id=? AND wc.company_id=? AND wc.id=? AND m.provider_kind='audio')",[updatedAt,executionRequestId,context.workspaceId,companyId,connectionId]);return Number(changed.rowsAffected)===1;}
  public async markBlockedAudioExecutionUnsupported(context:WorkspaceContext,companyId:number,connectionId:string,executionRequestId:ChannelExecutionRequestId,updatedAt:string):Promise<boolean>{const changed=await this.database.execute("UPDATE channel_execution_requests SET state='unsupported',outcome='unsupported',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND state='pending' AND media_gate_state='blocked_by_media' AND EXISTS(SELECT 1 FROM channel_provider_events e JOIN whatsapp_connections wc ON wc.id=e.transport_connection_id JOIN whatsapp_inbound_media m ON m.channel_provider_event_id=e.id WHERE e.id=channel_execution_requests.channel_provider_event_id AND wc.workspace_id=? AND wc.company_id=? AND wc.id=? AND m.provider_kind='audio')",[updatedAt,executionRequestId,context.workspaceId,companyId,connectionId]);return Number(changed.rowsAffected)===1;}

  private async current(database:SqlDatabase,context:WorkspaceContext,companyId:number,connectionId:string,id:string):Promise<Row|undefined>{return(await database.query<Row>("SELECT * FROM whatsapp_inbound_media WHERE id=? AND workspace_id=? AND company_id=? AND whatsapp_connection_id=?",[id,context.workspaceId,companyId,connectionId]))[0];}
  private async saved(database:SqlDatabase,id:string):Promise<WhatsAppInboundMedia>{const row=(await database.query<Row>("SELECT * FROM whatsapp_inbound_media WHERE id=?",[id]))[0];if(!row)throw new Error("WhatsApp inbound media settlement could not be read.");return media(row);}
}

function activeLease(row:Row,token:string,at:string):boolean{return!!token&&row.lease_token===token&&row.lease_expires_at!==null&&row.lease_expires_at>at;}
