import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { AsyncWhatsAppConversationRepositoryPort } from "../application/ports.js";
import { reconstructWhatsAppConversationBinding, whatsAppConnectionId, type WhatsAppConversationBinding, type WhatsAppConnectionId } from "../domain/whatsappConnection.js";
import { conversationId, conversationParticipantId, type ConversationId } from "../../conversation/domain/conversation.js";

interface Row extends Record<string, unknown> { id: string; whatsapp_connection_id: string; wa_id: string; conversation_id: string; customer_participant_id: string; assistant_participant_id: string; created_at: string; updated_at: string; }

function binding(row: Row): WhatsAppConversationBinding { return reconstructWhatsAppConversationBinding({ id: row.id as WhatsAppConversationBinding["id"], whatsAppConnectionId: whatsAppConnectionId(row.whatsapp_connection_id), waId: row.wa_id, conversationId: conversationId(row.conversation_id), customerParticipantId: conversationParticipantId(row.customer_participant_id), assistantParticipantId: conversationParticipantId(row.assistant_participant_id), createdAt: row.created_at, updatedAt: row.updated_at }); }

export class AsyncWhatsAppConversationPersistence implements AsyncWhatsAppConversationRepositoryPort {
  public constructor(private readonly database: SqlDatabase) {}
  public async findBinding(connectionIdValue: WhatsAppConnectionId, waId: string): Promise<WhatsAppConversationBinding | null> { const rows = await this.database.query<Row>("SELECT b.* FROM whatsapp_conversation_bindings b JOIN whatsapp_connections wc ON wc.id=b.whatsapp_connection_id JOIN conversations c ON c.id=b.conversation_id AND c.company_id=wc.company_id AND c.channel='whatsapp' JOIN conversation_participants customer ON customer.id=b.customer_participant_id AND customer.conversation_id=c.id JOIN conversation_participants assistant ON assistant.id=b.assistant_participant_id AND assistant.conversation_id=c.id WHERE b.whatsapp_connection_id=? AND b.wa_id=?", [connectionIdValue, waId]); return rows[0] ? binding(rows[0]) : null; }
  public async findBindingByConversation(context: WorkspaceContext, companyId: number, conversationIdValue: ConversationId): Promise<WhatsAppConversationBinding | null> { const rows = await this.database.query<Row>("SELECT b.* FROM whatsapp_conversation_bindings b JOIN whatsapp_connections wc ON wc.id=b.whatsapp_connection_id JOIN companies co ON co.id=wc.company_id JOIN conversations c ON c.id=b.conversation_id AND c.company_id=wc.company_id AND c.channel='whatsapp' WHERE co.workspace_id=? AND wc.workspace_id=? AND wc.company_id=? AND c.id=?", [context.workspaceId, context.workspaceId, companyId, conversationIdValue]); return rows[0] ? binding(rows[0]) : null; }
  public async createBinding(value: WhatsAppConversationBinding): Promise<WhatsAppConversationBinding | null> { const result = await this.database.execute("INSERT INTO whatsapp_conversation_bindings(id,whatsapp_connection_id,wa_id,conversation_id,customer_participant_id,assistant_participant_id,created_at,updated_at) SELECT ?,wc.id,?,c.id,customer.id,assistant.id,?,? FROM whatsapp_connections wc JOIN conversations c ON c.id=? AND c.company_id=wc.company_id AND c.channel='whatsapp' JOIN conversation_participants customer ON customer.id=? AND customer.conversation_id=c.id JOIN conversation_participants assistant ON assistant.id=? AND assistant.conversation_id=c.id WHERE wc.id=?", [value.id, value.waId, value.createdAt, value.updatedAt, value.conversationId, value.customerParticipantId, value.assistantParticipantId, value.whatsAppConnectionId]); return Number(result.rowsAffected) === 1 ? this.findBinding(value.whatsAppConnectionId, value.waId) : null; }
}
