import { randomUUID } from "node:crypto";
import type { SqlDatabase } from "../../config/sqlDatabase.js";
import { conversationId, conversationMessageId, conversationParticipantId, reconstructConversationMessage, type ConversationMessage } from "../../conversation/domain/conversation.js";
import { channelExecutionRequestId, channelProviderEventId, reconstructChannelExecutionRequest, reconstructChannelProviderEvent, reconstructProviderMessageRecord, type ChannelExecutionRequest, type ChannelExecutionRequestId, type ChannelProviderEvent, type ProviderMessageRecord } from "../../transport/domain/providerDelivery.js";
import { reconstructWhatsAppConversationBinding, whatsAppConnectionId, type WhatsAppConnection, type WhatsAppConversationBinding } from "../domain/whatsappConnection.js";
import type { WhatsAppInboundMedia, WhatsAppInboundMediaDescriptor } from "../domain/whatsappInboundMedia.js";
import type { AssistantResponseFinalizationResult } from "../../conversation/application/ports.js";

type ConnectionRow = { id: string; workspace_id: number; company_id: number; assistant_profile_id: string; phone_number_id: string; whatsapp_business_account_id: string; status: "active" | "inactive"; created_at: string; updated_at: string };
type BindingRow = { id: string; whatsapp_connection_id: string; wa_id: string; conversation_id: string; customer_participant_id: string; assistant_participant_id: string; created_at: string; updated_at: string };
type EventRow = { id: string; communication_channel: "whatsapp"; transport_provider: string; transport_connection_id: string; external_event_id: string; state: "claimed" | "processing" | "completed" | "failed"; conversation_id: string | null; conversation_message_id: string | null; created_at: string; updated_at: string };
type MessageRow = { id: string; conversation_id: string; sender_participant_id: string; direction: "inbound" | "outbound"; content: string; idempotency_key: string | null; assistant_execution_record_id: string | null; created_at: string };
type RequestRow = { id: string; channel_provider_event_id: string; state: "pending" | "leased" | "completed" | "failed" | "unsupported"; media_gate_state: "open" | "blocked_by_media" | "blocked_by_transcript"; snapshot_json: string; lease_owner: string | null; lease_expires_at: string | null; outcome: string | null; created_at: string; updated_at: string };
type MediaRow = { id: string; workspace_id: number; company_id: number; whatsapp_connection_id: string; channel_provider_event_id: string; conversation_message_id: string; provider_media_id: string; provider_kind: WhatsAppInboundMedia["descriptor"]["kind"]; declared_mime: string; safe_filename: string | null; ordinal: number; caption_present: number; state: WhatsAppInboundMedia["state"]; media_asset_id: string | null; failure_code: WhatsAppInboundMedia["failureCode"]; attempt_count: number; next_attempt_at: string | null; created_at: string; updated_at: string; completed_at: string | null };
type ResumeRow = { event_id: string; event_communication_channel: "whatsapp"; event_transport_provider: string; event_transport_connection_id: string; event_external_event_id: string; event_state: "claimed" | "processing" | "completed" | "failed"; event_conversation_id: string | null; event_conversation_message_id: string | null; event_created_at: string; event_updated_at: string; binding_id: string; binding_connection_id: string; binding_wa_id: string; binding_conversation_id: string; binding_customer_participant_id: string; binding_assistant_participant_id: string; binding_created_at: string; binding_updated_at: string; message_id: string; message_conversation_id: string; message_sender_participant_id: string; message_direction: "inbound" | "outbound"; message_content: string; message_idempotency_key: string | null; message_execution_record_id: string | null; message_created_at: string; };

const connection = (row: ConnectionRow): WhatsAppConnection => Object.freeze({ id: whatsAppConnectionId(row.id), workspaceId: Number(row.workspace_id), companyId: Number(row.company_id), assistantProfileId: row.assistant_profile_id as WhatsAppConnection["assistantProfileId"], phoneNumberId: row.phone_number_id, whatsappBusinessAccountId: row.whatsapp_business_account_id, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at });
const binding = (row: BindingRow): WhatsAppConversationBinding => reconstructWhatsAppConversationBinding({ id: row.id as WhatsAppConversationBinding["id"], whatsAppConnectionId: whatsAppConnectionId(row.whatsapp_connection_id), waId: row.wa_id, conversationId: conversationId(row.conversation_id), customerParticipantId: conversationParticipantId(row.customer_participant_id), assistantParticipantId: conversationParticipantId(row.assistant_participant_id), createdAt: row.created_at, updatedAt: row.updated_at });
const event = (row: EventRow): ChannelProviderEvent => reconstructChannelProviderEvent({ id: channelProviderEventId(row.id), communicationChannel: row.communication_channel, transportProvider: row.transport_provider, transportConnectionId: row.transport_connection_id, externalEventId: row.external_event_id, state: row.state, conversationId: row.conversation_id === null ? null : conversationId(row.conversation_id), conversationMessageId: row.conversation_message_id === null ? null : conversationMessageId(row.conversation_message_id), createdAt: row.created_at, updatedAt: row.updated_at });
const message = (row: MessageRow): ConversationMessage => reconstructConversationMessage({ id: conversationMessageId(row.id), conversationId: conversationId(row.conversation_id), senderParticipantId: conversationParticipantId(row.sender_participant_id), direction: row.direction, content: row.content, idempotencyKey: row.idempotency_key, executionRecordId: row.assistant_execution_record_id, createdAt: row.created_at });
const request = (row: RequestRow): ChannelExecutionRequest => reconstructChannelExecutionRequest({ id: channelExecutionRequestId(row.id), channelProviderEventId: channelProviderEventId(row.channel_provider_event_id), state: row.state, mediaGateState: row.media_gate_state, snapshot: JSON.parse(row.snapshot_json) as Record<string, unknown>, leaseOwner: row.lease_owner, leaseExpiresAt: row.lease_expires_at, outcome: row.outcome, createdAt: row.created_at, updatedAt: row.updated_at });
const media = (row: MediaRow): WhatsAppInboundMedia => Object.freeze({ id: row.id, workspaceId: Number(row.workspace_id), companyId: Number(row.company_id), connectionId: row.whatsapp_connection_id, eventId: row.channel_provider_event_id, conversationMessageId: row.conversation_message_id, descriptor: Object.freeze({ wamid: "", providerMediaId: row.provider_media_id, kind: row.provider_kind, declaredMime: row.declared_mime, filename: row.safe_filename, caption: null, ordinal: Number(row.ordinal) }), state: row.state, mediaAssetId: row.media_asset_id, failureCode: row.failure_code, attemptCount: Number(row.attempt_count), nextAttemptAt: row.next_attempt_at, createdAt: row.created_at, updatedAt: row.updated_at, completedAt: row.completed_at });

export interface AsyncWhatsAppInboundAttachment { readonly id: string; readonly descriptor: WhatsAppInboundMediaDescriptor; readonly createdAt: string; readonly updatedAt: string; }
export interface AsyncWhatsAppInboundCapture { readonly phoneNumberId: string; readonly waId: string; readonly wamid: string; readonly text: string; readonly event: ChannelProviderEvent; readonly inbound: ConversationMessage; readonly providerMessage: ProviderMessageRecord; readonly request: ChannelExecutionRequest; readonly binding: WhatsAppConversationBinding; readonly attachments?: readonly AsyncWhatsAppInboundAttachment[]; }
export interface AsyncWhatsAppInboundCaptureResult { readonly kind: "captured" | "replayed" | "unmatched"; readonly connection: WhatsAppConnection | null; readonly event: ChannelProviderEvent | null; readonly inbound: ConversationMessage | null; readonly request: ChannelExecutionRequest | null; readonly binding: WhatsAppConversationBinding | null; readonly media: readonly WhatsAppInboundMedia[]; }
export interface AsyncWhatsAppLeasedExecutionContext { readonly event: ChannelProviderEvent; readonly binding: WhatsAppConversationBinding; readonly inbound: ConversationMessage; }
export interface AsyncWhatsAppExecutionFinalization { readonly context: { readonly workspaceId: number; readonly workspaceKey: string }; readonly companyId: number; readonly connectionId: string; readonly requestId: ChannelExecutionRequestId; readonly owner: string; readonly leaseExpiresAt: string; readonly now: string; readonly eventId: string; readonly conversationId: string; readonly inboundMessageId: string; readonly assistantProfileId: string; readonly assistantParticipantId: string; readonly executionRecordId: string; readonly authorityGeneration: number; readonly outcome: "answered" | "safe_fallback"; readonly content: string; readonly replyIdempotencyKey: string; readonly outboundMessageId: string; readonly providerMessageId: string; readonly deliveryId: string; }
export class AsyncWhatsAppExecutionLeaseLostError extends Error {}

/** Durable WhatsApp webhook state. Each public state transition owns exactly one transaction. */
export class AsyncWhatsAppInboundPersistence {
  public constructor(private readonly database: SqlDatabase) {}

  public async capture(value: AsyncWhatsAppInboundCapture): Promise<AsyncWhatsAppInboundCaptureResult> {
    return this.database.transaction(async database => {
      const connectionRow = (await database.query<ConnectionRow>("SELECT w.* FROM whatsapp_connections w JOIN companies co ON co.id=w.company_id AND co.workspace_id=w.workspace_id WHERE w.phone_number_id=? AND w.status='active' AND co.lifecycle_state!='archived'", [value.phoneNumberId]))[0];
      if (!connectionRow) return Object.freeze({ kind: "unmatched", connection: null, event: null, inbound: null, request: null, binding: null, media: Object.freeze([]) });
      const active = connection(connectionRow), attachments = value.attachments ?? [];
      const prior = (await database.query<EventRow>("SELECT * FROM channel_provider_events WHERE transport_provider='meta_whatsapp_cloud' AND external_event_id=?", [value.wamid]))[0];
      if (prior) return this.replay(database, active, value, event(prior), attachments);

      let bindingRow = (await database.query<BindingRow>("SELECT * FROM whatsapp_conversation_bindings WHERE whatsapp_connection_id=? AND wa_id=?", [active.id, value.waId]))[0];
      if (!bindingRow) {
        const assistant = value.request.snapshot.assistantParticipantId;
        if (typeof assistant !== "string") throw new Error("WhatsApp execution request is invalid.");
        await database.execute("INSERT INTO conversations(id,company_id,channel,state,created_at,updated_at,closed_at) VALUES(?,?,'whatsapp','open',?,?,NULL)", [value.inbound.conversationId, active.companyId, value.inbound.createdAt, value.inbound.createdAt]);
        await database.execute("INSERT INTO conversation_participants(id,conversation_id,participant_type,reference,created_at) VALUES(?,?, 'whatsapp_contact',?,?)", [value.inbound.senderParticipantId, value.inbound.conversationId, value.waId, value.inbound.createdAt]);
        await database.execute("INSERT INTO conversation_participants(id,conversation_id,participant_type,reference,created_at) VALUES(?,?, 'assistant',?,?)", [assistant, value.inbound.conversationId, active.assistantProfileId, value.inbound.createdAt]);
        await database.execute("INSERT INTO whatsapp_conversation_bindings(id,whatsapp_connection_id,wa_id,conversation_id,customer_participant_id,assistant_participant_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)", [value.binding.id, active.id, value.waId, value.inbound.conversationId, value.inbound.senderParticipantId, assistant, value.binding.createdAt, value.binding.updatedAt]);
        bindingRow = (await database.query<BindingRow>("SELECT * FROM whatsapp_conversation_bindings WHERE whatsapp_connection_id=? AND wa_id=?", [active.id, value.waId]))[0];
      }
      if (!bindingRow) throw new Error("WhatsApp conversation binding could not be persisted.");
      const savedBinding = binding(bindingRow), snapshot = { ...value.request.snapshot, conversationId: savedBinding.conversationId, assistantProfileId: active.assistantProfileId, assistantParticipantId: savedBinding.assistantParticipantId, whatsAppConnectionId: active.id, recipientWaId: savedBinding.waId };
      const inserted = await database.execute("INSERT INTO channel_provider_events(id,communication_channel,transport_provider,transport_connection_id,external_event_id,state,conversation_id,conversation_message_id,created_at,updated_at) VALUES(?,?,?,?,?,'claimed',NULL,NULL,?,?) ON CONFLICT(transport_provider,external_event_id) DO NOTHING", [value.event.id, value.event.communicationChannel, value.event.transportProvider, active.id, value.wamid, value.event.createdAt, value.event.updatedAt]);
      if (Number(inserted.rowsAffected) !== 1) {
        const replay = (await database.query<EventRow>("SELECT * FROM channel_provider_events WHERE transport_provider='meta_whatsapp_cloud' AND external_event_id=?", [value.wamid]))[0];
        if (!replay) throw new Error("WhatsApp inbound replay could not be resolved.");
        return this.replay(database, active, value, event(replay), attachments);
      }
      await database.execute("INSERT INTO conversation_messages(id,conversation_id,sender_participant_id,direction,content,idempotency_key,assistant_execution_record_id,created_at) VALUES(?,?,?,?,?,?,?,?)", [value.inbound.id, savedBinding.conversationId, savedBinding.customerParticipantId, value.inbound.direction, value.inbound.content, value.inbound.idempotencyKey, value.inbound.executionRecordId, value.inbound.createdAt]);
      await database.execute("INSERT INTO provider_message_records(id,communication_channel,transport_provider,direction,transport_connection_id,conversation_message_id,external_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)", [value.providerMessage.id, value.providerMessage.communicationChannel, value.providerMessage.transportProvider, value.providerMessage.direction, active.id, value.inbound.id, value.providerMessage.externalMessageId, value.providerMessage.createdAt, value.providerMessage.updatedAt]);
      await database.execute("UPDATE channel_provider_events SET conversation_id=?,conversation_message_id=?,updated_at=? WHERE id=? AND conversation_message_id IS NULL", [savedBinding.conversationId, value.inbound.id, value.event.updatedAt, value.event.id]);
      await database.execute("INSERT INTO channel_execution_requests(id,channel_provider_event_id,state,media_gate_state,snapshot_json,lease_owner,lease_expires_at,outcome,created_at,updated_at) VALUES(?,?,'pending',?,?,NULL,NULL,NULL,?,?)", [value.request.id, value.event.id, attachments.length === 0 ? "open" : "blocked_by_media", JSON.stringify(snapshot), value.request.createdAt, value.request.updatedAt]);
      const savedEvent = (await database.query<EventRow>("SELECT * FROM channel_provider_events WHERE id=?", [value.event.id]))[0];
      const savedRequest = (await database.query<RequestRow>("SELECT * FROM channel_execution_requests WHERE channel_provider_event_id=?", [value.event.id]))[0];
      if (!savedEvent || !savedRequest) throw new Error("WhatsApp inbound execution could not be persisted.");
      const capturedMedia = await this.captureMedia(database, active, event(savedEvent), attachments);
      return Object.freeze({ kind: "captured", connection: active, event: event(savedEvent), inbound: value.inbound, request: request(savedRequest), binding: savedBinding, media: Object.freeze(capturedMedia) });
    });
  }

  private async replay(database: SqlDatabase, active: WhatsAppConnection, value: AsyncWhatsAppInboundCapture, savedEvent: ChannelProviderEvent, attachments: readonly AsyncWhatsAppInboundAttachment[]): Promise<AsyncWhatsAppInboundCaptureResult> {
    if (savedEvent.transportConnectionId !== active.id || !savedEvent.conversationMessageId) throw new Error("Inbound replay conflicts with the durable event.");
    const inboundRow = (await database.query<MessageRow>("SELECT * FROM conversation_messages WHERE id=?", [savedEvent.conversationMessageId]))[0];
    const requestRow = (await database.query<RequestRow>("SELECT * FROM channel_execution_requests WHERE channel_provider_event_id=?", [savedEvent.id]))[0];
    const bindingRow = savedEvent.conversationId === null ? undefined : (await database.query<BindingRow>("SELECT * FROM whatsapp_conversation_bindings WHERE whatsapp_connection_id=? AND conversation_id=?", [active.id, savedEvent.conversationId]))[0];
    if (!inboundRow || !requestRow || !bindingRow) throw new Error("Inbound replay could not be resolved.");
    const inbound = message(inboundRow), savedBinding = binding(bindingRow);
    if (inbound.conversationId !== savedBinding.conversationId || inbound.senderParticipantId !== savedBinding.customerParticipantId || inbound.direction !== value.inbound.direction || inbound.content !== value.inbound.content || inbound.idempotencyKey !== value.inbound.idempotencyKey) throw new Error("Inbound replay conflicts with the durable message.");
    const capturedMedia = await this.captureMedia(database, active, savedEvent, attachments, true);
    return Object.freeze({ kind: "replayed", connection: active, event: savedEvent, inbound, request: request(requestRow), binding: savedBinding, media: Object.freeze(capturedMedia) });
  }

  private async captureMedia(database: SqlDatabase, active: WhatsAppConnection, savedEvent: ChannelProviderEvent, attachments: readonly AsyncWhatsAppInboundAttachment[], replay = false): Promise<WhatsAppInboundMedia[]> {
    const existing = await database.query<MediaRow>("SELECT * FROM whatsapp_inbound_media WHERE whatsapp_connection_id=? AND channel_provider_event_id=? ORDER BY ordinal,provider_media_id", [active.id, savedEvent.id]);
    if (replay && existing.length !== attachments.length) throw new Error("Inbound replay conflicts with the durable media descriptor.");
    const captured: WhatsAppInboundMedia[] = [];
    for (const attachment of attachments) {
      if (replay) {
        const stored = existing.find(row => row.provider_media_id === attachment.descriptor.providerMediaId && Number(row.ordinal) === attachment.descriptor.ordinal);
        if (!stored || stored.provider_kind !== attachment.descriptor.kind || stored.declared_mime !== attachment.descriptor.declaredMime || stored.safe_filename !== attachment.descriptor.filename) throw new Error("Inbound replay conflicts with the durable media descriptor.");
        captured.push(media(stored));
        continue;
      }
      await database.execute("INSERT INTO whatsapp_inbound_media(id,workspace_id,company_id,whatsapp_connection_id,channel_provider_event_id,conversation_message_id,provider_media_id,provider_kind,declared_mime,safe_filename,ordinal,caption_present,state,media_asset_id,failure_code,attempt_count,next_attempt_at,created_at,updated_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'pending_download',NULL,NULL,0,NULL,?,?,NULL)", [attachment.id, active.workspaceId, active.companyId, active.id, savedEvent.id, savedEvent.conversationMessageId!, attachment.descriptor.providerMediaId, attachment.descriptor.kind, attachment.descriptor.declaredMime, attachment.descriptor.filename, attachment.descriptor.ordinal, attachment.descriptor.caption === null ? 0 : 1, attachment.createdAt, attachment.updatedAt]);
      const stored = (await database.query<MediaRow>("SELECT * FROM whatsapp_inbound_media WHERE whatsapp_connection_id=? AND channel_provider_event_id=? AND provider_media_id=? AND ordinal=?", [active.id, savedEvent.id, attachment.descriptor.providerMediaId, attachment.descriptor.ordinal]))[0];
      if (!stored || stored.provider_kind !== attachment.descriptor.kind || stored.declared_mime !== attachment.descriptor.declaredMime || stored.safe_filename !== attachment.descriptor.filename) throw new Error("WhatsApp inbound media could not be persisted.");
      captured.push(media(stored));
    }
    return captured;
  }

  public async leaseExecutionRequests(owner: string, now: string, expiresAt: string, limit: number): Promise<readonly ChannelExecutionRequest[]> { if (!Number.isSafeInteger(limit) || limit < 1) return []; return this.database.transaction(async database => { const rows = await database.query<RequestRow>("SELECT r.* FROM channel_execution_requests r JOIN channel_provider_events e ON e.id=r.channel_provider_event_id JOIN whatsapp_connections w ON w.id=e.transport_connection_id WHERE e.transport_provider='meta_whatsapp_cloud' AND w.status='active' AND r.media_gate_state='open' AND (r.state='pending' OR (r.state='leased' AND r.lease_expires_at<=?)) ORDER BY r.created_at,r.id LIMIT ?", [now, limit]); const leased: ChannelExecutionRequest[] = []; for (const row of rows) { const changed = await database.execute("UPDATE channel_execution_requests SET state='leased',lease_owner=?,lease_expires_at=?,updated_at=? WHERE id=? AND (state='pending' OR (state='leased' AND lease_expires_at<=?))", [owner, expiresAt, now, row.id, now]); if (Number(changed.rowsAffected) === 1) leased.push(request({ ...row, state: "leased", lease_owner: owner, lease_expires_at: expiresAt, updated_at: now })); } return Object.freeze(leased); }); }
  public async loadLeasedExecutionContext(context: { readonly workspaceId: number; readonly workspaceKey: string }, companyId: number, connectionId: string, executionRequestId: ChannelExecutionRequestId, owner: string, now: string): Promise<AsyncWhatsAppLeasedExecutionContext | null> {
    const rows = await this.database.query<ResumeRow>("SELECT e.id AS event_id,e.communication_channel AS event_communication_channel,e.transport_provider AS event_transport_provider,e.transport_connection_id AS event_transport_connection_id,e.external_event_id AS event_external_event_id,e.state AS event_state,e.conversation_id AS event_conversation_id,e.conversation_message_id AS event_conversation_message_id,e.created_at AS event_created_at,e.updated_at AS event_updated_at,b.id AS binding_id,b.whatsapp_connection_id AS binding_connection_id,b.wa_id AS binding_wa_id,b.conversation_id AS binding_conversation_id,b.customer_participant_id AS binding_customer_participant_id,b.assistant_participant_id AS binding_assistant_participant_id,b.created_at AS binding_created_at,b.updated_at AS binding_updated_at,m.id AS message_id,m.conversation_id AS message_conversation_id,m.sender_participant_id AS message_sender_participant_id,m.direction AS message_direction,m.content AS message_content,m.idempotency_key AS message_idempotency_key,m.assistant_execution_record_id AS message_execution_record_id,m.created_at AS message_created_at FROM channel_execution_requests r JOIN channel_provider_events e ON e.id=r.channel_provider_event_id JOIN whatsapp_connections w ON w.id=e.transport_connection_id JOIN companies co ON co.id=w.company_id AND co.workspace_id=w.workspace_id JOIN whatsapp_conversation_bindings b ON b.whatsapp_connection_id=w.id AND b.conversation_id=e.conversation_id JOIN conversation_messages m ON m.id=e.conversation_message_id AND m.conversation_id=e.conversation_id WHERE r.id=? AND r.state='leased' AND r.lease_owner=? AND r.lease_expires_at>? AND w.workspace_id=? AND co.workspace_id=? AND w.company_id=? AND w.id=? AND e.communication_channel='whatsapp'", [executionRequestId, owner, now, context.workspaceId, context.workspaceId, companyId, connectionId]);
    const row = rows[0];
    return row ? Object.freeze({ event: event({ id: row.event_id, communication_channel: row.event_communication_channel, transport_provider: row.event_transport_provider, transport_connection_id: row.event_transport_connection_id, external_event_id: row.event_external_event_id, state: row.event_state, conversation_id: row.event_conversation_id, conversation_message_id: row.event_conversation_message_id, created_at: row.event_created_at, updated_at: row.event_updated_at }), binding: binding({ id: row.binding_id, whatsapp_connection_id: row.binding_connection_id, wa_id: row.binding_wa_id, conversation_id: row.binding_conversation_id, customer_participant_id: row.binding_customer_participant_id, assistant_participant_id: row.binding_assistant_participant_id, created_at: row.binding_created_at, updated_at: row.binding_updated_at }), inbound: message({ id: row.message_id, conversation_id: row.message_conversation_id, sender_participant_id: row.message_sender_participant_id, direction: row.message_direction, content: row.message_content, idempotency_key: row.message_idempotency_key, assistant_execution_record_id: row.message_execution_record_id, created_at: row.message_created_at }) }) : null;
  }
  public async finalizeLeasedExecution(value: AsyncWhatsAppExecutionFinalization): Promise<AssistantResponseFinalizationResult> { return this.database.transaction(async database => {
    const leased = (await database.query<{id:string;status:"active"|"inactive"}>("SELECT r.id,w.status FROM channel_execution_requests r JOIN channel_provider_events e ON e.id=r.channel_provider_event_id JOIN whatsapp_connections w ON w.id=e.transport_connection_id JOIN companies co ON co.id=w.company_id AND co.workspace_id=w.workspace_id WHERE r.id=? AND r.state='leased' AND r.media_gate_state='open' AND r.lease_owner=? AND r.lease_expires_at=? AND r.lease_expires_at>? AND w.workspace_id=? AND co.workspace_id=? AND w.company_id=? AND w.id=? AND e.id=? AND e.conversation_id=? AND e.conversation_message_id=? AND json_extract(r.snapshot_json,'$.assistantProfileId')=? AND json_extract(r.snapshot_json,'$.assistantParticipantId')=? AND json_extract(r.snapshot_json,'$.replyIdempotencyKey')=?",[value.requestId,value.owner,value.leaseExpiresAt,value.now,value.context.workspaceId,value.context.workspaceId,value.companyId,value.connectionId,value.eventId,value.conversationId,value.inboundMessageId,value.assistantProfileId,value.assistantParticipantId,value.replyIdempotencyKey]))[0];
    if (!leased) throw new AsyncWhatsAppExecutionLeaseLostError("WhatsApp execution lease was lost.");
    if (leased.status !== "active") {
      await database.execute("UPDATE channel_execution_requests SET state='completed',lease_owner=NULL,lease_expires_at=NULL,outcome='suppressed',updated_at=? WHERE id=? AND state='leased' AND lease_owner=? AND lease_expires_at=?",[value.now,value.requestId,value.owner,value.leaseExpiresAt]);
      await database.execute("UPDATE channel_provider_events SET state='completed',updated_at=? WHERE id=? AND state IN ('claimed','processing')",[value.now,value.eventId]);
      return Object.freeze({kind:"authority_lost"});
    }
    const current=(await database.query<{updated_at:string}>("SELECT c.updated_at FROM conversations c JOIN companies co ON co.id=c.company_id WHERE c.id=? AND c.company_id=? AND co.workspace_id=? AND c.state='open'",[value.conversationId,value.companyId,value.context.workspaceId]))[0];
    if(!current)return Object.freeze({kind:"not_found"});
    const existing=(await database.query<MessageRow>("SELECT * FROM conversation_messages WHERE conversation_id=? AND idempotency_key=?",[value.conversationId,value.replyIdempotencyKey]))[0];
    if (!existing) {
      await database.execute("INSERT INTO conversation_controls(conversation_id,state,controlling_actor_id,last_controlling_actor_id,taken_at,released_at,last_operator_activity_at,attention_reason,resolved_at,resolved_by,version,created_at,updated_at) VALUES(?,'automated',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,?,?) ON CONFLICT(conversation_id) DO NOTHING",[value.conversationId,current.updated_at,current.updated_at]);
      const control=(await database.query<{state:string;authority_generation:number}>("SELECT state,authority_generation FROM conversation_controls WHERE conversation_id=?",[value.conversationId]))[0];
      if (!control || control.state !== "automated" || Number(control.authority_generation) !== value.authorityGeneration) return Object.freeze({kind:"authority_lost"});
    }
    let outbound: ConversationMessage;
    if(existing){outbound=message(existing);if(outbound.direction!=="outbound"||outbound.executionRecordId!==value.executionRecordId)throw new Error("WhatsApp outbound finalization conflicts.");}
    else { await database.execute("INSERT INTO conversation_controls(conversation_id,state,controlling_actor_id,last_controlling_actor_id,taken_at,released_at,last_operator_activity_at,attention_reason,resolved_at,resolved_by,version,created_at,updated_at) VALUES(?,'automated',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,?,?) ON CONFLICT(conversation_id) DO NOTHING",[value.conversationId,current.updated_at,current.updated_at]);const control=(await database.query<{state:string;authority_generation:number}>("SELECT state,authority_generation FROM conversation_controls WHERE conversation_id=?",[value.conversationId]))[0];const owned=(await database.query<{id:string}>("SELECT id FROM assistant_execution_records WHERE id=? AND company_id=? AND assistant_profile_id=? AND purpose='operational_execution' AND state IN ('answered','safe_fallback') AND json_extract(execution_snapshot_json,'$.conversationId')=? AND json_extract(execution_snapshot_json,'$.authorityGeneration')=?",[value.executionRecordId,value.companyId,value.assistantProfileId,value.conversationId,value.authorityGeneration]))[0];if(!owned)return Object.freeze({kind:"execution_not_owned"});if(!control||control.state==="human_controlled"||Number(control.authority_generation)!==value.authorityGeneration)return Object.freeze({kind:"authority_lost"});const inserted=await database.execute("INSERT INTO conversation_messages(id,conversation_id,sender_participant_id,direction,content,idempotency_key,assistant_execution_record_id,created_at) SELECT ?,c.id,p.id,'outbound',?,?,?,? FROM conversations c JOIN conversation_participants p ON p.id=? AND p.conversation_id=c.id JOIN companies co ON co.id=c.company_id WHERE c.id=? AND c.company_id=? AND co.workspace_id=?",[value.outboundMessageId,value.content,value.replyIdempotencyKey,value.executionRecordId,value.now,value.assistantParticipantId,value.conversationId,value.companyId,value.context.workspaceId]);if(Number(inserted.rowsAffected)!==1)throw new Error("WhatsApp outbound message could not be persisted.");const row=(await database.query<MessageRow>("SELECT * FROM conversation_messages WHERE id=?",[value.outboundMessageId]))[0];if(!row)throw new Error("WhatsApp outbound message could not be read.");outbound=message(row);}
    await database.execute("INSERT INTO provider_message_records(id,communication_channel,transport_provider,direction,transport_connection_id,conversation_message_id,external_message_id,created_at,updated_at) VALUES(?,'whatsapp','meta_whatsapp_cloud','outbound',?,?,NULL,?,?) ON CONFLICT(transport_provider,transport_connection_id,conversation_message_id) DO NOTHING",[value.providerMessageId,value.connectionId,outbound.id,value.now,value.now]);
    const provider=(await database.query<{id:string}>("SELECT id FROM provider_message_records WHERE transport_provider='meta_whatsapp_cloud' AND transport_connection_id=? AND conversation_message_id=? AND direction='outbound'",[value.connectionId,outbound.id]))[0];if(!provider)throw new Error("WhatsApp provider message could not be persisted.");
    await database.execute("INSERT INTO outbound_deliveries(id,provider_message_record_id,transport_connection_id,state,attempt_count,next_attempt_at,lease_owner,lease_expires_at,safe_error_category,expected_authority_generation,created_at,updated_at) VALUES(?,?,?,'pending',0,?,NULL,NULL,NULL,?,?,?) ON CONFLICT(provider_message_record_id,transport_connection_id) DO NOTHING",[value.deliveryId,provider.id,value.connectionId,value.now,value.authorityGeneration,value.now,value.now]);
    const changed=await database.execute("UPDATE channel_execution_requests SET state='completed',lease_owner=NULL,lease_expires_at=NULL,outcome=?,updated_at=? WHERE id=? AND state='leased' AND media_gate_state='open' AND lease_owner=? AND lease_expires_at=? AND lease_expires_at>? AND channel_provider_event_id=? AND EXISTS(SELECT 1 FROM channel_provider_events e JOIN whatsapp_connections w ON w.id=e.transport_connection_id JOIN companies co ON co.id=w.company_id AND co.workspace_id=w.workspace_id WHERE e.id=channel_execution_requests.channel_provider_event_id AND e.conversation_id=? AND e.conversation_message_id=? AND w.workspace_id=? AND w.company_id=? AND w.id=?)",[value.outcome,value.now,value.requestId,value.owner,value.leaseExpiresAt,value.now,value.eventId,value.conversationId,value.inboundMessageId,value.context.workspaceId,value.companyId,value.connectionId]);
    if(Number(changed.rowsAffected)!==1)throw new AsyncWhatsAppExecutionLeaseLostError("WhatsApp execution lease was lost.");
    await database.execute("UPDATE channel_provider_events SET state='completed',updated_at=? WHERE id=? AND state IN ('claimed','processing')",[value.now,value.eventId]);
    const control=(await database.query<{version:number;authority_generation:number}>("SELECT version,authority_generation FROM conversation_controls WHERE conversation_id=?",[value.conversationId]))[0];
    if (!control) throw new Error("WhatsApp conversation control could not be resolved.");
    await database.execute("INSERT INTO conversation_events(id,workspace_id,company_id,conversation_id,event_type,actor_user_id,control_version,authority_generation,related_message_id,related_operation_id,occurred_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM conversation_events WHERE workspace_id=? AND company_id=? AND conversation_id=? AND event_type='assistant_message_created' AND related_message_id=?)",[`cev_${randomUUID().replaceAll("-","")}`,value.context.workspaceId,value.companyId,value.conversationId,"assistant_message_created",null,control.version,control.authority_generation,outbound.id,null,value.now,value.context.workspaceId,value.companyId,value.conversationId,outbound.id]);
    return Object.freeze({kind:existing?"replayed":"finalized",message:outbound});
  }); }
  public async settleExecutionRequest(id: ChannelExecutionRequestId, owner: string, state: "completed" | "failed", outcome: string | null, updatedAt: string): Promise<ChannelExecutionRequest | null> { return this.database.transaction(async database => { const changed = await database.execute("UPDATE channel_execution_requests SET state=?,lease_owner=NULL,lease_expires_at=NULL,outcome=?,updated_at=? WHERE id=? AND state='leased' AND lease_owner=?", [state, outcome, updatedAt, id, owner]); if (Number(changed.rowsAffected) !== 1) return null; const row = (await database.query<RequestRow>("SELECT * FROM channel_execution_requests WHERE id=?", [id]))[0]; if (!row) return null; await database.execute("UPDATE channel_provider_events SET state=?,updated_at=? WHERE id=? AND state IN ('claimed','processing')", [state === "completed" ? "completed" : "failed", updatedAt, row.channel_provider_event_id]); return request(row); }); }
}
