import { randomUUID } from "node:crypto";
import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { MediaAssociationOwnerResolver, MediaRepositoryPort } from "../application/ports.js";
import type { SafeConversationAttachment } from "../application/safeConversationAttachment.js";
import { MediaDomainError, type MediaAsset, type MediaAssociation, type MediaBlob, type MediaBlobState } from "../domain/media.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";

type AssetRow = { id:string; workspace_id:number; company_id:number; kind:MediaAsset["kind"]; media_type:string; size_bytes:number|null; safe_filename:string|null; metadata_json:string; status:MediaAsset["status"]; created_at:string; archived_at:string|null; deleted_at:string|null; blob_id:string|null; };
type BlobRow = { id:string; workspace_id:number; company_id:number; sha256_digest:string; size_bytes:number; media_type:string; storage_reference:string; state:MediaBlobState; created_at:string; };
const asset = (row:AssetRow):MediaAsset => Object.freeze({id:row.id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),kind:row.kind,mediaType:row.media_type,sizeBytes:row.size_bytes===null?null:Number(row.size_bytes),filename:row.safe_filename,metadata:Object.freeze(JSON.parse(row.metadata_json) as Record<string,number>),status:row.status,createdAt:row.created_at,archivedAt:row.archived_at,deletedAt:row.deleted_at});
const blob = (row:BlobRow):MediaBlob => Object.freeze({id:row.id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),digest:row.sha256_digest,sizeBytes:Number(row.size_bytes),mediaType:row.media_type,storageReference:row.storage_reference,state:row.state,createdAt:row.created_at});
const eventId = ():string => `mae_${randomUUID().replaceAll("-","")}`;

/** Async media metadata persistence for SQLite and libSQL through SqlDatabase. */
export class AsyncMediaRepository implements MediaRepositoryPort {
  public constructor(private readonly database:SqlDatabase) {}
  public async reserve(c:WorkspaceContext,companyId:number,operation:string,key:string,fingerprint:string,value:MediaAsset,at:string) { return this.database.transaction(async d => { if(!await this.company(d,c,companyId)) throw new Error("Media company is outside workspace."); const existing=(await d.query<AssetRow & {request_fingerprint:string}>("SELECT a.*,i.request_fingerprint FROM media_idempotency i JOIN media_assets a ON a.id=i.asset_id WHERE i.workspace_id=? AND i.company_id=? AND i.operation=? AND i.idempotency_key=?",[c.workspaceId,companyId,operation,key]))[0]; if(existing){if(existing.request_fingerprint!==fingerprint)return {kind:"divergent" as const};return existing.status==="pending"?{kind:"in_progress" as const}:{kind:"same" as const,asset:asset(existing)};} await d.execute("INSERT INTO media_assets(id,workspace_id,company_id,blob_id,kind,media_type,size_bytes,safe_filename,metadata_json,status,created_at,archived_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,'pending',?,NULL,NULL)",[value.id,c.workspaceId,companyId,null,value.kind,value.mediaType,null,value.filename,JSON.stringify(value.metadata),at]);await d.execute("INSERT INTO media_idempotency(workspace_id,company_id,operation,idempotency_key,request_fingerprint,asset_id,created_at) VALUES(?,?,?,?,?,?,?)",[c.workspaceId,companyId,operation,key,fingerprint,value.id,at]);await this.event(d,c,companyId,value.id,"reserved",at);return {kind:"reserved" as const,asset:value}; }); }
  public async complete(c:WorkspaceContext,companyId:number,assetId:string,candidate:MediaBlob,at:string):Promise<MediaAsset|null>{return this.database.transaction(async d=>{const current=await this.row(d,c,companyId,assetId);if(!current||current.status!=="pending")return null;const found=(await d.query<BlobRow>("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND sha256_digest=? AND size_bytes=? AND media_type=? AND state='active'",[c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType]))[0],chosen=found?blob(found):candidate;if(!found)await d.execute("INSERT INTO media_blobs(id,workspace_id,company_id,sha256_digest,size_bytes,media_type,storage_reference,state,created_at) VALUES(?,?,?,?,?,?,?,'active',?)",[candidate.id,c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType,candidate.storageReference,at]);const updated=await d.execute("UPDATE media_assets SET blob_id=?,media_type=?,size_bytes=?,status='ready' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'",[chosen.id,chosen.mediaType,chosen.sizeBytes,assetId,c.workspaceId,companyId]);if(Number(updated.rowsAffected)!==1)return null;await this.event(d,c,companyId,assetId,"ready",at);return this.findAssetOn(d,c,companyId,assetId);});}
  public async fail(c:WorkspaceContext,companyId:number,assetId:string,code:string,at:string):Promise<void>{await this.database.transaction(async d=>{await d.execute("UPDATE media_assets SET status='failed' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'",[assetId,c.workspaceId,companyId]);await this.event(d,c,companyId,assetId,`failed:${code}`,at);});}
  public async findAsset(c:WorkspaceContext,companyId:number,assetId:string):Promise<MediaAsset|null>{return this.findAssetOn(this.database,c,companyId,assetId);}
  public async findBlob(c:WorkspaceContext,companyId:number,digest:string,sizeBytes:number,mediaType:string):Promise<MediaBlob|null>{const row=(await this.database.query<BlobRow>("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND sha256_digest=? AND size_bytes=? AND media_type=? AND state='active'",[c.workspaceId,companyId,digest,sizeBytes,mediaType]))[0];return row?blob(row):null;}
  public async archive(c:WorkspaceContext,companyId:number,assetId:string,at:string):Promise<MediaAsset|null>{return this.database.transaction(async d=>{const changed=await d.execute("UPDATE media_assets SET status='archived',archived_at=? WHERE id=? AND workspace_id=? AND company_id=? AND status='ready'",[at,assetId,c.workspaceId,companyId]);if(Number(changed.rowsAffected)!==1)return null;await this.event(d,c,companyId,assetId,"archived",at);return this.findAssetOn(d,c,companyId,assetId);});}
  public async delete(c:WorkspaceContext,companyId:number,assetId:string,at:string):Promise<{readonly asset:MediaAsset;readonly reclaim:MediaBlob|null}|null>{return this.database.transaction(async d=>{const current=await this.row(d,c,companyId,assetId);if(!current||!["ready","archived"].includes(current.status))return null;if((await d.query<{id:string}>("SELECT id FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? LIMIT 1",[c.workspaceId,companyId,assetId])).length)throw new MediaDomainError("media_asset_has_associations");await d.execute("UPDATE media_assets SET status='deleted',deleted_at=? WHERE id=? AND workspace_id=? AND company_id=?",[at,assetId,c.workspaceId,companyId]);await this.event(d,c,companyId,assetId,"deleted",at);let reclaim:MediaBlob|null=null;if(current.blob_id!==null&&(await d.query<{id:string}>("SELECT id FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('pending','ready','archived') LIMIT 1",[c.workspaceId,companyId,current.blob_id])).length===0){const row=(await d.query<BlobRow>("SELECT * FROM media_blobs WHERE id=? AND workspace_id=? AND company_id=? AND state='active'",[current.blob_id,c.workspaceId,companyId]))[0];if(row){await d.execute("UPDATE media_blobs SET state='reclaim_pending' WHERE id=? AND state='active'",[current.blob_id]);reclaim=Object.freeze({...blob(row),state:"reclaim_pending"});await this.event(d,c,companyId,assetId,"physical_reclaim_marked",at);}}const saved=await this.findAssetOn(d,c,companyId,assetId);if(!saved)throw new Error("Media asset could not be deleted.");return {asset:saved,reclaim};});}
  public async finalizeReclaim(c:WorkspaceContext,companyId:number,blobId:string,at:string):Promise<void>{await this.database.transaction(async d=>{const changed=await d.execute("UPDATE media_blobs SET state='reclaimed' WHERE id=? AND workspace_id=? AND company_id=? AND state='reclaim_pending' AND NOT EXISTS(SELECT 1 FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('pending','ready','archived'))",[blobId,c.workspaceId,companyId,c.workspaceId,companyId,blobId]);if(Number(changed.rowsAffected)===1){const row=(await d.query<{id:string}>("SELECT id FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status='deleted' ORDER BY rowid DESC LIMIT 1",[c.workspaceId,companyId,blobId]))[0];if(row)await this.event(d,c,companyId,row.id,"physical_reclaim_finalized",at);}});}
  public async createAssociation(c:WorkspaceContext,value:MediaAssociation,at:string,owns:()=>boolean|Promise<boolean>):Promise<MediaAssociation|null>{return this.database.transaction(async d=>{if(!await this.company(d,c,value.companyId)||!await owns())return null;const current=await this.row(d,c,value.companyId,value.assetId);if(!current||current.status!=="ready"||current.archived_at!==null||current.deleted_at!==null)return null;const existing=(await d.query<{id:string;created_at:string}>("SELECT id,created_at FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? AND owner_type=? AND owner_id=?",[c.workspaceId,value.companyId,value.assetId,value.ownerType,value.ownerId]))[0];if(existing)return Object.freeze({...value,id:existing.id,createdAt:existing.created_at});await d.execute("INSERT INTO media_asset_associations(id,workspace_id,company_id,asset_id,owner_type,owner_id,created_at) VALUES(?,?,?,?,?,?,?)",[value.id,c.workspaceId,value.companyId,value.assetId,value.ownerType,value.ownerId,at]);await this.event(d,c,value.companyId,value.assetId,"association_created",at);return value;});}
  public async listAssociations(c:WorkspaceContext,companyId:number,assetId:string):Promise<readonly MediaAssociation[]>{return (await this.database.query<{id:string;workspace_id:number;company_id:number;asset_id:string;owner_type:MediaAssociation["ownerType"];owner_id:string;created_at:string}>("SELECT * FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? ORDER BY created_at,id",[c.workspaceId,companyId,assetId])).map(row=>Object.freeze({id:row.id,assetId:row.asset_id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),ownerType:row.owner_type,ownerId:row.owner_id,createdAt:row.created_at}));}
  public async open(c:WorkspaceContext,companyId:number,assetId:string):Promise<MediaBlob|null>{const row=(await this.database.query<BlobRow>("SELECT b.* FROM media_assets a JOIN media_blobs b ON b.id=a.blob_id WHERE a.id=? AND a.workspace_id=? AND a.company_id=? AND a.status='ready' AND b.state='active'",[assetId,c.workspaceId,companyId]))[0];return row?blob(row):null;}
  public async listEvents(c:WorkspaceContext,companyId:number,assetId:string):Promise<readonly string[]>{return (await this.database.query<{event_type:string}>("SELECT event_type FROM media_asset_events WHERE workspace_id=? AND company_id=? AND asset_id=? ORDER BY rowid",[c.workspaceId,companyId,assetId])).map(row=>row.event_type);}
  public async listPendingReclaims(c:WorkspaceContext,companyId:number):Promise<readonly MediaBlob[]>{return (await this.database.query<BlobRow>("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND state='reclaim_pending' ORDER BY id",[c.workspaceId,companyId])).map(blob);}
  private async findAssetOn(d:SqlDatabase,c:WorkspaceContext,companyId:number,assetId:string):Promise<MediaAsset|null>{const row=await this.row(d,c,companyId,assetId);return row?asset(row):null;}
  private async row(d:SqlDatabase,c:WorkspaceContext,companyId:number,id:string):Promise<AssetRow|undefined>{return (await d.query<AssetRow>("SELECT * FROM media_assets WHERE id=? AND workspace_id=? AND company_id=?",[id,c.workspaceId,companyId]))[0];}
  private async company(d:SqlDatabase,c:WorkspaceContext,companyId:number):Promise<boolean>{return (await d.query<{id:number}>("SELECT id FROM companies WHERE workspace_id=? AND id=?",[c.workspaceId,companyId])).length>0;}
  private async event(d:SqlDatabase,c:WorkspaceContext,companyId:number,assetId:string,type:string,at:string):Promise<void>{await d.execute("INSERT INTO media_asset_events(id,workspace_id,company_id,asset_id,event_type,occurred_at) VALUES(?,?,?,?,?,?)",[eventId(),c.workspaceId,companyId,assetId,type,at]);}
}

export class AsyncConversationMessageMediaAssociationOwnerResolver implements MediaAssociationOwnerResolver {
  public constructor(private readonly database:SqlDatabase) {}
  public async owns(context:WorkspaceContext,companyId:number,type:MediaAssociation["ownerType"],id:string):Promise<boolean>{if(type!=="conversation_message")return false;return (await this.database.query<{id:string}>("SELECT m.id FROM conversation_messages m JOIN conversations v ON v.id=m.conversation_id JOIN companies c ON c.id=v.company_id WHERE m.id=? AND c.workspace_id=? AND c.id=?",[id,context.workspaceId,companyId])).length>0;}
}

export class AsyncSafeConversationAttachmentRepository {
  public constructor(private readonly database:SqlDatabase) {}
  public async getSafeConversationAttachments(context:WorkspaceContext,companyId:number,conversationMessageId:string):Promise<readonly SafeConversationAttachment[]>{if(!Number.isSafeInteger(companyId)||companyId<1||typeof conversationMessageId!=="string")return [];const rows=await this.database.query<{kind:string;media_type:string;safe_filename:string|null}>("SELECT a.kind,a.media_type,a.safe_filename FROM media_asset_associations ma JOIN media_assets a ON a.id=ma.asset_id AND a.workspace_id=ma.workspace_id AND a.company_id=ma.company_id JOIN conversation_messages m ON m.id=ma.owner_id JOIN conversations v ON v.id=m.conversation_id JOIN companies c ON c.id=a.company_id AND c.workspace_id=a.workspace_id WHERE ma.workspace_id=? AND ma.company_id=? AND ma.owner_type='conversation_message' AND ma.owner_id=? AND a.status='ready' AND a.archived_at IS NULL AND a.deleted_at IS NULL AND v.company_id=a.company_id ORDER BY a.kind,a.safe_filename,ma.id LIMIT 16",[context.workspaceId,companyId,conversationMessageId]);return Object.freeze(rows.flatMap((row):SafeConversationAttachment[]=>{if((row.kind!=="image"&&row.kind!=="document"&&row.kind!=="audio")||!safe(row.media_type,160))return[];const filename=row.safe_filename===null?undefined:safe(row.safe_filename,180);return row.safe_filename!==null&&!filename?[]:[Object.freeze({kind:row.kind,status:"available",mimeType:row.media_type,...(filename?{filename}:{})})];}));}
}

function safe(value:string,maximum:number):string|null{const normalized=value.normalize("NFKC").trim();return normalized&&normalized.length<=maximum&&!/[\u0000-\u001f\u007f]/u.test(normalized)?normalized:null;}
