import { randomUUID } from "node:crypto";
import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { MediaAssociationOwnerResolver, MediaRepositoryPort } from "../application/ports.js";
import type { SafeConversationAttachment } from "../application/safeConversationAttachment.js";
import { MediaDomainError, type MediaAsset, type MediaAssociation, type MediaBlob, type MediaBlobState, type MediaIngestAttempt, type MediaIngestAttemptState } from "../domain/media.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";

type AssetRow = { id:string; workspace_id:number; company_id:number; kind:MediaAsset["kind"]; media_type:string; size_bytes:number|null; safe_filename:string|null; metadata_json:string; status:MediaAsset["status"]; created_at:string; archived_at:string|null; deleted_at:string|null; blob_id:string|null; };
type BlobRow = { id:string; workspace_id:number; company_id:number; sha256_digest:string; size_bytes:number; media_type:string; storage_reference:string; state:MediaBlobState; created_at:string; };
type AttemptRow={asset_id:string;workspace_id:number;company_id:number;candidate_blob_id:string;staging_storage_reference:string;final_storage_reference:string;sha256_digest:string;size_bytes:number;inspected_media_type:string;state:MediaIngestAttemptState;lease_owner:string|null;lease_token:string|null;lease_expires_at:string|null;attempt_count:number;safe_failure_category:string|null;created_at:string;updated_at:string;settled_at:string|null;};
const asset = (row:AssetRow):MediaAsset => Object.freeze({id:row.id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),kind:row.kind,mediaType:row.media_type,sizeBytes:row.size_bytes===null?null:Number(row.size_bytes),filename:row.safe_filename,metadata:Object.freeze(JSON.parse(row.metadata_json) as Record<string,number>),status:row.status,createdAt:row.created_at,archivedAt:row.archived_at,deletedAt:row.deleted_at});
const blob = (row:BlobRow):MediaBlob => Object.freeze({id:row.id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),digest:row.sha256_digest,sizeBytes:Number(row.size_bytes),mediaType:row.media_type,storageReference:row.storage_reference,state:row.state,createdAt:row.created_at});
const attempt=(row:AttemptRow):MediaIngestAttempt=>Object.freeze({assetId:row.asset_id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),candidateBlobId:row.candidate_blob_id,stagingStorageReference:row.staging_storage_reference,finalStorageReference:row.final_storage_reference,digest:row.sha256_digest,sizeBytes:Number(row.size_bytes),inspectedMediaType:row.inspected_media_type,state:row.state,leaseOwner:row.lease_owner,leaseToken:row.lease_token,leaseExpiresAt:row.lease_expires_at,attemptCount:Number(row.attempt_count),failureCategory:row.safe_failure_category,createdAt:row.created_at,updatedAt:row.updated_at,settledAt:row.settled_at});
const eventId = ():string => `mae_${randomUUID().replaceAll("-","")}`;
/** Async media metadata persistence for SQLite and libSQL through SqlDatabase. */
export class AsyncMediaRepository implements MediaRepositoryPort {
  public constructor(private readonly database:SqlDatabase) {}
  public async resolve(c:WorkspaceContext,companyId:number,operation:string,key:string,fingerprint:string){return this.resolveOn(this.database,c,companyId,operation,key,fingerprint);}
  public async reserve(c:WorkspaceContext,companyId:number,operation:string,key:string,fingerprint:string,value:MediaAsset,ingest:MediaIngestAttempt,at:string) { if(!await this.company(this.database,c,companyId))throw new Error("Media company is outside workspace.");for(let retry=0;retry<4;retry+=1){try{await this.database.writeBatch([{sql:"INSERT INTO media_assets(id,workspace_id,company_id,blob_id,kind,media_type,size_bytes,safe_filename,metadata_json,status,created_at,archived_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,'pending',?,NULL,NULL)",args:[value.id,c.workspaceId,companyId,null,value.kind,value.mediaType,null,value.filename,JSON.stringify(value.metadata),at]},{sql:"INSERT INTO media_idempotency(workspace_id,company_id,operation,idempotency_key,request_fingerprint,asset_id,created_at) VALUES(?,?,?,?,?,?,?)",args:[c.workspaceId,companyId,operation,key,fingerprint,value.id,at]},{sql:"INSERT INTO media_ingest_attempts(asset_id,workspace_id,company_id,candidate_blob_id,staging_storage_reference,final_storage_reference,sha256_digest,size_bytes,inspected_media_type,state,lease_owner,lease_token,lease_expires_at,attempt_count,safe_failure_category,created_at,updated_at,settled_at) VALUES(?,?,?,?,?,?,?,?,?,'reserved',NULL,NULL,NULL,0,NULL,?,?,NULL)",args:[value.id,c.workspaceId,companyId,ingest.candidateBlobId,ingest.stagingStorageReference,ingest.finalStorageReference,ingest.digest,ingest.sizeBytes,ingest.inspectedMediaType,at,at]},{sql:"INSERT INTO media_asset_events(id,workspace_id,company_id,asset_id,event_type,occurred_at) VALUES(?,?,?,?,?,?)",args:[eventId(),c.workspaceId,companyId,value.id,"reserved",at]}]);return {kind:"reserved" as const,asset:value};}catch(error:unknown){if(idempotencyConstraint(error)){const resolved=await this.reconcile(c,companyId,operation,key,fingerprint);if(resolved)return resolved;throw new MediaDomainError("media_storage_failed");}if(!contention(error))throw error;if(retry<3)await new Promise<void>(resolve=>setTimeout(resolve,25*(retry+1)));}}for(let reconciliation=0;reconciliation<3;reconciliation+=1){const resolved=await this.reconcile(c,companyId,operation,key,fingerprint);if(resolved)return resolved;if(reconciliation<2)await new Promise<void>(resolve=>setTimeout(resolve,25*(reconciliation+1)));}throw new MediaDomainError("media_storage_failed"); }
  public async markStaged(c:WorkspaceContext,companyId:number,assetId:string,at:string):Promise<boolean>{return this.database.transaction(async d=>Number((await d.execute("UPDATE media_ingest_attempts SET state='staged',attempt_count=attempt_count+1,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state='reserved'",[at,assetId,c.workspaceId,companyId])).rowsAffected)===1);}
  public async markPromoted(c:WorkspaceContext,companyId:number,assetId:string,at:string):Promise<boolean>{return this.database.transaction(async d=>Number((await d.execute("UPDATE media_ingest_attempts SET state='promoted',attempt_count=attempt_count+1,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state='staged'",[at,assetId,c.workspaceId,companyId])).rowsAffected)===1);}
  public async complete(c:WorkspaceContext,companyId:number,assetId:string,candidate:MediaBlob,at:string):Promise<MediaAsset|null>{return this.database.transaction(async d=>{const current=await this.row(d,c,companyId,assetId),ingest=await this.attempt(d,c,companyId,assetId);if(!current||current.status!=="pending"||!ingest||ingest.state!=="promoted"||ingest.candidate_blob_id!==candidate.id||ingest.final_storage_reference!==candidate.storageReference)return null;const found=(await d.query<BlobRow>("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND sha256_digest=? AND size_bytes=? AND media_type=? AND state='active'",[c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType]))[0],chosen=found?blob(found):candidate;if(!found)await d.execute("INSERT INTO media_blobs(id,workspace_id,company_id,sha256_digest,size_bytes,media_type,storage_reference,state,created_at) VALUES(?,?,?,?,?,?,?,'active',?)",[candidate.id,c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType,candidate.storageReference,at]);const updated=await d.execute("UPDATE media_assets SET blob_id=?,media_type=?,size_bytes=?,status='ready' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'",[chosen.id,chosen.mediaType,chosen.sizeBytes,assetId,c.workspaceId,companyId]);if(Number(updated.rowsAffected)!==1)throw new Error("Media settlement lost its asset.");await d.execute("UPDATE media_ingest_attempts SET state='settled',safe_failure_category=NULL,settled_at=?,updated_at=? WHERE asset_id=? AND state='promoted'",[at,at,assetId]);await this.event(d,c,companyId,assetId,"ready",at);return this.findAssetOn(d,c,companyId,assetId);});}
  public async fail(c:WorkspaceContext,companyId:number,assetId:string,category:string,retryable:boolean,at:string):Promise<void>{await this.database.transaction(async d=>{const state=retryable?"retryable_failure":"terminal_failure";if(!retryable)await d.execute("UPDATE media_assets SET status='failed' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'",[assetId,c.workspaceId,companyId]);await d.execute("UPDATE media_ingest_attempts SET state=?,safe_failure_category=?,settled_at=CASE WHEN ? THEN NULL ELSE ? END,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state IN ('reserved','staged','promoted','retryable_failure')",[state,category,retryable?1:0,at,at,assetId,c.workspaceId,companyId]);await this.event(d,c,companyId,assetId,`failed:${category}`,at);});}
  public async findIngestAttempt(c:WorkspaceContext,companyId:number,assetId:string):Promise<MediaIngestAttempt|null>{const row=await this.attempt(this.database,c,companyId,assetId);return row?attempt(row):null;}
  public async findAsset(c:WorkspaceContext,companyId:number,assetId:string):Promise<MediaAsset|null>{return this.findAssetOn(this.database,c,companyId,assetId);}
  public async findBlob(c:WorkspaceContext,companyId:number,digest:string,sizeBytes:number,mediaType:string):Promise<MediaBlob|null>{const row=(await this.database.query<BlobRow>("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND sha256_digest=? AND size_bytes=? AND media_type=? AND state='active'",[c.workspaceId,companyId,digest,sizeBytes,mediaType]))[0];return row?blob(row):null;}
  public async archive(c:WorkspaceContext,companyId:number,assetId:string,at:string):Promise<MediaAsset|null>{return this.database.transaction(async d=>{const changed=await d.execute("UPDATE media_assets SET status='archived',archived_at=? WHERE id=? AND workspace_id=? AND company_id=? AND status='ready'",[at,assetId,c.workspaceId,companyId]);if(Number(changed.rowsAffected)!==1)return null;await this.event(d,c,companyId,assetId,"archived",at);return this.findAssetOn(d,c,companyId,assetId);});}
  public async delete(c:WorkspaceContext,companyId:number,assetId:string,at:string):Promise<{readonly asset:MediaAsset;readonly reclaim:MediaBlob|null}|null>{return this.database.transaction(async d=>{const current=await this.row(d,c,companyId,assetId);if(!current||!["ready","archived"].includes(current.status))return null;if((await d.query<{id:string}>("SELECT id FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? LIMIT 1",[c.workspaceId,companyId,assetId])).length)throw new MediaDomainError("media_asset_has_associations");await d.execute("UPDATE media_assets SET status='deleted',deleted_at=? WHERE id=? AND workspace_id=? AND company_id=?",[at,assetId,c.workspaceId,companyId]);await this.event(d,c,companyId,assetId,"deleted",at);let reclaim:MediaBlob|null=null;if(current.blob_id!==null&&(await d.query<{id:string}>("SELECT id FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('pending','ready','archived') LIMIT 1",[c.workspaceId,companyId,current.blob_id])).length===0){const row=(await d.query<BlobRow>("SELECT * FROM media_blobs WHERE id=? AND workspace_id=? AND company_id=? AND state='active'",[current.blob_id,c.workspaceId,companyId]))[0];if(row){await d.execute("UPDATE media_blobs SET state='reclaim_pending' WHERE id=? AND state='active'",[current.blob_id]);reclaim=Object.freeze({...blob(row),state:"reclaim_pending"});await this.event(d,c,companyId,assetId,"physical_reclaim_marked",at);}}const saved=await this.findAssetOn(d,c,companyId,assetId);if(!saved)throw new Error("Media asset could not be deleted.");return {asset:saved,reclaim};});}
  public async finalizeReclaim(c:WorkspaceContext,companyId:number,blobId:string,at:string):Promise<void>{await this.database.transaction(async d=>{const changed=await d.execute("UPDATE media_blobs SET state='reclaimed' WHERE id=? AND workspace_id=? AND company_id=? AND state='reclaim_pending' AND NOT EXISTS(SELECT 1 FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('pending','ready','archived'))",[blobId,c.workspaceId,companyId,c.workspaceId,companyId,blobId]);if(Number(changed.rowsAffected)===1){const row=(await d.query<{id:string}>("SELECT id FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status='deleted' ORDER BY rowid DESC LIMIT 1",[c.workspaceId,companyId,blobId]))[0];if(row)await this.event(d,c,companyId,row.id,"physical_reclaim_finalized",at);}});}
  public async createAssociation(c:WorkspaceContext,value:MediaAssociation,at:string,owns:()=>boolean|Promise<boolean>):Promise<MediaAssociation|null>{return this.database.transaction(async d=>{if(!await this.company(d,c,value.companyId)||!await owns())return null;const current=await this.row(d,c,value.companyId,value.assetId);if(!current||current.status!=="ready"||current.archived_at!==null||current.deleted_at!==null)return null;const existing=(await d.query<{id:string;created_at:string}>("SELECT id,created_at FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? AND owner_type=? AND owner_id=?",[c.workspaceId,value.companyId,value.assetId,value.ownerType,value.ownerId]))[0];if(existing)return Object.freeze({...value,id:existing.id,createdAt:existing.created_at});await d.execute("INSERT INTO media_asset_associations(id,workspace_id,company_id,asset_id,owner_type,owner_id,created_at) VALUES(?,?,?,?,?,?,?)",[value.id,c.workspaceId,value.companyId,value.assetId,value.ownerType,value.ownerId,at]);await this.event(d,c,value.companyId,value.assetId,"association_created",at);return value;});}
  public async listAssociations(c:WorkspaceContext,companyId:number,assetId:string):Promise<readonly MediaAssociation[]>{return (await this.database.query<{id:string;workspace_id:number;company_id:number;asset_id:string;owner_type:MediaAssociation["ownerType"];owner_id:string;created_at:string}>("SELECT * FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? ORDER BY created_at,id",[c.workspaceId,companyId,assetId])).map(row=>Object.freeze({id:row.id,assetId:row.asset_id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),ownerType:row.owner_type,ownerId:row.owner_id,createdAt:row.created_at}));}
  public async open(c:WorkspaceContext,companyId:number,assetId:string):Promise<MediaBlob|null>{const row=(await this.database.query<BlobRow>("SELECT b.* FROM media_assets a JOIN media_blobs b ON b.id=a.blob_id WHERE a.id=? AND a.workspace_id=? AND a.company_id=? AND a.status='ready' AND b.state='active'",[assetId,c.workspaceId,companyId]))[0];return row?blob(row):null;}
  public async listEvents(c:WorkspaceContext,companyId:number,assetId:string):Promise<readonly string[]>{return (await this.database.query<{event_type:string}>("SELECT event_type FROM media_asset_events WHERE workspace_id=? AND company_id=? AND asset_id=? ORDER BY rowid",[c.workspaceId,companyId,assetId])).map(row=>row.event_type);}
  public async listPendingReclaims(c:WorkspaceContext,companyId:number,limit?:number):Promise<readonly MediaBlob[]>{return (await this.database.query<BlobRow>(`SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND state='reclaim_pending' ORDER BY id${limit===undefined?"":" LIMIT ?"}`,[c.workspaceId,companyId,...(limit===undefined?[]:[limit])])).map(blob);}
  public async leaseIncomplete(c:WorkspaceContext,companyId:number,owner:string,token:string,now:string,expiresAt:string,limit:number):Promise<readonly MediaIngestAttempt[]>{return this.database.transaction(async d=>{const rows=await d.query<{asset_id:string}>("SELECT asset_id FROM media_ingest_attempts WHERE workspace_id=? AND company_id=? AND state IN ('reserved','staged','promoted','retryable_failure') AND (lease_expires_at IS NULL OR lease_expires_at<=?) ORDER BY updated_at,asset_id LIMIT ?",[c.workspaceId,companyId,now,limit]);for(const row of rows)await d.execute("UPDATE media_ingest_attempts SET lease_owner=?,lease_token=?,lease_expires_at=?,attempt_count=attempt_count+1,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state IN ('reserved','staged','promoted','retryable_failure') AND (lease_expires_at IS NULL OR lease_expires_at<=?)",[owner,token,expiresAt,now,row.asset_id,c.workspaceId,companyId,now]);return(await d.query<AttemptRow>("SELECT * FROM media_ingest_attempts WHERE workspace_id=? AND company_id=? AND lease_token=? ORDER BY updated_at,asset_id",[c.workspaceId,companyId,token])).map(attempt);});}
  public async markRecoveryStaged(c:WorkspaceContext,companyId:number,assetId:string,owner:string,token:string,at:string):Promise<boolean>{return this.database.transaction(async d=>Number((await d.execute("UPDATE media_ingest_attempts SET state='staged',updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state IN ('reserved','retryable_failure') AND lease_owner=? AND lease_token=? AND lease_expires_at>?",[at,assetId,c.workspaceId,companyId,owner,token,at])).rowsAffected)===1);}
  public async markRecoveryPromoted(c:WorkspaceContext,companyId:number,assetId:string,owner:string,token:string,at:string):Promise<boolean>{return this.database.transaction(async d=>Number((await d.execute("UPDATE media_ingest_attempts SET state='promoted',safe_failure_category=NULL,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state IN ('staged','retryable_failure') AND lease_owner=? AND lease_token=? AND lease_expires_at>?",[at,assetId,c.workspaceId,companyId,owner,token,at])).rowsAffected)===1);}
  public async settleRecovery(c:WorkspaceContext,companyId:number,assetId:string,owner:string,token:string,candidate:MediaBlob,at:string):Promise<MediaAsset|null>{return this.database.transaction(async d=>{const current=await this.row(d,c,companyId,assetId),ingest=await this.attempt(d,c,companyId,assetId);if(!current||current.status!=="pending"||!ingest||ingest.state!=="promoted"||ingest.lease_owner!==owner||ingest.lease_token!==token||!ingest.lease_expires_at||ingest.lease_expires_at<=at||ingest.candidate_blob_id!==candidate.id||ingest.final_storage_reference!==candidate.storageReference)return null;const found=(await d.query<BlobRow>("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND sha256_digest=? AND size_bytes=? AND media_type=? AND state='active'",[c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType]))[0],chosen=found?blob(found):candidate;if(!found)await d.execute("INSERT INTO media_blobs(id,workspace_id,company_id,sha256_digest,size_bytes,media_type,storage_reference,state,created_at) VALUES(?,?,?,?,?,?,?,'active',?)",[candidate.id,c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType,candidate.storageReference,at]);if(Number((await d.execute("UPDATE media_assets SET blob_id=?,media_type=?,size_bytes=?,status='ready' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'",[chosen.id,chosen.mediaType,chosen.sizeBytes,assetId,c.workspaceId,companyId])).rowsAffected)!==1)throw new Error("Media recovery settlement lost its asset.");await d.execute("UPDATE media_ingest_attempts SET state='settled',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,safe_failure_category=NULL,settled_at=?,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state='promoted' AND lease_owner=? AND lease_token=? AND lease_expires_at>?",[at,at,assetId,c.workspaceId,companyId,owner,token,at]);await this.event(d,c,companyId,assetId,"ready",at);return this.findAssetOn(d,c,companyId,assetId);});}
  public async failRecovery(c:WorkspaceContext,companyId:number,assetId:string,owner:string,token:string,category:string,retryable:boolean,at:string):Promise<boolean>{return this.database.transaction(async d=>{const result=await d.execute("UPDATE media_ingest_attempts SET state=?,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,safe_failure_category=?,settled_at=CASE WHEN ? THEN NULL ELSE ? END,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state IN ('reserved','staged','promoted','retryable_failure') AND lease_owner=? AND lease_token=? AND lease_expires_at>?",[retryable?"retryable_failure":"terminal_failure",category,retryable?1:0,at,at,assetId,c.workspaceId,companyId,owner,token,at]);if(Number(result.rowsAffected)!==1)return false;if(!retryable)await d.execute("UPDATE media_assets SET status='failed' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'",[assetId,c.workspaceId,companyId]);await this.event(d,c,companyId,assetId,`failed:${category}`,at);return true;});}
  public async leaseReclaims(c:WorkspaceContext,companyId:number,owner:string,token:string,now:string,expiresAt:string,limit:number):Promise<readonly MediaBlob[]>{return this.database.transaction(async d=>{const rows=await d.query<{id:string}>("SELECT id FROM media_blobs WHERE workspace_id=? AND company_id=? AND state='reclaim_pending' AND (reclaim_lease_expires_at IS NULL OR reclaim_lease_expires_at<=?) ORDER BY created_at,id LIMIT ?",[c.workspaceId,companyId,now,limit]);for(const row of rows)await d.execute("UPDATE media_blobs SET reclaim_lease_owner=?,reclaim_lease_token=?,reclaim_lease_expires_at=? WHERE id=? AND workspace_id=? AND company_id=? AND state='reclaim_pending' AND (reclaim_lease_expires_at IS NULL OR reclaim_lease_expires_at<=?)",[owner,token,expiresAt,row.id,c.workspaceId,companyId,now]);return(await d.query<BlobRow>("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND reclaim_lease_owner=? AND reclaim_lease_token=? AND reclaim_lease_expires_at>? ORDER BY id",[c.workspaceId,companyId,owner,token,now])).map(blob);});}
  public async finalizeLeasedReclaim(c:WorkspaceContext,companyId:number,blobId:string,owner:string,token:string,at:string):Promise<boolean>{return this.database.transaction(async d=>Number((await d.execute("UPDATE media_blobs SET state='reclaimed',reclaim_lease_owner=NULL,reclaim_lease_token=NULL,reclaim_lease_expires_at=NULL WHERE id=? AND workspace_id=? AND company_id=? AND state='reclaim_pending' AND reclaim_lease_owner=? AND reclaim_lease_token=? AND reclaim_lease_expires_at>? AND NOT EXISTS(SELECT 1 FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('pending','ready','archived'))",[blobId,c.workspaceId,companyId,owner,token,at,c.workspaceId,companyId,blobId])).rowsAffected)===1);}
  public async listReadyBlobs(c:WorkspaceContext,companyId:number,limit:number):Promise<readonly MediaBlob[]>{return(await this.database.query<BlobRow>("SELECT DISTINCT b.* FROM media_blobs b JOIN media_assets a ON a.blob_id=b.id AND a.workspace_id=b.workspace_id AND a.company_id=b.company_id WHERE b.workspace_id=? AND b.company_id=? AND b.state='active' AND a.status IN ('ready','archived') ORDER BY b.created_at,b.id LIMIT ?",[c.workspaceId,companyId,limit])).map(blob);}
  public async markBlobUnavailable(c:WorkspaceContext,companyId:number,blobId:string,category:string,at:string):Promise<boolean>{return this.database.transaction(async d=>{const rows=await d.query<{id:string}>("SELECT id FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('ready','archived')",[c.workspaceId,companyId,blobId]);if(!rows.length)return false;await d.execute("UPDATE media_assets SET status='failed',blob_id=NULL WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('ready','archived')",[c.workspaceId,companyId,blobId]);for(const row of rows)await this.event(d,c,companyId,row.id,`unavailable:${category}`,at);return true;});}
  public async referencesStorage(c:WorkspaceContext,companyId:number,reference:string):Promise<boolean>{return(await this.database.query<{id:string}>("SELECT id FROM media_blobs WHERE workspace_id=? AND company_id=? AND storage_reference=? UNION ALL SELECT asset_id id FROM media_ingest_attempts WHERE workspace_id=? AND company_id=? AND (staging_storage_reference=? OR final_storage_reference=?) LIMIT 1",[c.workspaceId,companyId,reference,c.workspaceId,companyId,reference,reference])).length>0;}
  public async listRecoveryScopes(limit:number):Promise<readonly {readonly workspaceId:number;readonly workspaceKey:string;readonly companyId:number}[]>{return(await this.database.query<{workspaceId:number;workspaceKey:string;companyId:number}>("SELECT c.workspace_id workspaceId,w.key workspaceKey,c.id companyId FROM companies c JOIN workspaces w ON w.id=c.workspace_id WHERE EXISTS(SELECT 1 FROM media_ingest_attempts i WHERE i.workspace_id=c.workspace_id AND i.company_id=c.id AND i.state IN ('reserved','staged','promoted','retryable_failure')) OR EXISTS(SELECT 1 FROM media_blobs b JOIN media_assets a ON a.blob_id=b.id WHERE b.workspace_id=c.workspace_id AND b.company_id=c.id AND a.status IN ('ready','archived')) OR EXISTS(SELECT 1 FROM media_blobs b WHERE b.workspace_id=c.workspace_id AND b.company_id=c.id AND b.state='reclaim_pending') ORDER BY c.workspace_id,c.id LIMIT ?",[limit])).map(value=>Object.freeze(value));}
  private async resolveOn(d:SqlDatabase,c:WorkspaceContext,companyId:number,operation:string,key:string,fingerprint:string){const existing=(await d.query<AssetRow&{request_fingerprint:string}>("SELECT a.*,i.request_fingerprint FROM media_idempotency i JOIN media_assets a ON a.id=i.asset_id WHERE i.workspace_id=? AND i.company_id=? AND i.operation=? AND i.idempotency_key=?",[c.workspaceId,companyId,operation,key]))[0];if(!existing)return{kind:"new" as const};if(existing.request_fingerprint!==fingerprint)return{kind:"divergent" as const};const prior=await this.attempt(d,c,companyId,existing.id);if(!prior&&existing.status==="pending")return{kind:"legacy_incomplete" as const};if(existing.status==="ready"&&prior?.state==="settled")return{kind:"same" as const,asset:asset(existing)};return prior?.state==="retryable_failure"?{kind:"retryable_failure" as const}:prior?.state==="terminal_failure"?{kind:"terminal_failure" as const}:{kind:"in_progress" as const};}
  private async reconcile(c:WorkspaceContext,companyId:number,operation:string,key:string,fingerprint:string):Promise<Exclude<Awaited<ReturnType<MediaRepositoryPort["resolve"]>>,{readonly kind:"new"}>|null>{try{const resolved=await this.resolveOn(this.database,c,companyId,operation,key,fingerprint);return resolved.kind==="new"?null:resolved;}catch{return null;}}
  private async findAssetOn(d:SqlDatabase,c:WorkspaceContext,companyId:number,assetId:string):Promise<MediaAsset|null>{const row=await this.row(d,c,companyId,assetId);return row?asset(row):null;}
  private async row(d:SqlDatabase,c:WorkspaceContext,companyId:number,id:string):Promise<AssetRow|undefined>{return (await d.query<AssetRow>("SELECT * FROM media_assets WHERE id=? AND workspace_id=? AND company_id=?",[id,c.workspaceId,companyId]))[0];}
  private async attempt(d:SqlDatabase,c:WorkspaceContext,companyId:number,assetId:string):Promise<AttemptRow|undefined>{return (await d.query<AttemptRow>("SELECT * FROM media_ingest_attempts WHERE asset_id=? AND workspace_id=? AND company_id=?",[assetId,c.workspaceId,companyId]))[0];}
  private async company(d:SqlDatabase,c:WorkspaceContext,companyId:number):Promise<boolean>{return (await d.query<{id:number}>("SELECT id FROM companies WHERE workspace_id=? AND id=?",[c.workspaceId,companyId])).length>0;}
  private async event(d:SqlDatabase,c:WorkspaceContext,companyId:number,assetId:string,type:string,at:string):Promise<void>{await d.execute("INSERT INTO media_asset_events(id,workspace_id,company_id,asset_id,event_type,occurred_at) VALUES(?,?,?,?,?,?)",[eventId(),c.workspaceId,companyId,assetId,type,at]);}
}

export class AsyncConversationMessageMediaAssociationOwnerResolver implements MediaAssociationOwnerResolver {
  public constructor(private readonly database:SqlDatabase) {}
  public async owns(context:WorkspaceContext,companyId:number,type:MediaAssociation["ownerType"],id:string):Promise<boolean>{if(type!=="conversation_message")return false;return (await this.database.query<{id:string}>("SELECT m.id FROM conversation_messages m JOIN conversations v ON v.id=m.conversation_id JOIN companies c ON c.id=v.company_id WHERE m.id=? AND c.workspace_id=? AND c.id=?",[id,context.workspaceId,companyId])).length>0;}
}

export class AsyncSafeConversationAttachmentRepository {
  public constructor(private readonly database:SqlDatabase) {}
  public async getSafeConversationAttachments(context:WorkspaceContext,companyId:number,conversationMessageId:string):Promise<readonly SafeConversationAttachment[]>{if(!Number.isSafeInteger(companyId)||companyId<1||typeof conversationMessageId!=="string")return [];const rows=await this.database.query<{kind:string;media_type:string;safe_filename:string|null}>("SELECT a.kind,a.media_type,a.safe_filename FROM media_asset_associations ma JOIN media_assets a ON a.id=ma.asset_id AND a.workspace_id=ma.workspace_id AND a.company_id=ma.company_id JOIN conversation_messages m ON m.id=ma.owner_id JOIN conversations v ON v.id=m.conversation_id JOIN companies c ON c.id=a.company_id AND c.workspace_id=a.workspace_id WHERE ma.workspace_id=? AND ma.company_id=? AND ma.owner_type='conversation_message' AND ma.owner_id=? AND a.status='ready' AND a.archived_at IS NULL AND a.deleted_at IS NULL AND v.company_id=a.company_id ORDER BY a.kind,a.safe_filename,ma.id LIMIT 16",[context.workspaceId,companyId,conversationMessageId]);return Object.freeze(rows.flatMap((row):SafeConversationAttachment[]=>{if((row.kind!=="image"&&row.kind!=="document"&&row.kind!=="audio")||!safe(row.media_type,160))return[];const filename=row.safe_filename===null?undefined:safe(row.safe_filename,180);return row.safe_filename!==null&&!filename?[]:[Object.freeze({kind:row.kind,status:"available",mimeType:row.media_type,...(filename?{filename}:{})})];}));}
}

function safe(value:string,maximum:number):string|null{const normalized=value.normalize("NFKC").trim();return normalized&&normalized.length<=maximum&&!/[\u0000-\u001f\u007f]/u.test(normalized)?normalized:null;}
function code(error:unknown):string|null{return typeof error==="object"&&error!==null&&"code" in error&&typeof (error as {code?:unknown}).code==="string"?(error as {code:string}).code:null;}
function message(error:unknown):string{return error instanceof Error?error.message:"";}
function contention(error:unknown):boolean{const value=code(error);return value==="SQLITE_BUSY"||value==="SQLITE_BUSY_RECOVERY"||value==="SQLITE_BUSY_SNAPSHOT"||value==="SQLITE_LOCKED"||/^(?:SQLITE_(?:BUSY|LOCKED)(?::|$)|database is locked$)/i.test(message(error));}
function idempotencyConstraint(error:unknown):boolean{const value=code(error),text=message(error);return (value==="SQLITE_CONSTRAINT"||value==="SQLITE_CONSTRAINT_UNIQUE"||value==="SQLITE_CONSTRAINT_PRIMARYKEY"||/UNIQUE constraint failed:/i.test(text))&&/UNIQUE constraint failed: media_idempotency\.(?:workspace_id|company_id|operation|idempotency_key)/i.test(text);}
