import type { BackupObjectStorage } from "./s3BackupObjectStorage.js";

export interface BackupRetentionConfiguration { readonly retentionDays:number;readonly minCompleteSets:number; }
export function backupRetentionConfiguration(environment:NodeJS.ProcessEnv=process.env):BackupRetentionConfiguration { const days=Number(environment.ATLAS_BACKUP_RETENTION_DAYS),sets=Number(environment.ATLAS_BACKUP_MIN_COMPLETE_SETS);if(!Number.isSafeInteger(days)||days<1||days>3650||!Number.isSafeInteger(sets)||sets<1||sets>100)throw new Error("Backup retention configuration is invalid.");return Object.freeze({retentionDays:days,minCompleteSets:sets}); }
export interface RetentionSet { readonly backupId:string;readonly createdAt:string;readonly manifestKey:string;readonly mediaBackupObjectKeys:readonly string[]; }
export interface BackupRetentionResult { readonly deleted:number;readonly locked:number;readonly protected:number;readonly pruned:number;readonly lockedSets:number; }
/** Applies retention only to discovered complete manifests. A manifest is deleted only after every media object is gone. */
export class BackupRetentionService { public constructor(private readonly storage:BackupObjectStorage,private readonly now:()=>Date=()=>new Date()){} public async prune(sets:readonly RetentionSet[],configuration:BackupRetentionConfiguration,activeBackupId:string|null):Promise<BackupRetentionResult>{const ordered=[...sets].sort((left,right)=>right.createdAt.localeCompare(left.createdAt));let deleted=0,locked=0,protectedSets=0,pruned=0,lockedSets=0;for(let index=0;index<ordered.length;index+=1){const set=ordered[index]!;if(index===0||index<configuration.minCompleteSets||set.backupId===activeBackupId||retained(set.createdAt,configuration.retentionDays,this.now())){protectedSets+=1;continue;}let setLocked=false;for(const key of set.mediaBackupObjectKeys){const outcome=await this.storage.delete(key);if(outcome==="locked"){locked+=1;setLocked=true;}else deleted+=1;}if(setLocked){lockedSets+=1;continue;}const manifest=await this.storage.delete(set.manifestKey);if(manifest==="locked"){locked+=1;lockedSets+=1;continue;}deleted+=1;pruned+=1;}return Object.freeze({deleted,locked,protected:protectedSets,pruned,lockedSets});} }
function retained(createdAt:string,retentionDays:number,now:Date):boolean{const created=new Date(createdAt);if(Number.isNaN(created.getTime()))return true;created.setUTCDate(created.getUTCDate()+retentionDays);return created>now;}
