import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createClient } from "@tursodatabase/api";
import type { SqlDatabase } from "../config/sqlDatabase.js";
import type { RotationCipher } from "../security/credentialReencryptionMaintenance.js";

const executeFile=promisify(execFile), timestamp=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/u, databaseName=/^[a-z0-9][a-z0-9-]{0,62}$/u;
export interface MediaInventoryItem { readonly reference:string; readonly digest:string; readonly sizeBytes:number; }
export interface DrManifest { readonly formatVersion:1; readonly backupId:string; readonly createdAt:string; readonly migrationHead:string; readonly database:{readonly mode:"turso_pitr";readonly sourceDatabase:string;readonly recoveryPoint:string}; readonly media:{readonly objectCount:number;readonly totalBytes:number;readonly inventoryChecksum:string}; readonly state:"started"|"media_complete"|"complete"|"failed"; }
export interface DatabaseRecoveryProvider { createPointInTimeRestore(sourceDatabase:string,targetDatabase:string,recoveryPoint:string):Promise<void>; verifyDatabaseExists(targetDatabase:string):Promise<void>; }
interface TursoPlatformClient { databases:{ create(name:string,input:{group:string;seed:{type:"database";name:string;timestamp:string}}):Promise<{hostname:string}>; get(name:string):Promise<{hostname:string}>; createToken(name:string,input:{expiration:"10m";authorization:"read-only"}):Promise<{jwt:string}>; }; }
export interface TursoManagementConfiguration { readonly org:string; readonly platformToken:string; readonly databaseName:string; readonly databaseGroup:string; }
export function tursoManagementConfiguration(environment:NodeJS.ProcessEnv=process.env):TursoManagementConfiguration { const org=environment.TURSO_ORG?.trim(),platformToken=environment.TURSO_PLATFORM_TOKEN?.trim(),databaseValue=environment.TURSO_DATABASE_NAME?.trim(),databaseGroup=environment.TURSO_DATABASE_GROUP?.trim();if(!org||!platformToken||!databaseValue||!databaseGroup||!databaseName.test(databaseValue)||!databaseName.test(databaseGroup))throw new Error("Turso disaster recovery configuration is invalid.");return Object.freeze({org,platformToken,databaseName:databaseValue,databaseGroup}); }
export interface RestoredDatabaseVerificationConnection { readonly url:string;readonly authToken:string; }
export class TursoPlatformDatabaseRecoveryProvider implements DatabaseRecoveryProvider { private readonly client:TursoPlatformClient; public constructor(configuration:TursoManagementConfiguration,client?:TursoPlatformClient){this.client=client??createClient({org:configuration.org,token:configuration.platformToken}) as unknown as TursoPlatformClient;this.group=configuration.databaseGroup;} private readonly group:string; public async createPointInTimeRestore(sourceDatabase:string,targetDatabase:string,recoveryPoint:string):Promise<void>{if(!databaseName.test(sourceDatabase)||!databaseName.test(targetDatabase)||sourceDatabase===targetDatabase||!timestamp.test(recoveryPoint))throw new Error("Turso recovery request is invalid.");try{await this.client.databases.create(targetDatabase,{group:this.group,seed:{type:"database",name:sourceDatabase,timestamp:recoveryPoint}});}catch{throw new Error("Turso recovery operation failed.");}} public async verifyDatabaseExists(targetDatabase:string):Promise<void>{if(!databaseName.test(targetDatabase))throw new Error("Turso recovery target is invalid.");try{await this.client.databases.get(targetDatabase);}catch{throw new Error("Turso recovery operation failed.");}} public async createVerificationConnection(targetDatabase:string):Promise<RestoredDatabaseVerificationConnection>{if(!databaseName.test(targetDatabase))throw new Error("Turso recovery target is invalid.");try{const [database,token]=await Promise.all([this.client.databases.get(targetDatabase),this.client.databases.createToken(targetDatabase,{expiration:"10m",authorization:"read-only"})]);if(!database.hostname||!token.jwt)throw new Error();return Object.freeze({url:`libsql://${database.hostname}`,authToken:token.jwt});}catch{throw new Error("Turso recovery operation failed.");}} }
export interface BackupMediaProvider { copy(backupId:string,item:MediaInventoryItem):Promise<void>; exists(backupId:string,item:MediaInventoryItem):Promise<boolean>; writeManifest(backupId:string,manifest:DrManifest):Promise<void>; readManifest(backupId:string):Promise<DrManifest>; }
export class DisasterRecoveryRepository { public constructor(private readonly database:SqlDatabase) {} public async migrationHead():Promise<string>{const rows=await this.database.query<{name:string}>("SELECT name FROM schema_migrations ORDER BY id DESC LIMIT 1");if(rows.length!==1)throw new Error("Recovery database migration metadata is invalid.");return rows[0]!.name;} public async mediaInventory():Promise<readonly MediaInventoryItem[]>{return(await this.database.query<{storage_reference:string;sha256_digest:string;size_bytes:number}>("SELECT storage_reference,sha256_digest,size_bytes FROM media_blobs WHERE state='active' ORDER BY rowid")).map(row=>Object.freeze({reference:row.storage_reference,digest:row.sha256_digest,sizeBytes:Number(row.size_bytes)}));} public async verifyReadOnly(expectedHead:string):Promise<void>{if(await this.migrationHead()!==expectedHead)throw new Error("Recovery database migration head is invalid.");const integrity=await this.database.query<{integrity_check:string}>("PRAGMA integrity_check");if(integrity.length!==1||integrity[0]?.integrity_check!=="ok")throw new Error("Recovery database integrity is invalid.");} }
export class TursoCliDatabaseRecoveryProvider implements DatabaseRecoveryProvider { public constructor(private readonly cliPath="turso") {} public async createPointInTimeRestore(sourceDatabase:string,targetDatabase:string,recoveryPoint:string):Promise<void>{if(!databaseName.test(sourceDatabase)||!databaseName.test(targetDatabase)||sourceDatabase===targetDatabase||!timestamp.test(recoveryPoint))throw new Error("Turso recovery request is invalid.");try{await executeFile(this.cliPath,["db","create",targetDatabase,"--from-db",sourceDatabase,"--timestamp",recoveryPoint],{windowsHide:true});}catch{throw new Error("Turso recovery operation failed.");}} public async verifyDatabaseExists(targetDatabase:string):Promise<void>{if(!databaseName.test(targetDatabase))throw new Error("Turso recovery target is invalid.");try{await executeFile(this.cliPath,["db","show",targetDatabase],{windowsHide:true});}catch{throw new Error("Turso recovery operation failed.");}} }
export interface CredentialCompatibilityCounts { readonly credentialRowsChecked:number;readonly credentialRowsCompatible:number;readonly credentialRowsIncompatible:number; }
/** Read-only, bounded verification of all persisted credential ciphertexts. */
export class RestoredCredentialCompatibilityVerifier { public constructor(private readonly database:SqlDatabase,private readonly whatsApp:RotationCipher,private readonly integration:RotationCipher) {} public async verify(batchSize=100):Promise<CredentialCompatibilityCounts>{if(!Number.isSafeInteger(batchSize)||batchSize<1||batchSize>1_000)throw new Error("Credential verification batch size is invalid.");let checked=0,compatible=0,incompatible=0;for(const target of [{table:"whatsapp_connection_credentials",column:"encrypted_access_token",cipher:this.whatsApp},{table:"integration_connection_secrets",column:"encrypted_secret",cipher:this.integration}] as const){let cursor=0;for(;;){const rows=await this.database.query<{rowid:number;ciphertext:string}>(`SELECT rowid,${target.column} ciphertext FROM ${target.table} WHERE rowid>? ORDER BY rowid LIMIT ?`,[cursor,batchSize]);if(!rows.length)break;for(const row of rows){cursor=row.rowid;checked+=1;try{target.cipher.decrypt(row.ciphertext);compatible+=1;}catch{incompatible+=1;}}}}return Object.freeze({credentialRowsChecked:checked,credentialRowsCompatible:compatible,credentialRowsIncompatible:incompatible});} }
export class DisasterRecoveryService { public constructor(private readonly repository:DisasterRecoveryRepository,private readonly media:BackupMediaProvider,private readonly recovery:DatabaseRecoveryProvider,private readonly now:()=>string=()=>new Date().toISOString()) {} public async backup(sourceDatabase:string):Promise<DrManifest>{if(!databaseName.test(sourceDatabase))throw new Error("Backup source is invalid.");const createdAt=this.now();if(!timestamp.test(createdAt))throw new Error("Backup time is invalid.");const backupId=`bkp_${randomUUID().replace(/-/gu,"")}`,items=await this.repository.mediaInventory(),migrationHead=await this.repository.migrationHead(),base={formatVersion:1 as const,backupId,createdAt,migrationHead,database:{mode:"turso_pitr" as const,sourceDatabase,recoveryPoint:createdAt},media:summary(items)};let manifest:DrManifest={...base,state:"started"};try{await this.media.writeManifest(backupId,manifest);for(const item of items)await this.media.copy(backupId,item);manifest={...base,state:"media_complete"};await this.media.writeManifest(backupId,manifest);for(const item of items)if(!await this.media.exists(backupId,item))throw new Error();manifest={...base,state:"complete"};await this.media.writeManifest(backupId,manifest);return Object.freeze(manifest);}catch{manifest={...base,state:"failed"};await this.media.writeManifest(backupId,manifest).catch(()=>undefined);throw new Error("Backup checkpoint failed.");}} public async restore(backupId:string,targetDatabase:string,restored:DisasterRecoveryRepository):Promise<{readonly missingMedia:number;readonly orphanMedia:number}>{const manifest=await this.media.readManifest(backupId);if(manifest.formatVersion!==1||manifest.state!=="complete"||!databaseName.test(targetDatabase)||targetDatabase===manifest.database.sourceDatabase)throw new Error("Restore request is invalid.");await this.recovery.createPointInTimeRestore(manifest.database.sourceDatabase,targetDatabase,manifest.database.recoveryPoint);await this.recovery.verifyDatabaseExists(targetDatabase);await restored.verifyReadOnly(manifest.migrationHead);const items=await restored.mediaInventory();let missingMedia=0;for(const item of items)if(!await this.media.exists(backupId,item))missingMedia+=1;if(missingMedia)throw new Error("Restore media reconciliation failed.");return Object.freeze({missingMedia,orphanMedia:Math.max(0,manifest.media.objectCount-items.length)});} }
function summary(items:readonly MediaInventoryItem[]){const canonical=items.map(item=>`${item.reference}:${item.digest}:${item.sizeBytes}`).join("\n");return Object.freeze({objectCount:items.length,totalBytes:items.reduce((total,item)=>total+item.sizeBytes,0),inventoryChecksum:createHash("sha256").update(canonical).digest("hex")});}
