import { DeleteObjectCommand, GetObjectCommand, HeadObjectCommand, ListObjectsV2Command, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { Readable } from "node:stream";
import type { BackupS3Configuration } from "../config/backupS3Configuration.js";

export interface BackupObject { readonly key:string; readonly body:AsyncIterable<Uint8Array>; readonly sizeBytes:number; readonly contentType:string|null; readonly checksum:string|null; }
export interface BackupObjectPage { readonly keys:readonly string[]; readonly continuationToken:string|null; }
export interface BackupObjectStorage { put(key:string,body:AsyncIterable<Uint8Array>,sizeBytes:number,contentType?:string,checksum?:string):Promise<void>; get(key:string,maximumBytes:number):Promise<BackupObject>; exists(key:string):Promise<boolean>; list(prefix:string,continuationToken:string|null,limit:number):Promise<BackupObjectPage>; delete(key:string):Promise<"deleted"|"locked">; }
interface S3ClientPort { send(command:object,options?:{readonly abortSignal?:AbortSignal}):Promise<unknown>; }
const keyPattern=/^(?:backup-work|backups)\/bkp_[a-f0-9]{32}\/(?:started\.json|media-complete\.json|failed\.json|manifest\.json|media\/[a-z0-9_-]{1,128})$/u;

/** Private operations storage. It never produces URLs and accepts only server-owned backup keys. */
export class S3BackupObjectStorage implements BackupObjectStorage {
  private readonly client:S3ClientPort;
  public constructor(private readonly configuration:BackupS3Configuration,client?:S3ClientPort,private readonly timeoutMilliseconds=30_000){if(!Number.isSafeInteger(timeoutMilliseconds)||timeoutMilliseconds<1||timeoutMilliseconds>60_000)throw new Error("Backup object storage timeout is invalid.");this.client=client??new S3Client({endpoint:configuration.endpoint,region:configuration.region,credentials:{accessKeyId:configuration.accessKeyId,secretAccessKey:configuration.secretAccessKey},maxAttempts:2});}
  public async put(key:string,body:AsyncIterable<Uint8Array>,sizeBytes:number,contentType="application/octet-stream",checksum?:string):Promise<void>{this.valid(key);if(!Number.isSafeInteger(sizeBytes)||sizeBytes<0)throw new Error("Backup object size is invalid.");try{await this.send(new PutObjectCommand({Bucket:this.configuration.bucket,Key:key,Body:Readable.from(this.bounded(body,sizeBytes)),ContentLength:sizeBytes,ContentType:contentType,ChecksumSHA256:checksum}));}catch{throw new Error("Backup object storage operation failed.");}}
  public async get(key:string,maximumBytes:number):Promise<BackupObject>{this.valid(key);if(!Number.isSafeInteger(maximumBytes)||maximumBytes<0)throw new Error("Backup object size is invalid.");try{const response=await this.send(new GetObjectCommand({Bucket:this.configuration.bucket,Key:key})) as {Body?:unknown;ContentLength?:number;ContentType?:string;ChecksumSHA256?:string};if(!Number.isSafeInteger(response.ContentLength)||response.ContentLength!<0||response.ContentLength!>maximumBytes||!response.Body||!(Symbol.asyncIterator in Object(response.Body)))throw new Error();return Object.freeze({key,body:this.bounded(response.Body as AsyncIterable<Uint8Array>,response.ContentLength!),sizeBytes:response.ContentLength!,contentType:response.ContentType??null,checksum:response.ChecksumSHA256??null});}catch{throw new Error("Backup object storage operation failed.");}}
  public async exists(key:string):Promise<boolean>{this.valid(key);try{await this.send(new HeadObjectCommand({Bucket:this.configuration.bucket,Key:key}));return true;}catch{return false;}}
  public async list(prefix:string,continuationToken:string|null,limit:number):Promise<BackupObjectPage>{if(!/^(?:backup-work|backups)\/$/u.test(prefix)||!Number.isSafeInteger(limit)||limit<1||limit>1_000)throw new Error("Backup object listing is invalid.");try{const response=await this.send(new ListObjectsV2Command({Bucket:this.configuration.bucket,Prefix:prefix,ContinuationToken:continuationToken??undefined,MaxKeys:limit})) as {Contents?:Array<{Key?:string}>;NextContinuationToken?:string};return Object.freeze({keys:Object.freeze((response.Contents??[]).map(item=>item.Key).filter((key):key is string=>typeof key==="string"&&keyPattern.test(key))),continuationToken:response.NextContinuationToken??null});}catch{throw new Error("Backup object storage operation failed.");}}
  public async delete(key:string):Promise<"deleted"|"locked">{this.valid(key);try{await this.send(new DeleteObjectCommand({Bucket:this.configuration.bucket,Key:key}));return "deleted";}catch{return "locked";}}
  private valid(key:string):void{if(!keyPattern.test(key))throw new Error("Backup object key is invalid.");}
  private async *bounded(body:AsyncIterable<Uint8Array>,expected:number):AsyncGenerator<Uint8Array>{let total=0;for await(const chunk of body){if(!(chunk instanceof Uint8Array))throw new Error("Backup object stream is invalid.");total+=chunk.byteLength;if(total>expected)throw new Error("Backup object size is invalid.");yield chunk;}if(total!==expected)throw new Error("Backup object size is invalid.");}
  private send(command:object):Promise<unknown>{return this.client.send(command,{abortSignal:AbortSignal.timeout(this.timeoutMilliseconds)});}
}
