// @vitest-environment jsdom
import { afterEach, expect, test, vi } from "vitest";
import { atlasApi } from "./atlasApi";

const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const scheduling={data:{aggregateVersion:7,locations:[{id:"loc_1",name:"Main",address:null,timezone:"UTC",active:true,created_at:"2026-01-01",updated_at:"2026-01-01"}],resources:[{id:"res_1",location_id:"loc_1",name:"Room",timezone:"UTC",capacity:1,active:true,created_at:"2026-01-01",updated_at:"2026-01-01"}],services:[{id:"svc_1",resource_id:"res_1",name:"Visit",duration_minutes:30,buffer_before_minutes:0,buffer_after_minutes:0,slot_granularity_minutes:15,minimum_lead_minutes:0,maximum_horizon_days:30,active:true,created_at:"2026-01-01",updated_at:"2026-01-01"}],weeklyWorkingWindows:[{id:"ww_1",resource_id:"res_1",weekday:0,start_time:"09:00",end_time:"17:00"}],dateExceptions:[{id:"ex_1",resource_id:"res_1",local_date:"2026-01-02",kind:"closed",start_time:null,end_time:null}],readiness:{state:"locally_configured",hasLocations:true,hasResources:true,hasServices:true,hasWeeklyAvailability:true}}};
afterEach(()=>vi.restoreAllMocks());

test("accepts valid scheduling configuration and command results",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response(scheduling)).mockResolvedValueOnce(response({data:{aggregateVersion:8,affected:{entityType:"location",entityId:"loc_1",action:"updated"}}}));const config=await atlasApi.getSchedulingConfiguration("work space",2);expect(config.locations[0]?.name).toBe("Main");expect(await atlasApi.mutateSchedulingConfiguration("csrf","work space",2,{operationId:"operation",expectedVersion:7,operation:"update_location",payload:{locationId:"loc_1"}})).toEqual({aggregateVersion:8,affected:{entityType:"location",entityId:"loc_1",action:"updated"}});});
test("rejects malformed scheduling configuration and command results",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({data:{...scheduling.data,aggregateVersion:0}})).mockResolvedValueOnce(response({data:{aggregateVersion:"8",affected:{entityType:"location",entityId:"loc_1",action:"updated"}}}));await expect(atlasApi.getSchedulingConfiguration("w",1)).rejects.toMatchObject({status:502});await expect(atlasApi.mutateSchedulingConfiguration("csrf","w",1,{operationId:"operation",expectedVersion:7,operation:"create_location",payload:{}})).rejects.toMatchObject({status:502});});
test("surfaces HTTP 409 scheduling conflicts",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({error:{code:"scheduling_configuration_changed",message:"stale"}},409));await expect(atlasApi.mutateSchedulingConfiguration("csrf","w",1,{operationId:"operation",expectedVersion:7,operation:"create_location",payload:{name:"Main"}})).rejects.toMatchObject({status:409,code:"scheduling_configuration_changed"});});
