import { afterEach, expect, test, vi } from "vitest";
import { atlasApi } from "./atlasApi";

function json(value:unknown,status=200):Response{return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
const summary={rolloutMode:"managed",subscription:{state:"active",plan:{key:"starter",name:"Starter",interval:"month",currency:"USD",amountMinor:1200}},entitlement:{state:"enabled",maxCompanies:2,maxAssistantProfiles:3,maxActiveChannels:1,mutationEligible:true,effectiveAt:"2026-01-01T00:00:00.000Z",expiresAt:null},capabilities:{canOpenBillingPortal:true,canCancel:true,canReactivate:false,canStartNewCheckout:true,canSwitchProvider:false}};
const offer={offerId:"offer_1",provider:"stripe",key:"starter",version:1,name:"Starter",description:"For small teams",inclusions:[{code:"companies",title:"Two companies",description:"Up to two"}],interval:"month",currency:"USD",amountMinor:1200,checkoutAvailable:true};
afterEach(()=>vi.restoreAllMocks());

test("decodes customer-safe current plan, offer, and management contracts and dispatches only an opaque offer ID",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json(summary)).mockResolvedValueOnce(json({offers:[offer]})).mockResolvedValueOnce(json({actions:["portal","cancel"],capabilities:summary.capabilities})).mockResolvedValueOnce(json({status:"succeeded",redirectUrl:"https://checkout.test/session"}));const decodedSummary=await atlasApi.getBillingSummary("work space"),decodedOffer=(await atlasApi.getBillingOffers("work space"))[0];expect(decodedSummary.subscription.plan).toEqual({key:"starter",name:"Starter",interval:"month",currency:"USD",amountMinor:1200});expect(decodedOffer).toEqual(offer);expect(Object.keys(decodedOffer??{})).not.toContain("providerPlanReference");expect((await atlasApi.getBillingManagementActions("work space")).actions).toEqual(["portal","cancel"]);await expect(atlasApi.checkoutBillingOffer("csrf","work space","offer_1","idem-1")).resolves.toEqual({status:"succeeded",redirectUrl:"https://checkout.test/session"});expect(fetch.mock.calls[3]?.[0]).toBe("/api/workspaces/work%20space/billing/checkout");expect(fetch.mock.calls[3]?.[1]).toMatchObject({method:"POST",headers:{"x-csrf-token":"csrf","idempotency-key":"idem-1"},body:JSON.stringify({offerId:"offer_1"})});expect(String(fetch.mock.calls[3]?.[1]?.body)).not.toMatch(/stripe|mercadopago|price|secret/i);});

test("rejects malformed or unsafe billing payloads",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({...summary,privateProviderReference:"secret"})).mockResolvedValueOnce(json({offers:[{...offer,providerPlanReference:"secret"}]})).mockResolvedValueOnce(json({status:"succeeded",redirectUrl:"javascript:alert(1)"}));await expect(atlasApi.getBillingSummary("w")).rejects.toMatchObject({status:502});await expect(atlasApi.getBillingOffers("w")).rejects.toMatchObject({status:502});await expect(atlasApi.openBillingPortal("csrf","w")).rejects.toMatchObject({status:502});});

test("preserves HTTP 409 as a safe billing conflict instead of treating it as checkout success",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({error:{code:"billing_state_changed",message:"State changed"}},409));await expect(atlasApi.checkoutBillingOffer("csrf","workspace","opaque-offer","idem")).rejects.toMatchObject({status:409,code:"billing_state_changed"});});

test("decodes payer identities and sends only an authorized opaque identity ID",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({options:[{identityId:"identity_opaque",email:"payer@example.test"}],selectedEmail:"payer@example.test"})).mockResolvedValueOnce(json({status:"succeeded"})).mockResolvedValueOnce(json({status:"succeeded"}));await expect(atlasApi.getBillingPayerIdentities("workspace")).resolves.toEqual({options:[{identityId:"identity_opaque",email:"payer@example.test"}],selectedEmail:"payer@example.test"});await atlasApi.setBillingPayerIdentity("csrf","workspace","identity_opaque");await atlasApi.clearBillingPayerIdentity("csrf","workspace","identity_opaque");expect(fetch.mock.calls.slice(1).map(call=>call[1])).toMatchObject([{method:"PUT",headers:{"x-csrf-token":"csrf"},body:JSON.stringify({identityId:"identity_opaque"})},{method:"DELETE",headers:{"x-csrf-token":"csrf"},body:JSON.stringify({identityId:"identity_opaque"})}]);});
