// @vitest-environment jsdom
import { afterEach, expect, test, vi } from "vitest";
import { atlasApi } from "./atlasApi";

const profile={id:"asp_1",name:"Atlas",description:null,businessRole:"Support",objective:"Help",audience:null,tone:"professional",assistantLanguage:"es",welcomeMessage:"Hola",fallbackMessage:"Contactanos.",status:"ready",createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null};
const capability={id:"live_data.read",assigned:false,availability:"available",consequence:"read_only",safeReason:null,safeNextAction:null,toolCount:1};
const tool={id:"live_data.read",enabled:false,availability:"available",capabilityId:"live_data.read",safeReason:null,safeNextAction:null};
const response=(body:unknown,status=200,headers:Record<string,string>={"content-type":"application/json"})=>new Response(JSON.stringify(body),{status,headers});
afterEach(()=>vi.restoreAllMocks());
test("maps valid assistant profile default readiness preview and execution contracts",async()=>{const readiness={assistantIdentifier:"default",workspaceId:1,companyId:2,status:"ready",blockers:[],knowledgeVersionId:"kver_1",assistantProfileId:"asp_1",evaluatedAt:"2026-01-01T00:00:00.000Z",policyVersion:"assistant-readiness-v1",configurationDigest:"a".repeat(64)},assignment={companyId:2,assistantProfileId:"asp_1",version:1,assignedAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",assignedByActorId:null,source:"operator"};vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response([profile])).mockResolvedValueOnce(response(assignment)).mockResolvedValueOnce(response(readiness)).mockResolvedValueOnce(response({status:"answered",answer:"Hola"})).mockResolvedValueOnce(response({status:"safe_fallback",answer:"Fallback"}));expect((await atlasApi.listAssistantProfiles("w",2))[0]?.id).toBe("asp_1");expect((await atlasApi.getDefaultAssistant("w",2)).version).toBe(1);expect((await atlasApi.getAssistantReadiness("w",2)).status).toBe("ready");expect((await atlasApi.previewAssistantProfile("csrf","w",2,"asp_1","hola")).status).toBe("answered");expect((await atlasApi.executeAssistantProfile("csrf","w",2,"asp_1","hola")).status).toBe("safe_fallback");});
test("rejects malformed assistant payloads safely and retains Retry-After",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response([{...profile,status:"unexpected"}])).mockResolvedValueOnce(response({error:{code:"rate_limited",message:"raw"}},429,{"content-type":"application/json","retry-after":"30"}));await expect(atlasApi.listAssistantProfiles("w",2)).rejects.toMatchObject({status:502});await expect(atlasApi.executeAssistantProfile("csrf","w",2,"asp_1","hola")).rejects.toMatchObject({status:429,code:"rate_limited",retryAfterSeconds:30});});
test("validates capability catalog and replacement contracts at runtime",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({capabilities:[capability]})).mockResolvedValueOnce(response({capabilities:["live_data.read"]}));expect(await atlasApi.getAssistantCapabilityCatalog("work space",2,"profile/id")).toEqual({capabilities:[capability]});expect(await atlasApi.replaceAssistantCapabilities("csrf","work space",2,"profile/id",["live_data.read"])).toEqual(["live_data.read"]);expect(fetchMock.mock.calls[0]?.[0]).toBe("/api/workspaces/work%20space/companies/2/assistant-profiles/profile%2Fid/capabilities/catalog");const [,options]=fetchMock.mock.calls[1] as [string,RequestInit];expect(options).toMatchObject({method:"PUT",headers:{"x-csrf-token":"csrf"}});expect(JSON.parse(String(options.body))).toEqual({capabilities:["live_data.read"]});});
test("rejects malformed capability catalog and replacement payloads safely",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({capabilities:[{...capability,toolCount:-1}]})).mockResolvedValueOnce(response({capabilities:["live_data.read",7]}));await expect(atlasApi.getAssistantCapabilityCatalog("w",2,"asp_1")).rejects.toMatchObject({status:502,message:"Assistant capability catalog response is temporarily unavailable."});await expect(atlasApi.replaceAssistantCapabilities("csrf","w",2,"asp_1",[])).rejects.toMatchObject({status:502,message:"Assistant capabilities response is temporarily unavailable."});});
test("validates tool catalog envelopes and safe item fields",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response({tools:[tool]})).mockResolvedValueOnce(response({tools:[{...tool,enabled:"yes"}]})).mockResolvedValueOnce(response({tools:[{...tool,availability:"broken"}]})).mockResolvedValueOnce(response({tools:[{...tool,capabilityId:""}]})).mockResolvedValueOnce(response({tools:[{...tool,safeReason:7}]}));expect(await atlasApi.getAssistantToolCatalog("work space",2,"profile/id")).toEqual({tools:[tool]});await expect(atlasApi.getAssistantToolCatalog("w",2,"p")).rejects.toMatchObject({status:502});await expect(atlasApi.getAssistantToolCatalog("w",2,"p")).rejects.toMatchObject({status:502});await expect(atlasApi.getAssistantToolCatalog("w",2,"p")).rejects.toMatchObject({status:502});await expect(atlasApi.getAssistantToolCatalog("w",2,"p")).rejects.toMatchObject({status:502});});
test("validates the exact customer-safe operational status projection",async()=>{const operational={assistant:{status:"ready",evaluatedAt:"2026-01-01T00:00:00.000Z",blockers:[]},whatsApp:[{connectionId:"connection_1",status:"active",validationState:"valid",healthState:"healthy"}],voice:{status:"unavailable"}};vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response(operational)).mockResolvedValueOnce(response({...operational,provider:"secret"})).mockResolvedValueOnce(response({...operational,assistant:{...operational.assistant,status:"unknown"}}));expect(await atlasApi.getCompanyOperationalStatus("work space",2)).toEqual(operational);await expect(atlasApi.getCompanyOperationalStatus("w",2)).rejects.toMatchObject({status:502});await expect(atlasApi.getCompanyOperationalStatus("w",2)).rejects.toMatchObject({status:502});});
