// @vitest-environment jsdom
import { afterEach, expect, test, vi } from "vitest";
import { atlasApi } from "./atlasApi";

const profile={id:"asp_1",name:"Atlas",description:null,businessRole:"Support",objective:"Help",audience:null,tone:"professional",assistantLanguage:"es",welcomeMessage:"Hola",fallbackMessage:"Contactanos.",status:"ready",createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null};
const response=(body:unknown,status=200,headers:Record<string,string>={"content-type":"application/json"})=>new Response(JSON.stringify(body),{status,headers});
afterEach(()=>vi.restoreAllMocks());
test("maps valid assistant profile default readiness preview and execution contracts",async()=>{const readiness={assistantIdentifier:"default",workspaceId:1,companyId:2,status:"ready",blockers:[],knowledgeVersionId:"kver_1",assistantProfileId:"asp_1",evaluatedAt:"2026-01-01T00:00:00.000Z",policyVersion:"assistant-readiness-v1",configurationDigest:"a".repeat(64)},assignment={companyId:2,assistantProfileId:"asp_1",version:1,assignedAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",assignedByActorId:null,source:"operator"};vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response([profile])).mockResolvedValueOnce(response(assignment)).mockResolvedValueOnce(response(readiness)).mockResolvedValueOnce(response({status:"answered",answer:"Hola"})).mockResolvedValueOnce(response({status:"safe_fallback",answer:"Fallback"}));expect((await atlasApi.listAssistantProfiles("w",2))[0]?.id).toBe("asp_1");expect((await atlasApi.getDefaultAssistant("w",2)).version).toBe(1);expect((await atlasApi.getAssistantReadiness("w",2)).status).toBe("ready");expect((await atlasApi.previewAssistantProfile("csrf","w",2,"asp_1","hola")).status).toBe("answered");expect((await atlasApi.executeAssistantProfile("csrf","w",2,"asp_1","hola")).status).toBe("safe_fallback");});
test("rejects malformed assistant payloads safely and retains Retry-After",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(response([{...profile,status:"unexpected"}])).mockResolvedValueOnce(response({error:{code:"rate_limited",message:"raw"}},429,{"content-type":"application/json","retry-after":"30"}));await expect(atlasApi.listAssistantProfiles("w",2)).rejects.toMatchObject({status:502});await expect(atlasApi.executeAssistantProfile("csrf","w",2,"asp_1","hola")).rejects.toMatchObject({status:429,code:"rate_limited",retryAfterSeconds:30});});
