import type { UserId } from "../../identity/domain/user.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { AssistantProfileService } from "../../assistant/services/assistantProfileService.js";
import type { WhatsAppConnectionService } from "../services/WhatsAppConnectionService.js";
import type { WhatsAppConnectionRepository } from "../../repositories/whatsappConnectionRepository.js";
import type { MetaEmbeddedSignupAttemptService } from "./metaEmbeddedSignupAttemptService.js";
import type { MetaEmbeddedSignupCompletionService } from "./metaEmbeddedSignupCompletionService.js";
import type { MetaWhatsAppReadinessService, MetaWhatsAppReadinessOutcome } from "./metaWhatsAppReadinessService.js";
import { abuseScope } from "../../abuse/sharedRateLimitRepository.js";
import { metaEmbeddedSignupActorLimit, metaEmbeddedSignupCompanyLimit, type RateLimitService } from "../../abuse/rateLimitService.js";
export type EmbeddedSignupUiStatus="awaiting_meta"|"verifying"|"connected"|"needs_attention"|"reconnect_required"|"failed"|"expired";
export interface EmbeddedSignupPublicConfig{readonly available:boolean;readonly appId?:string;readonly configId?:string;readonly graphApiVersion?:string;}
export function embeddedSignupPublicConfig(env:NodeJS.ProcessEnv=process.env):EmbeddedSignupPublicConfig{const appId=env.META_APP_ID?.trim(),configId=env.META_EMBEDDED_SIGNUP_CONFIG_ID?.trim(),graphApiVersion=env.META_GRAPH_API_VERSION?.trim();return appId&&/^\d{1,64}$/.test(appId)&&configId&&/^[A-Za-z0-9_-]{1,128}$/.test(configId)&&graphApiVersion&&/^v[1-9]\d*\.\d+$/.test(graphApiVersion)?Object.freeze({available:true,appId,configId,graphApiVersion}):Object.freeze({available:false});}
export class MetaEmbeddedSignupHttpService{
 public constructor(private readonly attempts:MetaEmbeddedSignupAttemptService|null,private readonly completion:MetaEmbeddedSignupCompletionService|null,private readonly readiness:MetaWhatsAppReadinessService|null,private readonly profiles:AssistantProfileService,private readonly whatsApp:WhatsAppConnectionService,private readonly links:WhatsAppConnectionRepository,private readonly config:EmbeddedSignupPublicConfig,private readonly limits?:RateLimitService){}
 public async start(c:WorkspaceContext,actor:UserId,companyId:number,profileValue:unknown){if(!this.config.available||!this.attempts)return{status:"needs_attention" as const,embeddedSignup:this.config};const profile=this.profiles.get(c,companyId,profileValue);const a=await this.attempts.start(c,actor,companyId,{assistantProfileId:profile.id});return{attemptId:a.attemptId,state:a.state,expiresAt:a.expiresAt,status:"awaiting_meta" as const,embeddedSignup:this.config};}
 public async reconnect(c:WorkspaceContext,actor:UserId,companyId:number,id:unknown){if(!this.config.available||!this.attempts)return{status:"needs_attention" as const,embeddedSignup:this.config};const w=this.whatsApp.get(c,companyId,id),inc=this.links.findIntegrationConnectionId(c,companyId,w.id);if(!inc)return{status:"needs_attention" as const,embeddedSignup:this.config};this.limit(c,actor,companyId);const a=await this.attempts.start(c,actor,companyId,{assistantProfileId:w.assistantProfileId,targetWhatsAppConnectionId:w.id,targetIntegrationConnectionId:inc});return{attemptId:a.attemptId,state:a.state,expiresAt:a.expiresAt,status:"awaiting_meta" as const,embeddedSignup:this.config};}
 public async status(c:WorkspaceContext,actor:UserId,companyId:number,id:string){if(!this.attempts)return null;const a=await this.attempts.findAttempt(c,actor,companyId,id);if(!a)return null;let status:EmbeddedSignupUiStatus=a.status==="started"?"awaiting_meta":a.status==="completing"?"verifying":a.status==="expired"?"expired":a.status==="failed"?"failed":"needs_attention";let whatsAppConnectionId:string|undefined;if(a.status==="completed"&&a.resolvedIntegrationConnectionId&&this.readiness){whatsAppConnectionId=this.links.findWhatsAppConnectionIdByIntegrationConnectionId(c,companyId,a.resolvedIntegrationConnectionId)??undefined;if(whatsAppConnectionId)status=readyStatus(await this.readiness.ensureReady({workspaceId:c.workspaceId,companyId,whatsAppConnectionId,setupSubscription:true}));}return{attemptId:a.id,status,expiresAt:a.expiresAt,safeFailureCode:a.safeFailureCode,retryable:status==="verifying"||status==="needs_attention",reconnectRequired:status==="reconnect_required",...(whatsAppConnectionId?{whatsAppConnectionId}:{})};}
 public async completeAttempt(c:WorkspaceContext,actor:UserId,companyId:number,id:string,b:Record<string,unknown>){if(!this.completion||typeof b.state!=="string"||typeof b.authorizationCode!=="string"||!b.authorizationCode||b.authorizationCode.length>4096)return{kind:"validation_error",status:"failed"};if(this.attempts&&await this.attempts.findAttempt(c,actor,companyId,id))this.limit(c,actor,companyId);const o=await this.completion.complete({workspaceId:c.workspaceId,companyId,actorId:actor,attemptId:id,state:b.state,authorizationCode:b.authorizationCode,...(typeof b.whatsappBusinessAccountIdHint==="string"?{whatsappBusinessAccountIdHint:b.whatsappBusinessAccountIdHint}:{}),...(typeof b.phoneNumberIdHint==="string"?{phoneNumberIdHint:b.phoneNumberIdHint}:{})});if((o.kind==="completed"||o.kind==="replayed")&&this.readiness){const r=await this.readiness.ensureReady({workspaceId:c.workspaceId,companyId,whatsAppConnectionId:o.whatsAppConnectionId,setupSubscription:true});return{kind:o.kind,attemptId:o.attemptId,whatsAppConnectionId:o.whatsAppConnectionId,status:readyStatus(r),retryable:["unready","rate_limited","unavailable","timeout"].includes(r.kind),reconnectRequired:r.kind==="reconnect_required"};}return{kind:o.kind,status:o.kind==="reconnect_required"?"reconnect_required":o.kind==="expired"?"expired":["rate_limited","unavailable","timeout","unready"].includes(o.kind)?"needs_attention":"failed",retryable:["rate_limited","unavailable","timeout","unready"].includes(o.kind),reconnectRequired:o.kind==="reconnect_required"};}
 private limit(c:WorkspaceContext,actor:UserId,companyId:number):void{this.limits?.enforce(abuseScope("workspace",c.workspaceId,"company",companyId,"actor",actor),"actor",metaEmbeddedSignupActorLimit);this.limits?.enforce(abuseScope("workspace",c.workspaceId,"company",companyId),"company",metaEmbeddedSignupCompanyLimit);}
}
function readyStatus(r:MetaWhatsAppReadinessOutcome):EmbeddedSignupUiStatus{return r.kind==="ready"||r.kind==="replayed"?"connected":r.kind==="reconnect_required"?"reconnect_required":"needs_attention";}
