import type { SqlArgument, SynchronousDatabase } from "../config/synchronousDatabase.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";
import type { ActivationVerificationAttempt, SynchronousActivationVerificationAttemptRepositoryPort } from "../activation/application/ports.js";

type Row = { id:string; workspace_id:number; company_id:number; web_chat_connection_id:string; token_digest:string; status:ActivationVerificationAttempt["status"]; created_at:string; expires_at:string; claimed_at:string|null; web_chat_session_id:string|null; conversation_id:string|null; inbound_message_id:string|null; execution_record_id:string|null; outcome_ref:ActivationVerificationAttempt["outcomeRef"]; completed_at:string|null; failure_code:ActivationVerificationAttempt["failureCode"]; };
const map = (row: Row): ActivationVerificationAttempt => Object.freeze({ id:row.id, workspaceId:row.workspace_id, companyId:row.company_id, webChatConnectionId:row.web_chat_connection_id, tokenDigest:row.token_digest, status:row.status, createdAt:row.created_at, expiresAt:row.expires_at, claimedAt:row.claimed_at, webChatSessionId:row.web_chat_session_id, conversationId:row.conversation_id, inboundMessageId:row.inbound_message_id, executionRecordId:row.execution_record_id, outcomeRef:row.outcome_ref, completedAt:row.completed_at, failureCode:row.failure_code });

export class ActivationVerificationAttemptRepository implements SynchronousActivationVerificationAttemptRepositoryPort {
  public constructor(private readonly db:SynchronousDatabase) {}
  public create(context:WorkspaceContext, value:ActivationVerificationAttempt):ActivationVerificationAttempt { const result=this.db.prepare("INSERT INTO activation_verification_attempts(id,workspace_id,company_id,web_chat_connection_id,token_digest,status,created_at,expires_at,claimed_at,web_chat_session_id,conversation_id,inbound_message_id,execution_record_id,outcome_ref,completed_at,failure_code) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM web_chat_connections WHERE id=? AND workspace_id=? AND company_id=?)").run(value.id,value.workspaceId,value.companyId,value.webChatConnectionId,value.tokenDigest,value.status,value.createdAt,value.expiresAt,value.claimedAt,value.webChatSessionId,value.conversationId,value.inboundMessageId,value.executionRecordId,value.outcomeRef,value.completedAt,value.failureCode,value.webChatConnectionId,context.workspaceId,value.companyId);if(result.changes!==1)throw new Error("Activation verification scope is invalid.");return value; }
  public findLatest(context:WorkspaceContext, companyId:number, connectionId:string):ActivationVerificationAttempt|null { const row=this.db.prepare("SELECT * FROM activation_verification_attempts WHERE workspace_id=? AND company_id=? AND web_chat_connection_id=? ORDER BY created_at DESC,id DESC LIMIT 1").get(context.workspaceId,companyId,connectionId) as Row|undefined;return row?map(row):null; }
  public hasSucceeded(context:WorkspaceContext, companyId:number, connectionId:string):boolean { return this.db.prepare("SELECT 1 FROM activation_verification_attempts WHERE workspace_id=? AND company_id=? AND web_chat_connection_id=? AND status='succeeded' LIMIT 1").get(context.workspaceId,companyId,connectionId)!==undefined; }
  public findClaimableByTokenDigest(digest:string):ActivationVerificationAttempt|null { const row=this.db.prepare("SELECT * FROM activation_verification_attempts WHERE token_digest=? AND status='pending' AND claimed_at IS NULL").get(digest) as Row|undefined;return row?map(row):null; }
  public claim(id:string, sessionId:string, conversationId:string, at:string):ActivationVerificationAttempt|null { return this.updated("UPDATE activation_verification_attempts SET claimed_at=?,web_chat_session_id=?,conversation_id=? WHERE id=? AND status='pending' AND claimed_at IS NULL",[at,sessionId,conversationId,id]); }
  public succeedForTurn(sessionId:string, conversationId:string, inboundMessageId:string, executionRecordId:string, outcomeRef:"answered"|"safe_fallback", at:string):ActivationVerificationAttempt|null { return this.updated("UPDATE activation_verification_attempts SET status='succeeded',inbound_message_id=?,execution_record_id=?,outcome_ref=?,completed_at=? WHERE web_chat_session_id=? AND conversation_id=? AND status='pending' AND claimed_at IS NOT NULL",[inboundMessageId,executionRecordId,outcomeRef,at,sessionId,conversationId]); }
  public failForSession(sessionId:string, conversationId:string, at:string):ActivationVerificationAttempt|null { return this.updated("UPDATE activation_verification_attempts SET status='failed',completed_at=?,failure_code='runtime_failure' WHERE web_chat_session_id=? AND conversation_id=? AND status='pending' AND claimed_at IS NOT NULL",[at,sessionId,conversationId]); }
  public expire(id:string, at:string):ActivationVerificationAttempt|null { return this.updated("UPDATE activation_verification_attempts SET status='expired',completed_at=? WHERE id=? AND status='pending'",[at,id]); }
  private updated(sql:string, values:readonly SqlArgument[]):ActivationVerificationAttempt|null { const result=this.db.prepare(sql).run(...values);if(result.changes!==1)return null;const id=sql.includes("WHERE id=?") ? values.at(-1) : null;if(typeof id==="string"){const row=this.db.prepare("SELECT * FROM activation_verification_attempts WHERE id=?").get(id) as Row;return map(row);}const sessionId=values.at(-2),conversationId=values.at(-1);if(typeof sessionId!=="string"||typeof conversationId!=="string")throw new Error("Activation verification update is invalid.");const row=this.db.prepare("SELECT * FROM activation_verification_attempts WHERE web_chat_session_id=? AND conversation_id=?").get(sessionId,conversationId) as Row;return map(row); }
}
