import { createHash, randomUUID } from "node:crypto";
import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import { billingProviderIdempotencyKey, type BillingOperationKind, type BillingOperationStatus } from "../billing/domain/billingOperations.js";
import type { BillingProviderKind } from "../billing/domain/billing.js";

export interface BillingOperation { readonly id:string; readonly billingAccountId:string; readonly kind:BillingOperationKind; readonly providerKind:BillingProviderKind; readonly operationId:string; readonly fingerprint:string; readonly providerIdempotencyKey:string; readonly status:BillingOperationStatus; readonly version:number; readonly providerObjectId:string|null; readonly safeResultJson:string|null; readonly catalogEntryId:string|null; readonly successTarget:string|null; readonly cancelTarget:string|null; readonly targetSubscriptionId:string|null; readonly recoveryCorrelationToken:string|null; readonly requestStartedAt:string|null; readonly recoveryNextAttemptAt:string|null; }
export interface RecoveryClaim { readonly operation:BillingOperation; readonly leaseToken:string; readonly version:number; readonly attemptCount:number; }
type Row=Record<string,unknown>;
function text(row:Row,key:string):string|null{return row[key]===null||row[key]===undefined?null:String(row[key]);}
function map(row:Row):BillingOperation { return Object.freeze({id:String(row.id),billingAccountId:String(row.billing_account_id),kind:row.operation_kind as BillingOperationKind,providerKind:row.provider_kind as BillingProviderKind,operationId:String(row.operation_id),fingerprint:String(row.request_fingerprint),providerIdempotencyKey:String(row.provider_idempotency_key),status:row.status as BillingOperationStatus,version:Number(row.version),providerObjectId:text(row,"provider_object_id"),safeResultJson:text(row,"safe_result_json"),catalogEntryId:text(row,"catalog_entry_id"),successTarget:text(row,"success_target"),cancelTarget:text(row,"cancel_target"),targetSubscriptionId:text(row,"target_subscription_id"),recoveryCorrelationToken:text(row,"recovery_correlation_token"),requestStartedAt:text(row,"request_started_at"),recoveryNextAttemptAt:text(row,"recovery_next_attempt_at")}); }
export class BillingOperationRepository {
  public constructor(private readonly db:SynchronousDatabase) {}
  public createOrReplay(input:{readonly billingAccountId:string;readonly kind:BillingOperationKind;readonly providerKind?:BillingProviderKind;readonly operationId:string;readonly fingerprint:string;readonly at:string;readonly catalogEntryId?:string;readonly successTarget?:string;readonly cancelTarget?:string;readonly targetSubscriptionId?:string}):{readonly kind:"created"|"same"|"conflict";readonly operation?:BillingOperation} { const providerKind=input.providerKind??"stripe",existing=this.find(input.billingAccountId,input.kind,input.operationId);if(existing)return existing.fingerprint===input.fingerprint&&existing.providerKind===providerKind?{kind:"same",operation:existing}:{kind:"conflict"};const correlation=input.kind==="checkout_session_create"?`aco_${createHash("sha256").update(`${input.billingAccountId}\n${input.operationId}`).digest("hex")}`:null;try{this.db.prepare("INSERT INTO billing_operations(id,billing_account_id,operation_kind,operation_id,request_fingerprint,provider_kind,provider_idempotency_key,status,catalog_entry_id,success_target,cancel_target,target_subscription_id,recovery_correlation_token,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'pending',?,?,?,?,?,?,?)").run(`bop_${randomUUID().replaceAll("-","")}`,input.billingAccountId,input.kind,input.operationId,input.fingerprint,providerKind,billingProviderIdempotencyKey(input.billingAccountId,input.kind,input.operationId),input.catalogEntryId??null,input.successTarget??null,input.cancelTarget??null,input.targetSubscriptionId??null,correlation,input.at,input.at);}catch{const raced=this.find(input.billingAccountId,input.kind,input.operationId);return raced&&raced.fingerprint===input.fingerprint&&raced.providerKind===providerKind?{kind:"same",operation:raced}:{kind:"conflict"};}return{kind:"created",operation:this.find(input.billingAccountId,input.kind,input.operationId)!}; }
  public find(account:string,kind:BillingOperationKind,operationId:string):BillingOperation|null { const row=this.db.prepare("SELECT * FROM billing_operations WHERE billing_account_id=? AND operation_kind=? AND operation_id=?").get(account,kind,operationId)as Row|undefined;return row?map(row):null; }
  public start(id:string,version:number,at:string):BillingOperation|null{return this.transition(id,version,"pending","request_started",at,null,null,null);}
  public succeed(id:string,version:number,objectId:string,safeResultJson:string|null,at:string):BillingOperation|null{return this.transition(id,version,"request_started","succeeded",at,objectId,safeResultJson,null);}
  public succeedRecovered(claim:RecoveryClaim,objectId:string,safeResultJson:string|null,at:string):BillingOperation|null{const operation=this.db.prepare("UPDATE billing_operations SET status='succeeded',provider_object_id=?,safe_result_json=?,settled_at=?,recovery_lease_token=NULL,recovery_lease_expires_at=NULL,recovery_safe_failure_code=NULL,version=version+1,updated_at=? WHERE id=? AND status IN ('uncertain','request_started') AND recovery_lease_token=? AND version=?").run(objectId,safeResultJson,at,at,claim.operation.id,claim.leaseToken,claim.version).changes===1?this.byId(claim.operation.id):null;if(operation&&operation.kind!=="checkout_session_create")this.enqueue(operation.billingAccountId,operation.providerKind,objectId,at);return operation;}
  public succeedRecoveredCheckout(claim:RecoveryClaim,objectId:string,safeResultJson:string|null,at:string):BillingOperation|null{return this.tx(()=>{const operation=this.succeedRecovered(claim,objectId,safeResultJson,at);if(!operation||!operation.catalogEntryId)return null;const ready=operation.providerKind==="mercadopago";this.db.prepare("INSERT INTO billing_checkout_enrollments(id,billing_account_id,catalog_entry_id,checkout_operation_id,provider_kind,provider_checkout_object_id,provider_subscription_id,provider_customer_id,status,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1,?,?) ON CONFLICT(provider_kind,provider_checkout_object_id) DO NOTHING").run(`bce_${randomUUID().replaceAll("-","")}`,operation.billingAccountId,operation.catalogEntryId,operation.id,operation.providerKind,objectId,ready?objectId:null,null,ready?"ready":"pending",at,at);if(ready)this.enqueue(operation.billingAccountId,operation.providerKind,objectId,at);return operation;});}
  public succeedCheckout(id:string,version:number,objectId:string,safeResultJson:string|null,catalogEntryId:string,at:string):BillingOperation|null{return this.tx(()=>{const operation=this.transition(id,version,"request_started","succeeded",at,objectId,safeResultJson,null);if(!operation)return null;const ready=operation.providerKind==="mercadopago",subscriptionId=ready?objectId:null;this.db.prepare("INSERT INTO billing_checkout_enrollments(id,billing_account_id,catalog_entry_id,checkout_operation_id,provider_kind,provider_checkout_object_id,provider_subscription_id,provider_customer_id,status,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1,?,?) ON CONFLICT(provider_kind,provider_checkout_object_id) DO NOTHING").run(`bce_${randomUUID().replaceAll("-","")}`,operation.billingAccountId,catalogEntryId,operation.id,operation.providerKind,objectId,subscriptionId,null,ready?"ready":"pending",at,at);if(ready)this.enqueue(operation.billingAccountId,operation.providerKind,objectId,at);return operation;});}
  public fail(id:string,version:number,code:string,at:string):BillingOperation|null{return this.transition(id,version,"request_started","failed",at,null,null,code);}
  public uncertain(id:string,version:number,at:string):BillingOperation|null{return this.db.prepare("UPDATE billing_operations SET status='uncertain',recovery_next_attempt_at=?,recovery_safe_failure_code=NULL,version=version+1,updated_at=? WHERE id=? AND version=? AND status='request_started'").run(at,at,id,version).changes===1?this.byId(id):null;}
  public claimRecovery(owner:string,now:string,staleBefore:string,leaseExpiresAt:string):RecoveryClaim|null{return this.tx(()=>{const row=this.db.prepare("SELECT * FROM billing_operations WHERE (recovery_lease_token IS NULL OR recovery_lease_expires_at<=?) AND ((status='uncertain' AND recovery_next_attempt_at<=?) OR (status='request_started' AND request_started_at<=?)) ORDER BY COALESCE(recovery_next_attempt_at,request_started_at),id LIMIT 1").get(now,now,staleBefore)as Row|undefined;if(!row)return null;const token=`bor_${randomUUID().replaceAll("-","")}`,changed=this.db.prepare("UPDATE billing_operations SET recovery_lease_token=?,recovery_lease_expires_at=?,recovery_attempt_count=recovery_attempt_count+1,version=version+1,updated_at=? WHERE id=? AND (recovery_lease_token IS NULL OR recovery_lease_expires_at<=?)").run(token,leaseExpiresAt,now,String(row.id),now).changes;if(changed!==1)return null;const operation=this.byId(String(row.id))!;return Object.freeze({operation,leaseToken:token,version:operation.version,attemptCount:Number((this.db.prepare("SELECT recovery_attempt_count FROM billing_operations WHERE id=?").get(operation.id)as Row).recovery_attempt_count)});});}
  public retryRecovery(claim:RecoveryClaim,next:string,code:string,at:string):boolean{return this.db.prepare("UPDATE billing_operations SET status='uncertain',recovery_next_attempt_at=?,recovery_safe_failure_code=?,recovery_lease_token=NULL,recovery_lease_expires_at=NULL,version=version+1,updated_at=? WHERE id=? AND recovery_lease_token=? AND version=?").run(next,code,at,claim.operation.id,claim.leaseToken,claim.version).changes===1;}
  public releaseRecoveryWindowExpired(claim:RecoveryClaim,at:string):boolean{return this.retryRecovery(claim,"9999-12-31T23:59:59.999Z","recovery_window_expired",at);}
  public targetProviderReference(operation:BillingOperation):string|null{if(!operation.targetSubscriptionId)return null;const row=this.db.prepare("SELECT provider_subscription_id FROM billing_subscriptions WHERE id=? AND billing_account_id=? AND provider_kind=?").get(operation.targetSubscriptionId,operation.billingAccountId,operation.providerKind)as Row|undefined;return row?text(row,"provider_subscription_id"):null;}
  public checkoutProviderReference(operation:BillingOperation):string|null{if(!operation.catalogEntryId)return null;const row=this.db.prepare("SELECT provider_price_id FROM billing_catalog_entries WHERE id=? AND provider_kind=?").get(operation.catalogEntryId,operation.providerKind)as Row|undefined;return row?text(row,"provider_price_id"):null;}
  private byId(id:string):BillingOperation|null{const row=this.db.prepare("SELECT * FROM billing_operations WHERE id=?").get(id)as Row|undefined;return row?map(row):null;}
  private transition(id:string,version:number,from:BillingOperationStatus,to:BillingOperationStatus,at:string,objectId:string|null,safeResultJson:string|null,code:string|null):BillingOperation|null {const settled=to==="succeeded"||to==="failed"?at:null,changed=this.db.prepare("UPDATE billing_operations SET status=?,request_started_at=CASE WHEN ?='request_started' THEN ? ELSE request_started_at END,provider_object_id=?,safe_result_json=?,failure_code=?,settled_at=?,recovery_next_attempt_at=CASE WHEN ?='request_started' THEN ? ELSE recovery_next_attempt_at END,version=version+1,attempt_count=attempt_count+CASE WHEN ?='request_started' THEN 1 ELSE 0 END,updated_at=? WHERE id=? AND version=? AND status=?").run(to,to,at,objectId,safeResultJson,code,settled,to,at,to,at,id,version,from).changes;if(changed!==1)return null;return this.byId(id);}
  private enqueue(accountId:string,provider:BillingProviderKind,objectId:string,at:string):void {const key=`provider_event:${provider}:${accountId}`;this.db.prepare("INSERT INTO billing_reconciliation_work(id,billing_account_id,provider_kind,reason,provider_object_id,coalesce_key,status,attempt_count,lease_owner,lease_token,lease_expires_at,next_attempt_at,safe_failure_code,version,wake_generation,created_at,updated_at) VALUES(?,?,?,?,?,?,'pending',0,NULL,NULL,NULL,?,NULL,1,1,?,?) ON CONFLICT(coalesce_key) DO UPDATE SET provider_object_id=excluded.provider_object_id,wake_generation=billing_reconciliation_work.wake_generation+1,next_attempt_at=MIN(billing_reconciliation_work.next_attempt_at,excluded.next_attempt_at),updated_at=excluded.updated_at").run(`brw_${randomUUID().replaceAll("-","")}`,accountId,provider,"checkout_enrollment",objectId,key,at,at,at);}
  private tx<T>(fn:()=>T):T {const owns=!this.db.isTransaction;if(owns)this.db.exec("BEGIN IMMEDIATE");try{const result=fn();if(owns)this.db.exec("COMMIT");return result;}catch(error){if(owns&&this.db.isTransaction)this.db.exec("ROLLBACK");throw error;}}
}
