import { randomUUID } from "node:crypto";
import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import { amountMinor, billingInterval, billingMarketingInclusionCode, billingPlanPublicationState, billingProviderOfferLifecycleState, billingProviderOfferReadinessState, currencyCode, effectiveSubscriptionState, entitlementState, providerEvidenceState, rolloutMode, type BillingInterval, type BillingMarketingInclusionCode, type BillingPlanPublicationState, type BillingProviderKind, type BillingProviderOfferLifecycleState, type BillingProviderOfferReadinessState, type EffectiveSubscriptionState, type EntitlementState, type ProviderEvidenceState, type RolloutMode } from "../billing/domain/billing.js";
import type { WorkspaceCommercialControls } from "./commercialControlsRepository.js";

type Row = Record<string, unknown>;
const nullable = (value: unknown): string | null => value === null ? null : String(value);
const id = (prefix: string): string => `${prefix}_${randomUUID().replaceAll("-", "")}`;

export interface BillingAccount { readonly id:string; readonly workspaceId:number; readonly rolloutMode:RolloutMode; readonly providerKind:BillingProviderKind|null; readonly providerCustomerId:string|null; readonly billingPayerIdentityId:string|null; readonly trialConsumedAt:string|null; readonly version:number; readonly createdAt:string; readonly updatedAt:string; }
export interface BillingCatalogEntry { readonly id:string; readonly planKey:string; readonly catalogVersion:number; readonly displayName:string; readonly description:string; readonly publicationState:BillingPlanPublicationState; readonly legacyProviderKind:BillingProviderKind|null; readonly trialDurationDays:number|null; readonly graceDurationDays:number|null; readonly maxCompanies:number|null; readonly maxAssistantProfiles:number|null; readonly maxActiveChannels:number|null; readonly mutationEligible:boolean; readonly entitlementDefinitionVersion:number; readonly version:number; readonly createdAt:string; readonly updatedAt:string; }
export interface BillingProviderCommercialOffer { readonly id:string; readonly catalogEntryId:string; readonly providerKind:BillingProviderKind; readonly offerVersion:number; readonly currency:string; readonly amountMinor:number; readonly interval:BillingInterval; readonly providerPlanReference:string; readonly readinessState:BillingProviderOfferReadinessState; readonly lifecycle:BillingProviderOfferLifecycleState; readonly version:number; readonly createdAt:string; readonly updatedAt:string; }
export interface BillingCatalogInclusion { readonly catalogEntryId:string; readonly code:BillingMarketingInclusionCode; readonly displayTitle:string; readonly displayDescription:string; readonly sortOrder:number; }
export interface BillingSubscription { readonly id:string; readonly billingAccountId:string; readonly catalogEntryId:string|null; readonly providerCommercialOfferId:string|null; readonly providerKind:BillingProviderKind|null; readonly providerSubscriptionId:string|null; readonly providerEvidenceState:ProviderEvidenceState|null; readonly effectiveState:EffectiveSubscriptionState; readonly version:number; readonly isCurrent:boolean; readonly createdAt:string; readonly updatedAt:string; }
export interface BillingEntitlementSnapshot { readonly id:string; readonly billingAccountId:string; readonly billingSubscriptionId:string; readonly state:EntitlementState; readonly maxCompanies:number|null; readonly maxAssistantProfiles:number|null; readonly maxActiveChannels:number|null; readonly mutationEligible:boolean; readonly version:number; readonly isCurrent:boolean; readonly evaluatedAt:string; readonly effectiveAt:string; readonly expiresAt:string|null; }
export interface BillingAuthorities { readonly account:BillingAccount; readonly subscription:BillingSubscription; readonly billing:BillingEntitlementSnapshot; readonly commercial:WorkspaceCommercialControls|null; }

function account(row: Row): BillingAccount { return Object.freeze({id:String(row.id),workspaceId:Number(row.workspace_id),rolloutMode:rolloutMode(row.rollout_mode),providerKind:nullable(row.provider_kind) as BillingProviderKind|null,providerCustomerId:nullable(row.provider_customer_id),billingPayerIdentityId:nullable(row.billing_payer_identity_id),trialConsumedAt:nullable(row.trial_consumed_at),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}); }
function catalog(row: Row): BillingCatalogEntry { return Object.freeze({id:String(row.id),planKey:String(row.plan_key),catalogVersion:Number(row.catalog_version),displayName:String(row.display_name),description:String(row.description),publicationState:billingPlanPublicationState(row.publication_state),legacyProviderKind:nullable(row.provider_kind) as BillingProviderKind|null,trialDurationDays:row.trial_duration_days===null?null:Number(row.trial_duration_days),graceDurationDays:row.grace_duration_days===null?null:Number(row.grace_duration_days),maxCompanies:row.entitlement_max_companies===null?null:Number(row.entitlement_max_companies),maxAssistantProfiles:row.entitlement_max_assistant_profiles===null?null:Number(row.entitlement_max_assistant_profiles),maxActiveChannels:row.entitlement_max_active_channels===null?null:Number(row.entitlement_max_active_channels),mutationEligible:Number(row.entitlement_mutation_eligible)===1,entitlementDefinitionVersion:Number(row.entitlement_definition_version),version:Number(row.version??1),createdAt:String(row.created_at),updatedAt:String(row.updated_at??row.created_at)}); }
function offer(row:Row):BillingProviderCommercialOffer{return Object.freeze({id:String(row.id),catalogEntryId:String(row.catalog_entry_id),providerKind:row.provider_kind as BillingProviderKind,offerVersion:Number(row.offer_version),currency:currencyCode(row.currency),amountMinor:amountMinor(Number(row.amount_minor)),interval:billingInterval(row.billing_interval),providerPlanReference:String(row.provider_plan_reference),readinessState:billingProviderOfferReadinessState(row.readiness_state),lifecycle:billingProviderOfferLifecycleState(row.lifecycle_state),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)});}
function subscription(row: Row): BillingSubscription { return Object.freeze({id:String(row.id),billingAccountId:String(row.billing_account_id),catalogEntryId:nullable(row.catalog_entry_id),providerCommercialOfferId:nullable(row.provider_commercial_offer_id),providerKind:nullable(row.provider_kind) as BillingProviderKind|null,providerSubscriptionId:nullable(row.provider_subscription_id),providerEvidenceState:row.provider_evidence_state===null?null:providerEvidenceState(row.provider_evidence_state),effectiveState:effectiveSubscriptionState(row.effective_state),version:Number(row.version),isCurrent:Number(row.is_current)===1,createdAt:String(row.created_at),updatedAt:String(row.updated_at)}); }
function snapshot(row: Row): BillingEntitlementSnapshot { return Object.freeze({id:String(row.id),billingAccountId:String(row.billing_account_id),billingSubscriptionId:String(row.billing_subscription_id),state:entitlementState(row.entitlement_state),maxCompanies:row.max_companies===null?null:Number(row.max_companies),maxAssistantProfiles:row.max_assistant_profiles===null?null:Number(row.max_assistant_profiles),maxActiveChannels:row.max_active_channels===null?null:Number(row.max_active_channels),mutationEligible:Number(row.mutation_eligible)===1,version:Number(row.version),isCurrent:Number(row.is_current)===1,evaluatedAt:String(row.evaluated_at),effectiveAt:String(row.effective_at),expiresAt:nullable(row.expires_at)}); }

export class BillingAccountRepository { public constructor(private readonly db:SynchronousDatabase) {} public findByWorkspace(workspaceId:number):BillingAccount|null { const row=this.db.prepare("SELECT * FROM billing_accounts WHERE workspace_id=?").get(workspaceId) as Row|undefined; return row?account(row):null; } public findById(accountId:string):BillingAccount|null { const row=this.db.prepare("SELECT * FROM billing_accounts WHERE id=?").get(accountId) as Row|undefined;return row?account(row):null; } public createUnmanaged(workspaceId:number,at:string):BillingAccount|null { this.tx(()=>this.db.prepare("INSERT INTO billing_accounts(id,workspace_id,rollout_mode,provider_kind,provider_customer_id,version,created_at,updated_at) VALUES(?,?,'unmanaged',NULL,NULL,1,?,?)").run(id("bac"),workspaceId,at,at)); return this.findByWorkspace(workspaceId); } public markManaged(workspaceId:number,provider:BillingProviderKind,customerId:string,expectedVersion:number,at:string):BillingAccount|null { const current=this.findByWorkspace(workspaceId); if(!current||current.version!==expectedVersion)return null; const changed=this.db.prepare("UPDATE billing_accounts SET rollout_mode='managed',provider_kind=?,provider_customer_id=?,version=version+1,updated_at=? WHERE workspace_id=? AND version=? AND rollout_mode='unmanaged'").run(provider,customerId,at,workspaceId,expectedVersion).changes; return changed===1?this.findByWorkspace(workspaceId):null; } public setPayerIdentity(accountId:string,identityId:string,expectedVersion:number,at:string):BillingAccount|null { const changed=this.db.prepare("UPDATE billing_accounts SET billing_payer_identity_id=?,version=version+1,updated_at=? WHERE id=? AND version=?").run(identityId,at,accountId,expectedVersion).changes;return changed===1?this.findById(accountId):null; } public clearPayerIdentity(accountId:string,expectedVersion:number,at:string):BillingAccount|null { const changed=this.db.prepare("UPDATE billing_accounts SET billing_payer_identity_id=NULL,version=version+1,updated_at=? WHERE id=? AND version=?").run(at,accountId,expectedVersion).changes;return changed===1?this.findById(accountId):null; } private tx<T>(f:()=>T):T { const own=!this.db.isTransaction;if(own)this.db.exec("BEGIN IMMEDIATE");try{const value=f();if(own)this.db.exec("COMMIT");return value;}catch(error){if(own&&this.db.isTransaction)this.db.exec("ROLLBACK");throw error;} } }
export class BillingCatalogRepository {
  public constructor(private readonly db:SynchronousDatabase) {}
  // This compatibility creator is retained for EPIC046 callers. New plan versions use createDraft.
  public create(input:Readonly<{planKey:string;catalogVersion:number;displayName:string;interval:BillingInterval;currency:string;amountMinor:number;lifecycle:"active"|"retired";maxCompanies:number|null;maxAssistantProfiles:number|null;maxActiveChannels:number|null;mutationEligible:boolean;entitlementDefinitionVersion:number;providerKind:BillingProviderKind|null;providerPriceId:string|null;}>):BillingCatalogEntry {
    const value={...input,interval:billingInterval(input.interval),currency:currencyCode(input.currency),amountMinor:amountMinor(input.amountMinor)}, entryId=id("bce"), publication=value.lifecycle==="active"?"published":"retired";
    this.tx(()=>{this.db.prepare("INSERT INTO billing_catalog_entries(id,plan_key,catalog_version,display_name,billing_interval,currency,amount_minor,lifecycle_state,entitlement_max_companies,entitlement_max_assistant_profiles,entitlement_max_active_channels,entitlement_mutation_eligible,entitlement_definition_version,provider_kind,provider_price_id,description,publication_state,trial_duration_days,grace_duration_days,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run(entryId,value.planKey,value.catalogVersion,value.displayName,value.interval,value.currency,value.amountMinor,value.lifecycle,value.maxCompanies,value.maxAssistantProfiles,value.maxActiveChannels,value.mutationEligible?1:0,value.entitlementDefinitionVersion,value.providerKind,value.providerPriceId,"",publication,null,null);if(value.providerKind&&value.providerPriceId)new BillingProviderCommercialOfferRepository(this.db).create({catalogEntryId:entryId,providerKind:value.providerKind,offerVersion:1,currency:value.providerKind==="mercadopago"?"ARS":value.currency,amountMinor:Math.max(1,value.amountMinor),interval:value.interval,providerPlanReference:value.providerPriceId,readinessState:"ready",lifecycle:publication==="published"?"sellable":"retired",at:new Date().toISOString()});});
    return this.find(entryId)!;
  }
  public createDraft(input:Readonly<{planKey:string;catalogVersion:number;displayName:string;description?:string;maxCompanies:number|null;maxAssistantProfiles:number|null;maxActiveChannels:number|null;mutationEligible:boolean;entitlementDefinitionVersion:number;trialDurationDays?:number|null;graceDurationDays?:number|null;at:string}>):BillingCatalogEntry {
    if(!/^[a-z0-9][a-z0-9_-]{0,79}$/u.test(input.planKey)||!Number.isSafeInteger(input.catalogVersion)||input.catalogVersion<1||!input.displayName||input.displayName.length>160||input.description!==undefined&&input.description.length>2000||input.trialDurationDays!==undefined&&input.trialDurationDays!==null&&(!Number.isSafeInteger(input.trialDurationDays)||input.trialDurationDays<1)||input.graceDurationDays!==undefined&&input.graceDurationDays!==null&&(!Number.isSafeInteger(input.graceDurationDays)||input.graceDurationDays<1))throw new Error("Billing catalog draft is invalid.");
    const entryId=id("bce");this.db.prepare("INSERT INTO billing_catalog_entries(id,plan_key,catalog_version,display_name,billing_interval,currency,amount_minor,lifecycle_state,entitlement_max_companies,entitlement_max_assistant_profiles,entitlement_max_active_channels,entitlement_mutation_eligible,entitlement_definition_version,provider_kind,provider_price_id,description,publication_state,trial_duration_days,grace_duration_days,version,created_at,updated_at) VALUES(?,?,?,?,?,'USD',0,'active',?,?,?,?,?,NULL,NULL,?,'draft',?,?,1,?,?)").run(entryId,input.planKey,input.catalogVersion,input.displayName,"month",input.maxCompanies,input.maxAssistantProfiles,input.maxActiveChannels,input.mutationEligible?1:0,input.entitlementDefinitionVersion,input.description??"",input.trialDurationDays??null,input.graceDurationDays??null,input.at,input.at);return this.find(entryId)!;
  }
  public find(entryId:string):BillingCatalogEntry|null { const row=this.db.prepare("SELECT * FROM billing_catalog_entries WHERE id=?").get(entryId) as Row|undefined;return row?catalog(row):null; }
  public published():readonly BillingCatalogEntry[] { return Object.freeze((this.db.prepare("SELECT * FROM billing_catalog_entries WHERE publication_state='published' ORDER BY plan_key,catalog_version").all() as Row[]).map(catalog)); }
  public active():readonly BillingCatalogEntry[] { return this.published(); }
  public sellableOffers(entryId:string):readonly BillingProviderCommercialOffer[]{return new BillingProviderCommercialOfferRepository(this.db).sellableForCatalog(entryId);}
  public inclusions(entryId:string):readonly BillingCatalogInclusion[]{return Object.freeze((this.db.prepare("SELECT catalog_entry_id,inclusion_code,display_title,display_description,sort_order FROM billing_catalog_inclusions WHERE catalog_entry_id=? ORDER BY sort_order,inclusion_code").all(entryId)as Row[]).map(row=>Object.freeze({catalogEntryId:String(row.catalog_entry_id),code:billingMarketingInclusionCode(row.inclusion_code),displayTitle:String(row.display_title),displayDescription:String(row.display_description),sortOrder:Number(row.sort_order)})));}
  public offer(offerId:string):BillingProviderCommercialOffer|null{return new BillingProviderCommercialOfferRepository(this.db).find(offerId);}
  public retire(entryId:string):boolean { return this.db.prepare("UPDATE billing_catalog_entries SET publication_state='retired',lifecycle_state='retired',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND publication_state='published'").run(entryId).changes===1; }
  private tx<T>(fn:()=>T):T{const owns=!this.db.isTransaction;if(owns)this.db.exec("BEGIN IMMEDIATE");try{const result=fn();if(owns)this.db.exec("COMMIT");return result;}catch(error){if(owns&&this.db.isTransaction)this.db.exec("ROLLBACK");throw error;}}
}

export class BillingProviderCommercialOfferRepository {
  public constructor(private readonly db:SynchronousDatabase) {}
  public create(input:Readonly<{catalogEntryId:string;providerKind:BillingProviderKind;offerVersion:number;currency:string;amountMinor:number;interval:BillingInterval;providerPlanReference:string;readinessState:BillingProviderOfferReadinessState;lifecycle:BillingProviderOfferLifecycleState;at:string}>):BillingProviderCommercialOffer {
    const currency=currencyCode(input.currency),amount=amountMinor(input.amountMinor),interval=billingInterval(input.interval);if(amount<1||input.providerKind==="stripe"&&currency!=="USD"||input.providerKind==="mercadopago"&&currency!=="ARS"||!input.providerPlanReference||input.providerPlanReference.length>200)throw new Error("Billing provider commercial offer is invalid.");
    const offerId=id("bpco");this.db.prepare("INSERT INTO billing_provider_commercial_offers(id,catalog_entry_id,provider_kind,offer_version,currency,amount_minor,billing_interval,provider_plan_reference,readiness_state,lifecycle_state,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?,?)").run(offerId,input.catalogEntryId,input.providerKind,input.offerVersion,currency,amount,interval,input.providerPlanReference,input.readinessState,input.lifecycle,input.at,input.at);return this.find(offerId)!;
  }
  public find(offerId:string):BillingProviderCommercialOffer|null{const row=this.db.prepare("SELECT * FROM billing_provider_commercial_offers WHERE id=?").get(offerId)as Row|undefined;return row?offer(row):null;}
  public sellableForCatalog(catalogEntryId:string):readonly BillingProviderCommercialOffer[]{return Object.freeze((this.db.prepare("SELECT * FROM billing_provider_commercial_offers WHERE catalog_entry_id=? AND lifecycle_state='sellable' AND readiness_state='ready' ORDER BY provider_kind,offer_version DESC").all(catalogEntryId)as Row[]).map(offer));}
  public findForCatalogProvider(catalogEntryId:string,providerKind:BillingProviderKind):BillingProviderCommercialOffer|null{const row=this.db.prepare("SELECT * FROM billing_provider_commercial_offers WHERE catalog_entry_id=? AND provider_kind=? AND lifecycle_state='sellable' AND readiness_state='ready' ORDER BY offer_version DESC LIMIT 1").get(catalogEntryId,providerKind)as Row|undefined;return row?offer(row):null;}
  public updateDraft(idValue:string,expectedVersion:number,input:Readonly<{currency:string;amountMinor:number;interval:BillingInterval;providerPlanReference:string;readinessState:BillingProviderOfferReadinessState;at:string}>):BillingProviderCommercialOffer|null{const currency=currencyCode(input.currency),amount=amountMinor(input.amountMinor),interval=billingInterval(input.interval),current=this.find(idValue);if(!current||current.version!==expectedVersion||current.lifecycle!=="draft"||amount<1||current.providerKind==="stripe"&&currency!=="USD"||current.providerKind==="mercadopago"&&currency!=="ARS"||!input.providerPlanReference||input.providerPlanReference.length>200)return null;const changed=this.db.prepare("UPDATE billing_provider_commercial_offers SET currency=?,amount_minor=?,billing_interval=?,provider_plan_reference=?,readiness_state=?,version=version+1,updated_at=? WHERE id=? AND version=? AND lifecycle_state='draft'").run(currency,amount,interval,input.providerPlanReference,input.readinessState,input.at,idValue,expectedVersion).changes;return changed===1?this.find(idValue):null;}
}
export class BillingSubscriptionRepository { public constructor(private readonly db:SynchronousDatabase) {} public current(accountId:string):BillingSubscription|null { const row=this.db.prepare("SELECT * FROM billing_subscriptions WHERE billing_account_id=? AND is_current=1").get(accountId) as Row|undefined;return row?subscription(row):null; } public compareAndSetState(accountId:string,expectedVersion:number,state:EffectiveSubscriptionState,at:string):BillingSubscription|null { effectiveSubscriptionState(state); const changed=this.db.prepare("UPDATE billing_subscriptions SET effective_state=?,version=version+1,updated_at=? WHERE billing_account_id=? AND is_current=1 AND version=?").run(state,at,accountId,expectedVersion).changes;return changed===1?this.current(accountId):null; } }
export class BillingEntitlementSnapshotRepository { public constructor(private readonly db:SynchronousDatabase) {} public current(accountId:string):BillingEntitlementSnapshot|null { const row=this.db.prepare("SELECT * FROM billing_entitlement_snapshots WHERE billing_account_id=? AND is_current=1").get(accountId) as Row|undefined;return row?snapshot(row):null; } public authorities(workspaceId:number,commercial:WorkspaceCommercialControls|null):BillingAuthorities|null { const row=this.db.prepare("SELECT s.* FROM billing_entitlement_snapshots s JOIN billing_accounts a ON a.id=s.billing_account_id WHERE a.workspace_id=? AND s.is_current=1").get(workspaceId) as Row|undefined;if(!row)return null;const value=snapshot(row),accountRow=this.db.prepare("SELECT * FROM billing_accounts WHERE id=?").get(value.billingAccountId)as Row|undefined,subscriptionRow=this.db.prepare("SELECT * FROM billing_subscriptions WHERE id=?").get(value.billingSubscriptionId)as Row|undefined;return accountRow&&subscriptionRow?Object.freeze({account:account(accountRow),subscription:subscription(subscriptionRow),billing:value,commercial}):null; } }
