import { randomUUID } from "node:crypto";
import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import type { BillingProviderKind } from "../billing/domain/billing.js";

export interface BillingWebhookEvent { readonly providerKind:BillingProviderKind;readonly providerEventId:string;readonly eventType:string;readonly providerObjectId:string|null;readonly providerCustomerId:string|null;readonly providerSubscriptionId:string|null;readonly correlationToken?:string|null;readonly payloadDigest:string; }
export type BillingWebhookAcceptance="accepted"|"duplicate"|"ignored";
export class BillingWebhookRepository {
  public constructor(private readonly db:SynchronousDatabase){}
  public accept(event:BillingWebhookEvent,at:string):BillingWebhookAcceptance{return this.tx(()=>{if(this.db.prepare("SELECT 1 FROM billing_provider_events WHERE provider_kind=? AND provider_event_id=?").get(event.providerKind,event.providerEventId))return"duplicate";const account=event.providerKind==="stripe"&&event.eventType==="checkout.session.completed"?this.bindCheckout(event,at):this.resolveAccount(event);this.db.prepare("INSERT INTO billing_provider_events(id,provider_kind,provider_event_id,event_type,provider_object_id,provider_customer_id,provider_subscription_id,payload_digest,status,received_at,processed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(`bpe_${randomUUID().replaceAll("-","")}`,event.providerKind,event.providerEventId,event.eventType,event.providerObjectId,event.providerCustomerId,event.providerSubscriptionId,event.payloadDigest,account?"received":"ignored",at,account?null:at);if(account)this.enqueue(account,event.providerKind,event.providerSubscriptionId??event.providerObjectId,at);return account?"accepted":"ignored";});}
  private bindCheckout(event:BillingWebhookEvent,at:string):string|null {if(!event.providerObjectId||!event.providerSubscriptionId)return null;let enrollment=this.db.prepare("SELECT * FROM billing_checkout_enrollments WHERE provider_kind='stripe' AND provider_checkout_object_id=?").get(event.providerObjectId)as Record<string,unknown>|undefined;if(!enrollment&&event.correlationToken){const operation=this.db.prepare("SELECT * FROM billing_operations WHERE provider_kind='stripe' AND operation_kind='checkout_session_create' AND recovery_correlation_token=? AND status IN ('request_started','uncertain')").get(event.correlationToken)as Record<string,unknown>|undefined;if(!operation||operation.catalog_entry_id===null)return null;this.db.prepare("INSERT INTO billing_checkout_enrollments(id,billing_account_id,catalog_entry_id,checkout_operation_id,provider_kind,provider_checkout_object_id,provider_subscription_id,provider_customer_id,status,version,created_at,updated_at) VALUES(?,?,?,?,? ,?,?,?,'ready',1,?,?)").run(`bce_${randomUUID().replaceAll("-","")}`,String(operation.billing_account_id),String(operation.catalog_entry_id),String(operation.id),"stripe",event.providerObjectId,event.providerSubscriptionId,event.providerCustomerId,at,at);this.db.prepare("UPDATE billing_operations SET status='succeeded',provider_object_id=?,safe_result_json=?,settled_at=?,version=version+1,updated_at=? WHERE id=? AND status IN ('request_started','uncertain')").run(event.providerObjectId,JSON.stringify({providerObjectId:event.providerObjectId}),at,at,String(operation.id));return String(operation.billing_account_id);}if(!enrollment)return null;if(String(enrollment.status)==="conflict")return null;const currentSubscription=enrollment.provider_subscription_id===null?null:String(enrollment.provider_subscription_id),currentCustomer=enrollment.provider_customer_id===null?null:String(enrollment.provider_customer_id);if((currentSubscription&&currentSubscription!==event.providerSubscriptionId)||(currentCustomer&&event.providerCustomerId&&currentCustomer!==event.providerCustomerId)){this.db.prepare("UPDATE billing_checkout_enrollments SET status='conflict',version=version+1,updated_at=? WHERE id=? AND version=?").run(at,String(enrollment.id),Number(enrollment.version));return null;}const changed=this.db.prepare("UPDATE billing_checkout_enrollments SET provider_subscription_id=?,provider_customer_id=COALESCE(provider_customer_id,?),status='ready',version=version+1,updated_at=? WHERE id=? AND version=? AND status IN ('pending','ready')").run(event.providerSubscriptionId,event.providerCustomerId,at,String(enrollment.id),Number(enrollment.version)).changes;if(changed!==1)return null;return String(enrollment.billing_account_id);}
  private resolveAccount(event:BillingWebhookEvent):string|null {const bySubscription=event.providerSubscriptionId?this.db.prepare("SELECT billing_account_id AS id FROM billing_subscriptions WHERE provider_kind=? AND provider_subscription_id=? AND is_current=1").get(event.providerKind,event.providerSubscriptionId)as{id:string}|undefined:undefined;const byCustomer=event.providerCustomerId?this.db.prepare("SELECT id FROM billing_accounts WHERE provider_kind=? AND provider_customer_id=?").get(event.providerKind,event.providerCustomerId)as{id:string}|undefined:undefined;if(event.providerSubscriptionId&&!bySubscription||event.providerCustomerId&&!byCustomer)return null;if(bySubscription&&byCustomer&&bySubscription.id!==byCustomer.id)return null;return bySubscription?.id??byCustomer?.id??null;}
  private enqueue(accountId:string,provider:BillingProviderKind,objectId:string|null,at:string):void {const key=`provider_event:${provider}:${accountId}`;this.db.prepare("INSERT INTO billing_reconciliation_work(id,billing_account_id,provider_kind,reason,provider_object_id,coalesce_key,status,attempt_count,lease_owner,lease_token,lease_expires_at,next_attempt_at,safe_failure_code,version,wake_generation,created_at,updated_at) VALUES(?,?,?,?,?,?,'pending',0,NULL,NULL,NULL,?,NULL,1,1,?,?) ON CONFLICT(coalesce_key) DO UPDATE SET provider_object_id=excluded.provider_object_id,wake_generation=billing_reconciliation_work.wake_generation+1,next_attempt_at=CASE WHEN billing_reconciliation_work.status='pending' THEN MIN(billing_reconciliation_work.next_attempt_at,excluded.next_attempt_at) ELSE billing_reconciliation_work.next_attempt_at END,updated_at=excluded.updated_at").run(`brw_${randomUUID().replaceAll("-","")}`,accountId,provider,"provider_event",objectId,key,at,at,at);}
  private tx<T>(fn:()=>T):T{const owns=!this.db.isTransaction;if(owns)this.db.exec("BEGIN IMMEDIATE");try{const result=fn();if(owns)this.db.exec("COMMIT");return result;}catch(error){if(owns&&this.db.isTransaction)this.db.exec("ROLLBACK");throw error;}}
}
