import { randomUUID } from "node:crypto";
import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import type { BillingProviderKind, EffectiveSubscriptionState, ProviderEvidenceState } from "../billing/domain/billing.js";
import { entitlementForEffectiveSubscription } from "../billing/domain/effectiveSubscriptionMapper.js";

type Row=Record<string,unknown>;
export interface ReconciliationClaim {readonly id:string;readonly billingAccountId:string;readonly providerKind:BillingProviderKind|null;readonly leaseToken:string;readonly version:number;readonly wakeGeneration:number;readonly attemptCount:number;}
export type ReconciliationSettle="applied"|"requeued"|"lost_lease"|"cas_lost";

export class BillingReconciliationRepository {
  public constructor(private readonly db:SynchronousDatabase) {}
  public claimNext(owner:string,now:string,leaseExpiresAt:string):ReconciliationClaim|null { return this.tx(()=>{const row=this.db.prepare("SELECT * FROM billing_reconciliation_work WHERE (status='pending' AND next_attempt_at<=?) OR (status='leased' AND lease_expires_at<=?) ORDER BY next_attempt_at,id LIMIT 1").get(now,now)as Row|undefined;if(!row)return null;const token=`brl_${randomUUID().replaceAll("-","")}`,changed=this.db.prepare("UPDATE billing_reconciliation_work SET status='leased',lease_owner=?,lease_token=?,lease_expires_at=?,attempt_count=attempt_count+1,version=version+1,updated_at=? WHERE id=? AND ((status='pending' AND next_attempt_at<=?) OR (status='leased' AND lease_expires_at<=?))").run(owner,token,leaseExpiresAt,now,String(row.id),now,now).changes;if(changed!==1)return null;const claim=this.db.prepare("SELECT * FROM billing_reconciliation_work WHERE id=?").get(String(row.id))as Row;return Object.freeze({id:String(claim.id),billingAccountId:String(claim.billing_account_id),providerKind:claim.provider_kind as BillingProviderKind|null,leaseToken:token,version:Number(claim.version),wakeGeneration:Number(claim.wake_generation),attemptCount:Number(claim.attempt_count)});}); }
  public trustedSubscription(claim:ReconciliationClaim):Row|null { return this.db.prepare("SELECT * FROM billing_subscriptions WHERE billing_account_id=? AND is_current=1 AND provider_kind=? AND provider_subscription_id IS NOT NULL").get(claim.billingAccountId,claim.providerKind)as Row|undefined??null; }
  public trustedEnrollment(claim:ReconciliationClaim):Row|null { return this.db.prepare("SELECT * FROM billing_checkout_enrollments WHERE billing_account_id=? AND provider_kind=? AND status='ready' AND provider_subscription_id IS NOT NULL ORDER BY created_at,id LIMIT 1").get(claim.billingAccountId,claim.providerKind)as Row|undefined??null; }
  public matchesEnrollmentCommercialEvidence(enrollment:Row,providerCommercialReference:string|null|undefined):boolean { const operation=this.db.prepare("SELECT provider_commercial_offer_id FROM billing_operations WHERE id=?").get(String(enrollment.checkout_operation_id))as Row|undefined;if(!operation?.provider_commercial_offer_id)return true;return typeof providerCommercialReference==="string"&&Boolean(this.db.prepare("SELECT 1 FROM billing_provider_commercial_offers WHERE id=? AND provider_kind=? AND provider_plan_reference=?").get(String(operation.provider_commercial_offer_id),String(enrollment.provider_kind),providerCommercialReference)); }
  public retry(claim:ReconciliationClaim,now:string,next:string,code:string):boolean { return this.tx(()=>this.db.prepare("UPDATE billing_reconciliation_work SET status='pending',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,next_attempt_at=?,safe_failure_code=?,version=version+1,updated_at=? WHERE id=? AND status='leased' AND lease_token=? AND version=?").run(next,code,now,claim.id,claim.leaseToken,claim.version).changes===1); }
  public apply(claim:ReconciliationClaim,subscription:Row,evidence:{providerEvidenceState:ProviderEvidenceState;cancelAtPeriodEnd:boolean},state:EffectiveSubscriptionState,at:string):ReconciliationSettle { return this.tx(()=>{if(!this.valid(claim))return"lost_lease";if(this.woken(claim)){this.requeue(claim,at);return"requeued";}const same=subscription.provider_evidence_state===evidence.providerEvidenceState&&subscription.effective_state===state&&Number(subscription.cancel_at_period_end)===(evidence.cancelAtPeriodEnd?1:0);if(!same){const changed=this.db.prepare("UPDATE billing_subscriptions SET provider_evidence_state=?,effective_state=?,cancel_at_period_end=?,version=version+1,updated_at=? WHERE id=? AND billing_account_id=? AND version=?").run(evidence.providerEvidenceState,state,evidence.cancelAtPeriodEnd?1:0,at,String(subscription.id),claim.billingAccountId,Number(subscription.version)).changes;if(changed!==1)return"cas_lost";this.project(String(subscription.catalog_entry_id??""),claim.billingAccountId,state,String(subscription.id),at);}return this.complete(claim,at);}); }
  public applyEnrollment(claim:ReconciliationClaim,enrollment:Row,evidence:{providerSubscriptionId:string;providerEvidenceState:ProviderEvidenceState;cancelAtPeriodEnd:boolean},state:EffectiveSubscriptionState,at:string):ReconciliationSettle { return this.tx(()=>{if(!this.valid(claim))return"lost_lease";if(this.woken(claim)){this.requeue(claim,at);return"requeued";}const fresh=this.db.prepare("SELECT * FROM billing_checkout_enrollments WHERE id=?").get(String(enrollment.id))as Row|undefined;if(!fresh||fresh.status!=="ready"||fresh.provider_subscription_id!==evidence.providerSubscriptionId||String(fresh.billing_account_id)!==claim.billingAccountId||!this.enrollmentHasTrustedCommercialEvidence(fresh))return"cas_lost";const account=this.db.prepare("SELECT * FROM billing_accounts WHERE id=?").get(claim.billingAccountId)as Row|undefined;if(!account||!this.compatible(account,fresh))return"cas_lost";const current=this.db.prepare("SELECT * FROM billing_subscriptions WHERE billing_account_id=? AND is_current=1").get(claim.billingAccountId)as Row|undefined;if(!current||current.provider_kind!==null||current.provider_subscription_id!==null)return"cas_lost";if(this.db.prepare("UPDATE billing_accounts SET rollout_mode='managed',provider_kind=?,provider_customer_id=COALESCE(provider_customer_id,?),version=version+1,updated_at=? WHERE id=? AND version=?").run(String(fresh.provider_kind),fresh.provider_customer_id as null|string,at,String(account.id),Number(account.version)).changes!==1)return"cas_lost";if(this.db.prepare("UPDATE billing_subscriptions SET is_current=0,version=version+1,updated_at=? WHERE id=? AND version=?").run(at,String(current.id),Number(current.version)).changes!==1)return"cas_lost";const subscriptionId=`bsub_${randomUUID().replaceAll("-","")}`;this.db.prepare("INSERT INTO billing_subscriptions(id,billing_account_id,catalog_entry_id,provider_commercial_offer_id,provider_kind,provider_subscription_id,provider_evidence_state,effective_state,current_period_start,current_period_end,trial_ends_at,grace_ends_at,cancel_at_period_end,is_current,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1,1,?,?)").run(subscriptionId,claim.billingAccountId,String(fresh.catalog_entry_id),fresh.provider_commercial_offer_id===null?null:String(fresh.provider_commercial_offer_id),String(fresh.provider_kind),evidence.providerSubscriptionId,evidence.providerEvidenceState,state,null,null,null,null,evidence.cancelAtPeriodEnd?1:0,at,at);if(this.db.prepare("UPDATE billing_checkout_enrollments SET status='consumed',version=version+1,updated_at=? WHERE id=? AND version=? AND status='ready'").run(at,String(fresh.id),Number(fresh.version)).changes!==1)return"cas_lost";if(state==='trial')this.db.prepare("UPDATE billing_accounts SET trial_consumed_at=COALESCE(trial_consumed_at,?) WHERE id=?").run(at,claim.billingAccountId);this.project(String(fresh.catalog_entry_id),claim.billingAccountId,state,subscriptionId,at);return this.complete(claim,at);}); }
  private compatible(account:Row,enrollment:Row):boolean { return (account.rollout_mode==='unmanaged'&&account.provider_kind===null&&account.provider_customer_id===null)||(account.rollout_mode==='managed'&&account.provider_kind===enrollment.provider_kind&&(account.provider_customer_id===null||enrollment.provider_customer_id===null||account.provider_customer_id===enrollment.provider_customer_id)); }
  private enrollmentHasTrustedCommercialEvidence(enrollment:Row):boolean { if(enrollment.provider_commercial_offer_id)return true;return Boolean(this.db.prepare("SELECT 1 FROM billing_catalog_entries WHERE id=? AND provider_kind=? AND provider_price_id IS NOT NULL").get(String(enrollment.catalog_entry_id),String(enrollment.provider_kind))); }
  private project(catalogId:string,accountId:string,state:EffectiveSubscriptionState,subscriptionId:string,at:string):void { const catalog=catalogId?this.db.prepare("SELECT * FROM billing_catalog_entries WHERE id=?").get(catalogId)as Row|undefined:undefined,entitlement=entitlementForEffectiveSubscription(state);this.db.prepare("UPDATE billing_entitlement_snapshots SET billing_subscription_id=?,entitlement_state=?,max_companies=?,max_assistant_profiles=?,max_active_channels=?,mutation_eligible=?,version=version+1,evaluated_at=?,effective_at=? WHERE billing_account_id=? AND is_current=1").run(subscriptionId,entitlement.state,catalog?.entitlement_max_companies as null|number|undefined??null,catalog?.entitlement_max_assistant_profiles as null|number|undefined??null,catalog?.entitlement_max_active_channels as null|number|undefined??null,entitlement.mutationEligible?1:0,at,at,accountId); }
  private valid(claim:ReconciliationClaim):boolean { const work=this.db.prepare("SELECT status,lease_token,version FROM billing_reconciliation_work WHERE id=?").get(claim.id)as Row|undefined;return!!work&&work.status==='leased'&&work.lease_token===claim.leaseToken&&Number(work.version)===claim.version; }
  private woken(claim:ReconciliationClaim):boolean { return Number((this.db.prepare("SELECT wake_generation FROM billing_reconciliation_work WHERE id=?").get(claim.id)as Row).wake_generation)!==claim.wakeGeneration; }
  private complete(claim:ReconciliationClaim,at:string):ReconciliationSettle { return this.db.prepare("UPDATE billing_reconciliation_work SET status='succeeded',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,safe_failure_code=NULL,version=version+1,updated_at=? WHERE id=? AND status='leased' AND lease_token=? AND version=? AND wake_generation=?").run(at,claim.id,claim.leaseToken,claim.version,claim.wakeGeneration).changes===1?"applied":"lost_lease"; }
  private requeue(claim:ReconciliationClaim,at:string):void { this.db.prepare("UPDATE billing_reconciliation_work SET status='pending',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,next_attempt_at=?,version=version+1,updated_at=? WHERE id=? AND lease_token=? AND version=?").run(at,at,claim.id,claim.leaseToken,claim.version); }
  private tx<T>(fn:()=>T):T { const owns=!this.db.isTransaction;if(owns)this.db.exec("BEGIN IMMEDIATE");try{const result=fn();if(owns)this.db.exec("COMMIT");return result;}catch(error){if(owns&&this.db.isTransaction)this.db.exec("ROLLBACK");throw error;} }
}
