import { randomUUID } from "node:crypto";
import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import { amountMinor, billingInterval, currencyCode, effectiveSubscriptionState, entitlementState, providerEvidenceState, rolloutMode, type BillingInterval, type BillingProviderKind, type EffectiveSubscriptionState, type EntitlementState, type ProviderEvidenceState, type RolloutMode } from "../billing/domain/billing.js";
import type { WorkspaceCommercialControls } from "./commercialControlsRepository.js";

type Row = Record<string, unknown>;
const nullable = (value: unknown): string | null => value === null ? null : String(value);
const id = (prefix: string): string => `${prefix}_${randomUUID().replaceAll("-", "")}`;

export interface BillingAccount { readonly id:string; readonly workspaceId:number; readonly rolloutMode:RolloutMode; readonly providerKind:BillingProviderKind|null; readonly providerCustomerId:string|null; readonly billingPayerIdentityId:string|null; readonly version:number; readonly createdAt:string; readonly updatedAt:string; }
export interface BillingCatalogEntry { readonly id:string; readonly planKey:string; readonly catalogVersion:number; readonly displayName:string; readonly interval:BillingInterval; readonly currency:string; readonly amountMinor:number; readonly lifecycle:"active"|"retired"; readonly maxCompanies:number|null; readonly maxAssistantProfiles:number|null; readonly maxActiveChannels:number|null; readonly mutationEligible:boolean; readonly entitlementDefinitionVersion:number; readonly providerKind:BillingProviderKind|null; readonly providerPriceId:string|null; readonly createdAt:string; }
export interface BillingSubscription { readonly id:string; readonly billingAccountId:string; readonly catalogEntryId:string|null; readonly providerKind:BillingProviderKind|null; readonly providerSubscriptionId:string|null; readonly providerEvidenceState:ProviderEvidenceState|null; readonly effectiveState:EffectiveSubscriptionState; readonly version:number; readonly isCurrent:boolean; readonly createdAt:string; readonly updatedAt:string; }
export interface BillingEntitlementSnapshot { readonly id:string; readonly billingAccountId:string; readonly billingSubscriptionId:string; readonly state:EntitlementState; readonly maxCompanies:number|null; readonly maxAssistantProfiles:number|null; readonly maxActiveChannels:number|null; readonly mutationEligible:boolean; readonly version:number; readonly isCurrent:boolean; readonly evaluatedAt:string; readonly effectiveAt:string; readonly expiresAt:string|null; }
export interface BillingAuthorities { readonly account:BillingAccount; readonly subscription:BillingSubscription; readonly billing:BillingEntitlementSnapshot; readonly commercial:WorkspaceCommercialControls|null; }

function account(row: Row): BillingAccount { return Object.freeze({id:String(row.id),workspaceId:Number(row.workspace_id),rolloutMode:rolloutMode(row.rollout_mode),providerKind:nullable(row.provider_kind) as BillingProviderKind|null,providerCustomerId:nullable(row.provider_customer_id),billingPayerIdentityId:nullable(row.billing_payer_identity_id),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}); }
function catalog(row: Row): BillingCatalogEntry { return Object.freeze({id:String(row.id),planKey:String(row.plan_key),catalogVersion:Number(row.catalog_version),displayName:String(row.display_name),interval:billingInterval(row.billing_interval),currency:currencyCode(row.currency),amountMinor:amountMinor(Number(row.amount_minor)),lifecycle:row.lifecycle_state as "active"|"retired",maxCompanies:row.entitlement_max_companies===null?null:Number(row.entitlement_max_companies),maxAssistantProfiles:row.entitlement_max_assistant_profiles===null?null:Number(row.entitlement_max_assistant_profiles),maxActiveChannels:row.entitlement_max_active_channels===null?null:Number(row.entitlement_max_active_channels),mutationEligible:Number(row.entitlement_mutation_eligible)===1,entitlementDefinitionVersion:Number(row.entitlement_definition_version),providerKind:nullable(row.provider_kind) as BillingProviderKind|null,providerPriceId:nullable(row.provider_price_id),createdAt:String(row.created_at)}); }
function subscription(row: Row): BillingSubscription { return Object.freeze({id:String(row.id),billingAccountId:String(row.billing_account_id),catalogEntryId:nullable(row.catalog_entry_id),providerKind:nullable(row.provider_kind) as BillingProviderKind|null,providerSubscriptionId:nullable(row.provider_subscription_id),providerEvidenceState:row.provider_evidence_state===null?null:providerEvidenceState(row.provider_evidence_state),effectiveState:effectiveSubscriptionState(row.effective_state),version:Number(row.version),isCurrent:Number(row.is_current)===1,createdAt:String(row.created_at),updatedAt:String(row.updated_at)}); }
function snapshot(row: Row): BillingEntitlementSnapshot { return Object.freeze({id:String(row.id),billingAccountId:String(row.billing_account_id),billingSubscriptionId:String(row.billing_subscription_id),state:entitlementState(row.entitlement_state),maxCompanies:row.max_companies===null?null:Number(row.max_companies),maxAssistantProfiles:row.max_assistant_profiles===null?null:Number(row.max_assistant_profiles),maxActiveChannels:row.max_active_channels===null?null:Number(row.max_active_channels),mutationEligible:Number(row.mutation_eligible)===1,version:Number(row.version),isCurrent:Number(row.is_current)===1,evaluatedAt:String(row.evaluated_at),effectiveAt:String(row.effective_at),expiresAt:nullable(row.expires_at)}); }

export class BillingAccountRepository { public constructor(private readonly db:SynchronousDatabase) {} public findByWorkspace(workspaceId:number):BillingAccount|null { const row=this.db.prepare("SELECT * FROM billing_accounts WHERE workspace_id=?").get(workspaceId) as Row|undefined; return row?account(row):null; } public findById(accountId:string):BillingAccount|null { const row=this.db.prepare("SELECT * FROM billing_accounts WHERE id=?").get(accountId) as Row|undefined;return row?account(row):null; } public createUnmanaged(workspaceId:number,at:string):BillingAccount|null { this.tx(()=>this.db.prepare("INSERT INTO billing_accounts(id,workspace_id,rollout_mode,provider_kind,provider_customer_id,version,created_at,updated_at) VALUES(?,?,'unmanaged',NULL,NULL,1,?,?)").run(id("bac"),workspaceId,at,at)); return this.findByWorkspace(workspaceId); } public markManaged(workspaceId:number,provider:BillingProviderKind,customerId:string,expectedVersion:number,at:string):BillingAccount|null { const current=this.findByWorkspace(workspaceId); if(!current||current.version!==expectedVersion)return null; const changed=this.db.prepare("UPDATE billing_accounts SET rollout_mode='managed',provider_kind=?,provider_customer_id=?,version=version+1,updated_at=? WHERE workspace_id=? AND version=? AND rollout_mode='unmanaged'").run(provider,customerId,at,workspaceId,expectedVersion).changes; return changed===1?this.findByWorkspace(workspaceId):null; } public setPayerIdentity(accountId:string,identityId:string,expectedVersion:number,at:string):BillingAccount|null { const changed=this.db.prepare("UPDATE billing_accounts SET billing_payer_identity_id=?,version=version+1,updated_at=? WHERE id=? AND version=?").run(identityId,at,accountId,expectedVersion).changes;return changed===1?this.findById(accountId):null; } public clearPayerIdentity(accountId:string,expectedVersion:number,at:string):BillingAccount|null { const changed=this.db.prepare("UPDATE billing_accounts SET billing_payer_identity_id=NULL,version=version+1,updated_at=? WHERE id=? AND version=?").run(at,accountId,expectedVersion).changes;return changed===1?this.findById(accountId):null; } private tx<T>(f:()=>T):T { const own=!this.db.isTransaction;if(own)this.db.exec("BEGIN IMMEDIATE");try{const value=f();if(own)this.db.exec("COMMIT");return value;}catch(error){if(own&&this.db.isTransaction)this.db.exec("ROLLBACK");throw error;} } }
export class BillingCatalogRepository { public constructor(private readonly db:SynchronousDatabase) {} public create(input:Omit<BillingCatalogEntry,"id"|"createdAt">):BillingCatalogEntry { const value={...input,interval:billingInterval(input.interval),currency:currencyCode(input.currency),amountMinor:amountMinor(input.amountMinor)}; const entryId=id("bce"); this.db.prepare("INSERT INTO billing_catalog_entries(id,plan_key,catalog_version,display_name,billing_interval,currency,amount_minor,lifecycle_state,entitlement_max_companies,entitlement_max_assistant_profiles,entitlement_max_active_channels,entitlement_mutation_eligible,entitlement_definition_version,provider_kind,provider_price_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(entryId,value.planKey,value.catalogVersion,value.displayName,value.interval,value.currency,value.amountMinor,value.lifecycle,value.maxCompanies,value.maxAssistantProfiles,value.maxActiveChannels,value.mutationEligible?1:0,value.entitlementDefinitionVersion,value.providerKind,value.providerPriceId); return this.find(entryId)!; } public find(entryId:string):BillingCatalogEntry|null { const row=this.db.prepare("SELECT * FROM billing_catalog_entries WHERE id=?").get(entryId) as Row|undefined;return row?catalog(row):null; } public active():readonly BillingCatalogEntry[] { return Object.freeze((this.db.prepare("SELECT * FROM billing_catalog_entries WHERE lifecycle_state='active' ORDER BY plan_key,catalog_version").all() as Row[]).map(catalog)); } public retire(entryId:string):boolean { return this.db.prepare("UPDATE billing_catalog_entries SET lifecycle_state='retired' WHERE id=? AND lifecycle_state='active'").run(entryId).changes===1; } }
export class BillingSubscriptionRepository { public constructor(private readonly db:SynchronousDatabase) {} public current(accountId:string):BillingSubscription|null { const row=this.db.prepare("SELECT * FROM billing_subscriptions WHERE billing_account_id=? AND is_current=1").get(accountId) as Row|undefined;return row?subscription(row):null; } public compareAndSetState(accountId:string,expectedVersion:number,state:EffectiveSubscriptionState,at:string):BillingSubscription|null { effectiveSubscriptionState(state); const changed=this.db.prepare("UPDATE billing_subscriptions SET effective_state=?,version=version+1,updated_at=? WHERE billing_account_id=? AND is_current=1 AND version=?").run(state,at,accountId,expectedVersion).changes;return changed===1?this.current(accountId):null; } }
export class BillingEntitlementSnapshotRepository { public constructor(private readonly db:SynchronousDatabase) {} public current(accountId:string):BillingEntitlementSnapshot|null { const row=this.db.prepare("SELECT * FROM billing_entitlement_snapshots WHERE billing_account_id=? AND is_current=1").get(accountId) as Row|undefined;return row?snapshot(row):null; } public authorities(workspaceId:number,commercial:WorkspaceCommercialControls|null):BillingAuthorities|null { const row=this.db.prepare("SELECT s.* FROM billing_entitlement_snapshots s JOIN billing_accounts a ON a.id=s.billing_account_id WHERE a.workspace_id=? AND s.is_current=1").get(workspaceId) as Row|undefined;if(!row)return null;const value=snapshot(row),accountRow=this.db.prepare("SELECT * FROM billing_accounts WHERE id=?").get(value.billingAccountId)as Row|undefined,subscriptionRow=this.db.prepare("SELECT * FROM billing_subscriptions WHERE id=?").get(value.billingSubscriptionId)as Row|undefined;return accountRow&&subscriptionRow?Object.freeze({account:account(accountRow),subscription:subscription(subscriptionRow),billing:value,commercial}):null; } }
