import { randomUUID } from "node:crypto";
import type { SynchronousDatabase } from "../config/synchronousDatabase.js";

export type CommercialStatus = "active" | "suspended";
export interface UserCommercialControls { readonly userId:string; readonly maxOwnedWorkspaces:number|null; readonly version:number; readonly createdAt:string; readonly updatedAt:string; }
export interface WorkspaceCommercialControls { readonly workspaceId:number; readonly status:CommercialStatus; readonly maxCompanies:number|null; readonly maxAssistantProfiles:number|null; readonly maxActiveChannels:number|null; readonly version:number; readonly createdAt:string; readonly updatedAt:string; readonly suspendedAt:string|null; }
export interface WorkspaceCommercialUsage { readonly companies:number; readonly assistantProfiles:number; readonly activeChannels:number; }
export interface CommercialControlAuditEvent { readonly id:string; readonly actorUserId:string; readonly subjectType:"user"|"workspace"; readonly subjectId:string; readonly eventType:string; readonly oldValue:Record<string,unknown>; readonly newValue:Record<string,unknown>; readonly version:number; readonly occurredAt:string; }
type Row=Record<string,unknown>;
const limit=(value:unknown):number|null=>value===null?null:Number(value);
function user(row:Row):UserCommercialControls{return Object.freeze({userId:String(row.user_id),maxOwnedWorkspaces:limit(row.max_owned_workspaces),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)});}
function workspace(row:Row):WorkspaceCommercialControls{return Object.freeze({workspaceId:Number(row.workspace_id),status:row.status as CommercialStatus,maxCompanies:limit(row.max_companies),maxAssistantProfiles:limit(row.max_assistant_profiles),maxActiveChannels:limit(row.max_active_channels),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at),suspendedAt:row.suspended_at===null?null:String(row.suspended_at)});}
function audit(row:Row):CommercialControlAuditEvent{return Object.freeze({id:String(row.id),actorUserId:String(row.actor_user_id),subjectType:row.subject_type as "user"|"workspace",subjectId:String(row.subject_id),eventType:String(row.event_type),oldValue:JSON.parse(String(row.old_value_json)) as Record<string,unknown>,newValue:JSON.parse(String(row.new_value_json)) as Record<string,unknown>,version:Number(row.version),occurredAt:String(row.occurred_at)});}
export class CommercialControlsRepository { public constructor(private readonly db:SynchronousDatabase) {}
  public workspace(id:number):WorkspaceCommercialControls|null{if(!this.hasWorkspaceControls())return null;const row=this.db.prepare("SELECT * FROM workspace_commercial_controls WHERE workspace_id=?").get(id) as Row|undefined;return row?workspace(row):null;}
  public workspaceByPublicId(id:string):WorkspaceCommercialControls|null{if(!this.hasWorkspaceControls())return null;const row=this.db.prepare("SELECT c.* FROM workspace_commercial_controls c JOIN workspaces w ON w.id=c.workspace_id WHERE w.public_id=?").get(id) as Row|undefined;return row?workspace(row):null;}
  public user(id:string):UserCommercialControls|null{if(!this.hasUserControls())return null;const row=this.db.prepare("SELECT * FROM user_commercial_controls WHERE user_id=?").get(id) as Row|undefined;return row?user(row):null;}
  public isWorkspaceActive(id:number):boolean{return !this.hasWorkspaceControls()||this.workspace(id)?.status==="active";}
  public ownedWorkspaceCount(userId:string):number{return Number((this.db.prepare("SELECT COUNT(*) count FROM memberships WHERE user_id=? AND role='owner' AND status='active'").get(userId) as {count:number}).count);}
  public ownedWorkspaceLimit(userId:string):number{if(this.db.prepare("SELECT 1 FROM platform_administrators WHERE user_id=? AND status='active'").get(userId))return Number.MAX_SAFE_INTEGER;if(!this.hasUserControls())return Number.MAX_SAFE_INTEGER;const controls=this.user(userId);return controls?controls.maxOwnedWorkspaces??Number.MAX_SAFE_INTEGER:0;}
  public usage(id:number):WorkspaceCommercialUsage{const companies=Number((this.db.prepare("SELECT COUNT(*) count FROM companies WHERE workspace_id=? AND lifecycle_state!='archived'").get(id) as {count:number}).count),assistantProfiles=Number((this.db.prepare("SELECT COUNT(*) count FROM assistant_profiles p JOIN companies c ON c.id=p.company_id WHERE c.workspace_id=? AND p.status!='archived'").get(id) as {count:number}).count),activeChannels=Number((this.db.prepare("SELECT (SELECT COUNT(*) FROM web_chat_connections WHERE workspace_id=? AND status='active')+(SELECT COUNT(*) FROM whatsapp_connections WHERE workspace_id=? AND status='active') count").get(id,id) as {count:number}).count);return Object.freeze({companies,assistantProfiles,activeChannels});}
  public updateUser(actor:string,id:string,maxOwnedWorkspaces:number|null,expectedVersion:number,at:string):UserCommercialControls|null{return this.atomic(()=>{const current=this.user(id);if(!current||current.version!==expectedVersion||(maxOwnedWorkspaces!==null&&maxOwnedWorkspaces<this.ownedWorkspaceCount(id)))return null;const changed={maxOwnedWorkspaces};if(this.db.prepare("UPDATE user_commercial_controls SET max_owned_workspaces=?,version=?,updated_at=? WHERE user_id=? AND version=?").run(maxOwnedWorkspaces,expectedVersion+1,at,id,expectedVersion).changes!==1)return null;this.append(actor,"user",id,"allowance_updated",{maxOwnedWorkspaces:current.maxOwnedWorkspaces},changed,expectedVersion+1,at);return this.user(id);});}
  public updateWorkspaceLimits(actor:string,id:number,input:{maxCompanies:number|null;maxAssistantProfiles:number|null;maxActiveChannels:number|null},expectedVersion:number,at:string):WorkspaceCommercialControls|null{return this.atomic(()=>{const current=this.workspace(id);if(!current||current.version!==expectedVersion)return null;const usage=this.usage(id),next={...input};if((next.maxCompanies!==null&&next.maxCompanies<usage.companies)||(next.maxAssistantProfiles!==null&&next.maxAssistantProfiles<usage.assistantProfiles)||(next.maxActiveChannels!==null&&next.maxActiveChannels<usage.activeChannels))return null;if(this.db.prepare("UPDATE workspace_commercial_controls SET max_companies=?,max_assistant_profiles=?,max_active_channels=?,version=?,updated_at=? WHERE workspace_id=? AND version=?").run(next.maxCompanies,next.maxAssistantProfiles,next.maxActiveChannels,expectedVersion+1,at,id,expectedVersion).changes!==1)return null;this.append(actor,"workspace",String(id),"limits_updated",this.limits(current),next,expectedVersion+1,at);return this.workspace(id);});}
  public setWorkspaceStatus(actor:string,id:number,status:CommercialStatus,expectedVersion:number,at:string):WorkspaceCommercialControls|null{return this.atomic(()=>{const current=this.workspace(id);if(!current||current.version!==expectedVersion||current.status===status)return null;const suspendedAt=status==="suspended"?at:null;if(this.db.prepare("UPDATE workspace_commercial_controls SET status=?,suspended_at=?,version=?,updated_at=? WHERE workspace_id=? AND version=?").run(status,suspendedAt,expectedVersion+1,at,id,expectedVersion).changes!==1)return null;this.append(actor,"workspace",String(id),status==="suspended"?"suspended":"reactivated",{status:current.status},{status},expectedVersion+1,at);return this.workspace(id);});}
  public audit(subjectType:"user"|"workspace",subjectId:string):readonly CommercialControlAuditEvent[]{if(!this.hasAuditEvents())return [];return (this.db.prepare("SELECT * FROM commercial_control_audit_events WHERE subject_type=? AND subject_id=? ORDER BY occurred_at DESC,id DESC").all(subjectType,subjectId) as Row[]).map(audit);}
  private limits(value:WorkspaceCommercialControls):Record<string,number|null>{return {maxCompanies:value.maxCompanies,maxAssistantProfiles:value.maxAssistantProfiles,maxActiveChannels:value.maxActiveChannels};}
  private append(actor:string,subjectType:"user"|"workspace",subjectId:string,eventType:string,oldValue:Record<string,unknown>,newValue:Record<string,unknown>,version:number,at:string):void{this.db.prepare("INSERT INTO commercial_control_audit_events(id,actor_user_id,subject_type,subject_id,event_type,old_value_json,new_value_json,version,occurred_at) VALUES(?,?,?,?,?,?,?,?,?)").run(randomUUID(),actor,subjectType,subjectId,eventType,JSON.stringify(oldValue),JSON.stringify(newValue),version,at);}
  private atomic<T>(operation:()=>T):T{const owns=!this.db.isTransaction;if(owns)this.db.exec("BEGIN IMMEDIATE");try{const value=operation();if(owns)this.db.exec("COMMIT");return value;}catch(error){if(owns&&this.db.isTransaction)this.db.exec("ROLLBACK");throw error;}}
  private hasWorkspaceControls():boolean{return this.hasTable("workspace_commercial_controls");}
  private hasUserControls():boolean{return this.hasTable("user_commercial_controls");}
  private hasAuditEvents():boolean{return this.hasTable("commercial_control_audit_events");}
  private hasTable(name:string):boolean{return this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name)!==undefined;}
}
