import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import type { KnowledgeRepositoryPort } from "../knowledge/application/ports.js";
import type { CompanyKnowledge } from "../types/companyKnowledge.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";
import type { CompanyKnowledgeVersion, ExtractedBusinessKnowledge, KnowledgeSource, KnowledgeSourceKind, KnowledgeSourceRevision } from "../knowledge/domain/knowledge.js";
import { KnowledgeDomainError, validateExtractedBusinessKnowledge, validateStoredCompanyKnowledgeJson } from "../knowledge/domain/knowledge.js";

type Row = Record<string, string | number | null>;
export class CompanyKnowledgeRepository implements KnowledgeRepositoryPort {
  public constructor(private readonly db: SynchronousDatabase, private readonly publicationFault?: (point:"version_insert"|"manifest_insert"|"publication_write"|"company_status")=>void) {}
  public listSources(c: WorkspaceContext, companyId: number): KnowledgeSource[] { return (this.db.prepare(`${SOURCE_SELECT} WHERE co.workspace_id=? AND co.id=? ORDER BY s.created_at DESC,s.id DESC`).all(c.workspaceId,companyId) as Row[]).map(source); }
  public findSource(c: WorkspaceContext, companyId: number, id: string): KnowledgeSource | null { const row=this.db.prepare(`${SOURCE_SELECT} WHERE co.workspace_id=? AND co.id=? AND s.id=?`).get(c.workspaceId,companyId,id) as Row|undefined; return row?source(row):null; }
  public findRevision(c: WorkspaceContext, companyId: number, sourceId: string, revisionId: string): KnowledgeSourceRevision|null { const row=this.db.prepare(`${REVISION_SELECT} WHERE co.workspace_id=? AND co.id=? AND s.id=? AND r.id=?`).get(c.workspaceId,companyId,sourceId,revisionId) as Row|undefined; return row?revision(row):null; }
  public latestRevision(c:WorkspaceContext,companyId:number,sourceId:string):KnowledgeSourceRevision|null{const row=this.db.prepare(`${REVISION_SELECT} WHERE co.workspace_id=? AND co.id=? AND s.id=? ORDER BY r.revision_number DESC LIMIT 1`).get(c.workspaceId,companyId,sourceId) as Row|undefined;return row?revision(row):null;}
  public findRevisions(c: WorkspaceContext, companyId: number, ids: readonly string[]): KnowledgeSourceRevision[] { if(!ids.length)return[]; const placeholders=ids.map(()=>"?").join(","); return (this.db.prepare(`${REVISION_SELECT} WHERE co.workspace_id=? AND co.id=? AND r.id IN (${placeholders})`).all(c.workspaceId,companyId,...ids) as Row[]).map(revision); }
  public createSourceAndPending(c:WorkspaceContext,companyId:number,input:{id:string;revisionId:string;kind:KnowledgeSourceKind;name:string;normalizedName:string;locator:string|null;mediaType:string;inputBytes:number;createdAt:string}) { this.tx(()=>{if(!this.company(c,companyId))throw new KnowledgeDomainError("resource_not_found");const count=(this.db.prepare("SELECT COUNT(*) count FROM knowledge_sources WHERE company_id=?").get(companyId) as {count:number}).count;if(count>=50)throw new KnowledgeDomainError("knowledge_limit_exceeded");this.db.prepare("INSERT INTO knowledge_sources VALUES(?,?,?,'user',?,?,?,'active',1,?,?,NULL)").run(input.id,companyId,input.kind,input.name,input.normalizedName,input.locator,input.createdAt,input.createdAt);this.db.prepare("INSERT INTO knowledge_source_revisions(id,source_id,revision_number,status,media_type,extractor_schema_version,input_bytes,created_at) VALUES(?,?,1,'pending',?,'company-business-knowledge-v1',?,?)").run(input.revisionId,input.id,input.mediaType,input.inputBytes,input.createdAt);this.db.prepare("UPDATE companies SET status='processing' WHERE id=? AND NOT EXISTS(SELECT 1 FROM company_knowledge_publications WHERE company_id=?)").run(companyId,companyId);}); return {source:this.findSource(c,companyId,input.id)!,revision:this.findRevision(c,companyId,input.id,input.revisionId)!}; }
  public reserveRevision(c:WorkspaceContext,companyId:number,input:{sourceId:string;revisionId:string;locator:string|null;expectedSourceVersion:number;mediaType:string;inputBytes:number;createdAt:string;abandonedBefore:string}):KnowledgeSourceRevision { this.tx(()=>{const s=this.findSource(c,companyId,input.sourceId);if(!s)throw new KnowledgeDomainError("resource_not_found");if(s.status!=="active")throw new KnowledgeDomainError("source_archived");this.db.prepare("UPDATE knowledge_source_revisions SET status='failed',failure_code='ingestion_interrupted',completed_at=? WHERE source_id=? AND status='pending' AND created_at<=?").run(input.createdAt,input.sourceId,input.abandonedBefore);if(this.db.prepare("SELECT 1 FROM knowledge_source_revisions WHERE source_id=? AND status='pending'").get(input.sourceId))throw new KnowledgeDomainError("knowledge_ingestion_in_progress");const next=(this.db.prepare("SELECT COALESCE(MAX(revision_number),0)+1 n FROM knowledge_source_revisions WHERE source_id=?").get(input.sourceId) as {n:number}).n;const changed=this.db.prepare("UPDATE knowledge_sources SET locator=?,version=version+1,updated_at=? WHERE id=? AND company_id=? AND version=?").run(input.locator,input.createdAt,input.sourceId,companyId,input.expectedSourceVersion);if(changed.changes!==1)throw new KnowledgeDomainError("knowledge_source_changed");this.db.prepare("INSERT INTO knowledge_source_revisions(id,source_id,revision_number,status,media_type,extractor_schema_version,input_bytes,created_at) VALUES(?,?,?,'pending',?,'company-business-knowledge-v1',?,?)").run(input.revisionId,input.sourceId,next,input.mediaType,input.inputBytes,input.createdAt);this.db.prepare("UPDATE companies SET status='processing' WHERE id=? AND NOT EXISTS(SELECT 1 FROM company_knowledge_publications WHERE company_id=?)").run(companyId,companyId);});return this.findRevision(c,companyId,input.sourceId,input.revisionId)!; }
  public completeRevision(c:WorkspaceContext,companyId:number,id:string,input:{contentDigest:string;normalizedText:string;extracted:ExtractedBusinessKnowledge;normalizedBytes:number;normalizedCharacters:number;pageCount:number|null;completedAt:string}):boolean { const result=this.db.prepare("UPDATE knowledge_source_revisions SET status='ready',content_digest=?,normalized_text=?,extracted_knowledge_json=?,normalized_bytes=?,normalized_characters=?,page_count=?,completed_at=? WHERE id=? AND status='pending' AND source_id IN(SELECT s.id FROM knowledge_sources s JOIN companies co ON co.id=s.company_id WHERE co.workspace_id=? AND co.id=?)").run(input.contentDigest,input.normalizedText,JSON.stringify(input.extracted),input.normalizedBytes,input.normalizedCharacters,input.pageCount,input.completedAt,id,c.workspaceId,companyId);return result.changes===1; }
  public failRevision(c:WorkspaceContext,companyId:number,id:string,code:string,at:string):boolean { const result=this.db.prepare("UPDATE knowledge_source_revisions SET status='failed',failure_code=?,completed_at=? WHERE id=? AND status='pending' AND source_id IN(SELECT s.id FROM knowledge_sources s JOIN companies co ON co.id=s.company_id WHERE co.workspace_id=? AND co.id=?)").run(code,at,id,c.workspaceId,companyId);if(result.changes===1)this.db.prepare("UPDATE companies SET status='failed' WHERE id=? AND NOT EXISTS(SELECT 1 FROM company_knowledge_publications WHERE company_id=?) AND NOT EXISTS(SELECT 1 FROM knowledge_source_revisions r JOIN knowledge_sources s ON s.id=r.source_id WHERE s.company_id=? AND r.status='pending')").run(companyId,companyId,companyId);return result.changes===1; }
  public archiveSource(c:WorkspaceContext,companyId:number,id:string,version:number,at:string):KnowledgeSource|null { const result=this.db.prepare("UPDATE knowledge_sources SET status='archived',version=version+1,updated_at=?,archived_at=? WHERE id=? AND company_id IN(SELECT id FROM companies WHERE workspace_id=? AND id=?) AND version=? AND status='active' AND NOT EXISTS(SELECT 1 FROM knowledge_source_revisions WHERE source_id=? AND status='pending')").run(at,at,id,c.workspaceId,companyId,version,id);return result.changes===1?this.findSource(c,companyId,id):null; }
  public loadPublished(c:WorkspaceContext,companyId:number):CompanyKnowledge|null { const row=this.db.prepare("SELECT v.knowledge_json FROM companies co JOIN company_knowledge_publications p ON p.company_id=co.id JOIN company_knowledge_versions v ON v.id=p.knowledge_version_id AND v.company_id=co.id WHERE co.workspace_id=? AND co.id=?").get(c.workspaceId,companyId) as {knowledge_json:string}|undefined;return row?validateStoredCompanyKnowledgeJson(row.knowledge_json):null; }
  public loadCurrentVersion(c:WorkspaceContext,companyId:number):CompanyKnowledgeVersion|null { const row=this.db.prepare("SELECT v.*,p.publication_version FROM companies co JOIN company_knowledge_publications p ON p.company_id=co.id JOIN company_knowledge_versions v ON v.id=p.knowledge_version_id WHERE co.workspace_id=? AND co.id=?").get(c.workspaceId,companyId) as Row|undefined;if(!row)return null;const ids=(this.db.prepare("SELECT source_revision_id FROM company_knowledge_version_sources WHERE knowledge_version_id=? ORDER BY ordinal").all(String(row.id)) as Array<{source_revision_id:string}>).map(x=>x.source_revision_id);return version(row,ids); }
  public publish(c:WorkspaceContext,companyId:number,input:{expectedVersionId:string|null;versionId:string;snapshotDigest:string;canonicalJson:string;revisionIds:readonly string[];actorId:string;at:string}) { let outcome:{status:"created"|"idempotent"|"changed";version?:CompanyKnowledgeVersion}={status:"changed"};this.tx(()=>{if(!this.company(c,companyId))throw new KnowledgeDomainError("resource_not_found");validateStoredCompanyKnowledgeJson(input.canonicalJson);const current=this.loadCurrentVersion(c,companyId);if(current?.snapshotDigest===input.snapshotDigest){outcome={status:"idempotent",version:current};return;}if((current?.id??null)!==input.expectedVersionId){outcome={status:"changed"};return;}if(this.db.prepare("SELECT 1 FROM company_knowledge_versions WHERE company_id=? AND snapshot_digest=?").get(companyId,input.snapshotDigest))throw new KnowledgeDomainError("knowledge_historical_version_conflict");const sources=this.findRevisions(c,companyId,input.revisionIds);if(sources.length!==input.revisionIds.length||sources.some(r=>r.status!=="ready"))throw new KnowledgeDomainError("source_revision_not_ready");const archived=(this.db.prepare(`SELECT COUNT(*) count FROM knowledge_source_revisions r JOIN knowledge_sources s ON s.id=r.source_id WHERE r.id IN (${input.revisionIds.map(()=>"?").join(",")}) AND s.status!='active'`).get(...input.revisionIds) as {count:number}).count;if(archived)throw new KnowledgeDomainError("source_archived");const number=(this.db.prepare("SELECT COALESCE(MAX(version_number),0)+1 n FROM company_knowledge_versions WHERE company_id=?").get(companyId) as {n:number}).n;this.db.prepare("INSERT INTO company_knowledge_versions VALUES(?,?,?,'company-knowledge-compiler-v1',?,?,?,?)").run(input.versionId,companyId,number,input.canonicalJson,input.snapshotDigest,input.actorId,input.at);this.publicationFault?.("version_insert");input.revisionIds.forEach((id,index)=>this.db.prepare("INSERT INTO company_knowledge_version_sources VALUES(?,?,?)").run(input.versionId,id,index+1));this.publicationFault?.("manifest_insert");if(current)this.db.prepare("UPDATE company_knowledge_publications SET knowledge_version_id=?,publication_version=publication_version+1,published_by_actor_id=?,published_at=? WHERE company_id=? AND knowledge_version_id=?").run(input.versionId,input.actorId,input.at,companyId,input.expectedVersionId);else this.db.prepare("INSERT INTO company_knowledge_publications VALUES(?,?,1,?,?)").run(companyId,input.versionId,input.actorId,input.at);this.publicationFault?.("publication_write");this.db.prepare("UPDATE companies SET status='ready' WHERE id=?").run(companyId);this.publicationFault?.("company_status");outcome={status:"created",version:this.loadCurrentVersion(c,companyId)!};});return outcome; }
  private company(c:WorkspaceContext,id:number):boolean{return Boolean(this.db.prepare("SELECT 1 FROM companies WHERE workspace_id=? AND id=?").get(c.workspaceId,id));}
  private tx<T>(fn:()=>T):T{try{this.db.exec("BEGIN IMMEDIATE");const result=fn();this.db.exec("COMMIT");return result;}catch(error){if(this.db.isTransaction)this.db.exec("ROLLBACK");const message=error instanceof Error?error.message:"";if(/database is locked|SQLITE_BUSY/i.test(message))throw new KnowledgeDomainError("knowledge_temporarily_unavailable");if(/knowledge_sources\.company_id, knowledge_sources\.normalized_name/i.test(message))throw new KnowledgeDomainError("knowledge_source_name_conflict");if(/idx_knowledge_revision_pending/i.test(message))throw new KnowledgeDomainError("knowledge_ingestion_in_progress");throw error;}}
}
const SOURCE_SELECT="SELECT s.* FROM knowledge_sources s JOIN companies co ON co.id=s.company_id";
const REVISION_SELECT="SELECT r.* FROM knowledge_source_revisions r JOIN knowledge_sources s ON s.id=r.source_id JOIN companies co ON co.id=s.company_id";
function source(r:Row):KnowledgeSource{return{id:String(r.id),companyId:Number(r.company_id),kind:String(r.kind) as KnowledgeSourceKind,origin:String(r.origin) as KnowledgeSource["origin"],name:String(r.name),normalizedName:String(r.normalized_name),locator:r.locator===null?null:String(r.locator),status:String(r.status) as KnowledgeSource["status"],version:Number(r.version),createdAt:String(r.created_at),updatedAt:String(r.updated_at),archivedAt:r.archived_at===null?null:String(r.archived_at)};}
function parseStoredJson(value:string):unknown{try{return JSON.parse(value);}catch{throw new KnowledgeDomainError("knowledge_integrity_failure");}}
function revision(r:Row):KnowledgeSourceRevision{return{id:String(r.id),sourceId:String(r.source_id),revisionNumber:Number(r.revision_number),status:String(r.status) as KnowledgeSourceRevision["status"],mediaType:String(r.media_type),contentDigest:r.content_digest===null?null:String(r.content_digest),normalizedText:r.normalized_text===null?null:String(r.normalized_text),extractedKnowledge:r.extracted_knowledge_json===null?null:validateExtractedBusinessKnowledge(parseStoredJson(String(r.extracted_knowledge_json))),extractorSchemaVersion:"company-business-knowledge-v1",inputBytes:Number(r.input_bytes),normalizedBytes:r.normalized_bytes===null?null:Number(r.normalized_bytes),normalizedCharacters:r.normalized_characters===null?null:Number(r.normalized_characters),pageCount:r.page_count===null?null:Number(r.page_count),failureCode:r.failure_code===null?null:String(r.failure_code),createdAt:String(r.created_at),completedAt:r.completed_at===null?null:String(r.completed_at)};}
function version(r:Row,ids:readonly string[]):CompanyKnowledgeVersion{return{id:String(r.id),companyId:Number(r.company_id),versionNumber:Number(r.version_number),compilerVersion:"company-knowledge-compiler-v1",knowledge:validateStoredCompanyKnowledgeJson(String(r.knowledge_json)),snapshotDigest:String(r.snapshot_digest),publishedByActorId:String(r.published_by_actor_id),publishedAt:String(r.published_at),sourceRevisionIds:ids,publicationVersion:Number(r.publication_version)};}
