import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";
import type { ConversationId, ConversationMessageId } from "../conversation/domain/conversation.js";
import type { ConversationIntelligenceRepositoryPort } from "../conversationIntelligence/application/ports.js";
import { conversationValue, type ConversationFact, type ConversationFactSourceKind, type ConversationIntelligenceState, type ConversationPendingItem, type ConversationReferenceGroup, type ConversationReferenceOption, type ConversationToolMemory } from "../conversationIntelligence/domain/conversationIntelligence.js";

interface StateRow { conversation_id: string; active_intent_json: string | null; version: number; created_at: string; updated_at: string; }
export class ConversationIntelligenceRepository implements ConversationIntelligenceRepositoryPort {
  public constructor(private readonly database: SynchronousDatabase) {}
  public find(context: WorkspaceContext, companyId: number, conversationId: ConversationId): ConversationIntelligenceState | null {
    const state = this.database.prepare("SELECT s.conversation_id,s.active_intent_json,s.version,s.created_at,s.updated_at FROM conversation_intelligence_states s JOIN conversations c ON c.id=s.conversation_id WHERE s.workspace_id=? AND s.company_id=? AND c.company_id=? AND s.conversation_id=?").get(context.workspaceId, companyId, companyId, conversationId) as StateRow | undefined;
    if (!state) return null;
    const facts = this.database.prepare("SELECT fact_key,value_json,authority,source_kind,source_message_id,source_tool_trace_id,source_order,updated_at FROM conversation_intelligence_facts WHERE conversation_id=? ORDER BY updated_at DESC,fact_key").all(conversationId) as Array<{ fact_key: string; value_json: string; authority: ConversationFact["authority"]; source_kind: ConversationFact["sourceKind"]; source_message_id: string | null; source_tool_trace_id: string | null; source_order: string; updated_at: string }>;
    const pending = this.database.prepare("SELECT pending_key,asked_at,created_at FROM conversation_intelligence_pending_items WHERE conversation_id=? ORDER BY created_at,pending_key").all(conversationId) as Array<{ pending_key: string; asked_at: string | null; created_at: string }>;
    const groupRows = this.database.prepare("SELECT id,group_kind,status,source_message_id,source_tool_trace_id,created_at,stale_at,expires_at FROM conversation_intelligence_reference_groups WHERE conversation_id=? ORDER BY created_at DESC,id DESC").all(conversationId) as Array<{ id: string; group_kind: string; status: "active" | "stale"; source_message_id: string | null; source_tool_trace_id: string | null; created_at: string; stale_at: string | null; expires_at: string | null }>;
    const option = this.database.prepare("SELECT reference_id,ordinal,label,safe_payload_json FROM conversation_intelligence_reference_options WHERE group_id=? ORDER BY ordinal");
    const tool = this.database.prepare("SELECT id,tool_trace_id,category,value_json,created_at FROM conversation_intelligence_tool_memory WHERE conversation_id=? ORDER BY created_at DESC,id DESC").all(conversationId) as Array<{ id: string; tool_trace_id: string; category: string; value_json: string; created_at: string }>;
    return Object.freeze({ conversationId: state.conversation_id as ConversationId, version: state.version, activeIntent: state.active_intent_json === null ? null : value(state.active_intent_json), createdAt: state.created_at, updatedAt: state.updated_at,
      facts: Object.freeze(facts.map((row) => Object.freeze({ key: row.fact_key, value: value(row.value_json), authority: row.authority, sourceKind: row.source_kind, sourceMessageId: row.source_message_id as ConversationMessageId | null, sourceToolTraceId: row.source_tool_trace_id, sourceOrder: row.source_order, updatedAt: row.updated_at }))),
      pending: Object.freeze(pending.map((row) => Object.freeze({ key: row.pending_key, askedAt: row.asked_at, createdAt: row.created_at }))),
      referenceGroups: Object.freeze(groupRows.map((row) => Object.freeze({ id: row.id, kind: row.group_kind, status: row.status, sourceMessageId: row.source_message_id as ConversationMessageId | null, sourceToolTraceId: row.source_tool_trace_id, createdAt: row.created_at, staleAt: row.stale_at, expiresAt: row.expires_at, options: Object.freeze((option.all(row.id) as Array<{ reference_id: string; ordinal: number; label: string; safe_payload_json: string }>).map((item) => Object.freeze({ referenceId: item.reference_id, ordinal: item.ordinal, label: item.label, safePayload: value(item.safe_payload_json) }))) }))),
      toolMemory: Object.freeze(tool.map((row) => Object.freeze({ id: row.id, traceId: row.tool_trace_id, category: row.category, value: value(row.value_json), createdAt: row.created_at }))),
    });
  }
  public isApplied(context: WorkspaceContext, companyId: number, conversationId: ConversationId, messageId: ConversationMessageId): boolean { return !!this.database.prepare("SELECT 1 FROM conversation_intelligence_applied_messages a JOIN conversation_intelligence_states s ON s.conversation_id=a.conversation_id WHERE s.workspace_id=? AND s.company_id=? AND a.conversation_id=? AND a.conversation_message_id=?").get(context.workspaceId, companyId, conversationId, messageId); }
  public compareAndSet(context: WorkspaceContext, companyId: number, conversationId: ConversationId, expectedVersion: number | null, valueToSave: { readonly state: ConversationIntelligenceState; readonly appliedMessageId: ConversationMessageId; readonly sourceKind: ConversationFactSourceKind; readonly at: string }): ConversationIntelligenceState | null {
    this.database.exec("BEGIN IMMEDIATE;"); try {
      const owned = this.database.prepare("SELECT 1 FROM conversations c JOIN companies co ON co.id=c.company_id WHERE co.workspace_id=? AND c.company_id=? AND c.id=?").get(context.workspaceId, companyId, conversationId);
      if (!owned || this.isApplied(context, companyId, conversationId, valueToSave.appliedMessageId)) { this.database.exec("ROLLBACK;"); return null; }
      const next = (expectedVersion ?? 0) + 1;
      const changed = expectedVersion === null ? this.database.prepare("INSERT INTO conversation_intelligence_states(conversation_id,workspace_id,company_id,active_intent_json,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(conversation_id) DO NOTHING").run(conversationId, context.workspaceId, companyId, valueToSave.state.activeIntent === null ? null : json(valueToSave.state.activeIntent), next, valueToSave.at, valueToSave.at).changes === 1 : this.database.prepare("UPDATE conversation_intelligence_states SET active_intent_json=?,version=?,updated_at=? WHERE conversation_id=? AND workspace_id=? AND company_id=? AND version=?").run(valueToSave.state.activeIntent === null ? null : json(valueToSave.state.activeIntent), next, valueToSave.at, conversationId, context.workspaceId, companyId, expectedVersion).changes === 1;
      if (!changed) { this.database.exec("ROLLBACK;"); return null; }
      this.database.prepare("DELETE FROM conversation_intelligence_facts WHERE conversation_id=?").run(conversationId); this.database.prepare("DELETE FROM conversation_intelligence_pending_items WHERE conversation_id=?").run(conversationId); this.database.prepare("DELETE FROM conversation_intelligence_reference_groups WHERE conversation_id=?").run(conversationId); this.database.prepare("DELETE FROM conversation_intelligence_tool_memory WHERE conversation_id=?").run(conversationId);
      const fact = this.database.prepare("INSERT INTO conversation_intelligence_facts(conversation_id,fact_key,value_json,authority,source_kind,source_message_id,source_tool_trace_id,source_order,updated_at) VALUES(?,?,?,?,?,?,?,?,?)"); for (const item of valueToSave.state.facts) fact.run(conversationId,item.key,json(item.value),item.authority,item.sourceKind,item.sourceMessageId,item.sourceToolTraceId,item.sourceOrder,item.updatedAt);
      const pending = this.database.prepare("INSERT INTO conversation_intelligence_pending_items(conversation_id,pending_key,asked_at,created_at) VALUES(?,?,?,?)"); for (const item of valueToSave.state.pending) pending.run(conversationId,item.key,item.askedAt,item.createdAt);
      const group = this.database.prepare("INSERT INTO conversation_intelligence_reference_groups(id,conversation_id,group_kind,status,source_message_id,source_tool_trace_id,created_at,stale_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?)"), option = this.database.prepare("INSERT INTO conversation_intelligence_reference_options(group_id,reference_id,ordinal,label,safe_payload_json) VALUES(?,?,?,?,?)"); for (const item of valueToSave.state.referenceGroups) { group.run(item.id,conversationId,item.kind,item.status,item.sourceMessageId,item.sourceToolTraceId,item.createdAt,item.staleAt,item.expiresAt); for (const child of item.options) option.run(item.id,child.referenceId,child.ordinal,child.label,json(child.safePayload)); }
      const memory = this.database.prepare("INSERT INTO conversation_intelligence_tool_memory(id,conversation_id,tool_trace_id,category,value_json,created_at) VALUES(?,?,?,?,?,?)"); for (const item of valueToSave.state.toolMemory) memory.run(item.id,conversationId,item.traceId,item.category,json(item.value),item.createdAt);
      this.database.prepare("INSERT INTO conversation_intelligence_applied_messages(conversation_id,conversation_message_id,state_version,applied_at) SELECT ?,m.id,?,? FROM conversation_messages m WHERE m.id=? AND m.conversation_id=?").run(conversationId,next,valueToSave.at,valueToSave.appliedMessageId,conversationId);
      this.database.exec("COMMIT;"); return this.find(context, companyId, conversationId);
    } catch (error: unknown) { if (this.database.isTransaction) this.database.exec("ROLLBACK;"); throw error; }
  }
}
function json(valueToEncode: unknown): string { return JSON.stringify(valueToEncode); }
function value(serialized: string) { try { return conversationValue(JSON.parse(serialized)); } catch { throw new Error("Conversation intelligence value is invalid."); } }
