import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";
import type { KnowledgeRetrievalRepositoryPort } from "../knowledgeV2/application/ports.js";
import { knowledgeV2Id, type KnowledgeChunkV2, type KnowledgeDocumentV2, type KnowledgeIndexV2 } from "../knowledgeV2/domain/knowledgeRetrieval.js";

type Row=Record<string,string|number|null>;
export class KnowledgeRetrievalRepository implements KnowledgeRetrievalRepositoryPort {
  public constructor(private readonly db:SynchronousDatabase){}
  public replaceRevision(c:WorkspaceContext,companyId:number,input:{sourceId:string;sourceRevisionId:string;contentDigest:string;normalizedText:string;createdAt:string;chunks:readonly {text:string;characterStart:number;characterEnd:number}[]}):KnowledgeIndexV2{const documentId=knowledgeV2Id("kdoc",`${companyId}\n${input.sourceRevisionId}\n${input.contentDigest}`),indexId=knowledgeV2Id("kidx",documentId);this.tx(()=>{this.db.prepare("DELETE FROM knowledge_v2_documents WHERE workspace_id=? AND company_id=? AND source_revision_id=?").run(c.workspaceId,companyId,input.sourceRevisionId);this.db.prepare("INSERT INTO knowledge_v2_documents VALUES(?,?,?,?,?,?,?,?)").run(documentId,c.workspaceId,companyId,input.sourceId,input.sourceRevisionId,input.contentDigest,input.normalizedText,input.createdAt);this.db.prepare("INSERT INTO knowledge_v2_indexes VALUES(?,?,?,?,?,'lexical','building',?,?,NULL)").run(indexId,c.workspaceId,companyId,input.sourceRevisionId,documentId,input.chunks.length,input.createdAt);for(const [ordinal,item] of input.chunks.entries()){const chunkId=knowledgeV2Id("kchk",`${documentId}\n${ordinal}\n${item.text}`),bytes=Buffer.byteLength(item.text,"utf8");this.db.prepare("INSERT INTO knowledge_v2_chunks VALUES(?,?,?,?,?,?,?,?)").run(chunkId,documentId,c.workspaceId,companyId,ordinal,item.text,item.text.normalize("NFKC").toLocaleLowerCase("en-US"),bytes);this.db.prepare("INSERT INTO knowledge_v2_chunk_provenance VALUES(?,?,?,?,?)").run(chunkId,input.sourceRevisionId,input.contentDigest,item.characterStart,item.characterEnd);}this.db.prepare("UPDATE knowledge_v2_indexes SET status='ready',completed_at=? WHERE id=?").run(input.createdAt,indexId);});return this.index(c,companyId,input.sourceRevisionId)!;}
  public readyForRevisions(c:WorkspaceContext,companyId:number,ids:readonly string[]):boolean{if(!ids.length)return false;const placeholders=ids.map(()=>"?").join(","),row=this.db.prepare(`SELECT COUNT(*) count FROM knowledge_v2_indexes WHERE workspace_id=? AND company_id=? AND status='ready' AND source_revision_id IN (${placeholders})`).get(c.workspaceId,companyId,...ids)as{count:number};return row.count===ids.length;}
  public findReadyChunks(c:WorkspaceContext,companyId:number,ids:readonly string[]):readonly KnowledgeChunkV2[]{if(!ids.length)return[];const placeholders=ids.map(()=>"?").join(",");return(this.db.prepare(`SELECT ch.*,p.source_revision_id,p.content_digest,p.character_start,p.character_end FROM knowledge_v2_chunks ch JOIN knowledge_v2_chunk_provenance p ON p.chunk_id=ch.id JOIN knowledge_v2_indexes i ON i.document_id=ch.document_id JOIN knowledge_v2_documents d ON d.id=ch.document_id JOIN knowledge_sources s ON s.id=d.source_id WHERE ch.workspace_id=? AND ch.company_id=? AND s.status='active' AND i.status='ready' AND i.source_revision_id IN (${placeholders}) ORDER BY ch.document_id,ch.ordinal`).all(c.workspaceId,companyId,...ids)as Row[]).map(chunk);}
  public findDocument(c:WorkspaceContext,companyId:number,revisionId:string):KnowledgeDocumentV2|null{const row=this.db.prepare("SELECT * FROM knowledge_v2_documents WHERE workspace_id=? AND company_id=? AND source_revision_id=?").get(c.workspaceId,companyId,revisionId)as Row|undefined;return row?document(row):null;}
  private index(c:WorkspaceContext,companyId:number,revisionId:string):KnowledgeIndexV2|null{const row=this.db.prepare("SELECT * FROM knowledge_v2_indexes WHERE workspace_id=? AND company_id=? AND source_revision_id=?").get(c.workspaceId,companyId,revisionId)as Row|undefined;return row?{id:String(row.id),workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),sourceRevisionId:String(row.source_revision_id),documentId:String(row.document_id),kind:"lexical",status:String(row.status)as KnowledgeIndexV2["status"],chunkCount:Number(row.chunk_count),createdAt:String(row.created_at),completedAt:row.completed_at===null?null:String(row.completed_at)}:null;}
  private tx<T>(fn:()=>T):T{try{this.db.exec("BEGIN IMMEDIATE");const value=fn();this.db.exec("COMMIT");return value;}catch(error){if(this.db.isTransaction)this.db.exec("ROLLBACK");throw error;}}
}
function document(row:Row):KnowledgeDocumentV2{return{id:String(row.id),workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),sourceId:String(row.source_id),sourceRevisionId:String(row.source_revision_id),contentDigest:String(row.content_digest),normalizedText:String(row.normalized_text),createdAt:String(row.created_at)};}
function chunk(row:Row):KnowledgeChunkV2{return{id:String(row.id),documentId:String(row.document_id),workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),ordinal:Number(row.ordinal),text:String(row.text),normalizedText:String(row.normalized_text),byteLength:Number(row.byte_length),sourceRevisionId:String(row.source_revision_id),contentDigest:String(row.content_digest),characterStart:Number(row.character_start),characterEnd:Number(row.character_end)};}
