import type { SynchronousDatabase } from "../config/synchronousDatabase.js";
import { randomUUID } from "node:crypto";
import type { MediaRepositoryPort } from "../media/application/ports.js";
import { MediaDomainError, type MediaAsset, type MediaAssociation, type MediaBlob, type MediaBlobState, type MediaIngestAttempt, type MediaIngestAttemptState } from "../media/domain/media.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";

interface Row { [key: string]: unknown; id: string; workspace_id: number; company_id: number; kind: MediaAsset["kind"]; media_type: string; size_bytes: number | null; safe_filename: string | null; metadata_json: string; status: MediaAsset["status"]; created_at: string; archived_at: string | null; deleted_at: string | null; blob_id: string | null; sha256_digest: string; storage_reference: string; state: MediaBlobState; }
interface AttemptRow { asset_id:string;workspace_id:number;company_id:number;candidate_blob_id:string;staging_storage_reference:string;final_storage_reference:string;sha256_digest:string;size_bytes:number;inspected_media_type:string;state:MediaIngestAttemptState;lease_owner:string|null;lease_token:string|null;lease_expires_at:string|null;attempt_count:number;safe_failure_category:string|null;created_at:string;updated_at:string;settled_at:string|null; }
const asset = (row: Row): MediaAsset => Object.freeze({ id: row.id, workspaceId: row.workspace_id, companyId: row.company_id, kind: row.kind, mediaType: row.media_type, sizeBytes: row.size_bytes, filename: row.safe_filename, metadata: Object.freeze(JSON.parse(row.metadata_json) as Record<string, number>), status: row.status, createdAt: row.created_at, archivedAt: row.archived_at, deletedAt: row.deleted_at });
const blob = (row: Row): MediaBlob => Object.freeze({ id: row.id, workspaceId: row.workspace_id, companyId: row.company_id, digest: row.sha256_digest, sizeBytes: Number(row.size_bytes), mediaType: row.media_type, storageReference: row.storage_reference, state: row.state, createdAt: row.created_at });
const attempt=(row:AttemptRow):MediaIngestAttempt=>Object.freeze({assetId:row.asset_id,workspaceId:Number(row.workspace_id),companyId:Number(row.company_id),candidateBlobId:row.candidate_blob_id,stagingStorageReference:row.staging_storage_reference,finalStorageReference:row.final_storage_reference,digest:row.sha256_digest,sizeBytes:Number(row.size_bytes),inspectedMediaType:row.inspected_media_type,state:row.state,leaseOwner:row.lease_owner,leaseToken:row.lease_token,leaseExpiresAt:row.lease_expires_at,attemptCount:Number(row.attempt_count),failureCategory:row.safe_failure_category,createdAt:row.created_at,updatedAt:row.updated_at,settledAt:row.settled_at});

export class MediaRepository implements MediaRepositoryPort {
  /** Optional deterministic test seam; production supplies no hook. */
  public constructor(private readonly db: SynchronousDatabase, private readonly transactionHook?: { readonly beforeBegin?: (operation: "attach" | "delete") => void; readonly beforeCommit?: (operation: "attach" | "delete") => void }) {}
  public resolve(c:WorkspaceContext,companyId:number,operation:string,key:string,fingerprint:string){const existing=this.db.prepare("SELECT a.*,i.request_fingerprint FROM media_idempotency i JOIN media_assets a ON a.id=i.asset_id WHERE i.workspace_id=? AND i.company_id=? AND i.operation=? AND i.idempotency_key=?").get(c.workspaceId,companyId,operation,key)as(Row&{request_fingerprint:string})|undefined;if(!existing)return{kind:"new" as const};if(existing.request_fingerprint!==fingerprint)return{kind:"divergent" as const};const prior=this.attempt(c,companyId,existing.id);if(!prior&&existing.status==="pending")return{kind:"legacy_incomplete" as const};if(existing.status==="ready"&&prior?.state==="settled")return{kind:"same" as const,asset:asset(existing)};return prior?.state==="retryable_failure"?{kind:"retryable_failure" as const}:prior?.state==="terminal_failure"?{kind:"terminal_failure" as const}:{kind:"in_progress" as const};}
  public reserve(c: WorkspaceContext, companyId: number, operation: string, key: string, fingerprint: string, value: MediaAsset, ingest: MediaIngestAttempt, at: string) { return this.tx(() => { if (!this.company(c, companyId)) throw new Error("Media company is outside workspace."); const resolved=this.resolve(c,companyId,operation,key,fingerprint);if(resolved.kind!=="new")return resolved; this.db.prepare("INSERT INTO media_assets(id,workspace_id,company_id,blob_id,kind,media_type,size_bytes,safe_filename,metadata_json,status,created_at,archived_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,'pending',?,NULL,NULL)").run(value.id,c.workspaceId,companyId,null,value.kind,value.mediaType,null,value.filename,JSON.stringify(value.metadata),at); this.db.prepare("INSERT INTO media_idempotency(workspace_id,company_id,operation,idempotency_key,request_fingerprint,asset_id,created_at) VALUES(?,?,?,?,?,?,?)").run(c.workspaceId,companyId,operation,key,fingerprint,value.id,at); this.db.prepare("INSERT INTO media_ingest_attempts(asset_id,workspace_id,company_id,candidate_blob_id,staging_storage_reference,final_storage_reference,sha256_digest,size_bytes,inspected_media_type,state,lease_owner,lease_token,lease_expires_at,attempt_count,safe_failure_category,created_at,updated_at,settled_at) VALUES(?,?,?,?,?,?,?,?,?,'reserved',NULL,NULL,NULL,0,NULL,?,?,NULL)").run(value.id,c.workspaceId,companyId,ingest.candidateBlobId,ingest.stagingStorageReference,ingest.finalStorageReference,ingest.digest,ingest.sizeBytes,ingest.inspectedMediaType,at,at); this.event(c,companyId,value.id,"reserved",at); return { kind: "reserved" as const, asset: value }; }); }
  public markStaged(c:WorkspaceContext,companyId:number,assetId:string,at:string):boolean{return this.tx(()=>Number(this.db.prepare("UPDATE media_ingest_attempts SET state='staged',attempt_count=attempt_count+1,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state='reserved'").run(at,assetId,c.workspaceId,companyId).changes)===1);}
  public markPromoted(c:WorkspaceContext,companyId:number,assetId:string,at:string):boolean{return this.tx(()=>Number(this.db.prepare("UPDATE media_ingest_attempts SET state='promoted',attempt_count=attempt_count+1,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state='staged'").run(at,assetId,c.workspaceId,companyId).changes)===1);}
  public complete(c: WorkspaceContext, companyId: number, assetId: string, candidate: MediaBlob, at: string): MediaAsset | null { return this.tx(() => { const current=this.row(c,companyId,assetId),ingest=this.attempt(c,companyId,assetId); if (!current || current.status!=="pending"||!ingest||ingest.state!=="promoted"||ingest.candidate_blob_id!==candidate.id||ingest.final_storage_reference!==candidate.storageReference) return null; const found=this.db.prepare("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND sha256_digest=? AND size_bytes=? AND media_type=? AND state='active'").get(c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType) as Row|undefined; const chosen=found?blob(found):candidate; if(!found)this.db.prepare("INSERT INTO media_blobs(id,workspace_id,company_id,sha256_digest,size_bytes,media_type,storage_reference,state,created_at) VALUES(?,?,?,?,?,?,?,'active',?)").run(candidate.id,c.workspaceId,companyId,candidate.digest,candidate.sizeBytes,candidate.mediaType,candidate.storageReference,at); const updated=this.db.prepare("UPDATE media_assets SET blob_id=?,media_type=?,size_bytes=?,status='ready' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'").run(chosen.id,chosen.mediaType,chosen.sizeBytes,assetId,c.workspaceId,companyId);if(Number(updated.changes)!==1)throw new Error("Media settlement lost its asset.");this.db.prepare("UPDATE media_ingest_attempts SET state='settled',safe_failure_category=NULL,settled_at=?,updated_at=? WHERE asset_id=? AND state='promoted'").run(at,at,assetId); this.event(c,companyId,assetId,"ready",at); return this.findAsset(c,companyId,assetId); }); }
  public fail(c: WorkspaceContext, companyId: number, assetId: string, category: string, retryable: boolean, at: string): void { this.tx(()=>{const state=retryable?"retryable_failure":"terminal_failure";if(!retryable)this.db.prepare("UPDATE media_assets SET status='failed' WHERE id=? AND workspace_id=? AND company_id=? AND status='pending'").run(assetId,c.workspaceId,companyId);this.db.prepare("UPDATE media_ingest_attempts SET state=?,safe_failure_category=?,settled_at=CASE WHEN ? THEN NULL ELSE ? END,updated_at=? WHERE asset_id=? AND workspace_id=? AND company_id=? AND state IN ('reserved','staged','promoted','retryable_failure')").run(state,category,retryable?1:0,at,at,assetId,c.workspaceId,companyId);this.event(c,companyId,assetId,`failed:${category}`,at);}); }
  public findIngestAttempt(c:WorkspaceContext,companyId:number,assetId:string):MediaIngestAttempt|null{const row=this.attempt(c,companyId,assetId);return row?attempt(row):null;}
  public findAsset(c: WorkspaceContext, companyId: number, id: string): MediaAsset | null { const row=this.row(c,companyId,id); return row?asset(row):null; }
  public findBlob(c: WorkspaceContext, companyId: number, digest: string, size: number, type: string): MediaBlob | null { const row=this.db.prepare("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND sha256_digest=? AND size_bytes=? AND media_type=? AND state='active'").get(c.workspaceId,companyId,digest,size,type)as Row|undefined;return row?blob(row):null; }
  public archive(c: WorkspaceContext, companyId: number, id: string, at: string): MediaAsset | null { return this.tx(()=>{const result=this.db.prepare("UPDATE media_assets SET status='archived',archived_at=? WHERE id=? AND workspace_id=? AND company_id=? AND status='ready'").run(at,id,c.workspaceId,companyId);if(Number(result.changes)!==1)return null;this.event(c,companyId,id,"archived",at);return this.findAsset(c,companyId,id);}); }
  public delete(c: WorkspaceContext, companyId: number, id: string, at: string) { return this.tx(()=>{const current=this.row(c,companyId,id);if(!current||!["ready","archived"].includes(current.status))return null;if(this.db.prepare("SELECT 1 FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=?").get(c.workspaceId,companyId,id))throw new MediaDomainError("media_asset_has_associations");this.db.prepare("UPDATE media_assets SET status='deleted',deleted_at=? WHERE id=?").run(at,id);this.event(c,companyId,id,"deleted",at);let reclaim:MediaBlob|null=null;if(current.blob_id){const live=this.db.prepare("SELECT 1 FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('pending','ready','archived') LIMIT 1").get(c.workspaceId,companyId,current.blob_id);if(!live){const row=this.db.prepare("SELECT * FROM media_blobs WHERE id=? AND workspace_id=? AND company_id=? AND state='active'").get(current.blob_id,c.workspaceId,companyId)as Row|undefined;if(row){this.db.prepare("UPDATE media_blobs SET state='reclaim_pending' WHERE id=? AND state='active'").run(current.blob_id);reclaim={...blob(row),state:"reclaim_pending"};this.event(c,companyId,id,"physical_reclaim_marked",at);}}}return{asset:asset(this.row(c,companyId,id)!),reclaim};},"delete"); }
  public finalizeReclaim(c: WorkspaceContext,companyId:number,blobId:string,at:string):void{this.tx(()=>{const result=this.db.prepare("UPDATE media_blobs SET state='reclaimed' WHERE id=? AND workspace_id=? AND company_id=? AND state='reclaim_pending' AND NOT EXISTS(SELECT 1 FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status IN ('pending','ready','archived'))").run(blobId,c.workspaceId,companyId,c.workspaceId,companyId,blobId);if(Number(result.changes)===1){const row=this.db.prepare("SELECT id FROM media_assets WHERE workspace_id=? AND company_id=? AND blob_id=? AND status='deleted' ORDER BY rowid DESC LIMIT 1").get(c.workspaceId,companyId,blobId)as{id:string}|undefined;if(row)this.event(c,companyId,row.id,"physical_reclaim_finalized",at);}});}
  public createAssociation(c:WorkspaceContext,value:MediaAssociation,at:string,owns:()=>boolean):MediaAssociation|null{return this.tx(()=>{if(!this.company(c,value.companyId))return null;const current=this.row(c,value.companyId,value.assetId);if(!current||current.status!=="ready"||current.archived_at!==null||current.deleted_at!==null||!owns())return null;const existing=this.db.prepare("SELECT id,created_at FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? AND owner_type=? AND owner_id=?").get(c.workspaceId,value.companyId,value.assetId,value.ownerType,value.ownerId)as{id:string;created_at:string}|undefined;if(existing)return Object.freeze({...value,id:existing.id,createdAt:existing.created_at});this.db.prepare("INSERT INTO media_asset_associations(id,workspace_id,company_id,asset_id,owner_type,owner_id,created_at) VALUES(?,?,?,?,?,?,?)").run(value.id,c.workspaceId,value.companyId,value.assetId,value.ownerType,value.ownerId,at);this.event(c,value.companyId,value.assetId,"association_created",at);return value;},"attach");}
  public listAssociations(c:WorkspaceContext,companyId:number,assetId:string):readonly MediaAssociation[]{return(this.db.prepare("SELECT * FROM media_asset_associations WHERE workspace_id=? AND company_id=? AND asset_id=? ORDER BY created_at,id").all(c.workspaceId,companyId,assetId)as Array<Row & {asset_id:string;owner_type:MediaAssociation["ownerType"];owner_id:string}>).map(row=>Object.freeze({id:row.id,assetId:row.asset_id,workspaceId:row.workspace_id,companyId:row.company_id,ownerType:row.owner_type,ownerId:row.owner_id,createdAt:row.created_at}));}
  public open(c:WorkspaceContext,companyId:number,assetId:string):MediaBlob|null{const row=this.db.prepare("SELECT b.* FROM media_assets a JOIN media_blobs b ON b.id=a.blob_id WHERE a.id=? AND a.workspace_id=? AND a.company_id=? AND a.status='ready' AND b.state='active'").get(assetId,c.workspaceId,companyId)as Row|undefined;return row?blob(row):null;}
  public listEvents(c:WorkspaceContext,companyId:number,assetId:string):readonly string[]{return(this.db.prepare("SELECT event_type FROM media_asset_events WHERE workspace_id=? AND company_id=? AND asset_id=? ORDER BY rowid").all(c.workspaceId,companyId,assetId)as Array<{event_type:string}>).map(row=>row.event_type);}
  public listPendingReclaims(c:WorkspaceContext,companyId:number):readonly MediaBlob[]{return(this.db.prepare("SELECT * FROM media_blobs WHERE workspace_id=? AND company_id=? AND state='reclaim_pending' ORDER BY id").all(c.workspaceId,companyId)as Row[]).map(blob);}
  private row(c:WorkspaceContext,companyId:number,id:string):Row|undefined{return this.db.prepare("SELECT * FROM media_assets WHERE id=? AND workspace_id=? AND company_id=?").get(id,c.workspaceId,companyId)as Row|undefined;}
  private attempt(c:WorkspaceContext,companyId:number,assetId:string):AttemptRow|undefined{return this.db.prepare("SELECT * FROM media_ingest_attempts WHERE asset_id=? AND workspace_id=? AND company_id=?").get(assetId,c.workspaceId,companyId)as AttemptRow|undefined;}
  private company(c:WorkspaceContext,companyId:number):boolean{return this.db.prepare("SELECT 1 FROM companies WHERE workspace_id=? AND id=?").get(c.workspaceId,companyId)!==undefined;}
  private event(c:WorkspaceContext,companyId:number,assetId:string,type:string,at:string):void{this.db.prepare("INSERT INTO media_asset_events(id,workspace_id,company_id,asset_id,event_type,occurred_at) VALUES(?,?,?,?,?,?)").run(`mae_${randomUUID().replace(/-/gu,"")}`,c.workspaceId,companyId,assetId,type,at);}
  private tx<T>(operation:()=>T, label?: "attach" | "delete"):T{const owns=!this.db.isTransaction;if(owns){if(label)this.transactionHook?.beforeBegin?.(label);this.db.exec("BEGIN IMMEDIATE;");}try{const value=operation();if(owns){if(label)this.transactionHook?.beforeCommit?.(label);this.db.exec("COMMIT;");}return value;}catch(error){if(owns&&this.db.isTransaction)this.db.exec("ROLLBACK;");throw error;}}
}
