import type { SynchronousDatabase } from "../config/synchronousDatabase.js";

export interface PlatformOverview { readonly totalUsers:number; readonly totalWorkspaces:number; readonly totalCompanies:number; readonly totalAssistantProfiles:number; readonly webChatConnections:number; readonly whatsAppConnections:{readonly total:number;readonly active:number;readonly healthy:number;readonly degraded:number}; }
export interface PlatformWorkspaceSummary { readonly id:string; readonly name:string; readonly createdAt:string; readonly memberCount:number; readonly companyCount:number; readonly assistantProfileCount:number; readonly webChatConnectionCount:number; readonly whatsApp:{readonly total:number;readonly active:number;readonly healthy:number;readonly degraded:number}; readonly latestActivityAt:string|null; }
export interface PlatformWorkspacePageRow { readonly cursorId:number; readonly summary:PlatformWorkspaceSummary; }
export interface PlatformUserSummary { readonly id:string; readonly email:string; readonly createdAt:string; readonly emailVerified:boolean; readonly activeWorkspaceMembershipCount:number; readonly hasActiveWorkspaceMembership:boolean; }
export interface PlatformUserPageRow { readonly cursorId:number; readonly summary:PlatformUserSummary; }

export class PlatformAdministrationRepository {
  public constructor(private readonly database:SynchronousDatabase) {}
  public overview():PlatformOverview { const row=this.database.prepare(`SELECT (SELECT COUNT(*) FROM users) totalUsers,(SELECT COUNT(*) FROM workspaces) totalWorkspaces,(SELECT COUNT(*) FROM companies) totalCompanies,(SELECT COUNT(*) FROM assistant_profiles) totalAssistantProfiles,(SELECT COUNT(*) FROM web_chat_connections) webChatConnections,(SELECT COUNT(*) FROM whatsapp_connections) whatsAppTotal,(SELECT COUNT(*) FROM whatsapp_connections WHERE status='active') whatsAppActive,(SELECT COUNT(*) FROM whatsapp_connection_operational_states WHERE health_state='healthy') whatsAppHealthy,(SELECT COUNT(*) FROM whatsapp_connection_operational_states WHERE health_state='degraded') whatsAppDegraded`).get() as Record<string,number>;return Object.freeze({totalUsers:Number(row.totalUsers),totalWorkspaces:Number(row.totalWorkspaces),totalCompanies:Number(row.totalCompanies),totalAssistantProfiles:Number(row.totalAssistantProfiles),webChatConnections:Number(row.webChatConnections),whatsAppConnections:Object.freeze({total:Number(row.whatsAppTotal),active:Number(row.whatsAppActive),healthy:Number(row.whatsAppHealthy),degraded:Number(row.whatsAppDegraded)})}); }
  public listWorkspaces(cursor:{readonly createdAt:string;readonly id:number}|null,limit:number):readonly PlatformWorkspacePageRow[]{const rows=this.database.prepare(`SELECT w.id cursorId,w.public_id id,w.name,w.created_at createdAt,(SELECT COUNT(*) FROM memberships m WHERE m.workspace_id=w.id AND m.status='active') memberCount,(SELECT COUNT(*) FROM companies c WHERE c.workspace_id=w.id) companyCount,(SELECT COUNT(*) FROM assistant_profiles ap INNER JOIN companies c ON c.id=ap.company_id WHERE c.workspace_id=w.id) assistantProfileCount,(SELECT COUNT(*) FROM web_chat_connections wc WHERE wc.workspace_id=w.id) webChatConnectionCount,(SELECT COUNT(*) FROM whatsapp_connections wa WHERE wa.workspace_id=w.id) whatsAppTotal,(SELECT COUNT(*) FROM whatsapp_connections wa WHERE wa.workspace_id=w.id AND wa.status='active') whatsAppActive,(SELECT COUNT(*) FROM whatsapp_connections wa INNER JOIN whatsapp_connection_operational_states ws ON ws.whatsapp_connection_id=wa.id WHERE wa.workspace_id=w.id AND ws.health_state='healthy') whatsAppHealthy,(SELECT COUNT(*) FROM whatsapp_connections wa INNER JOIN whatsapp_connection_operational_states ws ON ws.whatsapp_connection_id=wa.id WHERE wa.workspace_id=w.id AND ws.health_state='degraded') whatsAppDegraded,(SELECT MAX(activityAt) FROM (SELECT MAX(ce.occurred_at) activityAt FROM company_events ce WHERE ce.workspace_id=w.id UNION ALL SELECT MAX(ws.updated_at) activityAt FROM whatsapp_connections wa INNER JOIN whatsapp_connection_operational_states ws ON ws.whatsapp_connection_id=wa.id)) latestActivityAt FROM workspaces w WHERE (? IS NULL OR w.created_at<? OR (w.created_at=? AND w.id<?)) ORDER BY w.created_at DESC,w.id DESC LIMIT ?`).all(cursor?.createdAt??null,cursor?.createdAt??null,cursor?.createdAt??null,cursor?.id??null,limit+1) as Array<Record<string,unknown>>;return rows.map(row=>Object.freeze({cursorId:Number(row.cursorId),summary:Object.freeze({id:String(row.id),name:String(row.name),createdAt:String(row.createdAt),memberCount:Number(row.memberCount),companyCount:Number(row.companyCount),assistantProfileCount:Number(row.assistantProfileCount),webChatConnectionCount:Number(row.webChatConnectionCount),whatsApp:Object.freeze({total:Number(row.whatsAppTotal),active:Number(row.whatsAppActive),healthy:Number(row.whatsAppHealthy),degraded:Number(row.whatsAppDegraded)}),latestActivityAt:row.latestActivityAt===null?null:String(row.latestActivityAt)})}));}
  public listUsers(cursor:{readonly createdAt:string;readonly id:number}|null,limit:number):readonly PlatformUserPageRow[]{const rows=this.database.prepare(`SELECT u.rowid cursorId,u.id id,i.email email,u.created_at createdAt,i.email_verified emailVerified,(SELECT COUNT(*) FROM memberships m WHERE m.user_id=u.id AND m.status='active') activeWorkspaceMembershipCount FROM users u INNER JOIN authentication_identities i ON i.user_id=u.id WHERE (? IS NULL OR u.created_at<? OR (u.created_at=? AND u.rowid<?)) ORDER BY u.created_at DESC,u.rowid DESC LIMIT ?`).all(cursor?.createdAt??null,cursor?.createdAt??null,cursor?.createdAt??null,cursor?.id??null,limit+1) as Array<Record<string,unknown>>;return rows.map(row=>{const activeWorkspaceMembershipCount=Number(row.activeWorkspaceMembershipCount);return Object.freeze({cursorId:Number(row.cursorId),summary:Object.freeze({id:String(row.id),email:String(row.email),createdAt:String(row.createdAt),emailVerified:Number(row.emailVerified)===1,activeWorkspaceMembershipCount,hasActiveWorkspaceMembership:activeWorkspaceMembershipCount>0})});});}
}
