import type { SqlDatabase } from "../config/sqlDatabase.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";

export class SchedulingConfigurationRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async read(context: WorkspaceContext, companyId: number): Promise<Record<string, unknown> | null> { const controls=await this.database.query<Row>("SELECT version FROM scheduling_configuration_controls WHERE workspace_id=? AND company_id=?",[context.workspaceId,companyId]); if(!controls[0]) return null; const [locations,resources,services,windows,exceptions]=await Promise.all([this.database.query<Row>("SELECT id,name,address,timezone,active,created_at,updated_at FROM scheduling_locations WHERE workspace_id=? AND company_id=? ORDER BY name,id",[context.workspaceId,companyId]),this.database.query<Row>("SELECT id,location_id,name,timezone,capacity,active,created_at,updated_at FROM scheduling_resources WHERE workspace_id=? AND company_id=? ORDER BY name,id",[context.workspaceId,companyId]),this.database.query<Row>("SELECT id,resource_id,name,duration_minutes,buffer_before_minutes,buffer_after_minutes,slot_granularity_minutes,minimum_lead_minutes,maximum_horizon_days,active,created_at,updated_at FROM scheduling_services WHERE workspace_id=? AND company_id=? ORDER BY name,id",[context.workspaceId,companyId]),this.database.query<Row>("SELECT id,resource_id,weekday,start_time,end_time FROM scheduling_working_windows WHERE workspace_id=? AND company_id=? ORDER BY resource_id,weekday,start_time",[context.workspaceId,companyId]),this.database.query<Row>("SELECT id,resource_id,local_date,kind,start_time,end_time FROM scheduling_availability_exceptions WHERE workspace_id=? AND company_id=? ORDER BY resource_id,local_date,start_time",[context.workspaceId,companyId])]); return {aggregateVersion:Number(controls[0].version),locations,resources,services,weeklyWorkingWindows:windows,dateExceptions:exceptions}; }
  public async mutate(context: WorkspaceContext,companyId:number,input:{operationId:string;operation:string;fingerprint:string;expectedVersion:number;actorId:string;at:string;apply:(db:SqlDatabase)=>Promise<{entityType:string;entityId:string;action:string}>}):Promise<{kind:"applied";result:Record<string,unknown>}|{kind:"replayed";result:Record<string,unknown>}|{kind:"divergent"}|{kind:"stale"}> { return this.database.transaction(async db=>{const prior=await db.query<Row>("SELECT request_fingerprint,outcome_json FROM scheduling_configuration_operations WHERE workspace_id=? AND company_id=? AND operation_id=?",[context.workspaceId,companyId,input.operationId]);if(prior[0])return prior[0].request_fingerprint===input.fingerprint?{kind:"replayed",result:JSON.parse(String(prior[0].outcome_json)) as Record<string,unknown>}:{kind:"divergent"};const controls=await db.query<Row>("SELECT version FROM scheduling_configuration_controls WHERE workspace_id=? AND company_id=?",[context.workspaceId,companyId]);if(!controls[0]) throw new Error("not_found");const current=Number(controls[0].version);if(current!==input.expectedVersion)return{kind:"stale"};const affected=await input.apply(db),version=current+1,result={aggregateVersion:version,affected};await db.execute("UPDATE scheduling_configuration_controls SET version=?,updated_at=? WHERE workspace_id=? AND company_id=? AND version=?",[version,input.at,context.workspaceId,companyId,current]);await db.execute("INSERT INTO scheduling_configuration_operations(workspace_id,company_id,operation_id,operation,request_fingerprint,expected_version,resulting_version,actor_user_id,outcome_json,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?)",[context.workspaceId,companyId,input.operationId,input.operation,input.fingerprint,input.expectedVersion,version,input.actorId,JSON.stringify(result),input.at]);await db.execute("INSERT INTO scheduling_configuration_audit_events(id,workspace_id,company_id,operation_id,actor_user_id,affected_entity_type,affected_entity_id,action,resulting_version,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?)",[`sca_${crypto.randomUUID().replaceAll("-","")}`,context.workspaceId,companyId,input.operationId,input.actorId,affected.entityType,affected.entityId,affected.action,version,input.at]);return{kind:"applied",result};}); }
}
interface Row extends Record<string,unknown>{version:number;request_fingerprint:string;outcome_json:string}
