import type { RequestHandler, Response } from "express";
import { ActivationNotFoundError, ActivationService, ActivationUnavailableError, ActivationVerificationUnavailableError } from "../activation/services/activationService.js";
import type { ActivationProjection, ActivationStageId } from "../activation/domain/activation.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";

const companyId=(value:unknown):number=>{const parsed=typeof value==="string"&&/^\d+$/.test(value)?Number(value):NaN;if(!Number.isSafeInteger(parsed)||parsed<1)throw new ActivationNotFoundError();return parsed;};
export function createGetActivationController(service:ActivationService,context:WorkspaceContext):RequestHandler{return async(req,res)=>{try{const id=companyId(req.params.companyId);res.json(responseBody(await service.projection(context,id),id));}catch(error:unknown){respond(res,error);}};}
export function createStartActivationVerificationController(service:ActivationService,context:WorkspaceContext):RequestHandler{return async(req,res):Promise<void>=>{try{if(req.body!==undefined&&(!req.body||typeof req.body!=="object"||Array.isArray(req.body)||Object.keys(req.body).length!==0)){res.status(400).json({error:{code:"invalid_activation_verification_request",message:"Verification request is invalid."}});return;}res.status(201).json(await service.startVerification(context,companyId(req.params.companyId)));}catch(error:unknown){respond(res,error);}};}
function respond(response:Response,error:unknown):void{if(error instanceof ActivationNotFoundError){response.status(404).json({error:{code:"activation_not_found",message:"Activation is unavailable."}});return;}if(error instanceof ActivationVerificationUnavailableError){response.status(409).json({error:{code:"activation_verification_unavailable",message:"Web Chat must be active before verification."}});return;}response.status(error instanceof ActivationUnavailableError?503:503).json({error:{code:"activation_unavailable",message:"Activation is temporarily unavailable."}});}
export function responseBody(value:ActivationProjection,companyId:number){return Object.freeze({...value,stages:Object.freeze(value.stages.map(stage=>Object.freeze({...stage,actionPath:actionPath(stage.id,companyId)})))});}
function actionPath(id:ActivationStageId,companyId:number):string|null{if(id==="company")return `/companies/${companyId}`;if(id==="knowledge")return `/companies/${companyId}/knowledge`;if(id==="assistant")return `/companies/${companyId}/assistant`;if(id==="web_chat")return `/companies/${companyId}/channels/web-chat`;if(id==="human_ops")return "/conversations";return null;}
