import type { RequestHandler, Response } from "express";
import { PilotReadinessNotFoundError, PilotReadinessService, PilotReadinessUnavailableError, type PilotReadinessProjection } from "../onboarding/services/pilotReadinessService.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";

export function createGetPilotReadinessController(service: PilotReadinessService, context: WorkspaceContext): RequestHandler { return async (request, response): Promise<void> => { try { const id = companyId(request.params.companyId); response.json(responseBody(await service.get(context, id), id)); } catch (error: unknown) { respond(response, error); } }; }
export function responseBody(value: PilotReadinessProjection, companyId: number) { return Object.freeze({ overall: value.overall, classification: value.classification, checks: value.checks.map((check) => Object.freeze({ id: check.id, required: check.required, status: check.status, owner: check.owner, reasonCode: check.reasonCode, actionPath: actionPath(check.id, companyId) })), nextAction: value.nextAction, evaluatedAt: value.evaluatedAt, policyVersion: value.policyVersion }); }
function actionPath(id: PilotReadinessProjection["checks"][number]["id"], companyId: number): string | null { if (id === "workspace_context") return "/dashboard"; if (id === "company") return `/companies/${companyId}`; if (id === "default_assistant") return `/companies/${companyId}/assistant`; if (id === "published_knowledge") return `/companies/${companyId}/knowledge`; if (id === "commercial_entitlement") return "/billing"; if (id === "web_chat") return `/companies/${companyId}/channels/web-chat`; if (id === "whatsapp") return `/companies/${companyId}/channels/whatsapp`; if (id === "operational_channel") return `/companies/${companyId}/channels`; return `/companies/${companyId}/assistant`; }
function companyId(value: unknown): number { const parsed = typeof value === "string" && /^\d+$/.test(value) ? Number(value) : NaN; if (!Number.isSafeInteger(parsed) || parsed < 1) throw new PilotReadinessNotFoundError(); return parsed; }
function respond(response: Response, error: unknown): void { if (error instanceof PilotReadinessNotFoundError) { response.status(404).json({ error: { code: "pilot_readiness_not_found", message: "Pilot readiness is unavailable." } }); return; } const code = error instanceof PilotReadinessUnavailableError ? "pilot_readiness_unavailable" : "pilot_readiness_unavailable"; response.status(503).json({ error: { code, message: "Pilot readiness is temporarily unavailable." } }); }
