import type { RequestHandler, Response } from "express";
import type { WorkspaceContext } from "../types/workspaceContext.js";
import { VoiceReadNotFoundError, VoiceReadService } from "../whatsapp/services/voiceReadService.js";

export function createVoiceReadController(service: VoiceReadService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json(await service.read(context, company(req.params.companyId), parameter(req.params.conversationId), parameter(req.params.messageId))); } catch (error: unknown) { respond(res, error); } }; }
export function createVoicePlaybackController(service: VoiceReadService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { if (typeof req.headers.range === "string") { res.status(416).setHeader("Accept-Ranges", "none").end(); return; } const value = await service.playback(context, company(req.params.companyId), parameter(req.params.conversationId), parameter(req.params.messageId)); res.setHeader("Cache-Control", "no-store, private"); res.setHeader("Content-Type", value.mediaType); res.setHeader("Content-Length", String(value.content.byteLength)); res.setHeader("Content-Disposition", "inline; filename=voice-audio"); res.setHeader("Content-Security-Policy", "sandbox"); res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("Accept-Ranges", "none"); res.end(value.content); } catch (error: unknown) { respond(res, error); } }; }
function parameter(value: string | string[] | undefined): string { if (typeof value !== "string" || !value) throw new VoiceReadNotFoundError(); return value; }
function company(value: string | string[] | undefined): number { const parsed = parameter(value); if (!/^\d+$/u.test(parsed)) throw new VoiceReadNotFoundError(); return Number(parsed); }
function respond(res: Response, error: unknown): void { if (error instanceof VoiceReadNotFoundError) { res.status(404).json({ error: "Voice message was not found." }); return; } res.status(500).json({ error: "Voice message could not be read." }); }
