import type { RequestHandler, Response } from "express";
import type { WhatsAppConnection } from "../whatsapp/domain/whatsappConnection.js";
import { WhatsAppConnectionConflictError, WhatsAppConnectionCredentialsNotConfiguredError, WhatsAppConnectionKnowledgeUnavailableError, WhatsAppConnectionMetaReconnectRequiredError, WhatsAppConnectionNotFoundError, WhatsAppConnectionNotValidatedError, WhatsAppConnectionProfileNotExecutableError, WhatsAppConnectionService, WhatsAppConnectionValidationError } from "../whatsapp/services/WhatsAppConnectionService.js";
import { AbuseLimitExceededError } from "../abuse/rateLimitService.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";

export function createWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.status(201).json(response(await service.create(context, req.params.companyId, req.body))); } catch (error: unknown) { respond(res, error); } }; }
export function createListWhatsAppConnectionsController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json((await service.list(context, req.params.companyId)).map(response)); } catch (error: unknown) { respond(res, error); } }; }
export function createGetWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json(response(await service.get(context, req.params.companyId, req.params.connectionId))); } catch (error: unknown) { respond(res, error); } }; }
export function createUpdateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json(response(await service.update(context, req.params.companyId, req.params.connectionId, req.body))); } catch (error: unknown) { respond(res, error); } }; }
export function createGetWhatsAppConnectionStatusController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json(await service.status(context, req.params.companyId, req.params.connectionId)); } catch (error: unknown) { respond(res, error); } }; }
export function createConfigureWhatsAppCredentialsController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json(await service.configureCredentials(context, req.params.companyId, req.params.connectionId, req.body)); } catch (error: unknown) { respond(res, error); } }; }
export function createValidateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { const actorId = typeof res.locals.actorId === "string" ? res.locals.actorId : "unknown"; res.json(await service.validate(context, req.params.companyId, req.params.connectionId, actorId)); } catch (error: unknown) { respond(res, error); } }; }
export function createActivateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json(await service.activate(context, req.params.companyId, req.params.connectionId)); } catch (error: unknown) { respond(res, error); } }; }
export function createDeactivateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return async (req, res): Promise<void> => { try { res.json(await service.deactivate(context, req.params.companyId, req.params.connectionId)); } catch (error: unknown) { respond(res, error); } }; }
function response(value: WhatsAppConnection) { return { id: value.id, assistantProfileId: value.assistantProfileId, phoneNumberId: value.phoneNumberId, whatsappBusinessAccountId: value.whatsappBusinessAccountId, status: value.status, createdAt: value.createdAt, updatedAt: value.updatedAt }; }
function respond(res: Response, error: unknown): void { if (error instanceof AbuseLimitExceededError) { res.setHeader("Retry-After", String(error.retryAfterSeconds)); res.status(429).json({ error: { code: "rate_limited", message: "Request is temporarily unavailable." } }); return; } if (error instanceof WhatsAppConnectionValidationError) { res.status(400).json({ error: error.message }); return; } if (error instanceof WhatsAppConnectionNotFoundError) { res.status(404).json({ error: error.message }); return; } if (error instanceof WhatsAppConnectionMetaReconnectRequiredError) { res.status(409).json({ error: { code: "meta_reconnect_required", message: "Reconnect this WhatsApp Connection with Meta." } }); return; } if (error instanceof WhatsAppConnectionConflictError || error instanceof WhatsAppConnectionProfileNotExecutableError || error instanceof WhatsAppConnectionCredentialsNotConfiguredError || error instanceof WhatsAppConnectionNotValidatedError || error instanceof WhatsAppConnectionKnowledgeUnavailableError) { res.status(409).json({ error: error.message }); return; } console.error("WhatsApp Connection operation failed.", error); res.status(500).json({ error: "WhatsApp Connection operation failed." }); }
