import type { RequestHandler, Response } from "express";
import type { WhatsAppConnection } from "../whatsapp/domain/whatsappConnection.js";
import { WhatsAppConnectionConflictError, WhatsAppConnectionCredentialsNotConfiguredError, WhatsAppConnectionKnowledgeUnavailableError, WhatsAppConnectionNotFoundError, WhatsAppConnectionNotValidatedError, WhatsAppConnectionProfileNotExecutableError, WhatsAppConnectionService, WhatsAppConnectionValidationError } from "../whatsapp/services/WhatsAppConnectionService.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";

export function createWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { try { res.status(201).json(response(service.create(context, req.params.companyId, req.body))); } catch (error: unknown) { respond(res, error); } }; }
export function createListWhatsAppConnectionsController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { try { res.json(service.list(context, req.params.companyId).map(response)); } catch (error: unknown) { respond(res, error); } }; }
export function createGetWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { try { res.json(response(service.get(context, req.params.companyId, req.params.connectionId))); } catch (error: unknown) { respond(res, error); } }; }
export function createUpdateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { try { res.json(response(service.update(context, req.params.companyId, req.params.connectionId, req.body))); } catch (error: unknown) { respond(res, error); } }; }
export function createGetWhatsAppConnectionStatusController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { try { res.json(service.status(context, req.params.companyId, req.params.connectionId)); } catch (error: unknown) { respond(res, error); } }; }
export function createConfigureWhatsAppCredentialsController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { try { res.json(service.configureCredentials(context, req.params.companyId, req.params.connectionId, req.body)); } catch (error: unknown) { respond(res, error); } }; }
export function createValidateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { void service.validate(context, req.params.companyId, req.params.connectionId).then((value) => res.json(value)).catch((error: unknown) => respond(res, error)); }; }
export function createActivateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { void service.activate(context, req.params.companyId, req.params.connectionId).then((value) => res.json(value)).catch((error: unknown) => respond(res, error)); }; }
export function createDeactivateWhatsAppConnectionController(service: WhatsAppConnectionService, context: WorkspaceContext): RequestHandler { return (req, res): void => { try { res.json(service.deactivate(context, req.params.companyId, req.params.connectionId)); } catch (error: unknown) { respond(res, error); } }; }
function response(value: WhatsAppConnection) { return { id: value.id, assistantProfileId: value.assistantProfileId, phoneNumberId: value.phoneNumberId, whatsappBusinessAccountId: value.whatsappBusinessAccountId, status: value.status, createdAt: value.createdAt, updatedAt: value.updatedAt }; }
function respond(res: Response, error: unknown): void { if (error instanceof WhatsAppConnectionValidationError) { res.status(400).json({ error: error.message }); return; } if (error instanceof WhatsAppConnectionNotFoundError) { res.status(404).json({ error: error.message }); return; } if (error instanceof WhatsAppConnectionConflictError || error instanceof WhatsAppConnectionProfileNotExecutableError || error instanceof WhatsAppConnectionCredentialsNotConfiguredError || error instanceof WhatsAppConnectionNotValidatedError || error instanceof WhatsAppConnectionKnowledgeUnavailableError) { res.status(409).json({ error: error.message }); return; } console.error("WhatsApp Connection operation failed.", error); res.status(500).json({ error: "WhatsApp Connection operation failed." }); }
