import type{Request,RequestHandler}from"express";import type{UserId}from"../identity/domain/user.js";import type{AuthenticationService}from"../identity/services/authenticationService.js";import{WorkspaceAdministrationConflict,WorkspaceAdministrationError,type WorkspaceAdministrationService}from"../workspace/services/workspaceAdministrationService.js";
function body(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new WorkspaceAdministrationError();return value as Record<string,unknown>;}function field(value:Record<string,unknown>,key:string):string{if(typeof value[key]!=="string")throw new WorkspaceAdministrationError();return value[key];}
function cookie(req:Request,name:string):string|null{for(const part of(req.headers.cookie??"").split(";")){const[key,...rest]=part.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="));}return null;}
function param(req:Request,key:string):string{const value=req.params[key];if(typeof value!=="string")throw new WorkspaceAdministrationError();return value;}
function user(req:Request,authentication:AuthenticationService):UserId{const raw=cookie(req,authentication.cookieName()),current=raw?authentication.current(raw):null;if(!current)throw new WorkspaceAdministrationError();return current.userId as UserId;}
function stateUser(req:Request,authentication:AuthenticationService):UserId{const raw=cookie(req,authentication.cookieName());let sameOrigin=false;try{sameOrigin=typeof req.headers.origin==="string"&&new URL(req.headers.origin).host===req.headers.host;}catch{sameOrigin=false;}if(!raw||!sameOrigin||typeof req.headers["x-csrf-token"]!=="string"||req.headers["sec-fetch-site"]==="cross-site"||!authentication.validateCsrf(raw,req.headers["x-csrf-token"]))throw new WorkspaceAdministrationError();return user(req,authentication);}
function safe(handler:RequestHandler):RequestHandler{return async(req,res,next)=>{try{await handler(req,res,next);}catch(error){if(error instanceof WorkspaceAdministrationConflict){res.status(409).json({error:"Workspace state changed."});return;}if(error instanceof WorkspaceAdministrationError){res.status(404).json({error:"Workspace operation is not available."});return;}res.status(503).json({error:"Workspace service is temporarily unavailable."});}};}
export function createWorkspaceAdministrationControllers(service:WorkspaceAdministrationService,authentication:AuthenticationService):Record<string,RequestHandler>{return{
 create:safe((req,res)=>{const b=body(req.body),result=service.createWorkspace(stateUser(req,authentication),field(b,"name"));res.status(201).json({workspace:{id:result.workspace.publicId,name:result.workspace.name},membership:{id:result.member.id,role:result.member.role,status:result.member.status}});}),
 list:safe((req,res)=>res.json(service.listWorkspaces(user(req,authentication)).map(w=>({id:w.publicId,name:w.name,role:w.role})))),
 selected:safe((req,res)=>{const value=service.selected(user(req,authentication));res.json(value?{id:value.publicId,name:value.name,role:value.role}:null);}),
 select:safe((req,res)=>{const value=service.select(stateUser(req,authentication),param(req,"workspaceId"));res.json({id:value.publicId,name:value.name,role:value.role});}),
 memberships:safe((req,res)=>res.json(service.listMemberships(user(req,authentication),param(req,"workspaceId")))),
 invitations:safe((req,res)=>res.json(service.listInvitations(user(req,authentication),param(req,"workspaceId")))),
 invite:safe(async(req,res)=>{const b=body(req.body);await service.invite(stateUser(req,authentication),param(req,"workspaceId"),field(b,"email"),field(b,"role"));res.status(202).json({status:"invitation_requested"});}),
 accept:safe((req,res)=>{const b=body(req.body);service.accept(stateUser(req,authentication),field(b,"proof"),req.ip??"unknown",req.headers["user-agent"]??"");res.status(204).end();}),
 reject:safe((req,res)=>{const b=body(req.body);service.reject(stateUser(req,authentication),field(b,"proof"));res.status(204).end();}),
 revoke:safe((req,res)=>{service.invitationAction(stateUser(req,authentication),param(req,"workspaceId"),param(req,"invitationId"),"revoked");res.status(204).end();}),
 role:safe((req,res)=>{const b=body(req.body);service.changeMembership(stateUser(req,authentication),param(req,"workspaceId"),param(req,"membershipId"),"role",field(b,"role"));res.status(204).end();}),
 suspend:safe((req,res)=>{service.changeMembership(stateUser(req,authentication),param(req,"workspaceId"),param(req,"membershipId"),"suspend");res.status(204).end();}),
 reactivate:safe((req,res)=>{service.changeMembership(stateUser(req,authentication),param(req,"workspaceId"),param(req,"membershipId"),"reactivate");res.status(204).end();}),
 remove:safe((req,res)=>{service.changeMembership(stateUser(req,authentication),param(req,"workspaceId"),param(req,"membershipId"),"remove");res.status(204).end();}),
 leave:safe((req,res)=>{service.leave(stateUser(req,authentication),param(req,"workspaceId"));res.status(204).end();}),
 transfer:safe((req,res)=>{const b=body(req.body);const role=b.actorRole;service.transfer(stateUser(req,authentication),param(req,"workspaceId"),field(b,"targetMembershipId"),typeof role==="string"?role:undefined);res.status(204).end();}),
};}
