import type{Request,RequestHandler}from"express";import{AbuseLimitExceededError}from"../abuse/rateLimitService.js";import type{UserId}from"../identity/domain/user.js";import type{AuthenticationService}from"../identity/services/authenticationService.js";import{WorkspaceAdministrationConflict,WorkspaceAdministrationError,type WorkspaceAdministrationService}from"../workspace/services/workspaceAdministrationService.js";import{PermissionPolicy,type MembershipRole}from"../workspace/domain/membership.js";import{EffectiveRequestAuthorityResolver,type RequestOriginPolicy}from"../identity/infrastructure/requestOriginPolicy.js";
function body(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new WorkspaceAdministrationError();return value as Record<string,unknown>;}function field(value:Record<string,unknown>,key:string):string{if(typeof value[key]!=="string")throw new WorkspaceAdministrationError();return value[key];}
function cookie(req:Request,name:string):string|null{for(const part of(req.headers.cookie??"").split(";")){const[key,...rest]=part.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="));}return null;}
function param(req:Request,key:string):string{const value=req.params[key];if(typeof value!=="string")throw new WorkspaceAdministrationError();return value;}
async function user(req:Request,authentication:AuthenticationService):Promise<UserId>{const raw=cookie(req,authentication.cookieName()),current=raw?await authentication.current(raw):null;if(!current)throw new WorkspaceAdministrationError();return current.userId as UserId;}
const authorityResolver=new EffectiveRequestAuthorityResolver();
async function stateUser(req:Request,authentication:AuthenticationService,originPolicy:RequestOriginPolicy):Promise<UserId>{const raw=cookie(req,authentication.cookieName()),authority=authorityResolver.resolve({protocol:req.protocol,host:req.headers.host,forwardedProtocol:req.headers["x-forwarded-proto"]});const fetchSite=typeof req.headers["sec-fetch-site"]==="string"?req.headers["sec-fetch-site"]:undefined;if(!raw||!authority||!originPolicy.allows({origin:req.headers.origin,fetchSite,effectiveProtocol:authority.protocol,effectiveAuthority:authority.authority})||typeof req.headers["x-csrf-token"]!=="string"||!await authentication.validateCsrf(raw,req.headers["x-csrf-token"]))throw new WorkspaceAdministrationError();return user(req,authentication);}
function safe(handler:RequestHandler):RequestHandler{return async(req,res,next)=>{try{await handler(req,res,next);}catch(error){if(error instanceof AbuseLimitExceededError){res.setHeader("Retry-After",String(error.retryAfterSeconds));res.status(429).json({error:{code:"rate_limited",message:"Request is temporarily unavailable."}});return;}if(error instanceof WorkspaceAdministrationConflict){res.status(409).json({error:"Workspace state changed."});return;}if(error instanceof WorkspaceAdministrationError){res.status(404).json({error:"Workspace operation is not available."});return;}res.status(503).json({error:"Workspace service is temporarily unavailable."});}};}
const permissions=new PermissionPolicy();function workspaceDto(w:{publicId:string;name:string;role:string}){return{id:w.publicId,name:w.name,role:w.role,capabilities:[...permissions.derive(w.role as MembershipRole)].sort()};}
export function createWorkspaceAdministrationControllers(service:WorkspaceAdministrationService,authentication:AuthenticationService,originPolicy:RequestOriginPolicy):Record<string,RequestHandler>{return{
 create:safe(async(req,res)=>{const b=body(req.body);if(Object.keys(b).some(key=>key!=="name"&&key!=="timezone"&&key!=="defaultLocale"))throw new WorkspaceAdministrationError();const timezone=b.timezone,defaultLocale=b.defaultLocale;if(timezone!==undefined&&typeof timezone!=="string")throw new WorkspaceAdministrationError();if(defaultLocale!==undefined&&typeof defaultLocale!=="string")throw new WorkspaceAdministrationError();const result=await service.createWorkspace(await stateUser(req,authentication,originPolicy),field(b,"name"),{...(timezone===undefined?{}:{timezone}),...(defaultLocale===undefined?{}:{defaultLocale})});res.status(201).json({workspace:{id:result.workspace.publicId,name:result.workspace.name,timezone:result.workspace.timezone,defaultLocale:result.workspace.defaultLocale},membership:{id:result.member.id,role:result.member.role,status:result.member.status}});}),
 list:safe(async(req,res)=>res.json((await service.listWorkspaces(await user(req,authentication))).map(workspaceDto))),
 selected:safe(async(req,res)=>{const value=await service.selected(await user(req,authentication));res.json(value?workspaceDto(value):null);}),
 select:safe(async(req,res)=>{const value=await service.select(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"));res.json(workspaceDto(value));}),
 memberships:safe(async(req,res)=>res.json(await service.listMemberships(await user(req,authentication),param(req,"workspaceId")))),
 invitations:safe(async(req,res)=>res.json(await service.listInvitations(await user(req,authentication),param(req,"workspaceId")))),
 invite:safe(async(req,res)=>{const b=body(req.body);await service.invite(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"),field(b,"email"),field(b,"role"));res.status(202).json({status:"invitation_requested"});}),
 accept:safe(async(req,res)=>{const b=body(req.body);await service.accept(await stateUser(req,authentication,originPolicy),field(b,"proof"),req.ip??"unknown",req.headers["user-agent"]??"");res.status(204).end();}),
 reject:safe(async(req,res)=>{const b=body(req.body);await service.reject(await stateUser(req,authentication,originPolicy),field(b,"proof"));res.status(204).end();}),
 revoke:safe(async(req,res)=>{await service.invitationAction(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"),param(req,"invitationId"),"revoked");res.status(204).end();}),
 role:safe(async(req,res)=>{const b=body(req.body);await service.changeMembership(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"),param(req,"membershipId"),"role",field(b,"role"));res.status(204).end();}),
 suspend:safe(async(req,res)=>{await service.changeMembership(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"),param(req,"membershipId"),"suspend");res.status(204).end();}),
 reactivate:safe(async(req,res)=>{await service.changeMembership(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"),param(req,"membershipId"),"reactivate");res.status(204).end();}),
 remove:safe(async(req,res)=>{await service.changeMembership(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"),param(req,"membershipId"),"remove");res.status(204).end();}),
 leave:safe(async(req,res)=>{await service.leave(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"));res.status(204).end();}),
 transfer:safe(async(req,res)=>{const b=body(req.body),role=b.actorRole;await service.transfer(await stateUser(req,authentication,originPolicy),param(req,"workspaceId"),field(b,"targetMembershipId"),typeof role==="string"?role:undefined);res.status(204).end();}),
};}
