import { Router, type Request, type RequestHandler } from "express";
import type { UserRepositoryPort } from "../application/ports/repositories.js";
import type { AuthenticationService } from "../identity/services/authenticationService.js";
import type { UserId } from "../identity/domain/user.js";
import type { RequestOriginPolicy } from "../identity/infrastructure/requestOriginPolicy.js";
import { AuthorizationService } from "../workspace/services/authorizationService.js";
import { WorkspaceResolver } from "../workspace/services/workspaceResolver.js";
import type { WorkspaceContext } from "../types/workspaceContext.js";
import type { BillingRequestContext } from "../controllers/billingController.js";

type Controllers=Record<"summary"|"entitlements"|"catalog"|"payerIdentityOptions"|"setPayerIdentity"|"clearPayerIdentity"|"checkout"|"portal"|"cancel"|"reactivate",(context:BillingRequestContext)=>RequestHandler>;
function cookie(req:Request,name:string):string|null { for (const part of (req.headers.cookie??"").split(";")) { const [key,...rest]=part.trim().split("="); if (key===name) return decodeURIComponent(rest.join("=")); } return null; }
function workspace(req:Request):string { if (typeof req.params.workspaceId!=="string") throw new Error("invalid"); return req.params.workspaceId; }

export function createBillingRouter(dependencies:Readonly<{ authentication:AuthenticationService; users:UserRepositoryPort; authorization:AuthorizationService; resolver:WorkspaceResolver; originPolicy:RequestOriginPolicy; controllers:Controllers; }>):Router {
  const router=Router(); const authorized=(changing:boolean, controller:(context:BillingRequestContext)=>RequestHandler):RequestHandler=>async(req,res,next)=>{ res.setHeader("Cache-Control","no-store, private"); res.setHeader("Pragma","no-cache"); try { const raw=cookie(req,dependencies.authentication.cookieName()), identity=raw?dependencies.authentication.current(raw):null; if (!raw||!identity||typeof identity.authenticationIdentityId!=="string") throw new Error("denied"); const protocol:"http"|"https"|null=req.protocol==="http"||req.protocol==="https"?req.protocol:null, authority=protocol&&req.headers.host?{protocol,authority:req.headers.host}:null, fetchSite=typeof req.headers["sec-fetch-site"]==="string"?req.headers["sec-fetch-site"]:undefined; if (changing&&(!authority||typeof req.headers["x-csrf-token"]!=="string"||!dependencies.originPolicy.allows({origin:req.headers.origin,fetchSite,effectiveProtocol:authority.protocol,effectiveAuthority:authority.authority})||!dependencies.authentication.validateCsrf(raw,req.headers["x-csrf-token"]))) throw new Error("denied"); const user=dependencies.users.findById(identity.userId as UserId); if (!user) throw new Error("denied"); const decision=dependencies.authorization.authorize(user,workspace(req),"workspace:manage"); const context:WorkspaceContext=dependencies.resolver.resolve(decision); await controller({workspaceId:context.workspaceId,callerIdentityId:identity.authenticationIdentityId})(req,res,next); } catch { res.status(404).json({ error:"Resource not found." }); } };
  router.get("/:workspaceId/billing/summary",authorized(false,dependencies.controllers.summary)); router.get("/:workspaceId/billing/entitlements",authorized(false,dependencies.controllers.entitlements)); router.get("/:workspaceId/billing/catalog",authorized(false,dependencies.controllers.catalog)); router.get("/:workspaceId/billing/payer-identity-options",authorized(false,dependencies.controllers.payerIdentityOptions)); router.put("/:workspaceId/billing/payer-identity",authorized(true,dependencies.controllers.setPayerIdentity)); router.delete("/:workspaceId/billing/payer-identity",authorized(true,dependencies.controllers.clearPayerIdentity)); router.post("/:workspaceId/billing/checkout-sessions",authorized(true,dependencies.controllers.checkout)); router.post("/:workspaceId/billing/portal-sessions",authorized(true,dependencies.controllers.portal)); router.post("/:workspaceId/billing/subscription/cancel",authorized(true,dependencies.controllers.cancel)); router.post("/:workspaceId/billing/subscription/reactivate",authorized(true,dependencies.controllers.reactivate)); return router;
}
