import { randomUUID } from "node:crypto";
import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { UserId } from "../../identity/domain/user.js";
import type { CommercialControlAuditEvent, CommercialStatus, UserCommercialControls, WorkspaceCommercialControls, WorkspaceCommercialUsage } from "../../repositories/commercialControlsRepository.js";
import type { PlatformOverview, PlatformUserPageRow, PlatformWorkspacePageRow } from "../../repositories/platformAdministrationRepository.js";

type Row = Record<string, unknown>;
const number = (row: Row, key: string): number => Number(row[key]);
const nullableNumber = (row: Row, key: string): number | null => row[key] === null ? null : Number(row[key]);
const workspace = (row: Row): WorkspaceCommercialControls => Object.freeze({ workspaceId:number(row,"workspace_id"),status:String(row.status) as CommercialStatus,maxCompanies:nullableNumber(row,"max_companies"),maxAssistantProfiles:nullableNumber(row,"max_assistant_profiles"),maxActiveChannels:nullableNumber(row,"max_active_channels"),version:number(row,"version"),createdAt:String(row.created_at),updatedAt:String(row.updated_at),suspendedAt:row.suspended_at === null ? null : String(row.suspended_at) });
const user = (row: Row): UserCommercialControls => Object.freeze({ userId:String(row.user_id),maxOwnedWorkspaces:nullableNumber(row,"max_owned_workspaces"),version:number(row,"version"),createdAt:String(row.created_at),updatedAt:String(row.updated_at) });

export class AsyncPlatformAdministratorRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async isActive(userId: UserId): Promise<boolean> { return (await this.database.query<Row>("SELECT 1 FROM platform_administrators WHERE user_id=? AND status='active'",[userId])).length > 0; }
}

export class AsyncCommercialControlsRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async workspace(id:number):Promise<WorkspaceCommercialControls|null>{const rows=await this.database.query<Row>("SELECT * FROM workspace_commercial_controls WHERE workspace_id=?",[id]);return rows[0]?workspace(rows[0]):null;}
  public async workspaceByPublicId(id:string):Promise<WorkspaceCommercialControls|null>{const rows=await this.database.query<Row>("SELECT c.* FROM workspace_commercial_controls c JOIN workspaces w ON w.id=c.workspace_id WHERE w.public_id=?",[id]);return rows[0]?workspace(rows[0]):null;}
  public async user(id:string):Promise<UserCommercialControls|null>{const rows=await this.database.query<Row>("SELECT * FROM user_commercial_controls WHERE user_id=?",[id]);return rows[0]?user(rows[0]):null;}
  public async ownedWorkspaceCount(userId:string):Promise<number>{return number((await this.database.query<Row>("SELECT COUNT(*) count FROM memberships WHERE user_id=? AND role='owner' AND status='active'",[userId]))[0]??{},"count");}
  public async ownedWorkspaceLimit(userId:string):Promise<number>{if((await this.database.query<Row>("SELECT 1 FROM platform_administrators WHERE user_id=? AND status='active'",[userId])).length)return Number.MAX_SAFE_INTEGER;const controls=await this.user(userId);return controls?controls.maxOwnedWorkspaces??Number.MAX_SAFE_INTEGER:0;}
  public async isWorkspaceActive(id:number):Promise<boolean>{const value=await this.workspace(id);return !value||value.status==="active";}
  public async usage(id:number):Promise<WorkspaceCommercialUsage>{const row=(await this.database.query<Row>("SELECT (SELECT COUNT(*) FROM companies WHERE workspace_id=? AND lifecycle_state!='archived') companies,(SELECT COUNT(*) FROM assistant_profiles p JOIN companies c ON c.id=p.company_id WHERE c.workspace_id=? AND p.status!='archived') assistantProfiles,(SELECT (SELECT COUNT(*) FROM web_chat_connections WHERE workspace_id=? AND status='active')+(SELECT COUNT(*) FROM whatsapp_connections WHERE workspace_id=? AND status='active')) activeChannels",[id,id,id,id]))[0]??{};return Object.freeze({companies:number(row,"companies"),assistantProfiles:number(row,"assistantProfiles"),activeChannels:number(row,"activeChannels")});}
  public async updateUser(actor:string,id:string,maxOwnedWorkspaces:number|null,expectedVersion:number,at:string):Promise<UserCommercialControls|null>{return this.database.transaction(async database=>{const repository=new AsyncCommercialControlsRepository(database),current=await repository.user(id);if(!current||current.version!==expectedVersion||(maxOwnedWorkspaces!==null&&maxOwnedWorkspaces<await repository.ownedWorkspaceCount(id)))return null;if(Number((await database.execute("UPDATE user_commercial_controls SET max_owned_workspaces=?,version=?,updated_at=? WHERE user_id=? AND version=?",[maxOwnedWorkspaces,expectedVersion+1,at,id,expectedVersion])).rowsAffected)!==1)return null;await repository.append(actor,"user",id,"allowance_updated",{maxOwnedWorkspaces:current.maxOwnedWorkspaces},{maxOwnedWorkspaces},expectedVersion+1,at);return repository.user(id);});}
  public async updateWorkspaceLimits(actor:string,id:number,input:{maxCompanies:number|null;maxAssistantProfiles:number|null;maxActiveChannels:number|null},expectedVersion:number,at:string):Promise<WorkspaceCommercialControls|null>{return this.database.transaction(async database=>{const repository=new AsyncCommercialControlsRepository(database),current=await repository.workspace(id),usage=await repository.usage(id);if(!current||current.version!==expectedVersion||(input.maxCompanies!==null&&input.maxCompanies<usage.companies)||(input.maxAssistantProfiles!==null&&input.maxAssistantProfiles<usage.assistantProfiles)||(input.maxActiveChannels!==null&&input.maxActiveChannels<usage.activeChannels))return null;if(Number((await database.execute("UPDATE workspace_commercial_controls SET max_companies=?,max_assistant_profiles=?,max_active_channels=?,version=?,updated_at=? WHERE workspace_id=? AND version=?",[input.maxCompanies,input.maxAssistantProfiles,input.maxActiveChannels,expectedVersion+1,at,id,expectedVersion])).rowsAffected)!==1)return null;await repository.append(actor,"workspace",String(id),"limits_updated",{maxCompanies:current.maxCompanies,maxAssistantProfiles:current.maxAssistantProfiles,maxActiveChannels:current.maxActiveChannels},input,expectedVersion+1,at);return repository.workspace(id);});}
  public async setWorkspaceStatus(actor:string,id:number,status:CommercialStatus,expectedVersion:number,at:string):Promise<WorkspaceCommercialControls|null>{return this.database.transaction(async database=>{const repository=new AsyncCommercialControlsRepository(database),current=await repository.workspace(id);if(!current||current.version!==expectedVersion||current.status===status)return null;if(Number((await database.execute("UPDATE workspace_commercial_controls SET status=?,suspended_at=?,version=?,updated_at=? WHERE workspace_id=? AND version=?",[status,status==="suspended"?at:null,expectedVersion+1,at,id,expectedVersion])).rowsAffected)!==1)return null;await repository.append(actor,"workspace",String(id),status==="suspended"?"suspended":"reactivated",{status:current.status},{status},expectedVersion+1,at);return repository.workspace(id);});}
  public async audit(subjectType:"user"|"workspace",subjectId:string):Promise<readonly CommercialControlAuditEvent[]>{const rows=await this.database.query<Row>("SELECT * FROM commercial_control_audit_events WHERE subject_type=? AND subject_id=? ORDER BY occurred_at DESC,id DESC",[subjectType,subjectId]);return rows.map(row=>Object.freeze({id:String(row.id),actorUserId:String(row.actor_user_id),subjectType:row.subject_type as "user"|"workspace",subjectId:String(row.subject_id),eventType:String(row.event_type),oldValue:JSON.parse(String(row.old_value_json)) as Record<string,unknown>,newValue:JSON.parse(String(row.new_value_json)) as Record<string,unknown>,version:number(row,"version"),occurredAt:String(row.occurred_at)}));}
  private async append(actor:string,subjectType:"user"|"workspace",subjectId:string,eventType:string,oldValue:Record<string,unknown>,newValue:Record<string,unknown>,version:number,at:string):Promise<void>{await this.database.execute("INSERT INTO commercial_control_audit_events(id,actor_user_id,subject_type,subject_id,event_type,old_value_json,new_value_json,version,occurred_at) VALUES(?,?,?,?,?,?,?,?,?)",[randomUUID(),actor,subjectType,subjectId,eventType,JSON.stringify(oldValue),JSON.stringify(newValue),version,at]);}
}

export class AsyncPlatformAdministrationRepository {
  public constructor(private readonly database:SqlDatabase) {}
  public async overview():Promise<PlatformOverview>{const row=(await this.database.query<Row>("SELECT (SELECT COUNT(*) FROM users) totalUsers,(SELECT COUNT(*) FROM workspaces) totalWorkspaces,(SELECT COUNT(*) FROM companies) totalCompanies,(SELECT COUNT(*) FROM assistant_profiles) totalAssistantProfiles,(SELECT COUNT(*) FROM web_chat_connections) webChatConnections,(SELECT COUNT(*) FROM whatsapp_connections) whatsAppTotal,(SELECT COUNT(*) FROM whatsapp_connections WHERE status='active') whatsAppActive,(SELECT COUNT(*) FROM whatsapp_connection_operational_states WHERE health_state='healthy') whatsAppHealthy,(SELECT COUNT(*) FROM whatsapp_connection_operational_states WHERE health_state='degraded') whatsAppDegraded"))[0]??{};return Object.freeze({totalUsers:number(row,"totalUsers"),totalWorkspaces:number(row,"totalWorkspaces"),totalCompanies:number(row,"totalCompanies"),totalAssistantProfiles:number(row,"totalAssistantProfiles"),webChatConnections:number(row,"webChatConnections"),whatsAppConnections:Object.freeze({total:number(row,"whatsAppTotal"),active:number(row,"whatsAppActive"),healthy:number(row,"whatsAppHealthy"),degraded:number(row,"whatsAppDegraded")})});}
  public async listWorkspaces(cursor:{readonly createdAt:string;readonly id:number}|null,limit:number):Promise<readonly PlatformWorkspacePageRow[]>{const rows=await this.database.query<Row>("SELECT w.id cursorId,w.public_id id,w.name,w.created_at createdAt,(SELECT COUNT(*) FROM memberships m WHERE m.workspace_id=w.id AND m.status='active') memberCount,(SELECT COUNT(*) FROM companies c WHERE c.workspace_id=w.id) companyCount,(SELECT COUNT(*) FROM assistant_profiles ap JOIN companies c ON c.id=ap.company_id WHERE c.workspace_id=w.id) assistantProfileCount,(SELECT COUNT(*) FROM web_chat_connections wc WHERE wc.workspace_id=w.id) webChatConnectionCount,(SELECT COUNT(*) FROM whatsapp_connections wa WHERE wa.workspace_id=w.id) whatsAppTotal,(SELECT COUNT(*) FROM whatsapp_connections wa WHERE wa.workspace_id=w.id AND wa.status='active') whatsAppActive,(SELECT COUNT(*) FROM whatsapp_connections wa JOIN whatsapp_connection_operational_states ws ON ws.whatsapp_connection_id=wa.id WHERE wa.workspace_id=w.id AND ws.health_state='healthy') whatsAppHealthy,(SELECT COUNT(*) FROM whatsapp_connections wa JOIN whatsapp_connection_operational_states ws ON ws.whatsapp_connection_id=wa.id WHERE wa.workspace_id=w.id AND ws.health_state='degraded') whatsAppDegraded,NULL latestActivityAt FROM workspaces w WHERE (? IS NULL OR w.created_at<? OR (w.created_at=? AND w.id<?)) ORDER BY w.created_at DESC,w.id DESC LIMIT ?",[cursor?.createdAt??null,cursor?.createdAt??null,cursor?.createdAt??null,cursor?.id??null,limit+1]);return rows.map(row=>Object.freeze({cursorId:number(row,"cursorId"),summary:Object.freeze({id:String(row.id),name:String(row.name),createdAt:String(row.createdAt),memberCount:number(row,"memberCount"),companyCount:number(row,"companyCount"),assistantProfileCount:number(row,"assistantProfileCount"),webChatConnectionCount:number(row,"webChatConnectionCount"),whatsApp:Object.freeze({total:number(row,"whatsAppTotal"),active:number(row,"whatsAppActive"),healthy:number(row,"whatsAppHealthy"),degraded:number(row,"whatsAppDegraded")}),latestActivityAt:row.latestActivityAt===null?null:String(row.latestActivityAt)})}));}
  public async listUsers(cursor:{readonly createdAt:string;readonly id:number}|null,limit:number):Promise<readonly PlatformUserPageRow[]>{const rows=await this.database.query<Row>("SELECT u.rowid cursorId,u.id id,i.email email,u.created_at createdAt,i.email_verified emailVerified,(SELECT COUNT(*) FROM memberships m WHERE m.user_id=u.id AND m.status='active') activeWorkspaceMembershipCount FROM users u JOIN authentication_identities i ON i.user_id=u.id WHERE (? IS NULL OR u.created_at<? OR (u.created_at=? AND u.rowid<?)) ORDER BY u.created_at DESC,u.rowid DESC LIMIT ?",[cursor?.createdAt??null,cursor?.createdAt??null,cursor?.createdAt??null,cursor?.id??null,limit+1]);return rows.map(row=>{const count=number(row,"activeWorkspaceMembershipCount");return Object.freeze({cursorId:number(row,"cursorId"),summary:Object.freeze({id:String(row.id),email:String(row.email),createdAt:String(row.createdAt),emailVerified:number(row,"emailVerified")===1,activeWorkspaceMembershipCount:count,hasActiveWorkspaceMembership:count>0})});});}
}
