import { createHash, randomUUID } from "node:crypto";
import type { ProviderAdapterRegistryPort } from "../../integrations/application/providerAdapterRegistry.js";
import { googleCalendarEventId } from "../../integrations/providers/googleCalendarEventsProvider.js";
import type { BookingRepositoryPort } from "../application/bookingPorts.js";
import type { ExternalWriteOperationRepositoryPort } from "../application/externalCalendarPorts.js";
import type { SchedulingRepositoryPort } from "../application/ports.js";
import { externalWriteOperationId, externalWriteRequestFingerprint, reconstructExternalWriteOperation, type ExternalWriteOperation } from "../domain/externalCalendar.js";
import type { SchedulingBooking } from "../domain/scheduling.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { ExternalCalendarBindingService, ReadyExternalCalendarBinding } from "./externalCalendarBindingService.js";
import type { SchedulingService } from "./schedulingService.js";

export type ExternalCreateOutcome = { readonly kind: "created" | "replayed"; readonly booking: SchedulingBooking } | { readonly kind: "pending_recovery" } | { readonly kind: "conflict" | "unavailable" | "validation_error" };

/** Coordinates one durable CREATE intent; provider adapters never mutate local booking state. */
export class ExternalBookingCreateService {
  public constructor(private readonly scheduling: SchedulingService, private readonly schedulingRepository: SchedulingRepositoryPort, private readonly bindings: ExternalCalendarBindingService, private readonly operations: ExternalWriteOperationRepositoryPort, private readonly bookings: BookingRepositoryPort, private readonly registry: ProviderAdapterRegistryPort, private readonly clock: { now(): string }) {}
  public async create(context: WorkspaceContext, companyId: number, input: { readonly resourceId: string; readonly serviceId: string; readonly startAt: string; readonly reference: string; readonly idempotencyKey: string; readonly workerId: string }): Promise<ExternalCreateOutcome> {
    const reference = normalizeReference(input.reference); if (reference === null) return { kind: "validation_error" };
    const service = await this.schedulingRepository.findService(context, companyId, input.serviceId), resource = await this.schedulingRepository.findResource(context, companyId, input.resourceId); if (!service || !resource || service.resourceId !== resource.id || !resource.active || !service.active) return { kind: "validation_error" };
    const ready = await this.bindings.resolveReadyBindingForResource(context, companyId, resource.id); if (ready.kind !== "ready") return ready.kind === "unavailable" ? { kind: "unavailable" } : { kind: "validation_error" };
    const now = this.clock.now(), reservationExpiresAt = new Date(Date.parse(now) + 10 * 60_000).toISOString(), fingerprint = externalWriteRequestFingerprint({ operation: "create", bindingId: ready.binding.bindingId, serviceId: service.id, startAt: input.startAt, reference }), existing = await this.operations.findOperationByIdempotency(context, companyId, ready.binding.bindingId, "create", input.idempotencyKey);
    if (existing) return existing.requestFingerprint === fingerprint ? this.run(context, companyId, existing, ready.binding, resource.timezone, input.workerId) : { kind: "conflict" };
    let hold; try { hold = await this.scheduling.hold(context, companyId, { serviceId: service.id, startAt: input.startAt, expiresAt: reservationExpiresAt, idempotencyKey: `external-create:${createHash("sha256").update(`${ready.binding.bindingId}\u0000${input.idempotencyKey}`).digest("hex")}` }); } catch { return { kind: "conflict" }; }
    const id = externalWriteOperationId(`ewo_${randomUUID().replaceAll("-", "")}`), intent = reconstructExternalWriteOperation({ id, workspaceId: context.workspaceId, companyId, bindingId: ready.binding.bindingId, operation: "create", idempotencyKey: input.idempotencyKey, requestFingerprint: fingerprint, state: "pending", providerRequestCorrelationId: `create:${id}`, requestedBookingReference: reference, bookingId: null, sourceBookingId: null, holdId: hold.id, reservationExpiresAt, externalEventId: googleCalendarEventId(id), expectedRemoteVersion: null, leaseToken: null, leaseOwner: null, leaseAcquiredAt: null, leaseExpiresAt: null, attemptCount: 0, lastAttemptAt: null, safeFailureCode: null, completedAt: null, createdAt: now, updatedAt: now });
    const created = await this.operations.create(context, intent); if (created.kind === "divergent") return { kind: "conflict" }; if (created.kind === "not_found") return { kind: "validation_error" }; return this.run(context, companyId, created.operation, ready.binding, resource.timezone, input.workerId);
  }
  private async run(context: WorkspaceContext, companyId: number, operation: ExternalWriteOperation, binding: ReadyExternalCalendarBinding, timeZone: string, workerId: string): Promise<ExternalCreateOutcome> {
    if (operation.state === "succeeded" && operation.bookingId) { const booking = await this.bookings.findBooking(context, companyId, operation.bookingId); return booking ? { kind: "replayed", booking } : { kind: "conflict" }; }
    if (operation.state === "conflict" || operation.state === "failed") return { kind: "conflict" };
    const now = this.clock.now(), leaseExpiresAt = new Date(Date.parse(now) + 60_000).toISOString();
    if (operation.state === "pending") { const claim = await this.operations.claimPending(context, companyId, operation.id, workerId, now, leaseExpiresAt); if (claim.kind !== "claimed") return claim.kind === "not_found" ? { kind: "validation_error" } : { kind: "pending_recovery" }; return this.dispatch(context, companyId, claim.operation, binding, timeZone, workerId); }
    const claim = await this.operations.claimRecoverable(context, companyId, operation.id, workerId, now, leaseExpiresAt); if (claim.kind !== "claimed") return { kind: "pending_recovery" }; return this.reconcile(context, companyId, claim.operation, binding, timeZone);
  }
  private async dispatch(context: WorkspaceContext, companyId: number, operation: ExternalWriteOperation, binding: ReadyExternalCalendarBinding, timeZone: string, _workerId: string): Promise<ExternalCreateOutcome> {
    const provider = this.registry.resolveCalendarEvents(binding.provider, binding.kind); if (!provider || !operation.holdId || !operation.leaseToken) return this.fail(context, companyId, operation, "validation_error"); const hold = await this.schedulingRepository.findHold(context, companyId, operation.holdId); if (!hold) return this.fail(context, companyId, operation, "validation_error"); const result = await provider.insertEvent({ context, companyId, connectionId: binding.connectionId as never, binding: { id: binding.bindingId, workspaceId: context.workspaceId, companyId, resourceId: binding.resourceId as never, integrationConnectionId: binding.connectionId as never, externalCalendarId: binding.externalCalendarId, createdAt: operation.createdAt, updatedAt: operation.updatedAt }, externalEventId: operation.externalEventId, operationId: operation.id, startAt: hold.startAt, endAt: hold.endAt, timeZone, signal: new AbortController().signal });
    if (result.kind === "success") return this.finalize(context, companyId, operation, result.event, hold.startAt, hold.endAt, timeZone);
    if (result.kind === "conflict" || result.kind === "timeout" || result.kind === "unavailable" || result.kind === "rate_limited") { await this.operations.markUncertain(context, companyId, operation.id, operation.leaseToken, result.kind === "timeout" ? "timeout" : "unavailable", this.clock.now()); const claimed = await this.operations.claimRecoverable(context, companyId, operation.id, "reconcile", this.clock.now(), new Date(Date.parse(this.clock.now()) + 60_000).toISOString()); return claimed.kind === "claimed" ? this.reconcile(context, companyId, claimed.operation, binding, timeZone) : { kind: "pending_recovery" }; }
    return this.fail(context, companyId, operation, result.kind === "forbidden" ? "forbidden" : result.kind === "unauthorized" ? "unauthorized" : "validation_error");
  }
  private async reconcile(context: WorkspaceContext, companyId: number, operation: ExternalWriteOperation, binding: ReadyExternalCalendarBinding, timeZone: string): Promise<ExternalCreateOutcome> {
    const provider = this.registry.resolveCalendarEvents(binding.provider, binding.kind); if (!provider || !operation.leaseToken || !operation.holdId) return { kind: "pending_recovery" }; const hold = await this.schedulingRepository.findHold(context, companyId, operation.holdId); if (!hold) return this.fail(context, companyId, operation, "validation_error"); const result = await provider.getEvent({ context, companyId, connectionId: binding.connectionId as never, binding: { id: binding.bindingId, workspaceId: context.workspaceId, companyId, resourceId: binding.resourceId as never, integrationConnectionId: binding.connectionId as never, externalCalendarId: binding.externalCalendarId, createdAt: operation.createdAt, updatedAt: operation.updatedAt }, externalEventId: operation.externalEventId, signal: new AbortController().signal });
    if (result.kind === "success") return result.event.createOperationId === operation.id && result.event.startAt === hold.startAt && result.event.endAt === hold.endAt && result.event.timeZone === timeZone ? this.finalize(context, companyId, operation, result.event, hold.startAt, hold.endAt, timeZone) : this.conflict(context, companyId, operation);
    if (result.kind === "not_found") { const retry = await this.operations.markReconciliationSafeToRetry(context, companyId, operation.id, operation.leaseToken, this.clock.now()); return retry.kind === "applied" ? { kind: "pending_recovery" } : { kind: "conflict" }; }
    if (result.kind === "unauthorized" || result.kind === "forbidden" || result.kind === "validation_error" || result.kind === "invalid_response") return this.fail(context, companyId, operation, result.kind === "unauthorized" ? "unauthorized" : result.kind === "forbidden" ? "forbidden" : "validation_error");
    return { kind: "pending_recovery" };
  }
  private async finalize(context: WorkspaceContext, companyId: number, operation: ExternalWriteOperation, event: { readonly externalEventId: string; readonly remoteVersion: string | null; readonly startAt: string; readonly endAt: string; readonly timeZone: string; readonly createOperationId: string | null }, startAt: string, endAt: string, timeZone: string): Promise<ExternalCreateOutcome> { if (!operation.leaseToken || event.externalEventId !== operation.externalEventId || !event.remoteVersion || event.createOperationId !== operation.id || event.startAt !== startAt || event.endAt !== endAt || event.timeZone !== timeZone) return this.conflict(context, companyId, operation); const result = await this.operations.finalizeCreate(context, companyId, operation.id, operation.leaseToken, event.remoteVersion, this.clock.now()); return result.kind === "applied" ? { kind: "created", booking: result.booking } : result.kind === "replayed" ? { kind: "replayed", booking: result.booking } : { kind: "conflict" }; }
  private async conflict(context: WorkspaceContext, companyId: number, operation: ExternalWriteOperation): Promise<ExternalCreateOutcome> { if (operation.leaseToken) await this.operations.markConflict(context, companyId, operation.id, operation.leaseToken, this.clock.now()); return { kind: "conflict" }; }
  private async fail(context: WorkspaceContext, companyId: number, operation: ExternalWriteOperation, code: "unauthorized" | "forbidden" | "validation_error"): Promise<ExternalCreateOutcome> { if (operation.leaseToken) await this.operations.markFailed(context, companyId, operation.id, operation.leaseToken, code, this.clock.now()); if (operation.holdId) await this.schedulingRepository.releaseHold(context, companyId, operation.holdId, this.clock.now()); return code === "validation_error" ? { kind: "validation_error" } : { kind: "unavailable" }; }
}
function normalizeReference(value: string): string | null { const normalized = typeof value === "string" ? value.trim() : ""; return normalized && normalized.length <= 200 ? normalized : null; }
