import { randomUUID } from "node:crypto";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { ExternalBusySourcePort, SchedulingRepositoryPort } from "../application/ports.js";
import { reconstructBooking, reconstructBusyInterval, reconstructException, reconstructHold, reconstructLocation, reconstructResource, reconstructService, reconstructWorkingWindow, SchedulingError, type SchedulingAvailabilityException, type SchedulingBooking, type SchedulingBusyInterval, type SchedulingHold, type SchedulingLocation, type SchedulingResource, type SchedulingService as ServiceValue, type SchedulingSlot, validateDate, validateInstant, validateTime, validateTimezone } from "../domain/scheduling.js";

export class SchedulingConflictError extends SchedulingError {}
export class SchedulingNotFoundError extends SchedulingError {}
export class SchedulingIdempotencyError extends SchedulingError {}
export class SchedulingService {
  public constructor(private readonly repository: SchedulingRepositoryPort, private readonly clock: { now(): string }, private readonly externalBusySource?: ExternalBusySourcePort) {}
  public async createLocation(context: WorkspaceContext, companyId: number, input: { readonly name: string; readonly address?: string; readonly timezone: string }): Promise<SchedulingLocation> { const now = this.now(); return this.repository.createLocation(context, reconstructLocation({ id: id("slc") as SchedulingLocation["id"], workspaceId: context.workspaceId, companyId, name: text(input.name, 200), address: input.address?.trim() || null, timezone: validateTimezone(input.timezone), active: true, createdAt: now, updatedAt: now })).then(requiredResult); }
  public async createResource(context: WorkspaceContext, companyId: number, input: { readonly name: string; readonly timezone: string; readonly capacity?: number; readonly locationId?: string }): Promise<SchedulingResource> { const now = this.now(); return this.repository.createResource(context, reconstructResource({ id: id("src") as SchedulingResource["id"], workspaceId: context.workspaceId, companyId, locationId: input.locationId === undefined ? null : input.locationId as SchedulingResource["locationId"], name: text(input.name, 200), timezone: validateTimezone(input.timezone), capacity: input.capacity ?? 1, active: true, createdAt: now, updatedAt: now })).then(requiredResult); }
  public async createService(context: WorkspaceContext, companyId: number, input: { readonly resourceId: string; readonly name: string; readonly durationMinutes: number; readonly bufferBeforeMinutes?: number; readonly bufferAfterMinutes?: number; readonly slotGranularityMinutes?: number; readonly minimumLeadMinutes?: number; readonly maximumHorizonDays?: number }): Promise<ServiceValue> { const resource = await this.repository.findResource(context, companyId, input.resourceId); if (!resource?.active) missing(); const now = this.now(); return this.repository.createService(context, reconstructService({ id: id("ssv") as ServiceValue["id"], workspaceId: context.workspaceId, companyId, resourceId: resource.id, name: text(input.name, 200), durationMinutes: input.durationMinutes, bufferBeforeMinutes: input.bufferBeforeMinutes ?? 0, bufferAfterMinutes: input.bufferAfterMinutes ?? 0, slotGranularityMinutes: input.slotGranularityMinutes ?? 15, minimumLeadMinutes: input.minimumLeadMinutes ?? 0, maximumHorizonDays: input.maximumHorizonDays ?? 30, active: true, createdAt: now, updatedAt: now })).then(requiredResult); }
  public async addWorkingWindow(context: WorkspaceContext, companyId: number, input: { readonly resourceId: string; readonly weekday: number; readonly startTime: string; readonly endTime: string }): Promise<void> { if (!await this.repository.findResource(context, companyId, input.resourceId)) missing(); const result = await this.repository.addWorkingWindow(context, reconstructWorkingWindow({ id: randomUUID().replaceAll("-", ""), resourceId: input.resourceId as SchedulingResource["id"], weekday: input.weekday, startTime: validateTime(input.startTime), endTime: validateTime(input.endTime) })); if (!result) conflict("Scheduling working window already exists."); }
  public async addException(context: WorkspaceContext, companyId: number, input: { readonly resourceId: string; readonly localDate: string; readonly kind: "closed" | "open"; readonly startTime?: string; readonly endTime?: string }): Promise<void> { if (!await this.repository.findResource(context, companyId, input.resourceId)) missing(); const result = await this.repository.addException(context, reconstructException({ id: randomUUID().replaceAll("-", ""), resourceId: input.resourceId as SchedulingResource["id"], localDate: validateDate(input.localDate), kind: input.kind, startTime: input.startTime ?? null, endTime: input.endTime ?? null })); if (!result) conflict("Scheduling exception already exists."); }
  public async listSlots(context: WorkspaceContext, companyId: number, serviceId: string, input: { readonly fromLocalDate: string; readonly days?: number }): Promise<readonly SchedulingSlot[]> { const service = await this.service(context, companyId, serviceId), resource = await this.resource(context, companyId, service.resourceId); const from = validateDate(input.fromLocalDate), days = input.days ?? 7; if (!Number.isInteger(days) || days < 1 || days > 31) throw new SchedulingError("Scheduling slot range is invalid."); const result: SchedulingSlot[] = []; for (let offset = 0; offset < days; offset += 1) { const localDate = addDays(from, offset), weekday = new Date(`${localDate}T00:00:00.000Z`).getUTCDay(), windows = await this.effectiveWindows(context, companyId, resource.id, weekday, localDate); for (const window of windows) for (let minute = minutes(window.startTime); minute + service.durationMinutes <= minutes(window.endTime); minute += service.slotGranularityMinutes) for (const startAt of localToUtc(localDate, time(minute), resource.timezone)) { const endAt = new Date(Date.parse(startAt) + service.durationMinutes * 60_000).toISOString(); if (await this.available(context, companyId, service, resource, startAt, endAt)) result.push(Object.freeze({ serviceId: service.id, resourceId: resource.id, startAt, endAt, localDate, localStartTime: time(minute) })); } } return Object.freeze(result.sort((a, b) => a.startAt.localeCompare(b.startAt))); }
  public async hold(context: WorkspaceContext, companyId: number, input: { readonly serviceId: string; readonly startAt: string; readonly expiresAt: string; readonly idempotencyKey: string }): Promise<SchedulingHold> { const service = await this.service(context, companyId, input.serviceId), resource = await this.resource(context, companyId, service.resourceId), now = this.now(), startAt = validateInstant(input.startAt), endAt = new Date(Date.parse(startAt) + service.durationMinutes * 60_000).toISOString(), expiresAt = validateInstant(input.expiresAt); if (Date.parse(expiresAt) <= Date.parse(now) || Date.parse(expiresAt) > Date.parse(now) + 30 * 60_000) throw new SchedulingError("Scheduling hold expiration is invalid."); if (!await this.available(context, companyId, service, resource, startAt, endAt)) conflict("Scheduling interval is unavailable."); const value = reconstructHold({ id: id("shd") as SchedulingHold["id"], workspaceId: context.workspaceId, companyId, serviceId: service.id, idempotencyKey: text(input.idempotencyKey, 200), startAt, endAt, occupiedStartAt: shift(startAt, -service.bufferBeforeMinutes), occupiedEndAt: shift(endAt, service.bufferAfterMinutes), expiresAt, state: "active", createdAt: now, releasedAt: null }); const result = await this.repository.createHold(context, value, resource.capacity, now); if (result.kind === "same" || result.kind === "created") return result.hold!; if (result.kind === "divergent") throw new SchedulingIdempotencyError("Scheduling idempotency key has a different payload."); conflict("Scheduling interval is unavailable."); }
  public async book(context: WorkspaceContext, companyId: number, holdId: string, reference: string): Promise<SchedulingBooking> { const hold = await this.repository.findHold(context, companyId, holdId), now = this.now(); if (!hold || hold.state !== "active" || Date.parse(hold.expiresAt) <= Date.parse(now)) conflict("Scheduling hold is unavailable."); const service = await this.service(context, companyId, hold.serviceId), resource = await this.resource(context, companyId, service.resourceId); const booking = reconstructBooking({ id: id("sbk") as SchedulingBooking["id"], workspaceId: context.workspaceId, companyId, serviceId: hold.serviceId, holdId: hold.id, rescheduledFromBookingId: null, reference: text(reference, 100), startAt: hold.startAt, endAt: hold.endAt, occupiedStartAt: hold.occupiedStartAt, occupiedEndAt: hold.occupiedEndAt, state: "confirmed", createdAt: now, cancelledAt: null }); return (await this.repository.confirmHold(context, companyId, holdId, booking, resource.capacity, now)) ?? conflict("Scheduling hold is unavailable."); }
  public async releaseHold(context: WorkspaceContext, companyId: number, holdId: string): Promise<void> { if (!await this.repository.releaseHold(context, companyId, holdId, this.now())) missing(); }
  public async cancelBooking(context: WorkspaceContext, companyId: number, bookingId: string): Promise<SchedulingBooking> { return (await this.repository.cancelBooking(context, companyId, bookingId, this.now())) ?? missing(); }
  public async refreshExternalBusy(context: WorkspaceContext, companyId: number, resourceId: string, startAt: string, endAt: string): Promise<void> { if (!this.externalBusySource || !await this.externalBusySource.isReady()) return; const resource = await this.resource(context, companyId, resourceId); for (const item of await this.externalBusySource.listBusyIntervals({ resourceId, startAt, endAt })) { const value: SchedulingBusyInterval = reconstructBusyInterval({ ...item, id: randomUUID().replaceAll("-", ""), workspaceId: context.workspaceId, companyId, resourceId: resource.id, startAt: validateInstant(item.startAt), endAt: validateInstant(item.endAt), createdAt: this.now() }); await this.repository.upsertBusyInterval(context, value); } }
  private async available(context: WorkspaceContext, companyId: number, service: ServiceValue, resource: SchedulingResource, startAt: string, endAt: string): Promise<boolean> { const now = this.now(), local = localParts(startAt, resource.timezone), endLocal = localParts(endAt, resource.timezone), occupiedStartAt = shift(startAt, -service.bufferBeforeMinutes), occupiedEndAt = shift(endAt, service.bufferAfterMinutes), occupiedStartLocal = localParts(occupiedStartAt, resource.timezone), occupiedEndLocal = localParts(occupiedEndAt, resource.timezone); if (Date.parse(startAt) < Date.parse(now) + service.minimumLeadMinutes * 60_000 || Date.parse(startAt) > Date.parse(now) + service.maximumHorizonDays * 86_400_000 || local.date !== endLocal.date || local.time !== time(minutes(local.time)) || occupiedStartLocal.date !== occupiedEndLocal.date) return false; if (!(await this.effectiveWindows(context, companyId, resource.id, occupiedStartLocal.weekday, occupiedStartLocal.date)).some((window) => window.startTime <= occupiedStartLocal.time && window.endTime >= occupiedEndLocal.time)) return false; const rows = await this.repository.listOccupancy(context, companyId, resource.id, occupiedStartAt, occupiedEndAt, now); return capacityAvailable(rows, occupiedStartAt, occupiedEndAt, resource.capacity); }
  private async effectiveWindows(context: WorkspaceContext, companyId: number, resourceId: string, weekday: number, localDate: string): Promise<readonly { readonly startTime: string; readonly endTime: string }[]> { const exceptions = await this.repository.listExceptions(context, companyId, resourceId, localDate), closed = exceptions.filter((item) => item.kind === "closed"), opened = exceptions.filter((item) => item.kind === "open"), openedWindows = opened.filter((item) => item.startTime !== null).map((item) => ({ startTime: item.startTime!, endTime: item.endTime! })); if (closed.some((item) => item.startTime === null)) return Object.freeze(openedWindows); const base = (await this.repository.listWorkingWindows(context, companyId, resourceId, weekday)).map((item) => ({ startTime: item.startTime, endTime: item.endTime })); return Object.freeze([...subtractClosedWindows(base, closed), ...openedWindows]); }
  private async service(context: WorkspaceContext, companyId: number, serviceId: string): Promise<ServiceValue> { const value = await this.repository.findService(context, companyId, serviceId); if (!value?.active) missing(); return value; }
  private async resource(context: WorkspaceContext, companyId: number, resourceId: string): Promise<SchedulingResource> { const value = await this.repository.findResource(context, companyId, resourceId); if (!value?.active) missing(); return value; }
  private now(): string { return validateInstant(this.clock.now()); }
}
function capacityAvailable(rows: readonly { readonly startAt: string; readonly endAt: string; readonly units: number }[], startAt: string, endAt: string, capacity: number): boolean { const events = [{ at: startAt, delta: 0 }, { at: endAt, delta: 0 }, ...rows.flatMap((row) => [{ at: row.startAt, delta: row.units }, { at: row.endAt, delta: -row.units }])].sort((a, b) => a.at.localeCompare(b.at) || a.delta - b.delta); let used = 0; for (const event of events) { used += event.delta; if (event.at >= startAt && event.at < endAt && used >= capacity) return false; } return true; }
function subtractClosedWindows(windows: readonly { readonly startTime: string; readonly endTime: string }[], closed: readonly SchedulingAvailabilityException[]): readonly { readonly startTime: string; readonly endTime: string }[] { let result = [...windows]; for (const exception of closed) { if (exception.startTime === null) continue; const start = exception.startTime, end = exception.endTime!; result = result.flatMap((window) => { if (end <= window.startTime || start >= window.endTime) return [window]; const parts: { startTime: string; endTime: string }[] = []; if (start > window.startTime) parts.push({ startTime: window.startTime, endTime: start }); if (end < window.endTime) parts.push({ startTime: end, endTime: window.endTime }); return parts; }); } return result; }
function localToUtc(date: string, localTime: string, timezone: string): readonly string[] { const target = `${date}T${localTime}`, nominal = Date.parse(`${target}:00.000Z`), offsets = new Set<number>(); for (let hour = -16; hour <= 16; hour += 1) offsets.add(Date.parse(localParts(new Date(nominal + hour * 3_600_000).toISOString(), timezone).date + "T" + localParts(new Date(nominal + hour * 3_600_000).toISOString(), timezone).time + ":00.000Z") - (nominal + hour * 3_600_000)); return [...offsets].map((offset) => new Date(nominal - offset).toISOString()).filter((candidate) => { const local = localParts(candidate, timezone); return `${local.date}T${local.time}` === target; }).sort(); }
function localParts(value: string, timezone: string): { readonly date: string; readonly weekday: number; readonly time: string } { const parts = new Intl.DateTimeFormat("en-US", { timeZone: timezone, weekday: "short", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value)); const get = (part: Intl.DateTimeFormatPartTypes): string => parts.find((item) => item.type === part)?.value ?? ""; const day: Record<string, number> = { Sun: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6 }; return { date: `${get("year")}-${get("month")}-${get("day")}`, weekday: day[get("weekday")] ?? -1, time: `${get("hour")}:${get("minute")}` }; }
function addDays(date: string, days: number): string { return new Date(Date.parse(`${date}T00:00:00.000Z`) + days * 86_400_000).toISOString().slice(0, 10); }
function shift(value: string, minutes: number): string { return new Date(Date.parse(value) + minutes * 60_000).toISOString(); }
function minutes(value: string): number { return Number(value.slice(0, 2)) * 60 + Number(value.slice(3)); }
function time(value: number): string { return `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`; }
function id(prefix: string): string { return `${prefix}_${randomUUID().replaceAll("-", "")}`; }
function text(value: string, maximum: number): string { if (typeof value !== "string" || !value.trim() || value.length > maximum) throw new SchedulingError("Scheduling text is invalid."); return value.trim(); }
function missing(): never { throw new SchedulingNotFoundError("Scheduling resource was not found."); }
function conflict(message: string): never { throw new SchedulingConflictError(message); }
function requiredResult<T>(value: T | null): T { if (value === null) missing(); return value; }
