import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { CompanyDomainRepositoryPort } from "../../company/application/ports.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { WebChatConnectionRepositoryPort } from "../../webChat/application/ports.js";
import type { PilotReadinessService } from "../../onboarding/services/pilotReadinessService.js";
import { projectActivation, type ActivationProjection, type ActivationStageFact } from "../domain/activation.js";
import type { ActivationVerificationAttemptRepositoryPort } from "../application/ports.js";

export class ActivationNotFoundError extends Error {}
export class ActivationUnavailableError extends Error {}
export class ActivationVerificationUnavailableError extends Error {}
export interface ActivationVerificationStart { readonly token:string; readonly expiresAt:string; }

export class ActivationService {
  public constructor(private readonly companies:CompanyDomainRepositoryPort, private readonly webChat:WebChatConnectionRepositoryPort, private readonly pilot:PilotReadinessService, private readonly attempts:ActivationVerificationAttemptRepositoryPort, private readonly clock:{now():string}, private readonly lifetimeMilliseconds=15*60*1000) {}
  public async projection(context:WorkspaceContext, companyId:number):Promise<ActivationProjection> { try { if(!this.companies.findById(context,companyId as import("../../company/domain/company.js").CompanyId))throw new ActivationNotFoundError();const pilot=await this.pilot.get(context,companyId),check=(id:"company"|"published_knowledge"|"default_assistant"|"web_chat")=>pilot.checks.find(value=>value.id===id),fromCheck=(id:"company"|"published_knowledge"|"default_assistant"|"web_chat"):ActivationStageFact=>{const value=check(id);return value?{state:value.status==="complete"?"complete":value.status==="blocked"?"blocked":value.status==="unavailable"?"unavailable":"incomplete",owner:value.owner,reasonCode:value.reasonCode as ActivationStageFact["reasonCode"]}:{state:"unavailable",owner:"platform",reasonCode:null};},connection=this.webChat.listByCompany(context,companyId).find(value=>value.status==="active"),latest=connection?this.attempts.findLatest(context,companyId,connection.id):null,verification:ActivationStageFact=!connection?{state:"incomplete",owner:"customer",reasonCode:"verification_required"}:this.attempts.hasSucceeded(context,companyId,connection.id)?{state:"complete",owner:null,reasonCode:null}:latest?.status==="pending"?{state:"incomplete",owner:"customer",reasonCode:"verification_pending"}:{state:"incomplete",owner:"customer",reasonCode:latest?"verification_failed":"verification_required"};return projectActivation({company:fromCheck("company"),knowledge:fromCheck("published_knowledge"),assistant:fromCheck("default_assistant"),web_chat:fromCheck("web_chat"),verification,pilot_ready:pilot.overall==="pilot_ready"?{state:"complete",owner:null,reasonCode:null}:{state:"incomplete",owner:null,reasonCode:"pilot_not_ready"},human_ops:{state:"complete",owner:null,reasonCode:null}},this.clock.now()); } catch(error:unknown) { if(error instanceof ActivationNotFoundError)throw error;throw new ActivationUnavailableError(); } }
  public startVerification(context:WorkspaceContext, companyId:number):ActivationVerificationStart { const connection=this.webChat.listByCompany(context,companyId).find(value=>value.status==="active");if(!connection)throw new ActivationVerificationUnavailableError();const token=randomBytes(32).toString("base64url"),now=this.clock.now(),expiresAt=new Date(Date.parse(now)+this.lifetimeMilliseconds).toISOString();this.attempts.create(context,{id:`ava_${randomUUID().replaceAll("-","")}`,workspaceId:context.workspaceId,companyId,webChatConnectionId:connection.id,tokenDigest:digest(token),status:"pending",createdAt:now,expiresAt,claimedAt:null,webChatSessionId:null,conversationId:null,inboundMessageId:null,executionRecordId:null,outcomeRef:null,completedAt:null,failureCode:null});return Object.freeze({token,expiresAt}); }
  public canClaimPublicVerification(connectionPublicId:unknown, token:unknown):boolean { return this.claimable(connectionPublicId,token)!==null; }
  public claimPublicVerification(connectionPublicId:unknown, token:unknown, session: { readonly sessionId:string; readonly conversationId:string }):boolean { const attempt=this.claimable(connectionPublicId,token);return attempt!==null&&this.attempts.claim(attempt.id,session.sessionId,session.conversationId,this.clock.now())!==null; }
  public succeedForTurn(session:{readonly sessionId:string;readonly conversationId:string}, inboundMessageId:string, executionRecordId:string, outcome:"answered"|"safe_fallback"):void { this.attempts.succeedForTurn(session.sessionId,session.conversationId,inboundMessageId,executionRecordId,outcome,this.clock.now()); }
  public failForSession(session:{readonly sessionId:string;readonly conversationId:string}):void { this.attempts.failForSession(session.sessionId,session.conversationId,this.clock.now()); }
  private claimable(connectionPublicId:unknown, token:unknown):import("../application/ports.js").ActivationVerificationAttempt|null { if(typeof connectionPublicId!=="string"||typeof token!=="string"||!/^[A-Za-z0-9_-]{43}$/.test(token))return null;const attempt=this.attempts.findClaimableByTokenDigest(digest(token));if(!attempt)return null;const now=this.clock.now();if(Date.parse(attempt.expiresAt)<=Date.parse(now)){this.attempts.expire(attempt.id,now);return null;}const connection=this.webChat.findActiveById(attempt.webChatConnectionId as import("../../webChat/domain/webChatConnection.js").WebChatConnectionId);return connection?.publicId===connectionPublicId?attempt:null; }
}
function digest(value:string):string{return createHash("sha256").update(value).digest("hex");}
