// @vitest-environment jsdom
import { cleanup, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import App from "../App";
import { I18nProvider } from "../i18n/I18nContext";
import { RouterProvider } from "../routing/RouterProvider";
import { AuthenticationProvider } from "../state/AuthenticationContext";
import { ThemeProvider } from "../design-system/theme";

function json(value:unknown,status=200):Response{return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
function renderApp():void{render(<ThemeProvider><I18nProvider><RouterProvider><AuthenticationProvider><App/></AuthenticationProvider></RouterProvider></I18nProvider></ThemeProvider>);}
afterEach(()=>{cleanup();vi.unstubAllGlobals();window.history.replaceState({},"","/");});
test("renders a separate admin shell and safe overview for a platform admin",async()=>{window.history.replaceState({},"","/admin");vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(json({status:"authenticated",identity:{userId:"admin",email:"admin@example.test",locale:"en",status:"active",isPlatformAdmin:true,idleExpiresAt:"2026-01-01",absoluteExpiresAt:"2026-01-01"},csrfToken:"csrf",csrfGeneration:1}));if(url.endsWith("/admin/overview"))return Promise.resolve(json({data:{totalUsers:2,totalWorkspaces:1,totalCompanies:1,totalAssistantProfiles:1,webChatConnections:1,whatsAppConnections:{total:1,active:1,healthy:1,degraded:0}}}));return Promise.resolve(json({},404));}));renderApp();await screen.findByRole("heading",{name:"Administración de Atlas"});expect(document.querySelector(".admin-shell")).toBeTruthy();expect(document.querySelector(".app-shell")).toBeNull();expect(screen.getByText("Usuarios registrados")).toBeTruthy();});
test("does not render admin data for an authenticated non-admin",async()=>{window.history.replaceState({},"","/admin");vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(json({status:"authenticated",identity:{userId:"customer",email:"customer@example.test",locale:"en",status:"active",isPlatformAdmin:false,idleExpiresAt:"2026-01-01",absoluteExpiresAt:"2026-01-01"},csrfToken:"csrf",csrfGeneration:1}));if(url.endsWith("/workspaces")&&!url.includes("selected"))return Promise.resolve(json([]));return Promise.resolve(json({},404));}));renderApp();await waitFor(()=>expect(window.location.pathname).toBe("/dashboard"));expect(screen.queryByText("Administración de Atlas")).toBeNull();expect(vi.mocked(fetch).mock.calls.some(([input])=>String(input).includes("/admin/overview"))).toBe(false);});
test("redirects an unauthenticated admin route to the shared sign-in screen",async()=>{window.history.replaceState({},"","/admin");vi.stubGlobal("fetch",vi.fn(()=>Promise.resolve(json({},401))));renderApp();await screen.findByRole("heading",{name:"Welcome back"});expect(window.location.pathname).toBe("/sign-in");});
test("redirects an admin session from the shared sign-in route to admin",async()=>{window.history.replaceState({},"","/sign-in");vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(json({status:"authenticated",identity:{userId:"admin",email:"admin@example.test",locale:"en",status:"active",isPlatformAdmin:true,idleExpiresAt:"2026-01-01",absoluteExpiresAt:"2026-01-01"},csrfToken:"csrf",csrfGeneration:1}));if(url.endsWith("/admin/overview"))return Promise.resolve(json({data:{totalUsers:0,totalWorkspaces:0,totalCompanies:0,totalAssistantProfiles:0,webChatConnections:0,whatsAppConnections:{total:0,active:0,healthy:0,degraded:0}}}));return Promise.resolve(json({},404));}));renderApp();await waitFor(()=>expect(window.location.pathname).toBe("/admin"));await screen.findByRole("heading",{name:"Administración de Atlas"});});
