import { useEffect, useState } from "react";
import { atlasApi } from "../api/atlasApi";
import { useRouter } from "../routing/RouterProvider";
import { useAuthentication } from "../state/AuthenticationContext";
import type { PlatformOverview, PlatformUserSummary, PlatformWorkspaceSummary } from "../types/api";
import { StartupState } from "../components/StartupState";

function AdminShell({ children }: { readonly children: React.ReactNode }): React.JSX.Element {
  const { navigate, navigateToOwnWorkspace, appRoute } = useRouter(); const { logout } = useAuthentication();
  return <div className="admin-shell"><header className="admin-shell__header"><button className="admin-shell__brand" onClick={() => navigate("/admin")}>ATLAS <span>ADMIN</span></button><nav aria-label="Administración"><button aria-current={appRoute.kind === "admin" && appRoute.route === "overview" ? "page" : undefined} onClick={() => navigate("/admin")}>Resumen</button><button aria-current={appRoute.kind === "admin" && appRoute.route === "workspaces" ? "page" : undefined} onClick={() => navigate("/admin/workspaces")}>Clientes</button><button aria-current={appRoute.kind === "admin" && appRoute.route === "users" ? "page" : undefined} onClick={() => navigate("/admin/users")}>Usuarios</button><button onClick={navigateToOwnWorkspace}>Mi espacio</button><button onClick={() => void logout().then(() => navigate("/sign-in", { replace: true }))}>Cerrar sesión</button></nav></header><main className="admin-shell__content">{children}</main></div>;
}
function count(value:number,label:string):React.JSX.Element{return <article className="admin-metric"><strong>{value}</strong><span>{label}</span></article>;}
function Overview():React.JSX.Element{const[data,setData]=useState<PlatformOverview|null>(null),[error,setError]=useState(false);useEffect(()=>{let current=true;void atlasApi.platformOverview().then(value=>{if(current)setData(value);}).catch(()=>{if(current)setError(true);});return()=>{current=false;};},[]);if(error)return <section className="admin-state"><h1>Administración de Atlas</h1><p role="alert">No pudimos cargar el resumen administrativo.</p></section>;if(!data)return <StartupState/>;return <section className="admin-page"><div><p className="admin-eyebrow">Control privado</p><h1>Administración de Atlas</h1><p>Vista operativa de clientes y capacidad conectada.</p></div><div className="admin-metrics">{count(data.totalUsers,"Usuarios registrados")}{count(data.totalWorkspaces,"Clientes")}{count(data.totalCompanies,"Empresas")}{count(data.totalAssistantProfiles,"Perfiles asistentes")}{count(data.webChatConnections,"Web Chat configurado")}{count(data.whatsAppConnections.active,"WhatsApp activo")}</div><p className="admin-note">WhatsApp: {data.whatsAppConnections.total} conexiones, {data.whatsAppConnections.healthy} saludables y {data.whatsAppConnections.degraded} con atención.</p></section>;}
function format(value:string|null):string{return value?new Intl.DateTimeFormat("es-AR",{dateStyle:"medium"}).format(new Date(value)):"Sin actividad";}
function Workspaces():React.JSX.Element{const[rows,setRows]=useState<PlatformWorkspaceSummary[]|null>(null),[error,setError]=useState(false);useEffect(()=>{let current=true;void atlasApi.platformWorkspaces().then(value=>{if(current)setRows(value.workspaces);}).catch(()=>{if(current)setError(true);});return()=>{current=false;};},[]);if(error)return <section className="admin-state"><h1>Clientes</h1><p role="alert">No pudimos cargar los clientes.</p></section>;if(!rows)return <StartupState/>;return <section className="admin-page"><div><p className="admin-eyebrow">Clientes</p><h1>Workspaces de Atlas</h1><p>Resumen seguro y de solo lectura de cada cuenta.</p></div>{rows.length===0?<div className="admin-state"><h2>No hay clientes todavía</h2><p>Los nuevos workspaces aparecerán aquí.</p></div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Cliente</th><th>Empresas</th><th>Miembros</th><th>Asistentes</th><th>Web Chat</th><th>WhatsApp</th><th>Creado</th><th>Actividad</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><th scope="row">{row.name}</th><td>{row.companyCount}</td><td>{row.memberCount}</td><td>{row.assistantProfileCount}</td><td>{row.webChatConnectionCount}</td><td>{row.whatsApp.active} activos</td><td>{format(row.createdAt)}</td><td>{format(row.latestActivityAt)}</td></tr>)}</tbody></table></div>}</section>;}
function Users():React.JSX.Element{const[rows,setRows]=useState<PlatformUserSummary[]|null>(null),[error,setError]=useState(false),[nextCursor,setNextCursor]=useState<string|null>(null);const load=(cursor?:string):void=>{void atlasApi.platformUsers(cursor).then(page=>{setRows(existing=>cursor?[...(existing??[]),...page.users]:page.users);setNextCursor(page.nextCursor);}).catch(()=>setError(true));};useEffect(()=>load(),[]);if(error)return <section className="admin-state"><h1>Usuarios</h1><p role="alert">No pudimos cargar los usuarios.</p></section>;if(!rows)return <StartupState/>;return <section className="admin-page"><div><p className="admin-eyebrow">Usuarios</p><h1>Usuarios registrados</h1><p>Información operativa de solo lectura.</p></div>{rows.length===0?<div className="admin-state"><h2>No hay usuarios todavía</h2></div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Correo</th><th>Verificado</th><th>Espacios activos</th><th>Registrado</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><th scope="row">{row.email}</th><td>{row.emailVerified?"Sí":"No"}</td><td>{row.activeWorkspaceMembershipCount}</td><td>{format(row.createdAt)}</td></tr>)}</tbody></table>{nextCursor&&<button onClick={()=>load(nextCursor)}>Cargar más</button>}</div>}</section>;}
export function AdminPortal():React.JSX.Element{const{state:auth}=useAuthentication(),{appRoute,navigate}=useRouter();useEffect(()=>{if(auth.status==="unauthenticated")navigate("/sign-in",{replace:true});else if(auth.status==="authenticated"&&!auth.identity.isPlatformAdmin)navigate("/dashboard",{replace:true});},[auth,navigate]);if(auth.status==="booting")return <StartupState/>;if(auth.status!=="authenticated"||!auth.identity.isPlatformAdmin)return <StartupState/>;if(appRoute.kind!=="admin"||appRoute.route==="not-found")return <AdminShell><section className="admin-state"><h1>Página no encontrada</h1></section></AdminShell>;return <AdminShell>{appRoute.route==="overview"?<Overview/>:appRoute.route==="workspaces"?<Workspaces/>:<Users/>}</AdminShell>;}
