// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import App from "../App";
import { I18nProvider } from "../i18n/I18nContext";
import { RouterProvider } from "../routing/RouterProvider";
import { AuthenticationProvider } from "../state/AuthenticationContext";
import { ThemeProvider } from "../design-system/theme";

const id="bce_0123456789abcdef0123456789abcdef",offerId="bpco_0123456789abcdef0123456789abcdef";
function json(value:unknown,status=200):Response{return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
function renderApp():void{render(<ThemeProvider><I18nProvider><RouterProvider><AuthenticationProvider><App/></AuthenticationProvider></RouterProvider></I18nProvider></ThemeProvider>);}
afterEach(()=>{cleanup();vi.unstubAllGlobals();window.history.replaceState({},"","/");});
const identity={userId:"admin",email:"admin@example.test",locale:"en",status:"active",isPlatformAdmin:true,idleExpiresAt:"2026-01-01",absoluteExpiresAt:"2026-01-01"};
function session():Response{return json({status:"authenticated",identity,csrfToken:"csrf",csrfGeneration:1});}
function detail(version:number=1,offers:unknown[]=[],audit:unknown[]=[]):object{return{id,planKey:"atlas",catalogVersion:1,displayName:"Atlas",description:"Plan comercial",publicationState:"draft",trialDurationDays:null,graceDurationDays:null,maxCompanies:1,maxAssistantProfiles:1,maxActiveChannels:1,mutationEligible:true,version,subscriberCount:0,offers,audit};}

test("renders catalog summaries without provider references",async()=>{window.history.replaceState({},"","/admin/plans");const{offers:_offers,audit:_audit,...plan}=detail()as Record<string,unknown>;vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(session());if(url.endsWith("/admin/billing/plans"))return Promise.resolve(json({data:[plan]}));return Promise.resolve(json({},404));}));renderApp();await screen.findByRole("heading",{name:"Planes"});expect(screen.getByText("Atlas")).toBeTruthy();expect(screen.getByText("draft")).toBeTruthy();expect(document.body.textContent).not.toContain("price_");});

test("renders provider offer state and audit metadata without exposing its provider reference",async()=>{window.history.replaceState({},"",`/admin/plans/${id}`);const offer={id:offerId,catalogEntryId:id,providerKind:"stripe",offerVersion:1,currency:"USD",amountMinor:1250,interval:"month",providerPlanReference:"price_internal_only",readinessState:"ready",lifecycle:"draft",version:1},audit={id:"bca_0123456789abcdef0123456789abcdef",operationId:"validate_offer",eventType:"provider_offer_validated",resultingVersion:3,occurredAt:"2026-01-01T00:00:00.000Z"};vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(session());if(url.endsWith(`/admin/billing/plans/${id}`))return Promise.resolve(json({data:detail(3,[offer],[audit])}));return Promise.resolve(json({},404));}));renderApp();await screen.findByText("ready");expect(screen.getByText("provider_offer_validated")).toBeTruthy();expect(screen.getByText(/12[.,]50/)).toBeTruthy();expect(document.body.textContent).not.toContain("price_internal_only");});

test("blocks incomplete draft offers locally without making a commercial mutation",async()=>{window.history.replaceState({},"",`/admin/plans/${id}`);vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(session());if(url.endsWith(`/admin/billing/plans/${id}`))return Promise.resolve(json({data:detail()}));return Promise.resolve(json({},404));}));renderApp();await screen.findByRole("heading",{name:"Operaciones del catálogo"});fireEvent.click(screen.getByRole("button",{name:"Agregar oferta Stripe"}));expect(await screen.findByText("Ingresá una referencia y un importe válido.")).toBeTruthy();expect(vi.mocked(fetch).mock.calls.some(([input,init])=>String(input).endsWith("/offers")&&(init as RequestInit)?.method==="POST")).toBe(false);});

test("validates and publishes a ready offer with the current versions and CSRF token",async()=>{window.history.replaceState({},"",`/admin/plans/${id}`);const offer={id:offerId,catalogEntryId:id,providerKind:"stripe",offerVersion:1,currency:"USD",amountMinor:1000,interval:"month",providerPlanReference:"price_private",readinessState:"not_configured",lifecycle:"draft",version:1},detailValue=detail(3,[offer])as Record<string,unknown>,{offers:_offers,audit:_audit,...plan}=detailValue;vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(session());if(url.endsWith(`/offers/${offerId}/validate`))return Promise.resolve(json({data:{...offer,readinessState:"ready",version:2}}));if(url.endsWith("/publish"))return Promise.resolve(json({data:{...plan,publicationState:"published",version:4}}));if(url.endsWith(`/admin/billing/plans/${id}`))return Promise.resolve(json({data:detailValue}));return Promise.resolve(json({},404));}));renderApp();await screen.findByRole("button",{name:"Validar stripe v1"});fireEvent.click(screen.getByRole("button",{name:"Validar stripe v1"}));await screen.findByText("Validación: ready.");fireEvent.click(screen.getByRole("button",{name:"Publicar plan"}));await screen.findByText("Plan publicado.");const calls=vi.mocked(fetch).mock.calls;const validation=calls.find(([input])=>String(input).endsWith(`/offers/${offerId}/validate`));const publication=calls.find(([input])=>String(input).endsWith("/publish"));expect(validation?.[1]).toMatchObject({headers:{"x-csrf-token":"csrf"},body:expect.stringContaining('"expectedVersion":3')});expect(publication?.[1]).toMatchObject({headers:{"x-csrf-token":"csrf"},body:expect.stringContaining('"expectedVersion":3')});});
test("adds and validates a draft provider offer without rendering provider secrets",async()=>{window.history.replaceState({},"",`/admin/plans/${id}`);const plan={id,planKey:"atlas",catalogVersion:1,displayName:"Atlas",description:"",publicationState:"draft",trialDurationDays:null,graceDurationDays:null,maxCompanies:1,maxAssistantProfiles:1,maxActiveChannels:1,mutationEligible:true,version:1,subscriberCount:0,offers:[],audit:[]};vi.stubGlobal("fetch",vi.fn((input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(url.endsWith("/session/bootstrap"))return Promise.resolve(json({status:"authenticated",identity:{userId:"admin",email:"admin@example.test",locale:"en",status:"active",isPlatformAdmin:true,idleExpiresAt:"2026-01-01",absoluteExpiresAt:"2026-01-01"},csrfToken:"csrf",csrfGeneration:1}));if(url.endsWith(`/admin/billing/plans/${id}`)&&!init?.method)return Promise.resolve(json({data:plan}));if(url.endsWith(`/admin/billing/plans/${id}/offers`))return Promise.resolve(json({data:{id:offerId,catalogEntryId:id,providerKind:"stripe",offerVersion:1,currency:"USD",amountMinor:1000,interval:"month",providerPlanReference:"price_public",readinessState:"not_configured",lifecycle:"draft",version:1}}));return Promise.resolve(json({},404));}));renderApp();await screen.findByRole("heading",{name:"Operaciones del catálogo"});fireEvent.change(screen.getByLabelText("Referencia Stripe"),{target:{value:"price_public"}});fireEvent.change(screen.getByLabelText("Importe menor USD"),{target:{value:"1000"}});fireEvent.click(screen.getByRole("button",{name:"Agregar oferta Stripe"}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([input,init])=>String(input).endsWith("/offers")&&(init as RequestInit)?.method==="POST")).toBe(true));const call=vi.mocked(fetch).mock.calls.find(([input,init])=>String(input).endsWith("/offers")&&(init as RequestInit)?.method==="POST");expect(call?.[1]).toMatchObject({headers:{"x-csrf-token":"csrf"}});expect(JSON.stringify(call)).not.toContain("SECRET");});
