import { createHash } from "node:crypto";
import { integrationConnectionId, type IntegrationConnectionId } from "../../integrations/domain/integrationConnection.js";
import { schedulingBookingId, schedulingHoldId, schedulingResourceId, type SchedulingBookingId, type SchedulingHoldId, type SchedulingResourceId, validateInstant } from "./scheduling.js";

export type ExternalCalendarBindingId = string & { readonly __externalCalendarBinding: unique symbol };
export type ExternalBookingEventId = string & { readonly __externalBookingEvent: unique symbol };
export type ExternalWriteOperationId = string & { readonly __externalWriteOperation: unique symbol };
export type ExternalWriteOperationKind = "create" | "reschedule" | "cancel";
export type ExternalWriteOperationState = "pending" | "in_flight" | "reconciling" | "succeeded" | "uncertain" | "conflict" | "failed";
export type ExternalRemoteEventState = "active" | "cancelled";
export type ExternalWriteFailureCode = "unauthorized" | "forbidden" | "conflict" | "rate_limited" | "unavailable" | "timeout" | "invalid_response" | "validation_error" | "recovery_expired";

export interface ExternalCalendarBinding { readonly id: ExternalCalendarBindingId; readonly workspaceId: number; readonly companyId: number; readonly resourceId: SchedulingResourceId; readonly integrationConnectionId: IntegrationConnectionId; readonly externalCalendarId: string; readonly createdAt: string; readonly updatedAt: string; }
export interface ExternalBookingEvent { readonly id: ExternalBookingEventId; readonly workspaceId: number; readonly companyId: number; readonly bookingId: SchedulingBookingId; readonly bindingId: ExternalCalendarBindingId; readonly externalEventId: string; readonly remoteVersion: string | null; readonly remoteState: ExternalRemoteEventState; readonly createdAt: string; readonly updatedAt: string; }
export interface ExternalWriteOperation {
  readonly id: ExternalWriteOperationId; readonly workspaceId: number; readonly companyId: number; readonly bindingId: ExternalCalendarBindingId; readonly operation: ExternalWriteOperationKind; readonly idempotencyKey: string; readonly requestFingerprint: string; readonly state: ExternalWriteOperationState; readonly providerRequestCorrelationId: string; readonly requestedBookingReference: string | null; readonly bookingId: SchedulingBookingId | null; readonly sourceBookingId: SchedulingBookingId | null; readonly holdId: SchedulingHoldId | null; readonly reservationExpiresAt: string | null; readonly externalEventId: string; readonly expectedRemoteVersion: string | null; readonly leaseToken: string | null; readonly leaseOwner: string | null; readonly leaseAcquiredAt: string | null; readonly leaseExpiresAt: string | null; readonly attemptCount: number; readonly lastAttemptAt: string | null; readonly safeFailureCode: ExternalWriteFailureCode | null; readonly completedAt: string | null; readonly createdAt: string; readonly updatedAt: string;
}

export class ExternalCalendarDomainError extends Error {}
export function externalCalendarBindingId(value: string): ExternalCalendarBindingId { return identifier(value, "ecb") as ExternalCalendarBindingId; }
export function externalBookingEventId(value: string): ExternalBookingEventId { return identifier(value, "ebe") as ExternalBookingEventId; }
export function externalWriteOperationId(value: string): ExternalWriteOperationId { return identifier(value, "ewo") as ExternalWriteOperationId; }
export function reconstructExternalCalendarBinding(value: ExternalCalendarBinding): ExternalCalendarBinding { scope(value.workspaceId, value.companyId); return Object.freeze({ ...value, id: externalCalendarBindingId(value.id), resourceId: schedulingResourceId(value.resourceId), integrationConnectionId: integrationConnectionId(value.integrationConnectionId), externalCalendarId: text(value.externalCalendarId, 200), createdAt: validateInstant(value.createdAt), updatedAt: validateInstant(value.updatedAt) }); }
export function reconstructExternalBookingEvent(value: ExternalBookingEvent): ExternalBookingEvent { scope(value.workspaceId, value.companyId); if (value.remoteState !== "active" && value.remoteState !== "cancelled") throw new ExternalCalendarDomainError("External booking event state is invalid."); return Object.freeze({ ...value, id: externalBookingEventId(value.id), bookingId: schedulingBookingId(value.bookingId), bindingId: externalCalendarBindingId(value.bindingId), externalEventId: text(value.externalEventId, 200), remoteVersion: optionalText(value.remoteVersion, 200), createdAt: validateInstant(value.createdAt), updatedAt: validateInstant(value.updatedAt) }); }
export function reconstructExternalWriteOperation(value: ExternalWriteOperation): ExternalWriteOperation {
  scope(value.workspaceId, value.companyId);
  if (!( ["create", "reschedule", "cancel"] as const).includes(value.operation) || !( ["pending", "in_flight", "reconciling", "succeeded", "uncertain", "conflict", "failed"] as const).includes(value.state) || !Number.isInteger(value.attemptCount) || value.attemptCount < 0) throw new ExternalCalendarDomainError("External write operation is invalid.");
  const hasHold = value.holdId !== null, hasReservation = value.reservationExpiresAt !== null, hasLease = [value.leaseToken, value.leaseOwner, value.leaseAcquiredAt, value.leaseExpiresAt].every(item => item !== null), noLease = [value.leaseToken, value.leaseOwner, value.leaseAcquiredAt, value.leaseExpiresAt].every(item => item === null);
  if (hasHold !== hasReservation || (!hasLease && !noLease) || (value.operation === "create" && (value.sourceBookingId !== null || !hasHold)) || (value.operation === "reschedule" && (value.sourceBookingId === null || !hasHold)) || (value.operation === "cancel" && (value.sourceBookingId === null || hasHold))) throw new ExternalCalendarDomainError("External write operation shape is invalid.");
  if ((value.state === "in_flight" || value.state === "reconciling") !== hasLease || (value.state !== "in_flight" && value.state !== "reconciling" && !noLease) || ((value.state === "succeeded" || value.state === "conflict" || value.state === "failed") !== (value.completedAt !== null)) || ((value.state === "pending" || value.state === "uncertain") && value.completedAt !== null) || (hasReservation && Date.parse(value.reservationExpiresAt!) <= Date.parse(value.createdAt)) || (hasReservation && Date.parse(value.reservationExpiresAt!) - Date.parse(value.createdAt) > 86_400_000)) throw new ExternalCalendarDomainError("External write operation lifecycle is invalid.");
  if (value.safeFailureCode !== null && !( ["unauthorized", "forbidden", "conflict", "rate_limited", "unavailable", "timeout", "invalid_response", "validation_error", "recovery_expired"] as const).includes(value.safeFailureCode)) throw new ExternalCalendarDomainError("External write failure code is invalid.");
  return Object.freeze({ ...value, id: externalWriteOperationId(value.id), bindingId: externalCalendarBindingId(value.bindingId), idempotencyKey: text(value.idempotencyKey, 200), requestFingerprint: fingerprint(value.requestFingerprint), providerRequestCorrelationId: text(value.providerRequestCorrelationId, 200), bookingId: value.bookingId === null ? null : schedulingBookingId(value.bookingId), sourceBookingId: value.sourceBookingId === null ? null : schedulingBookingId(value.sourceBookingId), holdId: value.holdId === null ? null : schedulingHoldId(value.holdId), reservationExpiresAt: value.reservationExpiresAt === null ? null : validateInstant(value.reservationExpiresAt), externalEventId: text(value.externalEventId, 200), expectedRemoteVersion: optionalText(value.expectedRemoteVersion, 200), leaseToken: optionalText(value.leaseToken, 200), leaseOwner: optionalText(value.leaseOwner, 200), leaseAcquiredAt: value.leaseAcquiredAt === null ? null : validateInstant(value.leaseAcquiredAt), leaseExpiresAt: value.leaseExpiresAt === null ? null : validateInstant(value.leaseExpiresAt), lastAttemptAt: value.lastAttemptAt === null ? null : validateInstant(value.lastAttemptAt), completedAt: value.completedAt === null ? null : validateInstant(value.completedAt), createdAt: validateInstant(value.createdAt), updatedAt: validateInstant(value.updatedAt) });
}
export function externalWriteRequestFingerprint(value: { readonly operation: ExternalWriteOperationKind; readonly bindingId: string; readonly serviceId?: string; readonly sourceBookingId?: string; readonly startAt?: string; readonly reference?: string; readonly externalEventId?: string }): string { return createHash("sha256").update(canonical(value)).digest("hex"); }
export function externalBusyObservationKey(bindingId: ExternalCalendarBindingId, startAt: string, endAt: string): string { return `gfb:${bindingId}:${createHash("sha256").update(`${bindingId}\u0000${startAt}\u0000${endAt}\u00001`).digest("hex")}`; }
function canonical(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "number" || typeof value === "string") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (!value || typeof value !== "object") throw new ExternalCalendarDomainError("External write fingerprint input is invalid."); return `{${Object.keys(value as Record<string, unknown>).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`; }
function identifier(value: string, prefix: string): string { if (!new RegExp(`^${prefix}_[a-f0-9]{32}$`).test(value)) throw new ExternalCalendarDomainError("External calendar identifier is invalid."); return value; }
function scope(workspaceId: number, companyId: number): void { if (!Number.isSafeInteger(workspaceId) || workspaceId < 1 || !Number.isSafeInteger(companyId) || companyId < 1) throw new ExternalCalendarDomainError("External calendar scope is invalid."); }
function text(value: string, maximum: number): string { if (typeof value !== "string" || !value.trim() || value.length > maximum) throw new ExternalCalendarDomainError("External calendar text is invalid."); return value.trim(); }
function optionalText(value: string | null, maximum: number): string | null { return value === null ? null : text(value, maximum); }
function fingerprint(value: string): string { if (!/^[a-f0-9]{64}$/.test(value)) throw new ExternalCalendarDomainError("External write fingerprint is invalid."); return value; }
