export type SchedulingResourceId = string & { readonly __resource: unique symbol };
export type SchedulingServiceId = string & { readonly __service: unique symbol };
export type SchedulingLocationId = string & { readonly __location: unique symbol };
export type SchedulingHoldId = string & { readonly __hold: unique symbol };
export type SchedulingBookingId = string & { readonly __booking: unique symbol };

export interface SchedulingLocation { readonly id: SchedulingLocationId; readonly workspaceId: number; readonly companyId: number; readonly name: string; readonly address: string | null; readonly timezone: string; readonly active: boolean; readonly createdAt: string; readonly updatedAt: string; }
export interface SchedulingResource { readonly id: SchedulingResourceId; readonly workspaceId: number; readonly companyId: number; readonly locationId: SchedulingLocationId | null; readonly name: string; readonly timezone: string; readonly capacity: number; readonly active: boolean; readonly createdAt: string; readonly updatedAt: string; }
export interface SchedulingService { readonly id: SchedulingServiceId; readonly workspaceId: number; readonly companyId: number; readonly resourceId: SchedulingResourceId; readonly name: string; readonly durationMinutes: number; readonly bufferBeforeMinutes: number; readonly bufferAfterMinutes: number; readonly slotGranularityMinutes: number; readonly minimumLeadMinutes: number; readonly maximumHorizonDays: number; readonly active: boolean; readonly createdAt: string; readonly updatedAt: string; }
export interface SchedulingWorkingWindow { readonly id: string; readonly resourceId: SchedulingResourceId; readonly weekday: number; readonly startTime: string; readonly endTime: string; }
export interface SchedulingAvailabilityException { readonly id: string; readonly resourceId: SchedulingResourceId; readonly localDate: string; readonly kind: "closed" | "open"; readonly startTime: string | null; readonly endTime: string | null; }
export interface SchedulingBusyInterval { readonly id: string; readonly workspaceId: number; readonly companyId: number; readonly resourceId: SchedulingResourceId; readonly startAt: string; readonly endAt: string; readonly units: number; readonly source: "internal_block" | "external_observed"; readonly externalReference: string | null; readonly createdAt: string; }
export interface SchedulingHold { readonly id: SchedulingHoldId; readonly workspaceId: number; readonly companyId: number; readonly serviceId: SchedulingServiceId; readonly idempotencyKey: string; readonly startAt: string; readonly endAt: string; readonly occupiedStartAt: string; readonly occupiedEndAt: string; readonly expiresAt: string; readonly state: "active" | "released" | "expired"; readonly createdAt: string; readonly releasedAt: string | null; }
export interface SchedulingBooking { readonly id: SchedulingBookingId; readonly workspaceId: number; readonly companyId: number; readonly serviceId: SchedulingServiceId; readonly holdId: SchedulingHoldId | null; readonly rescheduledFromBookingId: SchedulingBookingId | null; readonly reference: string; readonly startAt: string; readonly endAt: string; readonly occupiedStartAt: string; readonly occupiedEndAt: string; readonly state: "confirmed" | "cancelled"; readonly createdAt: string; readonly cancelledAt: string | null; }
export interface SchedulingSlot { readonly serviceId: SchedulingServiceId; readonly resourceId: SchedulingResourceId; readonly startAt: string; readonly endAt: string; readonly localDate: string; readonly localStartTime: string; }
export interface SchedulingOccupancy { readonly startAt: string; readonly endAt: string; readonly units: number; }
export class SchedulingError extends Error {}
export class SchedulingNameConflictError extends SchedulingError {}

export function schedulingId(value: string, prefix: "src" | "ssv" | "slc" | "shd" | "sbk"): string { if (!new RegExp(`^${prefix}_[a-f0-9]{32}$`).test(value)) throw new SchedulingError("Scheduling ID is invalid."); return value; }
export function schedulingResourceId(value: string): SchedulingResourceId { return schedulingId(value, "src") as SchedulingResourceId; }
export function schedulingServiceId(value: string): SchedulingServiceId { return schedulingId(value, "ssv") as SchedulingServiceId; }
export function schedulingLocationId(value: string): SchedulingLocationId { return schedulingId(value, "slc") as SchedulingLocationId; }
export function schedulingHoldId(value: string): SchedulingHoldId { return schedulingId(value, "shd") as SchedulingHoldId; }
export function schedulingBookingId(value: string): SchedulingBookingId { return schedulingId(value, "sbk") as SchedulingBookingId; }
export function validateTimezone(value: string): string { try { return new Intl.DateTimeFormat("en-US", { timeZone: value }).resolvedOptions().timeZone; } catch { throw new SchedulingError("Scheduling timezone is invalid."); } }
export function validateTime(value: string): string { if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(value)) throw new SchedulingError("Scheduling local time is invalid."); return value; }
export function validateDate(value: string): string { if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || new Date(`${value}T00:00:00.000Z`).toISOString().slice(0, 10) !== value) throw new SchedulingError("Scheduling local date is invalid."); return value; }
export function validateInstant(value: string): string { if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) || Number.isNaN(Date.parse(value)) || new Date(value).toISOString() !== value) throw new SchedulingError("Scheduling timestamp must be a UTC ISO timestamp."); return value; }
export function validateInterval(startAt: string, endAt: string): { readonly startAt: string; readonly endAt: string } { const start = validateInstant(startAt), end = validateInstant(endAt); if (Date.parse(end) <= Date.parse(start)) throw new SchedulingError("Scheduling interval is invalid."); return { startAt: start, endAt: end }; }
export function normalizeSchedulingName(value: string): string { return required(value, 200).normalize("NFKC").trim().toLocaleLowerCase("en-US"); }
export function reconstructResource(value: SchedulingResource): SchedulingResource { scoped(value.workspaceId, value.companyId); required(value.name, 200); integer(value.capacity, 1, 10000); return Object.freeze({ ...value, id: schedulingResourceId(value.id), locationId: value.locationId === null ? null : schedulingLocationId(value.locationId), timezone: validateTimezone(value.timezone), createdAt: validateInstant(value.createdAt), updatedAt: validateInstant(value.updatedAt) }); }
export function reconstructLocation(value: SchedulingLocation): SchedulingLocation { scoped(value.workspaceId, value.companyId); required(value.name, 200); if (value.address !== null && value.address.length > 500) throw new SchedulingError("Scheduling location is invalid."); return Object.freeze({ ...value, id: schedulingLocationId(value.id), timezone: validateTimezone(value.timezone), createdAt: validateInstant(value.createdAt), updatedAt: validateInstant(value.updatedAt) }); }
export function reconstructService(value: SchedulingService): SchedulingService { scoped(value.workspaceId, value.companyId); required(value.name, 200); integer(value.durationMinutes, 1, 1440); integer(value.bufferBeforeMinutes, 0, 1440); integer(value.bufferAfterMinutes, 0, 1440); integer(value.slotGranularityMinutes, 1, 1440); integer(value.minimumLeadMinutes, 0, 525600); integer(value.maximumHorizonDays, 1, 730); return Object.freeze({ ...value, id: schedulingServiceId(value.id), resourceId: schedulingResourceId(value.resourceId), createdAt: validateInstant(value.createdAt), updatedAt: validateInstant(value.updatedAt) }); }
export function reconstructWorkingWindow(value: SchedulingWorkingWindow): SchedulingWorkingWindow { if (!/^[a-f0-9]{32}$/.test(value.id)) throw new SchedulingError("Scheduling working window is invalid."); integer(value.weekday, 0, 6); if (validateTime(value.startTime) >= validateTime(value.endTime)) throw new SchedulingError("Scheduling working window is invalid."); return Object.freeze({ ...value, resourceId: schedulingResourceId(value.resourceId) }); }
export function reconstructException(value: SchedulingAvailabilityException): SchedulingAvailabilityException { if (!/^[a-f0-9]{32}$/.test(value.id) || (value.kind !== "closed" && value.kind !== "open")) throw new SchedulingError("Scheduling exception is invalid."); validateDate(value.localDate); if ((value.startTime === null) !== (value.endTime === null)) throw new SchedulingError("Scheduling exception is invalid."); if (value.startTime !== null && (validateTime(value.startTime) >= validateTime(value.endTime!))) throw new SchedulingError("Scheduling exception is invalid."); return Object.freeze({ ...value, resourceId: schedulingResourceId(value.resourceId) }); }
export function reconstructBusyInterval(value: SchedulingBusyInterval): SchedulingBusyInterval { scoped(value.workspaceId, value.companyId); if (!/^[a-f0-9]{32}$/.test(value.id) || (value.source !== "internal_block" && value.source !== "external_observed")) throw new SchedulingError("Scheduling busy interval is invalid."); validateInterval(value.startAt, value.endAt); integer(value.units, 1, 10000); if ((value.source === "external_observed") !== (value.externalReference !== null)) throw new SchedulingError("Scheduling busy interval is invalid."); if (value.externalReference !== null) required(value.externalReference, 200); return Object.freeze({ ...value, resourceId: schedulingResourceId(value.resourceId), createdAt: validateInstant(value.createdAt) }); }
export function reconstructHold(value: SchedulingHold): SchedulingHold { scoped(value.workspaceId, value.companyId); required(value.idempotencyKey, 200); validateInterval(value.startAt, value.endAt); validateInterval(value.occupiedStartAt, value.occupiedEndAt); validateInstant(value.expiresAt); if (Date.parse(value.expiresAt) < Date.parse(value.createdAt) || !["active", "released", "expired"].includes(value.state)) throw new SchedulingError("Scheduling hold is invalid."); return Object.freeze({ ...value, id: schedulingHoldId(value.id), serviceId: schedulingServiceId(value.serviceId), createdAt: validateInstant(value.createdAt) }); }
export function reconstructBooking(value: SchedulingBooking): SchedulingBooking { scoped(value.workspaceId, value.companyId); required(value.reference, 100); validateInterval(value.startAt, value.endAt); validateInterval(value.occupiedStartAt, value.occupiedEndAt); if (!["confirmed", "cancelled"].includes(value.state)) throw new SchedulingError("Scheduling booking is invalid."); return Object.freeze({ ...value, id: schedulingBookingId(value.id), serviceId: schedulingServiceId(value.serviceId), holdId: value.holdId === null ? null : schedulingHoldId(value.holdId), rescheduledFromBookingId: value.rescheduledFromBookingId === null ? null : schedulingBookingId(value.rescheduledFromBookingId), createdAt: validateInstant(value.createdAt) }); }
function scoped(workspaceId: number, companyId: number): void { integer(workspaceId, 1, Number.MAX_SAFE_INTEGER); integer(companyId, 1, Number.MAX_SAFE_INTEGER); }
function integer(value: number, minimum: number, maximum: number): void { if (!Number.isInteger(value) || value < minimum || value > maximum) throw new SchedulingError("Scheduling number is invalid."); }
function required(value: string, maximum: number): string { if (typeof value !== "string" || value.trim().length === 0 || value.length > maximum) throw new SchedulingError("Scheduling text is invalid."); return value; }
