export type WhatsAppInboundMediaKind = "image" | "document" | "audio";
export type WhatsAppInboundMediaState = "pending_download" | "ingesting" | "associated" | "failed" | "unsupported";
export type WhatsAppInboundMediaFailure = "unsupported_media" | "integration_not_ready" | "media_download_failed" | "media_expired" | "media_too_large" | "media_mime_mismatch" | "media_ingest_failed" | "media_idempotency_in_progress" | "association_failed" | "provider_temporary_failure";

export interface WhatsAppInboundMediaDescriptor { readonly wamid: string; readonly providerMediaId: string; readonly kind: WhatsAppInboundMediaKind; readonly declaredMime: string; readonly filename: string | null; readonly caption: string | null; readonly ordinal: number; }
export interface WhatsAppInboundMedia { readonly id: string; readonly workspaceId: number; readonly companyId: number; readonly connectionId: string; readonly eventId: string; readonly conversationMessageId: string; readonly descriptor: WhatsAppInboundMediaDescriptor; readonly state: WhatsAppInboundMediaState; readonly mediaAssetId: string | null; readonly failureCode: WhatsAppInboundMediaFailure | null; readonly lastRetryFailureCode?: WhatsAppInboundMediaFailure | null; readonly lastRetryFailureAt?: string | null; readonly attemptCount: number; readonly nextAttemptAt: string | null; readonly leaseToken?: string | null; readonly leaseOwner?: string | null; readonly leaseAcquiredAt?: string | null; readonly leaseExpiresAt?: string | null; readonly createdAt: string; readonly updatedAt: string; readonly completedAt: string | null; }
export class WhatsAppInboundMediaError extends Error { public constructor(public readonly code: WhatsAppInboundMediaFailure) { super(code); } }
export type WhatsAppInboundMediaTransitionOutcome = { readonly kind:"applied"|"replayed"; readonly media:WhatsAppInboundMedia } | { readonly kind:"lease_lost"|"not_found" } | { readonly kind:"conflict"; readonly currentState:WhatsAppInboundMediaState };
export function neutralAttachmentMessage(): string { return "[attachment received]"; }
