import { productionAssistantCapabilityCatalog } from "../../assistant/domain/assistantCapability.js";
import type { ToolDefinition, ToolExecutionContext, ToolSchema } from "../../assistant/domain/tool.js";
import { SchedulingConflictError, SchedulingIdempotencyError, SchedulingNotFoundError } from "../services/schedulingService.js";
import type { BookingCommandService } from "../services/bookingCommandService.js";
import type { BookingQueryService } from "../services/bookingQueryService.js";

type SafeResult = { readonly status: "confirmed" | "cancelled" | "already_cancelled" | "not_found" | "conflict" | "unavailable"; readonly bookingId: string | null; readonly reference: string | null; readonly startAt: string | null; readonly endAt: string | null; readonly rescheduledFromBookingId: string | null; };
const outputSchema = { type: "object" as const, maxProperties: 6, required: ["status", "bookingId", "reference", "startAt", "endAt", "rescheduledFromBookingId"], properties: { status: { type: "enum" as const, values: ["confirmed", "cancelled", "already_cancelled", "not_found", "conflict", "unavailable"] }, bookingId: { type: "string" as const, maxLength: 40, nullable: true }, reference: { type: "string" as const, maxLength: 100, nullable: true }, startAt: { type: "string" as const, maxLength: 40, nullable: true }, endAt: { type: "string" as const, maxLength: 40, nullable: true }, rescheduledFromBookingId: { type: "string" as const, maxLength: 40, nullable: true } } };
export function schedulingBookingToolDefinitions(commands: BookingCommandService, queries: BookingQueryService): readonly ToolDefinition[] {
  return Object.freeze([
    write("scheduling.create_booking", "Creates a confirmed booking after authoritatively validating the requested slot.", ["serviceId", "startAt", "reference"], { serviceId: text(), startAt: text(), reference: text() }, (context, input) => commands.create(runtime(context), context.companyId, { ...(input as { serviceId: string; startAt: string; reference: string }), idempotencyKey: context.idempotencyKey! })),
    write("scheduling.reschedule_booking", "Atomically replaces a confirmed booking after authoritatively validating the new slot.", ["bookingId", "newStartAt", "reference"], { bookingId: text(), newStartAt: text(), reference: text() }, (context, input) => commands.reschedule(runtime(context), context.companyId, { ...(input as { bookingId: string; newStartAt: string; reference: string }), idempotencyKey: context.idempotencyKey! })),
    write("scheduling.cancel_booking", "Cancels a customer-approved booking.", ["bookingId"], { bookingId: text() }, async (context, input) => { const result = await commands.cancelWithOutcome(runtime(context), context.companyId, { bookingId: (input as { bookingId: string }).bookingId, idempotencyKey: context.idempotencyKey! }); return { ...result.booking, state: result.status }; }),
    read(queries),
  ]);
}
function write(name: string, description: string, required: readonly string[], properties: Record<string, { readonly type: "string"; readonly maxLength: number }>, execute: (context: ToolExecutionContext, input: unknown) => Promise<import("../domain/scheduling.js").SchedulingBooking | (Omit<import("../domain/scheduling.js").SchedulingBooking, "state"> & { readonly state: "already_cancelled" })>): ToolDefinition { return Object.freeze({ name, description, inputSchema: { type: "object" as const, maxProperties: required.length, required, properties: properties as Record<string, ToolSchema> }, outputSchema, requiredCapabilities: [productionAssistantCapabilityCatalog.require(name)], operationClass: "write", timeoutMilliseconds: 10_000, idempotencyPolicy: "source_owned_required", confirmationPolicy: "user", auditPolicy: { inputFields: required, outputFields: ["status", "bookingId", "reference"] }, executor: async (context: ToolExecutionContext, input: unknown) => safe(() => execute(context, input)) }); }
function read(queries: BookingQueryService): ToolDefinition { return Object.freeze({ name: "scheduling.get_booking", description: "Reads the current safe status of a booking.", inputSchema: { type: "object" as const, maxProperties: 1, required: ["bookingId"], properties: { bookingId: text() } }, outputSchema, requiredCapabilities: [productionAssistantCapabilityCatalog.require("scheduling.get_booking")], operationClass: "read", timeoutMilliseconds: 10_000, idempotencyPolicy: "not_applicable", confirmationPolicy: "none", auditPolicy: { inputFields: ["bookingId"], outputFields: ["status", "bookingId", "reference"] }, executor: async (context: ToolExecutionContext, input: unknown) => safe(() => queries.get(runtime(context), context.companyId, (input as { bookingId: string }).bookingId)) }); }
function text(): { readonly type: "string"; readonly maxLength: number } { return { type: "string", maxLength: 200 }; }
function runtime(context: { readonly workspaceId: number }): { readonly workspaceId: number; readonly workspaceKey: string } { return { workspaceId: context.workspaceId, workspaceKey: "runtime" }; }
async function safe(run: () => Promise<import("../domain/scheduling.js").SchedulingBooking | (Omit<import("../domain/scheduling.js").SchedulingBooking, "state"> & { readonly state: "already_cancelled" })>): Promise<SafeResult> { try { const booking = await run(); return Object.freeze({ status: booking.state, bookingId: booking.id, reference: booking.reference, startAt: booking.startAt, endAt: booking.endAt, rescheduledFromBookingId: booking.rescheduledFromBookingId }); } catch (error: unknown) { const status = error instanceof SchedulingNotFoundError ? "not_found" : error instanceof SchedulingConflictError || error instanceof SchedulingIdempotencyError ? "conflict" : "unavailable"; return Object.freeze({ status, bookingId: null, reference: null, startAt: null, endAt: null, rescheduledFromBookingId: null }); } }
