import type { IntegrationConnectionId } from "../../integrations/domain/integrationConnection.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { ExternalBookingEvent, ExternalCalendarBinding, ExternalCalendarBindingId, ExternalRemoteEventState, ExternalWriteOperation, ExternalWriteOperationId, ExternalWriteOperationState } from "../domain/externalCalendar.js";
import type { SchedulingBooking } from "../domain/scheduling.js";

export type ExternalCalendarProviderFailure = "not_found" | "unauthorized" | "forbidden" | "conflict" | "rate_limited" | "unavailable" | "timeout" | "invalid_response" | "validation_error";
export type ExternalBusyReadResult = { readonly kind: "success"; readonly intervals: readonly { readonly startAt: string; readonly endAt: string; readonly units: number; readonly observationKey: string }[] } | { readonly kind: Exclude<ExternalCalendarProviderFailure, "not_found" | "conflict"> };
export type ExternalEventResult = { readonly kind: "success"; readonly event: { readonly externalEventId: string; readonly remoteVersion: string | null; readonly remoteState: ExternalRemoteEventState; readonly startAt: string; readonly endAt: string; readonly timeZone: string; readonly createOperationId: string | null; readonly lastOperationId: string | null; } } | { readonly kind: ExternalCalendarProviderFailure };
export interface ExternalBusyProviderPort { listBusyIntervals(request: { readonly context: WorkspaceContext; readonly companyId: number; readonly connectionId: IntegrationConnectionId; readonly binding: ExternalCalendarBinding; readonly startAt: string; readonly endAt: string; readonly signal: AbortSignal }): Promise<ExternalBusyReadResult>; }
export interface ExternalCalendarEventProviderPort {
  getEvent(request: { readonly context: WorkspaceContext; readonly companyId: number; readonly connectionId: IntegrationConnectionId; readonly binding: ExternalCalendarBinding; readonly externalEventId: string; readonly signal: AbortSignal }): Promise<ExternalEventResult>;
  insertEvent(request: { readonly context: WorkspaceContext; readonly companyId: number; readonly connectionId: IntegrationConnectionId; readonly binding: ExternalCalendarBinding; readonly externalEventId: string; readonly operationId: string; readonly startAt: string; readonly endAt: string; readonly timeZone: string; readonly signal: AbortSignal }): Promise<ExternalEventResult>;
  patchEvent(request: { readonly context: WorkspaceContext; readonly companyId: number; readonly connectionId: IntegrationConnectionId; readonly binding: ExternalCalendarBinding; readonly externalEventId: string; readonly operationId: string; readonly expectedRemoteVersion: string; readonly startAt: string; readonly endAt: string; readonly timeZone: string; readonly signal: AbortSignal }): Promise<ExternalEventResult>;
  deleteEvent(request: { readonly context: WorkspaceContext; readonly companyId: number; readonly connectionId: IntegrationConnectionId; readonly binding: ExternalCalendarBinding; readonly externalEventId: string; readonly expectedRemoteVersion: string; readonly signal: AbortSignal }): Promise<{ readonly kind: "success" } | { readonly kind: ExternalCalendarProviderFailure }>;
}
export interface ExternalCalendarBindingRepositoryPort { create(context: WorkspaceContext, value: ExternalCalendarBinding): Promise<ExternalCalendarBinding | null>; findByResource(context: WorkspaceContext, companyId: number, resourceId: string): Promise<ExternalCalendarBinding | null>; findById(context: WorkspaceContext, companyId: number, id: ExternalCalendarBindingId): Promise<ExternalCalendarBinding | null>; }
export interface ExternalBookingEventRepositoryPort { create(context: WorkspaceContext, value: ExternalBookingEvent): Promise<ExternalBookingEvent | null>; findByBooking(context: WorkspaceContext, companyId: number, bookingId: string): Promise<ExternalBookingEvent | null>; findCurrent(context: WorkspaceContext, companyId: number, bookingId: string, bindingId: ExternalCalendarBindingId): Promise<ExternalBookingEvent | null>; }
export type ExternalWriteClaimOutcome = { readonly kind: "claimed"; readonly operation: ExternalWriteOperation } | { readonly kind: "idle" | "not_found" | "conflict" };
export type ExternalWriteTransitionOutcome = { readonly kind: "applied" | "replayed"; readonly operation: ExternalWriteOperation } | { readonly kind: "lease_lost" | "not_found" } | { readonly kind: "conflict"; readonly operation: ExternalWriteOperation };
export interface ExternalWriteOperationRepositoryPort {
  create(context: WorkspaceContext, value: ExternalWriteOperation): Promise<{ readonly kind: "created"; readonly operation: ExternalWriteOperation } | { readonly kind: "same"; readonly operation: ExternalWriteOperation } | { readonly kind: "divergent" } | { readonly kind: "not_found" }>;
  findOperationById(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId): Promise<ExternalWriteOperation | null>;
  findOperationByIdempotency(context: WorkspaceContext, companyId: number, bindingId: ExternalCalendarBindingId, operation: ExternalWriteOperation["operation"], idempotencyKey: string): Promise<ExternalWriteOperation | null>;
  findCurrent(context: WorkspaceContext, companyId: number, bookingId: string, bindingId: ExternalCalendarBindingId): Promise<ExternalBookingEvent | null>;
  listRecoverable(context: WorkspaceContext, companyId: number, states: readonly ExternalWriteOperationState[], now: string): Promise<readonly ExternalWriteOperation[]>;
  claimPending(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, owner: string, now: string, leaseExpiresAt: string): Promise<ExternalWriteClaimOutcome>;
  claimRecoverable(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, owner: string, now: string, leaseExpiresAt: string): Promise<ExternalWriteClaimOutcome>;
  markSucceeded(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, now: string): Promise<ExternalWriteTransitionOutcome>;
  markUncertain(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, failureCode: "unavailable" | "timeout" | "invalid_response", now: string): Promise<ExternalWriteTransitionOutcome>;
  markConflict(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, now: string): Promise<ExternalWriteTransitionOutcome>;
  markFailed(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, failureCode: Exclude<ExternalWriteOperation["safeFailureCode"], null | "recovery_expired">, now: string): Promise<ExternalWriteTransitionOutcome>;
  markReconciliationSafeToRetry(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, now: string): Promise<ExternalWriteTransitionOutcome>;
  finalizeCreate(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, remoteVersion: string, now: string): Promise<{ readonly kind: "applied" | "replayed"; readonly booking: SchedulingBooking } | { readonly kind: "lease_lost" | "not_found" | "conflict" }>;
  finalizeReschedule(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, remoteVersion: string, now: string): Promise<{ readonly kind: "applied" | "replayed"; readonly booking: SchedulingBooking } | { readonly kind: "lease_lost" | "not_found" | "conflict" }>;
  finalizeCancel(context: WorkspaceContext, companyId: number, id: ExternalWriteOperationId, leaseToken: string, now: string): Promise<{ readonly kind: "applied" | "replayed"; readonly booking: SchedulingBooking } | { readonly kind: "lease_lost" | "not_found" | "conflict" }>;
}
