import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { CompanyEvent, CompanyEventType, CreateCompanyPersistenceResult, SaveCompanyPersistenceResult } from "../application/ports.js";
import { reconstructCompany, type Company, type CompanyConfigurationInput, type CompanyId, type CompanySlug, type CompanyState } from "../domain/company.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import { CompanyDomainRepositoryContractError } from "../../repositories/companyDomainRepository.js";
import type { AsyncCompanyRepositoryPort } from "../../application/ports/repositories.js";
import type { Company as LegacyCompany, CompanyCreateInput, CompanyPersistenceInput, CompanyStatus } from "../../types/company.js";
import { normalizeCompanyName } from "../domain/company.js";
import { randomUUID } from "node:crypto";

type Row = Record<string, unknown>;
const columns = "id,workspace_id,name,name_normalized,slug,description,website,public_name,logo_asset_ref,brand_colors_json,lifecycle_state,timezone,locale,country_code,currency_code,date_format,phone_format,business_hours_json,version,created_at,updated_at,lifecycle_changed_at,suspended_at,archived_at";
const eventTypes = new Set<CompanyEventType>(["CompanyCreated","CompanyIdentityUpdated","CompanyBrandingUpdated","CompanyConfigurationUpdated","CompanyConfigured","CompanyActivated","CompanyAttentionRequired","CompanySuspended","CompanyRestored","CompanyArchived","CompanyUpdated"]);
function json(value: string, label: string): unknown { try { return JSON.parse(value); } catch { throw new CompanyDomainRepositoryContractError(`${label} JSON is invalid.`); } }
function required(value: unknown, label: string): string { if (value === null || value === undefined) throw new CompanyDomainRepositoryContractError(`${label} is missing.`); return String(value); }
function company(row: Row): Company { return reconstructCompany({ id:Number(row.id),workspaceId:Number(row.workspace_id),name:String(row.name),normalizedName:String(row.name_normalized),slug:String(row.slug),description:row.description as string|null,website:row.website as string|null,branding:{publicName:row.public_name as string|null,logoAssetReference:row.logo_asset_ref as string|null,colorTokens:json(String(row.brand_colors_json),"Brand colors") as Record<string,string>},configuration:row.timezone === null ? null : {timezone:String(row.timezone),locale:required(row.locale,"Company locale"),operatingLocale:{countryCode:required(row.country_code,"Country code"),currencyCode:required(row.currency_code,"Currency code"),dateFormat:required(row.date_format,"Date format") as "YYYY-MM-DD"|"DD/MM/YYYY"|"MM/DD/YYYY",phoneFormat:required(row.phone_format,"Phone format") as "international"|"national"},businessHours:json(String(row.business_hours_json),"Business hours") as CompanyConfigurationInput["businessHours"]},lifecycle:String(row.lifecycle_state),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at),lifecycleChangedAt:String(row.lifecycle_changed_at),suspendedAt:row.suspended_at as string|null,archivedAt:row.archived_at as string|null} as unknown as CompanyState); }
function constraint(error: unknown, column: string): boolean { return error instanceof Error && error.message.includes(column); }
function strictIsoTimestamp(value: string): boolean { const parsed = new Date(value); return !Number.isNaN(parsed.getTime()) && parsed.toISOString() === value; }

/** Async Company aggregate persistence seam; no synchronous application port is changed by this pass. */
export class AsyncCompanyDomainRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async findById(context: WorkspaceContext, id: CompanyId): Promise<Company | null> { const rows=await this.database.query<Row>(`SELECT ${columns} FROM companies WHERE workspace_id=? AND id=?`,[context.workspaceId,id]);return rows[0]?company(rows[0]):null; }
  public async findBySlug(context: WorkspaceContext, slug: CompanySlug): Promise<Company | null> { const rows=await this.database.query<Row>(`SELECT ${columns} FROM companies WHERE workspace_id=? AND slug=?`,[context.workspaceId,slug]);return rows[0]?company(rows[0]):null; }
  public async listByWorkspace(context: WorkspaceContext): Promise<readonly Company[]> { return (await this.database.query<Row>(`SELECT ${columns} FROM companies WHERE workspace_id=? ORDER BY id DESC`,[context.workspaceId])).map(company); }
  public async existsBySlug(context: WorkspaceContext, slug: CompanySlug, excluding?: CompanyId): Promise<boolean> { return (await this.database.query<Row>(excluding===undefined?"SELECT 1 FROM companies WHERE workspace_id=? AND slug=?":"SELECT 1 FROM companies WHERE workspace_id=? AND slug=? AND id!=?",excluding===undefined?[context.workspaceId,slug]:[context.workspaceId,slug,excluding])).length>0; }
  public async existsByNormalizedName(context: WorkspaceContext, name: string, excluding?: CompanyId): Promise<boolean> { return (await this.database.query<Row>(excluding===undefined?"SELECT 1 FROM companies WHERE workspace_id=? AND name_normalized=?":"SELECT 1 FROM companies WHERE workspace_id=? AND name_normalized=? AND id!=?",excluding===undefined?[context.workspaceId,name]:[context.workspaceId,name,excluding])).length>0; }
  public async createWithEvents(context: WorkspaceContext, value: Company, events: readonly CompanyEvent[]): Promise<CreateCompanyPersistenceResult> { const current=this.assertScope(context,value);this.assertEvents(current,events);try{return await this.database.transaction(async database=>{await database.execute(`INSERT INTO companies (${columns}) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,this.values(current));await this.events(database,context,current,events);const created=await this.findOn(database,context,current.id);if(!created)throw new CompanyDomainRepositoryContractError("Company could not be read after creation.");return {status:"created",company:created};});}catch(error){if(constraint(error,"companies.workspace_id, companies.slug"))return{status:"slug_conflict"};if(constraint(error,"companies.workspace_id, companies.name_normalized"))return{status:"name_conflict"};if(error instanceof Error&&error.message.includes("workspace company creation is unavailable"))return{status:"commercial_limit_reached"};throw error;} }
  public async saveWithEvents(context: WorkspaceContext, value: Company, expected: number, events: readonly CompanyEvent[]): Promise<SaveCompanyPersistenceResult> { const current=this.assertScope(context,value);if(!Number.isInteger(expected)||expected<1)throw new CompanyDomainRepositoryContractError("Expected Company version is invalid.");this.assertEvents(current,events);try{return await this.database.transaction(async database=>{const stored=(await database.query<Row>("SELECT version FROM companies WHERE workspace_id=? AND id=?",[context.workspaceId,current.id]))[0];if(!stored)return{status:"not_found"};if(Number(stored.version)!==expected)return{status:"version_conflict"};if(current.version!==expected+1)throw new CompanyDomainRepositoryContractError("Company version must advance exactly once from the expected version.");const write=await database.execute("UPDATE companies SET name=?,name_normalized=?,slug=?,description=?,website=?,public_name=?,logo_asset_ref=?,brand_colors_json=?,lifecycle_state=?,timezone=?,locale=?,country_code=?,currency_code=?,date_format=?,phone_format=?,business_hours_json=?,version=?,updated_at=?,lifecycle_changed_at=?,suspended_at=?,archived_at=? WHERE workspace_id=? AND id=? AND version=?",[...this.updateValues(current),context.workspaceId,current.id,expected]);if(Number(write.rowsAffected)!==1)return{status:"version_conflict"};await this.events(database,context,current,events);const saved=await this.findOn(database,context,current.id);if(!saved)throw new CompanyDomainRepositoryContractError("Company could not be read after save.");return{status:"saved",company:saved};});}catch(error){if(constraint(error,"companies.workspace_id, companies.slug"))return{status:"slug_conflict"};if(constraint(error,"companies.workspace_id, companies.name_normalized"))return{status:"name_conflict"};throw error;} }
  private values(value: Company): readonly (string|number|null)[] { const c=value.configuration;return[value.id,value.workspaceId,value.name,value.normalizedName,value.slug,value.description,value.website,value.branding.publicName,value.branding.logoAssetReference,JSON.stringify(value.branding.colorTokens),value.lifecycle,c?.timezone??null,c?.locale??null,c?.operatingLocale.countryCode??null,c?.operatingLocale.currencyCode??null,c?.operatingLocale.dateFormat??null,c?.operatingLocale.phoneFormat??null,JSON.stringify(c?.businessHours??{}),value.version,value.createdAt,value.updatedAt,value.lifecycleChangedAt,value.suspendedAt,value.archivedAt]; }
  private updateValues(value: Company): readonly (string|number|null)[] { const values=this.values(value);return[...values.slice(2,19),...values.slice(20)]; }
  private assertScope(context: WorkspaceContext, value: Company): Company { const current=reconstructCompany(value as unknown as CompanyState);if(current.workspaceId!==context.workspaceId)throw new CompanyDomainRepositoryContractError("Company ownership does not match repository scope.");return current; }
  private assertEvents(value: Company, events: readonly CompanyEvent[]): void { if(events.length===0)throw new CompanyDomainRepositoryContractError("Company persistence requires at least one event.");for(let index=0;index<events.length;index+=1){const event=events[index];if(!event||!eventTypes.has(event.type)||!event.id.trim()||event.aggregateVersion!==value.version||event.sequence!==index+1||!strictIsoTimestamp(event.occurredAt)||event.occurredAt!==value.updatedAt||typeof JSON.stringify(event.payload)!=="string")throw new CompanyDomainRepositoryContractError("Company event does not match aggregate persistence contract.");} }
  private async events(database: SqlDatabase, context: WorkspaceContext, value: Company, events: readonly CompanyEvent[]): Promise<void> { for(const event of events)await database.execute("INSERT INTO company_events (id,company_id,workspace_id,event_type,aggregate_version,event_sequence,occurred_at,actor_id,payload_json) VALUES (?,?,?,?,?,?,?,?,?)",[event.id,value.id,context.workspaceId,event.type,event.aggregateVersion,event.sequence,event.occurredAt,event.actorId,JSON.stringify(event.payload)]); }
  private async findOn(database: SqlDatabase, context: WorkspaceContext, id: CompanyId): Promise<Company|null> { const rows=await database.query<Row>(`SELECT ${columns} FROM companies WHERE workspace_id=? AND id=?`,[context.workspaceId,id]);return rows[0]?company(rows[0]):null; }
}

/** Async bridge for legacy Company callers during the production persistence migration. */
export class AsyncCompanyRepository implements AsyncCompanyRepositoryPort {
  public constructor(private readonly database: SqlDatabase) {}
  public async findById(context: WorkspaceContext, companyId: number): Promise<LegacyCompany | null> { return this.find(context, "id=?", [companyId]); }
  public async findByWebsite(context: WorkspaceContext, website: string): Promise<LegacyCompany | null> { return this.find(context, "website=?", [website]); }
  public async list(context: WorkspaceContext): Promise<LegacyCompany[]> { return (await this.database.query<LegacyRow>("SELECT id,workspace_id,name,website,phone,email,status,created_at FROM companies WHERE workspace_id=? ORDER BY id DESC", [context.workspaceId])).map(legacyCompany); }
  public async create(context: WorkspaceContext, input: CompanyCreateInput): Promise<LegacyCompany> {
    const timestamp = new Date().toISOString();
    return this.database.transaction(async database => {
      const result = await database.execute("INSERT INTO companies (workspace_id,name,name_normalized,slug,website,phone,email,status,lifecycle_state,version,created_at,updated_at,lifecycle_changed_at) VALUES (?,?,?,?,?,?,?,?, 'draft',1,?,?,?)", [context.workspaceId,input.name,normalizeCompanyName(input.name),`legacy-${randomUUID().replaceAll("-","")}`,input.website ?? null,input.phone ?? "",input.email ?? "",input.status ?? "processing",timestamp,timestamp,timestamp]);
      const company = await this.findOn(database, context, Number(result.lastInsertRowid));
      if (!company) throw new Error("Company could not be created.");
      await database.execute("INSERT INTO company_events (id,company_id,workspace_id,event_type,aggregate_version,event_sequence,occurred_at,actor_id,payload_json) VALUES (?,?,?,?,?,1,?,NULL,?)", [`legacy-${randomUUID()}`,company.id,context.workspaceId,"CompanyCreated",1,timestamp,JSON.stringify({ status: input.status ?? "processing" })]);
      return company;
    });
  }
  public async update(context: WorkspaceContext, companyId: number, input: CompanyPersistenceInput): Promise<LegacyCompany | null> { return this.write(context, companyId, "name=?,name_normalized=?,website=?,phone=?,email=?,status=?", [input.name,normalizeCompanyName(input.name),input.website,input.phone,input.email,input.status], "CompanyUpdated", { area: "legacy_update" }); }
  public async delete(context: WorkspaceContext, companyId: number): Promise<boolean> { return Number((await this.database.execute("DELETE FROM companies WHERE workspace_id=? AND id=?", [context.workspaceId,companyId])).rowsAffected) > 0; }
  public async updateStatus(context: WorkspaceContext, companyId: number, status: CompanyStatus): Promise<LegacyCompany | null> { return this.write(context, companyId, "status=?", [status], "CompanyUpdated", { area: "legacy_status" }); }
  private async find(context: WorkspaceContext, condition: string, values: readonly (string | number)[]): Promise<LegacyCompany | null> { const rows=await this.database.query<LegacyRow>(`SELECT id,workspace_id,name,website,phone,email,status,created_at FROM companies WHERE workspace_id=? AND ${condition}`,[context.workspaceId,...values]);return rows[0] ? legacyCompany(rows[0]) : null; }
  private async findOn(database: SqlDatabase, context: WorkspaceContext, companyId: number): Promise<LegacyCompany | null> { const rows=await database.query<LegacyRow>("SELECT id,workspace_id,name,website,phone,email,status,created_at FROM companies WHERE workspace_id=? AND id=?",[context.workspaceId,companyId]);return rows[0] ? legacyCompany(rows[0]) : null; }
  private async write(context: WorkspaceContext, companyId: number, set: string, values: readonly (string | null)[], eventType: "CompanyUpdated", payload: Readonly<Record<string,string>>): Promise<LegacyCompany | null> { return this.database.transaction(async database => { const rows=await database.query<{version:unknown}>("SELECT version FROM companies WHERE workspace_id=? AND id=?",[context.workspaceId,companyId]);if(!rows[0])return null;const version=Number(rows[0].version)+1,timestamp=new Date().toISOString(),result=await database.execute(`UPDATE companies SET ${set},version=?,updated_at=? WHERE workspace_id=? AND id=? AND version=?`,[...values,version,timestamp,context.workspaceId,companyId,version-1]);if(Number(result.rowsAffected)!==1)return null;await database.execute("INSERT INTO company_events (id,company_id,workspace_id,event_type,aggregate_version,event_sequence,occurred_at,actor_id,payload_json) VALUES (?,?,?,?,?,1,?,NULL,?)",[`legacy-${randomUUID()}`,companyId,context.workspaceId,eventType,version,timestamp,JSON.stringify(payload)]);return this.findOn(database,context,companyId); }); }
}

interface LegacyRow extends Record<string, unknown> { readonly id: number; readonly workspace_id: number; readonly name: string; readonly website: string | null; readonly phone: string; readonly email: string; readonly status: CompanyStatus; readonly created_at: string; }
function legacyCompany(row: LegacyRow): LegacyCompany { return { id:row.id,workspaceId:row.workspace_id,name:row.name,website:row.website,phone:row.phone,email:row.email,status:row.status,createdAt:row.created_at }; }
