import { BillingOperationRepository, type RecoveryClaim } from "../../repositories/billingOperationRepository.js";
import type { BillingProviderRegistry } from "../application/billingProviderRegistry.js";

const minute=60_000, stripeCheckoutRecoveryWindow=23*60*60*1000, maximumProviderTimeout=60_000, staleMargin=60_000;
export const billingOperationRecoveryStaleMilliseconds=maximumProviderTimeout+staleMargin;
export class BillingOperationRecoveryWorker {
  public constructor(private readonly operations:BillingOperationRepository,private readonly providers:BillingProviderRegistry,private readonly now:()=>string=()=>new Date().toISOString(),private readonly leaseMilliseconds=60_000){}
  public async runNext(owner="billing-operation-recovery"):Promise<"no_work"|"succeeded"|"failed"|"retry"|"lost_lease">{const now=this.now(),claim=this.operations.claimRecovery(owner,now,new Date(new Date(now).getTime()-billingOperationRecoveryStaleMilliseconds).toISOString(),new Date(new Date(now).getTime()+this.leaseMilliseconds).toISOString());if(!claim)return"no_work";const operation=claim.operation,provider=this.providers.get(operation.providerKind);if(!provider?.recoverOperation)return this.retry(claim,"recovery_unsupported");if(operation.kind==="checkout_session_create"&&operation.providerKind==="stripe"&&operation.requestStartedAt&&new Date(now).getTime()-new Date(operation.requestStartedAt).getTime()>stripeCheckoutRecoveryWindow){this.operations.releaseRecoveryWindowExpired(claim,now);return"retry";}const target=this.operations.targetProviderReference(operation),catalogReference=operation.kind==="checkout_session_create"?this.operations.checkoutProviderReference(operation):null;if(operation.kind==="checkout_session_create"&&!catalogReference)return this.retry(claim,"catalog_provider_mismatch");if(operation.kind!=="checkout_session_create"&&!target)return this.retry(claim,"invalid_target");const result=await provider.recoverOperation({kind:operation.kind,idempotencyKey:operation.providerIdempotencyKey,catalogReference:catalogReference??undefined,successTarget:operation.successTarget??undefined,cancelTarget:operation.cancelTarget??undefined,correlationToken:operation.recoveryCorrelationToken??undefined,subscriptionReference:target??undefined});if(result.kind==="success"){const safe=JSON.stringify({providerObjectId:result.providerObjectId,...(result.redirectUrl?{redirectUrl:result.redirectUrl}:{})}),settled=operation.kind==="checkout_session_create"?this.operations.succeedRecoveredCheckout(claim,result.providerObjectId,safe,now):this.operations.succeedRecovered(claim,result.providerObjectId,safe,now);return settled?"succeeded":"lost_lease";}if(result.kind==="failed")return this.operations.retryRecovery(claim,new Date(new Date(now).getTime()+minute).toISOString(),result.code,now)?"failed":"lost_lease";return this.retry(claim,"uncertain");}
  public async runBatch(limit=25,ownerPrefix="billing-operation-recovery"):Promise<readonly string[]>{const values:string[]=[];for(let index=0;index<Math.min(limit,25);index++){const result=await this.runNext(`${ownerPrefix}-${index}`);if(result==="no_work")break;values.push(result);}return values;}
  private retry(claim:RecoveryClaim,code:string):"retry"|"lost_lease"{const now=this.now(),next=new Date(new Date(now).getTime()+Math.min(60,2**Math.max(0,claim.attemptCount-1))*minute).toISOString();return this.operations.retryRecovery(claim,next,code,now)?"retry":"lost_lease";}
}
