import type { WhatsAppConnectionProviderValidationPort, WhatsAppConnectionProviderValidationResult } from "../application/ports.js";

export interface WhatsAppCloudApiPort { sendText(phoneNumberId: string, recipientWaId: string, text: string): Promise<string>; }
export class WhatsAppCloudApiError extends Error {
  public constructor(readonly status: number | null, readonly retryAfterMilliseconds: number | null) { super("WhatsApp delivery failed."); }
}
type ValidationFailureCode = "invalid_credentials" | "insufficient_permissions" | "phone_number_not_found" | "business_account_mismatch" | "rate_limited" | "provider_unavailable" | "provider_timeout" | "provider_rejected";
type SanitizedMetaError = { readonly message: string | null; readonly type: string | null; readonly code: number | null; readonly error_subcode: number | null; readonly fbtrace_id: string | null; };
type ValidationDiagnostic = { readonly event: "whatsapp_provider_validation"; readonly operation: "validate_connection"; readonly graphApiVersion: string; readonly httpStatus: number | null; readonly providerCode: number | null; readonly providerSubcode: number | null; readonly errorType: string | null; readonly transient: boolean | null; readonly error: SanitizedMetaError | null; readonly timestamp: string; };
export class WhatsAppCloudApiProvider implements WhatsAppCloudApiPort, WhatsAppConnectionProviderValidationPort {
  public constructor(private readonly accessToken: string, private readonly graphVersion: string, private readonly fetcher: typeof fetch = fetch, private readonly diagnostics: (value: ValidationDiagnostic) => void = value => console.info(JSON.stringify(value))) {}
  public async sendText(phoneNumberId: string, recipientWaId: string, text: string): Promise<string> { try { const response=await this.fetcher(`https://graph.facebook.com/${this.graphVersion}/${encodeURIComponent(phoneNumberId)}/messages`,{method:"POST",headers:{authorization:`Bearer ${this.accessToken}`,"content-type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:recipientWaId,type:"text",text:{body:text}})}); if(!response.ok)throw new WhatsAppCloudApiError(response.status,retryAfterMilliseconds(response.headers.get("retry-after"))); const body=await response.json() as {messages?:Array<{id?:unknown}>}; const id=body.messages?.[0]?.id; if(typeof id!=="string"||!id)throw new WhatsAppCloudApiError(null,null); return id; } catch(error:unknown) { if(error instanceof WhatsAppCloudApiError)throw error; throw new WhatsAppCloudApiError(null,null); } }
  public async validateConnection(input: { accessToken: string; phoneNumberId: string; whatsappBusinessAccountId: string }): Promise<WhatsAppConnectionProviderValidationResult> {
    try {
      const response = await this.fetcher(`https://graph.facebook.com/${this.graphVersion}/${encodeURIComponent(input.whatsappBusinessAccountId)}/phone_numbers?fields=id`, { headers: { authorization: `Bearer ${input.accessToken}` } });
      if (!response.ok) return this.failure(response);
      const body = await response.json() as { data?: Array<{ id?: unknown }> };
      return body.data?.some((phoneNumber) => phoneNumber.id === input.phoneNumberId) ? { status: "valid" } : { status: "invalid", failureCode: "business_account_mismatch" };
    } catch (error: unknown) { const code: ValidationFailureCode = error instanceof DOMException && error.name === "AbortError" ? "provider_timeout" : "provider_unavailable"; this.log(null, null, null, null, null, null); return { status: "invalid", failureCode: code }; }
  }
  private async failure(response: Response): Promise<{ status: "invalid"; failureCode: ValidationFailureCode }> { const error = await metaError(response), code = classify(response.status, error.code, error.type); this.log(response.status, error.code, error.subcode, error.type, error.transient, { message: error.message, type: error.type, code: error.code, error_subcode: error.subcode, fbtrace_id: error.fbtraceId }); return { status: "invalid", failureCode: code }; }
  private log(httpStatus: number | null, providerCode: number | null, providerSubcode: number | null, errorType: string | null, transient: boolean | null, error: SanitizedMetaError | null): void { this.diagnostics({ event: "whatsapp_provider_validation", operation: "validate_connection", graphApiVersion: this.graphVersion, httpStatus, providerCode, providerSubcode, errorType, transient, error, timestamp: new Date().toISOString() }); }
}

async function metaError(response: Response): Promise<{ code: number | null; subcode: number | null; type: string | null; transient: boolean | null; message: string | null; fbtraceId: string | null }> { try { const body = await response.json() as { error?: { code?: unknown; error_subcode?: unknown; type?: unknown; is_transient?: unknown; message?: unknown; fbtrace_id?: unknown } }, error = body.error; return { code: typeof error?.code === "number" ? error.code : null, subcode: typeof error?.error_subcode === "number" ? error.error_subcode : null, type: typeof error?.type === "string" ? error.type : null, transient: typeof error?.is_transient === "boolean" ? error.is_transient : null, message: typeof error?.message === "string" ? sanitizeMetaMessage(error.message) : null, fbtraceId: typeof error?.fbtrace_id === "string" ? error.fbtrace_id : null }; } catch { return { code: null, subcode: null, type: null, transient: null, message: null, fbtraceId: null }; } }
function sanitizeMetaMessage(value: string): string { return value.slice(0, 1_000).replace(/\b(?:access_token|authorization)\s*[=:]\s*(?:Bearer\s+)?[^\s,]+/gi, "$1=[REDACTED]"); }
function classify(status: number, _providerCode: number | null, _errorType: string | null): ValidationFailureCode { if (status === 401) return "invalid_credentials"; if (status === 403) return "insufficient_permissions"; if (status === 404) return "phone_number_not_found"; if (status === 429) return "rate_limited"; if (status === 408 || status === 504) return "provider_timeout"; if (status >= 500) return "provider_unavailable"; return "provider_rejected"; }

function retryAfterMilliseconds(value: string | null): number | null { if (!value) return null; const seconds = Number(value); if (Number.isFinite(seconds) && seconds >= 0) return Math.round(seconds * 1_000); const at = Date.parse(value); return Number.isFinite(at) ? Math.max(0, at - Date.now()) : null; }
