import type { WhatsAppConnectionProviderValidationPort, WhatsAppConnectionProviderValidationResult } from "../application/ports.js";

export interface WhatsAppCloudApiPort { sendText(phoneNumberId: string, recipientWaId: string, text: string): Promise<string>; }
type SanitizedOutboundReason = "outside_test_recipient_set" | "recipient_not_in_allowed_list" | "customer_service_window_closed" | "unsupported_message_type" | "phone_number_not_registered" | "permission_denied" | "rate_limited" | "provider_rejected";
export type WhatsAppOutboundFailureDiagnostic = { readonly graphApiVersion: string | null; readonly httpStatus: number | null; readonly providerCode: number | null; readonly providerSubcode: number | null; readonly errorType: string | null; readonly transient: boolean | null; readonly sanitizedDetailsCategory: "recipient_not_allowed" | "outside_test_recipient_set" | "unsupported_message" | "phone_number_not_registered" | "permission_denied" | "rate_limited" | "provider_rejected"; readonly sanitizedReason: SanitizedOutboundReason; };
export class WhatsAppCloudApiError extends Error {
  public constructor(readonly status: number | null, readonly retryAfterMilliseconds: number | null, readonly diagnostic: WhatsAppOutboundFailureDiagnostic | null = null) { super("WhatsApp delivery failed."); }
}
type ValidationFailureCode = "invalid_credentials" | "insufficient_permissions" | "phone_number_not_found" | "business_account_mismatch" | "rate_limited" | "provider_unavailable" | "provider_timeout" | "provider_rejected";
type SanitizedMetaError = { readonly message: string | null; readonly type: string | null; readonly code: number | null; readonly error_subcode: number | null; readonly fbtrace_id: string | null; };
type ValidationDiagnostic = { readonly event: "whatsapp_provider_validation"; readonly operation: "validate_connection"; readonly graphApiVersion: string; readonly httpStatus: number | null; readonly providerCode: number | null; readonly providerSubcode: number | null; readonly errorType: string | null; readonly transient: boolean | null; readonly error: SanitizedMetaError | null; readonly timestamp: string; };
export class WhatsAppCloudApiProvider implements WhatsAppCloudApiPort, WhatsAppConnectionProviderValidationPort {
  public constructor(private readonly accessToken: string, private readonly graphVersion: string, private readonly fetcher: typeof fetch = fetch, private readonly diagnostics: (value: ValidationDiagnostic) => void = value => console.info(JSON.stringify(value))) {}
  public async sendText(phoneNumberId: string, recipientWaId: string, text: string): Promise<string> { try { const response=await this.fetcher(`https://graph.facebook.com/${this.graphVersion}/${encodeURIComponent(phoneNumberId)}/messages`,{method:"POST",headers:{authorization:`Bearer ${this.accessToken}`,"content-type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:recipientWaId,type:"text",text:{body:text}})}); if(!response.ok) { const error=await metaError(response); throw new WhatsAppCloudApiError(response.status,retryAfterMilliseconds(response.headers.get("retry-after")),outboundDiagnostic(this.graphVersion,response.status,error)); } const body=await response.json() as {messages?:Array<{id?:unknown}>}; const id=body.messages?.[0]?.id; if(typeof id!=="string"||!id)throw new WhatsAppCloudApiError(null,null,outboundDiagnostic(this.graphVersion,null,emptyMetaError)); return id; } catch(error:unknown) { if(error instanceof WhatsAppCloudApiError)throw error; throw new WhatsAppCloudApiError(null,null,outboundDiagnostic(this.graphVersion,null,emptyMetaError)); } }
  public async validateConnection(input: { accessToken: string; phoneNumberId: string; whatsappBusinessAccountId: string }): Promise<WhatsAppConnectionProviderValidationResult> {
    try {
      const response = await this.fetcher(`https://graph.facebook.com/${this.graphVersion}/${encodeURIComponent(input.whatsappBusinessAccountId)}/phone_numbers?fields=id`, { headers: { authorization: `Bearer ${input.accessToken}` } });
      if (!response.ok) return this.failure(response);
      const body = await response.json() as { data?: Array<{ id?: unknown }> };
      return body.data?.some((phoneNumber) => phoneNumber.id === input.phoneNumberId) ? { status: "valid" } : { status: "invalid", failureCode: "business_account_mismatch" };
    } catch (error: unknown) { const code: ValidationFailureCode = error instanceof DOMException && error.name === "AbortError" ? "provider_timeout" : "provider_unavailable"; this.log(null, null, null, null, null, null); return { status: "invalid", failureCode: code }; }
  }
  private async failure(response: Response): Promise<{ status: "invalid"; failureCode: ValidationFailureCode }> { const error = await metaError(response), code = classify(response.status, error.code, error.type); this.log(response.status, error.code, error.subcode, error.type, error.transient, { message: error.message, type: error.type, code: error.code, error_subcode: error.subcode, fbtrace_id: error.fbtraceId }); return { status: "invalid", failureCode: code }; }
  private log(httpStatus: number | null, providerCode: number | null, providerSubcode: number | null, errorType: string | null, transient: boolean | null, error: SanitizedMetaError | null): void { this.diagnostics({ event: "whatsapp_provider_validation", operation: "validate_connection", graphApiVersion: this.graphVersion, httpStatus, providerCode, providerSubcode, errorType, transient, error, timestamp: new Date().toISOString() }); }
}

type MetaError = { readonly code: number | null; readonly subcode: number | null; readonly type: string | null; readonly transient: boolean | null; readonly message: string | null; readonly details: string | null; readonly fbtraceId: string | null; };
const emptyMetaError: MetaError = { code: null, subcode: null, type: null, transient: null, message: null, details: null, fbtraceId: null };
async function metaError(response: Response): Promise<MetaError> { try { const body = await response.json() as { error?: { code?: unknown; error_subcode?: unknown; type?: unknown; is_transient?: unknown; message?: unknown; error_data?: { details?: unknown }; fbtrace_id?: unknown } }, error = body.error; return { code: typeof error?.code === "number" ? error.code : null, subcode: typeof error?.error_subcode === "number" ? error.error_subcode : null, type: typeof error?.type === "string" ? error.type : null, transient: typeof error?.is_transient === "boolean" ? error.is_transient : null, message: typeof error?.message === "string" ? sanitizeMetaMessage(error.message) : null, details: typeof error?.error_data?.details === "string" ? error.error_data.details : null, fbtraceId: typeof error?.fbtrace_id === "string" ? error.fbtrace_id : null }; } catch { return emptyMetaError; } }
function outboundDiagnostic(graphApiVersion: string, httpStatus: number | null, error: MetaError): WhatsAppOutboundFailureDiagnostic { const sanitizedDetailsCategory = detailsCategory(httpStatus, error.code, error.details); return { graphApiVersion, httpStatus, providerCode: error.code, providerSubcode: error.subcode, errorType: error.type, transient: error.transient, sanitizedDetailsCategory, sanitizedReason: reason(error.code, error.details, sanitizedDetailsCategory) }; }
function detailsCategory(status: number | null, code: number | null, details: string | null): WhatsAppOutboundFailureDiagnostic["sanitizedDetailsCategory"] { const value = details?.toLowerCase() ?? ""; if (code === 131030) return "outside_test_recipient_set"; if (status === 429) return "rate_limited"; if (status === 401 || status === 403) return "permission_denied"; if (/test.{0,40}(recipient|number)|(recipient|number).{0,40}test/.test(value)) return "outside_test_recipient_set"; if (/recipient.{0,40}(allow|permission)|not allowed.{0,40}recipient/.test(value)) return "recipient_not_allowed"; if (/(phone number|number).{0,40}(not registered|unregistered)|not registered.{0,40}(phone number|number)/.test(value)) return "phone_number_not_registered"; if (/unsupported.{0,40}(message|type)|template.{0,40}(required|message)|message.{0,40}(unsupported|type)/.test(value)) return "unsupported_message"; return "provider_rejected"; }
function reason(code: number | null, details: string | null, category: WhatsAppOutboundFailureDiagnostic["sanitizedDetailsCategory"]): SanitizedOutboundReason { const value = details?.toLowerCase() ?? ""; if (code === 131030) return "recipient_not_in_allowed_list"; if (/customer service window|24.?hour/.test(value)) return "customer_service_window_closed"; if (category === "outside_test_recipient_set") return "outside_test_recipient_set"; if (category === "unsupported_message") return "unsupported_message_type"; return category === "recipient_not_allowed" ? "recipient_not_in_allowed_list" : category; }
function sanitizeMetaMessage(value: string): string { return value.slice(0, 1_000).replace(/\b(?:access_token|authorization)\s*[=:]\s*(?:Bearer\s+)?[^\s,]+/gi, "$1=[REDACTED]"); }
function classify(status: number, _providerCode: number | null, _errorType: string | null): ValidationFailureCode { if (status === 401) return "invalid_credentials"; if (status === 403) return "insufficient_permissions"; if (status === 404) return "phone_number_not_found"; if (status === 429) return "rate_limited"; if (status === 408 || status === 504) return "provider_timeout"; if (status >= 500) return "provider_unavailable"; return "provider_rejected"; }

function retryAfterMilliseconds(value: string | null): number | null { if (!value) return null; const seconds = Number(value); if (Number.isFinite(seconds) && seconds >= 0) return Math.round(seconds * 1_000); const at = Date.parse(value); return Number.isFinite(at) ? Math.max(0, at - Date.now()) : null; }
