import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import type { ActivationVerificationAttempt } from "../application/ports.js";

type Row={id:string;workspace_id:number;company_id:number;web_chat_connection_id:string;token_digest:string;status:ActivationVerificationAttempt["status"];created_at:string;expires_at:string;claimed_at:string|null;web_chat_session_id:string|null;conversation_id:string|null;inbound_message_id:string|null;execution_record_id:string|null;outcome_ref:ActivationVerificationAttempt["outcomeRef"];completed_at:string|null;failure_code:ActivationVerificationAttempt["failureCode"]};
const attempt=(row:Row):ActivationVerificationAttempt=>Object.freeze({id:row.id,workspaceId:row.workspace_id,companyId:row.company_id,webChatConnectionId:row.web_chat_connection_id,tokenDigest:row.token_digest,status:row.status,createdAt:row.created_at,expiresAt:row.expires_at,claimedAt:row.claimed_at,webChatSessionId:row.web_chat_session_id,conversationId:row.conversation_id,inboundMessageId:row.inbound_message_id,executionRecordId:row.execution_record_id,outcomeRef:row.outcome_ref,completedAt:row.completed_at,failureCode:row.failure_code});

export class AsyncActivationVerificationSettlementPersistence {
  public constructor(private readonly database:SqlDatabase) {}
  public async create(context:WorkspaceContext,value:ActivationVerificationAttempt):Promise<ActivationVerificationAttempt>{const result=await this.database.execute("INSERT INTO activation_verification_attempts(id,workspace_id,company_id,web_chat_connection_id,token_digest,status,created_at,expires_at,claimed_at,web_chat_session_id,conversation_id,inbound_message_id,execution_record_id,outcome_ref,completed_at,failure_code) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM web_chat_connections WHERE id=? AND workspace_id=? AND company_id=?)",[value.id,value.workspaceId,value.companyId,value.webChatConnectionId,value.tokenDigest,value.status,value.createdAt,value.expiresAt,value.claimedAt,value.webChatSessionId,value.conversationId,value.inboundMessageId,value.executionRecordId,value.outcomeRef,value.completedAt,value.failureCode,value.webChatConnectionId,context.workspaceId,value.companyId]);if(Number(result.rowsAffected)!==1)throw new Error("Activation verification scope is invalid.");return value;}
  public async findClaimableByTokenDigest(tokenDigest:string):Promise<ActivationVerificationAttempt|null>{const rows=await this.database.query<Row>("SELECT * FROM activation_verification_attempts WHERE token_digest=? AND status='pending' AND claimed_at IS NULL",[tokenDigest]);return rows[0]?attempt(rows[0]):null;}
  public async claim(id:string,sessionId:string,conversationId:string,at:string):Promise<ActivationVerificationAttempt|null>{const result=await this.database.execute("UPDATE activation_verification_attempts SET claimed_at=?,web_chat_session_id=?,conversation_id=? WHERE id=? AND status='pending' AND claimed_at IS NULL",[at,sessionId,conversationId,id]);return Number(result.rowsAffected)===1?this.findById(id):null;}
  public async succeedForTurn(sessionId:string,conversationId:string,inboundMessageId:string,executionRecordId:string,outcomeRef:"answered"|"safe_fallback",at:string):Promise<ActivationVerificationAttempt|null>{const result=await this.database.execute("UPDATE activation_verification_attempts SET status='succeeded',inbound_message_id=?,execution_record_id=?,outcome_ref=?,completed_at=? WHERE web_chat_session_id=? AND conversation_id=? AND status='pending' AND claimed_at IS NOT NULL",[inboundMessageId,executionRecordId,outcomeRef,at,sessionId,conversationId]);return Number(result.rowsAffected)===1?this.findBySession(sessionId,conversationId):null;}
  public async failForSession(sessionId:string,conversationId:string,at:string):Promise<ActivationVerificationAttempt|null>{const result=await this.database.execute("UPDATE activation_verification_attempts SET status='failed',completed_at=?,failure_code='runtime_failure' WHERE web_chat_session_id=? AND conversation_id=? AND status='pending' AND claimed_at IS NOT NULL",[at,sessionId,conversationId]);return Number(result.rowsAffected)===1?this.findBySession(sessionId,conversationId):null;}
  private async findById(id:string):Promise<ActivationVerificationAttempt|null>{const rows=await this.database.query<Row>("SELECT * FROM activation_verification_attempts WHERE id=?",[id]);return rows[0]?attempt(rows[0]):null;}
  private async findBySession(sessionId:string,conversationId:string):Promise<ActivationVerificationAttempt|null>{const rows=await this.database.query<Row>("SELECT * FROM activation_verification_attempts WHERE web_chat_session_id=? AND conversation_id=?",[sessionId,conversationId]);return rows[0]?attempt(rows[0]):null;}
}
