import assert from "node:assert/strict";
import test from "node:test";
import { ApiError } from "../api/atlasApi.ts";
import { assistantResourceReducer, initialAssistantResourceState, type AssistantScope } from "./assistantResourceState.ts";

const first: AssistantScope = { workspaceId: "w1", companyId: 1, assistantProfileId: "a1" };
const second: AssistantScope = { workspaceId: "w2", companyId: 2, assistantProfileId: "a2" };
test("assistant resources isolate workspace company and assistant scopes from stale responses",()=>{let state=assistantResourceReducer(initialAssistantResourceState<string>(),{type:"scopeChanged",scope:first}),generation=state.generation;state=assistantResourceReducer(state,{type:"loadStarted",generation});state=assistantResourceReducer(state,{type:"scopeChanged",scope:second});state=assistantResourceReducer(state,{type:"loaded",generation,value:"stale"});assert.deepEqual(state.scope,second);assert.equal(state.status,"idle");});
test("assistant resource failures map safely and retain confirmed values",()=>{let state=assistantResourceReducer(initialAssistantResourceState<string>(),{type:"scopeChanged",scope:first});state=assistantResourceReducer(state,{type:"loaded",generation:state.generation,value:"confirmed"});state=assistantResourceReducer(state,{type:"mutationStarted",mutation:"default"});state=assistantResourceReducer(state,{type:"mutationFailed",mutation:"default",error:new ApiError(409,"raw")});assert.equal(state.status,"conflict");assert.equal(state.value,"confirmed");state=assistantResourceReducer(state,{type:"mutationStarted",mutation:"retry"});state=assistantResourceReducer(state,{type:"mutationFailed",mutation:"retry",error:new ApiError(429,"raw","rate_limited",30)});assert.equal(state.status,"unavailable");assert.equal(state.retryAfterSeconds,30);for(const [status,expected] of [[400,"error"],[404,"not_found"],[403,"forbidden"],[503,"unavailable"]] as const){const next=assistantResourceReducer(state,{type:"failed",generation:state.generation,error:new ApiError(status,"raw")});assert.equal(next.status,expected);}});
test("assistant resources block duplicate mutations and replace only confirmed state",()=>{let state=assistantResourceReducer(initialAssistantResourceState<string>(),{type:"scopeChanged",scope:first});state=assistantResourceReducer(state,{type:"loaded",generation:state.generation,value:"old"});state=assistantResourceReducer(state,{type:"mutationStarted",mutation:"update"});assert.equal(assistantResourceReducer(state,{type:"mutationStarted",mutation:"duplicate"}).pendingMutation,"update");state=assistantResourceReducer(state,{type:"mutationConfirmed",mutation:"update",value:"new"});assert.equal(state.value,"new");assert.equal(state.pendingMutation,null);});
