import type { BillingOperationKind } from "../domain/billingOperations.js";
import type { BillingSubscriptionEvidence } from "../domain/effectiveSubscriptionMapper.js";

export interface BillingProviderCapabilities { readonly subscriptionCheckout:boolean; readonly requiresPayerEmailForCheckout:boolean; readonly supportsNativeCancelAtPeriodEnd:boolean; readonly supportsNativeReactivateCancelAtPeriodEnd:boolean; readonly supportsCustomerPortal:boolean; readonly supportsDistinctCheckoutCancelTarget:boolean; readonly providerCreateIdempotency:"documented"|"not_documented"; }
export const stripeBillingProviderCapabilities:BillingProviderCapabilities=Object.freeze({subscriptionCheckout:true,requiresPayerEmailForCheckout:false,supportsNativeCancelAtPeriodEnd:true,supportsNativeReactivateCancelAtPeriodEnd:true,supportsCustomerPortal:true,supportsDistinctCheckoutCancelTarget:true,providerCreateIdempotency:"documented"});
export const mercadoPagoBillingProviderCapabilities:BillingProviderCapabilities=Object.freeze({subscriptionCheckout:true,requiresPayerEmailForCheckout:true,supportsNativeCancelAtPeriodEnd:false,supportsNativeReactivateCancelAtPeriodEnd:false,supportsCustomerPortal:false,supportsDistinctCheckoutCancelTarget:false,providerCreateIdempotency:"not_documented"});
export type BillingProviderResult={readonly kind:"success";readonly providerObjectId:string;readonly redirectUrl?:string}|{readonly kind:"failed";readonly code:"unavailable"|"invalid_request"}|{readonly kind:"uncertain"};
export type BillingSubscriptionReadResult={readonly kind:"success";readonly evidence:BillingSubscriptionEvidence}|{readonly kind:"not_found"}|{readonly kind:"failed";readonly code:"unavailable"|"invalid_request"}|{readonly kind:"uncertain"};
export type BillingCommercialOfferValidation={readonly kind:"ready"}|{readonly kind:"invalid"}|{readonly kind:"unavailable"};
export interface BillingProvider { readonly capabilities:BillingProviderCapabilities; createCheckoutSession(input:{readonly idempotencyKey:string;readonly catalogReference:string;readonly successTarget:string;readonly cancelTarget:string;readonly correlationToken?:string|undefined;readonly payerEmail?:string}):Promise<BillingProviderResult>; createPortalSession(input:{readonly billingAccountReference:string;readonly returnTarget:string}):Promise<BillingProviderResult>; cancelAtPeriodEnd(input:{readonly idempotencyKey:string;readonly subscriptionReference:string}):Promise<BillingProviderResult>; reactivateSubscription(input:{readonly idempotencyKey:string;readonly subscriptionReference:string}):Promise<BillingProviderResult>; readSubscription(input:{readonly subscriptionReference:string}):Promise<BillingSubscriptionReadResult>; recoverOperation?(input:{readonly kind:BillingOperationKind;readonly idempotencyKey:string;readonly catalogReference?:string|undefined;readonly successTarget?:string|undefined;readonly cancelTarget?:string|undefined;readonly correlationToken?:string|undefined;readonly subscriptionReference?:string|undefined}):Promise<BillingProviderResult>; validateCommercialOffer?(input:{readonly catalogReference:string;readonly currency:string;readonly amountMinor:number;readonly interval:"month"|"year"}):Promise<BillingCommercialOfferValidation>; }
export class DeterministicFakeBillingProvider implements BillingProvider { public readonly calls:Array<{readonly kind:BillingOperationKind|"portal";readonly idempotencyKey:string|null;readonly payerEmail?:string}>=[]; public constructor(private readonly result:BillingProviderResult={kind:"success",providerObjectId:"fake_object"},public readonly capabilities:BillingProviderCapabilities=stripeBillingProviderCapabilities,private readonly readResult:BillingSubscriptionReadResult={kind:"uncertain"},private readonly validation:BillingCommercialOfferValidation={kind:"ready"}){} private call(kind:BillingOperationKind|"portal",key:string|null,payerEmail?:string):Promise<BillingProviderResult>{this.calls.push({kind,idempotencyKey:key,...(payerEmail?{payerEmail}:{})});return Promise.resolve(this.result);} public createCheckoutSession(value:Parameters<BillingProvider["createCheckoutSession"]>[0]){return this.call("checkout_session_create",value.idempotencyKey,value.payerEmail);} public createPortalSession(_value:Parameters<BillingProvider["createPortalSession"]>[0]){return this.call("portal",null);} public cancelAtPeriodEnd(value:Parameters<BillingProvider["cancelAtPeriodEnd"]>[0]){return this.call("subscription_cancel_at_period_end",value.idempotencyKey);} public reactivateSubscription(value:Parameters<BillingProvider["reactivateSubscription"]>[0]){return this.call("subscription_reactivate",value.idempotencyKey);} public readSubscription(_value:Parameters<BillingProvider["readSubscription"]>[0]):Promise<BillingSubscriptionReadResult>{return Promise.resolve(this.readResult);} public validateCommercialOffer(_value:Parameters<NonNullable<BillingProvider["validateCommercialOffer"]>>[0]):Promise<BillingCommercialOfferValidation>{return Promise.resolve(this.validation);} }
