import type { AsyncBillingCustomerReadRepository, AsyncBillingPayerIdentityRepository } from "../infrastructure/asyncBillingCustomerPersistence.js";
import type { BillingAccount } from "../../repositories/billingRepository.js";
export type BillingPayerIdentityMutationOutcome={readonly kind:"succeeded";readonly account:BillingAccount;readonly changed:boolean}|{readonly kind:"invalid"|"not_found"|"conflict"};
export class BillingPayerIdentityService {
  public constructor(private readonly customer:AsyncBillingCustomerReadRepository,private readonly identities:AsyncBillingPayerIdentityRepository,private readonly now:()=>string){}
  public async optionsForWorkspace(input:Readonly<{workspaceId:number;callerIdentityId:string}>):Promise<readonly Readonly<{identityId:string;email:string}>[]|null>{return await this.customer.account(input.workspaceId)?this.identities.options(input.workspaceId,input.callerIdentityId):null;}
  public async setOwnedForWorkspace(input:Readonly<{workspaceId:number;callerIdentityId:string;identityId:string;expectedVersion:number}>):Promise<BillingPayerIdentityMutationOutcome>{const before=await this.customer.account(input.workspaceId);if(!before)return{kind:"not_found"};const result=await this.identities.setOwned(input.workspaceId,input.callerIdentityId,input.identityId,input.expectedVersion,this.now());if(result!=="succeeded")return{kind:result==="not_found"?"not_found":result};const after=(await this.customer.account(input.workspaceId))!;return{kind:"succeeded",account:after,changed:after.version!==before.version};}
  public async clearOwnedForWorkspace(input:Readonly<{workspaceId:number;callerIdentityId:string;identityId:string;expectedVersion:number}>):Promise<BillingPayerIdentityMutationOutcome>{const before=await this.customer.account(input.workspaceId);if(!before)return{kind:"not_found"};const result=await this.identities.clearOwned(input.workspaceId,input.callerIdentityId,input.identityId,input.expectedVersion,this.now());if(result!=="succeeded")return{kind:result==="not_found"?"not_found":result};const after=(await this.customer.account(input.workspaceId))!;return{kind:"succeeded",account:after,changed:after.version!==before.version};}
}
