import { createHash } from "node:crypto";
import type { AsyncBillingCustomerReadRepository, AsyncBillingPayerIdentityRepository } from "../infrastructure/asyncBillingCustomerPersistence.js";
import { BillingOperationService, type BillingOperationOutcome } from "./billingOperationService.js";
export type BillingCapabilitiesDto=Readonly<{canOpenBillingPortal:boolean;canCancel:boolean;canReactivate:boolean;canStartNewCheckout:boolean;canSwitchProvider:false}>;
export type BillingEntitlementsDto=Readonly<{state:string;maxCompanies:number|null;maxAssistantProfiles:number|null;maxActiveChannels:number|null;mutationEligible:boolean;effectiveAt:string;expiresAt:string|null}>;
export class BillingApplicationService {
  public constructor(private readonly customer:AsyncBillingCustomerReadRepository,private readonly payers:AsyncBillingPayerIdentityRepository,private readonly operations:BillingOperationService,private readonly targets:Readonly<{checkoutSuccess:string;checkoutCancel:string;portalReturn:string}>,private readonly now:()=>string=()=>new Date().toISOString()){}
  public async summary(workspaceId:number):Promise<unknown|null>{const account=await this.customer.account(workspaceId);if(!account)return null;const sub=await this.customer.subscription(account.id),entry=sub?.catalogEntryId?await this.customer.entry(sub.catalogEntryId):null,offer=sub?.providerCommercialOfferId?await this.customer.offer(sub.providerCommercialOfferId):null;return Object.freeze({rolloutMode:account.rolloutMode,subscription:Object.freeze({state:sub?.effectiveState??"unmanaged",plan:entry&&offer?Object.freeze({key:entry.planKey,name:entry.displayName,interval:offer.interval,currency:offer.currency,amountMinor:offer.amountMinor}):null})});}
  public async customerSummary(workspaceId:number):Promise<unknown|null>{const account=await this.customer.account(workspaceId),summary=await this.summary(workspaceId);if(!account||!summary)return null;const [value,offers]=await Promise.all([this.customer.entitlement(account.id),this.allOffers()]);return Object.freeze({...summary,entitlement:value?Object.freeze({state:value.state,maxCompanies:value.maxCompanies,maxAssistantProfiles:value.maxAssistantProfiles,maxActiveChannels:value.maxActiveChannels,mutationEligible:value.mutationEligible,effectiveAt:value.effectiveAt,expiresAt:value.expiresAt}):null,capabilities:await this.operations.managementCapabilities(workspaceId,offers)});}
  public async entitlementsFor(workspaceId:number):Promise<BillingEntitlementsDto|null>{const account=await this.customer.account(workspaceId),value=account?await this.customer.entitlement(account.id):null;return value?Object.freeze({state:value.state,maxCompanies:value.maxCompanies,maxAssistantProfiles:value.maxAssistantProfiles,maxActiveChannels:value.maxActiveChannels,mutationEligible:value.mutationEligible,effectiveAt:value.effectiveAt,expiresAt:value.expiresAt}):null;}
  public async catalogForWorkspace(workspaceId:number):Promise<unknown|null>{if(!await this.customer.account(workspaceId))return null;const entries=await this.customer.published(),values=await Promise.all(entries.map(async entry=>(await this.customer.sellableOffers(entry.id)).map(offer=>Object.freeze({id:entry.id,providerCommercialOfferId:offer.id,key:entry.planKey,version:entry.catalogVersion,name:entry.displayName,interval:offer.interval,currency:offer.currency,amountMinor:offer.amountMinor}))));return Object.freeze({entries:Object.freeze(values.flat())});}
  public async offersForWorkspace(workspaceId:number):Promise<unknown|null>{if(!await this.customer.account(workspaceId))return null;const entries=await this.customer.published(),groups=await Promise.all(entries.map(async entry=>{const [inclusions,offers]=await Promise.all([this.customer.inclusions(entry.id),this.customer.sellableOffers(entry.id)]);return Promise.all(offers.map(async offer=>Object.freeze({offerId:offer.id,provider:offer.providerKind,key:entry.planKey,version:entry.catalogVersion,name:entry.displayName,description:entry.description,inclusions,interval:offer.interval,currency:offer.currency,amountMinor:offer.amountMinor,checkoutAvailable:(await this.operations.managementCapabilities(workspaceId,[offer])).canStartNewCheckout})));}));return Object.freeze({offers:Object.freeze(groups.flat())});}
  public async managementActionsFor(workspaceId:number):Promise<unknown|null>{if(!await this.customer.account(workspaceId))return null;const offers=await this.allOffers();return Object.freeze({actions:await this.operations.supportedManagementActions(workspaceId),capabilities:await this.operations.managementCapabilities(workspaceId,offers)});}
  public async payerIdentityOptionsFor(workspaceId:number,callerId:string):Promise<unknown|null>{const account=await this.customer.account(workspaceId);if(!account)return null;const options=await this.payers.options(workspaceId,callerId),selected=options.find(option=>option.identityId===account.billingPayerIdentityId);return Object.freeze({options,...(selected?{selectedEmail:selected.email}:{})});}
  public async setPayerIdentity(workspaceId:number,callerId:string,identityId:string):Promise<Readonly<{status:"succeeded"|"conflict"|"invalid"}>>{const account=await this.customer.account(workspaceId);if(!account)return{status:"invalid"};const result=await this.payers.setOwned(workspaceId,callerId,identityId,account.version,this.now());return Object.freeze({status:result==="succeeded"?"succeeded":result==="conflict"?"conflict":"invalid"});}
  public async clearPayerIdentity(workspaceId:number,callerId:string,identityId:string):Promise<Readonly<{status:"succeeded"|"conflict"|"invalid"}>>{const account=await this.customer.account(workspaceId);if(!account)return{status:"invalid"};const result=await this.payers.clearOwned(workspaceId,callerId,identityId,account.version,this.now());return Object.freeze({status:result==="succeeded"?"succeeded":result==="conflict"?"conflict":"invalid"});}
  public async checkout(workspaceId:number,entryId:string,offerId:string,key:string):Promise<Readonly<{status:string;redirectUrl?:string}>>{return dto(await this.operations.checkout({workspaceId,catalogEntryId:entryId,providerCommercialOfferId:offerId,operationId:id("checkout",key),successTarget:this.targets.checkoutSuccess,cancelTarget:this.targets.checkoutCancel}));}
  public async checkoutOffer(workspaceId:number,offerId:string,key:string):Promise<Readonly<{status:string;redirectUrl?:string}>>{const offer=await this.customer.offer(offerId);return offer?this.checkout(workspaceId,offer.catalogEntryId,offer.id,key):{status:"invalid"};}
  public async portal(workspaceId:number):Promise<Readonly<{status:string;redirectUrl?:string}>>{const result=await this.operations.portal({workspaceId,returnTarget:this.targets.portalReturn});return result.kind==="succeeded"?Object.freeze({status:"succeeded",...(result.result.kind==="success"&&result.result.redirectUrl?{redirectUrl:result.result.redirectUrl}:{})}):Object.freeze({status:result.kind});}
  public async cancel(workspaceId:number,key:string):Promise<Readonly<{status:string}>>{return this.subscriptionMutation(workspaceId,key,"cancel");} public async reactivate(workspaceId:number,key:string):Promise<Readonly<{status:string}>>{return this.subscriptionMutation(workspaceId,key,"reactivate");}
  private async subscriptionMutation(workspaceId:number,key:string,kind:"cancel"|"reactivate"):Promise<Readonly<{status:string}>>{const account=await this.customer.account(workspaceId),sub=account?await this.customer.subscription(account.id):null;if(!sub)return{status:"invalid"};const result=kind==="cancel"?await this.operations.cancelAtPeriodEnd({workspaceId,subscriptionId:sub.id,operationId:id(kind,key)}):await this.operations.reactivate({workspaceId,subscriptionId:sub.id,operationId:id(kind,key)});return{status:result.kind};}
  private async allOffers(){return (await Promise.all((await this.customer.published()).map(entry=>this.customer.sellableOffers(entry.id)))).flat();}
}
const id=(kind:string,key:string):string=>`http_${kind}_${createHash("sha256").update(key).digest("hex")}`;
const dto=(result:BillingOperationOutcome):Readonly<{status:string;redirectUrl?:string}>=>{if(result.kind!=="succeeded")return{status:result.kind};try{const value=JSON.parse(result.operation?.safeResultJson??"{}") as {redirectUrl?:unknown};return Object.freeze({status:"succeeded",...(typeof value.redirectUrl==="string"?{redirectUrl:value.redirectUrl}:{})});}catch{return{status:"succeeded"};}};
