import type { SynchronousDatabase } from "../../config/synchronousDatabase.js";
import { BillingAccountRepository, type BillingAccount } from "../../repositories/billingRepository.js";

export type BillingPayerIdentityMutationOutcome={readonly kind:"succeeded";readonly account:BillingAccount;readonly changed:boolean}|{readonly kind:"invalid"|"not_found"|"conflict"};
export class BillingPayerIdentityService {
  private readonly accounts:BillingAccountRepository;
  public constructor(private readonly db:SynchronousDatabase,private readonly now:()=>string){this.accounts=new BillingAccountRepository(db);}
  public optionsForWorkspace(input:{readonly workspaceId:number;readonly callerIdentityId:string}):readonly Readonly<{identityId:string;email:string}>[]|null { if(!this.accounts.findByWorkspace(input.workspaceId))return null;return Object.freeze((this.db.prepare("SELECT i.id identityId,i.email email FROM authentication_identities caller JOIN authentication_identities i ON i.user_id=caller.user_id JOIN memberships m ON m.user_id=i.user_id AND m.workspace_id=? AND m.status='active' WHERE caller.id=? AND i.email_verified=1 AND length(i.email) BETWEEN 3 AND 320 AND length(i.normalized_email) BETWEEN 3 AND 320 ORDER BY i.id").all(input.workspaceId,input.callerIdentityId) as readonly {identityId:string;email:string}[]).map(identity=>Object.freeze({identityId:identity.identityId,email:identity.email}))); }
  public setOwnedForWorkspace(input:{readonly workspaceId:number;readonly callerIdentityId:string;readonly identityId:string;readonly expectedVersion:number}):BillingPayerIdentityMutationOutcome { const account=this.accounts.findByWorkspace(input.workspaceId);if(!account)return{kind:"not_found"};if(account.version!==input.expectedVersion)return{kind:"conflict"};if(account.billingPayerIdentityId===input.identityId)return{kind:"succeeded",account,changed:false};const identity=this.db.prepare("SELECT i.id FROM authentication_identities caller JOIN authentication_identities i ON i.user_id=caller.user_id JOIN memberships m ON m.user_id=i.user_id AND m.workspace_id=? AND m.status='active' WHERE caller.id=? AND i.id=? AND i.email_verified=1 AND length(i.email) BETWEEN 3 AND 320 AND length(i.normalized_email) BETWEEN 3 AND 320").get(input.workspaceId,input.callerIdentityId,input.identityId);if(!identity)return{kind:"invalid"};const updated=this.accounts.setPayerIdentity(account.id,input.identityId,input.expectedVersion,this.now());return updated?{kind:"succeeded",account:updated,changed:true}:{kind:"conflict"}; }
  public clearOwnedForWorkspace(input:{readonly workspaceId:number;readonly callerIdentityId:string;readonly identityId:string;readonly expectedVersion:number}):BillingPayerIdentityMutationOutcome { const account=this.accounts.findByWorkspace(input.workspaceId);if(!account)return{kind:"not_found"};if(account.version!==input.expectedVersion)return{kind:"conflict"};if(account.billingPayerIdentityId!==input.identityId)return{kind:"invalid"};const owned=this.db.prepare("SELECT 1 FROM authentication_identities caller JOIN authentication_identities selected ON selected.user_id=caller.user_id WHERE caller.id=? AND selected.id=?").get(input.callerIdentityId,input.identityId);if(!owned)return{kind:"invalid"};const updated=this.accounts.clearPayerIdentity(account.id,input.expectedVersion,this.now());return updated?{kind:"succeeded",account:updated,changed:true}:{kind:"conflict"}; }
  public setForWorkspace(input:{readonly workspaceId:number;readonly identityId:string;readonly expectedVersion:number}):BillingPayerIdentityMutationOutcome { const account=this.accounts.findByWorkspace(input.workspaceId);if(!account)return{kind:"not_found"};if(account.version!==input.expectedVersion)return{kind:"conflict"};if(account.billingPayerIdentityId===input.identityId)return{kind:"succeeded",account,changed:false};const identity=this.db.prepare("SELECT i.id FROM authentication_identities i JOIN memberships m ON m.user_id=i.user_id AND m.workspace_id=? AND m.status='active' WHERE i.id=? AND i.email_verified=1 AND length(i.email) BETWEEN 3 AND 320 AND length(i.normalized_email) BETWEEN 3 AND 320").get(input.workspaceId,input.identityId);if(!identity)return this.db.prepare("SELECT 1 FROM authentication_identities WHERE id=?").get(input.identityId)?{kind:"invalid"}:{kind:"not_found"};const updated=this.accounts.setPayerIdentity(account.id,input.identityId,input.expectedVersion,this.now());return updated?{kind:"succeeded",account:updated,changed:true}:{kind:"conflict"}; }
  public clearForWorkspace(input:{readonly workspaceId:number;readonly expectedVersion:number}):BillingPayerIdentityMutationOutcome { const account=this.accounts.findByWorkspace(input.workspaceId);if(!account)return{kind:"not_found"};if(account.version!==input.expectedVersion)return{kind:"conflict"};if(account.billingPayerIdentityId===null)return{kind:"succeeded",account,changed:false};const updated=this.accounts.clearPayerIdentity(account.id,input.expectedVersion,this.now());return updated?{kind:"succeeded",account:updated,changed:true}:{kind:"conflict"}; }
}
