import { billingOperationFingerprint, type BillingOperationKind } from "../domain/billingOperations.js";
import type { BillingProviderKind } from "../domain/billing.js";
import { BillingAccountRepository, BillingCatalogRepository, BillingSubscriptionRepository } from "../../repositories/billingRepository.js";
import { BillingOperationRepository, OpenCheckoutEnrollmentConflictError, type BillingOperation } from "../../repositories/billingOperationRepository.js";
import { BillingProviderRegistry } from "./billingProviderRegistry.js";
import type { BillingPayerIdentityResolver } from "./billingPayerIdentityResolver.js";

export type BillingOperationOutcome={readonly kind:"succeeded"|"failed"|"uncertain"|"in_progress"|"conflict"|"invalid"|"unsupported"|"unavailable";readonly operation?:BillingOperation};
export type BillingPortalOutcome={readonly kind:"succeeded";readonly result:import("./billingProvider.js").BillingProviderResult}|Readonly<{readonly kind:"failed"|"uncertain"|"invalid"|"unsupported"|"unavailable"}>;
type CheckoutInput={readonly workspaceId:number;readonly catalogEntryId:string;readonly providerCommercialOfferId?:string;readonly operationId:string;readonly successTarget:string;readonly cancelTarget:string};type SubscriptionInput={readonly workspaceId:number;readonly operationId:string;readonly subscriptionId:string};
export class BillingOperationService {
  public constructor(private readonly accounts:BillingAccountRepository,private readonly catalog:BillingCatalogRepository,private readonly subscriptions:BillingSubscriptionRepository,private readonly operations:BillingOperationRepository,private readonly providers:BillingProviderRegistry,private readonly now:()=>string,private readonly payerResolver:BillingPayerIdentityResolver|null=null){}
  public checkout(input:CheckoutInput):Promise<BillingOperationOutcome>{const account=this.accounts.findByWorkspace(input.workspaceId),entry=this.catalog.find(input.catalogEntryId),offer=input.providerCommercialOfferId?this.catalog.offer(input.providerCommercialOfferId):entry?.legacyProviderKind?this.catalog.sellableOffers(entry.id).find(candidate=>candidate.providerKind===entry.legacyProviderKind)??null:null,kind=offer?.providerKind;if(!account||!entry||entry.publicationState!=="published"||!offer||offer.catalogEntryId!==entry.id||offer.lifecycle!=="sellable"||offer.readinessState!=="ready"||!kind||(account.providerKind&&account.providerKind!==kind))return Promise.resolve({kind:"invalid"});const provider=this.providers.get(kind);if(!provider)return Promise.resolve({kind:"unavailable"});if(!provider.capabilities.subscriptionCheckout)return Promise.resolve({kind:"unsupported"});const payer=provider.capabilities.requiresPayerEmailForCheckout?this.payerResolver?.resolveForBillingAccount(account.id)??null:null;if(provider.capabilities.requiresPayerEmailForCheckout&&!payer)return Promise.resolve({kind:"invalid"});const replay=this.operations.find(account.id,"checkout_session_create",input.operationId);if(!replay&&this.operations.hasOpenCheckoutEnrollment(account.id))return Promise.resolve({kind:"conflict"});return this.execute(account.id,"checkout_session_create",kind,input.operationId,billingOperationFingerprint({billingAccountId:account.id,operationKind:"checkout_session_create",catalogEntryId:entry.id,...(input.providerCommercialOfferId?{providerCommercialOfferId:offer.id}:{}),providerKind:kind,redirectTarget:input.successTarget,cancelTarget:input.cancelTarget}),operation=>provider.createCheckoutSession({idempotencyKey:operation.providerIdempotencyKey,catalogReference:offer.providerPlanReference,successTarget:input.successTarget,cancelTarget:input.cancelTarget,correlationToken:operation.recoveryCorrelationToken??undefined,...(payer?{payerEmail:payer.email}:{})}),entry.id,{catalogEntryId:entry.id,providerCommercialOfferId:offer.id,successTarget:input.successTarget,cancelTarget:input.cancelTarget});}
  public cancelAtPeriodEnd(input:SubscriptionInput):Promise<BillingOperationOutcome>{return this.subscription(input,"subscription_cancel_at_period_end",["trial","active","grace"]);}public reactivate(input:SubscriptionInput):Promise<BillingOperationOutcome>{return this.subscription(input,"subscription_reactivate",["canceling_at_period_end"]);}
  public async portal(input:{readonly workspaceId:number;readonly returnTarget:string}):Promise<BillingPortalOutcome>{const account=this.accounts.findByWorkspace(input.workspaceId),kind=account?.providerKind;if(!account||account.rolloutMode!=="managed"||!kind||!account.providerCustomerId)return{kind:"invalid"};const provider=this.providers.get(kind);if(!provider)return{kind:"unavailable"};if(!provider.capabilities.supportsCustomerPortal)return{kind:"unsupported"};const result=await provider.createPortalSession({billingAccountReference:account.providerCustomerId,returnTarget:input.returnTarget});return result.kind==="success"?{kind:"succeeded",result}:result.kind==="failed"?{kind:"failed"}:{kind:"uncertain"};}
  private subscription(input:SubscriptionInput,operationKind:Extract<BillingOperationKind,"subscription_cancel_at_period_end"|"subscription_reactivate">,states:readonly string[]):Promise<BillingOperationOutcome>{const account=this.accounts.findByWorkspace(input.workspaceId),sub=account&&this.subscriptions.current(account.id),kind=sub?.providerKind;if(!account||!sub||sub.id!==input.subscriptionId||!kind||!sub.providerSubscriptionId||!states.includes(sub.effectiveState)||(account.providerKind&&account.providerKind!==kind))return Promise.resolve({kind:"invalid"});const provider=this.providers.get(kind);if(!provider)return Promise.resolve({kind:"unavailable"});if(operationKind==="subscription_cancel_at_period_end"&&!provider.capabilities.supportsNativeCancelAtPeriodEnd)return Promise.resolve({kind:"unsupported"});if(operationKind==="subscription_reactivate"&&!provider.capabilities.supportsNativeReactivateCancelAtPeriodEnd)return Promise.resolve({kind:"unsupported"});return this.execute(account.id,operationKind,kind,input.operationId,billingOperationFingerprint({billingAccountId:account.id,operationKind,subscriptionId:sub.id,providerKind:kind}),operation=>operationKind==="subscription_cancel_at_period_end"?provider.cancelAtPeriodEnd({idempotencyKey:operation.providerIdempotencyKey,subscriptionReference:sub.providerSubscriptionId!}):provider.reactivateSubscription({idempotencyKey:operation.providerIdempotencyKey,subscriptionReference:sub.providerSubscriptionId!}),undefined,{targetSubscriptionId:sub.id});}
  private async execute(accountId:string,kind:BillingOperationKind,providerKind:BillingProviderKind,operationId:string,fingerprint:string,call:(operation:BillingOperation)=>Promise<import("./billingProvider.js").BillingProviderResult>,catalogEntryId?:string,context:Readonly<{catalogEntryId?:string;providerCommercialOfferId?:string;successTarget?:string;cancelTarget?:string;targetSubscriptionId?:string}>={}):Promise<BillingOperationOutcome>{const replay=this.operations.createOrReplay({billingAccountId:accountId,kind,providerKind,operationId,fingerprint,at:this.now(),...context});if(replay.kind==="conflict")return{kind:"conflict"};const operation=replay.operation!;if(operation.status==="succeeded")return{kind:"succeeded",operation};if(operation.status==="failed")return{kind:"failed",operation};if(operation.status==="uncertain")return{kind:"uncertain",operation};if(operation.status==="request_started")return{kind:"in_progress",operation:this.operations.find(accountId,kind,operationId)!};const started=this.operations.start(operation.id,operation.version,this.now());if(!started)return{kind:"in_progress",operation:this.operations.find(accountId,kind,operationId)!};const result=await call(started);if(result.kind==="success"){const safe=JSON.stringify({providerObjectId:result.providerObjectId,...(result.redirectUrl?{redirectUrl:result.redirectUrl}:{})});try{const settled=catalogEntryId?this.operations.succeedCheckout(started.id,started.version,result.providerObjectId,safe,catalogEntryId,this.now()):this.operations.succeed(started.id,started.version,result.providerObjectId,safe,this.now());return settled?{kind:"succeeded",operation:settled}:{kind:"uncertain",operation:this.operations.find(accountId,kind,operationId)!};}catch(error){if(error instanceof OpenCheckoutEnrollmentConflictError)return{kind:"conflict"};throw error;}}if(result.kind==="failed"){const settled=this.operations.fail(started.id,started.version,result.code,this.now());return settled?{kind:"failed",operation:settled}:{kind:"uncertain",operation:this.operations.find(accountId,kind,operationId)!};}const settled=this.operations.uncertain(started.id,started.version,this.now());return settled?{kind:"uncertain",operation:settled}:{kind:"uncertain",operation:this.operations.find(accountId,kind,operationId)!};}
}
