import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import { assistantProfileId } from "../../assistant/domain/assistantProfile.js";
import { reconstructWebChatConnection, type WebChatConnection, type WebChatConnectionId, type WebChatConnectionPublicId, type WebChatConnectionStatus } from "../domain/webChatConnection.js";
import { reconstructWebChatSession, type WebChatSession, type WebChatSessionId, type WebChatSessionState } from "../domain/webChatSession.js";
import { conversationId, conversationParticipantId } from "../../conversation/domain/conversation.js";
import { webChatConnectionId } from "../domain/webChatConnection.js";
import type { WebChatConnectionRepositoryPort } from "../application/ports.js";
import type { PublicWebChatTurnClaim, PublicWebChatTurnRepositoryPort, WebChatSessionRepositoryPort } from "../application/sessionPorts.js";

type ConnectionRow={id:string;public_id:string;workspace_id:number;company_id:number;assistant_profile_id:string;status:WebChatConnectionStatus;created_at:string;updated_at:string};
type SessionRow={id:string;web_chat_connection_id:string;conversation_id:string;visitor_participant_id:string;responder_participant_id:string;token_digest:string;state:WebChatSessionState;created_at:string;updated_at:string;expires_at:string;last_seen_at:string};
const connection=(row:ConnectionRow):WebChatConnection=>reconstructWebChatConnection({id:row.id as WebChatConnectionId,publicId:row.public_id as WebChatConnectionPublicId,workspaceId:row.workspace_id,companyId:row.company_id,assistantProfileId:assistantProfileId(row.assistant_profile_id),status:row.status,createdAt:row.created_at,updatedAt:row.updated_at});
const session=(row:SessionRow):WebChatSession=>reconstructWebChatSession({id:row.id as WebChatSessionId,webChatConnectionId:webChatConnectionId(row.web_chat_connection_id),conversationId:conversationId(row.conversation_id),visitorParticipantId:conversationParticipantId(row.visitor_participant_id),responderParticipantId:conversationParticipantId(row.responder_participant_id),tokenDigest:row.token_digest,state:row.state,createdAt:row.created_at,updatedAt:row.updated_at,expiresAt:row.expires_at,lastSeenAt:row.last_seen_at});

export class AsyncWebChatConnectionPersistence implements WebChatConnectionRepositoryPort {
  public constructor(private readonly database:SqlDatabase) {}
  public async create(context:WorkspaceContext,value:WebChatConnection):Promise<WebChatConnection|null>{const result=await this.database.execute("INSERT INTO web_chat_connections(id,public_id,workspace_id,company_id,assistant_profile_id,status,created_at,updated_at) SELECT ?,?,?,c.id,p.id,?,?,? FROM companies c JOIN assistant_profiles p ON p.id=? AND p.company_id=c.id WHERE c.workspace_id=? AND c.id=?",[value.id,value.publicId,value.workspaceId,value.status,value.createdAt,value.updatedAt,value.assistantProfileId,context.workspaceId,value.companyId]);return Number(result.rowsAffected)===1?this.findById(context,value.companyId,value.id):null;}
  public async findById(context:WorkspaceContext,companyId:number,id:WebChatConnectionId):Promise<WebChatConnection|null>{const rows=await this.database.query<ConnectionRow>("SELECT w.* FROM web_chat_connections w JOIN companies c ON c.id=w.company_id WHERE w.workspace_id=? AND c.workspace_id=? AND w.company_id=? AND w.id=?",[context.workspaceId,context.workspaceId,companyId,id]);return rows[0]?connection(rows[0]):null;}
  public async listByCompany(context:WorkspaceContext,companyId:number):Promise<WebChatConnection[]>{return (await this.database.query<ConnectionRow>("SELECT w.* FROM web_chat_connections w JOIN companies c ON c.id=w.company_id WHERE w.workspace_id=? AND c.workspace_id=? AND w.company_id=? ORDER BY w.created_at DESC,w.id DESC",[context.workspaceId,context.workspaceId,companyId])).map(connection);}
  public async findActiveByPublicId(publicId:WebChatConnectionPublicId):Promise<WebChatConnection|null>{const rows=await this.database.query<ConnectionRow>(`SELECT w.* FROM web_chat_connections w JOIN workspaces ws ON ws.id=w.workspace_id ${await this.commercialJoin()} JOIN companies c ON c.id=w.company_id AND c.workspace_id=ws.id AND c.lifecycle_state!='archived' JOIN assistant_profiles p ON p.id=w.assistant_profile_id AND p.company_id=c.id AND p.status!='archived' WHERE w.public_id=? AND w.status='active'`,[publicId]);return rows[0]?connection(rows[0]):null;}
  public async findActiveById(id:WebChatConnectionId):Promise<WebChatConnection|null>{const rows=await this.database.query<ConnectionRow>(`SELECT w.* FROM web_chat_connections w JOIN workspaces ws ON ws.id=w.workspace_id ${await this.commercialJoin()} JOIN companies c ON c.id=w.company_id AND c.workspace_id=ws.id AND c.lifecycle_state!='archived' JOIN assistant_profiles p ON p.id=w.assistant_profile_id AND p.company_id=c.id AND p.status!='archived' WHERE w.id=? AND w.status='active'`,[id]);return rows[0]?connection(rows[0]):null;}
  public async updateStatus(context:WorkspaceContext,companyId:number,id:WebChatConnectionId,status:WebChatConnectionStatus,updatedAt:string):Promise<WebChatConnection|null>{const result=await this.database.execute("UPDATE web_chat_connections SET status=?,updated_at=? WHERE id=? AND company_id=? AND workspace_id=? AND company_id IN (SELECT id FROM companies WHERE workspace_id=?)",[status,updatedAt,id,companyId,context.workspaceId,context.workspaceId]);return Number(result.rowsAffected)===1?this.findById(context,companyId,id):null;}
  private async commercialJoin():Promise<string>{return (await this.database.query<{id:number}>("SELECT 1 id FROM sqlite_master WHERE type='table' AND name='workspace_commercial_controls'"))[0]?"JOIN workspace_commercial_controls cc ON cc.workspace_id=ws.id AND cc.status='active'":"";}
}

/** Public-session storage is intentionally separate from the synchronous public web-chat service. */
export class AsyncPublicWebChatSessionPersistence implements WebChatSessionRepositoryPort {
  public constructor(private readonly database:SqlDatabase) {}
  public async transaction<T>(operation:()=>Promise<T>):Promise<T>{return this.database.transaction(async()=>operation());}
  public async create(value:WebChatSession):Promise<WebChatSession>{await this.database.execute("INSERT INTO web_chat_sessions(id,web_chat_connection_id,conversation_id,visitor_participant_id,responder_participant_id,token_digest,state,created_at,updated_at,expires_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",[value.id,value.webChatConnectionId,value.conversationId,value.visitorParticipantId,value.responderParticipantId,value.tokenDigest,value.state,value.createdAt,value.updatedAt,value.expiresAt,value.lastSeenAt]);return value;}
  public async findByTokenDigest(digest:string):Promise<WebChatSession|null>{const rows=await this.database.query<SessionRow>("SELECT s.* FROM web_chat_sessions s JOIN web_chat_connections c ON c.id=s.web_chat_connection_id JOIN companies co ON co.id=c.company_id AND co.workspace_id=c.workspace_id JOIN assistant_profiles p ON p.id=c.assistant_profile_id AND p.company_id=co.id JOIN conversations v ON v.id=s.conversation_id AND v.company_id=co.id JOIN conversation_participants visitor ON visitor.id=s.visitor_participant_id AND visitor.conversation_id=v.id JOIN conversation_participants responder ON responder.id=s.responder_participant_id AND responder.conversation_id=v.id WHERE s.token_digest=?",[digest]);return rows[0]?session(rows[0]):null;}
  public async findForCloseByTokenDigest(digest:string,publicId:string):Promise<WebChatSession|null>{const rows=await this.database.query<SessionRow>("SELECT s.* FROM web_chat_sessions s JOIN web_chat_connections c ON c.id=s.web_chat_connection_id WHERE s.token_digest=? AND c.public_id=?",[digest,publicId]);return rows[0]?session(rows[0]):null;}
  public async updateState(id:WebChatSessionId,expectedState:"active",state:WebChatSessionState,updatedAt:string):Promise<WebChatSession|null>{const result=await this.database.execute("UPDATE web_chat_sessions SET state=?,updated_at=? WHERE id=? AND state=?",[state,updatedAt,id,expectedState]);return Number(result.rowsAffected)===1?this.findById(id):null;}
  public async updateLastSeen(id:WebChatSessionId,expectedState:"active",updatedAt:string,lastSeenAt:string):Promise<WebChatSession|null>{const result=await this.database.execute("UPDATE web_chat_sessions SET updated_at=?,last_seen_at=? WHERE id=? AND state=?",[updatedAt,lastSeenAt,id,expectedState]);return Number(result.rowsAffected)===1?this.findById(id):null;}
  private async findById(id:WebChatSessionId):Promise<WebChatSession|null>{const rows=await this.database.query<SessionRow>("SELECT * FROM web_chat_sessions WHERE id=?",[id]);return rows[0]?session(rows[0]):null;}
}

export class AsyncPublicWebChatTurnPersistence implements PublicWebChatTurnRepositoryPort {
  public constructor(private readonly database: SqlDatabase) {}
  public async claim(sessionId: string, idempotencyKeyDigest: string, contentDigest: string, createdAt: string): Promise<PublicWebChatTurnClaim> {
    return this.database.transaction(async (database) => {
      // A turn cannot outlive its session; opportunistically remove expired-session claims.
      await database.execute("DELETE FROM public_web_chat_turns WHERE web_chat_session_id IN (SELECT id FROM web_chat_sessions WHERE expires_at<=?)", [createdAt]);
      const inserted = await database.execute("INSERT INTO public_web_chat_turns(web_chat_session_id,idempotency_key_digest,content_digest,status,created_at,updated_at) VALUES(?,?,?,'pending',?,?) ON CONFLICT(web_chat_session_id,idempotency_key_digest) DO NOTHING", [sessionId, idempotencyKeyDigest, contentDigest, createdAt, createdAt]);
      if (Number(inserted.rowsAffected) === 1) return Object.freeze({ kind: "acquired" });
      const row = (await database.query<{ content_digest: string; status: "pending" | "succeeded" | "failed"; response_message: string | null }>("SELECT content_digest,status,response_message FROM public_web_chat_turns WHERE web_chat_session_id=? AND idempotency_key_digest=?", [sessionId, idempotencyKeyDigest]))[0];
      if (!row || row.content_digest !== contentDigest) return Object.freeze({ kind: "mismatch" });
      if (row.status === "succeeded" && row.response_message !== null) return Object.freeze({ kind: "succeeded", message: row.response_message });
      return Object.freeze({ kind: row.status === "failed" ? "failed" : "in_progress" });
    });
  }
  public async abandon(sessionId: string, idempotencyKeyDigest: string): Promise<void> { await this.database.execute("DELETE FROM public_web_chat_turns WHERE web_chat_session_id=? AND idempotency_key_digest=? AND status='pending' AND inbound_message_id IS NULL", [sessionId, idempotencyKeyDigest]); }
  public async succeed(sessionId: string, idempotencyKeyDigest: string, inboundMessageId: string, executionRecordId: string, message: string, completedAt: string): Promise<void> { await this.database.execute("UPDATE public_web_chat_turns SET status='succeeded',inbound_message_id=?,execution_record_id=?,response_message=?,completed_at=?,updated_at=? WHERE web_chat_session_id=? AND idempotency_key_digest=? AND status='pending'", [inboundMessageId, executionRecordId, message, completedAt, completedAt, sessionId, idempotencyKeyDigest]); }
  public async fail(sessionId: string, idempotencyKeyDigest: string, inboundMessageId: string | null, completedAt: string): Promise<void> { await this.database.execute("UPDATE public_web_chat_turns SET status='failed',inbound_message_id=?,completed_at=?,updated_at=? WHERE web_chat_session_id=? AND idempotency_key_digest=? AND status='pending'", [inboundMessageId, completedAt, completedAt, sessionId, idempotencyKeyDigest]); }
  public async requestHumanHandoff(workspaceId: number, companyId: number, conversationId: string, occurredAt: string): Promise<void> {
    await this.database.transaction(async (database) => {
      await database.execute("INSERT INTO conversation_controls(conversation_id,state,controlling_actor_id,last_controlling_actor_id,taken_at,released_at,last_operator_activity_at,attention_reason,resolved_at,resolved_by,version,created_at,updated_at) SELECT ?,'automated',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,?,? WHERE EXISTS(SELECT 1 FROM conversations c JOIN companies co ON co.id=c.company_id WHERE c.id=? AND c.company_id=? AND co.workspace_id=? AND c.state='open') ON CONFLICT(conversation_id) DO NOTHING", [conversationId, occurredAt, occurredAt, conversationId, companyId, workspaceId]);
      await database.execute("UPDATE conversation_controls SET state='human_required',version=version+1,updated_at=? WHERE conversation_id=? AND state='automated'", [occurredAt, conversationId]);
    });
  }
}
