import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import { assistantProfileId } from "../../assistant/domain/assistantProfile.js";
import { reconstructWebChatConnection, type WebChatConnection, type WebChatConnectionId, type WebChatConnectionPublicId, type WebChatConnectionStatus } from "../domain/webChatConnection.js";
import { reconstructWebChatSession, type WebChatSession, type WebChatSessionId, type WebChatSessionState } from "../domain/webChatSession.js";
import { conversationId, conversationParticipantId } from "../../conversation/domain/conversation.js";

type ConnectionRow={id:string;public_id:string;workspace_id:number;company_id:number;assistant_profile_id:string;status:WebChatConnectionStatus;created_at:string;updated_at:string};
type SessionRow={id:string;web_chat_connection_id:string;conversation_id:string;visitor_participant_id:string;responder_participant_id:string;token_digest:string;state:WebChatSessionState;created_at:string;updated_at:string;expires_at:string;last_seen_at:string};
const connection=(row:ConnectionRow):WebChatConnection=>reconstructWebChatConnection({id:row.id as WebChatConnectionId,publicId:row.public_id as WebChatConnectionPublicId,workspaceId:row.workspace_id,companyId:row.company_id,assistantProfileId:assistantProfileId(row.assistant_profile_id),status:row.status,createdAt:row.created_at,updatedAt:row.updated_at});
const session=(row:SessionRow):WebChatSession=>reconstructWebChatSession({id:row.id as WebChatSessionId,webChatConnectionId:row.web_chat_connection_id as WebChatConnectionId,conversationId:conversationId(row.conversation_id),visitorParticipantId:conversationParticipantId(row.visitor_participant_id),responderParticipantId:conversationParticipantId(row.responder_participant_id),tokenDigest:row.token_digest,state:row.state,createdAt:row.created_at,updatedAt:row.updated_at,expiresAt:row.expires_at,lastSeenAt:row.last_seen_at});

export class AsyncWebChatConnectionPersistence {
  public constructor(private readonly database:SqlDatabase) {}
  public async create(context:WorkspaceContext,value:WebChatConnection):Promise<WebChatConnection|null>{const result=await this.database.execute("INSERT INTO web_chat_connections(id,public_id,workspace_id,company_id,assistant_profile_id,status,created_at,updated_at) SELECT ?,?,?,c.id,p.id,?,?,? FROM companies c JOIN assistant_profiles p ON p.id=? AND p.company_id=c.id WHERE c.workspace_id=? AND c.id=?",[value.id,value.publicId,value.workspaceId,value.status,value.createdAt,value.updatedAt,value.assistantProfileId,context.workspaceId,value.companyId]);return Number(result.rowsAffected)===1?this.findById(context,value.companyId,value.id):null;}
  public async findById(context:WorkspaceContext,companyId:number,id:WebChatConnectionId):Promise<WebChatConnection|null>{const rows=await this.database.query<ConnectionRow>("SELECT w.* FROM web_chat_connections w JOIN companies c ON c.id=w.company_id WHERE w.workspace_id=? AND c.workspace_id=? AND w.company_id=? AND w.id=?",[context.workspaceId,context.workspaceId,companyId,id]);return rows[0]?connection(rows[0]):null;}
  public async findActiveByPublicId(publicId:WebChatConnectionPublicId):Promise<WebChatConnection|null>{const rows=await this.database.query<ConnectionRow>("SELECT w.* FROM web_chat_connections w JOIN companies c ON c.id=w.company_id JOIN assistant_profiles p ON p.id=w.assistant_profile_id AND p.company_id=c.id WHERE w.public_id=? AND w.status='active' AND c.lifecycle_state!='archived' AND p.status!='archived'",[publicId]);return rows[0]?connection(rows[0]):null;}
  public async updateStatus(context:WorkspaceContext,companyId:number,id:WebChatConnectionId,status:WebChatConnectionStatus,updatedAt:string):Promise<WebChatConnection|null>{const result=await this.database.execute("UPDATE web_chat_connections SET status=?,updated_at=? WHERE id=? AND company_id=? AND workspace_id=?",[status,updatedAt,id,companyId,context.workspaceId]);return Number(result.rowsAffected)===1?this.findById(context,companyId,id):null;}
}

/** Public-session storage is intentionally separate from the synchronous public web-chat service. */
export class AsyncPublicWebChatSessionPersistence {
  public constructor(private readonly database:SqlDatabase) {}
  public async create(value:WebChatSession):Promise<WebChatSession>{await this.database.execute("INSERT INTO web_chat_sessions(id,web_chat_connection_id,conversation_id,visitor_participant_id,responder_participant_id,token_digest,state,created_at,updated_at,expires_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",[value.id,value.webChatConnectionId,value.conversationId,value.visitorParticipantId,value.responderParticipantId,value.tokenDigest,value.state,value.createdAt,value.updatedAt,value.expiresAt,value.lastSeenAt]);return value;}
  public async findByTokenDigest(digest:string):Promise<WebChatSession|null>{const rows=await this.database.query<SessionRow>("SELECT s.* FROM web_chat_sessions s JOIN web_chat_connections c ON c.id=s.web_chat_connection_id JOIN companies co ON co.id=c.company_id AND co.workspace_id=c.workspace_id JOIN assistant_profiles p ON p.id=c.assistant_profile_id AND p.company_id=co.id JOIN conversations v ON v.id=s.conversation_id AND v.company_id=co.id JOIN conversation_participants visitor ON visitor.id=s.visitor_participant_id AND visitor.conversation_id=v.id JOIN conversation_participants responder ON responder.id=s.responder_participant_id AND responder.conversation_id=v.id WHERE s.token_digest=?",[digest]);return rows[0]?session(rows[0]):null;}
  public async findForCloseByTokenDigest(digest:string,publicId:string):Promise<WebChatSession|null>{const rows=await this.database.query<SessionRow>("SELECT s.* FROM web_chat_sessions s JOIN web_chat_connections c ON c.id=s.web_chat_connection_id WHERE s.token_digest=? AND c.public_id=?",[digest,publicId]);return rows[0]?session(rows[0]):null;}
  public async updateState(id:WebChatSessionId,expectedState:"active",state:WebChatSessionState,updatedAt:string):Promise<WebChatSession|null>{const result=await this.database.execute("UPDATE web_chat_sessions SET state=?,updated_at=? WHERE id=? AND state=?",[state,updatedAt,id,expectedState]);return Number(result.rowsAffected)===1?this.findById(id):null;}
  public async updateLastSeen(id:WebChatSessionId,expectedState:"active",updatedAt:string,lastSeenAt:string):Promise<WebChatSession|null>{const result=await this.database.execute("UPDATE web_chat_sessions SET updated_at=?,last_seen_at=? WHERE id=? AND state=?",[updatedAt,lastSeenAt,id,expectedState]);return Number(result.rowsAffected)===1?this.findById(id):null;}
  private async findById(id:WebChatSessionId):Promise<WebChatSession|null>{const rows=await this.database.query<SessionRow>("SELECT * FROM web_chat_sessions WHERE id=?",[id]);return rows[0]?session(rows[0]):null;}
}
