import { createHash, randomUUID } from "node:crypto";
import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { BillingProviderKind } from "../domain/billing.js";
import { billingProviderIdempotencyKey, type BillingOperationKind, type BillingOperationStatus } from "../domain/billingOperations.js";
import type { BillingAccount, BillingEntitlementSnapshot, BillingProviderCommercialOffer, BillingSubscription } from "../../repositories/billingRepository.js";
import type { BillingOperation } from "../../repositories/billingOperationRepository.js";

type Row = Record<string, unknown>;
const text = (row: Row, key: string): string | null => row[key] == null ? null : String(row[key]);
const account = (row: Row): BillingAccount => Object.freeze({ id:String(row.id), workspaceId:Number(row.workspace_id), rolloutMode:row.rollout_mode as BillingAccount["rolloutMode"], providerKind:text(row,"provider_kind") as BillingProviderKind|null, providerCustomerId:text(row,"provider_customer_id"), billingPayerIdentityId:text(row,"billing_payer_identity_id"), trialConsumedAt:text(row,"trial_consumed_at"), version:Number(row.version), createdAt:String(row.created_at), updatedAt:String(row.updated_at) });
const subscription = (row: Row): BillingSubscription => Object.freeze({ id:String(row.id), billingAccountId:String(row.billing_account_id), catalogEntryId:text(row,"catalog_entry_id"), providerCommercialOfferId:text(row,"provider_commercial_offer_id"), providerKind:text(row,"provider_kind") as BillingProviderKind|null, providerSubscriptionId:text(row,"provider_subscription_id"), providerEvidenceState:text(row,"provider_evidence_state") as BillingSubscription["providerEvidenceState"], effectiveState:row.effective_state as BillingSubscription["effectiveState"], version:Number(row.version), isCurrent:Number(row.is_current)===1, createdAt:String(row.created_at), updatedAt:String(row.updated_at) });
const offer = (row: Row): BillingProviderCommercialOffer => Object.freeze({ id:String(row.id), catalogEntryId:String(row.catalog_entry_id), providerKind:row.provider_kind as BillingProviderKind, offerVersion:Number(row.offer_version), currency:String(row.currency), amountMinor:Number(row.amount_minor), interval:row.billing_interval as BillingProviderCommercialOffer["interval"], providerPlanReference:String(row.provider_plan_reference), readinessState:row.readiness_state as BillingProviderCommercialOffer["readinessState"], lifecycle:row.lifecycle_state as BillingProviderCommercialOffer["lifecycle"], version:Number(row.version), createdAt:String(row.created_at), updatedAt:String(row.updated_at) });
const snapshot = (row: Row): BillingEntitlementSnapshot => Object.freeze({ id:String(row.id), billingAccountId:String(row.billing_account_id), billingSubscriptionId:String(row.billing_subscription_id), state:row.entitlement_state as BillingEntitlementSnapshot["state"], maxCompanies:row.max_companies===null?null:Number(row.max_companies), maxAssistantProfiles:row.max_assistant_profiles===null?null:Number(row.max_assistant_profiles), maxActiveChannels:row.max_active_channels===null?null:Number(row.max_active_channels), mutationEligible:Number(row.mutation_eligible)===1, version:Number(row.version), isCurrent:Number(row.is_current)===1, evaluatedAt:String(row.evaluated_at), effectiveAt:String(row.effective_at), expiresAt:text(row,"expires_at") });
const operation = (row: Row): BillingOperation => Object.freeze({ id:String(row.id), billingAccountId:String(row.billing_account_id), kind:row.operation_kind as BillingOperationKind, providerKind:row.provider_kind as BillingProviderKind, operationId:String(row.operation_id), fingerprint:String(row.request_fingerprint), providerIdempotencyKey:String(row.provider_idempotency_key), status:row.status as BillingOperationStatus, version:Number(row.version), providerObjectId:text(row,"provider_object_id"), safeResultJson:text(row,"safe_result_json"), catalogEntryId:text(row,"catalog_entry_id"), providerCommercialOfferId:text(row,"provider_commercial_offer_id"), successTarget:text(row,"success_target"), cancelTarget:text(row,"cancel_target"), targetSubscriptionId:text(row,"target_subscription_id"), recoveryCorrelationToken:text(row,"recovery_correlation_token"), requestStartedAt:text(row,"request_started_at"), recoveryNextAttemptAt:text(row,"recovery_next_attempt_at") });

export class AsyncBillingCustomerReadRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async account(workspaceId:number):Promise<BillingAccount|null>{const row=(await this.database.query<Row>("SELECT * FROM billing_accounts WHERE workspace_id=?",[workspaceId]))[0];return row?account(row):null;}
  public async subscription(accountId:string):Promise<BillingSubscription|null>{const row=(await this.database.query<Row>("SELECT * FROM billing_subscriptions WHERE billing_account_id=? AND is_current=1",[accountId]))[0];return row?subscription(row):null;}
  public async entitlement(accountId:string):Promise<BillingEntitlementSnapshot|null>{const row=(await this.database.query<Row>("SELECT * FROM billing_entitlement_snapshots WHERE billing_account_id=? AND is_current=1",[accountId]))[0];return row?snapshot(row):null;}
  public async entry(id:string):Promise<Readonly<{id:string;planKey:string;catalogVersion:number;displayName:string;description:string;publicationState:string}>|null>{const row=(await this.database.query<Row>("SELECT id,plan_key,catalog_version,display_name,description,publication_state FROM billing_catalog_entries WHERE id=?",[id]))[0];return row?Object.freeze({id:String(row.id),planKey:String(row.plan_key),catalogVersion:Number(row.catalog_version),displayName:String(row.display_name),description:String(row.description),publicationState:String(row.publication_state)}):null;}
  public async published():Promise<readonly Readonly<{id:string;planKey:string;catalogVersion:number;displayName:string;description:string}>[]>{return Object.freeze((await this.database.query<Row>("SELECT id,plan_key,catalog_version,display_name,description FROM billing_catalog_entries WHERE publication_state='published' ORDER BY plan_key,catalog_version")).map(row=>Object.freeze({id:String(row.id),planKey:String(row.plan_key),catalogVersion:Number(row.catalog_version),displayName:String(row.display_name),description:String(row.description)})));}
  public async sellableOffers(entryId:string):Promise<readonly BillingProviderCommercialOffer[]>{return Object.freeze((await this.database.query<Row>("SELECT * FROM billing_provider_commercial_offers WHERE catalog_entry_id=? AND lifecycle_state='sellable' AND readiness_state='ready' ORDER BY provider_kind,offer_version DESC",[entryId])).map(offer));}
  public async offer(id:string):Promise<BillingProviderCommercialOffer|null>{const row=(await this.database.query<Row>("SELECT * FROM billing_provider_commercial_offers WHERE id=?",[id]))[0];return row?offer(row):null;}
  public async inclusions(entryId:string):Promise<readonly Readonly<{code:string;title:string;description:string}>[]>{return Object.freeze((await this.database.query<Row>("SELECT inclusion_code AS code,display_title,display_description FROM billing_catalog_inclusions WHERE catalog_entry_id=? ORDER BY inclusion_code",[entryId])).map(row=>Object.freeze({code:String(row.code),title:String(row.display_title),description:String(row.display_description)})));}
}

export class AsyncBillingOperationRepository {
  public constructor(private readonly database:SqlDatabase) {}
  public async find(accountId:string,kind:BillingOperationKind,operationId:string):Promise<BillingOperation|null>{const row=(await this.database.query<Row>("SELECT * FROM billing_operations WHERE billing_account_id=? AND operation_kind=? AND operation_id=?",[accountId,kind,operationId]))[0];return row?operation(row):null;}
  public async hasOpenCheckoutEnrollment(accountId:string):Promise<boolean>{return (await this.database.query<Row>("SELECT 1 FROM billing_checkout_enrollments WHERE billing_account_id=? AND status IN ('pending','ready') LIMIT 1",[accountId])).length>0;}
  public async createOrReplay(input:Readonly<{billingAccountId:string;kind:BillingOperationKind;providerKind:BillingProviderKind;operationId:string;fingerprint:string;at:string;catalogEntryId?:string;providerCommercialOfferId?:string;successTarget?:string;cancelTarget?:string;targetSubscriptionId?:string}>):Promise<Readonly<{kind:"created"|"same"|"conflict";operation?:BillingOperation}>>{const same=(value:BillingOperation):boolean=>value.fingerprint===input.fingerprint&&value.providerKind===input.providerKind&&(value.providerCommercialOfferId===null||value.providerCommercialOfferId===(input.providerCommercialOfferId??null)),existing=await this.find(input.billingAccountId,input.kind,input.operationId);if(existing)return same(existing)?{kind:"same",operation:existing}:{kind:"conflict"};const correlation=input.kind==="checkout_session_create"?`aco_${createHash("sha256").update(`${input.billingAccountId}\n${input.operationId}`).digest("hex")}`:null;try{await this.database.execute("INSERT INTO billing_operations(id,billing_account_id,operation_kind,operation_id,request_fingerprint,provider_kind,provider_idempotency_key,status,catalog_entry_id,provider_commercial_offer_id,success_target,cancel_target,target_subscription_id,recovery_correlation_token,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'pending',?,?,?,?,?,?,?,?)",[`bop_${randomUUID().replaceAll("-","")}`,input.billingAccountId,input.kind,input.operationId,input.fingerprint,input.providerKind,billingProviderIdempotencyKey(input.billingAccountId,input.kind,input.operationId),input.catalogEntryId??null,input.providerCommercialOfferId??null,input.successTarget??null,input.cancelTarget??null,input.targetSubscriptionId??null,correlation,input.at,input.at]);}catch{const raced=await this.find(input.billingAccountId,input.kind,input.operationId);return raced&&same(raced)?{kind:"same",operation:raced}:{kind:"conflict"};}return{kind:"created",operation:(await this.find(input.billingAccountId,input.kind,input.operationId))!};}
  public async start(id:string,version:number,at:string):Promise<BillingOperation|null>{return this.transition(id,version,"pending","request_started",at,null,null,null);}
  public async succeed(id:string,version:number,objectId:string,safe:string|null,at:string):Promise<BillingOperation|null>{return this.transition(id,version,"request_started","succeeded",at,objectId,safe,null);}
  public async fail(id:string,version:number,code:string,at:string):Promise<BillingOperation|null>{return this.transition(id,version,"request_started","failed",at,null,null,code);}
  public async uncertain(id:string,version:number,at:string):Promise<BillingOperation|null>{const result=await this.database.execute("UPDATE billing_operations SET status='uncertain',recovery_next_attempt_at=?,recovery_safe_failure_code=NULL,version=version+1,updated_at=? WHERE id=? AND version=? AND status='request_started'",[at,at,id,version]);return Number(result.rowsAffected)===1?this.byId(id):null;}
  public async succeedCheckout(id:string,version:number,objectId:string,safe:string|null,entryId:string,at:string):Promise<BillingOperation|null>{return this.database.transaction(async database=>{const settled=await this.transition(id,version,"request_started","succeeded",at,objectId,safe,null,database);if(!settled)return null;const offerId=settled.providerCommercialOfferId??(await database.query<Row>("SELECT id FROM billing_provider_commercial_offers WHERE catalog_entry_id=? AND provider_kind=? AND lifecycle_state='sellable' AND readiness_state='ready' ORDER BY offer_version DESC LIMIT 1",[entryId,settled.providerKind]))[0]?.id;if(!offerId)return null;const ready=settled.providerKind==="mercadopago";try{await database.execute("INSERT INTO billing_checkout_enrollments(id,billing_account_id,catalog_entry_id,provider_commercial_offer_id,checkout_operation_id,provider_kind,provider_checkout_object_id,provider_subscription_id,provider_customer_id,status,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?,?)",[`bce_${randomUUID().replaceAll("-","")}`,settled.billingAccountId,entryId,String(offerId),settled.id,settled.providerKind,objectId,ready?objectId:null,null,ready?"ready":"pending",at,at]);}catch(error){if(error instanceof Error&&/billing_checkout_enrollments\.billing_account_id/u.test(error.message))throw new OpenCheckoutEnrollmentConflictError();throw error;}if(ready)await this.enqueue(database,settled.billingAccountId,settled.providerKind,objectId,at);return settled;});}
  private async transition(id:string,version:number,from:BillingOperationStatus,to:BillingOperationStatus,at:string,objectId:string|null,safe:string|null,code:string|null,database:SqlDatabase=this.database):Promise<BillingOperation|null>{const result=await database.execute("UPDATE billing_operations SET status=?,request_started_at=CASE WHEN ?='request_started' THEN ? ELSE request_started_at END,provider_object_id=?,safe_result_json=?,failure_code=?,settled_at=?,recovery_next_attempt_at=CASE WHEN ?='request_started' THEN ? ELSE recovery_next_attempt_at END,version=version+1,attempt_count=attempt_count+CASE WHEN ?='request_started' THEN 1 ELSE 0 END,updated_at=? WHERE id=? AND version=? AND status=?",[to,to,at,objectId,safe,code,to==="succeeded"||to==="failed"?at:null,to,at,to,at,id,version,from]);return Number(result.rowsAffected)===1?this.byId(id,database):null;}
  private async byId(id:string,database:SqlDatabase=this.database):Promise<BillingOperation|null>{const row=(await database.query<Row>("SELECT * FROM billing_operations WHERE id=?",[id]))[0];return row?operation(row):null;}
  private async enqueue(database:SqlDatabase,accountId:string,providerKind:BillingProviderKind,objectId:string,at:string):Promise<void>{const key=`provider_event:${providerKind}:${accountId}`;await database.execute("INSERT INTO billing_reconciliation_work(id,billing_account_id,provider_kind,reason,provider_object_id,coalesce_key,status,attempt_count,lease_owner,lease_token,lease_expires_at,next_attempt_at,safe_failure_code,version,wake_generation,created_at,updated_at) VALUES(?,?,?,?,?,?,'pending',0,NULL,NULL,NULL,?,NULL,1,1,?,?) ON CONFLICT(coalesce_key) DO UPDATE SET provider_object_id=excluded.provider_object_id,wake_generation=billing_reconciliation_work.wake_generation+1,next_attempt_at=MIN(billing_reconciliation_work.next_attempt_at,excluded.next_attempt_at),updated_at=excluded.updated_at",[`brw_${randomUUID().replaceAll("-","")}`,accountId,providerKind,"checkout_enrollment",objectId,key,at,at,at]);}
}
export class OpenCheckoutEnrollmentConflictError extends Error {}

export class AsyncBillingPayerIdentityRepository {
  public constructor(private readonly database:SqlDatabase){}
  public async resolve(accountId:string):Promise<Readonly<{identityId:string;userId:string;email:string}>|null>{const row=(await this.database.query<Row>("SELECT i.id identityId,i.user_id userId,i.email email FROM billing_accounts a JOIN authentication_identities i ON i.id=a.billing_payer_identity_id JOIN memberships m ON m.user_id=i.user_id AND m.workspace_id=a.workspace_id AND m.status='active' WHERE a.id=? AND i.email_verified=1 AND length(i.email) BETWEEN 3 AND 320 AND length(i.normalized_email) BETWEEN 3 AND 320",[accountId]))[0];return row?Object.freeze({identityId:String(row.identityId),userId:String(row.userId),email:String(row.email)}):null;}
  public async options(workspaceId:number,callerId:string):Promise<readonly Readonly<{identityId:string;email:string}>[]>{return Object.freeze((await this.database.query<Row>("SELECT i.id identityId,i.email email FROM authentication_identities caller JOIN authentication_identities i ON i.user_id=caller.user_id JOIN memberships m ON m.user_id=i.user_id AND m.workspace_id=? AND m.status='active' WHERE caller.id=? AND i.email_verified=1 AND length(i.email) BETWEEN 3 AND 320 AND length(i.normalized_email) BETWEEN 3 AND 320 ORDER BY i.id",[workspaceId,callerId])).map(row=>Object.freeze({identityId:String(row.identityId),email:String(row.email)})));}
  public async setOwned(workspaceId:number,callerId:string,identityId:string,expected:number,at:string):Promise<"succeeded"|"conflict"|"invalid"|"not_found">{const row=(await this.database.query<Row>("SELECT * FROM billing_accounts WHERE workspace_id=?",[workspaceId]))[0];if(!row)return"not_found";const current=account(row);if(current.version!==expected)return"conflict";if(current.billingPayerIdentityId===identityId)return"succeeded";if(!(await this.database.query<Row>("SELECT 1 FROM authentication_identities WHERE id=?",[identityId])).length)return"not_found";const valid=await this.database.query<Row>("SELECT i.id FROM authentication_identities caller JOIN authentication_identities i ON i.user_id=caller.user_id JOIN memberships m ON m.user_id=i.user_id AND m.workspace_id=? AND m.status='active' WHERE caller.id=? AND i.id=? AND i.email_verified=1 AND length(i.email) BETWEEN 3 AND 320 AND length(i.normalized_email) BETWEEN 3 AND 320",[workspaceId,callerId,identityId]);if(!valid.length)return"invalid";const result=await this.database.execute("UPDATE billing_accounts SET billing_payer_identity_id=?,version=version+1,updated_at=? WHERE id=? AND version=?",[identityId,at,current.id,expected]);return Number(result.rowsAffected)===1?"succeeded":"conflict";}
  public async clearOwned(workspaceId:number,callerId:string,identityId:string,expected:number,at:string):Promise<"succeeded"|"conflict"|"invalid"|"not_found">{const row=(await this.database.query<Row>("SELECT * FROM billing_accounts WHERE workspace_id=?",[workspaceId]))[0];if(!row)return"not_found";const current=account(row);if(current.version!==expected)return"conflict";if(current.billingPayerIdentityId!==identityId)return"invalid";const owned=await this.database.query<Row>("SELECT 1 FROM authentication_identities caller JOIN authentication_identities selected ON selected.user_id=caller.user_id WHERE caller.id=? AND selected.id=?",[callerId,identityId]);if(!owned.length)return"invalid";const result=await this.database.execute("UPDATE billing_accounts SET billing_payer_identity_id=NULL,version=version+1,updated_at=? WHERE id=? AND version=?",[at,current.id,expected]);return Number(result.rowsAffected)===1?"succeeded":"conflict";}
}
