import { createHash, randomUUID } from "node:crypto";
import type { SqlDatabase } from "../../config/sqlDatabase.js";
import { billingInterval, billingMarketingInclusionCode, billingProviderKind, currencyCode, type BillingMarketingInclusionCode, type BillingProviderKind } from "../domain/billing.js";
import { CatalogConflictError, CatalogValidationError, type CatalogAdminAudit, type CatalogAdminOffer, type CatalogAdminPlan, type OfferInput, type PlanInput } from "../../repositories/billingCatalogAdministrationRepository.js";

type Row=Record<string,unknown>;
const id=(prefix:string):string=>`${prefix}_${randomUUID().replaceAll("-","")}`;
const fingerprint=(value:unknown):string=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const plan=(row:Row):CatalogAdminPlan=>Object.freeze({id:String(row.id),planKey:String(row.plan_key),catalogVersion:Number(row.catalog_version),displayName:String(row.display_name),description:String(row.description),publicationState:row.publication_state as CatalogAdminPlan["publicationState"],trialDurationDays:row.trial_duration_days===null?null:Number(row.trial_duration_days),graceDurationDays:row.grace_duration_days===null?null:Number(row.grace_duration_days),maxCompanies:row.entitlement_max_companies===null?null:Number(row.entitlement_max_companies),maxAssistantProfiles:row.entitlement_max_assistant_profiles===null?null:Number(row.entitlement_max_assistant_profiles),maxActiveChannels:row.entitlement_max_active_channels===null?null:Number(row.entitlement_max_active_channels),mutationEligible:Number(row.entitlement_mutation_eligible)===1,version:Number(row.version),subscriberCount:Number(row.subscriber_count)});
const offer=(row:Row):CatalogAdminOffer=>Object.freeze({id:String(row.id),catalogEntryId:String(row.catalog_entry_id),providerKind:row.provider_kind as BillingProviderKind,offerVersion:Number(row.offer_version),currency:String(row.currency),amountMinor:Number(row.amount_minor),interval:billingInterval(row.billing_interval),providerPlanReference:String(row.provider_plan_reference),readinessState:row.readiness_state as CatalogAdminOffer["readinessState"],lifecycle:row.lifecycle_state as CatalogAdminOffer["lifecycle"],version:Number(row.version)});

/** Portable SqlDatabase implementation of platform-only catalog administration. */
export class AsyncBillingCatalogAdministrationRepository {
  public constructor(private readonly database:SqlDatabase) {}
  public async list():Promise<readonly CatalogAdminPlan[]>{return Object.freeze((await this.database.query<Row>("SELECT c.*,COUNT(DISTINCT s.id) subscriber_count FROM billing_catalog_entries c LEFT JOIN billing_subscriptions s ON s.catalog_entry_id=c.id GROUP BY c.id ORDER BY c.plan_key,c.catalog_version DESC")).map(plan));}
  public async find(value:string):Promise<CatalogAdminPlan|null>{return this.findOn(this.database,value);}
  public async offers(value:string):Promise<readonly CatalogAdminOffer[]>{return Object.freeze((await this.database.query<Row>("SELECT * FROM billing_provider_commercial_offers WHERE catalog_entry_id=? ORDER BY provider_kind,offer_version DESC",[value])).map(offer));}
  public async audit(value:string):Promise<readonly CatalogAdminAudit[]>{return Object.freeze((await this.database.query<Row>("SELECT id,operation_id,event_type,resulting_version,occurred_at FROM billing_catalog_audit_events WHERE catalog_entry_id=? ORDER BY occurred_at DESC,id DESC",[value])).map(row=>Object.freeze({id:String(row.id),operationId:String(row.operation_id),eventType:String(row.event_type),resultingVersion:Number(row.resulting_version),occurredAt:String(row.occurred_at)})));}
  public async createDraft(actor:string,input:PlanInput,operationId:string,at:string):Promise<CatalogAdminPlan>{this.validatePlan(input);const value=`bce_${createHash("sha256").update(`${actor}:${operationId}`).digest("hex").slice(0,32)}`;return this.command(value,actor,operationId,{action:"plan_draft_created",input},at,async d=>{await d.execute("INSERT INTO billing_catalog_entries(id,plan_key,catalog_version,display_name,billing_interval,currency,amount_minor,lifecycle_state,entitlement_max_companies,entitlement_max_assistant_profiles,entitlement_max_active_channels,entitlement_mutation_eligible,entitlement_definition_version,provider_kind,provider_price_id,description,publication_state,trial_duration_days,grace_duration_days,version,created_at,updated_at) VALUES(?,?,?,?,?,'USD',0,'active',?,?,?,?,?,NULL,NULL,?,'draft',?,?,1,?,?)",[value,input.planKey,input.catalogVersion,input.displayName,"month",input.maxCompanies,input.maxAssistantProfiles,input.maxActiveChannels,input.mutationEligible?1:0,1,input.description,input.trialDurationDays,input.graceDurationDays,at,at]);await this.inclusions(d,value,input.inclusions);return (await this.findOn(d,value))!;});}
  public async updateDraft(actor:string,value:string,expected:number,input:PlanInput,operationId:string,at:string):Promise<CatalogAdminPlan>{this.validatePlan(input);return this.command(value,actor,operationId,{action:"plan_draft_updated",expectedVersion:expected,input},at,async d=>{const current=await this.findOn(d,value);if(!current||current.planKey!==input.planKey||current.catalogVersion!==input.catalogVersion||!await this.update(d,"UPDATE billing_catalog_entries SET display_name=?,description=?,entitlement_max_companies=?,entitlement_max_assistant_profiles=?,entitlement_max_active_channels=?,entitlement_mutation_eligible=?,trial_duration_days=?,grace_duration_days=?,version=version+1,updated_at=? WHERE id=? AND publication_state='draft' AND version=?",[input.displayName,input.description,input.maxCompanies,input.maxAssistantProfiles,input.maxActiveChannels,input.mutationEligible?1:0,input.trialDurationDays,input.graceDurationDays,at,value,expected]))throw new CatalogConflictError();await d.execute("DELETE FROM billing_catalog_inclusions WHERE catalog_entry_id=?",[value]);await this.inclusions(d,value,input.inclusions);return (await this.findOn(d,value))!;});}
  public addOffer(actor:string,value:string,expected:number,input:OfferInput,operationId:string,at:string):Promise<CatalogAdminOffer>{return this.newOffer("provider_offer_created",actor,value,expected,input,operationId,at);}
  public nextOfferVersion(actor:string,value:string,expected:number,input:OfferInput,operationId:string,at:string):Promise<CatalogAdminOffer>{return this.newOffer("provider_offer_next_version_created",actor,value,expected,input,operationId,at);}
  public async updateOfferDraft(actor:string,value:string,offerId:string,expected:number,offerVersion:number,input:OfferInput,operationId:string,at:string):Promise<CatalogAdminOffer>{this.validateOffer(input);return this.command(value,actor,operationId,{action:"provider_offer_draft_updated",expectedVersion:expected,expectedOfferVersion:offerVersion,offerId,input},at,async d=>{if(!await this.draft(d,value,offerId,expected,offerVersion,input.providerKind)||!await this.update(d,"UPDATE billing_provider_commercial_offers SET amount_minor=?,billing_interval=?,provider_plan_reference=?,readiness_state=?,version=version+1,updated_at=? WHERE id=? AND version=? AND lifecycle_state='draft'",[input.amountMinor,input.interval,input.providerPlanReference,input.readinessState,at,offerId,offerVersion])||!await this.bump(d,value,expected,at))throw new CatalogConflictError();return (await this.offerOn(d,offerId))!;});}
  public async setOfferReadiness(actor:string,value:string,offerId:string,expected:number,offerVersion:number,state:OfferInput["readinessState"],operationId:string,at:string):Promise<CatalogAdminOffer>{return this.command(value,actor,operationId,{action:"provider_offer_validated",expectedVersion:expected,expectedOfferVersion:offerVersion,offerId,readinessState:state},at,async d=>{if(!await this.draft(d,value,offerId,expected,offerVersion)||!await this.update(d,"UPDATE billing_provider_commercial_offers SET readiness_state=?,version=version+1,updated_at=? WHERE id=? AND version=? AND lifecycle_state='draft'",[state,at,offerId,offerVersion])||!await this.bump(d,value,expected,at))throw new CatalogConflictError();return (await this.offerOn(d,offerId))!;});}
  public async retirePlan(actor:string,value:string,expected:number,operationId:string,at:string):Promise<CatalogAdminPlan>{return this.command(value,actor,operationId,{action:"plan_retired",expectedVersion:expected},at,async d=>{if(!await this.update(d,"UPDATE billing_catalog_entries SET publication_state='retired',lifecycle_state='retired',version=version+1,updated_at=? WHERE id=? AND publication_state!='retired' AND version=?",[at,value,expected]))throw new CatalogConflictError();await d.execute("UPDATE billing_provider_commercial_offers SET lifecycle_state='retired',version=version+1,updated_at=? WHERE catalog_entry_id=? AND lifecycle_state!='retired'",[at,value]);return (await this.findOn(d,value))!;});}
  public async retireOffer(actor:string,value:string,offerId:string,expected:number,offerVersion:number,operationId:string,at:string):Promise<CatalogAdminOffer>{return this.command(value,actor,operationId,{action:"provider_offer_retired",expectedVersion:expected,expectedOfferVersion:offerVersion,offerId},at,async d=>{if(!await this.draft(d,value,offerId,expected,offerVersion)||!await this.update(d,"UPDATE billing_provider_commercial_offers SET lifecycle_state='retired',version=version+1,updated_at=? WHERE id=? AND version=? AND lifecycle_state='draft'",[at,offerId,offerVersion])||!await this.bump(d,value,expected,at))throw new CatalogConflictError();return (await this.offerOn(d,offerId))!;});}
  public async nextPlanVersion(actor:string,value:string,expected:number,operationId:string,at:string):Promise<CatalogAdminPlan>{return this.command(value,actor,operationId,{action:"plan_next_version_created",expectedVersion:expected},at,async d=>{const current=await this.findOn(d,value);if(!current||current.version!==expected||current.publicationState==="draft")throw new CatalogConflictError();const next=id("bce"),version=Number((await d.query<Row>("SELECT COALESCE(MAX(catalog_version),0)+1 value FROM billing_catalog_entries WHERE plan_key=?",[current.planKey]))[0]!.value);if(!await this.update(d,"INSERT INTO billing_catalog_entries(id,plan_key,catalog_version,display_name,billing_interval,currency,amount_minor,lifecycle_state,entitlement_max_companies,entitlement_max_assistant_profiles,entitlement_max_active_channels,entitlement_mutation_eligible,entitlement_definition_version,provider_kind,provider_price_id,description,publication_state,trial_duration_days,grace_duration_days,version,created_at,updated_at) SELECT ?,plan_key,?,display_name,billing_interval,currency,amount_minor,'active',entitlement_max_companies,entitlement_max_assistant_profiles,entitlement_max_active_channels,entitlement_mutation_eligible,entitlement_definition_version,NULL,NULL,description,'draft',trial_duration_days,grace_duration_days,1,?,? FROM billing_catalog_entries WHERE id=? AND version=?",[next,version,at,at,value,expected]))throw new CatalogConflictError();await d.execute("INSERT INTO billing_catalog_inclusions(catalog_entry_id,inclusion_code,display_title,display_description,sort_order) SELECT ?,inclusion_code,display_title,display_description,sort_order FROM billing_catalog_inclusions WHERE catalog_entry_id=?",[next,value]);return (await this.findOn(d,next))!;});}
  public async publish(actor:string,value:string,expected:number,operationId:string,at:string):Promise<CatalogAdminPlan>{return this.command(value,actor,operationId,{action:"plan_published",expectedVersion:expected},at,async d=>{const current=await this.findOn(d,value),ready=await d.query<Row>("SELECT id FROM billing_provider_commercial_offers WHERE catalog_entry_id=? AND readiness_state='ready' AND lifecycle_state='draft'",[value]);if(!current||current.publicationState!=="draft"||current.version!==expected||!ready.length||!await this.update(d,"UPDATE billing_catalog_entries SET publication_state='published',version=version+1,updated_at=? WHERE id=? AND version=?",[at,value,expected]))throw new CatalogConflictError();for(const row of ready)await d.execute("UPDATE billing_provider_commercial_offers SET lifecycle_state='sellable',version=version+1,updated_at=? WHERE id=? AND lifecycle_state='draft'",[at,String(row.id)]);return (await this.findOn(d,value))!;});}
  private async newOffer(action:string,actor:string,value:string,expected:number,input:OfferInput,operationId:string,at:string):Promise<CatalogAdminOffer>{this.validateOffer(input);return this.command(value,actor,operationId,{action,expectedVersion:expected,input},at,async d=>{const current=await this.findOn(d,value);if(!current||current.publicationState!=="draft"||current.version!==expected)throw new CatalogConflictError();const offerId=id("bpco"),version=Number((await d.query<Row>("SELECT COALESCE(MAX(offer_version),0)+1 value FROM billing_provider_commercial_offers WHERE catalog_entry_id=? AND provider_kind=?",[value,input.providerKind]))[0]!.value);await d.execute("INSERT INTO billing_provider_commercial_offers(id,catalog_entry_id,provider_kind,offer_version,currency,amount_minor,billing_interval,provider_plan_reference,readiness_state,lifecycle_state,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'draft',1,?,?)",[offerId,value,input.providerKind,version,input.providerKind==="stripe"?"USD":"ARS",input.amountMinor,input.interval,input.providerPlanReference,input.readinessState,at,at]);if(!await this.bump(d,value,expected,at))throw new CatalogConflictError();return (await this.offerOn(d,offerId))!;});}
  private async command<T>(value:string,actor:string,operationId:string,input:unknown,at:string,apply:(database:SqlDatabase)=>Promise<T>):Promise<T>{if(!/^[A-Za-z0-9_-]{1,200}$/u.test(operationId))throw new CatalogValidationError();const hash=fingerprint(input);return this.database.transaction(async d=>{const existing=(await d.query<Row>("SELECT request_fingerprint,outcome,safe_result_json FROM billing_catalog_operations WHERE catalog_entry_id=? AND operation_id=?",[value,operationId]))[0];if(existing){if(existing.request_fingerprint!==hash||existing.outcome!=="applied")throw new CatalogConflictError();return JSON.parse(String(existing.safe_result_json)) as T;}const result=await apply(d),version=(await this.findOn(d,value))?.version??(result as {version?:number}).version??1;await d.execute("INSERT INTO billing_catalog_operations(id,catalog_entry_id,operation_id,request_fingerprint,expected_version,resulting_version,actor_user_id,outcome,safe_result_json,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?)",[id("bco"),value,operationId,hash,Math.max(1,Number((input as {expectedVersion?:number}).expectedVersion??1)),version,actor,"applied",JSON.stringify(result),at]);await d.execute("INSERT INTO billing_catalog_audit_events(id,catalog_entry_id,operation_id,actor_user_id,event_type,old_value_json,new_value_json,resulting_version,occurred_at) VALUES(?,?,?,?,?,'{}','{}',?,?)",[id("bca"),value,operationId,actor,String((input as {action:string}).action),version,at]);return result;});}
  private async findOn(d:SqlDatabase,value:string):Promise<CatalogAdminPlan|null>{const row=(await d.query<Row>("SELECT c.*,COUNT(DISTINCT s.id) subscriber_count FROM billing_catalog_entries c LEFT JOIN billing_subscriptions s ON s.catalog_entry_id=c.id WHERE c.id=? GROUP BY c.id",[value]))[0];return row?plan(row):null;}
  private async offerOn(d:SqlDatabase,value:string):Promise<CatalogAdminOffer|null>{const row=(await d.query<Row>("SELECT * FROM billing_provider_commercial_offers WHERE id=?",[value]))[0];return row?offer(row):null;}
  private async update(d:SqlDatabase,sql:string,args:readonly import("../../config/sqlDatabase.js").SqlValue[]):Promise<boolean>{return Number((await d.execute(sql,args)).rowsAffected)===1;}
  private bump(d:SqlDatabase,value:string,expected:number,at:string):Promise<boolean>{return this.update(d,"UPDATE billing_catalog_entries SET version=version+1,updated_at=? WHERE id=? AND version=?",[at,value,expected]);}
  private async draft(d:SqlDatabase,value:string,offerId:string,expected:number,offerVersion:number,kind?:BillingProviderKind):Promise<boolean>{const current=await this.findOn(d,value),currentOffer=await this.offerOn(d,offerId);return !!current&&current.publicationState==="draft"&&current.version===expected&&!!currentOffer&&currentOffer.catalogEntryId===value&&currentOffer.lifecycle==="draft"&&currentOffer.version===offerVersion&&(!kind||currentOffer.providerKind===kind);}
  private async inclusions(d:SqlDatabase,value:string,values:readonly BillingMarketingInclusionCode[]):Promise<void>{for(const[order,code]of values.entries())await d.execute("INSERT INTO billing_catalog_inclusions(catalog_entry_id,inclusion_code,display_title,display_description,sort_order) VALUES(?,?,?,?,?)",[value,code,code,"",order]);}
  private validatePlan(value:PlanInput):void{try{if(!/^[a-z0-9][a-z0-9_-]{0,79}$/u.test(value.planKey)||!Number.isSafeInteger(value.catalogVersion)||value.catalogVersion<1||!value.displayName||value.displayName.length>160||value.description.length>2000||!Array.isArray(value.inclusions)||new Set(value.inclusions).size!==value.inclusions.length)throw new CatalogValidationError();for(const code of value.inclusions)billingMarketingInclusionCode(code);for(const limit of[value.maxCompanies,value.maxAssistantProfiles,value.maxActiveChannels])if(limit!==null&&(!Number.isSafeInteger(limit)||limit<0))throw new CatalogValidationError();for(const days of[value.trialDurationDays,value.graceDurationDays])if(days!==null&&(!Number.isSafeInteger(days)||days<1))throw new CatalogValidationError();}catch(error){if(error instanceof CatalogValidationError)throw error;throw new CatalogValidationError();}}
  private validateOffer(value:OfferInput):void{try{billingProviderKind(value.providerKind);billingInterval(value.interval);currencyCode(value.providerKind==="stripe"?"USD":"ARS");if(!Number.isSafeInteger(value.amountMinor)||value.amountMinor<1||!value.providerPlanReference||value.providerPlanReference.length>200||!["not_configured","invalid","unavailable","ready"].includes(value.readinessState))throw new CatalogValidationError();}catch(error){if(error instanceof CatalogValidationError)throw error;throw new CatalogValidationError();}}
}
