import type { SqlDatabase } from "../../config/sqlDatabase.js";
import type { WorkspaceContext } from "../../types/workspaceContext.js";
import { assistantCapabilityKey, type AssistantCapabilityKey } from "../domain/assistantCapability.js";
import { reconstructAssistantProfile, type AssistantLanguage, type AssistantProfile, type AssistantProfileId, type AssistantProfileStatus, type AssistantTone } from "../domain/assistantProfile.js";
import { assistantReadinessPolicyVersion, defaultAssistantIdentifier, type AssistantReadinessAssessment, type AssistantReadinessBlocker } from "../domain/assistantReadiness.js";
import { assistantProfileId } from "../domain/assistantProfile.js";
import type { DefaultAssistantAssignment } from "../domain/defaultAssistant.js";

type ProfileRow = { id:string; company_id:number; name:string; normalized_name:string; description:string|null; business_role:string|null; objective:string|null; audience:string|null; tone:AssistantTone; assistant_language:AssistantLanguage; welcome_message:string|null; fallback_message:string; status:AssistantProfileStatus; created_at:string; updated_at:string; archived_at:string|null; };
type ReadinessRow = { id:string; workspace_id:number; company_id:number; status:"ready"|"blocked"; blockers_json:string; knowledge_version_id:string|null; assistant_profile_id:string|null; whatsapp_connection_id:string|null; configuration_digest:string; evaluated_at:string; };
type AssignmentRow = { workspace_id:number; company_id:number; assistant_profile_id:string; version:number; assigned_at:string; updated_at:string; assigned_by_actor_id:string|null; source:string|null; };
const profileColumns = "p.id,p.company_id,p.name,p.normalized_name,p.description,p.business_role,p.objective,p.audience,p.tone,p.assistant_language,p.welcome_message,p.fallback_message,p.status,p.created_at,p.updated_at,p.archived_at";

function profile(row: ProfileRow): AssistantProfile { return reconstructAssistantProfile({ id:row.id as AssistantProfileId,companyId:row.company_id,name:row.name,normalizedName:row.normalized_name,description:row.description,businessRole:row.business_role,objective:row.objective,audience:row.audience,tone:row.tone,assistantLanguage:row.assistant_language,welcomeMessage:row.welcome_message,fallbackMessage:row.fallback_message,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,archivedAt:row.archived_at }); }
function assignment(row: AssignmentRow): DefaultAssistantAssignment { return { workspaceId:row.workspace_id,companyId:row.company_id,assistantProfileId:assistantProfileId(row.assistant_profile_id),version:row.version,assignedAt:row.assigned_at,updatedAt:row.updated_at,assignedByActorId:row.assigned_by_actor_id,source:row.source }; }
function readiness(row: ReadinessRow): AssistantReadinessAssessment { return Object.freeze({ id:row.id,assistantIdentifier:defaultAssistantIdentifier,workspaceId:row.workspace_id,companyId:row.company_id,status:row.status,blockers:Object.freeze(JSON.parse(row.blockers_json) as AssistantReadinessBlocker[]),knowledgeVersionId:row.knowledge_version_id,assistantProfileId:row.assistant_profile_id,whatsAppConnectionId:row.whatsapp_connection_id,policyVersion:assistantReadinessPolicyVersion,configurationDigest:row.configuration_digest,evaluatedAt:row.evaluated_at }); }

export class AsyncAssistantProfileRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async listActive(context: WorkspaceContext, companyId: number): Promise<readonly AssistantProfile[] | null> { const visible=await this.database.query<{id:number}>("SELECT id FROM companies WHERE workspace_id=? AND id=?",[context.workspaceId,companyId]); if(!visible.length)return null; return (await this.database.query<ProfileRow>(`SELECT ${profileColumns} FROM assistant_profiles p JOIN companies c ON c.id=p.company_id WHERE c.workspace_id=? AND c.id=? AND p.status!='archived' ORDER BY p.created_at DESC,p.id DESC`,[context.workspaceId,companyId])).map(profile); }
  public async findById(context: WorkspaceContext, companyId: number, id: AssistantProfileId): Promise<AssistantProfile | null> { const rows=await this.database.query<ProfileRow>(`SELECT ${profileColumns} FROM assistant_profiles p JOIN companies c ON c.id=p.company_id WHERE c.workspace_id=? AND c.id=? AND p.id=?`,[context.workspaceId,companyId,id]); return rows[0] ? profile(rows[0]) : null; }
  public async create(context: WorkspaceContext, companyId: number, value: AssistantProfile): Promise<AssistantProfile | null> { if(value.companyId!==companyId)throw new Error("Assistant Profile ownership does not match repository scope."); await this.database.execute("INSERT INTO assistant_profiles(id,company_id,name,normalized_name,description,business_role,objective,audience,tone,assistant_language,welcome_message,fallback_message,status,created_at,updated_at,archived_at) SELECT ?,c.id,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM companies c WHERE c.id=? AND c.workspace_id=?",[value.id,value.name,value.normalizedName,value.description,value.businessRole,value.objective,value.audience,value.tone,value.assistantLanguage,value.welcomeMessage,value.fallbackMessage,value.status,value.createdAt,value.updatedAt,value.archivedAt,companyId,context.workspaceId]); return this.findById(context,companyId,value.id); }
  public async update(context: WorkspaceContext, companyId: number, value: AssistantProfile): Promise<AssistantProfile | null> { if(value.companyId!==companyId)throw new Error("Assistant Profile ownership does not match repository scope."); const result=await this.database.execute("UPDATE assistant_profiles SET name=?,normalized_name=?,description=?,business_role=?,objective=?,audience=?,tone=?,assistant_language=?,welcome_message=?,fallback_message=?,status=?,updated_at=?,archived_at=? WHERE id=? AND company_id=? AND company_id IN(SELECT id FROM companies WHERE id=? AND workspace_id=?)",[value.name,value.normalizedName,value.description,value.businessRole,value.objective,value.audience,value.tone,value.assistantLanguage,value.welcomeMessage,value.fallbackMessage,value.status,value.updatedAt,value.archivedAt,value.id,companyId,companyId,context.workspaceId]); return Number(result.rowsAffected)===1 ? this.findById(context,companyId,value.id) : null; }
}

export class AsyncAssistantCapabilityRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async listForProfile(context: WorkspaceContext, companyId: number, profileId: string): Promise<readonly AssistantCapabilityKey[]> { return Object.freeze((await this.database.query<{capability_key:string}>("SELECT capability_key FROM assistant_profile_capabilities WHERE workspace_id=? AND company_id=? AND assistant_profile_id=? ORDER BY capability_key",[context.workspaceId,companyId,profileId])).map(row=>assistantCapabilityKey(row.capability_key))); }
  public async replaceForProfile(context: WorkspaceContext, companyId: number, profileId: string, capabilities: readonly AssistantCapabilityKey[], actorId: string, at: string): Promise<boolean> { return this.database.transaction(async database=>{const exists=await database.query<{id:string}>("SELECT p.id FROM assistant_profiles p JOIN companies c ON c.id=p.company_id WHERE p.id=? AND p.company_id=? AND c.workspace_id=?",[profileId,companyId,context.workspaceId]);if(!exists.length)return false;await database.execute("DELETE FROM assistant_profile_capabilities WHERE workspace_id=? AND company_id=? AND assistant_profile_id=?",[context.workspaceId,companyId,profileId]);for(const key of capabilities)await database.execute("INSERT INTO assistant_profile_capabilities(workspace_id,company_id,assistant_profile_id,capability_key,assigned_by_actor_id,assigned_at) VALUES(?,?,?,?,?,?)",[context.workspaceId,companyId,profileId,key,actorId,at]);return true;}); }
}

export class AsyncDefaultAssistantRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async find(context: WorkspaceContext, companyId: number): Promise<DefaultAssistantAssignment | null> { const rows=await this.database.query<AssignmentRow>("SELECT * FROM company_default_assistants WHERE workspace_id=? AND company_id=?",[context.workspaceId,companyId]);return rows[0]?assignment(rows[0]):null; }
  public async assign(context: WorkspaceContext, value: DefaultAssistantAssignment, expectedVersion: number | null): Promise<DefaultAssistantAssignment | null> { const result=await this.database.execute("INSERT INTO company_default_assistants(workspace_id,company_id,assistant_profile_id,version,assigned_at,updated_at,assigned_by_actor_id,source) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM companies c JOIN assistant_profiles p ON p.id=? AND p.company_id=c.id WHERE c.workspace_id=? AND c.id=? AND p.status!='archived') ON CONFLICT(company_id) DO UPDATE SET assistant_profile_id=excluded.assistant_profile_id,version=company_default_assistants.version+1,updated_at=excluded.updated_at,assigned_by_actor_id=excluded.assigned_by_actor_id,source=excluded.source WHERE company_default_assistants.version=?",[context.workspaceId,value.companyId,value.assistantProfileId,1,value.assignedAt,value.updatedAt,value.assignedByActorId,value.source,value.assistantProfileId,context.workspaceId,value.companyId,expectedVersion??0]);return Number(result.rowsAffected)===1?this.find(context,value.companyId):null; }
}

export class AsyncAssistantReadinessAssessmentRepository {
  public constructor(private readonly database: SqlDatabase) {}
  public async create(context: WorkspaceContext, value: AssistantReadinessAssessment): Promise<AssistantReadinessAssessment> { const result=await this.database.execute("INSERT INTO assistant_readiness_assessments(id,assistant_identifier,workspace_id,company_id,status,blockers_json,knowledge_version_id,assistant_profile_id,whatsapp_connection_id,policy_version,configuration_digest,evaluated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM companies WHERE id=? AND workspace_id=?)",[value.id,value.assistantIdentifier,value.workspaceId,value.companyId,value.status,JSON.stringify(value.blockers),value.knowledgeVersionId,value.assistantProfileId,value.whatsAppConnectionId,value.policyVersion,value.configurationDigest,value.evaluatedAt,value.companyId,context.workspaceId]);if(Number(result.rowsAffected)!==1)throw new Error("Assistant readiness company scope is invalid.");return value; }
  public async findLatest(context: WorkspaceContext, companyId: number, connectionId: string | null): Promise<AssistantReadinessAssessment | null> { const rows=await this.database.query<ReadinessRow>("SELECT id,workspace_id,company_id,status,blockers_json,knowledge_version_id,assistant_profile_id,whatsapp_connection_id,configuration_digest,evaluated_at FROM assistant_readiness_assessments WHERE workspace_id=? AND company_id=? AND assistant_identifier='default' AND ((whatsapp_connection_id IS NULL AND ? IS NULL) OR whatsapp_connection_id=?) ORDER BY evaluated_at DESC,id DESC LIMIT 1",[context.workspaceId,companyId,connectionId,connectionId]);return rows[0]?readiness(rows[0]):null; }
}
