import type { AuthenticationTransactionPort, Clock, CredentialEnrollmentDeliveryPort, CredentialEnrollmentHashProvider, PasswordHashProvider, PasswordVerificationProvider, RandomProvider, SessionIdentifierProvider } from "../application/ports.js";
import { createEmailAddress, createNormalizedEmail } from "../domain/email.js";
import { BuiltInCommonPasswordBlocklist, isSessionCurrent, PasswordPolicy, type PasswordCredential, type Session } from "../domain/authentication.js";
import type { CredentialEnrollment } from "../domain/credentialEnrollment.js";
import { formatVerificationProof, parseVerificationProof } from "../domain/proof.js";
import { identityIdentifier } from "./verificationIssuance.js";
import type { PlatformAdministratorAccessPort } from "../../platformAdmin/services/platformAuthorizationService.js";

export class AuthenticationFailure extends Error {}
export class AuthenticationConflict extends Error {}
export interface SessionGrant { rawIdentifier: string; csrfToken: string; csrfGeneration: number; absoluteExpiresAt: string; }
export interface SessionBootstrap { identity: { userId: string; email: string; locale: string; status: string; isPlatformAdmin: boolean; idleExpiresAt: string; absoluteExpiresAt: string }; csrfToken: string; csrfGeneration: number; }

export class AuthenticationService {
  private readonly policy = new PasswordPolicy(new BuiltInCommonPasswordBlocklist());
  public constructor(private readonly tx: AuthenticationTransactionPort, private readonly random: RandomProvider, private readonly enrollmentHash: CredentialEnrollmentHashProvider, private readonly passwords: PasswordHashProvider & PasswordVerificationProvider, private readonly identifiers: SessionIdentifierProvider, private readonly clock: Clock, private readonly delivery: CredentialEnrollmentDeliveryPort, private readonly enrollmentOrigin: string, private readonly production: boolean, private readonly platformAdministrators: PlatformAdministratorAccessPort | null = null, private readonly idleMs = 2 * 60 * 60 * 1000, private readonly absoluteMs = 12 * 60 * 60 * 1000, private readonly enrollmentMs = 30 * 60 * 1000, private readonly cooldownMs = 60 * 1000) { if (production && !enrollmentOrigin.startsWith("https://")) throw new Error("Production authentication requires an HTTPS origin."); }

  public async requestEnrollment(emailValue: string): Promise<void> {
    let issued: { workflow: CredentialEnrollment; proof: string; email: string; locale: "en" | "es" } | null = null;
    try { const normalized = createNormalizedEmail(createEmailAddress(emailValue)); issued = await this.tx.execute(async r => { const user = await r.users.findByNormalizedEmail(normalized); if (!user || user.status !== "active") return null; const identity = user.authenticationIdentities.find(i => i.normalizedEmail === normalized && i.emailVerified); if (!identity || await r.credentials.findCurrent(identity.id)) return null; const now = this.clock.now(), current = await r.enrollments.findCurrent(identity.id); if (current && Date.parse(now) - Date.parse(current.issuedAt) < this.cooldownMs) return null; if (current) await r.enrollments.update({ ...current, status: "superseded", supersededAt: now, updatedAt: now }, "pending"); const proof = formatVerificationProof(this.random.secureBytes(32)); const workflow: CredentialEnrollment = { id: this.id("cen"), userId: user.id, authenticationIdentityId: identity.id, purpose: "credential_enrollment", digestVersion: "sha256-v1", proofDigest: this.enrollmentHash.digest(proof), status: "pending", deliveryStatus: "pending", issuedAt: now, expiresAt: new Date(Date.parse(now) + this.enrollmentMs).toISOString(), consumedAt: null, supersededAt: null, invalidatedAt: null, updatedAt: now }; await r.enrollments.create(workflow); return { workflow, proof, email: identity.email, locale: user.locale }; }); } catch { return; }
    if (!issued) return;
    const outcome = await this.delivery.deliver({ recipient: createEmailAddress(issued.email), locale: issued.locale, enrollmentUrl: `${this.enrollmentOrigin}/enroll-credential?proof=${encodeURIComponent(issued.proof)}`, expiresAt: issued.workflow.expiresAt, workflowId: issued.workflow.id });
    await this.tx.execute(async r => { const at = this.clock.now(); await r.enrollments.setDeliveryStatus(issued!.workflow.id, outcome, at); if (outcome === "permanent_failure") { const current = await r.enrollments.findCurrent(issued!.workflow.authenticationIdentityId); if (current?.id === issued!.workflow.id) await r.enrollments.update({ ...current, status: "invalidated", invalidatedAt: at, updatedAt: at }, "pending"); } });
  }

  public async completeEnrollment(proofValue: string, password: string, confirmation: string): Promise<void> { this.policy.validate(password, confirmation); const proof = parseVerificationProof(proofValue), protection = await this.passwords.protect(password), digest = this.enrollmentHash.digest(proof); await this.tx.execute(async r => { const now = this.clock.now(), workflow = await r.enrollments.findByDigest(digest); if (!workflow || workflow.status !== "pending" || Date.parse(now) >= Date.parse(workflow.expiresAt)) throw new AuthenticationFailure(); const user = await r.users.findById(workflow.userId), identity = user?.authenticationIdentities.find(i => i.id === workflow.authenticationIdentityId); if (!user || user.status !== "active" || !identity?.emailVerified || await r.credentials.findCurrent(identity.id)) throw new AuthenticationFailure(); await r.credentials.create(this.credential(identity.id, 1, protection, now)); if (!await r.enrollments.update({ ...workflow, status: "consumed", consumedAt: now, updatedAt: now }, "pending")) throw new AuthenticationConflict(); }); }

  public async login(emailValue: string, password: string, origin: string): Promise<SessionGrant> { let normalized: ReturnType<typeof createNormalizedEmail>; try { normalized = createNormalizedEmail(createEmailAddress(emailValue)); } catch { await this.passwords.dummyVerify(password); throw new AuthenticationFailure(); } const snapshot = await this.tx.execute(async r => { await r.throttles.cleanup(this.clock.now()); if (await r.throttles.isBlocked(normalized, origin, this.clock.now(), 5)) return null; const user = await r.users.findByNormalizedEmail(normalized), identity = user?.authenticationIdentities.find(i => i.normalizedEmail === normalized), credential = identity ? await r.credentials.findCurrent(identity.id) : null; return user && identity && credential ? { user, identity, credential } : null; }); if (!snapshot) { await this.passwords.dummyVerify(password); await this.failure(normalized, origin); throw new AuthenticationFailure(); } const verified = await this.passwords.verify(password, this.protection(snapshot.credential)); if (!verified.matches || snapshot.user.status !== "active" || !snapshot.identity.emailVerified) { await this.failure(normalized, origin); throw new AuthenticationFailure(); } const upgraded = verified.needsUpgrade ? await this.passwords.protect(password) : null, identifier = this.identifiers.create(), csrf = formatVerificationProof(this.random.secureBytes(32)); return this.tx.execute(async r => { const user = await r.users.findById(snapshot.user.id); let credential = await r.credentials.findCurrent(snapshot.identity.id); if (!user || user.status !== "active" || !credential || credential.credentialVersion !== snapshot.credential.credentialVersion) throw new AuthenticationFailure(); if (upgraded) { const now = this.clock.now(), next = { ...this.credential(credential.authenticationIdentityId, credential.credentialVersion, upgraded, now), upgradedAt: now }; if (!await r.credentials.replace(next, credential.credentialVersion)) throw new AuthenticationConflict(); credential = next; } const session = this.session(user.id, snapshot.identity.id, credential.credentialVersion, identifier.digest, this.identifiers.digestSecret(csrf, "csrf"), null); await r.sessions.create(session); await r.throttles.clear(normalized, origin); return { rawIdentifier: identifier.raw, csrfToken: csrf, csrfGeneration: session.csrfGeneration, absoluteExpiresAt: session.absoluteExpiresAt }; }); }

  public async current(raw: string): Promise<{ userId: string; authenticationIdentityId: string; email: string; locale: string; status: string; isPlatformAdmin: boolean; idleExpiresAt: string; absoluteExpiresAt: string } | null> { const valid = await this.validSession(raw); if (!valid) return null; const user = await this.tx.execute(r => r.users.findById(valid.session.userId)), identity = user?.authenticationIdentities.find(i => i.id === valid.session.authenticationIdentityId); return user && identity ? { userId: user.id, authenticationIdentityId: identity.id, email: identity.email, locale: user.locale, status: user.status, isPlatformAdmin: this.platformAdministrators ? await this.platformAdministrators.isActive(user.id) : false, idleExpiresAt: valid.session.idleExpiresAt, absoluteExpiresAt: valid.session.absoluteExpiresAt } : null; }
  public async bootstrapSession(raw: string): Promise<SessionBootstrap> { const parsed = this.identifiers.parse(raw); if (!parsed) throw new AuthenticationFailure(); const csrf = formatVerificationProof(this.random.secureBytes(32)); return this.tx.execute(async r => { const now = this.clock.now(), session = await r.sessions.findByDigest(parsed.digest); if (!session || !isSessionCurrent(session, now)) throw new AuthenticationFailure(); const user = await r.users.findById(session.userId), credential = await r.credentials.findCurrent(session.authenticationIdentityId), identity = user?.authenticationIdentities.find(i => i.id === session.authenticationIdentityId); if (!user || user.status !== "active" || !credential || credential.credentialVersion !== session.credentialVersion || !identity) throw new AuthenticationFailure(); const idleExpiresAt = new Date(Math.min(Date.parse(now) + this.idleMs, Date.parse(session.absoluteExpiresAt))).toISOString(); if (!await r.sessions.rotateCsrf(session.id, session.csrfGeneration, this.identifiers.digestSecret(csrf, "csrf"), now, idleExpiresAt)) throw new AuthenticationConflict(); return { identity: { userId: user.id, email: identity.email, locale: user.locale, status: user.status, isPlatformAdmin: this.platformAdministrators ? await this.platformAdministrators.isActive(user.id) : false, idleExpiresAt, absoluteExpiresAt: session.absoluteExpiresAt }, csrfToken: csrf, csrfGeneration: session.csrfGeneration + 1 }; }); }
  public async refresh(raw: string): Promise<SessionGrant> { const parsed = this.identifiers.parse(raw); if (!parsed) throw new AuthenticationFailure(); const next = this.identifiers.create(), csrf = formatVerificationProof(this.random.secureBytes(32)); return this.tx.execute(async r => { const now = this.clock.now(), old = await r.sessions.findByDigest(parsed.digest); if (!old || !isSessionCurrent(old, now)) throw new AuthenticationFailure(); const user = await r.users.findById(old.userId), credential = await r.credentials.findCurrent(old.authenticationIdentityId); if (!user || user.status !== "active" || !credential || credential.credentialVersion !== old.credentialVersion) throw new AuthenticationFailure(); const idle = new Date(Math.min(Date.parse(now) + this.idleMs, Date.parse(old.absoluteExpiresAt))).toISOString(), replacement = { ...this.session(old.userId, old.authenticationIdentityId, old.credentialVersion, next.digest, this.identifiers.digestSecret(csrf, "csrf"), old.id), absoluteExpiresAt: old.absoluteExpiresAt, idleExpiresAt: idle }; if (!await r.sessions.replace(old.id, "active", replacement)) throw new AuthenticationConflict(); return { rawIdentifier: next.raw, csrfToken: csrf, csrfGeneration: replacement.csrfGeneration, absoluteExpiresAt: old.absoluteExpiresAt }; }); }
  public async logout(raw: string): Promise<void> { const parsed = this.identifiers.parse(raw); if (!parsed) return; await this.tx.execute(async r => { const session = await r.sessions.findByDigest(parsed.digest); if (session) await r.sessions.revoke(session.id, this.clock.now(), "logout"); }); }
  public async validateCsrf(raw: string, csrf: string): Promise<boolean> { const valid = await this.validSession(raw); return !!valid && this.identifiers.digestSecret(csrf, "csrf") === valid.session.csrfDigest; }
  public async replacePassword(raw: string, current: string, next: string, confirmation: string): Promise<void> { this.policy.validate(next, confirmation); const valid = await this.validSession(raw); if (!valid) throw new AuthenticationFailure(); const credential = await this.tx.execute(r => r.credentials.findCurrent(valid.session.authenticationIdentityId)); if (!credential) throw new AuthenticationFailure(); const verified = await this.passwords.verify(current, this.protection(credential)); if (!verified.matches) throw new AuthenticationFailure(); const protection = await this.passwords.protect(next); await this.tx.execute(async r => { const now = this.clock.now(), latest = await r.credentials.findCurrent(credential.authenticationIdentityId); if (!latest || latest.credentialVersion !== credential.credentialVersion) throw new AuthenticationConflict(); if (!await r.credentials.replace(this.credential(latest.authenticationIdentityId, latest.credentialVersion + 1, protection, now), latest.credentialVersion)) throw new AuthenticationConflict(); await r.sessions.revokeAll(valid.session.userId, now, "password_replaced"); }); }
  public cookieName(): string { return this.production ? "__Host-atlas_session" : "atlas_dev_session"; }
  private async validSession(raw: string): Promise<{ session: Session } | null> { const parsed = this.identifiers.parse(raw); if (!parsed) return null; return this.tx.execute(async r => { const session = await r.sessions.findByDigest(parsed.digest); if (!session || !isSessionCurrent(session, this.clock.now())) return null; const user = await r.users.findById(session.userId), credential = await r.credentials.findCurrent(session.authenticationIdentityId); return user?.status === "active" && credential?.credentialVersion === session.credentialVersion ? { session } : null; }); }
  private async failure(identity: string, origin: string): Promise<void> { await this.tx.execute(async r => { const now = this.clock.now(); await r.throttles.recordFailure(identity, origin, now, new Date(Date.parse(now) + 15 * 60 * 1000).toISOString()); }); }
  private credential(identityId: PasswordCredential["authenticationIdentityId"], version: number, protection: Awaited<ReturnType<PasswordHashProvider["protect"]>>, now: string): PasswordCredential { return { id: this.id("pwd"), authenticationIdentityId: identityId, state: "active", ...protection, credentialVersion: version, createdAt: now, replacedAt: null, upgradedAt: null }; }
  private protection(credential: PasswordCredential) { return { algorithm: credential.algorithm, algorithmVersion: credential.algorithmVersion, parameters: credential.parameters, salt: credential.salt, confirmation: credential.confirmation }; }
  private session(userId: Session["userId"], identityId: Session["authenticationIdentityId"], version: number, digest: string, csrfDigest: string, predecessorId: string | null): Session { const now = this.clock.now(); return { id: this.id("ses"), userId, authenticationIdentityId: identityId, strategy: "password", authenticationVersion: 1, credentialVersion: version, digestVersion: "sha256-v1", identifierDigest: digest, csrfDigest, csrfGeneration: 1, state: "active", issuedAt: now, lastSeenAt: now, idleExpiresAt: new Date(Date.parse(now) + this.idleMs).toISOString(), absoluteExpiresAt: new Date(Date.parse(now) + this.absoluteMs).toISOString(), predecessorId, replacedAt: null, revokedAt: null, revocationReason: null }; }
  private id(prefix: string): string { return `${prefix}_${Buffer.from(this.random.secureBytes(16)).toString("hex")}`; }
}
