export type Locale = "es" | "en";
export type Direction = "ltr" | "rtl";

export const localeMetadata: Record<Locale, { nativeName: string; direction: Direction }> = {
  es: { nativeName: "Español", direction: "ltr" },
  en: { nativeName: "English", direction: "ltr" },
};

export const translationKeys = [
  "app.brand", "app.portal", "app.title", "app.subtitle",
  "language.label", "language.es", "language.en",
  "common.cancel", "common.close", "common.save", "common.saving", "common.edit", "common.delete", "common.retry", "common.loading", "common.optional", "common.confirm", "common.back",
  "companies.title", "companies.create", "companies.createTitle", "companies.createSuccess", "companies.emptyTitle", "companies.emptyDescription", "companies.loadError", "companies.selectPrompt", "companies.mobileSelector", "companies.unknownWebsite",
  "companies.fields.name", "companies.fields.website", "companies.fields.phone", "companies.fields.email", "companies.fields.createdAt",
  "companies.placeholders.name", "companies.placeholders.website", "companies.placeholders.phone", "companies.placeholders.email",
  "companies.validation.name", "companies.validation.website", "companies.operationError", "companies.updateSuccess", "companies.deleteTitle", "companies.deletePrompt", "companies.deleteSuccess", "companies.deleteError",
  "status.processing", "status.ready", "status.failed", "status.unknown",
  "workspace.contactMissing", "workspace.websiteLink", "workspace.editTitle",
  "onboarding.title", "onboarding.description", "onboarding.websiteHelp", "onboarding.start", "onboarding.retry", "onboarding.processingTitle", "onboarding.processingDescription", "onboarding.success", "onboarding.error", "onboarding.invalidUrl", "onboarding.readyDescription", "onboarding.focusChat",
  "chat.title", "chat.context", "chat.languageNote", "chat.emptyTitle", "chat.emptyDescription", "chat.placeholder", "chat.send", "chat.sending", "chat.responding", "chat.user", "chat.atlas", "chat.system", "chat.unavailableProcessing", "chat.unavailableFailed", "chat.error", "chat.missingKnowledge", "chat.retry", "chat.clearOnSwitch",
  "states.loadingCompanies", "states.loadingCompany", "states.errorTitle", "states.successTitle",
  "accessibility.mainContent", "accessibility.companyNavigation", "accessibility.openCompanies", "accessibility.closeCompanies", "accessibility.externalLink", "accessibility.processing", "accessibility.ready", "accessibility.failed",
  "portal.resourceUnavailable", "portal.companyLoadError", "portal.workspaceCreateError", "portal.password", "portal.logout", "portal.workspaceSelect", "portal.workspaceNone", "portal.workspacesLoading", "portal.workspaceValidating", "portal.companiesTitle", "portal.companiesDescription", "portal.workspaceRequired", "portal.companiesLoading", "portal.companiesError", "portal.companiesEmpty", "portal.companySelect", "portal.companyNone",
  "profiles.title", "profiles.description", "profiles.companyRequired", "profiles.create", "profiles.createTitle", "profiles.editTitle", "profiles.loading", "profiles.loadError", "profiles.emptyTitle", "profiles.emptyDescription", "profiles.listLabel", "profiles.notConfigured", "profiles.updatedAt", "profiles.languageSelect", "profiles.validationRequired", "profiles.validationFallback", "profiles.validationError", "profiles.createSuccess", "profiles.updateSuccess", "profiles.archiveSuccess", "profiles.transitionSuccess", "profiles.createError", "profiles.updateError", "profiles.nameConflict", "profiles.updateConflict", "profiles.transitionConflict", "profiles.transitionError", "profiles.transitioning", "profiles.readyWarning", "profiles.archivedTitle", "profiles.archivedDescription", "profiles.archiveConfirmTitle", "profiles.archiveConfirm",
  "profiles.field.name", "profiles.field.description", "profiles.field.businessRole", "profiles.field.objective", "profiles.field.audience", "profiles.field.tone", "profiles.field.language", "profiles.field.welcomeMessage", "profiles.field.fallbackMessage",
  "profiles.tone.professional", "profiles.tone.friendly", "profiles.tone.concise", "profiles.tone.empathetic",
  "profiles.status.draft", "profiles.status.ready", "profiles.status.disabled", "profiles.status.archived",
  "profiles.action.ready", "profiles.action.draft", "profiles.action.disable", "profiles.action.archive", "profiles.action.restore",
  "preview.title", "preview.context", "preview.readyRequired", "preview.messageLabel", "preview.placeholder", "preview.limit", "preview.send", "preview.sending", "preview.responding", "preview.answer", "preview.fallback", "preview.profileUnavailable", "preview.companyUnavailable", "preview.knowledgeUnavailable", "preview.temporarilyUnavailable", "preview.invalid",
] as const;

export type TranslationKey = typeof translationKeys[number];
export type TranslationDictionary = Record<TranslationKey, string>;

const es: TranslationDictionary = {
  "app.brand": "ATLAS", "app.portal": "Portal", "app.title": "Atlas Portal", "app.subtitle": "Gestioná empresas y probá su asistente desde un solo lugar.",
  "language.label": "Idioma del portal", "language.es": "Español", "language.en": "English",
  "common.cancel": "Cancelar", "common.close": "Cerrar", "common.save": "Guardar", "common.saving": "Guardando…", "common.edit": "Editar", "common.delete": "Eliminar", "common.retry": "Intentar de nuevo", "common.loading": "Cargando…", "common.optional": "Opcional", "common.confirm": "Confirmar", "common.back": "Volver",
  "companies.title": "Empresas", "companies.create": "Nueva empresa", "companies.createTitle": "Crear empresa", "companies.createSuccess": "La empresa se creó correctamente.", "companies.emptyTitle": "Todavía no hay empresas", "companies.emptyDescription": "Creá la primera empresa para comenzar a preparar su asistente.", "companies.loadError": "No pudimos cargar las empresas.", "companies.selectPrompt": "Seleccioná una empresa para continuar.", "companies.mobileSelector": "Cambiar empresa", "companies.unknownWebsite": "Sitio sin definir",
  "companies.fields.name": "Nombre", "companies.fields.website": "Sitio web", "companies.fields.phone": "Teléfono", "companies.fields.email": "Correo electrónico", "companies.fields.createdAt": "Creada el",
  "companies.placeholders.name": "Empresa Ejemplo", "companies.placeholders.website": "https://empresa.example", "companies.placeholders.phone": "+54 11 0000 0000", "companies.placeholders.email": "contacto@empresa.example",
  "companies.validation.name": "Ingresá un nombre para la empresa.", "companies.validation.website": "Ingresá una URL válida que comience con http:// o https://.", "companies.operationError": "No pudimos guardar la empresa. Revisá los datos e intentá nuevamente.", "companies.updateSuccess": "Los datos de la empresa se actualizaron.", "companies.deleteTitle": "Eliminar empresa", "companies.deletePrompt": "¿Confirmás que querés eliminar {companyName}? También se eliminará su conocimiento guardado.", "companies.deleteSuccess": "La empresa se eliminó correctamente.", "companies.deleteError": "No pudimos eliminar la empresa.",
  "status.processing": "Procesando", "status.ready": "Lista", "status.failed": "Con errores", "status.unknown": "Estado desconocido",
  "workspace.contactMissing": "Sin datos", "workspace.websiteLink": "Abrir sitio web", "workspace.editTitle": "Editar empresa",
  "onboarding.title": "Incorporación", "onboarding.description": "Atlas analizará el sitio y preparará el conocimiento que usará el asistente.", "onboarding.websiteHelp": "Si cambiás la URL, se actualizará el sitio de esta misma empresa.", "onboarding.start": "Iniciar incorporación", "onboarding.retry": "Reintentar incorporación", "onboarding.processingTitle": "Preparando el conocimiento", "onboarding.processingDescription": "Estamos analizando el sitio y preparando el conocimiento de la empresa. Esto puede demorar unos minutos.", "onboarding.success": "La empresa está lista para probar el chat.", "onboarding.error": "No pudimos completar la incorporación. Los datos de la empresa siguen disponibles.", "onboarding.invalidUrl": "Ingresá una URL válida que comience con http:// o https://.", "onboarding.readyDescription": "El conocimiento está disponible. Podés repetir la incorporación para actualizarlo.", "onboarding.focusChat": "Probar el chat",
  "chat.title": "Chat de prueba", "chat.context": "Probando respuestas para {companyName}", "chat.languageNote": "El asistente responde según el idioma del mensaje del cliente. El idioma del portal no modifica sus respuestas.", "chat.emptyTitle": "Probá el asistente", "chat.emptyDescription": "Escribí una pregunta real que haría un cliente de esta empresa.", "chat.placeholder": "Escribí un mensaje…", "chat.send": "Enviar", "chat.sending": "Enviando…", "chat.responding": "Atlas está respondiendo…", "chat.user": "Vos", "chat.atlas": "Atlas", "chat.system": "Sistema", "chat.unavailableProcessing": "El chat estará disponible cuando termine la incorporación.", "chat.unavailableFailed": "Reintentá la incorporación antes de probar el chat.", "chat.error": "No pudimos obtener una respuesta. Intentá nuevamente.", "chat.missingKnowledge": "La empresa todavía no tiene conocimiento disponible.", "chat.retry": "Reenviar mensaje", "chat.clearOnSwitch": "La conversación se reinicia al cambiar de empresa.",
  "states.loadingCompanies": "Cargando empresas…", "states.loadingCompany": "Cargando empresa…", "states.errorTitle": "Algo salió mal", "states.successTitle": "Operación completada",
  "accessibility.mainContent": "Contenido principal", "accessibility.companyNavigation": "Navegación de empresas", "accessibility.openCompanies": "Abrir selector de empresas", "accessibility.closeCompanies": "Cerrar selector de empresas", "accessibility.externalLink": "Abre en una pestaña nueva", "accessibility.processing": "Estado: procesando", "accessibility.ready": "Estado: lista", "accessibility.failed": "Estado: con errores",
  "portal.resourceUnavailable": "El recurso ya no está disponible. Actualizamos el contexto.", "portal.companyLoadError": "No pudimos cargar la empresa seleccionada.", "portal.workspaceCreateError": "No pudimos crear el espacio de trabajo.", "portal.password": "Cambiar contraseña", "portal.logout": "Cerrar sesión", "portal.workspaceSelect": "Seleccionar espacio de trabajo", "portal.workspaceNone": "Sin espacio seleccionado", "portal.workspacesLoading": "Cargando espacios…", "portal.workspaceValidating": "Validando espacio…", "portal.companiesTitle": "Empresas del espacio", "portal.companiesDescription": "Seleccioná la empresa cuyos asistentes querés configurar.", "portal.workspaceRequired": "Seleccioná un espacio de trabajo para ver sus empresas.", "portal.companiesLoading": "Cargando empresas autorizadas…", "portal.companiesError": "No pudimos cargar las empresas.", "portal.companiesEmpty": "Creá la primera empresa para comenzar a configurar su asistente.", "portal.companySelect": "Seleccionar empresa", "portal.companyNone": "Sin empresa seleccionada",
  "profiles.title": "Perfiles de asistentes", "profiles.description": "Configurá cómo se presenta y responde cada asistente de la empresa.", "profiles.companyRequired": "Seleccioná una empresa para ver sus perfiles.", "profiles.create": "Nuevo perfil", "profiles.createTitle": "Crear perfil de asistente", "profiles.editTitle": "Editar perfil de asistente", "profiles.loading": "Cargando perfiles…", "profiles.loadError": "No pudimos cargar los perfiles.", "profiles.emptyTitle": "Todavía no hay perfiles", "profiles.emptyDescription": "Creá el primer perfil para configurar un asistente.", "profiles.listLabel": "Perfiles de asistentes", "profiles.notConfigured": "Sin configurar", "profiles.updatedAt": "Actualizado el {date}", "profiles.languageSelect": "Seleccioná un idioma", "profiles.validationRequired": "Completá el nombre y seleccioná el idioma del asistente.", "profiles.validationFallback": "El mensaje alternativo no puede quedar vacío.", "profiles.validationError": "Revisá los datos del perfil e intentá nuevamente.", "profiles.createSuccess": "El perfil se creó correctamente.", "profiles.updateSuccess": "El perfil se actualizó correctamente.", "profiles.archiveSuccess": "El perfil fue archivado.", "profiles.transitionSuccess": "El estado del perfil se actualizó.", "profiles.createError": "No pudimos crear el perfil.", "profiles.updateError": "No pudimos actualizar el perfil.", "profiles.nameConflict": "Ya existe un perfil con ese nombre en la empresa.", "profiles.updateConflict": "El perfil cambió o su configuración no es válida para este estado.", "profiles.transitionConflict": "El servidor no permitió cambiar el estado. Revisá la configuración e intentá nuevamente.", "profiles.transitionError": "No pudimos cambiar el estado del perfil.", "profiles.transitioning": "Actualizando…", "profiles.readyWarning": "La guía local detecta campos que conviene completar antes de marcar el perfil como listo:", "profiles.archivedTitle": "Perfil archivado", "profiles.archivedDescription": "{profileName} ya no aparece en la lista activa. Podés restaurarlo ahora.", "profiles.archiveConfirmTitle": "Archivar perfil", "profiles.archiveConfirm": "¿Confirmás que querés archivar {profileName}?",
  "profiles.field.name": "Nombre", "profiles.field.description": "Descripción", "profiles.field.businessRole": "Rol comercial", "profiles.field.objective": "Objetivo", "profiles.field.audience": "Audiencia", "profiles.field.tone": "Tono", "profiles.field.language": "Idioma del asistente", "profiles.field.welcomeMessage": "Mensaje de bienvenida", "profiles.field.fallbackMessage": "Mensaje alternativo",
  "profiles.tone.professional": "Profesional", "profiles.tone.friendly": "Amable", "profiles.tone.concise": "Conciso", "profiles.tone.empathetic": "Empático",
  "profiles.status.draft": "Borrador", "profiles.status.ready": "Listo", "profiles.status.disabled": "Deshabilitado", "profiles.status.archived": "Archivado",
  "profiles.action.ready": "Marcar como listo", "profiles.action.draft": "Volver a borrador", "profiles.action.disable": "Deshabilitar", "profiles.action.archive": "Archivar", "profiles.action.restore": "Restaurar a borrador",
  "preview.title": "Vista previa del asistente", "preview.context": "Probando {profileName} para {companyName}.", "preview.readyRequired": "Marcá el perfil como listo antes de probarlo.", "preview.messageLabel": "Mensaje de prueba", "preview.placeholder": "Escribí una pregunta real de un cliente…", "preview.limit": "{count}/2000 caracteres", "preview.send": "Probar respuesta", "preview.sending": "Enviando…", "preview.responding": "El asistente está preparando una respuesta…", "preview.answer": "Respuesta", "preview.fallback": "Respuesta alternativa segura", "preview.profileUnavailable": "El perfil ya no está listo para probar.", "preview.companyUnavailable": "La empresa todavía no está lista para la vista previa.", "preview.knowledgeUnavailable": "La empresa todavía no tiene conocimiento disponible.", "preview.temporarilyUnavailable": "La vista previa no está disponible temporalmente. Intentá nuevamente.", "preview.invalid": "Ingresá un mensaje válido de hasta 2000 caracteres.",
};

const en: TranslationDictionary = {
  "app.brand": "ATLAS", "app.portal": "Portal", "app.title": "Atlas Portal", "app.subtitle": "Manage companies and test their assistant in one place.",
  "language.label": "Portal language", "language.es": "Español", "language.en": "English",
  "common.cancel": "Cancel", "common.close": "Close", "common.save": "Save", "common.saving": "Saving…", "common.edit": "Edit", "common.delete": "Delete", "common.retry": "Try again", "common.loading": "Loading…", "common.optional": "Optional", "common.confirm": "Confirm", "common.back": "Back",
  "companies.title": "Companies", "companies.create": "New company", "companies.createTitle": "Create company", "companies.createSuccess": "The company was created successfully.", "companies.emptyTitle": "No companies yet", "companies.emptyDescription": "Create the first company to start preparing its assistant.", "companies.loadError": "We couldn't load the companies.", "companies.selectPrompt": "Select a company to continue.", "companies.mobileSelector": "Change company", "companies.unknownWebsite": "Website not defined",
  "companies.fields.name": "Name", "companies.fields.website": "Website", "companies.fields.phone": "Phone", "companies.fields.email": "Email", "companies.fields.createdAt": "Created on",
  "companies.placeholders.name": "Example Company", "companies.placeholders.website": "https://company.example", "companies.placeholders.phone": "+1 555 000 0000", "companies.placeholders.email": "contact@company.example",
  "companies.validation.name": "Enter a company name.", "companies.validation.website": "Enter a valid URL beginning with http:// or https://.", "companies.operationError": "We couldn't save the company. Review the details and try again.", "companies.updateSuccess": "The company details were updated.", "companies.deleteTitle": "Delete company", "companies.deletePrompt": "Are you sure you want to delete {companyName}? Its stored knowledge will also be deleted.", "companies.deleteSuccess": "The company was deleted successfully.", "companies.deleteError": "We couldn't delete the company.",
  "status.processing": "Processing", "status.ready": "Ready", "status.failed": "Failed", "status.unknown": "Unknown status",
  "workspace.contactMissing": "Not provided", "workspace.websiteLink": "Open website", "workspace.editTitle": "Edit company",
  "onboarding.title": "Onboarding", "onboarding.description": "Atlas will analyze the website and prepare the knowledge used by the assistant.", "onboarding.websiteHelp": "Changing the URL will update the website for this same company.", "onboarding.start": "Start onboarding", "onboarding.retry": "Retry onboarding", "onboarding.processingTitle": "Preparing company knowledge", "onboarding.processingDescription": "We're analyzing the website and preparing company knowledge. This may take a few minutes.", "onboarding.success": "The company is ready to test in chat.", "onboarding.error": "We couldn't complete onboarding. The company details remain available.", "onboarding.invalidUrl": "Enter a valid URL beginning with http:// or https://.", "onboarding.readyDescription": "Knowledge is available. You can run onboarding again to refresh it.", "onboarding.focusChat": "Test the chat",
  "chat.title": "Test chat", "chat.context": "Testing responses for {companyName}", "chat.languageNote": "The assistant responds in the customer's message language. The portal language does not change its responses.", "chat.emptyTitle": "Test the assistant", "chat.emptyDescription": "Enter a real question a customer might ask this company.", "chat.placeholder": "Write a message…", "chat.send": "Send", "chat.sending": "Sending…", "chat.responding": "Atlas is responding…", "chat.user": "You", "chat.atlas": "Atlas", "chat.system": "System", "chat.unavailableProcessing": "Chat will be available when onboarding is complete.", "chat.unavailableFailed": "Retry onboarding before testing the chat.", "chat.error": "We couldn't get a response. Try again.", "chat.missingKnowledge": "This company does not have knowledge available yet.", "chat.retry": "Send message again", "chat.clearOnSwitch": "The conversation resets when you switch companies.",
  "states.loadingCompanies": "Loading companies…", "states.loadingCompany": "Loading company…", "states.errorTitle": "Something went wrong", "states.successTitle": "Operation completed",
  "accessibility.mainContent": "Main content", "accessibility.companyNavigation": "Company navigation", "accessibility.openCompanies": "Open company selector", "accessibility.closeCompanies": "Close company selector", "accessibility.externalLink": "Opens in a new tab", "accessibility.processing": "Status: processing", "accessibility.ready": "Status: ready", "accessibility.failed": "Status: failed",
  "portal.resourceUnavailable": "The resource is no longer available. We refreshed the context.", "portal.companyLoadError": "We couldn't load the selected company.", "portal.workspaceCreateError": "We couldn't create the Workspace.", "portal.password": "Replace password", "portal.logout": "Log out", "portal.workspaceSelect": "Select Workspace", "portal.workspaceNone": "No Workspace selected", "portal.workspacesLoading": "Loading Workspaces…", "portal.workspaceValidating": "Validating Workspace…", "portal.companiesTitle": "Workspace companies", "portal.companiesDescription": "Select the company whose assistants you want to configure.", "portal.workspaceRequired": "Select a Workspace to view its companies.", "portal.companiesLoading": "Loading authorized companies…", "portal.companiesError": "We couldn't load the companies.", "portal.companiesEmpty": "Create the first company to start configuring its assistant.", "portal.companySelect": "Select company", "portal.companyNone": "No company selected",
  "profiles.title": "Assistant profiles", "profiles.description": "Configure how each company assistant presents itself and responds.", "profiles.companyRequired": "Select a company to view its profiles.", "profiles.create": "New profile", "profiles.createTitle": "Create Assistant Profile", "profiles.editTitle": "Edit Assistant Profile", "profiles.loading": "Loading profiles…", "profiles.loadError": "We couldn't load the profiles.", "profiles.emptyTitle": "No profiles yet", "profiles.emptyDescription": "Create the first profile to configure an assistant.", "profiles.listLabel": "Assistant Profiles", "profiles.notConfigured": "Not configured", "profiles.updatedAt": "Updated on {date}", "profiles.languageSelect": "Select a language", "profiles.validationRequired": "Enter a name and select the assistant language.", "profiles.validationFallback": "The fallback message cannot be empty.", "profiles.validationError": "Review the Profile details and try again.", "profiles.createSuccess": "The Profile was created successfully.", "profiles.updateSuccess": "The Profile was updated successfully.", "profiles.archiveSuccess": "The Profile was archived.", "profiles.transitionSuccess": "The Profile status was updated.", "profiles.createError": "We couldn't create the Profile.", "profiles.updateError": "We couldn't update the Profile.", "profiles.nameConflict": "A Profile with that name already exists in this company.", "profiles.updateConflict": "The Profile changed or its configuration is invalid for this status.", "profiles.transitionConflict": "The server did not allow the status change. Review the configuration and try again.", "profiles.transitionError": "We couldn't change the Profile status.", "profiles.transitioning": "Updating…", "profiles.readyWarning": "The local guide found fields you should complete before marking the Profile ready:", "profiles.archivedTitle": "Profile archived", "profiles.archivedDescription": "{profileName} is no longer in the active list. You can restore it now.", "profiles.archiveConfirmTitle": "Archive Profile", "profiles.archiveConfirm": "Are you sure you want to archive {profileName}?",
  "profiles.field.name": "Name", "profiles.field.description": "Description", "profiles.field.businessRole": "Business role", "profiles.field.objective": "Objective", "profiles.field.audience": "Audience", "profiles.field.tone": "Tone", "profiles.field.language": "Assistant language", "profiles.field.welcomeMessage": "Welcome message", "profiles.field.fallbackMessage": "Fallback message",
  "profiles.tone.professional": "Professional", "profiles.tone.friendly": "Friendly", "profiles.tone.concise": "Concise", "profiles.tone.empathetic": "Empathetic",
  "profiles.status.draft": "Draft", "profiles.status.ready": "Ready", "profiles.status.disabled": "Disabled", "profiles.status.archived": "Archived",
  "profiles.action.ready": "Mark ready", "profiles.action.draft": "Return to draft", "profiles.action.disable": "Disable", "profiles.action.archive": "Archive", "profiles.action.restore": "Restore to draft",
  "preview.title": "Assistant preview", "preview.context": "Testing {profileName} for {companyName}.", "preview.readyRequired": "Mark the Profile ready before previewing it.", "preview.messageLabel": "Test message", "preview.placeholder": "Enter a real customer question…", "preview.limit": "{count}/2000 characters", "preview.send": "Preview response", "preview.sending": "Sending…", "preview.responding": "The assistant is preparing a response…", "preview.answer": "Response", "preview.fallback": "Safe fallback response", "preview.profileUnavailable": "The Profile is no longer ready for preview.", "preview.companyUnavailable": "The company is not ready for preview yet.", "preview.knowledgeUnavailable": "The company does not have Knowledge available yet.", "preview.temporarilyUnavailable": "Preview is temporarily unavailable. Try again.", "preview.invalid": "Enter a valid message of up to 2000 characters.",
};

export const translations: Record<Locale, TranslationDictionary> = { es, en };
