export type Locale = "es" | "en";
export type Direction = "ltr" | "rtl";

export const localeMetadata: Record<Locale, { nativeName: string; direction: Direction }> = {
  es: { nativeName: "Español", direction: "ltr" },
  en: { nativeName: "English", direction: "ltr" },
};

export const translationKeys = [
  "app.brand", "app.portal", "app.title", "app.subtitle",
  "language.label", "language.es", "language.en",
  "common.cancel", "common.close", "common.save", "common.saving", "common.edit", "common.delete", "common.retry", "common.loading", "common.optional", "common.confirm", "common.back",
  "companies.title", "companies.create", "companies.createTitle", "companies.createSuccess", "companies.emptyTitle", "companies.emptyDescription", "companies.loadError", "companies.selectPrompt", "companies.mobileSelector", "companies.unknownWebsite",
  "companies.fields.name", "companies.fields.website", "companies.fields.phone", "companies.fields.email", "companies.fields.createdAt",
  "companies.placeholders.name", "companies.placeholders.website", "companies.placeholders.phone", "companies.placeholders.email",
  "companies.validation.name", "companies.validation.website", "companies.operationError", "companies.updateSuccess", "companies.deleteTitle", "companies.deletePrompt", "companies.deleteSuccess", "companies.deleteError",
  "status.processing", "status.ready", "status.failed", "status.unknown",
  "workspace.contactMissing", "workspace.websiteLink", "workspace.editTitle",
  "onboarding.title", "onboarding.description", "onboarding.websiteHelp", "onboarding.start", "onboarding.retry", "onboarding.processingTitle", "onboarding.processingDescription", "onboarding.success", "onboarding.error", "onboarding.invalidUrl", "onboarding.readyDescription", "onboarding.focusChat",
  "chat.title", "chat.context", "chat.languageNote", "chat.emptyTitle", "chat.emptyDescription", "chat.placeholder", "chat.send", "chat.sending", "chat.responding", "chat.user", "chat.atlas", "chat.system", "chat.unavailableProcessing", "chat.unavailableFailed", "chat.error", "chat.missingKnowledge", "chat.retry", "chat.clearOnSwitch",
  "states.loadingCompanies", "states.loadingCompany", "states.errorTitle", "states.successTitle",
  "accessibility.mainContent", "accessibility.companyNavigation", "accessibility.openCompanies", "accessibility.closeCompanies", "accessibility.externalLink", "accessibility.processing", "accessibility.ready", "accessibility.failed",
] as const;

export type TranslationKey = typeof translationKeys[number];
export type TranslationDictionary = Record<TranslationKey, string>;

const es: TranslationDictionary = {
  "app.brand": "ATLAS", "app.portal": "Portal", "app.title": "Atlas Portal", "app.subtitle": "Gestioná empresas y probá su asistente desde un solo lugar.",
  "language.label": "Idioma del portal", "language.es": "Español", "language.en": "English",
  "common.cancel": "Cancelar", "common.close": "Cerrar", "common.save": "Guardar", "common.saving": "Guardando…", "common.edit": "Editar", "common.delete": "Eliminar", "common.retry": "Intentar de nuevo", "common.loading": "Cargando…", "common.optional": "Opcional", "common.confirm": "Confirmar", "common.back": "Volver",
  "companies.title": "Empresas", "companies.create": "Nueva empresa", "companies.createTitle": "Crear empresa", "companies.createSuccess": "La empresa se creó correctamente.", "companies.emptyTitle": "Todavía no hay empresas", "companies.emptyDescription": "Creá la primera empresa para comenzar a preparar su asistente.", "companies.loadError": "No pudimos cargar las empresas.", "companies.selectPrompt": "Seleccioná una empresa para continuar.", "companies.mobileSelector": "Cambiar empresa", "companies.unknownWebsite": "Sitio sin definir",
  "companies.fields.name": "Nombre", "companies.fields.website": "Sitio web", "companies.fields.phone": "Teléfono", "companies.fields.email": "Correo electrónico", "companies.fields.createdAt": "Creada el",
  "companies.placeholders.name": "Empresa Ejemplo", "companies.placeholders.website": "https://empresa.example", "companies.placeholders.phone": "+54 11 0000 0000", "companies.placeholders.email": "contacto@empresa.example",
  "companies.validation.name": "Ingresá un nombre para la empresa.", "companies.validation.website": "Ingresá una URL válida que comience con http:// o https://.", "companies.operationError": "No pudimos guardar la empresa. Revisá los datos e intentá nuevamente.", "companies.updateSuccess": "Los datos de la empresa se actualizaron.", "companies.deleteTitle": "Eliminar empresa", "companies.deletePrompt": "¿Confirmás que querés eliminar {companyName}? También se eliminará su conocimiento guardado.", "companies.deleteSuccess": "La empresa se eliminó correctamente.", "companies.deleteError": "No pudimos eliminar la empresa.",
  "status.processing": "Procesando", "status.ready": "Lista", "status.failed": "Con errores", "status.unknown": "Estado desconocido",
  "workspace.contactMissing": "Sin datos", "workspace.websiteLink": "Abrir sitio web", "workspace.editTitle": "Editar empresa",
  "onboarding.title": "Incorporación", "onboarding.description": "Atlas analizará el sitio y preparará el conocimiento que usará el asistente.", "onboarding.websiteHelp": "Si cambiás la URL, se actualizará el sitio de esta misma empresa.", "onboarding.start": "Iniciar incorporación", "onboarding.retry": "Reintentar incorporación", "onboarding.processingTitle": "Preparando el conocimiento", "onboarding.processingDescription": "Estamos analizando el sitio y preparando el conocimiento de la empresa. Esto puede demorar unos minutos.", "onboarding.success": "La empresa está lista para probar el chat.", "onboarding.error": "No pudimos completar la incorporación. Los datos de la empresa siguen disponibles.", "onboarding.invalidUrl": "Ingresá una URL válida que comience con http:// o https://.", "onboarding.readyDescription": "El conocimiento está disponible. Podés repetir la incorporación para actualizarlo.", "onboarding.focusChat": "Probar el chat",
  "chat.title": "Chat de prueba", "chat.context": "Probando respuestas para {companyName}", "chat.languageNote": "El asistente responde según el idioma del mensaje del cliente. El idioma del portal no modifica sus respuestas.", "chat.emptyTitle": "Probá el asistente", "chat.emptyDescription": "Escribí una pregunta real que haría un cliente de esta empresa.", "chat.placeholder": "Escribí un mensaje…", "chat.send": "Enviar", "chat.sending": "Enviando…", "chat.responding": "Atlas está respondiendo…", "chat.user": "Vos", "chat.atlas": "Atlas", "chat.system": "Sistema", "chat.unavailableProcessing": "El chat estará disponible cuando termine la incorporación.", "chat.unavailableFailed": "Reintentá la incorporación antes de probar el chat.", "chat.error": "No pudimos obtener una respuesta. Intentá nuevamente.", "chat.missingKnowledge": "La empresa todavía no tiene conocimiento disponible.", "chat.retry": "Reenviar mensaje", "chat.clearOnSwitch": "La conversación se reinicia al cambiar de empresa.",
  "states.loadingCompanies": "Cargando empresas…", "states.loadingCompany": "Cargando empresa…", "states.errorTitle": "Algo salió mal", "states.successTitle": "Operación completada",
  "accessibility.mainContent": "Contenido principal", "accessibility.companyNavigation": "Navegación de empresas", "accessibility.openCompanies": "Abrir selector de empresas", "accessibility.closeCompanies": "Cerrar selector de empresas", "accessibility.externalLink": "Abre en una pestaña nueva", "accessibility.processing": "Estado: procesando", "accessibility.ready": "Estado: lista", "accessibility.failed": "Estado: con errores",
};

const en: TranslationDictionary = {
  "app.brand": "ATLAS", "app.portal": "Portal", "app.title": "Atlas Portal", "app.subtitle": "Manage companies and test their assistant in one place.",
  "language.label": "Portal language", "language.es": "Español", "language.en": "English",
  "common.cancel": "Cancel", "common.close": "Close", "common.save": "Save", "common.saving": "Saving…", "common.edit": "Edit", "common.delete": "Delete", "common.retry": "Try again", "common.loading": "Loading…", "common.optional": "Optional", "common.confirm": "Confirm", "common.back": "Back",
  "companies.title": "Companies", "companies.create": "New company", "companies.createTitle": "Create company", "companies.createSuccess": "The company was created successfully.", "companies.emptyTitle": "No companies yet", "companies.emptyDescription": "Create the first company to start preparing its assistant.", "companies.loadError": "We couldn't load the companies.", "companies.selectPrompt": "Select a company to continue.", "companies.mobileSelector": "Change company", "companies.unknownWebsite": "Website not defined",
  "companies.fields.name": "Name", "companies.fields.website": "Website", "companies.fields.phone": "Phone", "companies.fields.email": "Email", "companies.fields.createdAt": "Created on",
  "companies.placeholders.name": "Example Company", "companies.placeholders.website": "https://company.example", "companies.placeholders.phone": "+1 555 000 0000", "companies.placeholders.email": "contact@company.example",
  "companies.validation.name": "Enter a company name.", "companies.validation.website": "Enter a valid URL beginning with http:// or https://.", "companies.operationError": "We couldn't save the company. Review the details and try again.", "companies.updateSuccess": "The company details were updated.", "companies.deleteTitle": "Delete company", "companies.deletePrompt": "Are you sure you want to delete {companyName}? Its stored knowledge will also be deleted.", "companies.deleteSuccess": "The company was deleted successfully.", "companies.deleteError": "We couldn't delete the company.",
  "status.processing": "Processing", "status.ready": "Ready", "status.failed": "Failed", "status.unknown": "Unknown status",
  "workspace.contactMissing": "Not provided", "workspace.websiteLink": "Open website", "workspace.editTitle": "Edit company",
  "onboarding.title": "Onboarding", "onboarding.description": "Atlas will analyze the website and prepare the knowledge used by the assistant.", "onboarding.websiteHelp": "Changing the URL will update the website for this same company.", "onboarding.start": "Start onboarding", "onboarding.retry": "Retry onboarding", "onboarding.processingTitle": "Preparing company knowledge", "onboarding.processingDescription": "We're analyzing the website and preparing company knowledge. This may take a few minutes.", "onboarding.success": "The company is ready to test in chat.", "onboarding.error": "We couldn't complete onboarding. The company details remain available.", "onboarding.invalidUrl": "Enter a valid URL beginning with http:// or https://.", "onboarding.readyDescription": "Knowledge is available. You can run onboarding again to refresh it.", "onboarding.focusChat": "Test the chat",
  "chat.title": "Test chat", "chat.context": "Testing responses for {companyName}", "chat.languageNote": "The assistant responds in the customer's message language. The portal language does not change its responses.", "chat.emptyTitle": "Test the assistant", "chat.emptyDescription": "Enter a real question a customer might ask this company.", "chat.placeholder": "Write a message…", "chat.send": "Send", "chat.sending": "Sending…", "chat.responding": "Atlas is responding…", "chat.user": "You", "chat.atlas": "Atlas", "chat.system": "System", "chat.unavailableProcessing": "Chat will be available when onboarding is complete.", "chat.unavailableFailed": "Retry onboarding before testing the chat.", "chat.error": "We couldn't get a response. Try again.", "chat.missingKnowledge": "This company does not have knowledge available yet.", "chat.retry": "Send message again", "chat.clearOnSwitch": "The conversation resets when you switch companies.",
  "states.loadingCompanies": "Loading companies…", "states.loadingCompany": "Loading company…", "states.errorTitle": "Something went wrong", "states.successTitle": "Operation completed",
  "accessibility.mainContent": "Main content", "accessibility.companyNavigation": "Company navigation", "accessibility.openCompanies": "Open company selector", "accessibility.closeCompanies": "Close company selector", "accessibility.externalLink": "Opens in a new tab", "accessibility.processing": "Status: processing", "accessibility.ready": "Status: ready", "accessibility.failed": "Status: failed",
};

export const translations: Record<Locale, TranslationDictionary> = { es, en };
